/**
 * Expanded diagram templates based on GCSE/A-Level exam board research
 * Adds 50+ new diagram types commonly found in past papers
 */

import { DiagramSpec } from '@/types/diagram';
import { DiagramTemplate } from './diagramTemplates';

/**
 * ADDITIONAL MATHEMATICS DIAGRAM TEMPLATES
 * Based on AQA, Edexcel, OCR specifications
 */
export const MATHS_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  // Function graphs
  {
    id: 'maths-quadratic-graph',
    subject: 'maths',
    type: 'quadratic-graph',
    name: 'Quadratic Graph',
    description: 'Parabola with vertex, roots, and axis of symmetry',
    requiredElements: ['parabola', 'vertex', 'axis-of-symmetry'],
    optionalElements: ['roots', 'y-intercept', 'turning-point'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Quadratic Graph',
      elements: [{
        type: 'function-graph',
        functionType: 'quadratic',
        equation: params?.equation || 'y = x² - 4x + 3',
        xRange: [-2, 6],
        yRange: [-2, 10],
        showVertex: true,
        showRoots: true,
        showAxisOfSymmetry: true,
      }],
    }),
  },
  {
    id: 'maths-cubic-graph',
    subject: 'maths',
    type: 'cubic-graph',
    name: 'Cubic Graph',
    description: 'Cubic function with turning points',
    requiredElements: ['curve', 'turning-points'],
    optionalElements: ['inflection-point', 'roots'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Cubic Graph',
      elements: [{
        type: 'function-graph',
        functionType: 'cubic',
        equation: params?.equation || 'y = x³ - 3x',
        xRange: [-3, 3],
        yRange: [-10, 10],
        showTurningPoints: true,
      }],
    }),
  },
  {
    id: 'maths-reciprocal-graph',
    subject: 'maths',
    type: 'reciprocal-graph',
    name: 'Reciprocal Graph',
    description: 'Hyperbola y = 1/x with asymptotes',
    requiredElements: ['hyperbola', 'asymptotes'],
    optionalElements: ['quadrants'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Reciprocal Graph',
      elements: [{
        type: 'reciprocal-graph',
        equation: params?.equation || 'y = 1/x',
        xRange: [-5, 5],
        yRange: [-5, 5],
        showAsymptotes: true,
      }],
    }),
  },
  {
    id: 'maths-exponential-graph',
    subject: 'maths',
    type: 'exponential-graph',
    name: 'Exponential Graph',
    description: 'Exponential growth/decay curve',
    requiredElements: ['curve', 'asymptote'],
    optionalElements: ['y-intercept', 'growth-rate'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Exponential Graph',
      elements: [{
        type: 'exponential-graph',
        base: params?.base || 2,
        equation: params?.equation || 'y = 2^x',
        xRange: [-3, 3],
        yRange: [0, 10],
        showAsymptote: true,
      }],
    }),
  },
  {
    id: 'maths-trigonometric-graph',
    subject: 'maths',
    type: 'trigonometric-graph',
    name: 'Trigonometric Graph',
    description: 'Sin, cos, or tan curves with period and amplitude',
    requiredElements: ['sine-cosine-tan', 'period', 'amplitude'],
    optionalElements: ['phase-shift', 'vertical-shift'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Trigonometric Graph',
      elements: [{
        type: 'trig-graph',
        functions: params?.functions || ['sin', 'cos'],
        xRange: [0, 720], // degrees
        amplitude: params?.amplitude || 1,
        period: params?.period || 360,
        showPeriodMarkers: true,
      }],
    }),
  },
  
  // Statistics diagrams
  {
    id: 'maths-histogram',
    subject: 'maths',
    type: 'histogram',
    name: 'Histogram',
    description: 'Frequency density with unequal class widths',
    requiredElements: ['bars', 'frequency-density', 'class-widths'],
    optionalElements: ['modal-class'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 350,
      title: 'Histogram',
      elements: [{
        type: 'histogram',
        data: params?.data || [
          { classStart: 0, classEnd: 10, frequency: 8 },
          { classStart: 10, classEnd: 25, frequency: 15 },
          { classStart: 25, classEnd: 40, frequency: 12 },
          { classStart: 40, classEnd: 60, frequency: 10 },
        ],
        xLabel: 'Value',
        yLabel: 'Frequency Density',
      }],
    }),
  },
  {
    id: 'maths-box-plot',
    subject: 'maths',
    type: 'box-plot',
    name: 'Box Plot',
    description: 'Box and whisker diagram showing quartiles',
    requiredElements: ['box', 'whiskers', 'median', 'quartiles'],
    optionalElements: ['outliers', 'mean'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 200,
      title: 'Box Plot',
      elements: [{
        type: 'box-plot',
        min: params?.min || 10,
        q1: params?.q1 || 25,
        median: params?.median || 40,
        q3: params?.q3 || 55,
        max: params?.max || 75,
        outliers: params?.outliers || [],
      }],
    }),
  },
  {
    id: 'maths-scatter-graph',
    subject: 'maths',
    type: 'scatter-graph',
    name: 'Scatter Graph',
    description: 'Scatter plot with line of best fit',
    requiredElements: ['points', 'line-of-best-fit'],
    optionalElements: ['correlation-type', 'outliers'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Scatter Graph',
      elements: [{
        type: 'scatter-plot',
        points: params?.points || [
          { x: 1, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 5 },
          { x: 4, y: 4 }, { x: 5, y: 7 }, { x: 6, y: 8 },
        ],
        showLineOfBestFit: true,
        xLabel: params?.xLabel || 'x',
        yLabel: params?.yLabel || 'y',
      }],
    }),
  },
  {
    id: 'maths-cumulative-frequency',
    subject: 'maths',
    type: 'cumulative-frequency',
    name: 'Cumulative Frequency',
    description: 'Ogive with median and quartile lines',
    requiredElements: ['ogive', 'median-line', 'quartile-lines'],
    optionalElements: ['percentiles'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Cumulative Frequency Graph',
      elements: [{
        type: 'cumulative-frequency',
        data: params?.data || [
          { value: 10, cumFreq: 5 },
          { value: 20, cumFreq: 15 },
          { value: 30, cumFreq: 35 },
          { value: 40, cumFreq: 55 },
          { value: 50, cumFreq: 70 },
        ],
        showMedian: true,
        showQuartiles: true,
      }],
    }),
  },
  {
    id: 'maths-pie-chart',
    subject: 'maths',
    type: 'pie-chart',
    name: 'Pie Chart',
    description: 'Circular chart with sectors and angles',
    requiredElements: ['sectors', 'angles', 'labels'],
    optionalElements: ['percentages', 'legend'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Pie Chart',
      elements: [{
        type: 'pie-chart',
        data: params?.data || [
          { label: 'A', value: 30, angle: 108 },
          { label: 'B', value: 25, angle: 90 },
          { label: 'C', value: 20, angle: 72 },
          { label: 'D', value: 25, angle: 90 },
        ],
        radius: 150,
        showAngles: true,
      }],
    }),
  },
  {
    id: 'maths-stem-leaf',
    subject: 'maths',
    type: 'stem-leaf',
    name: 'Stem and Leaf Diagram',
    description: 'Data display with stem and leaves',
    requiredElements: ['stem', 'leaves', 'key'],
    optionalElements: ['back-to-back'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 300,
      height: 250,
      title: 'Stem and Leaf Diagram',
      elements: [{
        type: 'stem-leaf',
        data: params?.data || {
          '1': [2, 3, 5, 8],
          '2': [1, 3, 3, 6, 9],
          '3': [0, 2, 5],
          '4': [1, 3],
        },
        key: '2|3 means 23',
      }],
    }),
  },
  {
    id: 'maths-frequency-polygon',
    subject: 'maths',
    type: 'frequency-polygon',
    name: 'Frequency Polygon',
    description: 'Line graph joining midpoints of class intervals',
    requiredElements: ['polygon-line', 'midpoints', 'axes'],
    optionalElements: ['area-under-curve'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Frequency Polygon',
      elements: [{
        type: 'frequency-polygon',
        data: params?.data || [
          { midpoint: 5, frequency: 2 },
          { midpoint: 15, frequency: 8 },
          { midpoint: 25, frequency: 12 },
          { midpoint: 35, frequency: 6 },
          { midpoint: 45, frequency: 3 },
        ],
        xLabel: 'Value',
        yLabel: 'Frequency',
      }],
    }),
  },
  
  // Real-life graphs
  {
    id: 'maths-distance-time',
    subject: 'maths',
    type: 'distance-time',
    name: 'Distance-Time Graph',
    description: 'Graph showing journey with different speeds',
    requiredElements: ['journey-sections', 'stationary-periods'],
    optionalElements: ['speed-annotations'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Distance-Time Graph',
      elements: [{
        type: 'line-graph',
        points: params?.points || [
          { x: 0, y: 0 },
          { x: 2, y: 10 },
          { x: 3, y: 10 },
          { x: 5, y: 25 },
          { x: 7, y: 25 },
        ],
        xLabel: 'Time (hours)',
        yLabel: 'Distance (km)',
        annotations: params?.annotations || [],
      }],
    }),
  },
  {
    id: 'maths-speed-time',
    subject: 'maths',
    type: 'speed-time',
    name: 'Speed-Time Graph',
    description: 'Graph showing acceleration and deceleration',
    requiredElements: ['speed-sections', 'acceleration'],
    optionalElements: ['area-under-graph'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Speed-Time Graph',
      elements: [{
        type: 'line-graph',
        points: params?.points || [
          { x: 0, y: 0 },
          { x: 10, y: 20 },
          { x: 30, y: 20 },
          { x: 40, y: 0 },
        ],
        xLabel: 'Time (s)',
        yLabel: 'Speed (m/s)',
        showArea: true,
      }],
    }),
  },
  {
    id: 'maths-water-flow',
    subject: 'maths',
    type: 'water-flow',
    name: 'Water Flow Graph',
    description: 'Graph of depth vs time for container filling',
    requiredElements: ['depth-curve', 'container-shape'],
    optionalElements: ['rate-of-change'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Water Flow Graph',
      elements: [{
        type: 'curve-graph',
        curveType: params?.curveType || 'exponential',
        xLabel: 'Time (minutes)',
        yLabel: 'Depth (cm)',
        containerShape: params?.shape || 'cylinder',
      }],
    }),
  },
  
  // Geometry and transformations
  {
    id: 'maths-transformation',
    subject: 'maths',
    type: 'transformation',
    name: 'Transformation',
    description: 'Reflection, rotation, translation, or enlargement',
    requiredElements: ['original-shape', 'transformed-shape', 'transformation-type'],
    optionalElements: ['center-of-rotation', 'mirror-line', 'vector'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Transformation',
      elements: [{
        type: 'transformation',
        originalShape: params?.originalShape || [
          { x: 50, y: 50 },
          { x: 100, y: 50 },
          { x: 100, y: 100 },
          { x: 50, y: 100 },
        ],
        transformationType: params?.type || 'reflection',
        transformationLine: params?.line || 'x-axis',
        showOriginal: true,
        showTransformed: true,
      }],
    }),
  },
  {
    id: 'maths-vector',
    subject: 'maths',
    type: 'vector',
    name: 'Vector Diagram',
    description: 'Vectors with addition and resultant',
    requiredElements: ['vectors', 'components', 'resultant'],
    optionalElements: ['parallelogram-rule'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Vector Diagram',
      elements: [{
        type: 'vector-diagram',
        vectors: params?.vectors || [
          { start: { x: 100, y: 200 }, end: { x: 200, y: 150 }, label: 'a' },
          { start: { x: 200, y: 150 }, end: { x: 250, y: 250 }, label: 'b' },
        ],
        showResultant: true,
        showComponents: params?.showComponents || false,
      }],
    }),
  },
  {
    id: 'maths-locus',
    subject: 'maths',
    type: 'locus',
    name: 'Locus',
    description: 'Path of points following a rule',
    requiredElements: ['path', 'constraints', 'fixed-points'],
    optionalElements: ['construction-arcs'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Locus',
      elements: [{
        type: 'locus',
        locusType: params?.type || 'circle',
        fixedPoints: params?.points || [
          { x: 200, y: 200, label: 'A' },
        ],
        radius: params?.radius || 100,
      }],
    }),
  },
  {
    id: 'maths-construction',
    subject: 'maths',
    type: 'construction',
    name: 'Geometric Construction',
    description: 'Compass and straightedge construction',
    requiredElements: ['construction-arcs', 'construction-lines'],
    optionalElements: ['angle-bisector', 'perpendicular-bisector'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Geometric Construction',
      elements: [{
        type: 'construction',
        constructionType: params?.type || 'perpendicular-bisector',
        basePoints: params?.points || [
          { x: 100, y: 200 },
          { x: 300, y: 200 },
        ],
        showArcs: true,
        showConstructionLines: true,
      }],
    }),
  },
  {
    id: 'maths-angle-diagram',
    subject: 'maths',
    type: 'angle-diagram',
    name: 'Angle Diagram',
    description: 'Angles at a point, on a line, or in polygons',
    requiredElements: ['angles', 'angle-marks', 'angle-values'],
    optionalElements: ['parallel-marks', 'perpendicular-marks'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Angle Diagram',
      elements: [{
        type: 'angle-diagram',
        angleType: params?.type || 'angles-at-point',
        angles: params?.angles || [30, 60, 90, 180],
        showValues: true,
        showArcs: true,
      }],
    }),
  },
  {
    id: 'maths-circle-theorems',
    subject: 'maths',
    type: 'circle-theorems',
    name: 'Circle Theorems',
    description: 'Circle with chords, tangents, and angles',
    requiredElements: ['circle', 'chords', 'angles'],
    optionalElements: ['tangent', 'cyclic-quadrilateral'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Circle Theorems',
      elements: [{
        type: 'circle-theorem',
        theoremType: params?.type || 'angle-at-center',
        showConstruction: true,
        showAngles: true,
      }],
    }),
  },
  {
    id: 'maths-quadrilateral',
    subject: 'maths',
    type: 'quadrilateral',
    name: 'Quadrilateral',
    description: 'Square, rectangle, rhombus, parallelogram, trapezium',
    requiredElements: ['vertices', 'sides', 'angles'],
    optionalElements: ['diagonals', 'symmetry-lines'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Quadrilateral',
      elements: [{
        type: 'quadrilateral',
        quadType: params?.type || 'parallelogram',
        showAngles: true,
        showSides: true,
        showDiagonals: params?.showDiagonals || false,
      }],
    }),
  },
  {
    id: 'maths-polygon',
    subject: 'maths',
    type: 'polygon',
    name: 'Regular Polygon',
    description: 'Pentagon, hexagon, octagon etc.',
    requiredElements: ['vertices', 'sides', 'center'],
    optionalElements: ['interior-angles', 'exterior-angles'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Regular Polygon',
      elements: [{
        type: 'regular-polygon',
        sides: params?.sides || 6,
        radius: 150,
        showAngles: params?.showAngles || false,
        showCenter: true,
      }],
    }),
  },
  {
    id: 'maths-net',
    subject: 'maths',
    type: 'net',
    name: '3D Shape Net',
    description: '2D net that folds into 3D shape',
    requiredElements: ['faces', 'fold-lines', 'tabs'],
    optionalElements: ['measurements'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: '3D Shape Net',
      elements: [{
        type: 'net',
        shapeType: params?.shape || 'cube',
        showFoldLines: true,
        showTabs: true,
        showMeasurements: params?.showMeasurements || false,
      }],
    }),
  },
  {
    id: 'maths-plan-elevation',
    subject: 'maths',
    type: 'plan-elevation',
    name: 'Plan and Elevation',
    description: 'Front, side, and plan views of 3D shape',
    requiredElements: ['front-view', 'side-view', 'plan-view'],
    optionalElements: ['isometric-view'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 600,
      height: 400,
      title: 'Plan and Elevation',
      elements: [{
        type: 'plan-elevation',
        shape: params?.shape || 'cuboid',
        showFront: true,
        showSide: true,
        showPlan: true,
        showIsometric: params?.showIsometric || false,
      }],
    }),
  },
  {
    id: 'maths-number-line',
    subject: 'maths',
    type: 'number-line',
    name: 'Number Line',
    description: 'Number line with inequalities or intervals',
    requiredElements: ['line', 'scale', 'markers'],
    optionalElements: ['inequalities', 'intervals'],
    complexity: 1,
    generateSpec: (params) => ({
      width: 500,
      height: 100,
      title: 'Number Line',
      elements: [{
        type: 'number-line',
        range: params?.range || [-10, 10],
        markings: params?.markings || 1,
        highlights: params?.highlights || [],
        inequalities: params?.inequalities || [],
      }],
    }),
  },
];

/**
 * ADDITIONAL PHYSICS DIAGRAM TEMPLATES
 */
export const PHYSICS_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  // Mechanics
  {
    id: 'physics-free-body',
    subject: 'physics',
    type: 'free-body',
    name: 'Free Body Diagram',
    description: 'Object with all forces acting on it',
    requiredElements: ['object', 'force-arrows', 'labels'],
    optionalElements: ['angles', 'components'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Free Body Diagram',
      elements: [{
        type: 'free-body',
        object: params?.object || 'block',
        forces: params?.forces || [
          { direction: 90, magnitude: 10, label: 'Weight' },
          { direction: 270, magnitude: 10, label: 'Normal' },
        ],
        showComponents: params?.showComponents || false,
      }],
    }),
  },
  {
    id: 'physics-pendulum',
    subject: 'physics',
    type: 'pendulum',
    name: 'Pendulum',
    description: 'Simple pendulum with forces and angles',
    requiredElements: ['pivot', 'string', 'bob', 'angle'],
    optionalElements: ['forces', 'path'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Pendulum',
      elements: [{
        type: 'pendulum',
        angle: params?.angle || 30,
        length: params?.length || 200,
        showForces: params?.showForces || false,
        showPath: true,
      }],
    }),
  },
  {
    id: 'physics-spring',
    subject: 'physics',
    type: 'spring',
    name: 'Spring System',
    description: 'Mass-spring system with extension',
    requiredElements: ['spring', 'mass', 'extension'],
    optionalElements: ['equilibrium-position', 'forces'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 300,
      height: 400,
      title: 'Spring System',
      elements: [{
        type: 'spring',
        extension: params?.extension || 50,
        mass: params?.mass || 100,
        showForces: true,
        showMeasurements: true,
      }],
    }),
  },
  {
    id: 'physics-pulley',
    subject: 'physics',
    type: 'pulley',
    name: 'Pulley System',
    description: 'Pulley with masses and tensions',
    requiredElements: ['pulley', 'rope', 'masses'],
    optionalElements: ['tensions', 'accelerations'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 500,
      title: 'Pulley System',
      elements: [{
        type: 'pulley',
        masses: params?.masses || [100, 150],
        showTensions: true,
        showAccelerations: params?.moving || false,
      }],
    }),
  },
  {
    id: 'physics-inclined-plane',
    subject: 'physics',
    type: 'inclined-plane',
    name: 'Inclined Plane',
    description: 'Object on slope with force components',
    requiredElements: ['slope', 'object', 'angle'],
    optionalElements: ['force-components', 'friction'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Inclined Plane',
      elements: [{
        type: 'inclined-plane',
        angle: params?.angle || 30,
        showForces: true,
        showComponents: true,
        friction: params?.friction || false,
      }],
    }),
  },
  
  // Waves and optics
  {
    id: 'physics-transverse-wave',
    subject: 'physics',
    type: 'transverse-wave',
    name: 'Transverse Wave',
    description: 'Wave with amplitude and wavelength labeled',
    requiredElements: ['wave', 'amplitude', 'wavelength'],
    optionalElements: ['period', 'frequency'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Transverse Wave',
      elements: [{
        type: 'transverse-wave',
        amplitude: params?.amplitude || 50,
        wavelength: params?.wavelength || 100,
        cycles: params?.cycles || 2,
        showLabels: true,
      }],
    }),
  },
  {
    id: 'physics-longitudinal-wave',
    subject: 'physics',
    type: 'longitudinal-wave',
    name: 'Longitudinal Wave',
    description: 'Compressions and rarefactions',
    requiredElements: ['compressions', 'rarefactions', 'wavelength'],
    optionalElements: ['particles'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 200,
      title: 'Longitudinal Wave',
      elements: [{
        type: 'longitudinal-wave',
        compressions: params?.compressions || 3,
        showParticles: true,
        showLabels: true,
      }],
    }),
  },
  {
    id: 'physics-wave-fronts',
    subject: 'physics',
    type: 'wave-fronts',
    name: 'Wave Fronts',
    description: 'Circular or plane wave fronts',
    requiredElements: ['wave-fronts', 'source', 'direction'],
    optionalElements: ['barrier', 'gap'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Wave Fronts',
      elements: [{
        type: 'wave-fronts',
        frontType: params?.type || 'circular',
        source: { x: 200, y: 200 },
        showDirection: true,
      }],
    }),
  },
  {
    id: 'physics-refraction',
    subject: 'physics',
    type: 'refraction',
    name: 'Refraction Diagram',
    description: 'Light ray bending at boundary',
    requiredElements: ['incident-ray', 'refracted-ray', 'normal', 'boundary'],
    optionalElements: ['angles', 'refractive-indices'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Refraction',
      elements: [{
        type: 'refraction',
        incidentAngle: params?.incidentAngle || 45,
        n1: params?.n1 || 1.0,
        n2: params?.n2 || 1.5,
        showAngles: true,
        showNormal: true,
      }],
    }),
  },
  {
    id: 'physics-total-internal-reflection',
    subject: 'physics',
    type: 'total-internal-reflection',
    name: 'Total Internal Reflection',
    description: 'Critical angle and total internal reflection',
    requiredElements: ['critical-angle', 'reflected-ray', 'boundary'],
    optionalElements: ['multiple-rays'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Total Internal Reflection',
      elements: [{
        type: 'total-internal-reflection',
        criticalAngle: params?.criticalAngle || 42,
        showMultipleRays: true,
        showAngles: true,
      }],
    }),
  },
  {
    id: 'physics-convex-lens',
    subject: 'physics',
    type: 'convex-lens',
    name: 'Convex Lens Ray Diagram',
    description: 'Converging lens with object and image',
    requiredElements: ['lens', 'object', 'image', 'principal-rays'],
    optionalElements: ['focal-points', 'magnification'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Convex Lens',
      elements: [{
        type: 'convex-lens',
        objectDistance: params?.objectDistance || 150,
        focalLength: params?.focalLength || 75,
        showRays: true,
        showImage: true,
      }],
    }),
  },
  {
    id: 'physics-concave-lens',
    subject: 'physics',
    type: 'concave-lens',
    name: 'Concave Lens Ray Diagram',
    description: 'Diverging lens with virtual image',
    requiredElements: ['lens', 'object', 'virtual-image', 'diverging-rays'],
    optionalElements: ['focal-points'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Concave Lens',
      elements: [{
        type: 'concave-lens',
        objectDistance: params?.objectDistance || 150,
        focalLength: params?.focalLength || 75,
        showRays: true,
        showVirtualImage: true,
      }],
    }),
  },
  {
    id: 'physics-plane-mirror',
    subject: 'physics',
    type: 'plane-mirror',
    name: 'Plane Mirror',
    description: 'Reflection in plane mirror with virtual image',
    requiredElements: ['mirror', 'object', 'virtual-image', 'rays'],
    optionalElements: ['angles'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Plane Mirror',
      elements: [{
        type: 'plane-mirror',
        objectPosition: params?.position || { x: 100, y: 150 },
        showVirtualImage: true,
        showRays: true,
      }],
    }),
  },
  
  // Electricity
  {
    id: 'physics-series-circuit',
    subject: 'physics',
    type: 'series-circuit',
    name: 'Series Circuit',
    description: 'Components connected in series',
    requiredElements: ['battery', 'resistors', 'ammeter'],
    optionalElements: ['voltmeter', 'switch'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Series Circuit',
      elements: [{
        type: 'series-circuit',
        components: params?.components || ['battery', 'resistor', 'resistor', 'ammeter'],
        showValues: true,
      }],
    }),
  },
  {
    id: 'physics-parallel-circuit',
    subject: 'physics',
    type: 'parallel-circuit',
    name: 'Parallel Circuit',
    description: 'Components connected in parallel',
    requiredElements: ['battery', 'branches', 'resistors'],
    optionalElements: ['ammeters', 'voltmeters'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 350,
      title: 'Parallel Circuit',
      elements: [{
        type: 'parallel-circuit',
        branches: params?.branches || 2,
        componentsPerBranch: params?.componentsPerBranch || ['resistor', 'bulb'],
        showCurrentFlow: true,
      }],
    }),
  },
  {
    id: 'physics-potential-divider',
    subject: 'physics',
    type: 'potential-divider',
    name: 'Potential Divider',
    description: 'Voltage divider circuit',
    requiredElements: ['supply', 'resistors', 'output-voltage'],
    optionalElements: ['calculations'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Potential Divider',
      elements: [{
        type: 'potential-divider',
        r1: params?.r1 || 100,
        r2: params?.r2 || 200,
        supplyVoltage: params?.voltage || 12,
        showCalculations: true,
      }],
    }),
  },
  
  // Thermal physics
  {
    id: 'physics-particle-model',
    subject: 'physics',
    type: 'particle-model',
    name: 'Particle Model',
    description: 'Particles in solid, liquid, or gas',
    requiredElements: ['particles', 'container', 'state-label'],
    optionalElements: ['particle-motion', 'forces'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Particle Model',
      elements: [{
        type: 'particle-model',
        state: params?.state || 'solid',
        showMotion: params?.showMotion || false,
        showForces: params?.showForces || false,
      }],
    }),
  },
  {
    id: 'physics-heating-curve',
    subject: 'physics',
    type: 'heating-curve',
    name: 'Heating Curve',
    description: 'Temperature vs time with phase changes',
    requiredElements: ['curve', 'phase-changes', 'plateaus'],
    optionalElements: ['state-labels'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 450,
      height: 350,
      title: 'Heating Curve',
      elements: [{
        type: 'heating-curve',
        substance: params?.substance || 'water',
        showPhaseChanges: true,
        showStateLabels: true,
      }],
    }),
  },
  
  // Nuclear physics
  {
    id: 'physics-radioactive-decay',
    subject: 'physics',
    type: 'radioactive-decay',
    name: 'Radioactive Decay',
    description: 'Alpha, beta, or gamma decay diagram',
    requiredElements: ['nucleus', 'emission', 'products'],
    optionalElements: ['equation'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Radioactive Decay',
      elements: [{
        type: 'radioactive-decay',
        decayType: params?.type || 'alpha',
        showEquation: true,
        showParticles: true,
      }],
    }),
  },
  {
    id: 'physics-half-life',
    subject: 'physics',
    type: 'half-life',
    name: 'Half-Life Graph',
    description: 'Exponential decay curve',
    requiredElements: ['decay-curve', 'half-life-markers'],
    optionalElements: ['activity-values'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Half-Life Graph',
      elements: [{
        type: 'half-life',
        halfLife: params?.halfLife || 5,
        initialActivity: params?.initialActivity || 1000,
        showHalfLifeLines: true,
      }],
    }),
  },
];

/**
 * ADDITIONAL CHEMISTRY DIAGRAM TEMPLATES
 */
export const CHEMISTRY_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  // Atomic structure
  {
    id: 'chemistry-electron-shells',
    subject: 'chemistry',
    type: 'electron-shells',
    name: 'Electron Shell Diagram',
    description: 'Bohr model with electron shells',
    requiredElements: ['nucleus', 'shells', 'electrons'],
    optionalElements: ['protons', 'neutrons'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Electron Shell Diagram',
      elements: [{
        type: 'electron-shells',
        element: params?.element || 'Na',
        atomicNumber: params?.atomicNumber || 11,
        showNucleus: true,
        showElectronConfig: true,
      }],
    }),
  },
  {
    id: 'chemistry-orbital-diagram',
    subject: 'chemistry',
    type: 'orbital-diagram',
    name: 'Orbital Diagram',
    description: 's, p, d orbital box diagram',
    requiredElements: ['orbitals', 'electrons', 'spin-arrows'],
    optionalElements: ['energy-levels'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 300,
      title: 'Orbital Diagram',
      elements: [{
        type: 'orbital-diagram',
        element: params?.element || 'Fe',
        showSpins: true,
        showLabels: true,
      }],
    }),
  },
  
  // Bonding
  {
    id: 'chemistry-dot-cross',
    subject: 'chemistry',
    type: 'dot-cross',
    name: 'Dot and Cross Diagram',
    description: 'Covalent or ionic bonding diagram',
    requiredElements: ['atoms', 'electrons', 'bonds'],
    optionalElements: ['lone-pairs'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Dot and Cross Diagram',
      elements: [{
        type: 'dot-cross',
        molecule: params?.molecule || 'H2O',
        bondType: params?.bondType || 'covalent',
        showLonePairs: true,
      }],
    }),
  },
  {
    id: 'chemistry-3d-structure',
    subject: 'chemistry',
    type: '3d-structure',
    name: '3D Molecular Structure',
    description: 'VSEPR shapes - tetrahedral, trigonal planar etc',
    requiredElements: ['central-atom', 'bonds', '3d-representation'],
    optionalElements: ['bond-angles', 'lone-pairs'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: '3D Molecular Structure',
      elements: [{
        type: '3d-molecular',
        shape: params?.shape || 'tetrahedral',
        showAngles: true,
        show3D: true,
      }],
    }),
  },
  {
    id: 'chemistry-displayed-formula',
    subject: 'chemistry',
    type: 'displayed-formula',
    name: 'Displayed Formula',
    description: 'Structural formula showing all bonds',
    requiredElements: ['atoms', 'bonds', 'functional-groups'],
    optionalElements: ['hydrogen-atoms'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Displayed Formula',
      elements: [{
        type: 'structural-formula',
        molecule: params?.molecule || 'C2H5OH',
        showHydrogens: true,
        showBondTypes: true,
      }],
    }),
  },
  
  // Organic chemistry
  {
    id: 'chemistry-skeletal-formula',
    subject: 'chemistry',
    type: 'skeletal-formula',
    name: 'Skeletal Formula',
    description: 'Organic structure without C and H labels',
    requiredElements: ['carbon-skeleton', 'functional-groups'],
    optionalElements: ['stereochemistry'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 300,
      title: 'Skeletal Formula',
      elements: [{
        type: 'skeletal',
        molecule: params?.molecule || 'benzene',
        showFunctionalGroups: true,
      }],
    }),
  },
  {
    id: 'chemistry-isomers',
    subject: 'chemistry',
    type: 'isomers',
    name: 'Isomer Structures',
    description: 'Structural or stereoisomers',
    requiredElements: ['multiple-structures', 'same-formula'],
    optionalElements: ['isomer-type'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 600,
      height: 300,
      title: 'Isomers',
      elements: [{
        type: 'isomers',
        formula: params?.formula || 'C4H10',
        isomerType: params?.type || 'structural',
        showAll: true,
      }],
    }),
  },
  {
    id: 'chemistry-reaction-mechanism',
    subject: 'chemistry',
    type: 'reaction-mechanism',
    name: 'Reaction Mechanism',
    description: 'Curly arrows showing electron movement',
    requiredElements: ['curly-arrows', 'intermediates', 'products'],
    optionalElements: ['transition-state'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 600,
      height: 350,
      title: 'Reaction Mechanism',
      elements: [{
        type: 'mechanism',
        reactionType: params?.type || 'SN2',
        showCurlyArrows: true,
        showIntermediates: true,
      }],
    }),
  },
  
  // Energy diagrams
  {
    id: 'chemistry-energy-profile',
    subject: 'chemistry',
    type: 'energy-profile',
    name: 'Energy Profile',
    description: 'Reaction profile with activation energy',
    requiredElements: ['reactants', 'products', 'activation-energy'],
    optionalElements: ['catalyst-profile', 'enthalpy-change'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 450,
      height: 350,
      title: 'Energy Profile',
      elements: [{
        type: 'energy-profile',
        reactionType: params?.type || 'exothermic',
        showActivationEnergy: true,
        showEnthalpyChange: true,
        catalyst: params?.catalyst || false,
      }],
    }),
  },
  {
    id: 'chemistry-born-haber',
    subject: 'chemistry',
    type: 'born-haber',
    name: 'Born-Haber Cycle',
    description: 'Energy cycle for ionic compound formation',
    requiredElements: ['energy-levels', 'arrows', 'enthalpy-values'],
    optionalElements: ['intermediate-steps'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 500,
      height: 500,
      title: 'Born-Haber Cycle',
      elements: [{
        type: 'born-haber',
        compound: params?.compound || 'NaCl',
        showAllSteps: true,
        showValues: true,
      }],
    }),
  },
  {
    id: 'chemistry-maxwell-boltzmann',
    subject: 'chemistry',
    type: 'maxwell-boltzmann',
    name: 'Maxwell-Boltzmann Distribution',
    description: 'Molecular energy distribution curve',
    requiredElements: ['distribution-curve', 'activation-energy', 'axes'],
    optionalElements: ['temperature-comparison'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 350,
      title: 'Maxwell-Boltzmann Distribution',
      elements: [{
        type: 'maxwell-boltzmann',
        temperature: params?.temperature || 298,
        showActivationEnergy: true,
        compareTemperatures: params?.compare || false,
      }],
    }),
  },
  
  // Laboratory apparatus
  {
    id: 'chemistry-distillation',
    subject: 'chemistry',
    type: 'distillation',
    name: 'Distillation Apparatus',
    description: 'Simple or fractional distillation setup',
    requiredElements: ['flask', 'condenser', 'thermometer'],
    optionalElements: ['fractionating-column', 'heating'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Distillation Apparatus',
      elements: [{
        type: 'distillation',
        distillationType: params?.type || 'simple',
        showLabels: true,
        showWaterFlow: true,
      }],
    }),
  },
  {
    id: 'chemistry-titration-setup',
    subject: 'chemistry',
    type: 'titration-setup',
    name: 'Titration Setup',
    description: 'Burette, pipette, and conical flask',
    requiredElements: ['burette', 'conical-flask', 'white-tile'],
    optionalElements: ['pipette', 'indicator'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 350,
      height: 450,
      title: 'Titration Setup',
      elements: [{
        type: 'titration-apparatus',
        showVolumes: true,
        showIndicator: true,
        showMeniscus: true,
      }],
    }),
  },
  {
    id: 'chemistry-gas-collection',
    subject: 'chemistry',
    type: 'gas-collection',
    name: 'Gas Collection',
    description: 'Over water or upward/downward delivery',
    requiredElements: ['gas-jar', 'delivery-tube', 'collection-method'],
    optionalElements: ['water-trough'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Gas Collection',
      elements: [{
        type: 'gas-collection',
        method: params?.method || 'over-water',
        showLabels: true,
      }],
    }),
  },
  {
    id: 'chemistry-chromatography',
    subject: 'chemistry',
    type: 'chromatography',
    name: 'Chromatography',
    description: 'Paper or thin layer chromatography',
    requiredElements: ['paper', 'solvent-front', 'spots'],
    optionalElements: ['rf-values'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 300,
      height: 400,
      title: 'Chromatography',
      elements: [{
        type: 'chromatography',
        spots: params?.spots || 3,
        showRfValues: true,
        showSolventFront: true,
      }],
    }),
  },
  
  // Electrochemistry
  {
    id: 'chemistry-electrolysis',
    subject: 'chemistry',
    type: 'electrolysis',
    name: 'Electrolysis Cell',
    description: 'Electrodes, electrolyte, and ion movement',
    requiredElements: ['anode', 'cathode', 'electrolyte', 'ions'],
    optionalElements: ['half-equations'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Electrolysis Cell',
      elements: [{
        type: 'electrolysis',
        electrolyte: params?.electrolyte || 'CuSO4',
        showIonMovement: true,
        showEquations: true,
      }],
    }),
  },
  {
    id: 'chemistry-electrochemical-cell',
    subject: 'chemistry',
    type: 'electrochemical-cell',
    name: 'Electrochemical Cell',
    description: 'Voltaic/galvanic cell with salt bridge',
    requiredElements: ['half-cells', 'salt-bridge', 'electrodes'],
    optionalElements: ['voltmeter', 'electron-flow'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Electrochemical Cell',
      elements: [{
        type: 'galvanic-cell',
        anode: params?.anode || 'Zn',
        cathode: params?.cathode || 'Cu',
        showElectronFlow: true,
        showVoltmeter: true,
      }],
    }),
  },
  
  // Graphs
  {
    id: 'chemistry-ph-curve',
    subject: 'chemistry',
    type: 'ph-curve',
    name: 'pH Titration Curve',
    description: 'pH vs volume with equivalence point',
    requiredElements: ['curve', 'equivalence-point', 'axes'],
    optionalElements: ['buffer-region', 'indicators'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'pH Titration Curve',
      elements: [{
        type: 'ph-curve',
        titrationType: params?.type || 'strong-strong',
        showEquivalencePoint: true,
        showIndicators: params?.indicators || false,
      }],
    }),
  },
  {
    id: 'chemistry-rate-graph',
    subject: 'chemistry',
    type: 'rate-graph',
    name: 'Rate of Reaction Graph',
    description: 'Concentration or volume vs time',
    requiredElements: ['curve', 'initial-rate', 'axes'],
    optionalElements: ['half-life', 'tangent'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Rate of Reaction',
      elements: [{
        type: 'rate-graph',
        order: params?.order || 1,
        showInitialRate: true,
        showTangent: params?.tangent || false,
      }],
    }),
  },
];

/**
 * ADDITIONAL BIOLOGY DIAGRAM TEMPLATES
 */
export const BIOLOGY_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  // Cell biology
  {
    id: 'biology-plant-cell',
    subject: 'biology',
    type: 'plant-cell',
    name: 'Plant Cell',
    description: 'Plant cell with organelles labeled',
    requiredElements: ['cell-wall', 'chloroplast', 'vacuole', 'nucleus'],
    optionalElements: ['mitochondria', 'ribosomes'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Plant Cell',
      elements: [{
        type: 'plant-cell',
        showAllOrganelles: true,
        labelOrganelles: true,
        magnification: params?.magnification || 'x400',
      }],
    }),
  },
  {
    id: 'biology-animal-cell',
    subject: 'biology',
    type: 'animal-cell',
    name: 'Animal Cell',
    description: 'Animal cell with organelles',
    requiredElements: ['cell-membrane', 'nucleus', 'cytoplasm', 'mitochondria'],
    optionalElements: ['ribosomes', 'er', 'golgi'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Animal Cell',
      elements: [{
        type: 'animal-cell',
        showAllOrganelles: true,
        labelOrganelles: true,
        magnification: params?.magnification || 'x400',
      }],
    }),
  },
  {
    id: 'biology-bacterial-cell',
    subject: 'biology',
    type: 'bacterial-cell',
    name: 'Bacterial Cell',
    description: 'Prokaryotic cell structure',
    requiredElements: ['cell-wall', 'cell-membrane', 'cytoplasm', 'dna-loop'],
    optionalElements: ['plasmids', 'flagella', 'pili'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 300,
      title: 'Bacterial Cell',
      elements: [{
        type: 'bacterial-cell',
        showPlasmids: true,
        showFlagella: params?.flagella || false,
      }],
    }),
  },
  {
    id: 'biology-specialised-cells',
    subject: 'biology',
    type: 'specialised-cells',
    name: 'Specialised Cells',
    description: 'Nerve, muscle, root hair, or sperm cells',
    requiredElements: ['cell-shape', 'adaptations', 'labels'],
    optionalElements: ['function'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Specialised Cells',
      elements: [{
        type: 'specialised-cell',
        cellType: params?.type || 'nerve',
        showAdaptations: true,
        showFunction: true,
      }],
    }),
  },
  
  // Cell division
  {
    id: 'biology-mitosis',
    subject: 'biology',
    type: 'mitosis',
    name: 'Mitosis Stages',
    description: 'Prophase, metaphase, anaphase, telophase',
    requiredElements: ['stages', 'chromosomes', 'spindle'],
    optionalElements: ['centrioles', 'labels'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 600,
      height: 400,
      title: 'Mitosis',
      elements: [{
        type: 'mitosis',
        showAllStages: true,
        showSpindle: true,
        labelStages: true,
      }],
    }),
  },
  {
    id: 'biology-meiosis',
    subject: 'biology',
    type: 'meiosis',
    name: 'Meiosis Stages',
    description: 'Meiosis I and II with crossing over',
    requiredElements: ['meiosis-i', 'meiosis-ii', 'crossing-over'],
    optionalElements: ['genetic-variation'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 700,
      height: 500,
      title: 'Meiosis',
      elements: [{
        type: 'meiosis',
        showCrossingOver: true,
        showBothDivisions: true,
        labelStages: true,
      }],
    }),
  },
  
  // Genetics
  {
    id: 'biology-dna-structure',
    subject: 'biology',
    type: 'dna-structure',
    name: 'DNA Structure',
    description: 'Double helix with base pairs',
    requiredElements: ['double-helix', 'base-pairs', 'sugar-phosphate'],
    optionalElements: ['hydrogen-bonds', 'antiparallel'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 350,
      height: 450,
      title: 'DNA Structure',
      elements: [{
        type: 'dna',
        showBasePairs: true,
        showHydrogenBonds: true,
        show3D: params?.show3D || false,
      }],
    }),
  },
  {
    id: 'biology-protein-synthesis',
    subject: 'biology',
    type: 'protein-synthesis',
    name: 'Protein Synthesis',
    description: 'Transcription and translation',
    requiredElements: ['dna', 'mrna', 'ribosome', 'protein'],
    optionalElements: ['trna', 'amino-acids'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 600,
      height: 400,
      title: 'Protein Synthesis',
      elements: [{
        type: 'protein-synthesis',
        showTranscription: true,
        showTranslation: true,
        showTRNA: true,
      }],
    }),
  },
  {
    id: 'biology-punnett-square',
    subject: 'biology',
    type: 'punnett-square',
    name: 'Punnett Square',
    description: 'Genetic cross diagram',
    requiredElements: ['gametes', 'offspring', 'genotypes'],
    optionalElements: ['phenotypes', 'ratios'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 350,
      height: 350,
      title: 'Punnett Square',
      elements: [{
        type: 'punnett',
        parentGenotypes: params?.parents || ['Aa', 'Aa'],
        showPhenotypes: true,
        showRatios: true,
      }],
    }),
  },
  {
    id: 'biology-pedigree',
    subject: 'biology',
    type: 'pedigree',
    name: 'Pedigree Chart',
    description: 'Family tree showing inheritance',
    requiredElements: ['generations', 'affected-individuals', 'key'],
    optionalElements: ['carriers', 'genotypes'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Pedigree Chart',
      elements: [{
        type: 'pedigree',
        generations: params?.generations || 3,
        showKey: true,
        showGenotypes: params?.genotypes || false,
      }],
    }),
  },
  
  // Ecology
  {
    id: 'biology-food-chain',
    subject: 'biology',
    type: 'food-chain',
    name: 'Food Chain',
    description: 'Linear feeding relationship',
    requiredElements: ['producer', 'consumers', 'arrows'],
    optionalElements: ['trophic-levels', 'decomposers'],
    complexity: 1,
    generateSpec: (params) => ({
      width: 500,
      height: 200,
      title: 'Food Chain',
      elements: [{
        type: 'food-chain',
        organisms: params?.organisms || ['grass', 'rabbit', 'fox', 'decomposer'],
        showTrophicLevels: true,
      }],
    }),
  },
  {
    id: 'biology-pyramid-biomass',
    subject: 'biology',
    type: 'pyramid-biomass',
    name: 'Pyramid of Biomass',
    description: 'Biomass at each trophic level',
    requiredElements: ['pyramid-shape', 'trophic-levels', 'biomass-values'],
    optionalElements: ['organisms'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Pyramid of Biomass',
      elements: [{
        type: 'pyramid',
        pyramidType: 'biomass',
        levels: params?.levels || [1000, 100, 10, 1],
        showValues: true,
      }],
    }),
  },
  {
    id: 'biology-carbon-cycle',
    subject: 'biology',
    type: 'carbon-cycle',
    name: 'Carbon Cycle',
    description: 'Carbon movement through ecosystem',
    requiredElements: ['atmosphere', 'organisms', 'processes'],
    optionalElements: ['fossil-fuels', 'oceans'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 600,
      height: 500,
      title: 'Carbon Cycle',
      elements: [{
        type: 'carbon-cycle',
        showAllProcesses: true,
        showArrows: true,
        labelProcesses: true,
      }],
    }),
  },
  {
    id: 'biology-nitrogen-cycle',
    subject: 'biology',
    type: 'nitrogen-cycle',
    name: 'Nitrogen Cycle',
    description: 'Nitrogen transformations in ecosystem',
    requiredElements: ['nitrogen-forms', 'bacteria-types', 'processes'],
    optionalElements: ['plants', 'decomposition'],
    complexity: 4,
    generateSpec: (params) => ({
      width: 600,
      height: 500,
      title: 'Nitrogen Cycle',
      elements: [{
        type: 'nitrogen-cycle',
        showBacteria: true,
        showProcesses: true,
        showCompounds: true,
      }],
    }),
  },
  
  // Human biology
  {
    id: 'biology-digestive-system',
    subject: 'biology',
    type: 'digestive-system',
    name: 'Digestive System',
    description: 'Human digestive tract and organs',
    requiredElements: ['organs', 'path', 'labels'],
    optionalElements: ['enzymes', 'functions'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 500,
      title: 'Digestive System',
      elements: [{
        type: 'digestive-system',
        showAllOrgans: true,
        labelOrgans: true,
        showEnzymes: params?.enzymes || false,
      }],
    }),
  },
  {
    id: 'biology-respiratory-system',
    subject: 'biology',
    type: 'respiratory-system',
    name: 'Respiratory System',
    description: 'Lungs and gas exchange structures',
    requiredElements: ['trachea', 'bronchi', 'alveoli'],
    optionalElements: ['diaphragm', 'gas-exchange'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 450,
      title: 'Respiratory System',
      elements: [{
        type: 'respiratory-system',
        showAlveoli: true,
        showGasExchange: params?.gasExchange || false,
      }],
    }),
  },
  {
    id: 'biology-circulatory-system',
    subject: 'biology',
    type: 'circulatory-system',
    name: 'Circulatory System',
    description: 'Heart, blood vessels, and circulation',
    requiredElements: ['heart', 'arteries', 'veins'],
    optionalElements: ['capillaries', 'blood-flow'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 500,
      title: 'Circulatory System',
      elements: [{
        type: 'circulatory-system',
        showHeart: true,
        showBloodFlow: true,
        showOxygenation: params?.oxygenation || false,
      }],
    }),
  },
  {
    id: 'biology-nervous-system',
    subject: 'biology',
    type: 'nervous-system',
    name: 'Nervous System',
    description: 'Brain, spinal cord, and nerves',
    requiredElements: ['brain', 'spinal-cord', 'nerves'],
    optionalElements: ['reflex-arc', 'synapses'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 500,
      title: 'Nervous System',
      elements: [{
        type: 'nervous-system',
        showBrainRegions: params?.brainRegions || false,
        showReflexArc: params?.reflexArc || false,
      }],
    }),
  },
  {
    id: 'biology-neuron',
    subject: 'biology',
    type: 'neuron',
    name: 'Neuron Structure',
    description: 'Nerve cell with dendrites and axon',
    requiredElements: ['cell-body', 'dendrites', 'axon', 'terminals'],
    optionalElements: ['myelin-sheath', 'nodes'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 250,
      title: 'Neuron',
      elements: [{
        type: 'neuron',
        showMyelin: true,
        showSynapse: params?.synapse || false,
      }],
    }),
  },
  {
    id: 'biology-synapse',
    subject: 'biology',
    type: 'synapse',
    name: 'Synapse',
    description: 'Synaptic transmission',
    requiredElements: ['pre-synaptic', 'post-synaptic', 'neurotransmitters'],
    optionalElements: ['vesicles', 'receptors'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 350,
      title: 'Synapse',
      elements: [{
        type: 'synapse',
        showVesicles: true,
        showNeurotransmitters: true,
        showReceptors: true,
      }],
    }),
  },
  
  // Plant biology
  {
    id: 'biology-leaf-cross-section',
    subject: 'biology',
    type: 'leaf-cross-section',
    name: 'Leaf Cross Section',
    description: 'Leaf tissues and cells',
    requiredElements: ['epidermis', 'palisade', 'spongy', 'stomata'],
    optionalElements: ['xylem', 'phloem', 'chloroplasts'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Leaf Cross Section',
      elements: [{
        type: 'leaf-cross-section',
        showAllLayers: true,
        showStomata: true,
        showChloroplasts: params?.chloroplasts || false,
      }],
    }),
  },
  {
    id: 'biology-flower-structure',
    subject: 'biology',
    type: 'flower-structure',
    name: 'Flower Structure',
    description: 'Reproductive parts of flower',
    requiredElements: ['petals', 'stamens', 'carpel', 'sepals'],
    optionalElements: ['nectary', 'receptacle'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Flower Structure',
      elements: [{
        type: 'flower',
        showAllParts: true,
        labelParts: true,
        crossSection: params?.crossSection || false,
      }],
    }),
  },
  {
    id: 'biology-root-cross-section',
    subject: 'biology',
    type: 'root-cross-section',
    name: 'Root Cross Section',
    description: 'Root tissues and transport',
    requiredElements: ['epidermis', 'cortex', 'xylem', 'phloem'],
    optionalElements: ['root-hairs', 'endodermis'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Root Cross Section',
      elements: [{
        type: 'root-cross-section',
        showRootHairs: true,
        showTransportTissues: true,
      }],
    }),
  },
];

/**
 * ADDITIONAL GEOGRAPHY DIAGRAM TEMPLATES
 */
export const GEOGRAPHY_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  // Maps
  {
    id: 'geography-choropleth',
    subject: 'geography',
    type: 'choropleth',
    name: 'Choropleth Map',
    description: 'Map with shaded regions showing data',
    requiredElements: ['map-outline', 'shading', 'key'],
    optionalElements: ['boundaries', 'labels'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Choropleth Map',
      elements: [{
        type: 'choropleth',
        data: params?.data || 'population-density',
        showKey: true,
        showBoundaries: true,
      }],
    }),
  },
  {
    id: 'geography-isoline',
    subject: 'geography',
    type: 'isoline',
    name: 'Isoline Map',
    description: 'Contour lines or isobars',
    requiredElements: ['isolines', 'values', 'key'],
    optionalElements: ['spot-heights'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Isoline Map',
      elements: [{
        type: 'isoline',
        lineType: params?.type || 'contour',
        interval: params?.interval || 50,
        showValues: true,
      }],
    }),
  },
  {
    id: 'geography-dot-map',
    subject: 'geography',
    type: 'dot-map',
    name: 'Dot Map',
    description: 'Dots representing quantities',
    requiredElements: ['dots', 'distribution', 'key'],
    optionalElements: ['clusters'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Dot Map',
      elements: [{
        type: 'dot-map',
        dotValue: params?.value || 1000,
        showKey: true,
        showClusters: params?.clusters || false,
      }],
    }),
  },
  {
    id: 'geography-flow-map',
    subject: 'geography',
    type: 'flow-map',
    name: 'Flow Map',
    description: 'Movement patterns with arrows',
    requiredElements: ['arrows', 'origins', 'destinations'],
    optionalElements: ['flow-volume'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Flow Map',
      elements: [{
        type: 'flow-map',
        flowType: params?.type || 'migration',
        showVolume: true,
        showArrows: true,
      }],
    }),
  },
  {
    id: 'geography-proportional-symbol',
    subject: 'geography',
    type: 'proportional-symbol',
    name: 'Proportional Symbol Map',
    description: 'Circles sized by data values',
    requiredElements: ['symbols', 'sizes', 'key'],
    optionalElements: ['labels'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Proportional Symbol Map',
      elements: [{
        type: 'proportional-symbol',
        symbolType: params?.symbol || 'circle',
        showKey: true,
        showValues: params?.values || false,
      }],
    }),
  },
  
  // Physical geography
  {
    id: 'geography-river-cross-section',
    subject: 'geography',
    type: 'river-cross-section',
    name: 'River Cross Section',
    description: 'River channel profile',
    requiredElements: ['channel', 'banks', 'water-level'],
    optionalElements: ['velocity', 'depth-markers'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 450,
      height: 300,
      title: 'River Cross Section',
      elements: [{
        type: 'river-cross-section',
        stage: params?.stage || 'middle',
        showVelocity: params?.velocity || false,
        showDepth: true,
      }],
    }),
  },
  {
    id: 'geography-long-profile',
    subject: 'geography',
    type: 'long-profile',
    name: 'Long Profile',
    description: 'River gradient from source to mouth',
    requiredElements: ['profile-line', 'source', 'mouth'],
    optionalElements: ['stages', 'features'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Long Profile',
      elements: [{
        type: 'long-profile',
        showStages: true,
        showFeatures: params?.features || false,
      }],
    }),
  },
  {
    id: 'geography-meander',
    subject: 'geography',
    type: 'meander',
    name: 'Meander',
    description: 'River meander with erosion and deposition',
    requiredElements: ['channel', 'erosion', 'deposition'],
    optionalElements: ['flow-lines', 'oxbow'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Meander',
      elements: [{
        type: 'meander',
        showErosion: true,
        showDeposition: true,
        showFlow: params?.flow || false,
      }],
    }),
  },
  {
    id: 'geography-waterfall',
    subject: 'geography',
    type: 'waterfall',
    name: 'Waterfall',
    description: 'Waterfall formation and features',
    requiredElements: ['hard-rock', 'soft-rock', 'plunge-pool'],
    optionalElements: ['undercutting', 'retreat'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Waterfall',
      elements: [{
        type: 'waterfall',
        showRockTypes: true,
        showProcesses: params?.processes || false,
      }],
    }),
  },
  {
    id: 'geography-coastal-erosion',
    subject: 'geography',
    type: 'coastal-erosion',
    name: 'Coastal Erosion',
    description: 'Cliff profile and wave action',
    requiredElements: ['cliff', 'waves', 'erosion-features'],
    optionalElements: ['wave-cut-platform', 'processes'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Coastal Erosion',
      elements: [{
        type: 'coastal-erosion',
        featureType: params?.feature || 'cliff',
        showProcesses: true,
        showWaves: true,
      }],
    }),
  },
  {
    id: 'geography-glacier',
    subject: 'geography',
    type: 'glacier',
    name: 'Glacier',
    description: 'Glacier features and movement',
    requiredElements: ['ice', 'valley', 'moraine'],
    optionalElements: ['crevasses', 'flow-lines'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Glacier',
      elements: [{
        type: 'glacier',
        showFeatures: true,
        showMovement: params?.movement || false,
      }],
    }),
  },
  {
    id: 'geography-volcano',
    subject: 'geography',
    type: 'volcano',
    name: 'Volcano Cross Section',
    description: 'Volcanic structure and features',
    requiredElements: ['cone', 'crater', 'magma-chamber'],
    optionalElements: ['layers', 'vents'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Volcano',
      elements: [{
        type: 'volcano',
        volcanoType: params?.type || 'composite',
        showLayers: true,
        showMagma: true,
      }],
    }),
  },
  {
    id: 'geography-plate-boundary',
    subject: 'geography',
    type: 'plate-boundary',
    name: 'Plate Boundary',
    description: 'Tectonic plate interactions',
    requiredElements: ['plates', 'boundary', 'movement'],
    optionalElements: ['convection', 'features'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Plate Boundary',
      elements: [{
        type: 'plate-boundary',
        boundaryType: params?.type || 'divergent',
        showConvection: params?.convection || false,
        showFeatures: true,
      }],
    }),
  },
  
  // Human geography
  {
    id: 'geography-settlement-hierarchy',
    subject: 'geography',
    type: 'settlement-hierarchy',
    name: 'Settlement Hierarchy',
    description: 'Pyramid of settlement types',
    requiredElements: ['pyramid', 'settlement-types', 'population'],
    optionalElements: ['services'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Settlement Hierarchy',
      elements: [{
        type: 'settlement-hierarchy',
        showPopulation: true,
        showServices: params?.services || false,
      }],
    }),
  },
  {
    id: 'geography-burgess-model',
    subject: 'geography',
    type: 'burgess-model',
    name: 'Burgess Model',
    description: 'Concentric zone urban model',
    requiredElements: ['zones', 'cbd', 'labels'],
    optionalElements: ['key'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Burgess Model',
      elements: [{
        type: 'burgess-model',
        showZones: true,
        showLabels: true,
      }],
    }),
  },
  {
    id: 'geography-demographic-transition',
    subject: 'geography',
    type: 'demographic-transition',
    name: 'Demographic Transition Model',
    description: 'Population change over time',
    requiredElements: ['stages', 'birth-rate', 'death-rate'],
    optionalElements: ['total-population'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Demographic Transition Model',
      elements: [{
        type: 'dtm',
        showStages: true,
        showPopulation: params?.population || false,
      }],
    }),
  },
  {
    id: 'geography-land-use',
    subject: 'geography',
    type: 'land-use',
    name: 'Land Use Map',
    description: 'Urban or rural land use patterns',
    requiredElements: ['zones', 'key', 'boundaries'],
    optionalElements: ['labels'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Land Use Map',
      elements: [{
        type: 'land-use',
        areaType: params?.type || 'urban',
        showKey: true,
        showLabels: params?.labels || false,
      }],
    }),
  },
  
  // Weather and climate
  {
    id: 'geography-weather-map',
    subject: 'geography',
    type: 'weather-map',
    name: 'Weather Map',
    description: 'Synoptic chart with fronts and pressure',
    requiredElements: ['isobars', 'fronts', 'pressure-systems'],
    optionalElements: ['weather-stations'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Weather Map',
      elements: [{
        type: 'weather-map',
        showFronts: true,
        showIsobars: true,
        showStations: params?.stations || false,
      }],
    }),
  },
  {
    id: 'geography-wind-rose',
    subject: 'geography',
    type: 'wind-rose',
    name: 'Wind Rose',
    description: 'Wind direction and speed frequency',
    requiredElements: ['directions', 'frequencies', 'key'],
    optionalElements: ['speed-bands'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Wind Rose',
      elements: [{
        type: 'wind-rose',
        showFrequencies: true,
        showSpeeds: params?.speeds || false,
      }],
    }),
  },
  
  // Field sketches
  {
    id: 'geography-field-sketch',
    subject: 'geography',
    type: 'field-sketch',
    name: 'Field Sketch',
    description: 'Annotated landscape sketch',
    requiredElements: ['sketch', 'annotations', 'labels'],
    optionalElements: ['scale', 'compass'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 300,
      title: 'Field Sketch',
      elements: [{
        type: 'field-sketch',
        landscape: params?.landscape || 'coastal',
        showAnnotations: true,
        showCompass: true,
      }],
    }),
  },
  {
    id: 'geography-soil-profile',
    subject: 'geography',
    type: 'soil-profile',
    name: 'Soil Profile',
    description: 'Soil horizons and layers',
    requiredElements: ['horizons', 'labels', 'depth'],
    optionalElements: ['organic-matter', 'rock-fragments'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 300,
      height: 400,
      title: 'Soil Profile',
      elements: [{
        type: 'soil-profile',
        soilType: params?.type || 'podzol',
        showHorizons: true,
        showDepth: true,
      }],
    }),
  },
];

/**
 * HISTORY DIAGRAM TEMPLATES
 */
export const HISTORY_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'history-timeline',
    subject: 'history',
    type: 'timeline',
    name: 'Historical Timeline',
    description: 'Timeline with events and dates',
    requiredElements: ['timeline', 'events'],
    optionalElements: ['periods', 'labels'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 600,
      height: 200,
      title: 'Historical Timeline',
      elements: [{
        type: 'timeline',
        startDate: params?.startDate || '1900',
        endDate: params?.endDate || '2000',
        events: params?.events || [],
        showPeriods: true,
      }],
    }),
  },
  {
    id: 'history-source-analysis',
    subject: 'history',
    type: 'source-analysis',
    name: 'Source Analysis Layout',
    description: 'Layout for analyzing historical sources',
    requiredElements: ['source-box', 'analysis-sections'],
    optionalElements: ['annotations'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Source Analysis',
      elements: [{
        type: 'source-layout',
        sections: ['Content', 'Context', 'Purpose', 'Value'],
        sourceType: params?.sourceType || 'document',
      }],
    }),
  },
  {
    id: 'history-causation',
    subject: 'history',
    type: 'causation-diagram',
    name: 'Causation Diagram',
    description: 'Cause and consequence flowchart',
    requiredElements: ['causes', 'event', 'consequences'],
    optionalElements: ['links'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Causes and Consequences',
      elements: [{
        type: 'causation',
        event: params?.event || 'Historical Event',
        causes: params?.causes || [],
        consequences: params?.consequences || [],
      }],
    }),
  },
];

/**
 * ECONOMICS DIAGRAM TEMPLATES
 */
export const ECONOMICS_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'economics-supply-demand',
    subject: 'economics',
    type: 'supply-demand',
    name: 'Supply and Demand Curve',
    description: 'Market equilibrium diagram',
    requiredElements: ['axes', 'supply-curve', 'demand-curve', 'equilibrium'],
    optionalElements: ['shifts', 'labels'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Supply and Demand',
      elements: [{
        type: 'axes',
        xMin: 0,
        xMax: 100,
        yMin: 0,
        yMax: 100,
        xLabel: 'Quantity',
        yLabel: 'Price',
      }, {
        type: 'supply-demand',
        equilibriumPoint: params?.equilibrium || { x: 50, y: 50 },
        showShift: params?.showShift || false,
      }],
    }),
  },
  {
    id: 'economics-ppf',
    subject: 'economics',
    type: 'ppf',
    name: 'Production Possibility Frontier',
    description: 'PPF curve showing trade-offs',
    requiredElements: ['axes', 'ppf-curve'],
    optionalElements: ['points', 'shifts'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Production Possibility Frontier',
      elements: [{
        type: 'ppf',
        good1: params?.good1 || 'Good A',
        good2: params?.good2 || 'Good B',
        showPoints: true,
      }],
    }),
  },
  {
    id: 'economics-circular-flow',
    subject: 'economics',
    type: 'circular-flow',
    name: 'Circular Flow Model',
    description: 'Economic circular flow diagram',
    requiredElements: ['households', 'firms', 'flows'],
    optionalElements: ['government', 'foreign-sector'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Circular Flow of Income',
      elements: [{
        type: 'circular-flow',
        includeGovernment: params?.includeGovernment || false,
        includeForeign: params?.includeForeign || false,
      }],
    }),
  },
];

/**
 * BUSINESS DIAGRAM TEMPLATES
 */
export const BUSINESS_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'business-organizational-chart',
    subject: 'business',
    type: 'org-chart',
    name: 'Organizational Chart',
    description: 'Company hierarchy structure',
    requiredElements: ['hierarchy', 'departments'],
    optionalElements: ['roles', 'connections'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Organizational Structure',
      elements: [{
        type: 'org-chart',
        structure: params?.structure || 'hierarchical',
        levels: params?.levels || 3,
      }],
    }),
  },
  {
    id: 'business-product-lifecycle',
    subject: 'business',
    type: 'product-lifecycle',
    name: 'Product Life Cycle',
    description: 'Product life cycle curve',
    requiredElements: ['curve', 'stages'],
    optionalElements: ['labels', 'examples'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Product Life Cycle',
      elements: [{
        type: 'lifecycle-curve',
        stages: ['Introduction', 'Growth', 'Maturity', 'Decline'],
        showRevenue: true,
        showProfit: true,
      }],
    }),
  },
  {
    id: 'business-swot',
    subject: 'business',
    type: 'swot-analysis',
    name: 'SWOT Analysis',
    description: 'SWOT matrix diagram',
    requiredElements: ['quadrants'],
    optionalElements: ['items'],
    complexity: 1,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'SWOT Analysis',
      elements: [{
        type: 'swot-matrix',
        strengths: params?.strengths || [],
        weaknesses: params?.weaknesses || [],
        opportunities: params?.opportunities || [],
        threats: params?.threats || [],
      }],
    }),
  },
];

/**
 * PSYCHOLOGY DIAGRAM TEMPLATES
 */
export const PSYCHOLOGY_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'psychology-brain-regions',
    subject: 'psychology',
    type: 'brain-diagram',
    name: 'Brain Regions',
    description: 'Brain anatomy and regions',
    requiredElements: ['brain-outline', 'regions'],
    optionalElements: ['labels', 'functions'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Brain Regions',
      elements: [{
        type: 'brain',
        view: params?.view || 'sagittal',
        showRegions: true,
        showLabels: true,
      }],
    }),
  },
  {
    id: 'psychology-experimental-design',
    subject: 'psychology',
    type: 'experimental-design',
    name: 'Experimental Design',
    description: 'Research method diagram',
    requiredElements: ['groups', 'variables', 'process'],
    optionalElements: ['control', 'randomization'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Experimental Design',
      elements: [{
        type: 'experiment-flow',
        groups: params?.groups || ['Control', 'Experimental'],
        showRandomization: true,
        showVariables: true,
      }],
    }),
  },
  {
    id: 'psychology-normal-distribution',
    subject: 'psychology',
    type: 'normal-distribution',
    name: 'Normal Distribution',
    description: 'Bell curve for psychological measurements',
    requiredElements: ['curve', 'mean', 'std-dev'],
    optionalElements: ['percentiles', 'labels'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 450,
      height: 300,
      title: 'Normal Distribution',
      elements: [{
        type: 'bell-curve',
        mean: params?.mean || 100,
        stdDev: params?.stdDev || 15,
        showPercentiles: true,
      }],
    }),
  },
];

/**
 * ENGLISH LITERATURE DIAGRAM TEMPLATES
 */
export const ENGLISH_LITERATURE_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'english-plot-structure',
    subject: 'english-literature',
    type: 'plot-diagram',
    name: 'Plot Structure',
    description: 'Freytag pyramid or plot diagram',
    requiredElements: ['exposition', 'rising-action', 'climax', 'falling-action', 'resolution'],
    optionalElements: ['events', 'tension-line'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 500,
      height: 350,
      title: 'Plot Structure',
      elements: [{
        type: 'plot-pyramid',
        events: params?.events || [],
        showTension: true,
      }],
    }),
  },
  {
    id: 'english-character-map',
    subject: 'english-literature',
    type: 'character-map',
    name: 'Character Relationship Map',
    description: 'Character connections and relationships',
    requiredElements: ['characters', 'relationships'],
    optionalElements: ['quotes', 'themes'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 500,
      height: 400,
      title: 'Character Relationships',
      elements: [{
        type: 'character-web',
        characters: params?.characters || [],
        relationships: params?.relationships || [],
      }],
    }),
  },
  {
    id: 'english-theme-analysis',
    subject: 'english-literature',
    type: 'theme-diagram',
    name: 'Theme Analysis',
    description: 'Theme connections and evidence',
    requiredElements: ['theme', 'evidence'],
    optionalElements: ['quotes', 'analysis'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 450,
      height: 400,
      title: 'Theme Analysis',
      elements: [{
        type: 'theme-web',
        centralTheme: params?.theme || 'Theme',
        branches: params?.branches || [],
      }],
    }),
  },
];

/**
 * FURTHER MATHS DIAGRAM TEMPLATES
 */
export const FURTHER_MATHS_DIAGRAM_TEMPLATES_EXPANDED: DiagramTemplate[] = [
  {
    id: 'further-maths-3d-vector',
    subject: 'further-maths',
    type: '3d-vector',
    name: '3D Vector Diagram',
    description: '3D coordinate system with vectors',
    requiredElements: ['3d-axes', 'vectors'],
    optionalElements: ['planes', 'angles'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 450,
      title: '3D Vector Space',
      elements: [{
        type: '3d-axes',
        showGrid: true,
        vectors: params?.vectors || [],
      }],
    }),
  },
  {
    id: 'further-maths-complex-plane',
    subject: 'further-maths',
    type: 'complex-plane',
    name: 'Argand Diagram',
    description: 'Complex number representation',
    requiredElements: ['axes', 'complex-points'],
    optionalElements: ['loci', 'regions'],
    complexity: 2,
    generateSpec: (params) => ({
      width: 400,
      height: 400,
      title: 'Complex Plane',
      elements: [{
        type: 'argand-diagram',
        points: params?.points || [],
        showUnitCircle: params?.showUnitCircle || false,
      }],
    }),
  },
  {
    id: 'further-maths-matrix-transformation',
    subject: 'further-maths',
    type: 'matrix-transformation',
    name: 'Matrix Transformation',
    description: 'Geometric transformation visualization',
    requiredElements: ['original-shape', 'transformed-shape'],
    optionalElements: ['matrix', 'vectors'],
    complexity: 3,
    generateSpec: (params) => ({
      width: 450,
      height: 450,
      title: 'Matrix Transformation',
      elements: [{
        type: 'transformation',
        matrix: params?.matrix || [[1, 0], [0, 1]],
        shape: params?.shape || 'square',
        showMatrix: true,
      }],
    }),
  },
];

/**
 * Export all expanded templates
 */
export const ALL_EXPANDED_TEMPLATES = [
  ...MATHS_DIAGRAM_TEMPLATES_EXPANDED,
  ...PHYSICS_DIAGRAM_TEMPLATES_EXPANDED,
  ...CHEMISTRY_DIAGRAM_TEMPLATES_EXPANDED,
  ...BIOLOGY_DIAGRAM_TEMPLATES_EXPANDED,
  ...GEOGRAPHY_DIAGRAM_TEMPLATES_EXPANDED,
  ...HISTORY_DIAGRAM_TEMPLATES_EXPANDED,
  ...ECONOMICS_DIAGRAM_TEMPLATES_EXPANDED,
  ...BUSINESS_DIAGRAM_TEMPLATES_EXPANDED,
  ...PSYCHOLOGY_DIAGRAM_TEMPLATES_EXPANDED,
  ...ENGLISH_LITERATURE_DIAGRAM_TEMPLATES_EXPANDED,
  ...FURTHER_MATHS_DIAGRAM_TEMPLATES_EXPANDED,
];

/**
 * Get total count of all expanded templates
 */
export const EXPANDED_TEMPLATE_COUNT = ALL_EXPANDED_TEMPLATES.length;

console.log(`Created ${EXPANDED_TEMPLATE_COUNT} new expanded diagram templates based on exam board research`);