// Edexcel GCSE Chemistry Core Practicals
// Based on Edexcel 1CH0 specification (2016)
// Reference: https://www.pmt.education/teachers/chemistry/gcse/edexcel-gcse-chemistry-practical-notes/

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelGcseChemistryPracticals: Practical[] = [
  {
    id: 'edexcel-gcse-chemistry-cp1',
    name: 'CP1: Investigating the Composition of Inks',
    description: 'Use paper chromatography to investigate and compare the composition of different inks',
    icon: '🎨',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-mixtures'],
    equipment: [
      'Chromatography paper',
      'Beaker',
      'Water or suitable solvent',
      'Different coloured inks or food colourings',
      'Pencil (for baseline)',
      'Ruler',
      'Capillary tube or fine pipette',
      'Glass rod',
      'Watch glass or cover',
    ],
    safety: [
      'Some solvents are flammable - no naked flames',
      'Work in a well-ventilated area if using organic solvents',
      'Avoid skin contact with some dyes',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp2',
    name: 'CP2: Investigating pH',
    description: 'Investigate the change in pH on adding powdered calcium hydroxide or calcium oxide to a fixed volume of dilute hydrochloric acid',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases'],
    equipment: [
      'pH meter or universal indicator and colour chart',
      'Dilute hydrochloric acid',
      'Calcium hydroxide or calcium oxide powder',
      'Measuring cylinder',
      'Beaker',
      'Spatula',
      'Stirring rod',
      'Balance',
    ],
    safety: [
      'Wear safety glasses',
      'Calcium hydroxide/oxide is an irritant - avoid skin contact',
      'Dilute acid can irritate skin - wash off immediately',
      'Clean up spills promptly',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp3',
    name: 'CP3: Preparing Copper Sulfate',
    description: 'Prepare a pure, dry sample of hydrated copper sulfate crystals starting from copper oxide or copper carbonate',
    icon: '💎',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases', 'chemistry-making-salts'],
    equipment: [
      'Copper oxide or copper carbonate',
      'Dilute sulfuric acid',
      'Bunsen burner',
      'Tripod and gauze',
      'Evaporating basin',
      'Beaker',
      'Filter funnel and paper',
      'Stirring rod',
      'Spatula',
      'Crystallising dish',
    ],
    safety: [
      'Wear safety glasses',
      'Dilute sulfuric acid is corrosive - handle carefully',
      'Copper compounds can stain skin',
      'Take care with hot solutions',
      'Allow crystals to dry naturally - do not heat to dryness',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp4',
    name: 'CP4: Electrolysis of Copper Sulfate',
    description: 'Investigate the electrolysis of copper sulfate solution using inert (carbon) and copper electrodes',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-electrolysis'],
    equipment: [
      'Copper sulfate solution',
      'Beaker',
      'DC power supply',
      'Ammeter',
      'Carbon (graphite) electrodes',
      'Copper electrodes',
      'Connecting wires with crocodile clips',
      'Balance (for mass of electrodes)',
      'Stopwatch',
    ],
    safety: [
      'Wear safety glasses',
      'Low voltage DC only',
      'Copper sulfate solution is harmful - avoid skin contact',
      'Ensure good ventilation',
      'Do not touch electrodes while circuit is on',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp5',
    name: 'CP5: Acid-Alkali Titration',
    description: 'Carry out an accurate acid-alkali titration using a suitable indicator to determine concentration',
    icon: '🧫',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases', 'chemistry-quantitative'],
    equipment: [
      'Burette',
      'Pipette (25 cm³)',
      'Pipette filler',
      'Conical flask',
      'White tile',
      'Clamp stand and clamp',
      'Dilute acid and alkali of known/unknown concentration',
      'Suitable indicator (phenolphthalein or methyl orange)',
      'Wash bottle with distilled water',
    ],
    safety: [
      'Wear safety glasses',
      'Handle acids and alkalis carefully',
      'Rinse any spills immediately',
      'Take care when using glassware',
      'Some indicators are flammable',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp6',
    name: 'CP6: Investigating Reaction Rates',
    description: 'Investigate the effects of changing conditions (temperature, concentration, surface area) on the rate of a chemical reaction',
    icon: '⏱️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-rates'],
    equipment: [
      'Marble chips (calcium carbonate) of different sizes',
      'Dilute hydrochloric acid (different concentrations)',
      'Conical flask',
      'Delivery tube and bung',
      'Gas syringe or measuring cylinder and trough',
      'Stopwatch',
      'Balance',
      'Thermometer',
      'Water bath',
    ],
    safety: [
      'Wear safety glasses',
      'Take care with acids - corrosive',
      'Gas produced (CO₂) can cause asphyxiation in enclosed spaces',
      'Take care with hot water',
      'Ensure gas collection apparatus is secure',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp7',
    name: 'CP7: Identifying Ions',
    description: 'Use qualitative analysis to identify metal ions (flame tests, sodium hydroxide precipitation) and non-metal ions',
    icon: '🔥',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-analysis'],
    equipment: [
      'Bunsen burner',
      'Nichrome wire loops',
      'Concentrated hydrochloric acid (for cleaning wire)',
      'Test tubes and rack',
      'Sodium hydroxide solution',
      'Metal ion solutions (lithium, sodium, potassium, calcium, copper)',
      'Dilute acids',
      'Barium chloride solution',
      'Silver nitrate solution',
    ],
    safety: [
      'Wear safety glasses',
      'Concentrated HCl is very corrosive - use in fume cupboard',
      'Barium chloride is toxic - handle with care',
      'Silver nitrate stains skin',
      'Tie back loose hair when using Bunsen burner',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-gcse-chemistry-cp8',
    name: 'CP8: Combustion of Alcohols',
    description: 'Investigate the temperature rise produced by the combustion of different alcohols to compare their energy content',
    icon: '🔥',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-fuels', 'chemistry-organic'],
    equipment: [
      'Spirit burners containing different alcohols (methanol, ethanol, propanol, butanol)',
      'Copper calorimeter or metal can',
      'Thermometer',
      'Measuring cylinder',
      'Water',
      'Balance',
      'Clamp stand and clamp',
      'Heat shield/draught excluder',
      'Stopwatch',
    ],
    safety: [
      'Alcohols are highly flammable - keep away from other flames',
      'Wear safety glasses',
      'Replace cap on spirit burner to extinguish flame',
      'Ensure good ventilation',
      'Keep hair tied back',
      'Have fire extinguisher/blanket accessible',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
  },
];
