// AQA A-Level Physics Required Practicals
// Based on AQA 7408 specification
// Reference: https://www.aqa.org.uk/subjects/physics/a-level/physics-7408/specification/practical-assessment

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaALevelPhysicsPracticals: Practical[] = [
  {
    id: 'aqa-alevel-physics-rp1',
    name: 'RP1: Stationary Waves on a String',
    description: 'Investigation into the variation of the frequency of stationary waves on a string with length, tension and mass per unit length',
    icon: '🎸',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Signal generator',
      'Vibration generator',
      'String or elastic cord',
      'Pulley and clamp',
      'Slotted masses',
      'Metre ruler',
      'Balance',
      'Micrometer',
      'Strobe light (optional)',
    ],
    safety: [
      'Secure equipment to prevent falling',
      'Keep masses from falling on feet',
      'Strobe warning for photosensitive epilepsy',
      'Ensure string is securely fastened',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp2',
    name: 'RP2: Interference Effects',
    description: "Investigation of interference effects to include Young's double slit experiment and interference using a diffraction grating",
    icon: '🌈',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves', 'physics-optics'],
    equipment: [
      'Laser (Class 2 or below)',
      'Double slit',
      'Diffraction grating (known line spacing)',
      'Screen',
      'Metre ruler',
      'Vernier calipers or travelling microscope',
      'Darkened room',
    ],
    safety: [
      'Never look directly into laser beam',
      'Remove reflective objects (watches, jewellery)',
      'Use Class 2 laser or below',
      'Display laser warning signs',
      'Work in controlled lighting conditions',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp3',
    name: 'RP3: Determination of g',
    description: 'Determination of g by free-fall method using an electromagnet and electronic timing system',
    icon: '🍎',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-mechanics'],
    equipment: [
      'Electromagnet',
      'Steel ball bearing',
      'Electronic timer',
      'Trapdoor switch or light gates',
      'Metre ruler',
      'Clamp stand',
      'Spirit level',
    ],
    safety: [
      'Ball bearing can cause injury - use soft landing surface',
      'Secure the clamp stand',
      'Ensure electromagnet is positioned safely',
      'Keep area clear when dropping ball',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp4',
    name: "RP4: Determination of Young's Modulus",
    description: "Determination of Young modulus by measuring extension of a wire under tension",
    icon: '📏',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-materials'],
    equipment: [
      'Copper or steel wire (long, thin)',
      'Wooden blocks and G-clamp',
      'Pulley',
      'Slotted masses',
      'Metre ruler',
      'Micrometer screw gauge',
      'Vernier scale or travelling microscope',
      'Marker (tape)',
      'Safety glasses',
    ],
    safety: [
      'Wear safety glasses - wire may snap',
      'Keep feet clear of falling masses',
      'Use soft landing for masses',
      'Do not over-stretch wire past elastic limit',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp5',
    name: 'RP5: Determination of Resistivity',
    description: 'Determination of resistivity of a wire using a micrometer, ammeter, voltmeter and metre ruler',
    icon: '🔌',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Constantan or nichrome wire',
      'Micrometer screw gauge',
      'Metre ruler',
      'Ammeter',
      'Voltmeter',
      'Power supply (low voltage DC)',
      'Crocodile clips',
      'Connecting wires',
    ],
    safety: [
      'Wire can get hot - switch off between readings',
      'Use low voltage only',
      'Do not touch wire during experiment',
      'Allow cooling between measurements',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp6',
    name: 'RP6: Internal Resistance and EMF',
    description: 'Investigation of the emf and internal resistance of electric cells and batteries',
    icon: '🔋',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Cell or battery',
      'Variable resistor (rheostat)',
      'Ammeter',
      'Voltmeter',
      'Connecting wires',
      'Switch',
      'Fixed resistors (optional)',
    ],
    safety: [
      'Do not short circuit the cell',
      'Use low current to avoid heating',
      'Monitor cell temperature',
      'Do not mix old and new cells',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp7',
    name: 'RP7: Simple Harmonic Motion',
    description: 'Investigation into simple harmonic motion using a mass-spring system and simple pendulum',
    icon: '🕰️',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-shm', 'physics-oscillations'],
    equipment: [
      'Springs',
      'Slotted masses',
      'Clamp stand and clamp',
      'Metre ruler',
      'Stopwatch',
      'Fiducial marker',
      'Pendulum bob and string',
      'Protractor',
    ],
    safety: [
      'Secure clamp stand',
      'Keep feet clear of swinging masses',
      'Do not overload springs',
      'Use small amplitudes to avoid damage',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp8',
    name: "RP8: Boyle's Law / Charles's Law",
    description: "Investigation of Boyle's Law (constant temperature) and Charles's Law (constant pressure)",
    icon: '🎈',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal', 'physics-gases'],
    equipment: [
      "Boyle's Law apparatus (syringe or tube)",
      'Bourdon gauge or pressure sensor',
      "Charles's Law apparatus (capillary tube)",
      'Thermometer',
      'Water bath',
      'Ruler',
      'Bunsen burner or heater',
    ],
    safety: [
      'Do not exceed pressure limits of apparatus',
      'Take care with hot water',
      'Glass capillary tubes are fragile',
      'Allow time for thermal equilibrium',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp9',
    name: 'RP9: Charging and Discharging Capacitors',
    description: 'Investigation of the charge and discharge of capacitors, analysing time constant and capacitance',
    icon: '⚡',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-capacitance'],
    equipment: [
      'Capacitor (electrolytic, known value)',
      'Resistors (various values)',
      'Power supply',
      'Voltmeter or data logger',
      'Ammeter (optional)',
      'Stopwatch',
      'Switch',
      'Connecting wires',
    ],
    safety: [
      'Check capacitor polarity before connecting',
      'Do not exceed voltage rating',
      'Discharge capacitors before handling',
      'Large capacitors can store dangerous charge',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp10',
    name: 'RP10: Force on a Current-Carrying Wire',
    description: 'Investigate the relationship between force, flux density, current and length for a wire in a magnetic field',
    icon: '🧲',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-magnetism', 'physics-electromagnetism'],
    equipment: [
      'Top pan balance',
      'Horseshoe magnet or electromagnet',
      'Copper wire on frame',
      'Power supply',
      'Ammeter',
      'Variable resistor',
      'Clamp stand',
      'Connecting wires',
    ],
    safety: [
      'Strong magnets - keep away from electronic devices',
      'Wire can get hot at high currents',
      'Secure the balance and magnet',
      'Use appropriate current range',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp11',
    name: 'RP11: Magnetic Flux Linkage',
    description: 'Investigate magnetic flux linkage using a search coil and oscilloscope, analysing induced EMF',
    icon: '🌀',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electromagnetism', 'physics-induction'],
    equipment: [
      'Search coil',
      'Oscilloscope or data logger',
      'Signal generator',
      'Solenoid or bar magnet',
      'Connecting wires',
      'Ruler',
      'Known magnetic field source',
    ],
    safety: [
      'Handle oscilloscope carefully',
      'Do not drop magnets',
      'Keep magnets away from electronic devices',
      'Secure connecting wires',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'aqa-alevel-physics-rp12',
    name: 'RP12: Inverse Square Law for Gamma Radiation',
    description: 'Investigation of the inverse square law for gamma radiation using a Geiger-Müller tube',
    icon: '☢️',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-nuclear', 'physics-radiation'],
    equipment: [
      'Sealed gamma source (e.g., Co-60 or Cs-137)',
      'Geiger-Müller tube and counter/ratemeter',
      'Metre ruler',
      'Clamp stands',
      'Stopwatch',
      'Lead absorbers (for shielding)',
      'Tongs for handling source',
    ],
    safety: [
      'Follow CLEAPSS guidelines for radioactive sources',
      'Minimise exposure time',
      'Maximise distance from source',
      'Use shielding when not measuring',
      'Handle source with tongs only',
      'Never point source at people',
      'Return source to secure storage after use',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
  },
];
