// OCR Gateway GCSE Chemistry Practical Activity Groups (PAGs)
// Based on OCR Gateway J248 specification
// Reference: OCR specification and examination guidance

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrGcseChemistryPracticals: Practical[] = [
  {
    id: 'ocr-gcse-chemistry-pag1',
    name: 'PAG C1: Analysis',
    description: 'Qualitative analysis including flame tests, tests for gases, and identification of ions',
    icon: '🔥',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-analysis'],
    equipment: [
      'Bunsen burner',
      'Nichrome wire loops',
      'Concentrated hydrochloric acid (for cleaning wire)',
      'Test tubes and rack',
      'Sodium hydroxide solution',
      'Metal ion solutions',
      'Test reagents for gases',
      'Splint',
      'Limewater',
    ],
    safety: [
      'Wear safety glasses',
      'Concentrated HCl is very corrosive - use in fume cupboard',
      'Tie back loose hair when using Bunsen burner',
      'Some metal compounds are toxic',
      'Handle hot nichrome wire with care',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag2',
    name: 'PAG C2: Calorimetry',
    description: 'Investigate energy changes in chemical reactions using calorimetry',
    icon: '🌡️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-energy'],
    equipment: [
      'Polystyrene cup (calorimeter)',
      'Thermometer (0.5°C precision)',
      'Measuring cylinder',
      'Balance',
      'Acids and alkalis or metal powders',
      'Lid for cup',
      'Stirring rod',
      'Stopwatch',
    ],
    safety: [
      'Wear safety glasses',
      'Acids and alkalis can be corrosive',
      'Some reactions are exothermic - contents may get hot',
      'Metal powders can be irritants',
      'Clean up spills immediately',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag3',
    name: 'PAG C3: Electrolysis',
    description: 'Investigate the electrolysis of aqueous solutions and molten compounds',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-electrolysis'],
    equipment: [
      'Electrolysis cell',
      'DC power supply',
      'Ammeter',
      'Carbon (graphite) electrodes',
      'Copper electrodes',
      'Sodium chloride solution',
      'Copper sulfate solution',
      'Connecting wires with crocodile clips',
      'Test tubes for gas collection',
    ],
    safety: [
      'Wear safety glasses',
      'Low voltage DC only',
      'Chlorine gas is toxic - work in fume cupboard',
      'Hydrogen gas is flammable - no naked flames',
      'Copper sulfate solution is harmful',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag4',
    name: 'PAG C4: Preparing a Pure, Dry Salt',
    description: 'Prepare a pure, dry sample of a soluble salt by reaction of an acid with an insoluble base or carbonate',
    icon: '💎',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases', 'chemistry-making-salts'],
    equipment: [
      'Insoluble base (e.g., copper oxide) or carbonate',
      'Dilute acid (sulfuric, hydrochloric)',
      'Bunsen burner',
      'Tripod and gauze',
      'Evaporating basin',
      'Beaker',
      'Filter funnel and paper',
      'Stirring rod',
      'Crystallising dish',
    ],
    safety: [
      'Wear safety glasses',
      'Dilute acids are corrosive',
      'Copper compounds can stain skin',
      'Take care with hot solutions and evaporating basins',
      'Do not heat to complete dryness',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag5',
    name: 'PAG C5: Rates of Reaction',
    description: 'Investigate how changing conditions affects the rate of a reaction',
    icon: '⏱️',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-rates'],
    equipment: [
      'Conical flask',
      'Marble chips or magnesium ribbon',
      'Dilute hydrochloric acid (various concentrations)',
      'Gas syringe or collection over water',
      'Stopwatch',
      'Balance',
      'Thermometer',
      'Water bath',
      'Measuring cylinder',
    ],
    safety: [
      'Wear safety glasses',
      'Acids are corrosive',
      'Hydrogen gas is flammable',
      'Carbon dioxide can cause asphyxiation',
      'Take care with hot water',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag6',
    name: 'PAG C6: Titration',
    description: 'Carry out an acid-base titration to determine concentration of unknown solutions',
    icon: '🧫',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases', 'chemistry-quantitative'],
    equipment: [
      'Burette',
      'Pipette (25 cm³)',
      'Pipette filler',
      'Conical flask',
      'White tile',
      'Clamp stand and clamp',
      'Standard acid or alkali solution',
      'Unknown concentration solution',
      'Suitable indicator',
      'Wash bottle',
    ],
    safety: [
      'Wear safety glasses',
      'Handle acids and alkalis carefully',
      'Rinse skin immediately if contact occurs',
      'Take care with glassware',
      'Clean up spills promptly',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag7',
    name: 'PAG C7: Chromatography',
    description: 'Use paper chromatography to separate and identify substances in a mixture',
    icon: '🎨',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-mixtures', 'chemistry-analysis'],
    equipment: [
      'Chromatography paper',
      'Beaker',
      'Suitable solvent (water or ethanol)',
      'Samples to analyse (inks, food colourings)',
      'Pencil',
      'Ruler',
      'Capillary tubes or fine pipettes',
      'Watch glass or cover',
    ],
    safety: [
      'Some solvents are flammable - no naked flames',
      'Work in well-ventilated area',
      'Avoid skin contact with organic solvents',
      'Some dyes may be irritants',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'ocr-gcse-chemistry-pag8',
    name: 'PAG C8: Measuring and Testing Gases',
    description: 'Collect and test gases produced in chemical reactions including hydrogen, oxygen and carbon dioxide',
    icon: '💨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-reactions', 'chemistry-gases'],
    equipment: [
      'Conical flask or test tube',
      'Delivery tube and bung',
      'Gas syringe',
      'Trough and collection tubes',
      'Splint',
      'Glowing splint',
      'Limewater',
      'Chemicals to generate gases',
      'Stopwatch',
    ],
    safety: [
      'Wear safety glasses',
      'Hydrogen is flammable - test away from main gas supply',
      'Chlorine is toxic - work in fume cupboard',
      'Ensure good ventilation',
      'Do not inhale gases directly',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
  },
];
