// OCR A-Level Physics A Practical Activity Groups (PAGs)
// Based on OCR H556 specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/physics-a-h156-h556-from-2015/
// Note: OCR uses a flexible PAG approach - activities can be varied while meeting the same skills

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrALevelPhysicsPracticals: Practical[] = [
  {
    id: 'ocr-alevel-physics-pag1',
    name: 'PAG 1: Investigating Motion',
    description: 'Investigate the motion of objects, including determination of g by free-fall or projectile methods',
    icon: '🍎',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-mechanics', 'physics-motion'],
    equipment: [
      'Electromagnet and ball bearing',
      'Light gates or electronic timer',
      'Metre ruler',
      'Clamp stand',
      'Trapdoor switch',
      'Motion sensor (optional)',
      'Data logger (optional)',
      'Video camera for analysis (optional)',
    ],
    safety: [
      'Use soft landing surface',
      'Secure clamp stand',
      'Keep area clear when dropping objects',
      'Ball bearings can cause injury',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag2',
    name: 'PAG 2: Investigating Materials',
    description: "Investigate the properties of materials including Young modulus determination",
    icon: '📏',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-materials'],
    equipment: [
      'Copper or steel wire',
      'G-clamps and wooden blocks',
      'Pulley',
      'Slotted masses',
      'Metre ruler',
      'Micrometer screw gauge',
      'Vernier scale',
      'Marker tape',
      'Safety glasses',
    ],
    safety: [
      'Wear safety glasses - wire may snap',
      'Keep feet clear of falling masses',
      'Use soft landing surface',
      'Do not exceed elastic limit',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag3',
    name: 'PAG 3: Electrical Characteristics',
    description: 'Investigate the electrical characteristics of components (resistors, filament lamps, thermistors, diodes)',
    icon: '💡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Various components (resistor, lamp, thermistor, diode)',
      'Variable power supply',
      'Ammeter',
      'Voltmeter',
      'Variable resistor (potential divider)',
      'Connecting wires',
      'Component holders',
    ],
    safety: [
      'Filament lamp gets hot',
      'Use appropriate voltage for diode',
      'Avoid excessive current',
      'Allow components to cool',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag4',
    name: 'PAG 4: EMF and Internal Resistance',
    description: 'Investigate the EMF and internal resistance of cells and batteries',
    icon: '🔋',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Cell or battery',
      'Variable resistor (rheostat)',
      'Ammeter',
      'Voltmeter',
      'Connecting wires',
      'Switch',
      'Fixed resistors (various values)',
    ],
    safety: [
      'Do not short circuit the cell',
      'Use low currents to prevent heating',
      'Monitor cell temperature',
      'Disconnect when not in use',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag5',
    name: 'PAG 5: Inverse Square Law (Radiation)',
    description: 'Investigate the inverse square law for gamma radiation using a GM tube',
    icon: '☢️',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-nuclear', 'physics-radiation'],
    equipment: [
      'Sealed gamma source',
      'Geiger-Müller tube and counter',
      'Metre ruler',
      'Clamp stands',
      'Stopwatch',
      'Lead shielding',
      'Tongs for source handling',
    ],
    safety: [
      'Follow CLEAPSS guidelines',
      'Minimise exposure time',
      'Maximise distance from source',
      'Use shielding when not measuring',
      'Handle source with tongs only',
      'Never point source at people',
      'Return to secure storage after use',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag6',
    name: 'PAG 6: Circular Motion',
    description: 'Investigate circular motion and the relationship between angular velocity, radius, and centripetal force',
    icon: '🔄',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-circular-motion'],
    equipment: [
      'Circular motion apparatus',
      'Slotted masses',
      'Metre ruler',
      'Stopwatch',
      'Rubber bung on string',
      'Glass tube or rotating platform',
      'Marker for counting rotations',
    ],
    safety: [
      'Ensure clear space around apparatus',
      'Secure all masses properly',
      'Wear safety glasses',
      'Start with low speeds',
      'Check string/cord is not frayed',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag7',
    name: 'PAG 7: Simple Harmonic Motion',
    description: 'Investigate simple harmonic motion using a mass-spring system or pendulum',
    icon: '🕰️',
    color: 'bg-violet-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-shm', 'physics-oscillations'],
    equipment: [
      'Springs (various spring constants)',
      'Slotted masses and hanger',
      'Clamp stand',
      'Metre ruler',
      'Stopwatch',
      'Fiducial marker',
      'Pendulum bob and string',
      'Position sensor (optional)',
    ],
    safety: [
      'Secure clamp stand',
      'Keep clear of oscillating masses',
      'Do not overload springs',
      'Use small amplitudes',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag8',
    name: "PAG 8: Boyle's Law",
    description: "Investigate the relationship between pressure and volume of a gas at constant temperature",
    icon: '🎈',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal', 'physics-gases'],
    equipment: [
      "Boyle's Law apparatus",
      'Syringe or oil column',
      'Pressure gauge',
      'Ruler',
      'Foot pump or pressure source',
      'Thermometer',
    ],
    safety: [
      'Do not exceed pressure limits',
      'Ensure connections are secure',
      'Release pressure slowly',
      'Keep apparatus away from face',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag9',
    name: 'PAG 9: Force on a Current-Carrying Wire',
    description: 'Investigate the relationship between current, magnetic flux density, and force on a wire',
    icon: '🧲',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-magnetism', 'physics-electromagnetism'],
    equipment: [
      'Top pan balance',
      'Horseshoe magnet or electromagnet',
      'Wire frame or stiff wire',
      'Power supply',
      'Ammeter',
      'Variable resistor',
      'Clamp stand',
      'Connecting wires',
    ],
    safety: [
      'Strong magnets - keep away from electronics',
      'Wire can get hot at high currents',
      'Secure the balance',
      'Use appropriate current range',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag10',
    name: 'PAG 10: Magnetic Flux Linkage',
    description: 'Investigate magnetic flux linkage and electromagnetic induction using a search coil',
    icon: '🌀',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electromagnetism', 'physics-induction'],
    equipment: [
      'Search coil',
      'Oscilloscope or data logger',
      'Signal generator',
      'Solenoid',
      'Bar magnet',
      'Connecting wires',
      'Ruler',
      'Known magnetic field source',
    ],
    safety: [
      'Handle oscilloscope carefully',
      'Do not drop magnets',
      'Keep magnets away from electronic devices',
      'Secure connecting wires',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag11',
    name: 'PAG 11: Speed of Sound',
    description: 'Measure the speed of sound using stationary waves or time-of-flight methods',
    icon: '🔊',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves', 'physics-sound'],
    equipment: [
      'Resonance tube or Kundt\'s tube',
      'Tuning forks (various frequencies)',
      'Signal generator and loudspeaker',
      'Microphone',
      'Oscilloscope',
      'Metre ruler',
      'Water (for resonance tube)',
    ],
    safety: [
      'Keep sound levels reasonable',
      'Handle glass tubes carefully',
      'Avoid water spills near electrical equipment',
      'Handle tuning forks carefully',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'ocr-alevel-physics-pag12',
    name: 'PAG 12: Wave Properties',
    description: 'Investigate wave properties including interference, diffraction, and stationary waves',
    icon: '🌈',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves', 'physics-optics'],
    equipment: [
      'Laser (Class 2)',
      'Double slit',
      'Diffraction grating',
      'Screen',
      'Metre ruler',
      'Vernier calipers',
      'Darkened room',
      'Ripple tank (for water waves)',
    ],
    safety: [
      'Never look directly into laser beam',
      'Remove reflective objects',
      'Use Class 2 laser only',
      'Display laser warning signs',
      'Take care with water near electrical equipment',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
  },
];
