// AQA GCSE Chemistry Required Practicals
// Based on AQA 8462 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaGcseChemistryPracticals: Practical[] = [
  {
    id: 'aqa-gcse-chemistry-rp1',
    name: 'RP1: Making Salts',
    description: 'Preparation of a pure, dry sample of a soluble salt from an insoluble oxide or carbonate',
    icon: '🧂',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-chemical-changes'],
    equipment: [
      'Beaker',
      'Bunsen burner, tripod, gauze',
      'Evaporating basin',
      'Filter funnel and paper',
      'Glass rod',
      'Measuring cylinder',
      'Dilute acid (HCl or H₂SO₄)',
      'Metal oxide or carbonate',
      'Spatula',
    ],
    safety: [
      'Wear safety goggles throughout',
      'Acids are corrosive - handle carefully',
      'Take care with hot apparatus',
      'Wash hands after handling chemicals',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp2',
    name: 'RP2: Electrolysis',
    description: 'Investigate electrolysis of aqueous solutions using inert electrodes',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-chemical-changes'],
    equipment: [
      'Electrolysis cell',
      'Carbon/graphite electrodes (inert)',
      'Power supply (DC)',
      'Ammeter',
      'Connecting wires with crocodile clips',
      'Test tubes (for collecting gases)',
      'Various electrolyte solutions (CuSO₄, NaCl, H₂SO₄)',
      'Splint and lighted splint',
    ],
    safety: [
      'Wear safety goggles',
      'Chlorine gas is toxic - work in well-ventilated area',
      'Do not touch electrodes when power is on',
      'Handle acids carefully',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp3',
    name: 'RP3: Temperature Changes',
    description: 'Investigate the variables that affect temperature changes in chemical reactions',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-energy-changes'],
    equipment: [
      'Polystyrene cup (insulated)',
      'Thermometer (-10 to 110°C)',
      'Measuring cylinder',
      'Balance',
      'Spatula',
      'Dilute acid',
      'Alkali solution',
      'Metal powder or carbonate',
      'Stopwatch',
    ],
    safety: [
      'Wear safety goggles',
      'Some reactions are exothermic - take care',
      'Handle acids and alkalis carefully',
      'Metal powders can be flammable',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp4',
    name: 'RP4: Rates - Temperature',
    description: 'Investigate how changes in temperature affect the rate of reaction',
    icon: '🔥',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-rates'],
    equipment: [
      'Conical flask',
      'Delivery tube and bung',
      'Gas syringe or measuring cylinder (inverted)',
      'Water bath or Bunsen burner',
      'Thermometer',
      'Stopwatch',
      'Sodium thiosulfate solution',
      'Dilute hydrochloric acid',
      'Paper with cross marked on it',
    ],
    safety: [
      'Wear safety goggles',
      'Sulfur dioxide produced - work in well-ventilated area',
      'Take care with hot water baths',
      'Handle acids carefully',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp5',
    name: 'RP5: Rates - Concentration',
    description: 'Investigate how changes in concentration affect the rate of reaction',
    icon: '📊',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-rates'],
    equipment: [
      'Conical flask',
      'Gas syringe or measuring cylinder',
      'Delivery tube and bung',
      'Stopwatch',
      'Measuring cylinders (various sizes)',
      'Dilute hydrochloric acid (various concentrations)',
      'Marble chips (calcium carbonate)',
      'Balance',
    ],
    safety: [
      'Wear safety goggles',
      'Handle acids carefully',
      'Carbon dioxide is produced - ensure ventilation',
      'Marble chips can have sharp edges',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp6',
    name: 'RP6: Chromatography',
    description: 'Investigate how paper chromatography can be used to separate and identify substances',
    icon: '🎨',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-atomic-structure'],
    equipment: [
      'Chromatography paper',
      'Beaker with lid',
      'Solvent (water or ethanol)',
      'Pencil',
      'Ruler',
      'Capillary tube or fine glass rod',
      'Various inks or food colourings',
      'Reference substances',
    ],
    safety: [
      'Some solvents are flammable - no naked flames',
      'Work in well-ventilated area if using organic solvents',
      'Avoid skin contact with solvents',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp7',
    name: 'RP7: Water Purification',
    description: 'Analyse and purify water samples including testing for pH and dissolved solids',
    icon: '💧',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-atmosphere'],
    equipment: [
      'Evaporating basin',
      'Bunsen burner, tripod, gauze',
      'Balance',
      'pH meter or universal indicator',
      'Distillation apparatus',
      'Measuring cylinder',
      'Water samples (tap, river, sea)',
      'Filter funnel and paper',
    ],
    safety: [
      'Wear safety goggles',
      'Take care with hot apparatus',
      'Do not drink any water samples',
      'Natural water samples may contain pathogens',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
  {
    id: 'aqa-gcse-chemistry-rp8',
    name: 'RP8: Identifying Ions',
    description: 'Use chemical tests to identify metal ions and non-metal ions in compounds',
    icon: '🔬',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-chemistry-chemical-analysis'],
    equipment: [
      'Test tubes and rack',
      'Bunsen burner',
      'Wooden splints',
      'Nichrome wire loops',
      'Dilute acids (HCl, HNO₃, H₂SO₄)',
      'Sodium hydroxide solution',
      'Silver nitrate solution',
      'Barium chloride solution',
      'Various ionic compounds to test',
    ],
    safety: [
      'Wear safety goggles',
      'Silver nitrate stains skin - wear gloves',
      'Barium compounds are toxic - handle carefully',
      'Some precipitates are harmful - do not touch',
      'Acids and alkalis are corrosive',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
  },
];
