// OCR Gateway GCSE Biology A Practical Activity Groups (PAGs)
// Based on OCR J247 specification
// Note: OCR uses a flexible PAG approach - activities can be varied while meeting skill requirements

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrGcseBiologyPracticals: Practical[] = [
  {
    id: 'ocr-gcse-biology-pag1',
    name: 'PAG 1: Microscopy',
    description: 'Use a light microscope to make observations and drawings of biological specimens',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-cell-level-systems'],
    equipment: [
      'Light microscope',
      'Prepared slides',
      'Blank slides and cover slips',
      'Dropping pipettes',
      'Iodine solution',
      'Methylene blue stain',
      'Forceps',
      'Mounted needle',
      'Filter paper',
      'Stage micrometer (for calibration)',
    ],
    safety: [
      'Handle glass slides carefully',
      'Iodine can stain skin and clothing',
      'Methylene blue is an irritant',
      'Take care with sharp instruments',
      'Report broken glass immediately',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'ocr-gcse-biology-pag2',
    name: 'PAG 2: Enzyme Investigation',
    description: 'Investigate the effect of a factor (e.g., pH, temperature) on enzyme activity',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-cell-level-systems'],
    equipment: [
      'Test tubes and rack',
      'Water baths at different temperatures',
      'Spotting tile',
      'Dropping pipettes',
      'Amylase or other enzyme',
      'Starch solution',
      'Buffer solutions (various pH)',
      'Iodine solution',
      'Stopwatch',
      'Thermometer',
    ],
    safety: [
      'Wear safety goggles',
      'Take care with hot water baths',
      'Some buffer solutions are irritants',
      'Wash hands after handling enzymes',
      'Iodine can stain',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'ocr-gcse-biology-pag3',
    name: 'PAG 3: Photosynthesis Investigation',
    description: 'Investigate the rate of photosynthesis using aquatic plants',
    icon: '🌿',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-cell-level-systems'],
    equipment: [
      'Pondweed (Elodea or Cabomba)',
      'Large beaker or tank',
      'Lamp',
      'Metre ruler',
      'Stopwatch',
      'Thermometer',
      'Sodium hydrogencarbonate',
      'Boiling tube or gas syringe',
      'Funnel',
      'Paper clip or weight',
    ],
    safety: [
      'Take care with electrical equipment near water',
      'Allow lamp to cool before moving',
      'Wash hands after handling pondweed',
      'Be aware of heat from lamp',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'ocr-gcse-biology-pag4',
    name: 'PAG 4: Osmosis',
    description: 'Investigate osmosis in plant cells or tissue',
    icon: '💧',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-cell-level-systems'],
    equipment: [
      'Potato or other plant tissue',
      'Cork borer',
      'Scalpel',
      'Ruler',
      'Electronic balance',
      'Beakers or boiling tubes',
      'Sucrose or salt solutions (various concentrations)',
      'Distilled water',
      'Paper towels',
      'Tile',
    ],
    safety: [
      'Take care when using sharp cutting instruments',
      'Handle glassware carefully',
      'Wash hands after handling plant material',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'ocr-gcse-biology-pag5',
    name: 'PAG 5: Reaction Time',
    description: 'Investigate factors affecting human reaction time',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-organism-level'],
    equipment: [
      'Metre ruler or 30 cm ruler',
      'Calculator',
      'Computer reaction time test (optional)',
      'Table and chairs',
      'Data recording sheets',
    ],
    safety: [
      'Ensure informed consent from participants',
      'Be aware of any medical conditions',
      'Conduct tests in safe environment',
      'If investigating caffeine - check dietary restrictions',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'ocr-gcse-biology-pag6',
    name: 'PAG 6: Sampling Techniques',
    description: 'Use sampling techniques to estimate the population size and distribution of organisms',
    icon: '📊',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-gcse-biology-community'],
    equipment: [
      'Quadrat (0.5m × 0.5m)',
      'Tape measures',
      'Random number generator/table',
      'Identification keys',
      'Tally counter',
      'Recording sheets',
      'Calculator',
      'Pooter (for invertebrates)',
      'Pitfall traps (optional)',
      'Light meter (optional)',
    ],
    safety: [
      'Follow fieldwork safety guidelines',
      'Wear appropriate clothing and footwear',
      'Be aware of hazards in the habitat',
      'Wash hands after fieldwork',
      'Work in groups where possible',
      'Inform someone of your location',
      'Handle organisms carefully and return them',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'biology',
  },
];
