// Edexcel GCSE Biology Core Practicals
// Based on Edexcel 1BI0 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelGcseBiologyPracticals: Practical[] = [
  {
    id: 'edexcel-gcse-biology-cp1',
    name: 'CP1: Microscopy',
    description: 'Investigate biological specimens using microscopes, including magnification calculations and labelled diagrams',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-cells'],
    equipment: [
      'Light microscope',
      'Prepared slides',
      'Blank slides and cover slips',
      'Dropping pipettes',
      'Iodine solution',
      'Methylene blue stain',
      'Forceps',
      'Mounted needle',
      'Filter paper',
      'Graph paper',
    ],
    safety: [
      'Handle glass slides carefully - can break and cut',
      'Iodine can stain skin and clothing',
      'Methylene blue is an irritant',
      'Take care with sharp instruments',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp2',
    name: 'CP2: Enzyme Activity',
    description: 'Investigate the effect of pH on enzyme activity',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-cells'],
    equipment: [
      'Test tubes and rack',
      'Water bath',
      'Spotting tile',
      'Dropping pipettes',
      'Amylase solution',
      'Starch solution',
      'Buffer solutions (pH 4-9)',
      'Iodine solution',
      'Stopwatch',
      'Thermometer',
    ],
    safety: [
      'Wear safety goggles',
      'Some buffer solutions are irritants',
      'Take care with hot water bath',
      'Wash hands after handling enzymes',
      'Iodine can stain',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp3',
    name: 'CP3: Osmosis',
    description: 'Investigate osmosis in plant tissue',
    icon: '💧',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-cells'],
    equipment: [
      'Potato or other plant tissue',
      'Cork borer',
      'Scalpel or knife',
      'Ruler',
      'Electronic balance',
      'Boiling tubes or beakers',
      'Sucrose solutions (various concentrations)',
      'Distilled water',
      'Paper towels',
      'Tile',
    ],
    safety: [
      'Take care when using sharp cutting instruments',
      'Handle glassware carefully',
      'Wash hands after handling plant material',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp4',
    name: 'CP4: Reaction Time',
    description: 'Investigate the effect of a factor on human reaction time',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-systems'],
    equipment: [
      'Metre ruler or 30 cm ruler',
      'Calculator',
      'Computer reaction time test (optional)',
      'Table and chairs',
      'Data recording sheets',
    ],
    safety: [
      'Ensure informed consent from participants',
      'Be aware of any medical conditions',
      'Conduct tests in safe environment',
      'If investigating caffeine - be aware of dietary restrictions',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp5',
    name: 'CP5: Photosynthesis Rate',
    description: 'Investigate the rate of photosynthesis in an aquatic plant',
    icon: '🌿',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-plant-structures'],
    equipment: [
      'Pondweed (Elodea or Cabomba)',
      'Beaker or tank',
      'Lamp or light source',
      'Metre ruler',
      'Stopwatch',
      'Thermometer',
      'Sodium hydrogencarbonate',
      'Boiling tube or gas syringe',
      'Funnel',
      'Paper clip or weight',
    ],
    safety: [
      'Take care with electrical equipment near water',
      'Allow lamp to cool before handling',
      'Wash hands after handling pondweed',
      'Be aware of heat from lamp',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp6',
    name: 'CP6: Transpiration',
    description: 'Investigate the effect of environmental conditions on the rate of transpiration',
    icon: '🌱',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-plant-structures'],
    equipment: [
      'Potometer',
      'Leafy shoot (e.g., privet)',
      'Bowl of water',
      'Vaseline or petroleum jelly',
      'Fan',
      'Lamp',
      'Plastic bag',
      'Stopwatch',
      'Ruler',
      'Thermometer',
    ],
    safety: [
      'Take care when cutting shoots',
      'Handle glass potometer carefully',
      'Be aware of electrical equipment near water',
      'Vaseline may be irritant to some',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp7',
    name: 'CP7: Heart Dissection',
    description: 'Dissect and examine the structure of the heart',
    icon: '❤️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-exchange'],
    equipment: [
      'Heart (pig or lamb)',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Mounted needle',
      'Paper towels',
      'Disposable gloves',
    ],
    safety: [
      'Wear disposable gloves throughout',
      'Take extreme care with sharp instruments',
      'Wash hands thoroughly after handling',
      'Dispose of biological material appropriately',
      'Be respectful of specimens',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'edexcel-gcse-biology-cp8',
    name: 'CP8: Sampling',
    description: 'Use sampling techniques to estimate the population size of a species in a given area',
    icon: '📊',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-gcse-biology-ecosystems'],
    equipment: [
      'Quadrat (0.5m × 0.5m)',
      'Tape measures',
      'Random number generator/table',
      'Identification keys',
      'Tally counter',
      'Recording sheets',
      'Calculator',
      'Pooter (for invertebrates)',
      'Camera (optional)',
    ],
    safety: [
      'Conduct fieldwork safely',
      'Wear appropriate clothing and footwear',
      'Be aware of hazards in the habitat',
      'Wash hands after fieldwork',
      'Work in groups where possible',
      'Inform others of your location',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'biology',
  },
];
