// Edexcel A-Level Chemistry Core Practicals
// Based on Edexcel 9CH0 specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/chemistry-2015.html

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelALevelChemistryPracticals: Practical[] = [
  {
    id: 'edexcel-alevel-chemistry-cp1',
    name: 'CP1: Molar Volume of a Gas',
    description: 'Measure the molar volume of a gas by measuring the volume of gas produced from a known mass of reactant',
    icon: '💨',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-amounts'],
    equipment: [
      'Conical flask',
      'Delivery tube',
      'Gas syringe or inverted measuring cylinder',
      'Trough of water',
      'Balance (0.01g precision)',
      'Marble chips or metal',
      'Dilute hydrochloric acid',
      'Thermometer',
      'Barometer (for pressure reading)',
    ],
    safety: [
      'Wear safety glasses',
      'Dilute acid is an irritant',
      'Hydrogen is flammable - no naked flames if using metals',
      'Ensure good ventilation',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp2',
    name: 'CP2: Standard Solution Preparation',
    description: 'Preparation of a standard solution from a solid acid',
    icon: '⚖️',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-amounts'],
    equipment: [
      'Volumetric flask (250 cm³)',
      'Balance (0.01g precision)',
      'Weighing boat or bottle',
      'Beaker',
      'Stirring rod',
      'Wash bottle with distilled water',
      'Funnel',
      'Solid acid (e.g., oxalic acid or potassium hydrogen phthalate)',
    ],
    safety: [
      'Wear safety glasses',
      'Handle solid acids carefully',
      'Use distilled water throughout',
      'Ensure all solid has dissolved before making up to volume',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp3',
    name: 'CP3: Acid-Base Titration',
    description: 'Finding the concentration of a solution of hydrochloric acid by titration',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-amounts', 'edexcel-alevel-chemistry-acids-bases'],
    equipment: [
      'Burette and stand',
      'Pipette (25 cm³) and filler',
      'Conical flasks',
      'White tile',
      'Standard solution (from CP2)',
      'Hydrochloric acid (unknown concentration)',
      'Suitable indicator',
      'Wash bottle',
    ],
    safety: [
      'Wear safety glasses',
      'Handle acids and bases with care',
      'Clean up spills immediately',
      'Use pipette filler - never mouth pipette',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp4',
    name: 'CP4: Halogenoalkane Hydrolysis Rates',
    description: 'Investigation of the rates of hydrolysis of halogenoalkanes',
    icon: '⏱️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-organic1', 'edexcel-alevel-chemistry-kinetics1'],
    equipment: [
      'Test tubes and rack',
      'Water bath',
      'Stopwatch',
      '1-chlorobutane, 1-bromobutane, 1-iodobutane',
      'Ethanol',
      'Silver nitrate solution',
      'Thermometer',
      'Measuring cylinders',
    ],
    safety: [
      'Wear safety glasses',
      'Halogenoalkanes are volatile and harmful',
      'Work in fume cupboard',
      'Silver nitrate stains skin',
      'Ethanol is flammable',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp5',
    name: 'CP5: Oxidation of Ethanol',
    description: 'The oxidation of ethanol using acidified potassium dichromate',
    icon: '🍷',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-organic1'],
    equipment: [
      'Round-bottomed flask',
      'Distillation apparatus',
      'Liebig condenser',
      'Thermometer',
      'Ethanol',
      'Acidified potassium dichromate',
      'Anti-bumping granules',
      'Heating mantle',
      'Ice bath',
    ],
    safety: [
      'Wear safety glasses',
      'Ethanol is highly flammable',
      'Potassium dichromate is carcinogenic and toxic',
      'Work in fume cupboard',
      'Never heat a sealed system',
      'Ensure water is flowing through condenser before heating',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp6',
    name: 'CP6: Chlorination of 2-methylpropan-2-ol',
    description: 'Preparation of a halogenoalkane from an alcohol using an SN1 mechanism',
    icon: '⚗️',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-organic1'],
    equipment: [
      'Separating funnel',
      'Conical flask',
      '2-methylpropan-2-ol',
      'Concentrated hydrochloric acid',
      'Sodium hydrogencarbonate solution',
      'Anhydrous calcium chloride',
      'Distillation apparatus',
      'Ice bath',
    ],
    safety: [
      'Wear safety glasses',
      'Concentrated HCl is corrosive and produces fumes',
      'Work in fume cupboard',
      'Product is volatile and flammable',
      'Handle separating funnel with care - vent regularly',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp7',
    name: 'CP7: Analysis of Unknowns',
    description: 'Analysis of inorganic and organic unknowns using qualitative tests',
    icon: '🔍',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-inorganic1', 'edexcel-alevel-chemistry-analysis1'],
    equipment: [
      'Test tubes and rack',
      'Bunsen burner',
      'Nichrome wire',
      'Dilute sodium hydroxide',
      'Dilute ammonia',
      'Dilute acids (HCl, HNO₃, H₂SO₄)',
      'Silver nitrate solution',
      'Barium chloride solution',
      '2,4-DNP reagent',
      "Tollens' reagent",
    ],
    safety: [
      'Wear safety glasses',
      'Barium chloride is toxic',
      'Ammonia is irritant - use in fume cupboard',
      "Tollens' reagent must be freshly prepared",
      '2,4-DNP can be explosive when dry',
      'Silver nitrate stains skin',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp8',
    name: "CP8: Hess's Law Enthalpy",
    description: "Determining an enthalpy change indirectly using Hess's Law",
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-energetics1', 'edexcel-alevel-chemistry-energetics2'],
    equipment: [
      'Polystyrene cup with lid',
      'Thermometer (0.1°C precision)',
      'Measuring cylinder',
      'Balance',
      'Anhydrous copper sulfate',
      'Hydrated copper sulfate',
      'Distilled water',
      'Spatula',
      'Stopwatch',
    ],
    safety: [
      'Wear safety glasses',
      'Copper sulfate is harmful',
      'Reaction may be exothermic',
      'Handle hot solutions with care',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp9',
    name: 'CP9: Ka of a Weak Acid',
    description: 'Finding the Ka value for a weak acid using pH measurement',
    icon: '📊',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-acids-bases', 'edexcel-alevel-chemistry-equilibrium2'],
    equipment: [
      'pH meter or probe',
      'Burette',
      'Pipette and filler',
      'Conical flask',
      'Weak acid (e.g., ethanoic acid)',
      'Strong base (e.g., NaOH)',
      'Standard buffer solutions (for calibration)',
      'Magnetic stirrer (optional)',
      'Wash bottle',
    ],
    safety: [
      'Wear safety glasses',
      'Sodium hydroxide is corrosive',
      'Calibrate pH meter before use',
      'Handle glass electrode carefully',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp10',
    name: 'CP10: Electrochemical Cells',
    description: 'Investigate electrochemical cells and determine electrode potentials',
    icon: '🔋',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-redox2'],
    equipment: [
      'Metal electrodes (Zn, Cu, Fe, Ag)',
      'Metal salt solutions (1.0 mol dm⁻³)',
      'Beakers',
      'Salt bridge',
      'High resistance voltmeter',
      'Connecting wires with crocodile clips',
      'Filter paper',
      'Potassium nitrate solution',
    ],
    safety: [
      'Wear safety glasses',
      'Some metal salts are toxic',
      'Handle electrodes carefully',
      'Clean up spills immediately',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp11',
    name: 'CP11: Redox Titration',
    description: 'Redox titration to determine concentration (e.g., iron(II) with potassium manganate(VII))',
    icon: '🧫',
    color: 'bg-fuchsia-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-redox1', 'edexcel-alevel-chemistry-transition-metals'],
    equipment: [
      'Burette',
      'Pipette and filler',
      'Conical flask',
      'White tile',
      'Potassium manganate(VII) solution',
      'Iron(II) solution (acidified)',
      'Dilute sulfuric acid',
      'Wash bottle',
    ],
    safety: [
      'Wear safety glasses',
      'Potassium manganate(VII) is an oxidizer and stains',
      'Sulfuric acid is corrosive',
      'Clean up spills immediately',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp12',
    name: 'CP12: Transition Metal Complex',
    description: 'Preparation of a transition metal complex (e.g., [Cu(NH₃)₄(H₂O)₂]²⁺)',
    icon: '🎨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-transition-metals'],
    equipment: [
      'Beaker',
      'Measuring cylinder',
      'Copper sulfate solution',
      'Concentrated ammonia solution',
      'Stirring rod',
      'Filter funnel and paper',
      'Wash bottle with ethanol',
      'Watch glass',
    ],
    safety: [
      'Wear safety glasses',
      'Concentrated ammonia is corrosive and produces harmful fumes',
      'Work in fume cupboard',
      'Copper compounds are harmful to aquatic life',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp13',
    name: 'CP13: Iodine-Propanone Reaction',
    description: 'Following the rate of the iodine-propanone reaction (clock reaction)',
    icon: '⏰',
    color: 'bg-violet-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-kinetics2'],
    equipment: [
      'Conical flasks',
      'Measuring cylinders',
      'Stopwatch',
      'Iodine solution',
      'Propanone',
      'Sulfuric acid',
      'Sodium thiosulfate solution',
      'White tile',
      'Colorimeter (optional)',
    ],
    safety: [
      'Wear safety glasses',
      'Propanone is highly flammable',
      'Work away from flames',
      'Iodine is irritant and stains',
      'Sulfuric acid is corrosive',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp14',
    name: 'CP14: Activation Energy',
    description: 'Finding the activation energy of a reaction using the Arrhenius equation',
    icon: '📈',
    color: 'bg-rose-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-kinetics2'],
    equipment: [
      'Conical flask',
      'Water baths at various temperatures',
      'Thermometer',
      'Stopwatch',
      'Sodium thiosulfate solution',
      'Hydrochloric acid',
      'White paper with cross',
      'Measuring cylinders',
      'Graph paper or computer for analysis',
    ],
    safety: [
      'Wear safety glasses',
      'Sulfur dioxide produced - work in fume cupboard',
      'Take care with hot water baths',
      'Dilute acid is irritant',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp15',
    name: 'CP15: Organic Analysis (Spectra)',
    description: 'Analysis of organic unknowns using NMR, IR, and mass spectrometry data',
    icon: '📋',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-analysis1', 'edexcel-alevel-chemistry-analysis2'],
    equipment: [
      'IR spectra (provided)',
      'NMR spectra (¹H and ¹³C)',
      'Mass spectra',
      'Data tables for chemical shifts',
      'IR correlation charts',
      'Calculator',
      'Unknown organic samples',
    ],
    safety: [
      'This is primarily a data analysis practical',
      'If handling samples: wear safety glasses',
      'Organic unknowns may be flammable or harmful',
      'Work in fume cupboard if using samples',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'edexcel-alevel-chemistry-cp16',
    name: 'CP16: Preparation of Aspirin',
    description: 'Preparation, purification and testing of aspirin (2-acetoxybenzoic acid)',
    icon: '💊',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-chemistry-organic2', 'edexcel-alevel-chemistry-organic3'],
    equipment: [
      '2-hydroxybenzoic acid (salicylic acid)',
      'Ethanoic anhydride',
      'Concentrated phosphoric acid (catalyst)',
      'Water bath',
      'Ice bath',
      'Buchner funnel and flask',
      'Filter paper',
      'Melting point apparatus',
      'Recrystallisation equipment',
      'Iron(III) chloride solution (for purity test)',
    ],
    safety: [
      'Wear safety glasses',
      'Ethanoic anhydride is corrosive and lachrymatory',
      'Work in fume cupboard',
      'Phosphoric acid is corrosive',
      'Product is for analysis only - DO NOT INGEST',
      'Allow apparatus to cool before handling',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'chemistry',
  },
];
