// AQA A-Level Chemistry Required Practicals
// Based on AQA 7405 specification
// Reference: https://www.aqa.org.uk/subjects/chemistry/a-level/chemistry-7405/specification/practical-assessment

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaALevelChemistryPracticals: Practical[] = [
  {
    id: 'aqa-alevel-chemistry-rp1',
    name: 'RP1: Volumetric Solution and Titration',
    description: 'Make up a volumetric solution and carry out a simple acid-base titration',
    icon: '🧪',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-quantitative', 'chemistry-acids-bases'],
    equipment: [
      'Volumetric flask (250 cm³)',
      'Balance (0.01g precision)',
      'Weighing boat',
      'Burette',
      'Pipette (25 cm³) and filler',
      'Conical flasks',
      'White tile',
      'Suitable indicator (phenolphthalein/methyl orange)',
      'Wash bottle',
    ],
    safety: [
      'Wear safety glasses',
      'Handle acids and alkalis carefully',
      'Some indicators are flammable',
      'Clean up spills immediately',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp2',
    name: 'RP2: Enthalpy Change',
    description: 'Measurement of an enthalpy change using calorimetry (neutralisation, combustion, or reaction)',
    icon: '🌡️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-energetics', 'chemistry-thermodynamics'],
    equipment: [
      'Polystyrene cup with lid (calorimeter)',
      'Thermometer (0.2°C precision)',
      'Measuring cylinder',
      'Balance',
      'Acids and alkalis or reactants',
      'Stopwatch',
      'Stirring rod',
      'Graph paper for extrapolation',
    ],
    safety: [
      'Wear safety glasses',
      'Exothermic reactions can cause temperature to rise rapidly',
      'Some reactants are corrosive',
      'Handle hot solutions with care',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp3',
    name: 'RP3: Rate of Reaction (Temperature)',
    description: 'Investigation of how the rate of a reaction changes with temperature',
    icon: '⏱️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-kinetics', 'chemistry-rates'],
    equipment: [
      'Conical flask',
      'Sodium thiosulfate solution',
      'Dilute hydrochloric acid',
      'Thermometer',
      'Water baths at various temperatures',
      'Stopwatch',
      'White paper with cross',
      'Measuring cylinders',
    ],
    safety: [
      'Wear safety glasses',
      'Sulfur dioxide produced - work in fume cupboard',
      'Dilute acid is irritant',
      'Take care with hot water baths',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp4',
    name: 'RP4: Identification of Ions',
    description: 'Carry out test-tube reactions to identify cations and anions',
    icon: '🔍',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-analysis', 'chemistry-ions'],
    equipment: [
      'Test tubes and rack',
      'Bunsen burner (for flame tests)',
      'Nichrome wire',
      'Dilute sodium hydroxide',
      'Dilute ammonia',
      'Dilute acids',
      'Silver nitrate solution',
      'Barium chloride solution',
      'Litmus paper',
    ],
    safety: [
      'Wear safety glasses',
      'Barium chloride is toxic',
      'Silver nitrate stains skin',
      'Ammonia is an irritant - use in fume cupboard',
      'Concentrated HCl for cleaning wire - use with care',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp5',
    name: 'RP5: Distillation',
    description: 'Distillation of a product from a reaction (e.g., preparation and purification of an organic liquid)',
    icon: '⚗️',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-organic', 'chemistry-purification'],
    equipment: [
      'Round-bottomed flask',
      'Quickfit distillation apparatus',
      'Liebig condenser',
      'Thermometer adapter and thermometer',
      'Receiving flask',
      'Heating mantle or water bath',
      'Anti-bumping granules',
      'Rubber tubing for water circulation',
    ],
    safety: [
      'Never heat a sealed system',
      'Ensure water flow through condenser before heating',
      'Many organic liquids are flammable',
      'Work in fume cupboard',
      'Use anti-bumping granules',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp6',
    name: 'RP6: Tests for Organic Functional Groups',
    description: 'Tests for alcohol, aldehyde, ketone, carboxylic acid, alkene functional groups',
    icon: '🧬',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-organic', 'chemistry-functional-groups'],
    equipment: [
      'Test tubes and rack',
      'Water bath',
      'Bromine water',
      "Fehling's solution or Tollens' reagent",
      '2,4-DNP reagent',
      'Sodium carbonate',
      'Acidified potassium dichromate',
      'Universal indicator',
    ],
    safety: [
      'Wear safety glasses',
      'Many organic compounds are flammable - no naked flames',
      'Bromine water is corrosive and toxic',
      '2,4-DNP is potentially explosive when dry',
      'Tollens reagent should be freshly prepared and disposed of immediately',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp7',
    name: 'RP7: Rate of Reaction (Initial Rates)',
    description: 'Measure the rate of a reaction by an initial rate method (e.g., iodine clock)',
    icon: '📊',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-kinetics', 'chemistry-rate-equations'],
    equipment: [
      'Conical flasks',
      'Measuring cylinders',
      'Stopwatch',
      'Solutions for iodine clock reaction',
      'Starch indicator',
      'Burette (for accurate volumes)',
      'White tile',
      'Thermometer',
    ],
    safety: [
      'Wear safety glasses',
      'Potassium iodate is an oxidizer',
      'Sulfuric acid is corrosive',
      'Work in well-ventilated area',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp8',
    name: 'RP8: Measuring EMF of Electrochemical Cells',
    description: 'Measure the EMF of electrochemical cells and investigate electrode potentials',
    icon: '🔋',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-electrochemistry', 'chemistry-redox'],
    equipment: [
      'Metal electrodes (zinc, copper, iron, etc.)',
      'Metal salt solutions (1.0 mol dm⁻³)',
      'Beakers',
      'Salt bridge (filter paper soaked in KNO₃)',
      'High resistance voltmeter',
      'Connecting wires with crocodile clips',
      'Reference electrode (optional)',
    ],
    safety: [
      'Wear safety glasses',
      'Some metal salts are toxic (e.g., copper, lead)',
      'Clean up spills immediately',
      'Handle electrodes with care',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp9',
    name: 'RP9: pH Curves and Buffers',
    description: 'Investigate how pH changes when a weak acid reacts with a strong base, and study buffer solutions',
    icon: '📈',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-acids-bases', 'chemistry-equilibria'],
    equipment: [
      'Burette',
      'Pipette and filler',
      'Conical flask',
      'pH meter or probe',
      'Weak acid (e.g., ethanoic acid)',
      'Strong base (e.g., NaOH)',
      'Buffer solution',
      'Magnetic stirrer (optional)',
      'Standard buffer solutions for calibration',
    ],
    safety: [
      'Wear safety glasses',
      'Sodium hydroxide is corrosive',
      'Handle pH electrodes carefully',
      'Calibrate pH meter before use',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp10',
    name: 'RP10: Preparation of Organic Solid (Aspirin)',
    description: 'Prepare and purify an organic solid, determine its melting point, and assess purity',
    icon: '💊',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-organic', 'chemistry-synthesis'],
    equipment: [
      '2-hydroxybenzoic acid (salicylic acid)',
      'Ethanoic anhydride',
      'Conical flask',
      'Water bath',
      'Ice bath',
      'Buchner funnel and flask',
      'Filter paper',
      'Melting point apparatus',
      'Balance',
    ],
    safety: [
      'Wear safety glasses',
      'Ethanoic anhydride is corrosive and lachrymatory',
      'Work in fume cupboard',
      'Phosphoric acid catalyst is corrosive',
      'Aspirin produced is for analysis only - do not ingest',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp11',
    name: 'RP11: Transition Metal Chemistry',
    description: 'Investigate the chemistry of transition metal compounds (complex ions, redox reactions, catalysis)',
    icon: '🎨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-transition-metals'],
    equipment: [
      'Test tubes and rack',
      'Transition metal salt solutions',
      'Sodium hydroxide solution',
      'Ammonia solution',
      'EDTA solution',
      'Hydrogen peroxide',
      'Potassium iodide',
      'Sodium thiosulfate',
    ],
    safety: [
      'Wear safety glasses',
      'Ammonia is an irritant',
      'Some transition metal compounds are toxic',
      'Hydrogen peroxide is an oxidizer',
      'Work in fume cupboard for ammonia reactions',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'aqa-alevel-chemistry-rp12',
    name: 'RP12: Thin Layer Chromatography',
    description: 'Separate species by thin-layer chromatography (TLC) and determine Rf values',
    icon: '📋',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['chemistry-analysis', 'chemistry-chromatography'],
    equipment: [
      'TLC plates (silica or alumina)',
      'Development tank with lid',
      'Suitable solvent system',
      'Capillary tubes or micropipettes',
      'UV lamp (254 nm)',
      'Pencil',
      'Ruler',
      'Iodine chamber (optional)',
      'Standard samples',
    ],
    safety: [
      'Wear safety glasses',
      'Many solvents are flammable - no naked flames',
      'Work in fume cupboard',
      'UV light can damage eyes - do not look directly at lamp',
      'Handle TLC plates by edges only',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'chemistry',
  },
];
