// AQA GCSE Physics Required Practicals
// Based on AQA 8463 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaGcsePhysicsPracticals: Practical[] = [
  {
    id: 'aqa-gcse-physics-rp1',
    name: 'RP1: Specific Heat Capacity',
    description: 'Investigate the specific heat capacity of materials including water and aluminium',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Electric heater/immersion heater',
      'Joulemeter or ammeter and voltmeter',
      'Thermometer (0.5°C precision)',
      'Insulating material',
      'Balance (0.1g precision)',
      'Stopwatch',
    ],
    safety: [
      'Hot surfaces - use insulation and handle with care',
      'Electrical equipment near water - keep dry',
      'Do not leave heater unattended',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp2',
    name: 'RP2: Thermal Insulation',
    description: 'Investigate how the amount of thermal energy transferred depends on insulation',
    icon: '🧤',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Boiling tubes or beakers',
      'Thermometer',
      'Stopwatch',
      'Various insulating materials (bubble wrap, felt, foam)',
      'Hot water',
      'Measuring cylinder',
    ],
    safety: [
      'Hot water can scald - handle carefully',
      'Use beaker tongs or insulated gloves',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp3',
    name: 'RP3: Resistance and Wire Length',
    description: 'Investigate how the resistance of a wire depends on its length',
    icon: '📏',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Metre ruler',
      'Constantan or nichrome wire',
      'Ammeter',
      'Voltmeter',
      'Power supply (low voltage DC)',
      'Crocodile clips',
      'Connecting wires',
    ],
    safety: [
      'Wire can get hot - do not touch during experiment',
      'Use low voltage power supply only',
      'Turn off between readings to prevent overheating',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp4',
    name: 'RP4: I-V Characteristics',
    description: 'Investigate the I-V characteristics of a filament lamp, diode, and resistor',
    icon: '💡',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Filament lamp',
      'Diode',
      'Fixed resistor',
      'Variable resistor',
      'Ammeter',
      'Voltmeter',
      'Power supply',
      'Connecting wires',
    ],
    safety: [
      'Filament lamp gets hot - do not touch',
      'Diode can be damaged by reverse voltage - check polarity',
      'Use appropriate current ranges',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp5',
    name: 'RP5: Density',
    description: 'Determine the density of regular and irregular shaped objects',
    icon: '⚖️',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-particle-model'],
    equipment: [
      'Balance (0.1g precision)',
      'Ruler/vernier calipers',
      'Measuring cylinder',
      'Eureka can (displacement can)',
      'Various regular objects (cubes, cylinders)',
      'Various irregular objects (stones, keys)',
      'Water',
    ],
    safety: [
      'Glass measuring cylinders can break - handle carefully',
      'Clean up water spills immediately',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp6',
    name: 'RP6: Force and Extension',
    description: 'Investigate the relationship between force and extension for a spring',
    icon: '🔩',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Spring',
      'Clamp stand and clamp',
      'Ruler',
      'Slotted masses and hanger',
      'Pointer/marker',
      'Safety goggles',
    ],
    safety: [
      'Wear safety goggles - springs can snap',
      'Do not exceed elastic limit',
      'Secure clamp stand to prevent toppling',
      'Keep feet clear of falling masses',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp7',
    name: 'RP7: Acceleration (F=ma)',
    description: 'Investigate the relationship between force, mass, and acceleration',
    icon: '🚀',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Dynamics trolley',
      'Ramp/track',
      'Light gates or ticker timer',
      'Slotted masses',
      'Pulley',
      'String',
      'Balance',
      'Ruler',
    ],
    safety: [
      'Ensure trolley cannot fall off track',
      'Use buffers at end of track',
      'Keep feet clear of falling masses',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp8',
    name: 'RP8: Waves',
    description: 'Investigate waves in a ripple tank and waves on a string',
    icon: '🌊',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ripple tank with motor',
      'Lamp/strobe light',
      'Ruler',
      'Signal generator',
      'Vibration generator',
      'String/elastic cord',
      'Pulley and masses',
      'Metre ruler',
    ],
    safety: [
      'Water and electricity - keep equipment dry',
      'Strobe lighting can trigger seizures - warn students',
      'Do not look directly at strobe light',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp9',
    name: 'RP9: Radiation and Absorption',
    description: 'Investigate infrared radiation absorption and emission by different surfaces',
    icon: '☀️',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Leslie cube',
      'Infrared thermometer or thermocouple',
      'Boiling water',
      'Stopwatch',
      'Heat source (radiant heater)',
      'Metal plates (matt black, shiny silver, white)',
    ],
    safety: [
      'Hot water and surfaces - handle with care',
      'Do not touch Leslie cube during experiment',
      'Use heat-resistant mat',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'aqa-gcse-physics-rp10',
    name: 'RP10: Light - Reflection and Refraction',
    description: 'Investigate reflection and refraction of light using ray boxes',
    icon: '🔦',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ray box',
      'Power supply',
      'Plane mirror',
      'Rectangular glass/perspex block',
      'Protractor',
      'Ruler',
      'White paper',
      'Pins',
    ],
    safety: [
      'Do not look directly into ray box light',
      'Glass blocks can have sharp edges',
      'Take care with pins',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'physics',
  },
];
