// AQA GCSE Biology Required Practicals
// Based on AQA 8461 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaGcseBiologyPracticals: Practical[] = [
  {
    id: 'aqa-gcse-biology-rp1',
    name: 'RP1: Microscopy',
    description: 'Use a light microscope to observe, draw and label a selection of plant and animal cells',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-cell-biology'],
    equipment: [
      'Light microscope',
      'Prepared slides (cheek cells, onion cells)',
      'Glass slides and cover slips',
      'Dropping pipettes',
      'Iodine solution',
      'Methylene blue stain',
      'Forceps',
      'Mounted needle',
      'Filter paper',
    ],
    safety: [
      'Handle glass slides carefully',
      'Iodine can stain skin and clothing',
      'Methylene blue is an irritant',
      'Take care when using sharp instruments',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp2',
    name: 'RP2: Osmosis',
    description: 'Investigate the effect of a range of concentrations of salt or sugar solutions on the mass of plant tissue',
    icon: '💧',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-cell-biology'],
    equipment: [
      'Potato or other plant tissue',
      'Cork borer',
      'Scalpel',
      'Ruler',
      'Electronic balance',
      'Beakers or boiling tubes',
      'Sucrose or salt solutions (various concentrations)',
      'Distilled water',
      'Paper towels',
      'Tile',
    ],
    safety: [
      'Take care when using sharp instruments',
      'Wash hands after handling plant material',
      'Take care with glassware',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp3',
    name: 'RP3: Food Tests',
    description: 'Use qualitative reagents to test for a range of carbohydrates, lipids and proteins',
    icon: '🍎',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-organisation'],
    equipment: [
      'Test tubes and rack',
      'Bunsen burner, tripod, gauze',
      'Water bath',
      'Dropping pipettes',
      'Benedict\'s solution',
      'Iodine solution',
      'Biuret reagent',
      'Ethanol',
      'Food samples',
      'White tile',
    ],
    safety: [
      'Wear safety goggles',
      'Benedict\'s test requires hot water - take care',
      'Ethanol is flammable - no naked flames nearby',
      'Biuret reagent contains copper sulfate - irritant',
      'Some reagents are corrosive',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp4',
    name: 'RP4: Enzymes',
    description: 'Investigate the effect of pH on the rate of reaction of amylase enzyme',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-organisation'],
    equipment: [
      'Test tubes and rack',
      'Water bath at 35°C',
      'Spotting tile',
      'Dropping pipettes',
      'Amylase solution',
      'Starch solution',
      'Buffer solutions (various pH)',
      'Iodine solution',
      'Stopwatch',
      'Thermometer',
    ],
    safety: [
      'Wear safety goggles',
      'Some buffer solutions are irritants',
      'Take care with hot water bath',
      'Wash hands after handling enzymes',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp5',
    name: 'RP5: Photosynthesis',
    description: 'Investigate the effect of light intensity on the rate of photosynthesis using an aquatic organism such as pondweed',
    icon: '🌿',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-bioenergetics'],
    equipment: [
      'Pondweed (Elodea or Cabomba)',
      'Beaker',
      'Lamp',
      'Metre ruler',
      'Stopwatch',
      'Thermometer',
      'Sodium hydrogencarbonate (to provide CO₂)',
      'Boiling tube or measuring cylinder',
      'Funnel',
      'Paper clip or weight',
    ],
    safety: [
      'Take care with electrical equipment near water',
      'Allow lamp to cool before moving',
      'Wash hands after handling pondweed',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp6',
    name: 'RP6: Reaction Time',
    description: 'Plan and carry out an investigation into the effect of a factor on human reaction time',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-homeostasis'],
    equipment: [
      'Ruler (30 cm or metre)',
      'Calculator',
      'Stopwatch (optional)',
      'Computer reaction time test (optional)',
      'Table and chair',
    ],
    safety: [
      'Ensure participants consent to testing',
      'Be aware of any medical conditions',
      'Avoid testing with caffeine if investigating its effect',
      'No running or dangerous activities',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp7',
    name: 'RP7: Plant Responses',
    description: 'Investigate the effect of light or gravity on the growth of newly germinated seedlings',
    icon: '🌱',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-homeostasis'],
    equipment: [
      'Petri dishes',
      'Cotton wool or filter paper',
      'Cress or bean seeds',
      'Light-proof box or tin',
      'Lamp',
      'Ruler',
      'Clinostat (optional)',
      'Camera or phone (for recording)',
    ],
    safety: [
      'Wash hands after handling seeds',
      'Some seeds may be treated with fungicide',
      'Handle electrical equipment carefully',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp8',
    name: 'RP8: Sampling',
    description: 'Measure the population size of a common species in a habitat using sampling techniques',
    icon: '📊',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-ecology'],
    equipment: [
      'Quadrat (0.5m × 0.5m)',
      'Tape measure or metre ruler',
      'Random number generator/table',
      'Identification key',
      'Tally counter',
      'Recording sheet',
      'Calculator',
      'Camera (optional)',
    ],
    safety: [
      'Be aware of surroundings in fieldwork',
      'Wear appropriate clothing and footwear',
      'Wash hands after fieldwork',
      'Be aware of any hazards in the habitat',
      'Work in pairs or groups',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp9',
    name: 'RP9: Field Investigation',
    description: 'Investigate the effect of an environmental factor on the distribution of a species in an ecosystem',
    icon: '🌍',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-ecology'],
    equipment: [
      'Quadrats',
      'Tape measures',
      'Transect line',
      'Light meter',
      'pH probe or universal indicator',
      'Thermometer',
      'Identification keys',
      'Recording sheets',
      'Compass',
    ],
    safety: [
      'Follow fieldwork safety guidelines',
      'Wear appropriate clothing',
      'Be aware of terrain hazards',
      'Wash hands after fieldwork',
      'Inform someone of your location',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
  {
    id: 'aqa-gcse-biology-rp10',
    name: 'RP10: Decay',
    description: 'Investigate the effect of temperature on the rate of decay of fresh milk by measuring pH change',
    icon: '🦠',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-gcse-biology-ecology'],
    equipment: [
      'Fresh milk',
      'Test tubes or small beakers',
      'pH probe or universal indicator',
      'Water baths at different temperatures',
      'Thermometer',
      'Stopwatch',
      'Lipase or bacteria culture (optional)',
      'Phenolphthalein indicator (optional)',
    ],
    safety: [
      'Wash hands thoroughly after handling',
      'Do not consume any milk samples',
      'Take care with hot water',
      'Some indicators are irritants',
      'Dispose of biological waste appropriately',
    ],
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'biology',
  },
];
