// Edexcel GCSE Physics Core Practicals
// Based on Edexcel 1PH0 specification (2016)
// Reference: https://www.physicsandmathstutor.com/physics-revision/gcse-edexcel/practical-skills/

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelGcsePhysicsPracticals: Practical[] = [
  {
    id: 'edexcel-gcse-physics-cp1',
    name: "CP1: Newton's Second Law",
    description: 'Investigate the relationship between force, mass and acceleration using trolleys on a ramp',
    icon: '🚀',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Dynamics trolley',
      'Ramp or runway',
      'Light gates and data logger',
      'Pulley',
      'String',
      'Slotted masses and hanger',
      'Balance',
      'Ruler',
    ],
    safety: [
      'Secure the ramp to prevent movement',
      'Place a soft barrier at the end to stop the trolley',
      'Keep feet clear of falling masses',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp2',
    name: 'CP2: Waves',
    description: 'Investigate the suitability of equipment to measure speed, frequency and wavelength of waves in a solid and a fluid',
    icon: '🌊',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ripple tank with motor and dipper',
      'Lamp and screen',
      'Ruler',
      'Stopwatch',
      'Signal generator',
      'Vibration generator',
      'Stretched string or elastic cord',
      'Stroboscope (optional)',
    ],
    safety: [
      'Keep electrical equipment away from water',
      'Mop up water spills immediately',
      'Strobe warning for those with photosensitive epilepsy',
      'Secure the ripple tank to prevent tipping',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp3',
    name: 'CP3: Refraction',
    description: 'Investigate refraction in rectangular glass blocks in terms of the interaction of electromagnetic waves with matter',
    icon: '🔦',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ray box or single slit light source',
      'Rectangular glass or perspex block',
      'Protractor',
      'Ruler',
      'White paper',
      'Pencil',
      'Pins (for ray tracing method)',
    ],
    safety: [
      'Do not look directly into the light source',
      'Handle glass blocks carefully to avoid breakage',
      'Take care with sharp edges on glass blocks',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp4',
    name: 'CP4: Radiation and Absorption',
    description: 'Investigate how the nature of a surface affects the amount of thermal energy radiated or absorbed',
    icon: '☀️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Leslie cube (metal cube with different surface finishes)',
      'Infrared thermometer or sensor',
      'Hot water',
      'Thermometer',
      'Stopwatch',
      'Matt black and shiny silver surfaces',
      'Beakers with different surface coatings',
    ],
    safety: [
      'Hot water can cause scalds - handle carefully',
      'Leslie cube gets very hot - use tongs or heat-resistant gloves',
      'Allow equipment to cool before handling',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp5',
    name: 'CP5: Circuits (I-V Characteristics)',
    description: 'Investigate the I-V characteristics of a filament lamp, diode, and fixed resistor',
    icon: '💡',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Filament lamp',
      'Diode',
      'Fixed resistor',
      'Variable resistor or potential divider',
      'Ammeter',
      'Voltmeter',
      'Power supply (low voltage DC)',
      'Connecting wires',
    ],
    safety: [
      'Filament lamp gets hot - allow to cool before handling',
      'Check polarity when using diode',
      'Do not exceed component ratings',
      'Use low voltage power supply only',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp6',
    name: 'CP6: Density',
    description: 'Investigate the densities of regular and irregular solid objects and liquids',
    icon: '⚖️',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-particle-model'],
    equipment: [
      'Balance (0.1g precision)',
      'Ruler or vernier calipers',
      'Regular solid objects (cube, cylinder, sphere)',
      'Irregular solid objects',
      'Measuring cylinder',
      'Water',
      'Eureka can (displacement can)',
      'Various liquids',
    ],
    safety: [
      'Handle heavy objects carefully',
      'Wipe up water spills immediately',
      'Glass measuring cylinders can break if knocked over',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp7',
    name: 'CP7: Specific Heat Capacity',
    description: 'Investigate the specific heat capacity of materials including water and metal blocks',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Electric heater/immersion heater',
      'Joulemeter or ammeter and voltmeter',
      'Thermometer (0.5°C precision)',
      'Insulating material (lagging)',
      'Balance',
      'Stopwatch',
      'Metal block with holes for heater and thermometer',
      'Beaker and water',
    ],
    safety: [
      'Hot surfaces - use insulation and handle with care',
      'Electrical equipment near water - keep connections dry',
      'Do not leave heater unattended',
      'Allow to cool before dismantling',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'edexcel-gcse-physics-cp8',
    name: 'CP8: Springs (Force and Extension)',
    description: "Investigate the relationship between force and extension for a spring (Hooke's Law)",
    icon: '🔩',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Spring (helical)',
      'Clamp stand, boss and clamp',
      'Metre ruler',
      'Slotted masses (100g)',
      'Mass hanger',
      'Pointer or marker',
      'Set square',
      'Safety glasses',
    ],
    safety: [
      'Wear safety glasses - springs can snap',
      'Do not exceed the elastic limit of the spring',
      'Keep feet away from falling masses',
      'Use a sand tray or soft mat beneath the masses',
    ],
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'physics',
  },
];
