// Edexcel A-Level Physics Core Practicals
// Based on Edexcel 9PH0 specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/physics-2015.html

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelALevelPhysicsPracticals: Practical[] = [
  {
    id: 'edexcel-alevel-physics-cp1',
    name: 'CP1: Acceleration of Free Fall',
    description: 'Determine the acceleration of a freely-falling object using an electromagnet and light gates or similar timing method',
    icon: '🍎',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-mechanics', 'physics-motion'],
    equipment: [
      'Electromagnet',
      'Steel ball bearing',
      'Electronic timer or light gates',
      'Metre ruler',
      'Clamp stand',
      'Trapdoor switch (optional)',
      'Soft landing surface',
    ],
    safety: [
      'Use soft landing surface for ball',
      'Secure clamp stand firmly',
      'Keep area clear when dropping',
      'Ball bearing can cause injury if dropped on feet',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp2',
    name: 'CP2: Stationary Waves on a String',
    description: 'Determine the frequency of stationary waves on a string by varying length, tension, and mass per unit length',
    icon: '🎸',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Signal generator',
      'Vibration generator',
      'String or elastic cord',
      'Pulley and clamp',
      'Slotted masses and hanger',
      'Metre ruler',
      'Balance',
      'Micrometer',
    ],
    safety: [
      'Secure equipment to prevent falling',
      'Keep masses clear of feet',
      'Ensure string is securely fastened',
      'Do not overload the string',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp3',
    name: "CP3: Young Modulus",
    description: "Determine the Young modulus of a material by measuring stress and strain",
    icon: '📏',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-materials'],
    equipment: [
      'Copper or steel wire (long, thin)',
      'Wooden blocks and G-clamp',
      'Pulley',
      'Slotted masses',
      'Metre ruler',
      'Micrometer screw gauge',
      'Vernier scale or travelling microscope',
      'Marker tape',
      'Safety glasses',
    ],
    safety: [
      'Wear safety glasses - wire may snap',
      'Keep feet clear of falling masses',
      'Use soft landing for masses',
      'Do not exceed elastic limit of wire',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp4',
    name: 'CP4: Speed of Sound',
    description: 'Determine the speed of sound in air using a two-beam oscilloscope and microphones',
    icon: '🔊',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves', 'physics-sound'],
    equipment: [
      'Two-beam oscilloscope',
      'Two microphones',
      'Signal generator',
      'Loudspeaker',
      'Metre ruler',
      'Connecting cables',
    ],
    safety: [
      'Keep sound levels reasonable',
      'Handle oscilloscope carefully',
      'Avoid tripping on cables',
      'Do not look directly at loudspeaker cone at high volumes',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp5',
    name: 'CP5: Thermistor Characteristics',
    description: 'Investigate the characteristics of a thermistor, measuring resistance at different temperatures',
    icon: '🌡️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity', 'physics-thermal'],
    equipment: [
      'NTC thermistor',
      'Ohmmeter or multimeter',
      'Beaker',
      'Water bath or ice/hot water',
      'Thermometer',
      'Stirring rod',
      'Clamp stand',
    ],
    safety: [
      'Take care with hot water',
      'Do not touch heating element',
      'Ensure electrical connections are dry',
      'Handle glass thermometer carefully',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp6',
    name: 'CP6: Internal Resistance of a Cell',
    description: 'Determine the EMF and internal resistance of a cell by measuring terminal p.d. and current',
    icon: '🔋',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Cell or battery',
      'Variable resistor (rheostat)',
      'Ammeter',
      'Voltmeter',
      'Connecting wires',
      'Switch',
    ],
    safety: [
      'Do not short circuit the cell',
      'Use low currents to prevent heating',
      'Monitor cell temperature',
      'Disconnect when not taking readings',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp7',
    name: 'CP7: I-V Characteristics',
    description: 'Investigate the I-V characteristics of a filament lamp, thermistor, and diode',
    icon: '💡',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Filament lamp',
      'Thermistor',
      'Diode',
      'Variable power supply',
      'Ammeter',
      'Voltmeter',
      'Variable resistor',
      'Connecting wires',
    ],
    safety: [
      'Filament lamp gets hot - do not touch',
      'Use appropriate voltage range for diode',
      'Avoid excessive current through components',
      'Allow cooling between measurements',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp8',
    name: 'CP8: Force on a Current-Carrying Wire',
    description: 'Investigate how the force on a wire varies with flux density, current, and length',
    icon: '🧲',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-magnetism', 'physics-electromagnetism'],
    equipment: [
      'Top pan balance',
      'Horseshoe magnet or C-core electromagnet',
      'Copper wire frame',
      'Power supply',
      'Ammeter',
      'Variable resistor',
      'Clamp stand',
      'Connecting wires',
    ],
    safety: [
      'Strong magnets - keep away from electronic devices',
      'Wire can get hot at high currents',
      'Secure the balance',
      'Use appropriate current range',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp9',
    name: "CP9: Boyle's Law",
    description: "Investigate the relationship between pressure and volume of a gas at constant temperature (Boyle's Law)",
    icon: '🎈',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal', 'physics-gases'],
    equipment: [
      "Boyle's Law apparatus",
      'Syringe or oil column tube',
      'Pressure gauge or Bourdon gauge',
      'Ruler',
      'Foot pump or pressure source',
      'Thermometer',
    ],
    safety: [
      'Do not exceed pressure limits of apparatus',
      'Ensure all connections are secure',
      'Release pressure slowly',
      'Keep away from face when pressurising',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp10',
    name: "CP10: Charles's Law",
    description: "Investigate the relationship between volume and temperature of a gas at constant pressure (Charles's Law)",
    icon: '♨️',
    color: 'bg-rose-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal', 'physics-gases'],
    equipment: [
      "Charles's Law apparatus",
      'Capillary tube with trapped air',
      'Water bath',
      'Thermometer',
      'Bunsen burner or heater',
      'Ruler',
      'Stirring rod',
    ],
    safety: [
      'Take care with hot water',
      'Glass capillary tubes are fragile',
      'Allow time for thermal equilibrium',
      'Handle heating equipment carefully',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp11',
    name: 'CP11: Gamma Radiation Absorption',
    description: 'Investigate the absorption of gamma radiation by lead, verifying exponential absorption',
    icon: '☢️',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-nuclear', 'physics-radiation'],
    equipment: [
      'Sealed gamma source (e.g., Co-60)',
      'Geiger-Müller tube and counter',
      'Lead sheets of various thicknesses',
      'Ruler',
      'Clamp stands',
      'Stopwatch',
      'Tongs for handling source',
    ],
    safety: [
      'Follow CLEAPSS guidelines for radioactive sources',
      'Minimise exposure time',
      'Maximise distance from source',
      'Use shielding when not measuring',
      'Handle source with tongs only',
      'Never point source at people',
      'Return source to secure storage',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp12',
    name: 'CP12: Specific Heat Capacity',
    description: 'Determine the specific heat capacity of a material using electrical heating',
    icon: '🔥',
    color: 'bg-orange-600',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal'],
    equipment: [
      'Metal block with heater hole',
      'Immersion heater',
      'Thermometer or temperature probe',
      'Joulemeter or ammeter and voltmeter',
      'Power supply',
      'Stopwatch',
      'Balance',
      'Insulation (lagging)',
    ],
    safety: [
      'Metal block gets very hot',
      'Use insulation to handle hot block',
      'Ensure heater is fully inserted',
      'Do not touch heating element',
      'Allow cooling before handling',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp13',
    name: 'CP13: Specific Latent Heat',
    description: 'Determine the specific latent heat of fusion or vaporisation',
    icon: '🧊',
    color: 'bg-sky-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-thermal'],
    equipment: [
      'Ice or water',
      'Immersion heater',
      'Beaker or container',
      'Balance',
      'Joulemeter or ammeter and voltmeter',
      'Thermometer',
      'Funnel and filter paper (for ice)',
      'Stopwatch',
    ],
    safety: [
      'Handle hot water/steam carefully',
      'Electrical equipment near water - keep dry',
      'Use insulation to minimise heat loss',
      'Do not touch heating element',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp14',
    name: 'CP14: Force and Momentum',
    description: 'Investigate the relationship between force, time, and change of momentum',
    icon: '🚀',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-mechanics', 'physics-momentum'],
    equipment: [
      'Dynamics trolley or air track glider',
      'Light gates',
      'Data logger',
      'Pulley and string',
      'Slotted masses',
      'Metre ruler',
      'Interrupt cards',
    ],
    safety: [
      'Secure the track',
      'Use soft buffers at track ends',
      'Keep masses from falling',
      'Do not obstruct moving trolley',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp15',
    name: 'CP15: Simple Harmonic Motion',
    description: 'Investigate simple harmonic motion using a mass-spring system and/or simple pendulum',
    icon: '🕰️',
    color: 'bg-violet-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-shm', 'physics-oscillations'],
    equipment: [
      'Springs',
      'Slotted masses and hanger',
      'Clamp stand',
      'Metre ruler',
      'Stopwatch',
      'Fiducial marker',
      'Pendulum bob and string',
      'Protractor',
    ],
    safety: [
      'Secure clamp stand',
      'Keep clear of swinging masses',
      'Do not overload springs',
      'Use small amplitudes',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
  {
    id: 'edexcel-alevel-physics-cp16',
    name: 'CP16: Inverse Square Law (Light)',
    description: 'Investigate how light intensity varies with distance from a point source',
    icon: '💡',
    color: 'bg-yellow-400',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves', 'physics-light'],
    equipment: [
      'Light source (lamp)',
      'Light meter or LDR circuit',
      'Metre ruler',
      'Darkened room',
      'Clamp stand',
      'Voltmeter (if using LDR)',
      'Black card (to reduce reflections)',
    ],
    safety: [
      'Lamp gets hot - do not touch',
      'Work in darkened room safely',
      'Allow lamp to cool before handling',
      'Avoid looking directly at bright light',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
  },
];
