// AQA A-Level Biology Required Practicals
// Based on AQA 7402 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const aqaALevelBiologyPracticals: Practical[] = [
  {
    id: 'aqa-alevel-biology-rp1',
    name: 'RP1: Effect of Enzyme Concentration',
    description: 'Investigation into the effect of a named variable on the rate of an enzyme-controlled reaction',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-biological-molecules'],
    equipment: [
      'Test tubes and rack',
      'Water bath',
      'Syringes or pipettes',
      'Enzyme solution (e.g., catalase, amylase)',
      'Substrate solution',
      'Buffer solutions',
      'Stopwatch',
      'Colorimeter (optional)',
      'Cuvettes',
      'Thermometer',
    ],
    safety: [
      'Wear safety goggles',
      'Hydrogen peroxide can bleach skin',
      'Take care with hot water',
      'Wash hands after handling enzymes',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp2',
    name: 'RP2: Microscopy',
    description: 'Preparation of stained squashes of cells from plant root tips; setup and use of an optical microscope',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-cells'],
    equipment: [
      'Light microscope',
      'Root tips (e.g., garlic, onion)',
      'Slides and cover slips',
      'Aceto-orcein or toluidine blue stain',
      'Hydrochloric acid',
      'Watch glass',
      'Forceps',
      'Mounted needle',
      'Filter paper',
      'Bunsen burner',
    ],
    safety: [
      'Wear safety goggles',
      'HCl is corrosive - handle carefully',
      'Stains can be toxic and stain skin',
      'Take care with Bunsen burner',
      'Handle glass carefully',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp3',
    name: 'RP3: Osmosis',
    description: 'Production of a dilution series of a solute to produce a calibration curve with which to identify the water potential of plant tissue',
    icon: '💧',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-cells'],
    equipment: [
      'Potato tissue or other plant material',
      'Cork borer',
      'Scalpel',
      'Balance (to 2 d.p.)',
      'Boiling tubes',
      'Sucrose solutions (various molarities)',
      'Distilled water',
      'Ruler',
      'Paper towels',
      'Tile',
    ],
    safety: [
      'Take care with sharp instruments',
      'Handle glassware carefully',
      'Wash hands after practical',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp4',
    name: 'RP4: Dissection of Gas Exchange System',
    description: 'Dissection of animal or plant gas exchange system or mass transport system or organ',
    icon: '🫁',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-exchange'],
    equipment: [
      'Specimen (e.g., fish head, locust, pig lungs)',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Seeker/probe',
      'Mounted needle',
      'Disposable gloves',
      'Paper towels',
    ],
    safety: [
      'Wear disposable gloves',
      'Handle sharp instruments with care',
      'Wash hands thoroughly after handling',
      'Dispose of biological material properly',
      'Be respectful of specimens',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp5',
    name: 'RP5: Dissection of Alimentary Canal',
    description: 'Dissection of an animal organ, or system of organs, to investigate structure and function',
    icon: '🔪',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-exchange'],
    equipment: [
      'Specimen (e.g., rat, fish)',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Seeker/probe',
      'Mounted needle',
      'Disposable gloves',
      'Pins',
      'Paper towels',
    ],
    safety: [
      'Wear disposable gloves throughout',
      'Handle sharp instruments carefully',
      'Wash hands thoroughly after handling',
      'Dispose of biological material appropriately',
      'Be respectful of specimens',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp6',
    name: 'RP6: Dissection of Plant Transport Tissues',
    description: 'Dissection of plant organs to investigate structure and function',
    icon: '🌿',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-exchange'],
    equipment: [
      'Plant stems (e.g., celery, rhubarb)',
      'Scalpel or razor blade',
      'Microscope slides',
      'Cover slips',
      'Light microscope',
      'Stains (e.g., toluidine blue)',
      'Forceps',
      'Water in dropping bottle',
    ],
    safety: [
      'Take care with sharp blades',
      'Handle stains carefully',
      'Handle glass slides carefully',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp7',
    name: 'RP7: DNA Electrophoresis',
    description: 'Use of aseptic technique to investigate effect of antimicrobial substances on microbial growth',
    icon: '🧬',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-genetic-information'],
    equipment: [
      'Electrophoresis tank',
      'Agarose gel',
      'Buffer solution',
      'Power pack',
      'Micropipettes',
      'DNA samples',
      'Loading dye',
      'DNA ladder',
      'Staining solution',
      'UV transilluminator or safe dye',
    ],
    safety: [
      'Electrical equipment - do not touch when running',
      'Handle gels carefully',
      'UV light is harmful - use viewing box',
      'Ethidium bromide is mutagenic if used',
      'Use safer alternatives like SYBR safe',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp8',
    name: 'RP8: Chromatography of Photosynthetic Pigments',
    description: 'Separation of photosynthetic pigments by chromatography',
    icon: '🌈',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-energy-transfers'],
    equipment: [
      'Leaves (e.g., spinach, nettle)',
      'Mortar and pestle',
      'Propanone or other solvent',
      'Sand',
      'Chromatography paper or TLC plate',
      'Capillary tube',
      'Boiling tube',
      'Bung',
      'Ruler',
      'Pencil',
    ],
    safety: [
      'Propanone is highly flammable - no naked flames',
      'Work in well-ventilated area',
      'Avoid inhaling solvent vapours',
      'Wear safety goggles',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp9',
    name: 'RP9: Respiration using Respirometer',
    description: 'Investigation into the rate of respiration of organisms using a respirometer',
    icon: '💨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-energy-transfers'],
    equipment: [
      'Respirometer',
      'Germinating seeds or small invertebrates',
      'Soda lime or potassium hydroxide',
      'Cotton wool',
      'Water bath',
      'Thermometer',
      'Stopwatch',
      'Syringe',
      'Manometer fluid',
    ],
    safety: [
      'Soda lime/KOH is corrosive - do not touch',
      'Handle organisms carefully',
      'Ensure apparatus is sealed properly',
      'Wash hands after handling organisms',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp10',
    name: 'RP10: Muscle and Nerve Dissection',
    description: 'Investigation into the structure and function of muscle and nerve tissue',
    icon: '💪',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-respond'],
    equipment: [
      'Chicken wing or other specimen',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Seeker/probe',
      'Disposable gloves',
      'Paper towels',
    ],
    safety: [
      'Wear disposable gloves',
      'Handle sharp instruments carefully',
      'Wash hands thoroughly after handling',
      'Dispose of biological material properly',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp11',
    name: 'RP11: Animal Response Investigation',
    description: 'Investigation into the effect of an environmental variable on the movement or distribution of an organism',
    icon: '🐛',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-respond'],
    equipment: [
      'Choice chamber',
      'Small invertebrates (e.g., woodlice, maggots)',
      'Damp and dry materials',
      'Light and dark conditions',
      'Thermometer',
      'Stopwatch',
      'Data recording sheets',
    ],
    safety: [
      'Handle organisms carefully and return them',
      'Wash hands after handling',
      'Ensure organisms are not harmed',
      'Use appropriate conditions for species',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'aqa-alevel-biology-rp12',
    name: 'RP12: Plant Response Investigation',
    description: 'Investigation into plant responses to stimuli such as light or gravity',
    icon: '🌱',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['aqa-alevel-biology-organisms-respond'],
    equipment: [
      'Seeds (e.g., cress, mung beans)',
      'Petri dishes',
      'Cotton wool or filter paper',
      'Light-proof box',
      'Clinostat (optional)',
      'Ruler',
      'Protractor',
      'Camera',
      'Lamp',
    ],
    safety: [
      'Wash hands after handling seeds',
      'Some seeds may be treated with chemicals',
      'Handle electrical equipment safely',
    ],
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'biology',
  },
];
