// OCR Gateway GCSE Physics Practical Activity Groups (PAGs)
// Based on OCR Gateway J249 specification
// Reference: https://www.physicsandmathstutor.com/physics-revision/gcse-ocr-a/practical-skills/

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrGcsePhysicsPracticals: Practical[] = [
  {
    id: 'ocr-gcse-physics-pag1',
    name: 'PAG1: Density',
    description: 'Investigate the densities of regular and irregular solid objects using appropriate apparatus and techniques',
    icon: '⚖️',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-particle-model'],
    equipment: [
      'Balance (resolution at least 0.1g)',
      'Ruler or vernier calipers or micrometer',
      'Regular solid objects (cube, cylinder, sphere)',
      'Irregular solid objects',
      'Measuring cylinder (appropriate size)',
      'Water',
      'Displacement can (eureka can)',
    ],
    safety: [
      'Handle heavy objects carefully',
      'Wipe up water spills immediately',
      'Glass measuring cylinders can break if dropped',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag2',
    name: "PAG2: Springs (Hooke's Law)",
    description: "Investigate the relationship between force and extension for a spring to verify Hooke's Law",
    icon: '🔩',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Spring (helical)',
      'Clamp stand, boss and clamp',
      'Metre ruler (mm scale)',
      'Slotted masses (100g increments)',
      'Mass hanger',
      'Pointer attached to spring',
      'Set square',
      'Safety glasses',
    ],
    safety: [
      'Wear safety glasses - springs can snap suddenly',
      'Do not exceed the elastic limit of the spring',
      'Keep feet clear of falling masses',
      'Place a soft mat or sand tray beneath apparatus',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag3',
    name: 'PAG3: Acceleration',
    description: 'Investigate the effect of varying force or mass on the acceleration of an object (F = ma)',
    icon: '🚀',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-forces'],
    equipment: [
      'Dynamics trolley',
      'Runway or track',
      'Light gates and data logger',
      'Interrupt card of known length',
      'Pulley',
      'String',
      'Slotted masses',
      'Balance',
    ],
    safety: [
      'Secure the runway to prevent movement',
      'Place a soft barrier or cushion at the end of the track',
      'Keep feet clear of falling masses',
      'Check light gates are secure',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag4',
    name: 'PAG4: Waves',
    description: 'Investigate wave properties including frequency, wavelength and wave speed using ripple tanks and vibrating strings',
    icon: '🌊',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ripple tank with motor and dipper',
      'Lamp and viewing screen',
      'Ruler',
      'Stopwatch',
      'Signal generator',
      'Vibration generator',
      'Stretched string',
      'Pulley and masses for tension',
    ],
    safety: [
      'Keep electrical equipment away from water',
      'Mop up water spills immediately',
      'Strobe warning for photosensitive epilepsy',
      'Secure the ripple tank to prevent tipping',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag5',
    name: 'PAG5: Specific Heat Capacity',
    description: 'Investigate the specific heat capacity of materials by electrical heating',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-energy'],
    equipment: [
      'Electric heater/immersion heater',
      'Joulemeter or ammeter and voltmeter',
      'Thermometer (resolution 1°C or better)',
      'Insulating material (lagging)',
      'Balance',
      'Stopwatch',
      'Metal block with holes for heater and thermometer',
      'Beaker and water',
    ],
    safety: [
      'Hot surfaces - use insulation and handle with care',
      'Electrical equipment near water - keep connections dry',
      'Do not leave heater unattended',
      'Allow equipment to cool before dismantling',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag6',
    name: 'PAG6: I-V Characteristics',
    description: 'Investigate the I-V characteristics of circuit components including resistors, filament lamps and diodes',
    icon: '💡',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Fixed resistor',
      'Filament lamp',
      'Diode',
      'Variable resistor or potential divider',
      'Ammeter (appropriate range)',
      'Voltmeter (appropriate range)',
      'Power supply (low voltage DC)',
      'Connecting wires',
    ],
    safety: [
      'Filament lamp gets hot - allow to cool before handling',
      'Check diode polarity before connecting',
      'Do not exceed component ratings',
      'Use low voltage power supply only',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag7',
    name: 'PAG7: Series and Parallel Circuits',
    description: 'Investigate current and potential difference in series and parallel circuits',
    icon: '🔌',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-electricity'],
    equipment: [
      'Identical lamps or resistors (at least 3)',
      'Ammeter',
      'Voltmeter',
      'Power supply (low voltage DC)',
      'Connecting wires',
      'Switches',
      'Circuit board or breadboard',
    ],
    safety: [
      'Use low voltage power supply only',
      'Check circuit connections before switching on',
      'Do not short circuit the power supply',
      'Lamps may get hot during prolonged use',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
  {
    id: 'ocr-gcse-physics-pag8',
    name: 'PAG8: Reflection and Refraction',
    description: 'Investigate the reflection and refraction of light using ray boxes and glass blocks',
    icon: '🔦',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['physics-waves'],
    equipment: [
      'Ray box or single slit light source',
      'Plane mirror',
      'Rectangular glass or perspex block',
      'Semicircular glass block',
      'Protractor',
      'Ruler',
      'White paper',
      'Pencil',
      'Pins (for ray tracing)',
    ],
    safety: [
      'Do not look directly into the light source',
      'Handle glass blocks carefully to avoid breakage',
      'Take care with sharp edges on glass blocks',
      'Dispose of broken glass safely',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
  },
];
