// OCR A-Level Biology A Practical Activity Groups (PAGs)
// Based on OCR H420 specification
// Note: OCR uses a flexible PAG approach - activities can be varied while meeting skill requirements

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrALevelBiologyPracticals: Practical[] = [
  {
    id: 'ocr-alevel-biology-pag1',
    name: 'PAG 1: Microscopy',
    description: 'Use a light microscope to make observations and measure biological specimens',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-foundations'],
    equipment: [
      'Light microscope',
      'Stage micrometer',
      'Eyepiece graticule',
      'Prepared slides',
      'Blank slides and cover slips',
      'Stains',
      'Forceps',
      'Mounted needle',
    ],
    safety: [
      'Handle glass slides carefully',
      'Stains may be toxic or irritant',
      'Take care with sharp instruments',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag2',
    name: 'PAG 2: Biological Molecules',
    description: 'Investigate the effect of a variable on enzyme activity',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-foundations'],
    equipment: [
      'Test tubes',
      'Water baths',
      'Enzyme and substrate solutions',
      'Buffer solutions',
      'Colorimeter',
      'Cuvettes',
      'Stopwatch',
      'Thermometer',
    ],
    safety: [
      'Take care with hot water',
      'Wash hands after handling enzymes',
      'Some buffers may be irritants',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag3',
    name: 'PAG 3: Enzyme Investigation',
    description: 'Investigate enzyme kinetics with substrate concentration',
    icon: '📈',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-foundations'],
    equipment: [
      'Enzyme solution',
      'Substrate solutions (various concentrations)',
      'Test tubes',
      'Water bath',
      'Stopwatch',
      'Colorimeter',
      'Cuvettes',
    ],
    safety: [
      'Take care with hot water',
      'Wash hands after handling',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag4',
    name: 'PAG 4: Membrane Permeability',
    description: 'Investigate factors affecting membrane permeability using beetroot',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-foundations'],
    equipment: [
      'Beetroot',
      'Cork borer',
      'Ruler',
      'Test tubes',
      'Water baths',
      'Colorimeter',
      'Cuvettes',
      'Distilled water',
    ],
    safety: [
      'Take care with sharp instruments',
      'Take care with hot water',
      'Beetroot stains',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag5',
    name: 'PAG 5: Cell Division',
    description: 'Prepare and examine root tip squash to observe mitosis',
    icon: '🧬',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-foundations'],
    equipment: [
      'Root tips',
      'Slides and cover slips',
      'Stain',
      'Hydrochloric acid',
      'Watch glass',
      'Forceps',
      'Light microscope',
      'Filter paper',
    ],
    safety: [
      'HCl is corrosive',
      'Stain may be toxic',
      'Handle glass carefully',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag6',
    name: 'PAG 6: Dissection',
    description: 'Dissection to examine gas exchange or transport systems',
    icon: '🔪',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-exchange-transport'],
    equipment: [
      'Specimen',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Gloves',
      'Paper towels',
    ],
    safety: [
      'Wear gloves',
      'Handle sharp instruments carefully',
      'Wash hands thoroughly',
      'Dispose of tissue properly',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag7',
    name: 'PAG 7: Heart Dissection',
    description: 'Dissect and examine the structure of the mammalian heart',
    icon: '❤️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-exchange-transport'],
    equipment: [
      'Heart specimen',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Gloves',
      'Paper towels',
    ],
    safety: [
      'Wear gloves throughout',
      'Handle sharp instruments carefully',
      'Wash hands thoroughly after',
      'Dispose of tissue properly',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag8',
    name: 'PAG 8: Plant Transport',
    description: 'Investigate water transport in plants using stained xylem',
    icon: '🌿',
    color: 'bg-emerald-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-exchange-transport'],
    equipment: [
      'Plant stems',
      'Dye solution (e.g., eosin)',
      'Scalpel or razor blade',
      'Microscope slides',
      'Light microscope',
      'Beakers',
      'Ruler',
    ],
    safety: [
      'Take care with sharp blades',
      'Dye may stain',
      'Handle glass carefully',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag9',
    name: 'PAG 9: Investigating Microorganisms',
    description: 'Investigate the effect of antimicrobials using aseptic technique',
    icon: '🦠',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-biodiversity'],
    equipment: [
      'Nutrient agar plates',
      'Bacterial culture',
      'Inoculating loop',
      'Bunsen burner',
      'Antimicrobial discs',
      'Forceps',
      'Tape',
      'Incubator',
    ],
    safety: [
      'Use strict aseptic technique',
      'Do not open plates after incubation',
      'Incubate at 25°C maximum',
      'Autoclave all waste',
      'Wash hands thoroughly',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag10',
    name: 'PAG 10: Nervous Tissue',
    description: 'Investigate the structure of nervous tissue through dissection',
    icon: '🧠',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-communication-homeostasis'],
    equipment: [
      'Specimen with nerves',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Gloves',
      'Microscope',
    ],
    safety: [
      'Wear gloves',
      'Handle sharp instruments carefully',
      'Wash hands thoroughly',
      'Dispose of tissue properly',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag11',
    name: 'PAG 11: Chromatography',
    description: 'Separate and identify photosynthetic pigments using chromatography',
    icon: '🌈',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-energy'],
    equipment: [
      'Leaves',
      'Mortar and pestle',
      'Propanone',
      'Sand',
      'Chromatography paper',
      'Capillary tube',
      'Boiling tube',
      'Ruler',
    ],
    safety: [
      'Propanone is highly flammable - no flames',
      'Work in well-ventilated area',
      'Avoid inhaling vapours',
      'Wear safety goggles',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'ocr-alevel-biology-pag12',
    name: 'PAG 12: Respiration Rates',
    description: 'Investigate the rate of respiration in organisms using a respirometer',
    icon: '💨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-biology-energy'],
    equipment: [
      'Respirometer',
      'Germinating seeds or invertebrates',
      'Soda lime',
      'Cotton wool',
      'Water bath',
      'Thermometer',
      'Stopwatch',
      'Syringe',
    ],
    safety: [
      'Soda lime is corrosive - do not touch',
      'Handle organisms carefully',
      'Wash hands after practical',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'biology',
  },
];
