// Edexcel A-Level Biology A Core Practicals
// Based on Edexcel 9BI0 specification

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const edexcelALevelBiologyPracticals: Practical[] = [
  {
    id: 'edexcel-alevel-biology-cp1',
    name: 'CP1: Vitamin C in Food',
    description: 'Investigate the vitamin C content of food and drink using DCPIP',
    icon: '🍊',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-lifestyle-health'],
    equipment: [
      'DCPIP solution',
      'Vitamin C standard solution',
      'Fruit juice samples',
      'Syringes or burettes',
      'Test tubes',
      'White tile',
      'Distilled water',
    ],
    safety: [
      'DCPIP may stain skin and clothes',
      'Handle glassware carefully',
      'Do not taste samples',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp2',
    name: 'CP2: Cell Membrane Permeability',
    description: 'Investigate the effect of temperature on cell membrane permeability in beetroot',
    icon: '🌡️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-genes-health'],
    equipment: [
      'Beetroot',
      'Cork borer',
      'Scalpel',
      'Ruler',
      'Test tubes',
      'Water baths at different temperatures',
      'Colorimeter',
      'Cuvettes',
      'Distilled water',
    ],
    safety: [
      'Take care with sharp instruments',
      'Take care with hot water baths',
      'Beetroot stains - protect clothing',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp3',
    name: 'CP3: Mitosis in Root Tip',
    description: 'Prepare and observe a root tip squash to identify stages of mitosis',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-voice-genome'],
    equipment: [
      'Root tips (garlic or onion)',
      'Microscope slides',
      'Cover slips',
      'Aceto-orcein stain',
      'Hydrochloric acid',
      'Watch glass',
      'Forceps',
      'Mounted needle',
      'Light microscope',
      'Filter paper',
    ],
    safety: [
      'Wear safety goggles',
      'HCl is corrosive',
      'Stain may be toxic',
      'Handle glass carefully',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp4',
    name: 'CP4: Staining Plant Tissue',
    description: 'Investigate plant tissue using staining techniques',
    icon: '🌿',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-biodiversity'],
    equipment: [
      'Plant stems',
      'Razor blade or scalpel',
      'Microscope slides',
      'Cover slips',
      'Toluidine blue or phloroglucinol',
      'Light microscope',
      'Forceps',
      'Water in dropping bottle',
    ],
    safety: [
      'Take care with sharp blades',
      'Handle stains carefully - may be irritants',
      'Handle glass carefully',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp9',
    name: 'CP9: Photosynthesis Pigments',
    description: 'Investigate photosynthetic pigments using chromatography',
    icon: '🌈',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-energy-exercise'],
    equipment: [
      'Leaves',
      'Mortar and pestle',
      'Propanone',
      'Sand',
      'Chromatography paper or TLC plate',
      'Capillary tube',
      'Boiling tube',
      'Bung',
      'Ruler',
      'Pencil',
    ],
    safety: [
      'Propanone is highly flammable - no flames',
      'Work in well-ventilated area',
      'Avoid inhaling vapours',
      'Wear safety goggles',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp10',
    name: 'CP10: Respiration Rates',
    description: 'Investigate the rate of respiration using a respirometer',
    icon: '💨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-energy-exercise'],
    equipment: [
      'Respirometer',
      'Germinating seeds or small invertebrates',
      'Soda lime',
      'Cotton wool',
      'Water bath',
      'Thermometer',
      'Stopwatch',
      'Syringe',
    ],
    safety: [
      'Soda lime is corrosive - do not touch',
      'Handle organisms carefully',
      'Wash hands after practical',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp11',
    name: 'CP11: Bacterial Growth',
    description: 'Investigate the effect of antimicrobial substances on bacterial growth using aseptic technique',
    icon: '🦠',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-infection-immunity'],
    equipment: [
      'Nutrient agar plates',
      'Bacterial culture',
      'Inoculating loop',
      'Bunsen burner',
      'Antimicrobial discs',
      'Forceps',
      'Tape',
      'Marker pen',
      'Incubator (25°C max in schools)',
    ],
    safety: [
      'Use strict aseptic technique',
      'Do not open plates after incubation',
      'Incubate at 25°C maximum',
      'Autoclave all waste',
      'Wash hands thoroughly',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp12',
    name: 'CP12: Muscle Contraction',
    description: 'Investigate the structure and function of muscle tissue through dissection',
    icon: '💪',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-run-for-life'],
    equipment: [
      'Chicken wing or leg',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Disposable gloves',
      'Paper towels',
    ],
    safety: [
      'Wear gloves throughout',
      'Handle sharp instruments carefully',
      'Wash hands after handling',
      'Dispose of tissue properly',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp13',
    name: 'CP13: Brain Structure',
    description: 'Examine the structure of a mammalian brain through dissection',
    icon: '🧠',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-grey-matter'],
    equipment: [
      'Brain specimen',
      'Dissection board',
      'Scalpel',
      'Scissors',
      'Forceps',
      'Probe',
      'Disposable gloves',
      'Paper towels',
    ],
    safety: [
      'Wear gloves throughout',
      'Handle carefully and respectfully',
      'Use sharp instruments with care',
      'Wash hands thoroughly',
      'Dispose properly',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp14',
    name: 'CP14: Habituation Investigation',
    description: 'Investigate habituation as a form of learning in an organism',
    icon: '🐌',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-grey-matter'],
    equipment: [
      'Organisms (e.g., snails, woodlice)',
      'Stimulus source',
      'Stopwatch',
      'Recording sheets',
      'Appropriate containers',
    ],
    safety: [
      'Handle organisms carefully',
      'Do not harm animals',
      'Return organisms after study',
      'Wash hands after handling',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp15',
    name: 'CP15: Plant Hormones',
    description: 'Investigate the effect of plant hormones on plant growth',
    icon: '🌱',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-grey-matter'],
    equipment: [
      'Seedlings',
      'Auxin solution',
      'Gibberellin solution',
      'Control solutions',
      'Petri dishes',
      'Ruler',
      'Light source',
      'Camera',
    ],
    safety: [
      'Wash hands after handling hormones',
      'Handle solutions carefully',
      'Wash hands after handling seeds',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
  {
    id: 'edexcel-alevel-biology-cp16',
    name: 'CP16: Animal Responses',
    description: 'Investigate the effect of environmental factors on animal movement or distribution',
    icon: '🐛',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['edexcel-alevel-biology-grey-matter'],
    equipment: [
      'Choice chamber',
      'Small invertebrates',
      'Various environmental conditions',
      'Stopwatch',
      'Recording sheets',
    ],
    safety: [
      'Handle organisms carefully',
      'Do not harm animals',
      'Return organisms after study',
      'Wash hands after handling',
    ],
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'biology',
  },
];
