// OCR A-Level Chemistry A Practical Activity Groups (PAGs)
// Based on OCR H432 specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/chemistry-a-h032-h432-from-2015/
// Note: OCR uses a flexible PAG approach - activities can be varied while meeting the same skills

import { Practical, PRACTICAL_SUBTOPICS } from '@/types';

export const ocrALevelChemistryPracticals: Practical[] = [
  {
    id: 'ocr-alevel-chemistry-pag1',
    name: 'PAG 1: Moles Determination',
    description: 'Determine the molar mass or amount of substance using various methods',
    icon: '⚖️',
    color: 'bg-blue-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-amount-substance'],
    equipment: [
      'Balance (0.01g precision)',
      'Volumetric flask',
      'Gas syringe or measuring cylinder over water',
      'Conical flask with delivery tube',
      'Thermometer',
      'Barometer (for pressure)',
      'Various reactants for different methods',
    ],
    safety: [
      'Wear safety glasses',
      'Follow specific safety guidance for chosen reaction',
      'Ensure good ventilation if producing gases',
      'Handle acids and metals with care',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag2',
    name: 'PAG 2: Acid-Base and Redox Titrations',
    description: 'Carry out acid-base and redox titrations with appropriate techniques',
    icon: '🧪',
    color: 'bg-green-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-acids-redox', 'ocr-alevel-chemistry-redox2'],
    equipment: [
      'Burette and stand',
      'Pipette (25 cm³) and filler',
      'Conical flasks',
      'White tile',
      'Volumetric flask',
      'Indicators (phenolphthalein, methyl orange)',
      'Standard solutions',
      'Potassium manganate(VII) for redox',
    ],
    safety: [
      'Wear safety glasses',
      'Handle acids and bases carefully',
      'Potassium manganate(VII) is an oxidizer and stains',
      'Use pipette filler - never mouth pipette',
      'Clean up spills immediately',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag3',
    name: 'PAG 3: Enthalpy Changes',
    description: 'Measure enthalpy changes for reactions including neutralisation, dissolution, and combustion',
    icon: '🌡️',
    color: 'bg-orange-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-physical1', 'ocr-alevel-chemistry-thermodynamics'],
    equipment: [
      'Polystyrene cup calorimeter',
      'Thermometer (0.2°C precision)',
      'Measuring cylinder',
      'Balance',
      'Stirring rod',
      'Lid for calorimeter',
      'Stopwatch',
      'Graph paper for cooling corrections',
    ],
    safety: [
      'Wear safety glasses',
      'Reactions may be strongly exothermic',
      'Handle hot solutions carefully',
      'Some reactants are corrosive',
      'Ensure good ventilation for combustion experiments',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag4',
    name: 'PAG 4: Rates of Reaction',
    description: 'Investigate how concentration, temperature, and catalysts affect reaction rate',
    icon: '⏱️',
    color: 'bg-red-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-physical1', 'ocr-alevel-chemistry-rates'],
    equipment: [
      'Conical flasks',
      'Measuring cylinders',
      'Stopwatch',
      'Water baths at different temperatures',
      'Thermometer',
      'White paper with cross (for disappearing cross)',
      'Gas syringe (for gas production)',
      'Colorimeter (optional)',
      'Data logger (optional)',
    ],
    safety: [
      'Wear safety glasses',
      'Sulfur dioxide may be produced - work in fume cupboard',
      'Take care with hot water baths',
      'Some catalysts are toxic',
      'Hydrogen peroxide is an oxidizer',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag5',
    name: 'PAG 5: Electrochemical Cells',
    description: 'Construct electrochemical cells and measure electrode potentials',
    icon: '🔋',
    color: 'bg-yellow-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-redox2'],
    equipment: [
      'Metal electrodes (Zn, Cu, Fe, Mg, Ag)',
      'Metal salt solutions (1.0 mol dm⁻³)',
      'Beakers',
      'Salt bridge (KNO₃ soaked filter paper)',
      'High resistance voltmeter',
      'Connecting wires with crocodile clips',
      'Sandpaper (to clean electrodes)',
    ],
    safety: [
      'Wear safety glasses',
      'Some metal salts are toxic (copper, lead)',
      'Silver nitrate stains skin',
      'Clean electrodes before use',
      'Dispose of solutions appropriately',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag6',
    name: 'PAG 6: Organic Synthesis',
    description: 'Use techniques such as reflux, distillation, heating under reflux, and purification',
    icon: '⚗️',
    color: 'bg-teal-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-synthesis-as', 'ocr-alevel-chemistry-synthesis'],
    equipment: [
      'Round-bottomed flask',
      'Reflux condenser',
      'Distillation apparatus',
      'Liebig condenser',
      'Heating mantle or water bath',
      'Anti-bumping granules',
      'Separating funnel',
      'Drying agent (anhydrous sodium sulfate)',
      'Thermometer adapter',
    ],
    safety: [
      'Wear safety glasses',
      'Many organic reagents are flammable',
      'Never heat a sealed system',
      'Ensure water flows through condenser before heating',
      'Work in fume cupboard',
      'Use anti-bumping granules',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag7',
    name: 'PAG 7: Qualitative Tests',
    description: 'Carry out qualitative tests on organic and inorganic unknowns',
    icon: '🔍',
    color: 'bg-purple-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-periodic-table', 'ocr-alevel-chemistry-analysis'],
    equipment: [
      'Test tubes and rack',
      'Bunsen burner',
      'Nichrome wire (flame tests)',
      'Dilute NaOH, ammonia, HCl, HNO₃, H₂SO₄',
      'Silver nitrate solution',
      'Barium chloride/nitrate solution',
      'Bromine water',
      '2,4-DNP reagent',
      "Tollens'/Fehling's reagent",
      'Litmus/pH paper',
    ],
    safety: [
      'Wear safety glasses',
      'Barium compounds are toxic',
      'Bromine water is corrosive and toxic',
      'Ammonia is irritant - use in fume cupboard',
      "Tollens' reagent should be freshly made and disposed of immediately",
      '2,4-DNP can be explosive when dry',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag8',
    name: 'PAG 8: Preparation of Organic Solids',
    description: 'Prepare, purify and analyse organic solids including determination of melting point',
    icon: '💊',
    color: 'bg-indigo-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-synthesis', 'ocr-alevel-chemistry-carbonyls'],
    equipment: [
      'Reaction vessel (conical flask/beaker)',
      'Buchner funnel and flask',
      'Filter paper',
      'Ice bath',
      'Recrystallisation solvent',
      'Melting point apparatus',
      'Capillary tubes',
      'Balance',
      'Drying oven (optional)',
    ],
    safety: [
      'Wear safety glasses',
      'Some organic solids are irritants',
      'Recrystallisation solvents may be flammable',
      'Handle hot solutions with care',
      'Products are for analysis only - do not ingest',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag9',
    name: 'PAG 9: Preparation of Organic Liquids',
    description: 'Prepare and purify organic liquids using distillation techniques',
    icon: '🫗',
    color: 'bg-amber-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-synthesis', 'ocr-alevel-chemistry-alcohols'],
    equipment: [
      'Round-bottomed flask',
      'Distillation head',
      'Liebig condenser',
      'Thermometer and adapter',
      'Receiving flask',
      'Heating mantle',
      'Anti-bumping granules',
      'Separating funnel',
      'Drying agent',
      'Boiling point determination apparatus',
    ],
    safety: [
      'Wear safety glasses',
      'Organic liquids are often flammable',
      'Work in fume cupboard',
      'Never heat a sealed system',
      'Ensure condenser water is flowing',
      'Use correct heating method for boiling point',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag10',
    name: 'PAG 10: Transition Metal Chemistry',
    description: 'Investigate properties of transition metals including complex ions, colour changes, and catalysis',
    icon: '🎨',
    color: 'bg-cyan-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-transition-metals'],
    equipment: [
      'Test tubes and rack',
      'Transition metal salt solutions',
      'Sodium hydroxide solution',
      'Ammonia solution (dilute and concentrated)',
      'EDTA solution',
      'Potassium thiocyanate',
      'Hydrogen peroxide',
      'Potassium iodide',
      'Starch indicator',
    ],
    safety: [
      'Wear safety glasses',
      'Ammonia is an irritant - use fume cupboard',
      'Some transition metal compounds are toxic',
      'Hydrogen peroxide is an oxidizer',
      'Thiocyanate solutions should be handled carefully',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag11',
    name: 'PAG 11: pH Curves and Buffers',
    description: 'Record pH curves for acid-base titrations and investigate buffer solutions',
    icon: '📈',
    color: 'bg-pink-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-equilibrium'],
    equipment: [
      'Burette',
      'Pipette and filler',
      'Conical flask or beaker',
      'pH meter or probe',
      'Data logger (optional)',
      'Magnetic stirrer',
      'Standard buffer solutions (pH 4, 7, 10)',
      'Strong/weak acids and bases',
      'Buffer solution components',
    ],
    safety: [
      'Wear safety glasses',
      'Sodium hydroxide is corrosive',
      'Handle pH electrode carefully - fragile glass',
      'Calibrate pH meter before use',
      'Clean electrode between measurements',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
  {
    id: 'ocr-alevel-chemistry-pag12',
    name: 'PAG 12: Chromatography and Spectroscopy',
    description: 'Use chromatography to separate mixtures and analyse using spectroscopic data',
    icon: '📋',
    color: 'bg-lime-500',
    subtopics: [...PRACTICAL_SUBTOPICS],
    linkedTopicIds: ['ocr-alevel-chemistry-analysis', 'ocr-alevel-chemistry-synthesis-as'],
    equipment: [
      'TLC plates (silica)',
      'Development tank with lid',
      'Capillary tubes',
      'UV lamp (254 nm)',
      'Various solvent systems',
      'Pencil and ruler',
      'Column chromatography apparatus (optional)',
      'Spectra data sheets (IR, NMR, MS)',
      'Data tables for interpretation',
    ],
    safety: [
      'Wear safety glasses',
      'Organic solvents are flammable - no naked flames',
      'Work in fume cupboard',
      'UV light damages eyes - do not look directly',
      'Handle TLC plates by edges',
      'Iodine is harmful - use in fume cupboard',
    ],
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'chemistry',
  },
];
