// Edexcel GCSE Biology (1BI0) Topics
// Based on the official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/sciences-2016.html

import { Topic } from '@/types';

export const edexcelBiologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1 TOPICS (Topics 1-5)
  // ============================================================================
  {
    id: 'edexcel-gcse-biology-cells',
    examBoard: 'edexcel',
    name: 'Key Concepts in Biology',
    description: 'Cells, microscopy, enzymes, transport, and cell division',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.1 The structure of cells
      'Eukaryotic cells',
      'Prokaryotic cells',
      'Animal cell structure',
      'Plant cell structure',
      'Bacterial cell structure',
      'Nucleus and genetic material',
      'Cytoplasm',
      'Cell membrane',
      'Mitochondria',
      'Ribosomes',
      'Chloroplasts',
      'Vacuole',
      'Cell wall',
      // 1.2 Microscopy
      'Light microscopy',
      'Electron microscopy',
      'Magnification calculations',
      'Scale bars',
      'Resolution',
      'Preparing slides',
      'Core Practical 1: Microscopy',
      // 1.3 Enzymes and nutrition
      'Enzyme structure',
      'Lock and key model',
      'Enzyme specificity',
      'Active site',
      'Factors affecting enzyme activity',
      'Effect of temperature on enzymes',
      'Optimum temperature',
      'Denaturation',
      'Effect of pH on enzymes',
      'Core Practical 2: Enzyme activity',
      // 1.4 Transport in and out of cells
      'Diffusion',
      'Factors affecting diffusion',
      'Surface area to volume ratio',
      'Osmosis',
      'Osmosis in plants',
      'Osmosis in animals',
      'Active transport',
      'Core Practical 3: Osmosis',
      // 1.5 Cell division
      'The cell cycle',
      'Mitosis',
      'Stages of mitosis',
      'Chromosomes',
      'Growth in organisms',
      'Differentiation',
      'Stem cells',
      'Meristems',
    ],
  },
  {
    id: 'edexcel-gcse-biology-systems',
    examBoard: 'edexcel',
    name: 'Cells and Control',
    description: 'Mitosis, cell growth, nervous system, and the brain',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 2.1 Mitosis and the cell cycle
      'Cell cycle stages',
      'DNA replication',
      'Mitosis stages in detail',
      'Importance of mitosis',
      'Cancer',
      'Uncontrolled cell division',
      // 2.2 Cell differentiation and stem cells
      'Cell differentiation',
      'Specialised cells',
      'Stem cells',
      'Embryonic stem cells',
      'Adult stem cells',
      'Uses of stem cells',
      'Ethical issues with stem cells',
      // 2.3 The nervous system
      'Structure of nervous system',
      'Central nervous system',
      'Peripheral nervous system',
      'Receptors',
      'Effectors',
      'Neurones',
      'Sensory neurones',
      'Motor neurones',
      'Relay neurones',
      'Synapses',
      'Neurotransmitters',
      'Reflex actions',
      'Reflex arc',
      'Core Practical 4: Reaction time',
      // 2.4 The brain
      'Structure of the brain',
      'Cerebral cortex',
      'Cerebellum',
      'Medulla',
      'Brain scanning techniques',
      'Treating brain damage',
    ],
  },
  {
    id: 'edexcel-gcse-biology-genetics',
    examBoard: 'edexcel',
    name: 'Genetics',
    description: 'DNA, protein synthesis, genetic inheritance, and genetic modification',
    icon: '🧬',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.1 Sexual and asexual reproduction
      'Sexual reproduction',
      'Asexual reproduction',
      'Comparison of sexual and asexual',
      'Meiosis',
      'Gametes',
      'Genetic variation from meiosis',
      // 3.2 DNA and protein synthesis
      'DNA structure',
      'Double helix',
      'Nucleotides',
      'Base pairs',
      'Complementary base pairing',
      'Genes',
      'Chromosomes',
      'Genome',
      'Protein synthesis',
      'Transcription',
      'Translation',
      'Amino acids',
      'Codons',
      // 3.3 Genetic inheritance
      'Alleles',
      'Dominant alleles',
      'Recessive alleles',
      'Homozygous',
      'Heterozygous',
      'Genotype',
      'Phenotype',
      'Monohybrid crosses',
      'Punnett squares',
      'Genetic diagrams',
      'Family pedigrees',
      'Inherited diseases',
      'Polydactyly',
      'Cystic fibrosis',
      'Sex determination',
      'Sex chromosomes',
      // 3.4 Genetic modification
      'Genetic engineering',
      'Restriction enzymes',
      'Vectors',
      'Plasmids',
      'GM crops',
      'GM bacteria for insulin',
      'Benefits and risks of GM',
      'Selective breeding',
      'Uses of selective breeding',
      'Problems with selective breeding',
    ],
  },
  {
    id: 'edexcel-gcse-biology-health',
    examBoard: 'edexcel',
    name: 'Natural Selection and Genetic Modification',
    description: 'Evolution, natural selection, and classification',
    icon: '🦎',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 4.1 Evidence for human evolution
      'Human evolution',
      'Fossil evidence',
      'Stone tools',
      'Ardi',
      'Lucy',
      'Leakey\'s discovery',
      'Homo habilis to Homo sapiens',
      // 4.2 Darwin and evolution
      'Darwin\'s theory of evolution',
      'Natural selection',
      'Survival of the fittest',
      'Variation',
      'Competition',
      'Adaptation',
      'Evidence for evolution',
      'Fossil record',
      'Antibiotic resistance',
      'Wallace\'s contribution',
      // 4.3 Classification
      'Classification systems',
      'Linnaean system',
      'Kingdoms',
      'Phylum, class, order, family, genus, species',
      'Binomial naming',
      'Three-domain system',
      'Archaea',
      'Bacteria',
      'Eukaryota',
      'Evolutionary relationships',
      'Evolutionary trees',
    ],
  },
  {
    id: 'edexcel-gcse-biology-health-disease',
    examBoard: 'edexcel',
    name: 'Health, Disease and the Development of Medicines',
    description: 'Communicable diseases, immune system, and drug development',
    icon: '💊',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 5.1 Health and disease
      'Health definition',
      'Disease',
      'Communicable diseases',
      'Non-communicable diseases',
      'Risk factors',
      // 5.2 Pathogens
      'Types of pathogen',
      'Bacteria',
      'Viruses',
      'Fungi',
      'Protists',
      'How pathogens spread',
      // 5.3 Viral diseases
      'HIV/AIDS',
      'Tobacco mosaic virus',
      // 5.4 Bacterial diseases
      'Salmonella',
      'Gonorrhoea',
      // 5.5 Malaria
      'Life cycle of Plasmodium',
      'Transmission by mosquitoes',
      'Prevention of malaria',
      // 5.6 Human defences
      'Physical barriers',
      'Skin',
      'Mucus membranes',
      'Cilia',
      'Stomach acid',
      'Immune system',
      'White blood cells',
      'Phagocytosis',
      'Antibodies',
      'Antitoxins',
      // 5.7 Vaccination
      'How vaccines work',
      'Antigens and antibodies',
      'Memory cells',
      'Herd immunity',
      // 5.8 Antibiotics
      'Discovery of antibiotics',
      'Penicillin',
      'Antibiotic resistance',
      'MRSA',
      // 5.9 Development of medicines
      'Drug testing',
      'Preclinical testing',
      'Clinical trials',
      'Double-blind trials',
      'Placebo',
      // 5.10 Monoclonal antibodies
      'Production of monoclonal antibodies',
      'Hybridomas',
      'Uses in pregnancy tests',
      'Uses in disease diagnosis',
      'Uses in cancer treatment',
    ],
  },

  // ============================================================================
  // PAPER 2 TOPICS (Topics 6-9)
  // ============================================================================
  {
    id: 'edexcel-gcse-biology-plant-structures',
    examBoard: 'edexcel',
    name: 'Plant Structures and their Functions',
    description: 'Photosynthesis, transport in plants, and plant hormones',
    icon: '🌱',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 6.1 Photosynthesis
      'Photosynthesis equation',
      'Endothermic reaction',
      'Chloroplasts',
      'Chlorophyll',
      'Light-dependent reactions',
      'Factors affecting photosynthesis',
      'Light intensity',
      'Carbon dioxide concentration',
      'Temperature',
      'Limiting factors',
      'Uses of glucose',
      'Glucose for respiration',
      'Glucose for storage (starch)',
      'Glucose for cellulose',
      'Glucose for proteins and lipids',
      'Core Practical 5: Photosynthesis rate',
      // 6.2 Transport in plants
      'Root structure',
      'Root hair cells',
      'Xylem',
      'Phloem',
      'Transpiration',
      'Transpiration stream',
      'Factors affecting transpiration',
      'Translocation',
      'Core Practical 6: Transpiration',
      // 6.3 Plant hormones
      'Auxins',
      'Phototropism',
      'Gravitropism',
      'Gibberellins',
      'Ethene',
      'Uses of plant hormones',
      'Rooting powder',
      'Weedkillers',
      'Fruit ripening',
    ],
  },
  {
    id: 'edexcel-gcse-biology-animal-coordination',
    examBoard: 'edexcel',
    name: 'Animal Coordination, Control and Homeostasis',
    description: 'Hormones, blood glucose control, and maintaining internal conditions',
    icon: '⚖️',
    color: 'bg-amber-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 7.1 Hormones and the endocrine system
      'Endocrine system',
      'Hormones',
      'Glands',
      'Pituitary gland',
      'Thyroid gland',
      'Adrenal glands',
      'Pancreas',
      'Ovaries',
      'Testes',
      // 7.2 Control of blood glucose
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Glycogen',
      'Negative feedback',
      'Type 1 diabetes',
      'Type 2 diabetes',
      'Treatment of diabetes',
      // 7.3 Hormones in human reproduction
      'Puberty',
      'Male reproductive hormones',
      'Testosterone',
      'Female reproductive hormones',
      'Oestrogen',
      'Progesterone',
      'Menstrual cycle',
      'FSH',
      'LH',
      // 7.4 Contraception
      'Hormonal contraception',
      'Pill',
      'Implants',
      'Injections',
      'Non-hormonal contraception',
      'Barrier methods',
      'IUD',
      // 7.5 Fertility treatment
      'IVF',
      'Clomifene',
      'FSH injections',
      'Ethical issues with fertility treatment',
      // 7.6 Homeostasis
      'Definition of homeostasis',
      'Importance of homeostasis',
      'Control systems',
      'Receptors',
      'Coordination centres',
      'Effectors',
      // 7.7 Thermoregulation
      'Body temperature regulation',
      'Hypothalamus',
      'Vasoconstriction',
      'Vasodilation',
      'Sweating',
      'Shivering',
      // 7.8 Osmoregulation
      'Water balance',
      'Kidney structure',
      'Nephron',
      'Filtration',
      'Reabsorption',
      'ADH',
      'Urine concentration',
      'Kidney failure',
      'Dialysis',
      'Kidney transplant',
    ],
  },
  {
    id: 'edexcel-gcse-biology-exchange',
    examBoard: 'edexcel',
    name: 'Exchange and Transport in Animals',
    description: 'Gas exchange, circulatory system, and blood',
    icon: '🫁',
    color: 'bg-rose-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 8.1 Gas exchange
      'Lungs structure',
      'Alveoli',
      'Gas exchange in alveoli',
      'Adaptations of alveoli',
      'Surface area to volume ratio',
      'Breathing mechanism',
      'Ventilation',
      // 8.2 Circulatory system
      'Double circulatory system',
      'Heart structure',
      'Chambers of the heart',
      'Valves',
      'Coronary arteries',
      'Cardiac cycle',
      'Heart rate',
      // 8.3 Blood vessels
      'Arteries',
      'Veins',
      'Capillaries',
      'Structure of blood vessels',
      'Function of blood vessels',
      // 8.4 Blood
      'Blood composition',
      'Red blood cells',
      'Haemoglobin',
      'White blood cells',
      'Platelets',
      'Plasma',
      'Core Practical 7: Heart dissection',
      // 8.5 Cardiovascular disease
      'Coronary heart disease',
      'Risk factors for CHD',
      'Atherosclerosis',
      'Stents',
      'Statins',
      'Heart bypass surgery',
      'Artificial hearts',
      'Heart transplants',
    ],
  },
  {
    id: 'edexcel-gcse-biology-ecosystems',
    examBoard: 'edexcel',
    name: 'Ecosystems and Material Cycles',
    description: 'Ecology, food chains, and nutrient cycles',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 9.1 Ecosystems
      'Ecosystems',
      'Communities',
      'Populations',
      'Habitats',
      'Niches',
      'Abiotic factors',
      'Biotic factors',
      'Core Practical 8: Sampling',
      // 9.2 Feeding relationships
      'Producers',
      'Consumers',
      'Food chains',
      'Food webs',
      'Trophic levels',
      'Predator-prey relationships',
      // 9.3 Competition
      'Interspecific competition',
      'Intraspecific competition',
      'Resources competed for',
      // 9.4 Adaptations
      'Structural adaptations',
      'Behavioural adaptations',
      'Functional adaptations',
      'Extremophiles',
      // 9.5 Pyramids
      'Pyramids of numbers',
      'Pyramids of biomass',
      'Pyramids of energy',
      // 9.6 Energy transfer
      'Energy flow in ecosystems',
      'Efficiency of energy transfer',
      'Energy losses',
      'Calculating efficiency',
      // 9.7 Carbon cycle
      'Carbon cycle',
      'Photosynthesis in carbon cycle',
      'Respiration in carbon cycle',
      'Decomposition',
      'Combustion',
      'Fossil fuels',
      // 9.8 Water cycle
      'Water cycle stages',
      'Evaporation',
      'Condensation',
      'Precipitation',
      'Transpiration',
      // 9.9 Nitrogen cycle
      'Nitrogen cycle',
      'Nitrogen fixation',
      'Nitrification',
      'Denitrification',
      'Decomposers',
      // 9.10 Human impacts
      'Biodiversity',
      'Importance of biodiversity',
      'Threats to biodiversity',
      'Deforestation',
      'Pollution',
      'Global warming',
      'Greenhouse effect',
      'Conservation',
      'Maintaining biodiversity',
    ],
  },
];

export function getEdexcelBiologyTopicById(id: string): Topic | undefined {
  return edexcelBiologyTopics.find((topic) => topic.id === id);
}

export function getEdexcelBiologyTopicsByPaper(paper: 1 | 2): Topic[] {
  const paperName = `Paper ${paper}`;
  return edexcelBiologyTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countEdexcelBiologySubtopics(): number {
  return edexcelBiologyTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
