// Edexcel A-Level Psychology Topics (9PS0)
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/psychology-2015.html

import { Topic } from '@/types';

export const edexcelALevelPsychologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: FOUNDATIONS IN PSYCHOLOGY (35%)
  // Topics 1-4 are compulsory
  // ============================================================================
  {
    id: 'edexcel-alevel-psych-social',
    name: 'Social Psychology',
    description: 'Obedience, prejudice, and social psychological explanations of behaviour',
    icon: '👥',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Obedience
      "Milgram's agency theory of obedience",
      'Agentic state vs autonomous state',
      'Moral strain',
      "Evaluation of Milgram's agency theory",
      "Milgram's (1963) baseline study",
      'Procedure of Milgram study',
      'Findings and conclusions',
      "Milgram's variations",
      'Effect of location on obedience',
      'Effect of proximity on obedience',
      'Effect of uniform on obedience',
      'Ethical issues in obedience research',
      'Social impact theory (Latané)',
      'Strength, immediacy, number',
      'Application of social impact theory',
      'Factors affecting obedience',
      'Individual differences in obedience',
      'Situational factors in obedience',
      // Prejudice
      'Social identity theory (Tajfel and Turner)',
      'In-groups and out-groups',
      'Social categorisation',
      'Social identification',
      'Social comparison',
      'Positive distinctiveness',
      'Evaluation of social identity theory',
      'Realistic conflict theory (Sherif)',
      'Competition for resources',
      'Superordinate goals',
      "Sherif's Robbers Cave study",
      'Procedure of Robbers Cave',
      'Findings and conclusions',
      'Evaluation of realistic conflict theory',
      'Individual differences in prejudice',
      'Authoritarian personality',
      'Right-wing authoritarianism',
      // Classic study
      "Burger's (2009) replication of Milgram",
      'Ethical modifications made',
      'Findings comparison with original',
      // Contemporary study in social psychology
      'Reicher and Haslam (2006) BBC Prison Study',
      'Procedure of BBC Prison Study',
      'Findings on social identity',
      'Implications for understanding tyranny',
    ],
  },
  {
    id: 'edexcel-alevel-psych-cognitive',
    name: 'Cognitive Psychology',
    description: 'Memory processes, models of memory, and applications to eyewitness testimony',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Models of memory
      'Multi-store model of memory',
      'Sensory memory',
      'Short-term memory',
      'Long-term memory',
      'Transfer between stores',
      'Evaluation of multi-store model',
      'Working memory model',
      'Central executive',
      'Phonological loop',
      'Visuo-spatial sketchpad',
      'Episodic buffer',
      'Evaluation of working memory model',
      'Episodic and semantic memory',
      'Procedural memory',
      // Reconstructive memory
      'Reconstructive nature of memory',
      'Role of schemas',
      'Bartlett (1932) War of the Ghosts',
      'Procedure of War of the Ghosts study',
      'Findings on memory distortion',
      'Evaluation of Bartlett',
      // Forgetting
      'Theories of forgetting',
      'Interference theory',
      'Proactive interference',
      'Retroactive interference',
      'Retrieval failure theory',
      'Context-dependent memory',
      'State-dependent memory',
      'Decay theory',
      // Eyewitness testimony
      'Factors affecting eyewitness testimony',
      'Leading questions',
      'Post-event information',
      'Anxiety and weapon focus',
      'Age of witness',
      // Classic study
      'Baddeley (1966) study on encoding',
      'Acoustic and semantic encoding',
      'Procedure and findings',
      'Implications for STM and LTM',
      // Contemporary study
      'Sebastián and Hernández-Gil (2012)',
      'Digit span across age groups',
      'Development of working memory',
      'Cross-cultural comparison (Spain vs UK)',
    ],
  },
  {
    id: 'edexcel-alevel-psych-biological',
    name: 'Biological Psychology',
    description: 'Brain structure, neurotransmitters, aggression, and biological explanations of behaviour',
    icon: '🔬',
    color: 'bg-green-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // The nervous system
      'Structure of the nervous system',
      'Central nervous system',
      'Peripheral nervous system',
      'Autonomic nervous system',
      'Sympathetic division',
      'Parasympathetic division',
      'Somatic nervous system',
      // Neurons and synaptic transmission
      'Structure and function of neurons',
      'Sensory neurons',
      'Motor neurons',
      'Relay neurons',
      'Synaptic transmission',
      'Neurotransmitter release',
      'Receptor binding',
      'Excitation and inhibition',
      // Neurotransmitters
      'Role of dopamine',
      'Role of serotonin',
      'Role of adrenaline',
      'Role of noradrenaline',
      // Brain structure
      'Brain localisation',
      'Frontal lobe functions',
      'Temporal lobe functions',
      'Parietal lobe functions',
      'Occipital lobe functions',
      'Prefrontal cortex and behaviour',
      'Limbic system and emotion',
      'Amygdala function',
      'Hippocampus function',
      // Brain scanning techniques
      'fMRI scanning',
      'PET scanning',
      'CAT/CT scanning',
      'Strengths and limitations of each',
      // Aggression
      'Biological explanations of aggression',
      'Role of hormones: testosterone',
      'Role of the amygdala',
      'Role of serotonin in aggression',
      'Brain damage and aggression',
      'Genetic factors in aggression',
      'MAOA gene (warrior gene)',
      'Evaluation of biological explanations',
      // Evolution and behaviour
      'Evolution and human behaviour',
      'Natural selection',
      'Sexual selection',
      'Evolutionary explanations of aggression',
      // Classic study
      'Raine et al. (1997) brain abnormalities in murderers',
      'PET scans of murderers pleading NGRI',
      'Procedure and methodology',
      'Findings on prefrontal cortex',
      'Findings on limbic system',
      'Evaluation and implications',
      // Contemporary study
      'Brendgen et al. (2005) genetics of aggression',
      'Twin study methodology',
      'Physical vs social aggression',
      'Heritability estimates',
    ],
  },
  {
    id: 'edexcel-alevel-psych-learning',
    name: 'Learning Theories',
    description: 'Classical and operant conditioning, social learning, and phobias',
    icon: '📖',
    color: 'bg-yellow-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Classical conditioning
      'Classical conditioning theory',
      "Pavlov's research with dogs",
      'Unconditioned stimulus (UCS)',
      'Unconditioned response (UCR)',
      'Conditioned stimulus (CS)',
      'Conditioned response (CR)',
      'Acquisition of conditioned response',
      'Extinction',
      'Spontaneous recovery',
      'Stimulus generalisation',
      'Stimulus discrimination',
      'Higher-order conditioning',
      'Evaluation of classical conditioning',
      // Operant conditioning
      'Operant conditioning theory',
      "Skinner's research",
      'Skinner box experiments',
      'Positive reinforcement',
      'Negative reinforcement',
      'Positive punishment',
      'Negative punishment',
      'Schedules of reinforcement',
      'Continuous reinforcement',
      'Partial reinforcement schedules',
      'Fixed ratio schedules',
      'Variable ratio schedules',
      'Fixed interval schedules',
      'Variable interval schedules',
      'Shaping behaviour',
      'Evaluation of operant conditioning',
      // Social learning theory
      'Social learning theory',
      "Bandura's theory",
      'Observational learning',
      'Modelling',
      'Vicarious reinforcement',
      'Mediational processes',
      'Attention',
      'Retention',
      'Motor reproduction',
      'Motivation',
      'Role of self-efficacy',
      'Evaluation of social learning theory',
      // Phobias
      'Classical conditioning and phobias',
      'Acquisition of phobias',
      'Watson and Rayner Little Albert study',
      'Operant conditioning and phobias',
      'Maintenance of phobias',
      'Avoidance behaviour',
      'Two-process model (Mowrer)',
      'Social learning and phobias',
      'Treatments for phobias',
      'Systematic desensitisation',
      'Reciprocal inhibition',
      'Anxiety hierarchy',
      'Flooding/implosion',
      'Effectiveness of behavioural treatments',
      // Classic study
      'Watson and Rayner (1920) Little Albert',
      'Procedure and ethical issues',
      'Findings and implications',
      'Evaluation of Little Albert study',
      // Contemporary study
      'Capafons et al. (1998) treatment of flying phobia',
      'Systematic desensitisation procedure',
      'Effectiveness findings',
    ],
  },

  // ============================================================================
  // PAPER 2: APPLICATIONS OF PSYCHOLOGY (35%)
  // Topic 5 is compulsory, plus one option from Topics 6-8
  // ============================================================================
  {
    id: 'edexcel-alevel-psych-clinical',
    name: 'Clinical Psychology',
    description: 'Mental health, diagnosis of disorders, and treatments including schizophrenia and depression',
    icon: '🩺',
    color: 'bg-red-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Defining abnormality
      'Defining mental health',
      'Statistical infrequency',
      'Deviation from social norms',
      'Failure to function adequately',
      'Deviation from ideal mental health',
      'Cultural considerations',
      'Evaluation of definitions',
      // Diagnosis and classification
      'Diagnosis of mental disorders',
      'DSM-5 classification system',
      'ICD-11 classification system',
      'Reliability of diagnosis',
      'Validity of diagnosis',
      'Culture-bound syndromes',
      'Gender bias in diagnosis',
      // Schizophrenia
      'Schizophrenia characteristics',
      'Positive symptoms',
      'Hallucinations',
      'Delusions',
      'Thought disorder',
      'Negative symptoms',
      'Affective flattening',
      'Alogia (poverty of speech)',
      'Avolition',
      'Biological explanations of schizophrenia',
      'Genetic explanations',
      'Gottesman twin studies',
      'Dopamine hypothesis',
      'Brain structure abnormalities',
      'Non-biological explanations',
      'Double-bind theory',
      'Expressed emotion',
      'Cognitive explanations',
      'Treatments for schizophrenia',
      'Antipsychotic medication',
      'Typical antipsychotics',
      'Atypical antipsychotics',
      'CBT for schizophrenia',
      'Family therapy',
      // Unipolar depression
      'Depression characteristics',
      'DSM-5 criteria',
      'Behavioural symptoms',
      'Emotional symptoms',
      'Cognitive symptoms',
      'Biological explanations of depression',
      'Genetic factors',
      'Monoamine hypothesis',
      'Role of serotonin',
      'Role of noradrenaline',
      'Cognitive explanations',
      "Beck's negative cognitive triad",
      'Negative schemas',
      "Ellis's ABC model",
      'Irrational beliefs',
      'Social factors in depression',
      'Treatments for depression',
      'Antidepressants: SSRIs',
      'Antidepressants: SNRIs',
      'How antidepressants work',
      'Cognitive behavioural therapy',
      'Effectiveness of treatments',
      // Classic study
      'Rosenhan (1973) On Being Sane in Insane Places',
      'Procedure: pseudopatients',
      'Findings on labelling',
      'Implications for diagnosis',
      'Evaluation of Rosenhan',
      // Contemporary study
      'Carlsson et al. (2000)',
      'Dopamine hypothesis of schizophrenia',
      'Brain imaging evidence',
    ],
  },
  {
    id: 'edexcel-alevel-psych-criminological',
    name: 'Criminological Psychology',
    description: 'Explanations of crime, eyewitness testimony, and treatment of offenders',
    icon: '🔍',
    color: 'bg-gray-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // What makes a criminal?
      'Defining crime and antisocial behaviour',
      'Individual differences in criminality',
      'Nature vs nurture debate',
      // Biological explanations
      'Biological explanations of criminality',
      'Genetic explanations',
      "Lombroso's atavistic form",
      'Twin and adoption studies',
      'XYY syndrome',
      'Brain abnormalities',
      'Role of prefrontal cortex',
      "Raine's research",
      'Role of amygdala',
      'Hormonal factors',
      'Testosterone and crime',
      'Evaluation of biological explanations',
      // Social explanations
      'Social explanations of criminality',
      'Learning theories',
      'Sutherland differential association',
      'Social learning theory',
      'Labelling theory',
      'Self-fulfilling prophecy',
      'Social deprivation',
      'Evaluation of social explanations',
      // Psychological explanations
      'Psychological explanations',
      'Personality theories',
      "Eysenck's criminal personality",
      'Psychodynamic explanations',
      'Cognitive explanations',
      'Moral reasoning',
      'Cognitive distortions',
      // Eyewitness testimony
      'Factors affecting EWT',
      'Leading questions',
      'Loftus and Palmer research',
      'Post-event discussion',
      'Anxiety and arousal',
      'Weapon focus effect',
      'Age of witness',
      'Recognising faces',
      'Cross-race effect',
      'Cognitive interview technique',
      'Components of cognitive interview',
      'Effectiveness of cognitive interview',
      // Jury decision making
      'Jury decision making',
      'Characteristics affecting decisions',
      'Pre-trial publicity',
      'Expert witnesses',
      'Defendant characteristics',
      'Attractiveness bias',
      // Treating offenders
      'Biological treatments',
      'Castration for sex offenders',
      'Drug treatments',
      'Psychological treatments',
      'Anger management',
      'Token economy programmes',
      'Cognitive skills programmes',
      'Restorative justice',
      'Effectiveness of treatments',
      'Recidivism rates',
      // Classic study
      'Loftus and Palmer (1974) eyewitness testimony',
      'Experiment 1: verb impact',
      'Experiment 2: false memories',
      'Evaluation of study',
      // Contemporary study
      'Valentine and Mesout (2009) Horror Dungeon',
      'Anxiety and face recognition',
      'Real-world EWT research',
    ],
  },
  {
    id: 'edexcel-alevel-psych-child',
    name: 'Child Psychology',
    description: 'Attachment, deprivation, daycare, and autism',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Attachment
      'Development of attachment',
      'Stages of attachment (Schaffer)',
      'Pre-attachment phase',
      'Attachment-in-the-making',
      'Clear-cut attachment',
      'Multiple attachments',
      'Types of attachment',
      'Secure attachment',
      'Insecure-avoidant',
      'Insecure-resistant',
      'Disorganised attachment',
      "Ainsworth's Strange Situation",
      'Procedure and findings',
      'Cross-cultural variations',
      "Van Ijzendoorn's meta-analysis",
      // Explanations of attachment
      "Bowlby's monotropic theory",
      'Social releasers',
      'Critical period',
      'Internal working model',
      'Continuity hypothesis',
      'Learning theory of attachment',
      'Classical conditioning',
      'Operant conditioning',
      'Evaluation of attachment theories',
      // Deprivation and privation
      'Effects of deprivation',
      "Bowlby's 44 thieves study",
      'Maternal deprivation hypothesis',
      'Critical period vs sensitive period',
      'Effects of privation',
      'Romanian orphan studies',
      "Rutter's ERA study",
      'Recovery from privation',
      'Resilience factors',
      // Daycare
      'Effects of daycare on children',
      'Social development',
      'Cognitive development',
      'Attachment security',
      'Quality of daycare',
      'NICHD study findings',
      'EPPE study findings',
      // Autism spectrum disorder
      'Characteristics of autism',
      'Social interaction difficulties',
      'Communication difficulties',
      'Restricted interests',
      'Repetitive behaviours',
      'Biological explanations of autism',
      'Genetic factors',
      'Brain differences',
      'Mirror neuron dysfunction',
      'Psychological explanations',
      'Theory of mind deficit',
      'Sally-Anne task',
      'Extreme male brain theory',
      'Weak central coherence',
      'Treatments and interventions',
      'Applied behaviour analysis (ABA)',
      'TEACCH programme',
      'Social skills training',
      // Classic study
      'Bowlby (1944) 44 thieves',
      'Procedure and case histories',
      'Findings on affectionless psychopathy',
      'Evaluation',
      // Contemporary study
      'Li et al. (2013) attachment types',
      'Chinese vs American samples',
      'Cultural differences',
    ],
  },
  {
    id: 'edexcel-alevel-psych-health',
    name: 'Health Psychology',
    description: 'Stress, addiction, and health promotion',
    icon: '❤️',
    color: 'bg-rose-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Stress
      'Definition and types of stress',
      'Acute vs chronic stress',
      'Physiology of stress response',
      'HPA axis',
      'SAM pathway',
      'General Adaptation Syndrome',
      'Alarm stage',
      'Resistance stage',
      'Exhaustion stage',
      // Effects of stress
      'Effects on immune system',
      'Immunosuppression',
      "Kiecolt-Glaser's research",
      'Cardiovascular effects',
      'Type A personality',
      'Psychological effects',
      'Anxiety and depression',
      // Sources of stress
      'Life events',
      'Social Readjustment Rating Scale',
      "Holmes and Rahe's research",
      'Daily hassles',
      "Kanner's research",
      'Workplace stress',
      'Lack of control',
      'Workload',
      // Managing stress
      'Drug treatments',
      'Benzodiazepines',
      'Beta-blockers',
      'Psychological approaches',
      'Stress inoculation training',
      'Cognitive behavioural techniques',
      'Biofeedback',
      'Mindfulness',
      'Exercise',
      'Social support',
      // Addiction
      'Defining addiction',
      'Physical dependence',
      'Psychological dependence',
      'Tolerance',
      'Withdrawal',
      // Explanations of addiction
      'Biological explanations',
      'Genetic vulnerability',
      'Neurochemistry',
      'Dopamine reward pathway',
      'Psychological explanations',
      'Classical conditioning',
      'Operant conditioning',
      'Social learning',
      'Cognitive explanations',
      'Expectancy theory',
      'Social factors',
      'Peer pressure',
      'Family influences',
      // Types of addiction
      'Drug addiction',
      'Nicotine addiction',
      'Alcohol addiction',
      'Behavioural addictions',
      'Gambling addiction',
      'Internet/gaming addiction',
      // Treating addiction
      'Biological treatments',
      'Medication-assisted treatment',
      'Nicotine replacement',
      'Aversion therapy',
      'Psychological treatments',
      'Cognitive behavioural therapy',
      '12-step programmes',
      'Motivational interviewing',
      // Health promotion
      'Models of health behaviour',
      'Health Belief Model',
      'Theory of planned behaviour',
      'Stages of change model',
      'Health promotion campaigns',
      'Fear appeals',
      'Effectiveness of campaigns',
      // Classic study
      'Olds and Milner (1954) pleasure centres',
      'Brain stimulation reward',
      'Implications for addiction',
      // Contemporary study
      "Munafò et al. (2007) DRD4 gene and smoking",
      'Genetic vulnerability to nicotine',
    ],
  },

  // ============================================================================
  // PAPER 3: PSYCHOLOGICAL SKILLS (30%)
  // Topics 9 - Research methods and Issues/Debates
  // ============================================================================
  {
    id: 'edexcel-alevel-psych-research-methods',
    name: 'Research Methods',
    description: 'Scientific methodology, experimental design, data analysis, and statistical testing',
    icon: '📊',
    color: 'bg-indigo-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Scientific method
      'The scientific method',
      'Hypothesis testing',
      'Theory development',
      'Empiricism',
      'Objectivity',
      'Replicability',
      'Falsifiability',
      // Research methods
      'Laboratory experiments',
      'Field experiments',
      'Natural experiments',
      'Quasi-experiments',
      'Observations',
      'Naturalistic observation',
      'Controlled observation',
      'Participant observation',
      'Covert vs overt',
      'Questionnaires',
      'Open and closed questions',
      'Interviews',
      'Structured interviews',
      'Unstructured interviews',
      'Semi-structured interviews',
      'Correlational studies',
      'Case studies',
      'Content analysis',
      'Longitudinal studies',
      'Cross-sectional studies',
      'Cross-cultural studies',
      'Meta-analysis',
      // Design decisions
      'Aims and hypotheses',
      'Directional hypotheses',
      'Non-directional hypotheses',
      'Null hypotheses',
      'Variables',
      'Independent variables',
      'Dependent variables',
      'Extraneous variables',
      'Confounding variables',
      'Operationalisation',
      'Experimental designs',
      'Independent groups',
      'Repeated measures',
      'Matched pairs',
      'Order effects',
      'Counterbalancing',
      'Sampling methods',
      'Random sampling',
      'Stratified sampling',
      'Opportunity sampling',
      'Volunteer sampling',
      'Systematic sampling',
      // Evaluation issues
      'Reliability',
      'Test-retest reliability',
      'Inter-rater reliability',
      'Split-half reliability',
      'Validity',
      'Internal validity',
      'External validity',
      'Ecological validity',
      'Construct validity',
      'Face validity',
      'Demand characteristics',
      'Social desirability',
      'Investigator effects',
      'Hawthorne effect',
      // Ethics
      'Ethical guidelines',
      'BPS Code of Ethics',
      'Informed consent',
      'Deception',
      'Right to withdraw',
      'Protection from harm',
      'Confidentiality',
      'Privacy',
      'Ethical committees',
      'Cost-benefit analysis',
      // Data analysis
      'Levels of measurement',
      'Nominal data',
      'Ordinal data',
      'Interval data',
      'Ratio data',
      'Descriptive statistics',
      'Measures of central tendency',
      'Mean, median, mode',
      'Measures of dispersion',
      'Range',
      'Standard deviation',
      'Data presentation',
      'Tables',
      'Bar charts',
      'Histograms',
      'Scattergrams',
      'Line graphs',
      'Frequency polygons',
      'Normal distribution',
      'Skewed distributions',
      // Inferential statistics
      'Probability and significance',
      'Type I and Type II errors',
      'Statistical tests',
      'Chi-squared test',
      'Mann-Whitney U test',
      'Wilcoxon signed-ranks test',
      "Spearman's rho",
      'Choosing statistical tests',
      'One-tailed vs two-tailed tests',
      'Critical values and tables',
      // Qualitative analysis
      'Thematic analysis',
      'Grounded theory',
      'Content analysis categories',
      'Qualitative vs quantitative',
    ],
  },
  {
    id: 'edexcel-alevel-psych-issues-debates',
    name: 'Issues and Debates',
    description: 'Key debates and issues in psychology including ethics, nature-nurture, and reductionism',
    icon: '⚖️',
    color: 'bg-orange-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Ethics
      'Ethical issues in psychological research',
      'Ethics of working with humans',
      'Ethics of animal research',
      'Socially sensitive research',
      'Use of psychological research',
      // Nature-nurture
      'Nature-nurture debate',
      'Heredity vs environment',
      'Interactionist approach',
      'Diathesis-stress model',
      'Epigenetics',
      'Examples across topics',
      // Reductionism vs holism
      'Reductionism vs holism debate',
      'Biological reductionism',
      'Environmental reductionism',
      'Machine reductionism',
      'Benefits of reductionist approach',
      'Holistic approaches',
      'Levels of explanation',
      // Psychology as a science
      'Psychology as a science',
      'Scientific criteria',
      'Empiricism',
      'Objectivity',
      'Control',
      'Replicability',
      'Falsifiability',
      'Paradigms in psychology',
      'Pre-paradigmatic science',
      'Is psychology a science?',
      // Culture and gender
      'Cultural issues in psychology',
      'Ethnocentrism',
      'Cultural bias',
      'Emic vs etic approaches',
      'Cultural relativism',
      'Universality',
      'Gender issues in psychology',
      'Androcentrism',
      'Alpha bias',
      'Beta bias',
      'Gender bias in research',
      // Free will and determinism
      'Free will vs determinism',
      'Hard determinism',
      'Soft determinism',
      'Biological determinism',
      'Environmental determinism',
      'Psychic determinism',
      'Free will in humanistic psychology',
      'Implications for society',
      // Individual and situational
      'Individual vs situational explanations',
      'Dispositional factors',
      'Situational factors',
      'Interactionist perspective',
      'Fundamental attribution error',
      // Using psychological knowledge
      'Applications of psychology',
      'Practical applications',
      'Social control issues',
      'Use and misuse of research',
      'Psychology in society',
    ],
  },
];

export function getEdexcelALevelPsychologyTopicById(id: string): Topic | undefined {
  return edexcelALevelPsychologyTopics.find((topic) => topic.id === id);
}
