// OCR A-Level Business (H431) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/business-h031-h431-from-2015/
// Component 1: Operating in a local business environment (33%)
// Component 2: The UK business environment (33%)
// Component 3: The global business environment (34%)

import { Topic } from '@/types';

export const ocrALevelBusinessTopics: Topic[] = [
  // ============================================================================
  // COMPONENT 1: OPERATING IN A LOCAL BUSINESS ENVIRONMENT
  // ============================================================================

  // The local business environment
  {
    id: 'ocr-alevel-bus-local-environment',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'The Local Business Environment',
    description: 'Business activity, ownership, and objectives',
    icon: '🏪',
    color: 'bg-blue-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // Enterprise
      'Enterprise',
      'Entrepreneurs',
      'Characteristics of entrepreneurs',
      'Risk and reward',
      'Role of enterprise in business',
      'Intrapreneurs',
      'Business ideas',
      'Identifying opportunities',
      'Factors of production',
      'Land',
      'Labour',
      'Capital',
      'Enterprise as factor',
      // Forms of business
      'Sole traders',
      'Advantages of sole traders',
      'Disadvantages of sole traders',
      'Partnerships',
      'Partnership agreements',
      'Unlimited liability',
      'Limited liability',
      'Private limited companies',
      'Public limited companies',
      'Shares and shareholders',
      'Dividends',
      'Social enterprises',
      'Cooperatives',
      'Franchises',
      'Franchisors',
      'Franchisees',
      // Business aims and objectives
      'Mission statements',
      'Corporate aims',
      'Corporate objectives',
      'SMART objectives',
      'Survival',
      'Profit maximisation',
      'Profit satisficing',
      'Sales maximisation',
      'Market share growth',
      'Cost efficiency',
      'Employee welfare',
      'Customer satisfaction',
      'Social objectives',
      'Ethical objectives',
      // Stakeholders
      'Stakeholders',
      'Internal stakeholders',
      'External stakeholders',
      'Shareholders',
      'Employees',
      'Customers',
      'Suppliers',
      'Local community',
      'Government',
      'Pressure groups',
      'Stakeholder conflict',
      'Stakeholder mapping',
    ],
  },

  // Marketing
  {
    id: 'ocr-alevel-bus-marketing',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Marketing',
    description: 'Market research, segmentation, and marketing mix',
    icon: '📊',
    color: 'bg-green-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // Marketing objectives
      'Marketing objectives',
      'Sales volume targets',
      'Sales value targets',
      'Market share objectives',
      'Brand awareness',
      'Customer loyalty',
      // Market research
      'Market research',
      'Primary research',
      'Surveys',
      'Questionnaires',
      'Focus groups',
      'Interviews',
      'Observation',
      'Test marketing',
      'Secondary research',
      'Internal data',
      'External data',
      'Qualitative research',
      'Quantitative research',
      'Sampling',
      'Random sampling',
      'Stratified sampling',
      'Quota sampling',
      'Cluster sampling',
      'Data analysis',
      'Limitations of market research',
      // Market analysis
      'Market size',
      'Market growth',
      'Market share',
      'Market segmentation',
      'Demographic segmentation',
      'Geographic segmentation',
      'Psychographic segmentation',
      'Behavioural segmentation',
      'Benefits of segmentation',
      'Target markets',
      'Mass marketing',
      'Niche marketing',
      // Marketing mix
      'Marketing mix',
      '4Ps',
      '7Ps',
      // Product
      'Product decisions',
      'Product differentiation',
      'Unique selling point (USP)',
      'Product portfolio',
      'Boston Matrix',
      'Stars',
      'Cash cows',
      'Question marks',
      'Dogs',
      'Product life cycle',
      'Introduction',
      'Growth',
      'Maturity',
      'Decline',
      'Extension strategies',
      'Branding',
      'Brand building',
      'Brand loyalty',
      'Brand extension',
      // Price
      'Pricing strategies',
      'Cost-plus pricing',
      'Penetration pricing',
      'Price skimming',
      'Competitive pricing',
      'Psychological pricing',
      'Dynamic pricing',
      'Loss leader pricing',
      'Price elasticity of demand',
      'Calculating PED',
      'Elastic demand',
      'Inelastic demand',
      'PED and revenue',
      'Income elasticity of demand',
      // Promotion
      'Promotional mix',
      'Above-the-line promotion',
      'Below-the-line promotion',
      'Advertising',
      'Sales promotion',
      'Public relations',
      'Personal selling',
      'Direct marketing',
      'Digital marketing',
      'Social media marketing',
      'Sponsorship',
      // Place
      'Distribution channels',
      'Direct distribution',
      'Indirect distribution',
      'Retailers',
      'Wholesalers',
      'E-commerce',
      'Multi-channel distribution',
      // People, Process, Physical evidence
      'People in services',
      'Customer service',
      'Process',
      'Physical evidence',
    ],
  },

  // People
  {
    id: 'ocr-alevel-bus-people',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'People',
    description: 'Human resources, motivation, and organisational structure',
    icon: '👥',
    color: 'bg-purple-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // Workforce planning
      'Human resources',
      'Workforce planning',
      'Labour demand',
      'Labour supply',
      'Skills gap',
      'Recruitment',
      'Internal recruitment',
      'External recruitment',
      'Job descriptions',
      'Person specifications',
      'Selection methods',
      'Interviews',
      'Assessment centres',
      'Psychometric testing',
      'References',
      'Training',
      'Induction training',
      'On-the-job training',
      'Off-the-job training',
      'Apprenticeships',
      'Development',
      'Appraisals',
      // Organisational structure
      'Organisational structure',
      'Hierarchy',
      'Levels of hierarchy',
      'Chain of command',
      'Span of control',
      'Tall structures',
      'Flat structures',
      'Centralisation',
      'Decentralisation',
      'Delegation',
      'Empowerment',
      'Matrix structures',
      // Motivation
      'Motivation theories',
      'Taylor\'s Scientific Management',
      'Time and motion studies',
      'Piece rate',
      'Mayo\'s Human Relations',
      'Hawthorne studies',
      'Maslow\'s Hierarchy of Needs',
      'Physiological needs',
      'Safety needs',
      'Social needs',
      'Esteem needs',
      'Self-actualisation',
      'Herzberg\'s Two Factor Theory',
      'Motivators',
      'Hygiene factors',
      // Financial motivation
      'Financial motivation',
      'Wages',
      'Salaries',
      'Commission',
      'Bonus schemes',
      'Profit sharing',
      'Performance-related pay',
      'Share ownership',
      'Fringe benefits',
      // Non-financial motivation
      'Non-financial motivation',
      'Job enrichment',
      'Job enlargement',
      'Job rotation',
      'Team working',
      'Flexible working',
      'Remote working',
      'Recognition',
      // Leadership
      'Leadership',
      'Management vs leadership',
      'Leadership styles',
      'Autocratic leadership',
      'Democratic leadership',
      'Paternalistic leadership',
      'Laissez-faire leadership',
      'Factors affecting leadership style',
      // Employer-employee relations
      'Trade unions',
      'Collective bargaining',
      'Industrial action',
      'Works councils',
      'ACAS',
      'Employment law',
    ],
  },

  // Operations
  {
    id: 'ocr-alevel-bus-operations',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Operations',
    description: 'Production methods, quality, and efficiency',
    icon: '⚙️',
    color: 'bg-orange-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // Production
      'Production',
      'Added value',
      'Production methods',
      'Job production',
      'Batch production',
      'Flow production',
      'Cell production',
      'Choosing production method',
      // Productivity and efficiency
      'Productivity',
      'Labour productivity',
      'Capital productivity',
      'Efficiency',
      'Capacity',
      'Capacity utilisation',
      'Under-utilisation',
      'Over-capacity',
      'Improving capacity utilisation',
      // Lean production
      'Lean production',
      'Just-in-time (JIT)',
      'JIT advantages',
      'JIT disadvantages',
      'Kaizen',
      'Continuous improvement',
      'Waste minimisation',
      'Time-based management',
      // Quality
      'Quality',
      'Quality control',
      'Quality assurance',
      'Total Quality Management (TQM)',
      'Quality circles',
      'Zero defects',
      'Quality standards',
      'ISO 9001',
      'Cost of quality',
      'Cost of poor quality',
      // Stock control
      'Stock/inventory',
      'Types of stock',
      'Raw materials',
      'Work in progress',
      'Finished goods',
      'Stock control',
      'Buffer stocks',
      'Lead time',
      'Re-order level',
      'Re-order quantity',
      'Stock control charts',
      'JIT stock management',
      // Supply chain
      'Supply chain',
      'Supplier relationships',
      'Supplier selection',
      'Procurement',
      'Logistics',
      'Distribution',
    ],
  },

  // Finance
  {
    id: 'ocr-alevel-bus-finance',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Finance',
    description: 'Sources of finance, cash flow, and profitability',
    icon: '💰',
    color: 'bg-yellow-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // Sources of finance
      'Sources of finance',
      'Internal finance',
      'Retained profit',
      'Sale of assets',
      'Working capital',
      'External finance',
      'Share capital',
      'Loan capital',
      'Bank loans',
      'Overdrafts',
      'Mortgages',
      'Debentures',
      'Venture capital',
      'Business angels',
      'Crowdfunding',
      'Trade credit',
      'Leasing',
      'Hire purchase',
      'Grants',
      'Short-term vs long-term finance',
      // Costs and revenue
      'Costs',
      'Fixed costs',
      'Variable costs',
      'Semi-variable costs',
      'Total costs',
      'Average costs',
      'Direct costs',
      'Indirect costs',
      'Overheads',
      'Revenue',
      'Total revenue',
      'Average revenue',
      // Profit
      'Profit',
      'Gross profit',
      'Operating profit',
      'Net profit',
      'Profit margins',
      'Gross profit margin',
      'Operating profit margin',
      'Net profit margin',
      // Break-even
      'Break-even analysis',
      'Break-even point',
      'Calculating break-even',
      'Contribution',
      'Contribution per unit',
      'Break-even charts',
      'Margin of safety',
      'Target profit',
      'Benefits of break-even',
      'Limitations of break-even',
      // Cash flow
      'Cash flow',
      'Cash vs profit',
      'Cash flow forecasts',
      'Cash inflows',
      'Cash outflows',
      'Net cash flow',
      'Opening balance',
      'Closing balance',
      'Cash flow problems',
      'Improving cash flow',
      // Budgets
      'Budgets',
      'Purpose of budgets',
      'Types of budgets',
      'Setting budgets',
      'Historical budgeting',
      'Zero-based budgeting',
      'Variance analysis',
      'Favourable variances',
      'Adverse variances',
    ],
  },

  // ============================================================================
  // COMPONENT 2: THE UK BUSINESS ENVIRONMENT
  // ============================================================================

  // External environment
  {
    id: 'ocr-alevel-bus-external-environment',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'The External Environment',
    description: 'Economic, legal, and competitive factors',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // Economic environment
      'Economic environment',
      'Business cycle',
      'Boom',
      'Recession',
      'Recovery',
      'Slump',
      'Economic growth',
      'GDP',
      'Inflation',
      'Effects of inflation',
      'Interest rates',
      'Effects of interest rate changes',
      'Unemployment',
      'Types of unemployment',
      'Exchange rates',
      'Strong pound',
      'Weak pound',
      'Government policy',
      'Fiscal policy',
      'Monetary policy',
      'Supply-side policies',
      // Legal environment
      'Legal environment',
      'Consumer protection',
      'Consumer Rights Act',
      'Sale of Goods Act',
      'Employment law',
      'Minimum wage',
      'National Living Wage',
      'Working Time Regulations',
      'Equality Act',
      'Discrimination law',
      'Health and safety',
      'Environmental law',
      'Data protection',
      'GDPR',
      'Competition law',
      // Competitive environment
      'Competition',
      'Porter\'s Five Forces',
      'Threat of new entrants',
      'Bargaining power of suppliers',
      'Bargaining power of buyers',
      'Threat of substitutes',
      'Competitive rivalry',
      'Barriers to entry',
      'Market structures',
      'Perfect competition',
      'Monopolistic competition',
      'Oligopoly',
      'Monopoly',
      // PESTLE
      'PESTLE analysis',
      'Political factors',
      'Economic factors',
      'Social factors',
      'Technological factors',
      'Legal factors',
      'Environmental factors',
    ],
  },

  // Business strategy
  {
    id: 'ocr-alevel-bus-strategy',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Business Strategy',
    description: 'Strategic analysis, choice, and implementation',
    icon: '🎯',
    color: 'bg-indigo-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // Strategic analysis
      'Strategy',
      'Strategic planning',
      'Mission and vision',
      'Corporate objectives',
      'Functional objectives',
      'Strategy vs tactics',
      'SWOT analysis',
      'Strengths',
      'Weaknesses',
      'Opportunities',
      'Threats',
      // Strategic direction
      'Ansoff\'s Matrix',
      'Market penetration',
      'Market development',
      'Product development',
      'Diversification',
      'Porter\'s Generic Strategies',
      'Cost leadership',
      'Differentiation',
      'Focus strategy',
      // Growth strategies
      'Business growth',
      'Organic growth',
      'Inorganic growth',
      'Mergers',
      'Acquisitions',
      'Takeovers',
      'Horizontal integration',
      'Vertical integration',
      'Conglomerate diversification',
      'Synergy',
      'Economies of scale',
      'Diseconomies of scale',
      'Retrenchment',
      'Divestment',
      // Financial strategy
      'Financial ratios',
      'Profitability ratios',
      'Return on capital employed',
      'Liquidity ratios',
      'Current ratio',
      'Acid test ratio',
      'Gearing ratio',
      'Efficiency ratios',
      'Receivables days',
      'Payables days',
      'Inventory turnover',
      // Investment appraisal
      'Investment appraisal',
      'Payback period',
      'Average rate of return',
      'Net present value',
      'Discount factors',
      'Time value of money',
    ],
  },

  // Decision making
  {
    id: 'ocr-alevel-bus-decision-making',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Decision Making',
    description: 'Decision-making tools and techniques',
    icon: '🧮',
    color: 'bg-pink-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // Decision making process
      'Decision making',
      'Scientific decision making',
      'Intuitive decision making',
      'Strategic decisions',
      'Tactical decisions',
      'Operational decisions',
      'Risk vs uncertainty',
      'Data-driven decisions',
      // Decision trees
      'Decision trees',
      'Decision nodes',
      'Chance nodes',
      'Probabilities',
      'Expected values',
      'Net gains',
      'Benefits of decision trees',
      'Limitations of decision trees',
      // Critical path analysis
      'Critical path analysis',
      'Network diagrams',
      'Activities',
      'Dependencies',
      'Earliest start time',
      'Latest finish time',
      'Critical path',
      'Float time',
      'Free float',
      'Total float',
      'Benefits of CPA',
      'Limitations of CPA',
      // Sales forecasting
      'Sales forecasting',
      'Time series analysis',
      'Trends',
      'Moving averages',
      'Extrapolation',
      'Seasonal variations',
      'Correlation',
      'Limitations of forecasting',
    ],
  },

  // Managing change
  {
    id: 'ocr-alevel-bus-change',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managing Change',
    description: 'Organisational change and culture',
    icon: '🔄',
    color: 'bg-cyan-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // Change management
      'Business change',
      'Causes of change',
      'Internal causes',
      'External causes',
      'Types of change',
      'Incremental change',
      'Step change',
      'Transformational change',
      // Change models
      'Lewin\'s Force Field Analysis',
      'Driving forces',
      'Restraining forces',
      'Change process',
      'Unfreezing',
      'Moving',
      'Refreezing',
      // Organisational culture
      'Organisational culture',
      'Types of culture',
      'Power culture',
      'Role culture',
      'Task culture',
      'Person culture',
      'Strong culture',
      'Weak culture',
      'Changing culture',
      'Difficulties in changing culture',
      // Resistance to change
      'Resistance to change',
      'Causes of resistance',
      'Fear of unknown',
      'Loss of control',
      'Job security concerns',
      'Overcoming resistance',
      'Communication',
      'Involvement',
      'Support',
      'Training',
    ],
  },

  // ============================================================================
  // COMPONENT 3: THE GLOBAL BUSINESS ENVIRONMENT
  // ============================================================================

  // Globalisation
  {
    id: 'ocr-alevel-bus-globalisation',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Globalisation',
    description: 'Global business environment and international trade',
    icon: '🌐',
    color: 'bg-violet-500',
    paperRestriction: 'Component 3',
    subtopics: [
      // Globalisation
      'Globalisation',
      'Drivers of globalisation',
      'Technology and globalisation',
      'Trade liberalisation',
      'Political changes',
      'Transport improvements',
      'Communication advances',
      'Benefits of globalisation',
      'Drawbacks of globalisation',
      // International trade
      'International trade',
      'Exports',
      'Imports',
      'Balance of trade',
      'Free trade',
      'Benefits of free trade',
      'Protectionism',
      'Tariffs',
      'Quotas',
      'Non-tariff barriers',
      'Trading blocs',
      'EU',
      'NAFTA/USMCA',
      'WTO',
      // Emerging markets
      'Emerging markets',
      'BRIC countries',
      'Characteristics of emerging markets',
      'Opportunities in emerging markets',
      'Risks in emerging markets',
    ],
  },

  // Global marketing
  {
    id: 'ocr-alevel-bus-global-marketing',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Global Marketing',
    description: 'International marketing strategies',
    icon: '📣',
    color: 'bg-rose-500',
    paperRestriction: 'Component 3',
    subtopics: [
      // Global marketing strategies
      'Global marketing',
      'Standardisation',
      'Adaptation',
      'Glocal strategy',
      'Global branding',
      'International marketing mix',
      'Cultural considerations',
      'Language barriers',
      'Religious factors',
      'Local preferences',
      // Market entry
      'Market entry strategies',
      'Exporting',
      'Direct exporting',
      'Indirect exporting',
      'Licensing',
      'Franchising',
      'Joint ventures',
      'Strategic alliances',
      'Wholly owned subsidiaries',
      'Foreign direct investment',
      'Mergers and acquisitions',
      // Multinational corporations
      'Multinational corporations',
      'Characteristics of MNCs',
      'Reasons for becoming MNC',
      'Benefits to host countries',
      'Drawbacks to host countries',
      'Transfer pricing',
      'Tax avoidance',
      'Ethical issues with MNCs',
    ],
  },

  // Global operations
  {
    id: 'ocr-alevel-bus-global-operations',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Global Operations',
    description: 'Managing international operations and supply chains',
    icon: '🚀',
    color: 'bg-amber-500',
    paperRestriction: 'Component 3',
    subtopics: [
      // Global production
      'Global production',
      'Location decisions',
      'Factors affecting location',
      'Costs of production',
      'Labour availability',
      'Infrastructure',
      'Government incentives',
      'Market access',
      'Offshoring',
      'Reshoring',
      'Outsourcing',
      // Global supply chains
      'Global supply chains',
      'Managing global suppliers',
      'Supplier selection globally',
      'Quality management globally',
      'Logistics',
      'Supply chain risks',
      'Currency fluctuations',
      'Political instability',
      'Natural disasters',
      // Exchange rates
      'Exchange rates',
      'Floating exchange rates',
      'Fixed exchange rates',
      'Strong currency impact',
      'Weak currency impact',
      'Managing exchange rate risk',
      'Hedging',
    ],
  },

  // Ethics and sustainability
  {
    id: 'ocr-alevel-bus-ethics-sustainability',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'business',
    name: 'Ethics and Sustainability',
    description: 'Corporate social responsibility and sustainable business',
    icon: '🌱',
    color: 'bg-emerald-500',
    paperRestriction: 'Component 3',
    subtopics: [
      // Business ethics
      'Business ethics',
      'Ethical decision making',
      'Ethical dilemmas',
      'Ethical trade-offs',
      'Corporate governance',
      'Stakeholder interests',
      'Whistleblowing',
      // Corporate social responsibility
      'Corporate Social Responsibility',
      'Carroll\'s CSR pyramid',
      'Economic responsibilities',
      'Legal responsibilities',
      'Ethical responsibilities',
      'Philanthropic responsibilities',
      'Benefits of CSR',
      'Costs of CSR',
      'CSR reporting',
      // Sustainability
      'Sustainability',
      'Environmental sustainability',
      'Social sustainability',
      'Economic sustainability',
      'Triple bottom line',
      'Carbon footprint',
      'Climate change impact',
      'Sustainable business practices',
      'Renewable resources',
      'Waste reduction',
      'Circular economy',
      // Pressure groups
      'Pressure groups',
      'Types of pressure groups',
      'Tactics of pressure groups',
      'Business response to pressure groups',
      'Consumer activism',
    ],
  },
];

// Helper function to get topic by ID
export function getOCRALevelBusinessTopicById(id: string): Topic | undefined {
  return ocrALevelBusinessTopics.find(topic => topic.id === id);
}
