// AQA A-Level Economics (7136) Topics
// Based on the official AQA specification
// Reference: https://www.aqa.org.uk/subjects/economics/a-level/economics-7136/specification
// Paper 1: Markets and Market Failure (33.3%)
// Paper 2: National and International Economy (33.3%)
// Paper 3: Economic Principles and Issues - Synoptic (33.3%)

import { Topic } from '@/types';

export const aqaALevelEconomicsTopics: Topic[] = [
  // ============================================================================
  // SECTION 4.1: INDIVIDUALS, FIRMS, MARKETS AND MARKET FAILURE (Microeconomics)
  // Assessed in Paper 1 and Paper 3
  // ============================================================================

  // 4.1.1 Economic methodology and the economic problem
  {
    id: 'aqa-alevel-econ-methodology',
    examBoard: 'aqa',
    name: 'Economic Methodology and the Economic Problem',
    description: 'Economic methodology, the nature of economics, and the economic problem',
    icon: '🔬',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Economic methodology
      'Positive and normative statements',
      'The role of value judgements in economics',
      'Economic models and assumptions',
      'Scientific method in economics',
      'Role of ceteris paribus',
      // Nature of economics
      'Microeconomics vs macroeconomics',
      // Economic problem
      'Unlimited wants and finite resources',
      'Scarcity and choice',
      'Opportunity cost',
      'Production possibility frontiers',
      'PPF and opportunity cost',
      'PPF and economic efficiency',
      'PPF shifts',
      'Consumer goods vs capital goods',
      'Resource allocation',
    ],
  },

  // 4.1.2 Individual economic decision making
  {
    id: 'aqa-alevel-econ-individual',
    examBoard: 'aqa',
    name: 'Individual Economic Decision Making',
    description: 'Consumer behaviour, utility theory, and behavioural economics',
    icon: '🧠',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Consumer behaviour and utility
      'Utility theory',
      'Total utility',
      'Marginal utility',
      'Diminishing marginal utility',
      'Utility maximisation',
      'Equi-marginal principle',
      'Rational economic decision making',
      // Imperfect information
      'Symmetric information',
      'Asymmetric information',
      'Adverse selection',
      'Moral hazard',
      // Behavioural economics
      'Bounded rationality',
      'Bounded self-control',
      'Biases in decision making',
      'Anchoring',
      'Availability bias',
      'Social norms',
      'Rules of thumb',
      'Choice architecture',
      'Nudge theory',
      'Framing',
      'Default choice',
    ],
  },

  // 4.1.3 Price determination in a competitive market
  {
    id: 'aqa-alevel-econ-price',
    examBoard: 'aqa',
    name: 'Price Determination in a Competitive Market',
    description: 'Demand, supply, elasticity, and market equilibrium',
    icon: '📈',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Demand
      'The law of demand',
      'Individual and market demand',
      'Demand curves',
      'Movement along demand curve',
      'Shifts in demand curve',
      'Conditions of demand',
      'Determinants of demand',
      'Income and demand',
      'Normal goods',
      'Inferior goods',
      'Price of related goods',
      'Substitutes',
      'Complements',
      'Consumer confidence',
      // Supply
      'The law of supply',
      'Individual and market supply',
      'Supply curves',
      'Movement along supply curve',
      'Shifts in supply curve',
      'Conditions of supply',
      'Determinants of supply',
      'Costs of production',
      'Technology',
      'Taxes and subsidies',
      // Price elasticity of demand
      'Concept of PED',
      'Calculating PED',
      'Interpreting PED values',
      'Elastic and inelastic demand',
      'Determinants of PED',
      'Substitutability',
      'Proportion of income',
      'Time period',
      'Nature of good',
      'PED and total revenue',
      // Cross elasticity of demand
      'Concept of XED',
      'Calculating XED',
      'Interpreting XED values',
      'XED for substitutes',
      'XED for complements',
      // Income elasticity of demand
      'Concept of YED',
      'Calculating YED',
      'Normal vs inferior goods',
      'Necessities vs luxuries',
      // Price elasticity of supply
      'Concept of PES',
      'Calculating PES',
      'Determinants of PES',
      'Time period and PES',
      'Spare capacity',
      'Stock levels',
      'Mobility of factors',
      // Market equilibrium
      'Market equilibrium',
      'Equilibrium price',
      'Equilibrium quantity',
      'Disequilibrium',
      'Excess demand',
      'Excess supply',
      'Price adjustment mechanism',
      'Consumer and producer surplus',
      // Functions of price mechanism
      'Rationing function',
      'Signalling function',
      'Incentive function',
    ],
  },

  // 4.1.4 Production, costs and revenue
  {
    id: 'aqa-alevel-econ-production',
    examBoard: 'aqa',
    name: 'Production, Costs and Revenue',
    description: 'Production theory, costs, and revenue analysis',
    icon: '🏭',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Production and productivity
      'Production',
      'Productivity',
      'Specialisation',
      'Division of labour',
      // Short-run production
      'Short run vs long run',
      'Law of diminishing returns',
      'Total product',
      'Average product',
      'Marginal product',
      // Costs of production
      'Fixed costs',
      'Variable costs',
      'Total cost',
      'Average fixed cost',
      'Average variable cost',
      'Average total cost',
      'Marginal cost',
      'Relationship between AC and MC',
      // Short-run cost curves
      'Shape of short-run cost curves',
      'U-shaped average cost curve',
      // Long-run costs
      'Economies of scale',
      'Internal economies of scale',
      'Technical economies',
      'Purchasing economies',
      'Managerial economies',
      'Financial economies',
      'Marketing economies',
      'Risk-bearing economies',
      'External economies of scale',
      'Diseconomies of scale',
      'Internal diseconomies',
      'External diseconomies',
      'Long-run average cost curve',
      'Minimum efficient scale',
      // Revenue
      'Total revenue',
      'Average revenue',
      'Marginal revenue',
      'AR and MR curves under perfect competition',
      'AR and MR curves under imperfect competition',
    ],
  },

  // 4.1.5 Perfect competition, imperfectly competitive markets and monopoly
  {
    id: 'aqa-alevel-econ-market-structures',
    examBoard: 'aqa',
    name: 'Perfect Competition, Imperfect Competition and Monopoly',
    description: 'Market structures, profit maximisation, and efficiency',
    icon: '🏆',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Market structures overview
      'Market structure spectrum',
      'Features of different market structures',
      // Perfect competition
      'Assumptions of perfect competition',
      'Many buyers and sellers',
      'Homogeneous products',
      'Perfect information',
      'No barriers to entry or exit',
      'Price takers',
      'Short-run equilibrium in perfect competition',
      'Long-run equilibrium in perfect competition',
      'Efficiency in perfect competition',
      // Monopolistic competition
      'Features of monopolistic competition',
      'Product differentiation',
      'Non-price competition',
      'Short-run and long-run equilibrium',
      // Oligopoly
      'Features of oligopoly',
      'Concentration ratios',
      'Interdependence',
      'Game theory basics',
      "Prisoner's dilemma",
      'Kinked demand curve',
      'Price rigidity',
      'Non-price competition in oligopoly',
      'Collusion',
      'Cartels',
      'Tacit collusion',
      // Monopoly
      'Features of monopoly',
      'Sources of monopoly power',
      'Legal barriers',
      'Natural barriers',
      'Strategic barriers',
      'Monopoly equilibrium',
      'Profit maximisation',
      'MC = MR rule',
      'Price discrimination',
      'First degree price discrimination',
      'Second degree price discrimination',
      'Third degree price discrimination',
      'Conditions for price discrimination',
      // Natural monopoly
      'Characteristics of natural monopoly',
      'Regulation of natural monopoly',
      // Contestable markets
      'Theory of contestable markets',
      'Hit and run competition',
      'Sunk costs',
      'Implications for efficiency',
      // Efficiency
      'Allocative efficiency',
      'Productive efficiency',
      'Dynamic efficiency',
      'X-inefficiency',
      'Pareto efficiency',
    ],
  },

  // 4.1.6 The labour market
  {
    id: 'aqa-alevel-econ-labour',
    examBoard: 'aqa',
    name: 'The Labour Market',
    description: 'Labour demand, supply, wages, and market imperfections',
    icon: '👷',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Demand for labour
      'Derived demand',
      'Marginal revenue product (MRP)',
      'MRP = MPP × MR',
      'MRP curve as demand curve',
      'Factors affecting demand for labour',
      // Supply of labour
      'Individual labour supply',
      'Backward bending supply curve',
      'Income and substitution effects',
      'Market supply of labour',
      'Factors affecting supply',
      'Net migration',
      'Participation rates',
      // Wage determination
      'Equilibrium wage',
      'Perfectly competitive labour markets',
      'Wage differentials',
      'Compensating wage differentials',
      // Labour market imperfections
      'Monopsony',
      'Single employer',
      'Wage-setting power',
      'Monopsony equilibrium',
      // Trade unions
      'Role of trade unions',
      'Collective bargaining',
      'Trade union effects on wages',
      'Trade unions and efficiency',
      // Government intervention
      'National Minimum Wage',
      'National Living Wage',
      'Effects of minimum wage',
      'Employment effects',
      'Poverty effects',
      // Discrimination
      'Labour market discrimination',
      'Gender pay gap',
      'Ethnic pay gap',
      'Equal pay legislation',
    ],
  },

  // 4.1.7 Distribution of income and wealth
  {
    id: 'aqa-alevel-econ-distribution',
    examBoard: 'aqa',
    name: 'Distribution of Income and Wealth',
    description: 'Income and wealth inequality, poverty, and redistribution',
    icon: '⚖️',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Income and wealth
      'Difference between income and wealth',
      'Sources of income',
      'Sources of wealth',
      // Inequality
      'Income inequality',
      'Wealth inequality',
      'Lorenz curve',
      'Gini coefficient',
      'Causes of inequality',
      'Consequences of inequality',
      // Poverty
      'Absolute poverty',
      'Relative poverty',
      'Poverty line',
      'Causes of poverty',
      'Poverty trap',
      // Government policies
      'Progressive taxation',
      'Transfer payments',
      'Benefits system',
      'Universal Credit',
      'Means-tested vs universal benefits',
      'National Minimum Wage',
      'Public services',
    ],
  },

  // 4.1.8 Market failure
  {
    id: 'aqa-alevel-econ-market-failure',
    examBoard: 'aqa',
    name: 'Market Failure',
    description: 'Types of market failure and government intervention',
    icon: '⚠️',
    color: 'bg-rose-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Types of market failure
      'Definition of market failure',
      'Partial market failure',
      'Complete market failure',
      'Missing markets',
      // Externalities
      'Private costs and benefits',
      'External costs and benefits',
      'Social costs and benefits',
      'Marginal analysis of externalities',
      'MSC and MSB',
      'Negative externalities of production',
      'Negative externalities of consumption',
      'Positive externalities of production',
      'Positive externalities of consumption',
      'Welfare loss diagrams',
      'Deadweight loss',
      // Public goods
      'Characteristics of public goods',
      'Non-excludability',
      'Non-rivalry',
      'Non-rejectability',
      'Free rider problem',
      'Under-provision by markets',
      'Quasi-public goods',
      // Information failures
      'Asymmetric information',
      'Adverse selection',
      'Moral hazard',
      'Principal-agent problem',
      // Merit and demerit goods
      'Merit goods',
      'Under-consumption',
      'Information failure',
      'Positive externalities',
      'Demerit goods',
      'Over-consumption',
      // Monopoly as market failure
      'Allocative inefficiency',
      'Higher prices',
      'Lower output',
      'Welfare loss from monopoly',
      // Immobility of factors
      'Geographical immobility',
      'Occupational immobility',
    ],
  },

  // 4.1.9 Government intervention in markets
  {
    id: 'aqa-alevel-econ-intervention',
    examBoard: 'aqa',
    name: 'Government Intervention in Markets',
    description: 'Methods of government intervention and government failure',
    icon: '🏛️',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // Reasons for intervention
      'Correcting market failure',
      'Redistributing income',
      'Providing public goods',
      // Indirect taxation
      'Ad valorem taxes',
      'Specific taxes',
      'Effect on markets',
      'Tax incidence',
      'Internalising externalities',
      // Subsidies
      'Effect of subsidies on markets',
      'Subsidy to correct positive externalities',
      'Problems with subsidies',
      // Price controls
      'Maximum prices (price ceilings)',
      'Minimum prices (price floors)',
      'Buffer stock schemes',
      // Tradable permits
      'Carbon trading',
      'Pollution permits',
      'Cap and trade',
      // Provision of public goods
      'Direct provision',
      'Contracting out',
      // Provision of information
      'Addressing information failure',
      'Labelling requirements',
      'Public information campaigns',
      // Regulation
      'Purpose of regulation',
      'Types of regulation',
      'Costs and benefits of regulation',
      // State ownership
      'Nationalisation',
      'Arguments for and against',
      // Government failure
      'Definition of government failure',
      'Causes of government failure',
      'Unintended consequences',
      'Distortion of price signals',
      'Information gaps',
      'Administrative costs',
      'Regulatory capture',
      'Political self-interest',
    ],
  },

  // ============================================================================
  // SECTION 4.2: THE NATIONAL AND INTERNATIONAL ECONOMY (Macroeconomics)
  // Assessed in Paper 2 and Paper 3
  // ============================================================================

  // 4.2.1 Measurement of macroeconomic performance
  {
    id: 'aqa-alevel-econ-measurement',
    examBoard: 'aqa',
    name: 'Measurement of Macroeconomic Performance',
    description: 'Measuring economic performance and living standards',
    icon: '📊',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // National income
      'Gross Domestic Product (GDP)',
      'Measuring GDP',
      'Output method',
      'Income method',
      'Expenditure method',
      'Nominal vs real GDP',
      'GDP deflator',
      'GDP per capita',
      'Gross National Income (GNI)',
      // Limitations of GDP
      'GDP as measure of living standards',
      'Non-marketed output',
      'Shadow economy',
      'Quality of goods',
      'Distribution of income',
      'Environmental costs',
      // Other measures
      'Human Development Index (HDI)',
      'Index of Sustainable Economic Welfare',
      'Happiness indices',
      // Economic growth
      'Short-run growth',
      'Long-run growth',
      'Trend rate of growth',
      'Output gap',
      'Positive output gap',
      'Negative output gap',
      // Business cycle
      'Boom',
      'Recession',
      'Slump',
      'Recovery',
      'Causes of business cycle',
    ],
  },

  // 4.2.2 How the macroeconomy works
  {
    id: 'aqa-alevel-econ-macro-model',
    examBoard: 'aqa',
    name: 'How the Macroeconomy Works',
    description: 'AD/AS model, multiplier, and transmission mechanisms',
    icon: '⚙️',
    color: 'bg-amber-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // Circular flow of income
      'Injections',
      'Investment',
      'Government spending',
      'Exports',
      'Withdrawals (leakages)',
      'Savings',
      'Taxation',
      'Imports',
      'Equilibrium in circular flow',
      // Aggregate demand
      'Components of AD',
      'Consumption (C)',
      'Investment (I)',
      'Government spending (G)',
      'Net exports (X-M)',
      'AD curve',
      'Shifts in AD',
      // Consumption
      'Consumption function',
      'Average propensity to consume (APC)',
      'Marginal propensity to consume (MPC)',
      'Determinants of consumption',
      'Wealth effects',
      'Interest rates',
      'Consumer confidence',
      // Savings
      'Average propensity to save (APS)',
      'Marginal propensity to save (MPS)',
      'Determinants of saving',
      // Investment
      'Gross vs net investment',
      'Determinants of investment',
      'Interest rates',
      'Business confidence',
      'Animal spirits',
      'Accelerator theory',
      'Rate of economic growth',
      // Aggregate supply
      'Short-run aggregate supply (SRAS)',
      'Long-run aggregate supply (LRAS)',
      'Keynesian LRAS',
      'Classical LRAS',
      'Shifts in SRAS',
      'Shifts in LRAS',
      // Macroeconomic equilibrium
      'AD/AS equilibrium',
      'Changes in equilibrium',
      'Demand-side shocks',
      'Supply-side shocks',
      // Multiplier
      'The multiplier concept',
      'Multiplier formula',
      'Size of multiplier',
      'Factors affecting multiplier',
      'Marginal propensities',
    ],
  },

  // 4.2.3 Economic performance
  {
    id: 'aqa-alevel-econ-performance',
    examBoard: 'aqa',
    name: 'Economic Performance',
    description: 'Growth, employment, inflation, and balance of payments',
    icon: '🎯',
    color: 'bg-lime-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // Economic growth
      'Actual vs potential growth',
      'Causes of short-run growth',
      'Causes of long-run growth',
      'Investment in capital',
      'Investment in human capital',
      'Technology and innovation',
      'Labour supply',
      'Productivity growth',
      'Benefits of growth',
      'Higher living standards',
      'Employment',
      'Tax revenues',
      'Costs of growth',
      'Inflation',
      'Balance of payments',
      'Environmental costs',
      'Sustainability',
      // Employment and unemployment
      'Labour force participation',
      'Employment rate',
      'Unemployment rate',
      'Types of unemployment',
      'Frictional unemployment',
      'Structural unemployment',
      'Cyclical unemployment',
      'Seasonal unemployment',
      'Real wage unemployment',
      'Natural rate of unemployment',
      'NAIRU',
      'Causes of unemployment',
      'Consequences of unemployment',
      'Output loss',
      'Fiscal costs',
      'Social costs',
      'Hysteresis',
      // Inflation and deflation
      'Consumer Price Index (CPI)',
      'Retail Price Index (RPI)',
      'CPIH',
      'Inflation target',
      'Causes of inflation',
      'Demand-pull inflation',
      'Cost-push inflation',
      'Imported inflation',
      'Expectations',
      'Wage-price spiral',
      'Consequences of inflation',
      'Shoe leather costs',
      'Menu costs',
      'Uncertainty',
      'Redistribution',
      'Competitiveness',
      'Deflation',
      'Causes of deflation',
      'Consequences of deflation',
      'Debt deflation',
      // Balance of payments
      'Current account',
      'Trade in goods',
      'Trade in services',
      'Primary income',
      'Secondary income',
      'Financial account',
      'Capital account',
      'Balance of payments equilibrium',
      'Current account deficit',
      'Current account surplus',
      'Causes of deficit/surplus',
      'Consequences of deficit/surplus',
    ],
  },

  // 4.2.4 Financial markets and monetary policy
  {
    id: 'aqa-alevel-econ-monetary',
    examBoard: 'aqa',
    name: 'Financial Markets and Monetary Policy',
    description: 'Financial markets, money, banking, and monetary policy',
    icon: '💰',
    color: 'bg-violet-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // Money and banking
      'Functions of money',
      'Medium of exchange',
      'Store of value',
      'Unit of account',
      'Standard of deferred payment',
      'Money supply',
      'Narrow money',
      'Broad money',
      'Commercial banks',
      'Money creation',
      'Credit multiplier',
      // Financial markets
      'Functions of financial markets',
      'Capital markets',
      'Money markets',
      'Foreign exchange markets',
      'Bond market',
      'Equity market',
      // Central banks
      'Role of Bank of England',
      'Monetary Policy Committee',
      'Lender of last resort',
      'Financial stability',
      // Monetary policy
      'Objectives of monetary policy',
      'Interest rates',
      'Bank Rate',
      'Transmission mechanism',
      'Effect on consumption',
      'Effect on investment',
      'Effect on exchange rate',
      'Effect on asset prices',
      'Quantitative easing',
      'Forward guidance',
      // Regulation of banks
      'Capital requirements',
      'Liquidity requirements',
      'Financial conduct regulation',
      'Systemic risk',
    ],
  },

  // 4.2.5 Fiscal policy and supply-side policies
  {
    id: 'aqa-alevel-econ-fiscal',
    examBoard: 'aqa',
    name: 'Fiscal Policy and Supply-side Policies',
    description: 'Government spending, taxation, and supply-side measures',
    icon: '📋',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // Fiscal policy
      'Definition of fiscal policy',
      'Government spending',
      'Current spending',
      'Capital spending',
      'Transfer payments',
      'Automatic stabilisers',
      'Discretionary fiscal policy',
      'Taxation',
      'Direct taxes',
      'Indirect taxes',
      'Progressive taxation',
      'Regressive taxation',
      'Proportional taxation',
      'Canons of taxation',
      'Laffer curve',
      // Government budget
      'Budget deficit',
      'Budget surplus',
      'Cyclical deficit',
      'Structural deficit',
      'National debt',
      'Debt to GDP ratio',
      'Fiscal rules',
      'Austerity',
      'Crowding out',
      'Ricardian equivalence',
      // Supply-side policies
      'Definition of supply-side policies',
      'Shifting LRAS',
      'Market-based policies',
      'Income tax cuts',
      'Corporation tax cuts',
      'Deregulation',
      'Privatisation',
      'Trade union reform',
      'Welfare reform',
      'Interventionist policies',
      'Education and training',
      'Infrastructure investment',
      'Industrial policy',
      'Regional policy',
      'R&D subsidies',
      'Evaluation of supply-side policies',
      'Time lags',
      'Effectiveness',
      'Equity concerns',
    ],
  },

  // 4.2.6 The international economy
  {
    id: 'aqa-alevel-econ-international',
    examBoard: 'aqa',
    name: 'The International Economy',
    description: 'International trade, exchange rates, and globalisation',
    icon: '🌍',
    color: 'bg-sky-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // International trade
      'Benefits of trade',
      'Specialisation',
      'Absolute advantage',
      'Comparative advantage',
      'Gains from trade',
      'Terms of trade',
      'Pattern of trade',
      // Trade restrictions
      'Tariffs',
      'Quotas',
      'Subsidies',
      'Non-tariff barriers',
      'Arguments for protectionism',
      'Infant industry',
      'Dumping',
      'National security',
      'Diversification',
      'Arguments against protectionism',
      'Trade creation',
      'Trade diversion',
      // Trading blocs
      'Free trade area',
      'Customs union',
      'Single market',
      'Economic union',
      'Monetary union',
      'World Trade Organization (WTO)',
      // Exchange rates
      'Exchange rate determination',
      'Floating exchange rates',
      'Demand for currency',
      'Supply of currency',
      'Fixed exchange rates',
      'Managed float',
      'Appreciation',
      'Depreciation',
      'Causes of exchange rate changes',
      'Effects of exchange rate changes',
      'On trade',
      'On inflation',
      'On output and employment',
      'Competitive devaluation',
      'Marshall-Lerner condition',
      'J-curve effect',
      // Globalisation
      'Definition of globalisation',
      'Causes of globalisation',
      'Trade liberalisation',
      'Technology',
      'Multinational corporations',
      'Benefits of globalisation',
      'Costs of globalisation',
      'Winners and losers',
      'De-globalisation',
    ],
  },
];

export function getAQAALevelEconomicsTopicById(id: string): Topic | undefined {
  return aqaALevelEconomicsTopics.find((topic) => topic.id === id);
}

export function countAQAALevelEconomicsSubtopics(): number {
  return aqaALevelEconomicsTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
