// OCR GCSE Economics (J205) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/economics-j205-from-2017/
// Component 1: Introduction to Economics (50%)
// Component 2: National and International Economics (50%)

import { Topic } from '@/types';

export const ocrEconomicsTopics: Topic[] = [
  // ============================================================================
  // COMPONENT 1: INTRODUCTION TO ECONOMICS - Topics 1-4
  // ============================================================================

  // Topic 1: Main economic groups and factors of production
  {
    id: 'groups',
    examBoard: 'ocr',
    name: 'Main Economic Groups and Factors of Production',
    description: 'Economic agents, factors of production, and resource allocation',
    icon: '🏛️',
    color: 'bg-blue-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // 1a The economic problem
      'Scarcity',
      'Limited resources',
      'Unlimited wants',
      'Choice',
      'Opportunity cost',
      // 1b Main economic groups
      'Consumers',
      'Producers/firms',
      'Government',
      'Workers',
      // 1c Factors of production
      'Land',
      'Labour',
      'Capital',
      'Enterprise',
      'Rewards for factors of production',
      'Rent',
      'Wages',
      'Interest',
      'Profit',
      // 1d Resource allocation
      'What to produce',
      'How to produce',
      'For whom to produce',
      'Market economy',
      'Mixed economy',
      'Command economy',
    ],
  },

  // Topic 2: Markets
  {
    id: 'markets',
    examBoard: 'ocr',
    name: 'Markets',
    description: 'Demand, supply, price determination, and price elasticity',
    icon: '📈',
    color: 'bg-green-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // 2a Demand
      'Definition of demand',
      'Effective demand',
      'Demand curves',
      'Shifts of demand curves',
      'Movements along demand curves',
      'Factors affecting demand',
      'Price',
      'Income',
      'Prices of other goods',
      'Substitutes',
      'Complements',
      'Tastes and preferences',
      'Advertising',
      'Population',
      // 2b Supply
      'Definition of supply',
      'Supply curves',
      'Shifts of supply curves',
      'Movements along supply curves',
      'Factors affecting supply',
      'Costs of production',
      'Technology',
      'Indirect taxes',
      'Subsidies',
      'Weather',
      'Number of producers',
      // 2c Price determination
      'Market equilibrium',
      'Equilibrium price',
      'Equilibrium quantity',
      'Excess demand (shortage)',
      'Excess supply (surplus)',
      'How markets clear',
      'Changes in equilibrium',
      // 2d Price elasticity of demand (PED)
      'Definition of PED',
      'Formula for PED',
      'Calculating PED',
      'Elastic demand',
      'Inelastic demand',
      'Unit elastic demand',
      'Factors affecting PED',
      'Substitutes available',
      'Necessity vs luxury',
      'Proportion of income',
      'Time period',
      'Addiction',
      'Importance of PED to firms',
      'Importance of PED to government',
      // 2e Price elasticity of supply (PES)
      'Definition of PES',
      'Formula for PES',
      'Calculating PES',
      'Elastic supply',
      'Inelastic supply',
      'Factors affecting PES',
      'Time period',
      'Spare capacity',
      'Stock levels',
      'Ease of switching production',
    ],
  },

  // Topic 3: Market failure and government intervention
  {
    id: 'market-failure',
    examBoard: 'ocr',
    name: 'Market Failure and Government Intervention',
    description: 'Types of market failure and corrective policies',
    icon: '⚠️',
    color: 'bg-red-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // 3a Market failure
      'Definition of market failure',
      'When markets fail to allocate resources efficiently',
      // 3b Externalities
      'Definition of externalities',
      'Private costs',
      'External costs',
      'Social costs',
      'Private benefits',
      'External benefits',
      'Social benefits',
      'Negative externalities',
      'Negative externalities of consumption',
      'Negative externalities of production',
      'Positive externalities',
      'Positive externalities of consumption',
      'Positive externalities of production',
      'Over-production from negative externalities',
      'Under-production from positive externalities',
      // 3c Merit goods
      'Definition of merit goods',
      'Characteristics of merit goods',
      'Examples of merit goods',
      'Education as merit good',
      'Healthcare as merit good',
      'Under-consumption of merit goods',
      'Information failure',
      // 3d Demerit goods
      'Definition of demerit goods',
      'Characteristics of demerit goods',
      'Examples of demerit goods',
      'Tobacco as demerit good',
      'Alcohol as demerit good',
      'Over-consumption of demerit goods',
      // 3e Public goods
      'Definition of public goods',
      'Non-excludability',
      'Non-rivalry',
      'Free rider problem',
      'Examples of public goods',
      'Street lighting',
      'National defence',
      // 3f Government intervention
      'Indirect taxes',
      'Effect of indirect tax on market',
      'Tax incidence',
      'Subsidies',
      'Effect of subsidies on market',
      'Minimum prices',
      'Maximum prices',
      'State provision',
      'Government provision of public goods',
      'Government provision of merit goods',
      'Regulation',
      // 3g Government failure
      'Definition of government failure',
      'Unintended consequences',
      'Information gaps',
      'Administrative costs',
    ],
  },

  // Topic 4: Production, costs, revenue and profit
  {
    id: 'production',
    examBoard: 'ocr',
    name: 'Production, Costs, Revenue and Profit',
    description: 'Business economics and financial concepts',
    icon: '🏭',
    color: 'bg-purple-500',
    paperRestriction: 'Component 1',
    subtopics: [
      // 4a Production
      'Definition of production',
      'Productivity',
      'Output per worker',
      'Specialisation',
      'Division of labour',
      'Advantages of specialisation',
      'Disadvantages of specialisation',
      // 4b Costs
      'Fixed costs',
      'Variable costs',
      'Total costs',
      'Average costs',
      'Cost calculations',
      'Economies of scale',
      'Types of economies of scale',
      'Technical economies',
      'Purchasing economies',
      'Financial economies',
      'Marketing economies',
      'Managerial economies',
      'Diseconomies of scale',
      // 4c Revenue
      'Total revenue',
      'Average revenue',
      'Revenue formula',
      'Price x quantity',
      // 4d Profit
      'Definition of profit',
      'Profit formula',
      'Total revenue - total costs',
      'Role of profit in market economy',
      'Profit as incentive',
      'Profit as signal',
      'Profit and investment',
    ],
  },

  // ============================================================================
  // COMPONENT 2: NATIONAL AND INTERNATIONAL ECONOMICS - Topics 5-7
  // ============================================================================

  // Topic 5: The national economy
  {
    id: 'national',
    examBoard: 'ocr',
    name: 'The National Economy',
    description: 'Macroeconomic indicators, economic growth, and the business cycle',
    icon: '📊',
    color: 'bg-indigo-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // 5a Economic indicators
      'Gross Domestic Product (GDP)',
      'Real GDP',
      'Nominal GDP',
      'GDP per capita',
      'Inflation rate',
      'Unemployment rate',
      // 5b Economic growth
      'Definition of economic growth',
      'Short-run growth',
      'Long-run growth',
      'Actual growth',
      'Potential growth',
      'Benefits of economic growth',
      'Higher living standards',
      'More jobs',
      'Higher tax revenues',
      'Costs of economic growth',
      'Environmental damage',
      'Inequality',
      'Inflation pressure',
      // 5c The business cycle
      'Boom',
      'Recession',
      'Slump',
      'Recovery',
      'Peak',
      'Trough',
      'Characteristics of each phase',
      'Output during business cycle',
      'Employment during business cycle',
      // 5d Inflation
      'Definition of inflation',
      'Measuring inflation',
      'Consumer Prices Index (CPI)',
      'Causes of inflation',
      'Demand-pull inflation',
      'Cost-push inflation',
      'Effects of inflation',
      'Reduced purchasing power',
      'Uncertainty for businesses',
      'International competitiveness',
      'Menu costs',
      'Shoe leather costs',
      'Winners and losers from inflation',
      // 5e Unemployment
      'Definition of unemployment',
      'Measuring unemployment',
      'Claimant count',
      'Labour Force Survey',
      'Types of unemployment',
      'Cyclical unemployment',
      'Structural unemployment',
      'Frictional unemployment',
      'Seasonal unemployment',
      'Causes of unemployment',
      'Effects of unemployment',
      'On individuals',
      'On economy',
      'On government',
    ],
  },

  // Topic 6: Government economic objectives and policies
  {
    id: 'policy',
    examBoard: 'ocr',
    name: 'Government Economic Objectives and Policies',
    description: 'Fiscal policy, monetary policy, and supply-side policies',
    icon: '🏛️',
    color: 'bg-emerald-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // 6a Government objectives
      'Economic growth',
      'Low unemployment',
      'Low and stable inflation',
      'Balance of payments equilibrium',
      'Fair distribution of income',
      'Conflicts between objectives',
      // 6b Fiscal policy
      'Definition of fiscal policy',
      'Government spending',
      'Taxation',
      'Direct taxes',
      'Income tax',
      'Corporation tax',
      'Indirect taxes',
      'VAT',
      'Excise duties',
      'Progressive taxes',
      'Regressive taxes',
      'Government budget',
      'Budget deficit',
      'Budget surplus',
      'National debt',
      'Expansionary fiscal policy',
      'Contractionary fiscal policy',
      'Automatic stabilisers',
      // 6c Monetary policy
      'Definition of monetary policy',
      'Bank of England',
      'Monetary Policy Committee (MPC)',
      'Interest rates',
      'Bank Rate',
      'Effects of interest rate changes',
      'On spending',
      'On saving',
      'On borrowing',
      'On investment',
      'On exchange rates',
      'Quantitative easing',
      // 6d Supply-side policies
      'Definition of supply-side policies',
      'Market-based supply-side policies',
      'Reducing income tax',
      'Reducing corporation tax',
      'Reducing benefits',
      'Deregulation',
      'Privatisation',
      'Trade union reform',
      'Interventionist supply-side policies',
      'Education and training',
      'Infrastructure spending',
      'Healthcare investment',
      'Research and development',
    ],
  },

  // Topic 7: International trade and the global economy
  {
    id: 'trade',
    examBoard: 'ocr',
    name: 'International Trade and the Global Economy',
    description: 'Trade, exchange rates, globalisation, and economic development',
    icon: '🌍',
    color: 'bg-amber-500',
    paperRestriction: 'Component 2',
    subtopics: [
      // 7a International trade
      'Reasons for international trade',
      'Specialisation',
      'Comparative advantage',
      'Access to wider markets',
      'Greater choice',
      'Lower prices',
      'Imports',
      'Exports',
      'Visible trade',
      'Invisible trade',
      // 7b Balance of payments
      'Current account',
      'Trade in goods',
      'Trade in services',
      'Current account deficit',
      'Current account surplus',
      'Causes of current account deficit',
      'Consequences of current account deficit',
      // 7c Exchange rates
      'Definition of exchange rate',
      'Floating exchange rate',
      'Fixed exchange rate',
      'Currency appreciation',
      'Currency depreciation',
      'Factors affecting exchange rates',
      'Interest rates',
      'Inflation',
      'Trade balance',
      'Speculation',
      'Effects of exchange rate changes',
      'On exports',
      'On imports',
      'On inflation',
      'On economic growth',
      // 7d Trade policy
      'Free trade',
      'Benefits of free trade',
      'Protectionism',
      'Tariffs',
      'Quotas',
      'Subsidies to domestic producers',
      'Non-tariff barriers',
      'Arguments for protectionism',
      'Infant industry argument',
      'Protecting jobs',
      'National security',
      'Arguments against protectionism',
      // 7e Globalisation
      'Definition of globalisation',
      'Causes of globalisation',
      'Improved transport',
      'Improved communication',
      'Reduced trade barriers',
      'Transnational corporations (TNCs)',
      'Benefits of globalisation',
      'Costs of globalisation',
      // 7f Economic development
      'Definition of economic development',
      'Difference from economic growth',
      'Measures of development',
      'Human Development Index (HDI)',
      'Factors affecting development',
      'Education',
      'Healthcare',
      'Infrastructure',
      'Political stability',
    ],
  },
];

export function getOCREconomicsTopicById(id: string): Topic | undefined {
  return ocrEconomicsTopics.find((topic) => topic.id === id);
}

export function getOCREconomicsTopicsByComponent(component: 1 | 2): Topic[] {
  const componentName = `Component ${component}`;
  return ocrEconomicsTopics.filter((topic) => topic.paperRestriction === componentName);
}

export function countOCREconomicsSubtopics(): number {
  return ocrEconomicsTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
