// Edexcel A-Level English Literature (9ET0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/english-literature-2015.html

import { Topic } from '@/types';

export const edexcelALevelEnglishLiteratureTopics: Topic[] = [
  // Paper 1: Drama - Shakespeare (Tragedy)
  {
    id: 'lit-othello',
    name: 'Othello (Tragedy)',
    description: 'Shakespeare\'s domestic tragedy exploring jealousy, race, and betrayal',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Tragic hero and hamartia',
      'Jealousy as tragic flaw',
      'Race and outsider status',
      'Manipulation and evil',
      'Love and trust destroyed',
      'Honour and reputation',
      'Othello\'s nobility and fall',
      'Iago\'s motiveless malignity',
      'Desdemona\'s innocence',
      'Emilia\'s awakening',
      'Venetian society',
      'Military vs domestic',
      'Aristotelian tragedy',
      'Language and rhetoric',
      'Dramatic structure',
      'Critical perspectives on race',
    ],
  },
  {
    id: 'lit-hamlet',
    name: 'Hamlet (Tragedy)',
    description: 'Shakespeare\'s greatest tragedy of revenge, madness, and mortality',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Revenge and delay',
      'Madness and performance',
      'Mortality and death',
      'Corruption and decay',
      'Appearance vs reality',
      'Family and betrayal',
      'Hamlet\'s soliloquies',
      'Claudius\'s guilt',
      'Gertrude\'s ambiguity',
      'Ophelia\'s tragedy',
      'The ghost\'s role',
      'Play within play',
      'Graveyard scene',
      'Revenge tragedy genre',
      'Existential questions',
      'Performance history',
    ],
  },
  {
    id: 'lit-twelfth-night-alevel',
    name: 'Twelfth Night (Comedy)',
    description: 'Shakespeare\'s romantic comedy of disguise, desire, and festive misrule',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love and desire',
      'Gender and disguise',
      'Madness and festivity',
      'Class ambition',
      'Music and melancholy',
      'Comic vs cruel',
      'Viola\'s resourcefulness',
      'Orsino\'s self-indulgence',
      'Olivia\'s awakening',
      'Malvolio\'s humiliation',
      'Sir Toby\'s world',
      'Feste\'s wisdom',
      'Comic conventions',
      'Green world theory',
      'Gender performance',
      'Dark elements in comedy',
    ],
  },
  // Paper 1: Drama - Other Drama
  {
    id: 'lit-streetcar-edexcel',
    name: 'A Streetcar Named Desire',
    description: 'Williams\' Southern Gothic tragedy of illusion versus brutal reality',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Illusion vs reality',
      'Desire and sexuality',
      'Old South decline',
      'Masculinity and violence',
      'Madness and breakdown',
      'Class conflict',
      'Blanche\'s fragility',
      'Stanley\'s dominance',
      'Stella\'s choice',
      'Mitch\'s compassion',
      'Expressionist staging',
      'Music and symbols',
      'American Dream critique',
      'Tragic structure',
      'Gender politics',
      'Production interpretations',
    ],
  },
  {
    id: 'lit-hedda-gabler',
    name: 'Hedda Gabler',
    description: 'Ibsen\'s psychological tragedy of a woman trapped by society',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Female entrapment',
      'Boredom and frustration',
      'Power and control',
      'Social conventions',
      'Sexuality and fear',
      'Death and destruction',
      'Hedda\'s complexity',
      'Tesman\'s inadequacy',
      'Lovborg\'s passion',
      'Judge Brack\'s manipulation',
      'Realistic drama',
      'Symbolism (pistols, vine leaves)',
      'Tragic inevitability',
      'Norwegian society',
      'Feminist readings',
      'Modern productions',
    ],
  },
  // Paper 2: Prose
  {
    id: 'lit-frankenstein-alevel',
    name: 'Frankenstein',
    description: 'Shelley\'s Gothic novel exploring creation, responsibility, and monstrosity',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Creation and responsibility',
      'Monstrosity and humanity',
      'Ambition and hubris',
      'Isolation and rejection',
      'Nature vs science',
      'The sublime',
      'Victor\'s obsession',
      'The creature\'s eloquence',
      'Walton as frame',
      'Female characters',
      'The De Laceys',
      'Paradise Lost echoes',
      'Gothic conventions',
      'Romantic influences',
      'Science and ethics',
      'Critical approaches',
    ],
  },
  {
    id: 'lit-dracula',
    name: 'Dracula',
    description: 'Stoker\'s Gothic masterpiece exploring Victorian anxieties',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Good vs evil',
      'Victorian sexuality',
      'Foreignness and invasion',
      'Science vs superstition',
      'Gender and the New Woman',
      'Blood and corruption',
      'Count Dracula\'s power',
      'Van Helsing\'s knowledge',
      'Mina\'s strength',
      'Lucy\'s transformation',
      'Harker\'s ordeal',
      'Epistolary form',
      'Gothic atmosphere',
      'Colonial anxieties',
      'Technology and modernity',
      'Critical interpretations',
    ],
  },
  {
    id: 'lit-handmaids-edexcel',
    name: 'The Handmaid\'s Tale',
    description: 'Atwood\'s dystopia examining theocratic oppression of women',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Totalitarianism',
      'Female subjugation',
      'Language and control',
      'Memory and resistance',
      'Body and reproduction',
      'Religious extremism',
      'Offred\'s survival',
      'The Commander',
      'Serena Joy',
      'Nick and rebellion',
      'The historical notes',
      'Gilead\'s creation',
      'Feminist critique',
      'Dystopian tradition',
      'Narrative unreliability',
      'Contemporary parallels',
    ],
  },
  // Paper 3: Poetry
  {
    id: 'lit-keats-edexcel',
    name: 'John Keats: Poetry',
    description: 'Keats\'s Romantic poetry exploring beauty, mortality, and imagination',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Beauty and truth',
      'Mortality and permanence',
      'The imagination',
      'Sensory richness',
      'Love and longing',
      'Nature and art',
      'Ode to a Nightingale',
      'Ode on a Grecian Urn',
      'To Autumn',
      'La Belle Dame sans Merci',
      'The Eve of St Agnes',
      'Bright Star',
      'Ode forms',
      'Negative capability',
      'Classical influences',
      'Romantic context',
    ],
  },
  {
    id: 'lit-rossetti',
    name: 'Christina Rossetti: Poetry',
    description: 'Rossetti\'s Victorian poetry of faith, love, and female experience',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Religious devotion',
      'Death and afterlife',
      'Unfulfilled love',
      'Female desire',
      'Sisterhood and rivalry',
      'Nature imagery',
      'Goblin Market',
      'Remember',
      'A Birthday',
      'Winter: My Secret',
      'In the Round Tower',
      'Devotional poems',
      'Pre-Raphaelite context',
      'Gender and voice',
      'Form and technique',
      'Critical debates',
    ],
  },
  {
    id: 'lit-larkin',
    name: 'Philip Larkin: Poetry',
    description: 'Larkin\'s post-war poetry of mortality, loneliness, and everyday England',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Mortality and time',
      'Loneliness and isolation',
      'England and Englishness',
      'Love and relationships',
      'Work and routine',
      'Religion\'s decline',
      'The Whitsun Weddings',
      'Church Going',
      'Aubade',
      'This Be The Verse',
      'High Windows',
      'Mr Bleaney',
      'Movement poetry',
      'Technical mastery',
      'Pessimism and humour',
      'Critical reputation',
    ],
  },
  // Coursework
  {
    id: 'lit-coursework',
    name: 'Coursework: Comparative Essay',
    description: 'Independent comparative study of two texts',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Text selection',
      'Thesis development',
      'Comparative frameworks',
      'Critical reading',
      'Research methods',
      'Essay structure',
      'AO1: Argument and style',
      'AO2: Methods analysis',
      'AO3: Context',
      'AO4: Connections',
      'AO5: Interpretations',
      'Referencing skills',
      'Drafting process',
      'Word count (2500-3000)',
      'Academic integrity',
      'Moderation criteria',
    ],
  },
];

export function getEdexcelALevelEnglishLiteratureTopicById(id: string): Topic | undefined {
  return edexcelALevelEnglishLiteratureTopics.find((topic) => topic.id === id);
}
