// AQA A-Level English Literature A (7712) Topics
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/english/a-level/english-literature-a-7712

import { Topic } from '@/types';

export const aqaALevelEnglishLiteratureTopics: Topic[] = [
  // Paper 1: Love Through the Ages
  {
    id: 'aqa-alevel-eng-lit-othello',
    name: 'Othello',
    description: 'Shakespeare\'s tragedy exploring jealousy, race, and the destruction of love',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Jealousy and its consequences',
      'Race and otherness',
      'Love and trust',
      'Deception and manipulation',
      'Honour and reputation',
      'Gender and patriarchy',
      'Othello as tragic hero',
      'Iago\'s villainy',
      'Desdemona\'s virtue',
      'The handkerchief',
      'Venice vs Cyprus',
      'Domestic tragedy',
      'Military honour',
      'Language and rhetoric',
      'Dramatic irony',
      'Critical interpretations',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-taming-shrew',
    name: 'The Taming of the Shrew',
    description: 'Shakespeare\'s controversial comedy exploring gender, marriage, and power',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Gender roles and power',
      'Marriage as transaction',
      'Performance and identity',
      'Taming and transformation',
      'Love and compatibility',
      'Comedy and controversy',
      'Katherina\'s character',
      'Petruchio\'s methods',
      'Bianca and suitors',
      'The induction frame',
      'Disguise and deception',
      'The final speech',
      'Renaissance marriage',
      'Feminist interpretations',
      'Irony and subversion',
      'Modern productions',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-keats-poetry',
    name: 'Keats: Selected Poems',
    description: 'Keats\'s exploration of beauty, mortality, and the creative imagination',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Beauty and truth',
      'Mortality and transience',
      'The imagination',
      'Negative capability',
      'Sensory experience',
      'Art and permanence',
      'Ode to a Nightingale',
      'Ode on a Grecian Urn',
      'La Belle Dame sans Merci',
      'The Eve of St Agnes',
      'To Autumn',
      'Ode on Melancholy',
      'Romantic ideals',
      'Form and technique',
      'Classical influences',
      'Critical approaches',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-great-gatsby',
    name: 'The Great Gatsby',
    description: 'Fitzgerald\'s critique of the American Dream through tragic romance',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'The American Dream',
      'Love and obsession',
      'Wealth and corruption',
      'Time and the past',
      'Class and social mobility',
      'Appearance vs reality',
      'Gatsby\'s idealisation',
      'Daisy as symbol',
      'Nick as narrator',
      'Tom\'s brutality',
      'The green light',
      'The eyes of Dr T.J. Eckleburg',
      'Jazz Age context',
      'Narrative technique',
      'Symbolism and colour',
      'Modernist elements',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-wuthering-heights',
    name: 'Wuthering Heights',
    description: 'Emily Brontë\'s Gothic masterpiece of destructive passion',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Passionate love',
      'Revenge and cruelty',
      'Nature and wildness',
      'Social class',
      'The supernatural',
      'Childhood and identity',
      'Heathcliff\'s transformation',
      'Catherine\'s conflict',
      'The second generation',
      'Lockwood and Nelly',
      'Heights vs Grange',
      'Windows and boundaries',
      'Gothic elements',
      'Narrative complexity',
      'Critical interpretations',
      'Romantic vs Victorian',
    ],
  },
  // Paper 2: Texts in Shared Contexts - WW1 and its Aftermath
  {
    id: 'aqa-alevel-eng-lit-war-poetry',
    name: 'WW1 Poetry',
    description: 'Poetry responding to the First World War\'s devastation',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Patriotism and disillusion',
      'Suffering and sacrifice',
      'Comradeship and loss',
      'Nature and destruction',
      'Memory and memorialisation',
      'Truth and propaganda',
      'Owen\'s poetry',
      'Sassoon\'s satire',
      'Rosenberg\'s imagery',
      'Brooke\'s idealism',
      'Trench experience',
      'Shell shock and trauma',
      'Form and innovation',
      'Contrasting perspectives',
      'Home front vs front line',
      'Legacy and remembrance',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-regeneration',
    name: 'Regeneration',
    description: 'Pat Barker\'s novel exploring trauma and treatment in WW1',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Psychological trauma',
      'Masculinity and war',
      'Class and authority',
      'Treatment and recovery',
      'Memory and repression',
      'Duty vs conscience',
      'Rivers and his methods',
      'Sassoon\'s protest',
      'Prior\'s complexity',
      'Burns\'s suffering',
      'Craiglockhart setting',
      'Historical accuracy',
      'Gender and sexuality',
      'Narrative technique',
      'Anti-war message',
      'Regeneration trilogy',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-atonement',
    name: 'Atonement',
    description: 'McEwan\'s metafictional exploration of guilt, war, and storytelling',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Guilt and atonement',
      'Truth and fiction',
      'War\'s devastation',
      'Class and prejudice',
      'Love and loss',
      'Childhood and innocence',
      'Briony\'s crime',
      'Robbie and Cecilia',
      'Dunkirk retreat',
      'The twist ending',
      'Metafictional elements',
      'Narrative perspective',
      'Literary allusions',
      'Time structure',
      'The power of stories',
      'Critical interpretations',
    ],
  },
  // Modern and Contemporary Topics
  {
    id: 'aqa-alevel-eng-lit-handmaids-tale',
    name: 'The Handmaid\'s Tale',
    description: 'Atwood\'s dystopian vision of female oppression in Gilead',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Patriarchal oppression',
      'Female resistance',
      'Language and power',
      'Memory and identity',
      'Religion and control',
      'Love and survival',
      'Offred\'s narrative',
      'The Commander',
      'Serena Joy',
      'Moira\'s rebellion',
      'Historical Notes',
      'Biblical influences',
      'Feminist critique',
      'Dystopian genre',
      'Narrative ambiguity',
      'Contemporary relevance',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-streetcar',
    name: 'A Streetcar Named Desire',
    description: 'Tennessee Williams\' tragedy of illusion, desire, and destruction',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Fantasy vs reality',
      'Desire and sexuality',
      'Death of the Old South',
      'Masculinity and violence',
      'Madness and fragility',
      'Class and culture clash',
      'Blanche\'s decline',
      'Stanley\'s brutality',
      'Stella\'s complicity',
      'Mitch and illusion',
      'The Elysian Fields',
      'Light and darkness',
      'Music and atmosphere',
      'Expressionist technique',
      'American Dream',
      'Critical perspectives',
    ],
  },
  {
    id: 'aqa-alevel-eng-lit-nea',
    name: 'Non-Exam Assessment (NEA)',
    description: 'Independent critical study comparing texts across time',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Choosing texts',
      'Developing a thesis',
      'Comparative analysis',
      'Critical approaches',
      'Research skills',
      'Academic writing',
      'AO1: Response and argument',
      'AO2: Methods analysis',
      'AO3: Contextual understanding',
      'AO4: Connections',
      'AO5: Critical interpretations',
      'Bibliography skills',
      'Planning structure',
      'Draft development',
      'Word count management',
      'Academic integrity',
    ],
  },
];

export function getAQAALevelEnglishLiteratureTopicById(id: string): Topic | undefined {
  return aqaALevelEnglishLiteratureTopics.find((topic) => topic.id === id);
}
