// OCR GCSE Business (J204) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/business-j204-from-2017/
// Paper 1: Business 1 – Business Activity, Marketing and People (50%)
// Paper 2: Business 2 – Operations, Finance and Influences on Business (50%)

import { Topic } from '@/types';

export const ocrGCSEBusinessTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: BUSINESS 1 – BUSINESS ACTIVITY, MARKETING AND PEOPLE
  // ============================================================================
  {
    id: 'business-activity',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'Business Activity',
    description: 'The role of business enterprise, business planning, ownership, and objectives',
    icon: '🏢',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.1 The role of business enterprise and entrepreneurship
      'Business enterprise',
      'Purpose of business',
      'Producing goods',
      'Providing services',
      'Enterprise',
      'Entrepreneurs',
      'Role of entrepreneurs',
      'Characteristics of entrepreneurs',
      'Risk-taking',
      'Creativity',
      'Innovation',
      'Determination',
      'Risk and reward',
      'Financial risk',
      'Personal risk',
      'Rewards of enterprise',
      'Profit',
      'Independence',
      'Satisfaction',
      'Reasons for starting a business',
      'Spotting opportunities',
      'Being your own boss',
      'Flexibility',
      'Challenges of starting a business',
      'Raising finance',
      'Finding customers',
      'Competition',
      // 1.2 Business planning
      'Business planning',
      'Business plans',
      'Purpose of business plans',
      'Securing finance',
      'Setting objectives',
      'Components of business plan',
      'Executive summary',
      'Business description',
      'Market analysis',
      'Marketing strategy',
      'Operations plan',
      'Financial projections',
      'Cash flow forecast',
      'Break-even analysis',
      'SWOT analysis',
      'Strengths',
      'Weaknesses',
      'Opportunities',
      'Threats',
      'Using SWOT analysis',
      // 1.3 Business ownership
      'Business ownership',
      'Sole traders',
      'Features of sole traders',
      'Advantages of sole traders',
      'Disadvantages of sole traders',
      'Partnerships',
      'Features of partnerships',
      'Advantages of partnerships',
      'Disadvantages of partnerships',
      'Deed of partnership',
      'Unlimited liability',
      'Limited liability',
      'Private limited companies (Ltd)',
      'Features of Ltd',
      'Advantages of Ltd',
      'Disadvantages of Ltd',
      'Public limited companies (PLC)',
      'Features of PLC',
      'Advantages of PLC',
      'Disadvantages of PLC',
      'Shareholders',
      'Dividends',
      'Stock market flotation',
      'Franchises',
      'Franchisor',
      'Franchisee',
      'Advantages of franchising',
      'Disadvantages of franchising',
      'Social enterprises',
      'Not-for-profit organisations',
      'Charities',
      // 1.4 Business aims and objectives
      'Business aims',
      'Business objectives',
      'Financial objectives',
      'Survival',
      'Profit maximisation',
      'Sales growth',
      'Market share',
      'Non-financial objectives',
      'Customer satisfaction',
      'Employee welfare',
      'Social objectives',
      'Environmental objectives',
      'Why objectives differ',
      'Size of business',
      'Stage of development',
      'Type of ownership',
      'Market conditions',
      'Changing objectives',
    ],
  },
  {
    id: 'marketing',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'Marketing',
    description: 'Market research, segmentation, and the marketing mix',
    icon: '📊',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 2.1 The role of marketing
      'Marketing',
      'Role of marketing',
      'Purpose of marketing',
      'Identifying customer needs',
      'Satisfying customer needs',
      'Meeting customer expectations',
      'Building customer relationships',
      'Market',
      'Mass market',
      'Niche market',
      'Advantages of mass market',
      'Advantages of niche market',
      // 2.2 Market research
      'Market research',
      'Purpose of market research',
      'Understanding customers',
      'Identifying gaps',
      'Reducing risk',
      'Primary research',
      'Methods of primary research',
      'Surveys',
      'Questionnaires',
      'Interviews',
      'Focus groups',
      'Observation',
      'Test marketing',
      'Advantages of primary research',
      'Disadvantages of primary research',
      'Secondary research',
      'Methods of secondary research',
      'Internet research',
      'Market reports',
      'Government statistics',
      'Competitor information',
      'Advantages of secondary research',
      'Disadvantages of secondary research',
      'Qualitative data',
      'Quantitative data',
      'Using market research data',
      'Limitations of market research',
      // 2.3 Market segmentation
      'Market segmentation',
      'Methods of segmentation',
      'Demographic segmentation',
      'Age',
      'Gender',
      'Income',
      'Family status',
      'Geographic segmentation',
      'Location',
      'Region',
      'Psychographic segmentation',
      'Lifestyle',
      'Values',
      'Behavioural segmentation',
      'Benefits of segmentation',
      'Target market',
      'Targeting customers',
      // 2.4 The marketing mix – product and price
      'Marketing mix',
      '4Ps',
      'Product',
      'Types of products',
      'Goods',
      'Services',
      'Product design',
      'Function',
      'Aesthetics',
      'Cost to produce',
      'Product differentiation',
      'USP (Unique Selling Point)',
      'Branding',
      'Brand image',
      'Brand loyalty',
      'Benefits of branding',
      'Product life cycle',
      'Development stage',
      'Introduction stage',
      'Growth stage',
      'Maturity stage',
      'Decline stage',
      'Extension strategies',
      'Product portfolio',
      'Boston Matrix',
      'Stars',
      'Cash cows',
      'Question marks',
      'Dogs',
      'Price',
      'Importance of price',
      'Pricing strategies',
      'Cost-plus pricing',
      'Competitive pricing',
      'Penetration pricing',
      'Price skimming',
      'Psychological pricing',
      'Promotional pricing',
      'Factors affecting pricing',
      'Costs',
      'Demand',
      'Competition',
      'Brand image',
      // 2.5 The marketing mix – promotion and place
      'Promotion',
      'Purpose of promotion',
      'Informing',
      'Persuading',
      'Reminding',
      'Types of promotion',
      'Advertising',
      'TV advertising',
      'Print advertising',
      'Online advertising',
      'Sales promotion',
      'Discounts',
      'BOGOF',
      'Competitions',
      'Free samples',
      'Loyalty cards',
      'Sponsorship',
      'Public relations',
      'Social media marketing',
      'Viral marketing',
      'Direct marketing',
      'Choosing promotional methods',
      'Place',
      'Distribution channels',
      'Direct selling',
      'Retailers',
      'Wholesalers',
      'E-commerce',
      'M-commerce',
      'Multi-channel distribution',
      'Factors affecting distribution',
      'Type of product',
      'Target market',
      'Cost',
    ],
  },
  {
    id: 'people',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'People',
    description: 'Recruitment, training, motivation, and organisational structure',
    icon: '👥',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.1 The role of human resources
      'Human resources',
      'Role of HR',
      'Workforce planning',
      'Recruitment',
      'Training',
      'Employee welfare',
      'Legal compliance',
      // 3.2 Organisational structures and ways of working
      'Organisational structure',
      'Hierarchy',
      'Levels of hierarchy',
      'Chain of command',
      'Span of control',
      'Wide span of control',
      'Narrow span of control',
      'Tall structures',
      'Advantages of tall structures',
      'Disadvantages of tall structures',
      'Flat structures',
      'Advantages of flat structures',
      'Disadvantages of flat structures',
      'Centralisation',
      'Advantages of centralisation',
      'Disadvantages of centralisation',
      'Decentralisation',
      'Advantages of decentralisation',
      'Disadvantages of decentralisation',
      'Ways of working',
      'Full-time employment',
      'Part-time employment',
      'Flexible working',
      'Remote working',
      'Zero-hours contracts',
      'Temporary contracts',
      // 3.3 Communication in business
      'Communication',
      'Importance of communication',
      'Internal communication',
      'External communication',
      'Methods of communication',
      'Written communication',
      'Verbal communication',
      'Electronic communication',
      'Visual communication',
      'Effective communication',
      'Barriers to communication',
      'Overcoming barriers',
      // 3.4 Recruitment and selection
      'Recruitment',
      'Recruitment process',
      'Identifying vacancies',
      'Writing job descriptions',
      'Creating person specifications',
      'Internal recruitment',
      'Advantages of internal recruitment',
      'Disadvantages of internal recruitment',
      'External recruitment',
      'Advantages of external recruitment',
      'Disadvantages of external recruitment',
      'Recruitment methods',
      'Job adverts',
      'Recruitment agencies',
      'Online recruitment',
      'Selection',
      'Selection process',
      'Application forms',
      'CVs',
      'Cover letters',
      'Interviews',
      'References',
      'Tests and assessments',
      'Legal considerations',
      'Discrimination',
      'Equal opportunities',
      // 3.5 Motivation and retention
      'Motivation',
      'Importance of motivation',
      'Benefits of motivated staff',
      'Productivity',
      'Quality',
      'Staff retention',
      'Customer service',
      'Financial motivation',
      'Remuneration',
      'Wages',
      'Salaries',
      'Commission',
      'Bonus',
      'Profit sharing',
      'Performance-related pay',
      'Piece rate',
      'Non-financial motivation',
      'Job rotation',
      'Job enrichment',
      'Job enlargement',
      'Empowerment',
      'Autonomy',
      'Recognition',
      'Working environment',
      'Fringe benefits',
      'Staff retention',
      'Reducing staff turnover',
      // 3.6 Training and development
      'Training',
      'Purpose of training',
      'Induction training',
      'On-the-job training',
      'Advantages of on-the-job training',
      'Disadvantages of on-the-job training',
      'Off-the-job training',
      'Advantages of off-the-job training',
      'Disadvantages of off-the-job training',
      'Benefits of training',
      'Costs of training',
      'Development',
      'Career progression',
      'Appraisals',
      'Performance management',
    ],
  },

  // ============================================================================
  // PAPER 2: BUSINESS 2 – OPERATIONS, FINANCE AND INFLUENCES ON BUSINESS
  // ============================================================================
  {
    id: 'production',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'Production',
    description: 'Production processes, quality, customer service, and supply chain',
    icon: '🏭',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 4.1 Production processes
      'Production',
      'Production processes',
      'Job production',
      'Features of job production',
      'Advantages of job production',
      'Disadvantages of job production',
      'Batch production',
      'Features of batch production',
      'Advantages of batch production',
      'Disadvantages of batch production',
      'Flow production',
      'Features of flow production',
      'Advantages of flow production',
      'Disadvantages of flow production',
      'Choosing production method',
      'Nature of product',
      'Demand levels',
      'Available resources',
      'Lean production',
      'Just-in-time (JIT)',
      'Kaizen',
      'Cell production',
      'Technology in production',
      'Automation',
      'CAD (Computer Aided Design)',
      'CAM (Computer Aided Manufacturing)',
      'Robotics',
      'Benefits of technology',
      'Productivity',
      'Measuring productivity',
      'Improving productivity',
      // 4.2 Quality
      'Quality',
      'Importance of quality',
      'Customer satisfaction',
      'Reputation',
      'Competitiveness',
      'Quality control',
      'Inspection',
      'Checking finished products',
      'Advantages of quality control',
      'Disadvantages of quality control',
      'Quality assurance',
      'Building in quality',
      'Zero defects',
      'Advantages of quality assurance',
      'Total Quality Management (TQM)',
      'Continuous improvement',
      'Costs of quality',
      'Prevention costs',
      'Appraisal costs',
      'Failure costs',
      // 4.3 Customer service
      'Customer service',
      'Importance of customer service',
      'Customer satisfaction',
      'Customer loyalty',
      'Repeat business',
      'Elements of customer service',
      'Product knowledge',
      'Speed of service',
      'Reliability',
      'Personalisation',
      'After-sales service',
      'Customer feedback',
      'Handling complaints',
      'ICT in customer service',
      'Online support',
      'FAQs',
      'Chatbots',
      // 4.4 Consumer law
      'Consumer law',
      'Consumer Rights Act 2015',
      'Satisfactory quality',
      'Fit for purpose',
      'As described',
      'Right to refund',
      'Right to repair',
      'Right to replacement',
      'Sale of Goods Act',
      'Consumer protection',
      'Impact of consumer law',
      // 4.5 Business location
      'Business location',
      'Factors affecting location',
      'Proximity to market',
      'Proximity to materials',
      'Proximity to labour',
      'Transport links',
      'Costs',
      'Rent',
      'Rates',
      'Government incentives',
      'Infrastructure',
      'E-commerce impact',
      // 4.6 Working with suppliers
      'Suppliers',
      'Role of suppliers',
      'Choosing suppliers',
      'Price',
      'Quality',
      'Reliability',
      'Flexibility',
      'Location',
      'Supplier relationships',
      'Supply chain',
      'Procurement',
      'Stock management',
      'Stock control',
      'Just-in-time (JIT)',
      'Advantages of JIT',
      'Disadvantages of JIT',
      'Just-in-case',
      'Buffer stock',
      'Lead time',
      'Reorder level',
      'Costs of holding stock',
      'Costs of stockouts',
    ],
  },
  {
    id: 'finance',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'Finance',
    description: 'Sources of finance, cash flow, and financial performance',
    icon: '💰',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 5.1 Sources of finance
      'Finance',
      'Why businesses need finance',
      'Start-up costs',
      'Running costs',
      'Expansion',
      'Internal sources of finance',
      'Retained profit',
      'Sale of assets',
      "Owner's savings",
      'External sources of finance',
      'Bank loans',
      'Advantages of loans',
      'Disadvantages of loans',
      'Bank overdrafts',
      'Advantages of overdrafts',
      'Disadvantages of overdrafts',
      'Trade credit',
      'Hire purchase',
      'Leasing',
      'Share capital',
      'Venture capital',
      'Crowdfunding',
      'Government grants',
      'Choosing sources of finance',
      'Purpose of finance',
      'Amount needed',
      'Duration',
      'Cost of finance',
      'Short-term vs long-term',
      // 5.2 Revenue, costs and profit
      'Revenue',
      'Total revenue',
      'Calculating revenue',
      'Revenue formula',
      'Costs',
      'Fixed costs',
      'Examples of fixed costs',
      'Variable costs',
      'Examples of variable costs',
      'Total costs',
      'Calculating total costs',
      'Interest',
      'Cost of borrowing',
      'Profit',
      'Gross profit',
      'Calculating gross profit',
      'Net profit',
      'Calculating net profit',
      'Profit formula',
      'Importance of profit',
      'Reinvestment',
      'Dividends',
      'Loss',
      'Causes of loss',
      // 5.3 Break-even analysis
      'Break-even',
      'Break-even point',
      'Contribution',
      'Contribution per unit',
      'Calculating break-even',
      'Break-even formula',
      'Break-even charts',
      'Drawing break-even charts',
      'Total revenue line',
      'Total costs line',
      'Fixed costs line',
      'Interpreting break-even charts',
      'Margin of safety',
      'Calculating margin of safety',
      'Uses of break-even analysis',
      'Limitations of break-even analysis',
      // 5.4 Cash and cash flow
      'Cash',
      'Importance of cash',
      'Cash vs profit',
      'Cash flow',
      'Cash inflows',
      'Sources of inflows',
      'Cash outflows',
      'Types of outflows',
      'Net cash flow',
      'Cash flow forecasts',
      'Purpose of forecasts',
      'Structure of cash flow forecast',
      'Opening balance',
      'Closing balance',
      'Cash flow problems',
      'Causes of problems',
      'Low sales',
      'High costs',
      'Poor credit control',
      'Overtrading',
      'Solutions to cash flow problems',
      'Improving inflows',
      'Reducing outflows',
      'Arranging finance',
      // 5.5 Financial performance
      'Financial performance',
      'Gross profit margin',
      'Calculating gross profit margin',
      'Net profit margin',
      'Calculating net profit margin',
      'Interpreting profit margins',
      'Average rate of return (ARR)',
      'Calculating ARR',
      'Interpreting ARR',
      'Using financial data',
      'Limitations of financial data',
    ],
  },
  {
    id: 'influences',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'business',
    name: 'Influences on Business',
    description: 'Ethical, environmental, economic, and legal influences on business',
    icon: '🌍',
    color: 'bg-green-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 6.1 Ethical and environmental considerations
      'Business ethics',
      'Ethical issues',
      'Fair trade',
      'Treatment of workers',
      'Treatment of suppliers',
      'Honest marketing',
      'Animal welfare',
      'Environmental issues',
      'Sustainability',
      'Carbon footprint',
      'Pollution',
      'Waste management',
      'Recycling',
      'Renewable resources',
      'Packaging',
      'Trade-offs',
      'Profit vs ethics',
      'Short-term vs long-term',
      'Pressure groups',
      'Impact of pressure groups',
      'Responding to ethical issues',
      // 6.2 The economic climate
      'Economic climate',
      'Impact on business',
      'Interest rates',
      'Effects of interest rate changes',
      'Cost of borrowing',
      'Consumer spending',
      'Exchange rates',
      'Effects of exchange rate changes',
      'Imports',
      'Exports',
      'Inflation',
      'Effects of inflation',
      'Purchasing power',
      'Unemployment',
      'Effects of unemployment',
      'Consumer confidence',
      'Labour supply',
      'Economic growth',
      'Effects of economic growth',
      'Recession',
      'Effects of recession',
      'Business cycle',
      'Government policies',
      'Taxation',
      'Income tax',
      'VAT',
      'Corporation tax',
      'Government spending',
      'Business rates',
      // 6.3 Globalisation
      'Globalisation',
      'What is globalisation',
      'International trade',
      'Imports',
      'Exports',
      'Trading blocs',
      'EU',
      'Tariffs',
      'Quotas',
      'Benefits of globalisation',
      'New markets',
      'Lower costs',
      'Access to resources',
      'Drawbacks of globalisation',
      'Competition',
      'Cultural differences',
      'Multinationals',
      'Impact of multinationals',
      // 6.4 Legislation
      'Employment law',
      'Minimum wage',
      'Living wage',
      'Working hours',
      'Working Time Regulations',
      'Discrimination',
      'Equality Act',
      'Protected characteristics',
      'Health and safety',
      'Health and Safety at Work Act',
      'Risk assessments',
      'Consumer law',
      'Consumer Rights Act',
      'Environmental law',
      'Environmental regulations',
      'Impact of legislation',
      'Costs of compliance',
      'Benefits of compliance',
      // 6.5 Competitive environment
      'Competition',
      'Competitors',
      'Market structure',
      'Competitive market',
      'Monopoly',
      'Competitive advantage',
      'Responding to competition',
      'Price competition',
      'Non-price competition',
      'Product differentiation',
      'Innovation',
      'Market conditions',
      'Market trends',
      'Business growth',
      'Organic growth',
      'Mergers and takeovers',
      'Risks of growth',
    ],
  },
];

// Helper function to get topic by ID
export function getOCRGCSEBusinessTopicById(id: string): Topic | undefined {
  return ocrGCSEBusinessTopics.find(topic => topic.id === id);
}
