// AQA A-Level Geography (7037) Topics
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/geography/a-level/geography-7037

import { Topic } from '@/types';

export const aqaALevelGeographyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: PHYSICAL GEOGRAPHY (Section A - Core)
  // ============================================================================
  {
    id: 'aqa-alevel-geog-water-carbon',
    name: 'Water and Carbon Cycles',
    description: 'Systems approach to physical geography, water and carbon cycles as closed systems',
    icon: '💧',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Systems concepts
      'Systems in physical geography',
      'Open and closed systems',
      'Inputs, outputs, stores and flows',
      'Dynamic equilibrium',
      'Positive and negative feedback',
      // Water cycle
      'Global water cycle as a closed system',
      'Water cycle stores: oceans, ice, groundwater, atmosphere',
      'Water cycle flows: evaporation, condensation, precipitation',
      'Drainage basin as an open system',
      'Drainage basin inputs: precipitation',
      'Drainage basin outputs: evapotranspiration, river discharge',
      'Drainage basin stores: soil moisture, groundwater, channel storage',
      'Drainage basin transfers: infiltration, percolation, throughflow, overland flow',
      'Storm hydrographs',
      'Lag time and peak discharge',
      'Factors affecting storm hydrographs',
      'River regimes',
      'Water balance and deficits/surpluses',
      'Human impacts on water cycle',
      'Urbanisation effects on drainage',
      'Water extraction and abstraction',
      'Deforestation impacts on water cycle',
      // Carbon cycle
      'Global carbon cycle',
      'Carbon stores: atmosphere, oceans, lithosphere, biosphere',
      'Carbon fluxes and transfers',
      'Photosynthesis and respiration',
      'Decomposition and carbon release',
      'Ocean carbon pump',
      'Geological carbon cycle',
      'Fossil fuel formation',
      'Carbon sequestration',
      'Human impacts on carbon cycle',
      'Fossil fuel combustion',
      'Deforestation and carbon release',
      'Land use change impacts',
      // Connections
      'Links between water and carbon cycles',
      'Climate feedbacks',
      'Amazon rainforest case study',
      'Arctic tundra case study',
    ],
  },
  {
    id: 'aqa-alevel-geog-coastal',
    name: 'Coastal Systems and Landscapes',
    description: 'Coastal processes, landforms and management strategies',
    icon: '🌊',
    color: 'bg-cyan-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Coasts as systems
      'Coastal system: inputs, processes, outputs',
      'Sources of energy: waves, tides, currents',
      'Sediment sources and sinks',
      'Sediment cells and budget',
      'Dynamic equilibrium on coasts',
      // Wave processes
      'Wave formation and characteristics',
      'Wave refraction',
      'Constructive waves',
      'Destructive waves',
      'Wave energy and coastal erosion',
      // Coastal processes
      'Marine erosion: hydraulic action',
      'Marine erosion: abrasion/corrasion',
      'Marine erosion: corrosion/solution',
      'Marine erosion: attrition',
      'Sub-aerial weathering: mechanical',
      'Sub-aerial weathering: chemical',
      'Sub-aerial weathering: biological',
      'Mass movement: rockfall, landslides, slumping',
      'Longshore drift',
      'Coastal transportation',
      'Coastal deposition',
      // Erosional landforms
      'Cliffs and wave-cut platforms',
      'Headlands and bays',
      'Caves, arches, stacks and stumps',
      'Geos and blowholes',
      // Depositional landforms
      'Beaches: sand and shingle',
      'Beach profiles and berms',
      'Spits and bars',
      'Tombolos',
      'Barrier beaches and islands',
      'Sand dunes',
      'Salt marshes',
      // Sea level change
      'Eustatic sea level change',
      'Isostatic sea level change',
      'Emergent coastlines',
      'Submergent coastlines: rias and fjords',
      'Raised beaches',
      // Coastal management
      'Hard engineering: sea walls',
      'Hard engineering: groynes',
      'Hard engineering: rock armour/rip-rap',
      'Hard engineering: offshore breakwaters',
      'Soft engineering: beach nourishment',
      'Soft engineering: dune regeneration',
      'Soft engineering: managed retreat',
      'Shoreline Management Plans (SMPs)',
      'Integrated Coastal Zone Management (ICZM)',
      'Cost-benefit analysis',
      'Holderness coast case study',
    ],
  },
  {
    id: 'aqa-alevel-geog-glacial',
    name: 'Glacial Systems and Landscapes',
    description: 'Glacial processes, landforms and periglacial environments',
    icon: '🏔️',
    color: 'bg-slate-400',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Glaciers as systems
      'Glacial system: inputs, processes, outputs',
      'Glacial budget: accumulation and ablation',
      'Mass balance',
      'Equilibrium line altitude',
      'Glacier advance and retreat',
      // Ice formation and movement
      'Snow to firn to glacial ice',
      'Internal deformation/plastic flow',
      'Basal sliding',
      'Rotational movement',
      'Extensional and compressional flow',
      'Warm-based glaciers',
      'Cold-based glaciers',
      // Glacial erosion
      'Glacial erosion processes: plucking',
      'Glacial erosion processes: abrasion',
      'Glacial erosion processes: freeze-thaw',
      'Rates of glacial erosion',
      // Erosional landforms
      'Corries/cirques',
      'Aretes and pyramidal peaks',
      'Glacial troughs (U-shaped valleys)',
      'Hanging valleys',
      'Truncated spurs',
      'Ribbon lakes',
      'Roches moutonnees',
      'Crag and tail',
      'Striations',
      // Glacial transportation
      'Supraglacial transport',
      'Englacial transport',
      'Subglacial transport',
      // Depositional landforms
      'Till/boulder clay',
      'Moraines: lateral, medial, terminal, ground',
      'Drumlins',
      'Erratics',
      // Fluvioglacial processes
      'Meltwater streams',
      'Fluvioglacial deposition',
      'Eskers',
      'Kames and kame terraces',
      'Outwash plains/sandur',
      'Kettle holes',
      'Varves',
      // Periglacial environments
      'Permafrost: continuous and discontinuous',
      'Active layer',
      'Periglacial processes: frost heave',
      'Ice wedges',
      'Patterned ground',
      'Pingos',
      'Solifluction',
      'Thermokarst',
      // Human activity in glacial areas
      'Glacial landscape tourism',
      'Hydroelectric power',
      'Climate change impacts on glaciers',
    ],
  },
  {
    id: 'aqa-alevel-geog-hazards',
    name: 'Hazards',
    description: 'Tectonic, atmospheric and fire hazards, risk management',
    icon: '🌋',
    color: 'bg-red-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Hazard concepts
      'Definition of hazard',
      'Hazard perception',
      'Hazard risk equation',
      'Vulnerability and resilience',
      'Hazard management cycle',
      'Park model of hazard response',
      // Plate tectonics
      'Earth structure: core, mantle, crust',
      'Plate tectonic theory',
      'Evidence for plate tectonics',
      'Convection currents',
      'Sea floor spreading',
      'Paleomagnetism',
      'Plate boundaries: divergent/constructive',
      'Plate boundaries: convergent/destructive',
      'Plate boundaries: conservative/transform',
      'Hot spots',
      // Volcanic hazards
      'Volcano formation',
      'Volcanic eruption types',
      'Shield volcanoes',
      'Composite/stratovolcanoes',
      'Primary volcanic hazards: lava, pyroclastic flows',
      'Secondary volcanic hazards: lahars, jokulhlaups',
      'Volcanic gases',
      'Volcanic explosivity index (VEI)',
      'Volcanic hazard prediction',
      'Mount Pinatubo case study',
      'Eyjafjallajokull case study',
      // Earthquake hazards
      'Earthquake causes',
      'Focus and epicentre',
      'Seismic waves: P, S, surface',
      'Earthquake magnitude: Richter, moment magnitude',
      'Earthquake intensity: Mercalli scale',
      'Primary earthquake impacts',
      'Secondary impacts: tsunamis, liquefaction, landslides',
      'Earthquake prediction and monitoring',
      'Earthquake-resistant design',
      'Nepal earthquake case study',
      'Japan earthquake/tsunami case study',
      // Storm hazards
      'Tropical storm formation',
      'Hurricane/typhoon/cyclone structure',
      'Saffir-Simpson scale',
      'Storm surge',
      'Tropical storm impacts',
      'Tropical storm prediction and tracking',
      'Climate change and storm intensity',
      'Hurricane Katrina case study',
      'Typhoon Haiyan case study',
      // Wildfire hazards
      'Causes of wildfires',
      'Fire weather conditions',
      'Wildfire behaviour',
      'Impacts of wildfires',
      'Wildfire management',
      'California wildfires case study',
      'Australian bushfires case study',
      // Multi-hazard environments
      'Hazard hotspots',
      'Philippines multi-hazard case study',
    ],
  },
  {
    id: 'aqa-alevel-geog-ecosystems',
    name: 'Ecosystems Under Stress',
    description: 'Ecosystem processes, biodiversity and human impacts',
    icon: '🌿',
    color: 'bg-green-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Ecosystem concepts
      'Ecosystem definition and components',
      'Biotic and abiotic factors',
      'Producers, consumers, decomposers',
      'Food chains and food webs',
      'Trophic levels',
      'Energy flow in ecosystems',
      'Nutrient cycling',
      'Gersmehl nutrient model',
      'Ecosystem productivity',
      'Biomass',
      // Ecosystem types
      'Biomes and their distribution',
      'Climate-vegetation relationship',
      'Tropical rainforests',
      'Savanna grasslands',
      'Hot deserts',
      'Mediterranean ecosystems',
      'Temperate deciduous forests',
      'Taiga/boreal forests',
      'Tundra',
      // Succession
      'Primary succession',
      'Secondary succession',
      'Seral stages',
      'Climax community',
      'Plagioclimax',
      'Lithosere',
      'Hydrosere',
      'Psammosere',
      // Biodiversity
      'Biodiversity definition and measurement',
      'Species diversity',
      'Genetic diversity',
      'Ecosystem diversity',
      'Importance of biodiversity',
      'Ecosystem services',
      'Biodiversity hotspots',
      // Threats to ecosystems
      'Deforestation',
      'Climate change impacts on ecosystems',
      'Habitat fragmentation',
      'Invasive species',
      'Pollution',
      'Overexploitation',
      'Mass extinction',
      // Conservation
      'Protected areas',
      'National parks',
      'Conservation strategies',
      'CITES',
      'Rewilding',
      'Sustainable management',
      'Amazon rainforest management',
      'Coral reef conservation',
    ],
  },
  // ============================================================================
  // PAPER 2: HUMAN GEOGRAPHY (Core)
  // ============================================================================
  {
    id: 'aqa-alevel-geog-global-systems',
    name: 'Global Systems and Global Governance',
    description: 'Globalisation, global governance and the global commons',
    icon: '🌐',
    color: 'bg-indigo-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Globalisation
      'Dimensions of globalisation',
      'Economic globalisation',
      'Political globalisation',
      'Social globalisation',
      'Cultural globalisation',
      'Factors driving globalisation',
      'Transport and communication developments',
      'Containerisation',
      'International trade',
      'TNCs/MNCs role in globalisation',
      'Global production networks',
      'Global financial systems',
      // Consequences of globalisation
      'Winners and losers of globalisation',
      'Inequality and globalisation',
      'Cultural homogenisation',
      'Glocalisation',
      'Environmental impacts of globalisation',
      // Global governance
      'Need for global governance',
      'United Nations',
      'International Monetary Fund (IMF)',
      'World Bank',
      'World Trade Organisation (WTO)',
      'Non-governmental organisations (NGOs)',
      'G7/G8/G20',
      'Effectiveness of global governance',
      // The global commons
      'Definition of global commons',
      'Antarctica',
      'High seas/oceans',
      'Atmosphere',
      'Outer space',
      'Tragedy of the commons',
      // Antarctica case study
      'Antarctic Treaty System',
      'Antarctica governance',
      'Scientific research in Antarctica',
      'Environmental threats to Antarctica',
      'Tourism in Antarctica',
      'Geopolitics of Antarctica',
      'Climate change and Antarctica',
      // Globalisation critique
      'Deglobalisation',
      'Trade wars',
      'Brexit and globalisation',
      'Nationalism vs globalisation',
    ],
  },
  {
    id: 'aqa-alevel-geog-changing-places',
    name: 'Changing Places',
    description: 'Place meanings, representations and changes',
    icon: '🏘️',
    color: 'bg-amber-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Nature and importance of places
      'Place concept',
      'Location vs locale vs sense of place',
      'Insider and outsider perspectives',
      'Categories of place: near and far',
      'Experienced places',
      'Media places',
      // Place meanings
      'Sense of place',
      'Place attachment',
      'Place identity',
      'Factors shaping place identity',
      'Demographics and place',
      'Socio-economic characteristics',
      'Cultural characteristics',
      'Political characteristics',
      'Lived experience of place',
      // Relationships and connections
      'External forces shaping places',
      'Flows of people',
      'Flows of capital',
      'Flows of information',
      'Government policies and place',
      'Past and present connections',
      // Changing places
      'Processes of change',
      'Globalisation and place change',
      'Gentrification',
      'Decline and regeneration',
      'Re-imaging and rebranding',
      'Privatisation of public space',
      // Place representations
      'Quantitative representations',
      'Census data',
      'Qualitative representations',
      'Photography and place',
      'Art and place',
      'Film and place',
      'Literature and place',
      'Music and place',
      // Place studies
      'Local place study',
      'Contrasting place study',
      'Comparison of places',
      'Fieldwork and place',
    ],
  },
  {
    id: 'aqa-alevel-geog-urban',
    name: 'Contemporary Urban Environments',
    description: 'Urbanisation, urban forms and sustainability',
    icon: '🏙️',
    color: 'bg-gray-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2 (Option)',
    subtopics: [
      // Urbanisation
      'Global pattern of urbanisation',
      'Urbanisation rates',
      'Rural-urban migration causes',
      'Push and pull factors',
      'Natural increase in cities',
      'Counter-urbanisation',
      'Suburbanisation',
      'Re-urbanisation',
      // Urban forms
      'Primate cities',
      'Megacities',
      'World cities',
      'Urban morphology',
      'Bid-rent theory',
      'Urban land use models',
      'CBD characteristics',
      'Inner city',
      'Suburbs',
      // Social and economic issues
      'Urban social inequality',
      'Segregation and polarisation',
      'Gated communities',
      'Housing issues',
      'Urban poverty',
      'Informal settlements/slums',
      'Urban crime',
      // Urban climate
      'Urban heat island effect',
      'Air quality and pollution',
      'Urban wind patterns',
      'Urban precipitation',
      // Urban drainage
      'Urban hydrological cycle',
      'Increased surface runoff',
      'Urban flood risk',
      'Sustainable urban drainage systems (SUDS)',
      // Urban waste
      'Municipal waste production',
      'Waste management strategies',
      'Recycling',
      'Incineration',
      'Landfill',
      // Urban sustainability
      'Sustainable urban development',
      'Eco-cities',
      'Urban green spaces',
      'Transport solutions',
      'Smart cities',
      'Urban planning strategies',
      'Case study: sustainable urban area',
    ],
  },
  {
    id: 'aqa-alevel-geog-population',
    name: 'Population and the Environment',
    description: 'Population change, food security and health',
    icon: '👥',
    color: 'bg-orange-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2 (Option)',
    subtopics: [
      // Population concepts
      'Global population growth',
      'Demographic transition model',
      'Population structure',
      'Population pyramids',
      'Dependency ratio',
      'Natural change',
      'Birth rates and death rates',
      'Fertility rates',
      'Infant mortality',
      'Life expectancy',
      // Population and resources
      'Malthusian theory',
      'Boserup theory',
      'Club of Rome/Limits to Growth',
      'Optimum population',
      'Overpopulation',
      'Underpopulation',
      'Carrying capacity',
      // Environment and population
      'Environmental factors affecting population',
      'Climate and population distribution',
      'Resource availability',
      'Population-environment interactions',
      // Food security
      'Global food production patterns',
      'Food security definition',
      'Causes of food insecurity',
      'Climate change and food production',
      'Agricultural systems',
      'Green Revolution',
      'GM crops',
      'Sustainable agriculture',
      'Food miles',
      'Land grabbing',
      // Health and population
      'Global health patterns',
      'Disease distribution',
      'Epidemiological transition',
      'HIV/AIDS global patterns',
      'Malaria distribution',
      'Health inequalities',
      'Access to healthcare',
      'Pharmaceutical industry',
      'Health and development',
    ],
  },
  {
    id: 'aqa-alevel-geog-resource-security',
    name: 'Resource Security',
    description: 'Water, energy and mineral resource security',
    icon: '⚡',
    color: 'bg-yellow-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2 (Option)',
    subtopics: [
      // Resource concepts
      'Natural resources definition',
      'Renewable vs non-renewable',
      'Resource classification',
      'Resource depletion',
      'Resource security definition',
      // Water security
      'Global water distribution',
      'Water availability',
      'Water stress and scarcity',
      'Physical water scarcity',
      'Economic water scarcity',
      'Factors affecting water supply',
      'Water demand patterns',
      'Agricultural water use',
      'Industrial water use',
      'Domestic water use',
      // Water conflicts
      'Transboundary water issues',
      'Water as a geopolitical resource',
      'Water wars potential',
      // Water management
      'Large-scale water projects: dams',
      'Desalination',
      'Water transfer schemes',
      'Water conservation',
      'Rainwater harvesting',
      'Virtual water',
      // Energy security
      'Global energy consumption patterns',
      'Energy mix',
      'Fossil fuels: oil, gas, coal',
      'Peak oil theory',
      'Energy demand factors',
      'Energy supply factors',
      'Geopolitics of energy',
      'OPEC',
      // Renewable energy
      'Solar energy',
      'Wind energy',
      'Hydroelectric power',
      'Tidal and wave energy',
      'Geothermal energy',
      'Biomass and biofuels',
      'Nuclear energy debate',
      // Energy futures
      'Energy transition',
      'Decarbonisation',
      'Carbon capture and storage',
      'Hydrogen economy',
      // Mineral resources
      'Mineral resource distribution',
      'Rare earth elements',
      'Conflict minerals',
      'Recycling and circular economy',
    ],
  },
  // ============================================================================
  // GEOGRAPHICAL SKILLS
  // ============================================================================
  {
    id: 'aqa-alevel-geog-skills',
    name: 'Geographical Skills and Fieldwork',
    description: 'Quantitative and qualitative skills, fieldwork investigation',
    icon: '📊',
    color: 'bg-purple-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'All Papers + NEA',
    subtopics: [
      // Cartographic skills
      'Atlas maps',
      'Thematic maps',
      'OS maps at different scales',
      'Grid references',
      'Cross-sections',
      'Choropleth maps',
      'Isoline maps',
      'Flow line maps',
      'Desire line maps',
      'GIS applications',
      // Graphical skills
      'Line graphs',
      'Bar charts',
      'Histograms',
      'Pie charts',
      'Scatter graphs',
      'Triangular graphs',
      'Radial diagrams',
      'Logarithmic scales',
      'Dispersion diagrams',
      'Box and whisker plots',
      // Statistical skills
      'Measures of central tendency: mean, median, mode',
      'Measures of dispersion: range, IQR, standard deviation',
      'Sampling techniques',
      'Stratified sampling',
      'Random sampling',
      'Systematic sampling',
      'Correlation and regression',
      "Spearman's rank correlation",
      'Chi-squared test',
      'Mann-Whitney U test',
      'Statistical significance',
      // Qualitative skills
      'Coding and categorisation',
      'Interview analysis',
      'Questionnaire design',
      'Content analysis',
      'Discourse analysis',
      // Fieldwork
      'Fieldwork enquiry process',
      'Hypothesis formulation',
      'Data collection methods',
      'Primary data collection',
      'Secondary data sources',
      'Risk assessment',
      'Data presentation',
      'Data analysis',
      'Conclusions and evaluation',
      'Accuracy and reliability',
      'Limitations and improvements',
    ],
  },
];

export function getAQAALevelGeographyTopicById(id: string): Topic | undefined {
  return aqaALevelGeographyTopics.find((topic) => topic.id === id);
}
