// AQA A-Level Psychology Topics (7182)
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/psychology/a-level/psychology-7182

import { Topic } from '@/types';

export const aqaALevelPsychologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: INTRODUCTORY TOPICS IN PSYCHOLOGY (33.3%)
  // ============================================================================
  {
    id: 'aqa-alevel-psych-social-influence',
    name: 'Social Influence',
    description: 'Conformity, obedience, resistance to social influence, and minority influence',
    icon: '👥',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Conformity
      'Types of conformity: internalisation',
      'Types of conformity: identification',
      'Types of conformity: compliance',
      'Explanations for conformity: informational social influence',
      'Explanations for conformity: normative social influence',
      'Variables affecting conformity: group size',
      'Variables affecting conformity: unanimity',
      'Variables affecting conformity: task difficulty',
      "Asch's research on conformity",
      "Asch's variations and findings",
      'Evaluation of conformity research',
      // Conformity to social roles
      'Conformity to social roles',
      "Zimbardo's Stanford Prison Experiment",
      'Evaluation of Zimbardo study',
      'Ethical issues in conformity research',
      // Obedience
      "Milgram's research on obedience",
      "Milgram's baseline study procedure",
      "Milgram's findings and conclusions",
      'Situational variables affecting obedience: proximity',
      'Situational variables affecting obedience: location',
      'Situational variables affecting obedience: uniform',
      'Explanations for obedience: agentic state',
      'Explanations for obedience: legitimacy of authority',
      'Dispositional explanation: authoritarian personality',
      "Adorno's F-scale research",
      'Evaluation of obedience explanations',
      // Resistance to social influence
      'Resistance to social influence: social support',
      'How social support enables resistance to conformity',
      'How social support enables resistance to obedience',
      'Resistance to social influence: locus of control',
      'Internal vs external locus of control',
      "Rotter's locus of control concept",
      // Minority influence
      'Minority influence: consistency',
      'Minority influence: commitment',
      'Minority influence: flexibility',
      "Moscovici's research on minority influence",
      'The snowball effect in social change',
      'Role of social influence in social change',
      'Evaluation of minority influence research',
    ],
  },
  {
    id: 'aqa-alevel-psych-memory',
    name: 'Memory',
    description: 'Models of memory, types of long-term memory, forgetting, and eyewitness testimony',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Multi-store model
      'The multi-store model of memory',
      'Sensory register: coding, capacity, duration',
      'Short-term memory: coding, capacity, duration',
      'Long-term memory: coding, capacity, duration',
      'Atkinson and Shiffrin multi-store model',
      'Evaluation of the multi-store model',
      'Research evidence for the multi-store model',
      // Types of LTM
      'Types of long-term memory: episodic',
      'Types of long-term memory: semantic',
      'Types of long-term memory: procedural',
      "Tulving's research on LTM types",
      'Clinical evidence for LTM types',
      // Working memory model
      'The working memory model',
      'Central executive function and capacity',
      'Phonological loop: articulatory control system',
      'Phonological loop: phonological store',
      'Visuo-spatial sketchpad function',
      'Episodic buffer function',
      'Baddeley and Hitch working memory model',
      'Evaluation of the working memory model',
      'Research evidence for working memory',
      // Forgetting
      'Explanations for forgetting: interference',
      'Proactive interference',
      'Retroactive interference',
      'Research on interference (Underwood, McGeoch)',
      'Explanations for forgetting: retrieval failure',
      'Encoding specificity principle',
      'Context-dependent forgetting',
      'State-dependent forgetting',
      'Cue-dependent forgetting',
      'Evaluation of forgetting explanations',
      // Eyewitness testimony
      'Factors affecting eyewitness testimony accuracy',
      'Misleading information: leading questions',
      'Misleading information: post-event discussion',
      "Loftus and Palmer's car crash study",
      'Effect of anxiety on eyewitness testimony',
      "Weapon focus effect (Loftus's research)",
      "Deffenbacher's meta-analysis on anxiety",
      "Yuille and Cutshall's real-life shooting study",
      'The cognitive interview technique',
      'Components of cognitive interview',
      'Effectiveness of cognitive interview',
      'Evaluation of eyewitness testimony research',
    ],
  },
  {
    id: 'aqa-alevel-psych-attachment',
    name: 'Attachment',
    description: 'Formation of attachments, types of attachment, and effects of early attachment',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Caregiver-infant interactions
      'Caregiver-infant interactions: reciprocity',
      'Caregiver-infant interactions: interactional synchrony',
      'Research on caregiver-infant interactions',
      'Stages of attachment development',
      "Schaffer's stages of attachment",
      'Multiple attachments and secondary attachments',
      // Animal studies
      "Lorenz's research on imprinting in geese",
      'Critical period for imprinting',
      'Sexual imprinting',
      "Harlow's research with monkeys",
      'Contact comfort vs food',
      'Critical period for attachment in monkeys',
      'Evaluation of animal studies of attachment',
      // Explanations of attachment
      'Learning theory of attachment',
      'Classical conditioning explanation',
      'Operant conditioning explanation',
      'Evaluation of learning theory',
      "Bowlby's monotropic theory",
      'Social releasers and critical period',
      'Internal working model',
      'Continuity hypothesis',
      'Evaluation of monotropic theory',
      // Ainsworth's Strange Situation
      "Ainsworth's Strange Situation procedure",
      'Secure attachment (Type B)',
      'Insecure-avoidant attachment (Type A)',
      'Insecure-resistant attachment (Type C)',
      'Evaluation of Strange Situation',
      // Cultural variations
      'Cultural variations in attachment',
      "Van Ijzendoorn's meta-analysis",
      'Cross-cultural attachment patterns',
      'Evaluation of cross-cultural attachment research',
      // Bowlby's maternal deprivation
      "Bowlby's maternal deprivation hypothesis",
      'Critical period for attachment',
      'Effects of maternal deprivation',
      "Bowlby's 44 thieves study",
      'Evaluation of maternal deprivation hypothesis',
      // Romanian orphan studies
      'Romanian orphan studies: effects of institutionalisation',
      "Rutter's English and Romanian Adoptees study",
      'Effects of early institutional care',
      'Recovery from early deprivation',
      'Evaluation of Romanian orphan research',
      // Influence on later relationships
      'Influence of early attachment on childhood relationships',
      'Internal working model and peer relationships',
      'Influence of early attachment on adult relationships',
      'Hazan and Shaver love quiz research',
      'Continuity hypothesis evaluation',
    ],
  },
  {
    id: 'aqa-alevel-psych-psychopathology',
    name: 'Psychopathology',
    description: 'Definitions of abnormality, characteristics and treatments of mental disorders',
    icon: '🩺',
    color: 'bg-red-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Definitions of abnormality
      'Definitions of abnormality: statistical infrequency',
      'Evaluation of statistical infrequency definition',
      'Definitions of abnormality: deviation from social norms',
      'Cultural relativism in defining abnormality',
      'Evaluation of deviation from social norms',
      'Definitions of abnormality: failure to function adequately',
      "Rosenhan and Seligman's criteria",
      'Evaluation of failure to function adequately',
      'Definitions of abnormality: deviation from ideal mental health',
      "Jahoda's criteria for mental health",
      'Evaluation of ideal mental health definition',
      // Phobias
      'Phobias: behavioural characteristics',
      'Phobias: emotional characteristics',
      'Phobias: cognitive characteristics',
      'Two-process model of phobias',
      'Classical conditioning and phobia acquisition',
      'Operant conditioning and phobia maintenance',
      "Watson and Rayner's Little Albert study",
      'Evaluation of behavioural approach to phobias',
      'Systematic desensitisation',
      'Reciprocal inhibition principle',
      'Anxiety hierarchy construction',
      'Effectiveness of systematic desensitisation',
      'Flooding (implosion therapy)',
      'How flooding works',
      'Effectiveness and ethics of flooding',
      // Depression
      'Depression: behavioural characteristics',
      'Depression: emotional characteristics',
      'Depression: cognitive characteristics',
      "Beck's negative cognitive triad",
      'Negative schemas in depression',
      'Cognitive biases in depression',
      "Ellis's ABC model",
      'Irrational beliefs and musturbatory thinking',
      'Evaluation of cognitive explanations of depression',
      'Cognitive behaviour therapy (CBT) for depression',
      'Challenging irrational thoughts',
      'Behavioural activation',
      'Effectiveness of CBT for depression',
      'Evaluation of CBT',
      // OCD
      'OCD: behavioural characteristics',
      'OCD: emotional characteristics',
      'OCD: cognitive characteristics',
      'Biological explanation: genetic factors in OCD',
      'COMT gene and serotonin',
      'Family and twin studies of OCD',
      'Biological explanation: neural factors in OCD',
      'Role of serotonin in OCD',
      'Abnormal brain circuits in OCD',
      'Evaluation of biological explanations of OCD',
      'Drug therapy for OCD: SSRIs',
      'How SSRIs work',
      'Effectiveness of SSRIs for OCD',
      'Evaluation of drug therapy for OCD',
    ],
  },

  // ============================================================================
  // PAPER 2: PSYCHOLOGY IN CONTEXT (33.3%)
  // ============================================================================
  {
    id: 'aqa-alevel-psych-approaches',
    name: 'Approaches in Psychology',
    description: 'Origins of psychology and the major psychological approaches',
    icon: '📚',
    color: 'bg-indigo-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Origins
      'Origins of psychology: Wundt and introspection',
      'Emergence of psychology as a science',
      'The scientific method in psychology',
      // Behaviourist approach
      'The behaviourist approach',
      'Assumptions of behaviourism',
      'Classical conditioning: Pavlov',
      'Unconditioned and conditioned stimuli/responses',
      'Operant conditioning: Skinner',
      'Positive and negative reinforcement',
      'Punishment in operant conditioning',
      'Evaluation of the behaviourist approach',
      // Social learning theory
      'Social learning theory',
      'Role of mediational processes',
      'Attention, retention, reproduction, motivation',
      'Vicarious reinforcement',
      'Identification and modelling',
      "Bandura's Bobo doll research",
      'Evaluation of social learning theory',
      // Cognitive approach
      'The cognitive approach',
      'Internal mental processes',
      'The role of schemas',
      'Use of theoretical and computer models',
      'Emergence of cognitive neuroscience',
      'Evaluation of the cognitive approach',
      // Biological approach
      'The biological approach',
      'Influence of genes on behaviour',
      'Genotype and phenotype',
      'Evolution and behaviour',
      'Biological structures and neurochemistry',
      'Evaluation of the biological approach',
      // Psychodynamic approach
      'The psychodynamic approach',
      'Role of the unconscious',
      'Structure of personality: id, ego, superego',
      'Defence mechanisms: repression',
      'Defence mechanisms: denial',
      'Defence mechanisms: displacement',
      'Psychosexual stages of development',
      'Evaluation of the psychodynamic approach',
      // Humanistic psychology
      'Humanistic psychology',
      'Free will and self-actualisation',
      "Maslow's hierarchy of needs",
      'Focus on the self: congruence',
      'Conditions of worth',
      "Rogers's person-centred therapy",
      'Evaluation of humanistic psychology',
      // Comparison of approaches
      'Comparison of approaches',
      'Similarities and differences between approaches',
      'Eclecticism in psychological practice',
    ],
  },
  {
    id: 'aqa-alevel-psych-biopsychology',
    name: 'Biopsychology',
    description: 'The nervous system, brain localisation, neuropsychology, and biological rhythms',
    icon: '🔬',
    color: 'bg-green-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Nervous system
      'Structure and function of the nervous system',
      'Central nervous system (CNS)',
      'Peripheral nervous system (PNS)',
      'Somatic nervous system',
      'Autonomic nervous system',
      'Sympathetic and parasympathetic divisions',
      // Neurons
      'Structure of the neuron',
      'Types of neurons: sensory',
      'Types of neurons: relay',
      'Types of neurons: motor',
      'Function of sensory, relay and motor neurons',
      // Synaptic transmission
      'Process of synaptic transmission',
      'Neurotransmitters',
      'Excitation and inhibition',
      'Summation',
      // Endocrine system
      'The endocrine system',
      'Glands and hormones',
      'Pituitary gland function',
      'Adrenal glands and adrenaline',
      // Fight or flight
      'The fight or flight response',
      'Role of the amygdala',
      'Role of the hypothalamus',
      'Role of adrenaline in fight or flight',
      'Acute and chronic stress responses',
      // Localisation of function
      'Localisation of function in the brain',
      'Motor area function',
      'Somatosensory area function',
      'Visual area function',
      'Auditory area function',
      "Language areas: Broca's area",
      "Language areas: Wernicke's area",
      'Evidence for localisation',
      'Evaluation of localisation theory',
      // Lateralisation
      'Lateralisation and split-brain research',
      "Sperry's split-brain studies",
      'Hemispheric specialisation',
      'Language lateralisation',
      'Evaluation of split-brain research',
      // Plasticity and recovery
      'Brain plasticity',
      'Functional recovery after brain trauma',
      'Neural reorganisation',
      'Factors affecting recovery',
      'Evaluation of plasticity research',
      // Ways of studying the brain
      'Ways of studying the brain: fMRI',
      'How fMRI works',
      'Strengths and limitations of fMRI',
      'Ways of studying the brain: EEG',
      'How EEG works',
      'Event-related potentials (ERPs)',
      'Strengths and limitations of EEG',
      'Ways of studying the brain: post-mortem examination',
      'Strengths and limitations of post-mortems',
      // Biological rhythms
      'Circadian rhythms',
      'Sleep-wake cycle',
      'Role of endogenous pacemakers',
      'Suprachiasmatic nucleus (SCN)',
      'Role of exogenous zeitgebers',
      'Light as a zeitgeber',
      'Research on circadian rhythms',
      'Infradian rhythms',
      'Menstrual cycle as infradian rhythm',
      'Ultradian rhythms',
      'Stages of sleep as ultradian rhythm',
      'Research on biological rhythms',
      'Evaluation of biological rhythms research',
    ],
  },
  {
    id: 'aqa-alevel-psych-research-methods',
    name: 'Research Methods',
    description: 'Scientific methodology, experimental design, data analysis, and inferential testing',
    icon: '📊',
    color: 'bg-yellow-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Experimental method
      'The experimental method',
      'Laboratory experiments',
      'Field experiments',
      'Natural experiments',
      'Quasi-experiments',
      'Strengths and limitations of each type',
      // Observational techniques
      'Observational techniques',
      'Naturalistic vs controlled observation',
      'Covert vs overt observation',
      'Participant vs non-participant observation',
      'Evaluation of observational methods',
      // Self-report techniques
      'Self-report techniques: questionnaires',
      'Open and closed questions',
      'Structured interviews',
      'Unstructured interviews',
      'Semi-structured interviews',
      'Evaluation of self-report methods',
      // Correlations
      'Correlations',
      'Positive, negative and zero correlations',
      'Correlation coefficients',
      'Difference between correlation and causation',
      // Other methods
      'Content analysis',
      'Case studies',
      // Scientific processes
      'Aims and hypotheses',
      'Directional (one-tailed) hypotheses',
      'Non-directional (two-tailed) hypotheses',
      'Null hypothesis',
      // Sampling
      'Sampling methods: random sampling',
      'Sampling methods: systematic sampling',
      'Sampling methods: stratified sampling',
      'Sampling methods: opportunity sampling',
      'Sampling methods: volunteer sampling',
      'Evaluation of sampling methods',
      // Experimental design
      'Experimental designs: repeated measures',
      'Experimental designs: independent groups',
      'Experimental designs: matched pairs',
      'Order effects and counterbalancing',
      'Participant variables',
      // Variables
      'Variables: independent, dependent, extraneous',
      'Operationalisation of variables',
      'Confounding variables',
      'Demand characteristics',
      'Investigator effects',
      // Control
      'Control: randomisation',
      'Control: standardisation',
      'Control: counterbalancing',
      'Use of control groups',
      // Pilot studies
      'Pilot studies and their purpose',
      // Ethical issues
      'Ethical issues in research',
      'BPS Code of Ethics',
      'Informed consent',
      'Deception',
      'Right to withdraw',
      'Protection from harm',
      'Confidentiality',
      'Privacy',
      'Dealing with ethical issues',
      // Peer review
      'The role of peer review',
      'Evaluation of peer review process',
      // Economics
      'Implications of psychological research for the economy',
      // Reliability
      'Reliability: test-retest reliability',
      'Reliability: inter-observer reliability',
      'Ways to assess reliability',
      'Ways to improve reliability',
      // Validity
      'Types of validity: face validity',
      'Types of validity: concurrent validity',
      'Types of validity: ecological validity',
      'Types of validity: temporal validity',
      'Internal and external validity',
      'Ways to assess and improve validity',
      // Features of science
      'Features of science: objectivity',
      'Features of science: empirical methods',
      'Features of science: replicability',
      'Features of science: falsifiability',
      'Theory construction and hypothesis testing',
      'Paradigms and paradigm shifts',
      // Report writing
      'Sections of a scientific report',
      'Abstract',
      'Introduction',
      'Method',
      'Results',
      'Discussion',
      'Referencing',
      // Data handling
      'Quantitative and qualitative data',
      'Primary and secondary data',
      'Meta-analysis',
      // Descriptive statistics
      'Measures of central tendency: mean',
      'Measures of central tendency: median',
      'Measures of central tendency: mode',
      'Measures of dispersion: range',
      'Measures of dispersion: standard deviation',
      'Calculation and interpretation of statistics',
      // Data presentation
      'Presentation of quantitative data: tables',
      'Presentation of quantitative data: graphs',
      'Bar charts',
      'Histograms',
      'Scattergrams',
      'Line graphs',
      // Distributions
      'Normal distribution',
      'Characteristics of normal distribution',
      'Skewed distributions: positive skew',
      'Skewed distributions: negative skew',
      // Levels of measurement
      'Levels of measurement: nominal',
      'Levels of measurement: ordinal',
      'Levels of measurement: interval',
      'Levels of measurement: ratio',
      // Inferential statistics
      'Introduction to inferential statistics',
      'Probability and significance',
      'Using statistical tables and critical values',
      'Type I and Type II errors',
      // Statistical tests
      'Sign test: when to use',
      'Sign test: calculation',
      'Factors affecting choice of statistical test',
      "Chi-squared test: when to use and how to interpret",
      "Spearman's rho: when to use",
      "Pearson's r: when to use",
      'Wilcoxon signed-ranks test: when to use',
      'Mann-Whitney U test: when to use',
      'Related t-test: when to use',
      'Unrelated t-test: when to use',
    ],
  },

  // ============================================================================
  // PAPER 3: ISSUES AND OPTIONS IN PSYCHOLOGY (33.3%)
  // ============================================================================
  {
    id: 'aqa-alevel-psych-issues-debates',
    name: 'Issues and Debates',
    description: 'Key debates and issues in psychology including nature-nurture, free will, and ethics',
    icon: '⚖️',
    color: 'bg-orange-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Gender bias
      'Gender bias in psychological research',
      'Androcentrism',
      'Alpha bias',
      'Beta bias',
      'Examples of gender bias in psychology',
      'Implications of gender bias',
      // Cultural bias
      'Cultural bias in psychological research',
      'Ethnocentrism',
      'Cultural relativism',
      'Imposed etic',
      'Examples of cultural bias in psychology',
      'Implications of cultural bias',
      // Free will and determinism
      'Free will and determinism debate',
      'Hard determinism',
      'Soft determinism',
      'Biological determinism',
      'Environmental determinism',
      'Psychic determinism',
      'Scientific emphasis on causal explanations',
      'Implications for psychology',
      // Nature-nurture debate
      'The nature-nurture debate',
      'Relative importance of heredity',
      'Relative importance of environment',
      'The interactionist approach',
      'Diathesis-stress model',
      'Epigenetics',
      'Examples of nature-nurture in psychology',
      // Holism and reductionism
      'Holism and reductionism',
      'Levels of explanation in psychology',
      'Biological reductionism',
      'Environmental reductionism',
      'Benefits of reductionist approach',
      'Benefits of holistic approach',
      // Idiographic and nomothetic approaches
      'Idiographic approach',
      'Nomothetic approach',
      'Comparison of approaches',
      'Examples in psychology',
      'Complementary nature of approaches',
      // Ethical implications
      'Ethical implications of research',
      'Socially sensitive research',
      'Implications of research for participants',
      'Wider implications of research findings',
      'Examples of socially sensitive research',
      'Guidelines for conducting sensitive research',
    ],
  },

  // OPTION 1 TOPICS
  {
    id: 'aqa-alevel-psych-relationships',
    name: 'Relationships',
    description: 'Attraction, theories of romantic relationships, and virtual relationships',
    icon: '💑',
    color: 'bg-rose-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 1',
    subtopics: [
      // Evolutionary explanations
      'Evolutionary explanations for partner preferences',
      'Sexual selection and human behaviour',
      'Inter-sexual selection',
      'Intra-sexual selection',
      'Parental investment theory',
      'Evaluation of evolutionary explanations',
      // Factors affecting attraction
      'Self-disclosure in relationships',
      "Reis and Shaver's model",
      'Physical attractiveness',
      'Halo effect',
      'Matching hypothesis',
      "Walster's computer dance study",
      'Filter theory of attraction',
      "Kerckhoff and Davis's research",
      'Social demography filter',
      'Similarity of attitudes filter',
      'Complementarity of needs filter',
      'Evaluation of attraction factors',
      // Theories of romantic relationships
      'Social exchange theory',
      'Comparison level (CL)',
      'Comparison level for alternatives (CLalt)',
      'Evaluation of social exchange theory',
      'Equity theory',
      'Perceived fairness in relationships',
      "Walster's equity principles",
      'Evaluation of equity theory',
      "Rusbult's investment model",
      'Satisfaction',
      'Comparison with alternatives',
      'Investment size',
      'Commitment',
      'Evaluation of investment model',
      // Relationship breakdown
      "Duck's phase model of relationship breakdown",
      'Intrapsychic phase',
      'Dyadic phase',
      'Social phase',
      'Grave-dressing phase',
      'Resurrection phase',
      'Evaluation of phase model',
      'Reasons for relationship breakdown',
      // Virtual relationships
      'Virtual relationships in social media',
      'Self-disclosure in virtual relationships',
      'Reduced cues theory',
      'Hyperpersonal model',
      'Absence of gating in virtual relationships',
      'Evaluation of virtual relationships research',
      // Parasocial relationships
      'Parasocial relationships',
      'Levels of parasocial relationships',
      'Entertainment-social level',
      'Intense-personal level',
      'Borderline-pathological level',
      'Absorption-addiction model',
      'Attachment theory explanation',
      'Evaluation of parasocial relationships research',
    ],
  },
  {
    id: 'aqa-alevel-psych-gender',
    name: 'Gender',
    description: 'Sex and gender, gender identity, and explanations for gender development',
    icon: '⚧️',
    color: 'bg-violet-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 1',
    subtopics: [
      // Sex and gender
      'Sex and gender distinction',
      'Sex-role stereotypes',
      'Androgyny',
      'Bem Sex Role Inventory (BSRI)',
      'Evaluation of BSRI',
      // Chromosomes and hormones
      'Role of chromosomes in sex determination',
      'XX and XY chromosomes',
      'Role of hormones in gender',
      'Testosterone effects on behaviour',
      'Oestrogen effects on behaviour',
      'Oxytocin and gender behaviour',
      'Atypical sex chromosome patterns',
      "Klinefelter's syndrome (XXY)",
      "Turner's syndrome (XO)",
      'Evaluation of biological explanations',
      // Gender identity
      'Gender identity development',
      'Gender dysphoria',
      'Biological explanations of gender dysphoria',
      'Brain-sex theory',
      'Genetic factors in gender dysphoria',
      'Social/psychological explanations',
      'Evaluation of explanations',
      // Cognitive explanations
      "Kohlberg's theory of gender development",
      'Gender identity stage',
      'Gender stability stage',
      'Gender constancy stage',
      'Evaluation of Kohlberg',
      'Gender schema theory',
      "Martin and Halverson's theory",
      'In-group and out-group schemas',
      'Evaluation of gender schema theory',
      // Psychodynamic explanation
      'Psychodynamic explanation of gender',
      'Oedipus complex',
      'Electra complex',
      'Identification with same-sex parent',
      'Evaluation of psychodynamic explanation',
      // Social learning theory
      'Social learning theory of gender',
      'Role of reinforcement',
      'Role of modelling',
      'Mediational processes',
      'Evaluation of SLT explanation',
      // Cultural and media influences
      'Cultural influences on gender',
      'Cross-cultural research',
      "Mead's research",
      'Media influences on gender',
      'Evaluation of cultural/media influences',
      // Atypical gender development
      'Gender identity disorder in children',
      'Biological intersex conditions',
      'Androgen insensitivity syndrome (AIS)',
      'Congenital adrenal hyperplasia (CAH)',
    ],
  },
  {
    id: 'aqa-alevel-psych-cognition-development',
    name: 'Cognition and Development',
    description: "Piaget's and Vygotsky's theories, development of social cognition, and theory of mind",
    icon: '🎓',
    color: 'bg-cyan-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 1',
    subtopics: [
      // Piaget's theory
      "Piaget's theory of cognitive development",
      'Schemas',
      'Assimilation',
      'Accommodation',
      'Equilibration',
      'Stages of cognitive development',
      'Sensorimotor stage (0-2 years)',
      'Object permanence',
      'Pre-operational stage (2-7 years)',
      'Egocentrism',
      'Three mountains task',
      'Class inclusion',
      'Conservation',
      'Concrete operational stage (7-11 years)',
      'Decentration',
      'Formal operational stage (11+ years)',
      'Abstract and logical thinking',
      'Evaluation of Piaget',
      // Vygotsky's theory
      "Vygotsky's theory of cognitive development",
      'Zone of proximal development (ZPD)',
      'Scaffolding',
      'Role of others in development',
      'Evaluation of Vygotsky',
      // Baillargeon's research
      "Baillargeon's research on infant abilities",
      'Violation of expectation research',
      'Drawbridge study',
      'Physical reasoning in infants',
      'Nativist interpretation',
      'Evaluation of Baillargeon',
      // Development of social cognition
      'Development of social cognition',
      "Selman's levels of perspective-taking",
      'Undifferentiated perspective-taking',
      'Social-informational perspective-taking',
      'Self-reflective perspective-taking',
      'Mutual perspective-taking',
      'Societal perspective-taking',
      'Evaluation of Selman',
      // Theory of mind
      'Theory of mind (ToM)',
      'First-order ToM',
      'Second-order ToM',
      'False belief tasks',
      'Sally-Anne task',
      'Smarties task',
      'Development of ToM',
      'ToM and autism',
      // Mirror neuron system
      'The mirror neuron system',
      'Role in social cognition',
      'Mirror neurons and empathy',
      'Mirror neurons and ToM',
      'Research evidence',
      'Evaluation of mirror neuron system',
    ],
  },

  // OPTION 2 TOPICS
  {
    id: 'aqa-alevel-psych-schizophrenia',
    name: 'Schizophrenia',
    description: 'Classification, biological and psychological explanations, and treatments',
    icon: '🔮',
    color: 'bg-slate-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 2',
    subtopics: [
      // Classification and diagnosis
      'Classification of schizophrenia',
      'Positive symptoms',
      'Hallucinations',
      'Delusions',
      'Negative symptoms',
      'Speech poverty (alogia)',
      'Avolition',
      'Affective flattening',
      'Reliability of diagnosis',
      'Validity of diagnosis',
      'Co-morbidity issues',
      'Culture and gender bias in diagnosis',
      'Symptom overlap with other disorders',
      // Biological explanations
      'Genetic explanations of schizophrenia',
      'Family studies',
      'Twin studies',
      'Adoption studies',
      'Candidate genes',
      'Polygenic nature',
      'Neural correlates of schizophrenia',
      'Dopamine hypothesis',
      'Hyperdopaminergia',
      'Brain structure abnormalities',
      'Enlarged ventricles',
      'Reduced prefrontal cortex',
      'Evaluation of biological explanations',
      // Psychological explanations
      'Family dysfunction explanations',
      'Double-bind theory (Bateson)',
      'Expressed emotion',
      'Schizophrenogenic mother',
      'Cognitive explanations',
      'Dysfunctional thought processing',
      'Metarepresentation dysfunction',
      'Central control dysfunction',
      'Evaluation of psychological explanations',
      // Drug therapy
      'Typical antipsychotics',
      'Chlorpromazine',
      'Dopamine antagonists',
      'Atypical antipsychotics',
      'Clozapine',
      'Effects on dopamine and serotonin',
      'Effectiveness of drug therapy',
      'Side effects of antipsychotics',
      'Evaluation of drug therapy',
      // Psychological therapies
      'Cognitive behavioural therapy (CBT) for schizophrenia',
      'Challenging delusional beliefs',
      'Reality testing',
      'Family therapy',
      'Reducing expressed emotion',
      'Psychoeducation',
      'Token economies',
      'Effectiveness of psychological therapies',
      'Evaluation of psychological therapies',
      // Interactionist approach
      'The interactionist approach',
      'Diathesis-stress model',
      'Original and modern versions',
      'Combining biological and psychological treatments',
      'Evaluation of interactionist approach',
    ],
  },
  {
    id: 'aqa-alevel-psych-eating-behaviour',
    name: 'Eating Behaviour',
    description: 'Explanations for food preferences, anorexia nervosa, and obesity',
    icon: '🍽️',
    color: 'bg-amber-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 2',
    subtopics: [
      // Food preferences
      'Explanations for food preferences',
      'Evolutionary explanations',
      'Taste aversion',
      'Neophobia',
      'Preference for sweet/fatty foods',
      'Role of learning in food preference',
      'Classical conditioning',
      'Social learning',
      'Cultural influences on food preference',
      'Evaluation of explanations',
      // Neural mechanisms
      'The role of the hypothalamus',
      'Lateral hypothalamus (LH)',
      'Ventromedial hypothalamus (VMH)',
      'Role of ghrelin',
      'Role of leptin',
      'Evaluation of neural explanations',
      // Anorexia nervosa
      'Anorexia nervosa: characteristics',
      'Biological explanations of anorexia',
      'Genetic factors',
      'Twin studies',
      'Neural explanations',
      'Serotonin dysfunction',
      'Dopamine dysfunction',
      'Evaluation of biological explanations',
      'Family systems theory',
      'Enmeshment',
      'Autonomy and control',
      'Social learning theory explanation',
      'Role of media',
      'Role of peers',
      'Cognitive explanations',
      'Distorted body image',
      'Irrational beliefs about weight',
      'Evaluation of psychological explanations',
      // Obesity
      'Obesity: characteristics and prevalence',
      'Biological explanations of obesity',
      'Genetic factors',
      'Thrifty gene hypothesis',
      'Neural factors',
      'Psychological explanations of obesity',
      'Restraint theory',
      'Boundary model',
      'Disinhibition',
      'Role of denial',
      'Evaluation of obesity explanations',
      // Success and failure of dieting
      'Success and failure of dieting',
      'Cognitive factors in dieting',
      'Boundary model applied to dieting',
      'What-the-hell effect',
      'Role of denial in failed dieting',
      'Ironic processes theory',
      'Evaluation of dieting research',
    ],
  },
  {
    id: 'aqa-alevel-psych-stress',
    name: 'Stress',
    description: 'Physiology of stress, sources of stress, individual differences, and stress management',
    icon: '😰',
    color: 'bg-red-400',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 2',
    subtopics: [
      // Physiology of stress
      'The physiology of stress',
      'General adaptation syndrome (GAS)',
      'Alarm stage',
      'Resistance stage',
      'Exhaustion stage',
      'Evaluation of GAS',
      'Hypothalamic-pituitary-adrenal (HPA) system',
      'Role of cortisol',
      'Sympathomedullary pathway (SAM)',
      'Role of adrenaline',
      'Chronic vs acute stress',
      // Effects of stress
      'Effects of stress on the immune system',
      'Immunosuppression',
      "Kiecolt-Glaser's research",
      'Effects on wound healing',
      'Stress and cardiovascular disorders',
      'Type A behaviour and heart disease',
      "Friedman and Rosenman's research",
      'Evaluation of research on stress effects',
      // Sources of stress
      'Sources of stress: life changes',
      'Social Readjustment Rating Scale (SRRS)',
      "Holmes and Rahe's research",
      'Evaluation of life changes research',
      'Sources of stress: daily hassles',
      'Hassles and Uplifts Scale',
      "Kanner's research",
      'Evaluation of daily hassles research',
      'Sources of stress: workplace stress',
      'Workload',
      'Lack of control',
      "Marmot's Whitehall studies",
      "Johansson's sawmill study",
      'Evaluation of workplace stress research',
      // Measuring stress
      'Measuring stress: physiological measures',
      'Skin conductance response',
      'Heart rate and blood pressure',
      'Self-report measures',
      'Evaluation of stress measures',
      // Individual differences
      'Individual differences in stress',
      'Personality types: Type A, B, C',
      'Hardy personality',
      'Hardiness: commitment, challenge, control',
      "Kobasa's research",
      'Evaluation of individual differences',
      // Stress management
      'Drug therapy for stress',
      'Benzodiazepines (BZs)',
      'Beta-blockers',
      'How drug treatments work',
      'Evaluation of drug therapy',
      'Stress inoculation training (SIT)',
      'Conceptualisation phase',
      'Skills acquisition phase',
      'Application phase',
      'Evaluation of SIT',
      'Biofeedback',
      'How biofeedback works',
      'Evaluation of biofeedback',
      'Social support as stress management',
      'Instrumental support',
      'Emotional support',
      'Esteem support',
      'Evaluation of social support',
      // Gender differences
      'Gender differences in coping with stress',
      'Tend-and-befriend response',
      'Role of oxytocin',
      'Evaluation of gender differences research',
    ],
  },

  // OPTION 3 TOPICS
  {
    id: 'aqa-alevel-psych-aggression',
    name: 'Aggression',
    description: 'Neural and hormonal mechanisms, evolutionary explanations, and social psychological theories',
    icon: '😠',
    color: 'bg-red-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 3',
    subtopics: [
      // Neural and hormonal mechanisms
      'Neural mechanisms in aggression',
      'Role of the limbic system',
      'Role of the amygdala',
      'Prefrontal cortex dysfunction',
      'Role of serotonin in aggression',
      'Low serotonin hypothesis',
      'Hormonal mechanisms: testosterone',
      'Testosterone and aggression research',
      'Challenge hypothesis',
      'MAOA gene and aggression',
      "Brunner's research",
      'Warrior gene',
      'Gene-environment interaction',
      'Evaluation of biological mechanisms',
      // Genetic factors
      'Genetic factors in aggression',
      'Twin studies',
      'Adoption studies',
      'Evaluation of genetic explanations',
      // Ethological explanation
      'Ethological explanation of aggression',
      'Innate releasing mechanisms',
      'Fixed action patterns',
      "Lorenz's hydraulic model",
      'Ritualistic aggression',
      'Evaluation of ethological explanation',
      // Evolutionary explanations
      'Evolutionary explanations of human aggression',
      'Aggression as adaptive',
      'Male-male competition',
      'Sexual jealousy',
      'Mate retention strategies',
      'Aggression and status',
      'Evaluation of evolutionary explanations',
      // Social psychological explanations
      'Frustration-aggression hypothesis',
      'Dollard et al. original theory',
      'Berkowitz reformulation',
      'Aggressive cues',
      'Weapons effect',
      'Evaluation of frustration-aggression hypothesis',
      'Social learning theory of aggression',
      "Bandura's research",
      'Observational learning',
      'Vicarious reinforcement',
      'Self-efficacy',
      'Evaluation of SLT of aggression',
      'De-individuation',
      'Anonymity and reduced self-awareness',
      "Zimbardo's research",
      "Diener's research",
      'Evaluation of de-individuation',
      // Institutional aggression
      'Institutional aggression in prisons',
      'Dispositional explanation: importation model',
      'Pre-institutional factors',
      'Evaluation of importation model',
      'Situational explanation: deprivation model',
      'Deprivation of liberty, autonomy, security',
      "Sykes' five deprivations",
      'Evaluation of deprivation model',
      // Media influences
      'Media influences on aggression',
      'Research on media effects',
      'Computer games and aggression',
      'Desensitisation',
      'Disinhibition',
      'Cognitive priming',
      'Evaluation of media influence research',
    ],
  },
  {
    id: 'aqa-alevel-psych-forensic',
    name: 'Forensic Psychology',
    description: 'Offender profiling, explanations of offending, and dealing with offenders',
    icon: '🔍',
    color: 'bg-gray-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 3',
    subtopics: [
      // Offender profiling
      'Offender profiling: top-down approach',
      'FBI typology approach',
      'Organised vs disorganised offenders',
      'Crime scene analysis',
      'Evaluation of top-down profiling',
      'Offender profiling: bottom-up approach',
      "Canter's investigative psychology",
      'Interpersonal coherence',
      'Forensic awareness',
      'Smallest space analysis',
      'Geographical profiling',
      "Canter's circle theory",
      'Marauder vs commuter patterns',
      'Evaluation of bottom-up profiling',
      // Biological explanations
      'Biological explanations of offending',
      'Genetic explanations',
      'Twin and adoption studies',
      'Candidate genes (MAOA)',
      'Neural explanations',
      'Prefrontal cortex dysfunction',
      "Raine's research",
      'Evaluation of biological explanations',
      // Psychological explanations
      "Eysenck's theory of the criminal personality",
      'Extraversion',
      'Neuroticism',
      'Psychoticism',
      'Biological basis of personality',
      'Conditioning and socialisation',
      'Evaluation of Eysenck',
      'Cognitive explanations',
      'Level of moral reasoning',
      "Kohlberg's theory and offending",
      'Cognitive distortions',
      'Hostile attribution bias',
      'Minimalisation',
      'Evaluation of cognitive explanations',
      'Differential association theory',
      "Sutherland's theory",
      'Learned behaviour',
      'Frequency, intensity, duration, priority',
      'Evaluation of differential association',
      // Dealing with offenders
      'Custodial sentencing',
      'Aims of custodial sentencing',
      'Deterrence',
      'Incapacitation',
      'Retribution',
      'Rehabilitation',
      'Psychological effects of custody',
      'Recidivism',
      'Evaluation of custodial sentencing',
      'Behaviour modification in custody',
      'Token economy programmes',
      'Effectiveness of token economies',
      'Ethical issues',
      'Evaluation of behaviour modification',
      'Anger management',
      'Cognitive preparation phase',
      'Skill acquisition phase',
      'Application phase',
      'Effectiveness of anger management',
      'Evaluation of anger management',
      'Restorative justice',
      'Principles of restorative justice',
      'Victim-offender mediation',
      'Conferencing',
      'Effectiveness of restorative justice',
      'Evaluation of restorative justice',
    ],
  },
  {
    id: 'aqa-alevel-psych-addiction',
    name: 'Addiction',
    description: 'Risk factors, explanations for nicotine and gambling addiction, and reducing addiction',
    icon: '🎰',
    color: 'bg-emerald-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Paper 3 Option 3',
    subtopics: [
      // Describing addiction
      'Describing addiction',
      'Physical vs psychological dependence',
      'Tolerance',
      'Withdrawal syndrome',
      // Risk factors
      'Risk factors in developing addiction',
      'Genetic vulnerability',
      'Family and twin studies',
      'Dopamine receptor genes',
      'Stress as a risk factor',
      'Self-medication hypothesis',
      'Personality factors',
      'Sensation-seeking',
      'Impulsivity',
      'Antisocial personality',
      'Evaluation of risk factors',
      'Family influences',
      'Parental modelling',
      'Attitudes to addiction',
      'Peer influences',
      'Social identity theory',
      'Social learning',
      'Evaluation of family and peer influences',
      // Nicotine addiction
      'Nicotine addiction: brain neurochemistry',
      'Dopamine and reward pathway',
      'Nicotinic acetylcholine receptors',
      'Role of the nucleus accumbens',
      'Evaluation of neurochemical explanation',
      'Nicotine addiction: learning theory',
      'Classical conditioning: cue reactivity',
      'Operant conditioning: reinforcement',
      'Positive reinforcement (pleasure)',
      'Negative reinforcement (avoiding withdrawal)',
      'Social learning',
      'Evaluation of learning theory',
      // Gambling addiction
      'Gambling addiction: learning theory',
      'Operant conditioning explanation',
      'Variable reinforcement schedules',
      'Partial reinforcement effect',
      'Classical conditioning: cues',
      'Evaluation of learning theory',
      'Gambling addiction: cognitive theory',
      'Cognitive biases',
      'Illusion of control',
      "Gambler's fallacy",
      'Recall bias',
      'Attribution errors',
      'Evaluation of cognitive explanation',
      // Reducing addiction
      'Reducing addiction: drug therapy',
      'Drug interventions for nicotine',
      'Nicotine replacement therapy',
      'Varenicline (Champix)',
      'Drug interventions for gambling',
      'Opioid antagonists',
      'Evaluation of drug therapy',
      'Reducing addiction: behavioural interventions',
      'Aversion therapy',
      'How aversion therapy works',
      'Covert sensitisation',
      'Evaluation of behavioural interventions',
      'Reducing addiction: CBT',
      'Cognitive restructuring',
      'Functional analysis',
      'Skills training',
      'Evaluation of CBT for addiction',
      // Theory of planned behaviour
      'Theory of planned behaviour',
      'Behavioural attitude',
      'Subjective norms',
      'Perceived behavioural control',
      'Application to addiction',
      'Evaluation of TPB',
      // Prochaska's model
      "Prochaska's six-stage model of behaviour change",
      'Pre-contemplation stage',
      'Contemplation stage',
      'Preparation stage',
      'Action stage',
      'Maintenance stage',
      'Termination stage',
      'Application to addiction treatment',
      "Evaluation of Prochaska's model",
    ],
  },
];

export function getAQAALevelPsychologyTopicById(id: string): Topic | undefined {
  return aqaALevelPsychologyTopics.find((topic) => topic.id === id);
}
