// Edexcel GCSE English Literature (1ET0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/english-literature-2015.html

import { Topic } from '@/types';

export const edexcelGCSEEnglishLiteratureTopics: Topic[] = [
  // Paper 1: Shakespeare and Post-1914 Literature
  {
    id: 'lit-macbeth',
    name: 'Macbeth',
    description: 'Shakespeare\'s tragedy exploring ambition, guilt, and supernatural forces',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Ambition and its destructive nature',
      'Guilt and psychological torment',
      'The supernatural and witchcraft',
      'Masculinity and violence',
      'Kingship and tyranny',
      'Appearance vs reality',
      'Fate vs free will',
      'Lady Macbeth\'s manipulation',
      'Macbeth\'s tragic downfall',
      'The witches\' prophecies',
      'Banquo\'s ghost',
      'Duncan as ideal king',
      'Malcolm and restoration',
      'Blood imagery',
      'Sleep and sleeplessness',
      'Scotland vs England',
    ],
  },
  {
    id: 'lit-romeo-juliet',
    name: 'Romeo and Juliet',
    description: 'Shakespeare\'s tragic love story set against family feuding',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love at first sight',
      'Fate and the stars',
      'Family honour and feuding',
      'Youth and impulsiveness',
      'Death and sacrifice',
      'Light and dark imagery',
      'Public vs private conflict',
      'Marriage and society',
      'Romeo\'s passion',
      'Juliet\'s maturity',
      'The Nurse\'s loyalty',
      'Friar Lawrence\'s plan',
      'Tybalt and honour',
      'Mercutio\'s death',
      'The balcony scene',
      'The tomb scene',
    ],
  },
  {
    id: 'lit-merchant-venice',
    name: 'The Merchant of Venice',
    description: 'Shakespeare\'s problematic comedy exploring mercy, justice, and prejudice',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Mercy vs justice',
      'Anti-Semitism and prejudice',
      'Friendship and sacrifice',
      'Love and wealth',
      'Appearance vs reality',
      'Bonds and contracts',
      'Shylock\'s complexity',
      'Portia\'s wit and agency',
      'Antonio\'s devotion',
      'Bassanio\'s choice',
      'The casket scenes',
      'The trial scene',
      'The ring plot',
      'Venice and Belmont',
      'Christian vs Jewish values',
      'Revenge and forgiveness',
    ],
  },
  {
    id: 'lit-much-ado',
    name: 'Much Ado About Nothing',
    description: 'Shakespeare\'s romantic comedy exploring love, deception, and reputation',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love and resistance',
      'Deception and eavesdropping',
      'Honour and shame',
      'Gender expectations',
      'Wit and wordplay',
      'True vs false appearances',
      'Beatrice\'s independence',
      'Benedick\'s transformation',
      'Hero\'s suffering',
      'Claudio\'s cruelty',
      'Don John\'s malice',
      'Dogberry\'s comedy',
      'The masked ball',
      'The gulling scenes',
      'The church scene',
      'Resolution and marriage',
    ],
  },
  {
    id: 'lit-twelfth-night',
    name: 'Twelfth Night',
    description: 'Shakespeare\'s comedy of mistaken identity, love, and festivity',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love and desire',
      'Disguise and identity',
      'Madness and misrule',
      'Class and ambition',
      'Festivity and excess',
      'Gender confusion',
      'Viola\'s resourcefulness',
      'Olivia\'s mourning',
      'Orsino\'s melancholy',
      'Malvolio\'s humiliation',
      'Sir Toby\'s revelry',
      'Feste\'s wisdom',
      'The letter plot',
      'The twins\' reunion',
      'Music and songs',
      'Comedy and cruelty',
    ],
  },
  // 19th Century Novels
  {
    id: 'lit-christmas-carol',
    name: 'A Christmas Carol',
    description: 'Dickens\' moral tale of redemption and social conscience',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Redemption and change',
      'Social responsibility',
      'Christmas values',
      'Wealth vs happiness',
      'Family bonds',
      'Past, present, and future',
      'Scrooge\'s transformation',
      'Marley\'s warning',
      'The three spirits',
      'The Cratchit family',
      'Tiny Tim\'s innocence',
      'Ignorance and Want',
      'Victorian poverty',
      'Cold and warmth imagery',
      'Light and darkness',
      'The supernatural',
    ],
  },
  {
    id: 'lit-jekyll-hyde',
    name: 'The Strange Case of Dr Jekyll and Mr Hyde',
    description: 'Stevenson\'s Gothic novella exploring the dual nature of humanity',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Duality and division',
      'Repression and release',
      'Victorian hypocrisy',
      'Scientific ambition',
      'Secrets and shame',
      'Respectability and reputation',
      'Jekyll\'s transformation',
      'Hyde\'s depravity',
      'Utterson\'s investigation',
      'The door symbolism',
      'London\'s dark streets',
      'Violence and murder',
      'Loss of control',
      'The final revelation',
      'Gothic atmosphere',
      'Male society and secrets',
    ],
  },
  {
    id: 'lit-frankenstein',
    name: 'Frankenstein',
    description: 'Shelley\'s Gothic novel about creation, responsibility, and isolation',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Creation and consequences',
      'Parental responsibility',
      'Isolation and rejection',
      'Ambition and hubris',
      'Monstrosity and appearance',
      'Nature vs nurture',
      'Victor\'s obsession',
      'The creature\'s humanity',
      'Walton\'s parallel journey',
      'The De Lacey family',
      'Female victims',
      'The Arctic setting',
      'Prometheus myth',
      'Frame narrative',
      'Romantic ideals',
      'Revenge and destruction',
    ],
  },
  {
    id: 'lit-jane-eyre',
    name: 'Jane Eyre',
    description: 'Brontë\'s novel of a governess\'s journey to independence and love',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Independence and equality',
      'Love and morality',
      'Social class barriers',
      'Religion and conscience',
      'Gender restrictions',
      'Reason vs passion',
      'Jane\'s growth',
      'Rochester\'s secret',
      'Bertha in the attic',
      'Reed family cruelty',
      'Lowood School',
      'Thornfield romance',
      'Moor House',
      'The mad woman',
      'Fire imagery',
      'Equality in marriage',
    ],
  },
  {
    id: 'lit-pride-prejudice',
    name: 'Pride and Prejudice',
    description: 'Austen\'s witty novel of manners exploring marriage and social class',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Pride and prejudice',
      'Marriage for love vs money',
      'Class and social mobility',
      'First impressions',
      'Female independence',
      'Wit and irony',
      'Elizabeth\'s judgement',
      'Darcy\'s pride',
      'Jane\'s goodness',
      'Wickham\'s villainy',
      'Lady Catherine',
      'The Bennet parents',
      'Pemberley estate',
      'Letter writing',
      'Reputation and scandal',
      'Character development',
    ],
  },
  // Post-1914 Literature
  {
    id: 'lit-inspector-calls',
    name: 'An Inspector Calls',
    description: 'Priestley\'s morality play examining responsibility and class division',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Collective responsibility',
      'Class consciousness',
      'Capitalism critique',
      'Generational attitudes',
      'Confession and guilt',
      'Gender inequality',
      'Inspector Goole\'s message',
      'Birling\'s arrogance',
      'Sybil\'s coldness',
      'Sheila\'s conscience',
      'Eric\'s desperation',
      'Gerald\'s betrayal',
      'Eva Smith\'s fate',
      'The final phone call',
      'Dramatic irony',
      '1912 setting, 1945 message',
    ],
  },
  {
    id: 'lit-animal-farm',
    name: 'Animal Farm',
    description: 'Orwell\'s allegorical novella satirising totalitarianism and revolution',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Power and corruption',
      'Revolution and betrayal',
      'Propaganda and language',
      'Class and exploitation',
      'Education and ignorance',
      'Idealism vs reality',
      'Napoleon\'s tyranny',
      'Snowball\'s vision',
      'Boxer\'s loyalty',
      'Squealer\'s manipulation',
      'The Seven Commandments',
      'The windmill',
      'The dogs and violence',
      'Benjamin\'s cynicism',
      'Russian Revolution parallels',
      'Pigs becoming human',
    ],
  },
  // Poetry Anthology
  {
    id: 'lit-poetry-relationships',
    name: 'Poetry Anthology: Relationships',
    description: 'Edexcel poetry collection exploring various aspects of human relationships',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Romantic love',
      'Family relationships',
      'Loss and grief',
      'Memory and nostalgia',
      'Identity and self',
      'Conflict in relationships',
      'Comparing Romantic poems',
      'Comparing Literary Heritage poems',
      'Comparing Contemporary poems',
      'Language analysis',
      'Structure analysis',
      'Form analysis',
      'Context and meaning',
      'Voice and perspective',
      'Imagery and symbolism',
      'Comparison techniques',
    ],
  },
  {
    id: 'lit-unseen-poetry',
    name: 'Unseen Poetry',
    description: 'Skills for responding to unfamiliar poems in examination conditions',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Reading strategies',
      'Identifying themes',
      'Language analysis',
      'Structure analysis',
      'Form identification',
      'Tone and atmosphere',
      'Voice and speaker',
      'Imagery analysis',
      'Sound and rhythm',
      'Comparing two poems',
      'Finding connections',
      'Contrasting approaches',
      'Using terminology',
      'Evidence and quotation',
      'Planning answers',
      'Time management',
    ],
  },
];

export function getEdexcelGCSEEnglishLiteratureTopicById(id: string): Topic | undefined {
  return edexcelGCSEEnglishLiteratureTopics.find((topic) => topic.id === id);
}
