// OCR A-Level Physics A (H556) Topics
// Complete specification coverage
// Paper 1 (Modelling Physics): Modules 1, 2, 3, 5
// Paper 2 (Exploring Physics): Modules 1, 2, 4, 6
// Paper 3 (Unified Physics): All modules - synoptic questions

import { Topic } from '@/types';

export const ocrALevelPhysicsTopics: Topic[] = [
  // ==========================================
  // MODULE 1: Development of Practical Skills
  // ==========================================
  {
    id: 'practical-skills',
    name: 'Development of Practical Skills',
    description: 'Practical skills for written examination and practical endorsement',
    icon: '🔬',
    color: 'bg-purple-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Papers 1, 2 & 3',
    subtopics: [
      // 1.1 Practical skills assessed in a written examination
      'Planning experiments',
      'Implementing experimental procedures',
      'Analysing experimental results',
      'Evaluating experimental procedures',
      'Identifying variables',
      'Control variables',
      'Selecting appropriate apparatus',
      'Risk assessment',
      'Recording observations',
      'Significant figures',
      'Tables and graphs',
      'Line of best fit',
      'Gradient and intercept',
      'Systematic errors',
      'Random errors',
      'Uncertainty calculations',
      'Percentage uncertainty',
      'Combining uncertainties',
      'Error bars',
      'Anomalous results',
      // 1.2 Practical skills assessed in the practical endorsement
      'PAG practical activities',
      'Using appropriate techniques',
      'Safe use of equipment',
      'Following written procedures',
      'Making accurate observations',
      'Keeping appropriate records',
      'Researching and referencing',
      'Using instruments correctly',
    ],
  },

  // ==========================================
  // MODULE 2: Foundations of Physics
  // ==========================================
  {
    id: 'foundations',
    name: 'Foundations of Physics',
    description: 'Physical quantities, units, scalars, vectors and estimation',
    icon: '📐',
    color: 'bg-blue-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Papers 1, 2 & 3',
    subtopics: [
      // 2.1 Physical quantities and units
      'SI units',
      'Base units',
      'Derived units',
      'Prefixes',
      'Homogeneity of equations',
      'Checking equations dimensionally',
      'Scalar quantities',
      'Vector quantities',
      'Adding vectors',
      'Subtracting vectors',
      'Resolving vectors',
      'Vector components',
      'Resultant vectors',
      // 2.2 Making measurements and analysing data
      'Measurement techniques',
      'Precision and accuracy',
      'Absolute uncertainty',
      'Fractional uncertainty',
      'Uncertainty in measurements',
      'Propagation of uncertainties',
      'Graphical analysis',
      'Linear relationships',
      'Logarithmic relationships',
      'Using spreadsheets',
      // 2.3 Nature of quantities
      'Estimation',
      'Orders of magnitude',
      'Standard form',
    ],
  },

  // ==========================================
  // MODULE 3: Forces and Motion (Paper 1)
  // ==========================================
  {
    id: 'forces-motion',
    name: 'Forces and Motion',
    description: 'Kinematics, dynamics, work, energy, materials and momentum',
    icon: '🚀',
    color: 'bg-green-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1 & 3',
    subtopics: [
      // 3.1 Motion
      'Displacement',
      'Instantaneous velocity',
      'Average velocity',
      'Instantaneous acceleration',
      'Average acceleration',
      'Displacement-time graphs',
      'Velocity-time graphs',
      'Area under graphs',
      'Gradient of graphs',
      'SUVAT equations',
      'Deriving SUVAT equations',
      'Free fall',
      'Acceleration due to gravity (g)',
      'Projectile motion',
      'Horizontal projection',
      'Projection at an angle',
      'Trajectory calculations',
      'Range of projectile',
      'Maximum height',
      // 3.2 Forces in action
      'Types of forces',
      'Contact forces',
      'Non-contact forces',
      'Free-body diagrams',
      'Weight',
      'Tension',
      'Normal contact force',
      'Friction',
      'Drag forces',
      'Air resistance',
      'Terminal velocity',
      'Equilibrium',
      'Coplanar forces',
      'Turning effects',
      'Moment of force',
      'Torque',
      'Couple',
      'Principle of moments',
      'Centre of mass',
      'Centre of gravity',
      'Stability',
      'Density',
      'Pressure',
      'Upthrust',
      'Archimedes\' principle',
      // 3.3 Work, energy and power
      'Work done',
      'Work done by a force',
      'Work done at an angle',
      'Kinetic energy',
      'Gravitational potential energy',
      'Elastic potential energy',
      'Conservation of energy',
      'Energy transfers',
      'Power',
      'Power and velocity',
      'Efficiency',
      // 3.4 Materials
      'Springs',
      'Hooke\'s law',
      'Spring constant',
      'Springs in series',
      'Springs in parallel',
      'Elastic limit',
      'Elastic deformation',
      'Plastic deformation',
      'Tensile stress',
      'Tensile strain',
      'Young modulus',
      'Stress-strain graphs',
      'Ultimate tensile stress',
      'Breaking stress',
      'Elastic strain energy',
      'Area under force-extension graph',
      // 3.5 Newton's laws of motion and momentum
      'Newton\'s first law',
      'Inertia',
      'Newton\'s second law',
      'F = ma',
      'Net force',
      'Newton\'s third law',
      'Action-reaction pairs',
      'Momentum',
      'Impulse',
      'Force-time graphs',
      'Conservation of momentum',
      'Elastic collisions',
      'Inelastic collisions',
      'Perfectly inelastic collisions',
      'Explosions',
      'Two-dimensional collisions',
    ],
  },

  // ==========================================
  // MODULE 4: Electrons, Waves and Photons (Paper 2)
  // ==========================================
  {
    id: 'electrons-waves',
    name: 'Electrons, Waves and Photons',
    description: 'Electricity, waves, quantum physics and optics',
    icon: '⚡',
    color: 'bg-yellow-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2 & 3',
    subtopics: [
      // 4.1 Charge and current
      'Electric charge',
      'Elementary charge',
      'Electric current',
      'Conventional current',
      'Electron flow',
      'I = Q/t',
      'Kirchhoff\'s first law',
      'Conservation of charge',
      'Mean drift velocity',
      'Number density',
      'Current in metals',
      'Current in semiconductors',
      // 4.2 Energy, power and resistance
      'Potential difference',
      'Electromotive force (EMF)',
      'Energy transfer in circuits',
      'Electron volt',
      'Resistance',
      'Ohm\'s law',
      'Ohmic conductors',
      'I-V characteristics',
      'Filament lamp',
      'Thermistor',
      'Light-dependent resistor (LDR)',
      'Diode',
      'Light-emitting diode (LED)',
      'Resistivity',
      'Effect of temperature on resistance',
      'Electrical power',
      'Power equations',
      'Energy dissipation',
      // 4.3 Electrical circuits
      'Series circuits',
      'Parallel circuits',
      'Kirchhoff\'s second law',
      'Resistors in series',
      'Resistors in parallel',
      'Potential divider',
      'Potential divider equation',
      'Sensor circuits',
      'Internal resistance',
      'Lost volts',
      'Terminal potential difference',
      'EMF and internal resistance equation',
      'Power output from source',
      // 4.4 Waves
      'Progressive waves',
      'Transverse waves',
      'Longitudinal waves',
      'Wave properties',
      'Wavelength',
      'Frequency',
      'Period',
      'Amplitude',
      'Phase and phase difference',
      'Wave speed equation',
      'Intensity',
      'Intensity and amplitude',
      'Reflection',
      'Refraction',
      'Refractive index',
      'Snell\'s law',
      'Total internal reflection',
      'Critical angle',
      'Optical fibres',
      'Diffraction',
      'Polarisation',
      'Polarised light',
      'Malus\' law',
      'Applications of polarisation',
      // 4.5 Quantum physics
      'Photons',
      'Photon energy',
      'Planck constant',
      'Photoelectric effect',
      'Threshold frequency',
      'Work function',
      'Einstein\'s photoelectric equation',
      'Stopping potential',
      'Wave-particle duality',
      'de Broglie wavelength',
      'Electron diffraction',
      'Energy levels',
      'Line spectra',
      'Emission spectra',
      'Absorption spectra',
      'Photon emission and absorption',
      'Ground state',
      'Excited states',
      'Ionisation energy',
    ],
  },

  // ==========================================
  // MODULE 5: Newtonian World and Astrophysics (Paper 1)
  // ==========================================
  {
    id: 'newtonian-astro',
    name: 'Newtonian World and Astrophysics',
    description: 'Thermal physics, gases, circular motion, oscillations, gravitation and cosmology',
    icon: '🌌',
    color: 'bg-indigo-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1 & 3',
    subtopics: [
      // 5.1 Thermal physics
      'Temperature',
      'Thermal equilibrium',
      'Absolute zero',
      'Kelvin scale',
      'Celsius to Kelvin conversion',
      'States of matter',
      'Internal energy',
      'Kinetic energy of molecules',
      'Potential energy of molecules',
      'Specific heat capacity',
      'Q = mcΔθ',
      'Specific latent heat',
      'Latent heat of fusion',
      'Latent heat of vaporisation',
      // 5.2 Ideal gases
      'Kinetic theory of gases',
      'Assumptions of kinetic theory',
      'Brownian motion',
      'Pressure of a gas',
      'pV = (1/3)Nm<c²>',
      'Boyle\'s law',
      'Charles\'s law',
      'Pressure law',
      'Ideal gas equation (pV = nRT)',
      'Molar gas constant',
      'Avogadro constant',
      'Boltzmann constant',
      'pV = NkT',
      'Root mean square speed',
      'Kinetic energy of gas molecules',
      'E = (3/2)kT',
      // 5.3 Circular motion
      'Circular motion',
      'Angular displacement',
      'Angular velocity',
      'Radian',
      'Period of circular motion',
      'Linear speed',
      'Centripetal acceleration',
      'Centripetal force',
      'F = mv²/r',
      'Horizontal circular motion',
      'Vertical circular motion',
      'Conical pendulum',
      'Banked tracks',
      // 5.4 Oscillations
      'Simple harmonic motion',
      'SHM definition',
      'a = -ω²x',
      'Displacement in SHM',
      'Velocity in SHM',
      'Acceleration in SHM',
      'SHM graphs',
      'Angular frequency',
      'Period of SHM',
      'Mass-spring oscillator',
      'Simple pendulum',
      'Period of pendulum',
      'Energy in SHM',
      'Energy-displacement graphs in SHM',
      'Damped oscillations',
      'Light damping',
      'Heavy damping',
      'Critical damping',
      'Forced oscillations',
      'Resonance',
      'Natural frequency',
      'Driving frequency',
      'Effects of damping on resonance',
      // 5.5 Gravitational fields
      'Gravitational field',
      'Gravitational field lines',
      'Gravitational field strength',
      'Uniform gravitational field',
      'Radial gravitational field',
      'Newton\'s law of gravitation',
      'F = GMm/r²',
      'Gravitational constant G',
      'g = GM/r²',
      'Gravitational potential',
      'V = -GM/r',
      'Gravitational potential energy',
      'E = -GMm/r',
      'Escape velocity',
      'Satellite motion',
      'Orbital period',
      'Orbital speed',
      'Geostationary orbit',
      'Low Earth orbit',
      'Kepler\'s third law',
      'Energy of an orbiting satellite',
      // 5.6 Astrophysics and cosmology
      'Stars',
      'Stellar evolution',
      'Life cycle of stars',
      'Protostar',
      'Main sequence',
      'Red giant',
      'White dwarf',
      'Supernova',
      'Neutron star',
      'Black hole',
      'Hertzsprung-Russell diagram',
      'Luminosity',
      'Apparent magnitude',
      'Absolute magnitude',
      'Stefan-Boltzmann law',
      'Wien\'s displacement law',
      'Stellar spectra',
      'Spectral classes',
      'Doppler effect for light',
      'Red shift',
      'Blue shift',
      'Hubble\'s law',
      'Hubble constant',
      'Expanding universe',
      'Big Bang theory',
      'Age of universe',
      'Cosmic microwave background radiation',
      'Dark matter',
      'Dark energy',
    ],
  },

  // ==========================================
  // MODULE 6: Particles and Medical Physics (Paper 2)
  // ==========================================
  {
    id: 'particles-medical',
    name: 'Particles and Medical Physics',
    description: 'Capacitors, electric fields, electromagnetism, nuclear physics and medical imaging',
    icon: '⚛️',
    color: 'bg-red-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2 & 3',
    subtopics: [
      // 6.1 Capacitors
      'Capacitance',
      'C = Q/V',
      'Parallel plate capacitor',
      'Dielectrics',
      'Permittivity',
      'Relative permittivity',
      'Capacitors in series',
      'Capacitors in parallel',
      'Energy stored in capacitor',
      'W = ½QV = ½CV² = ½Q²/C',
      'Charging capacitors',
      'Discharging capacitors',
      'Time constant',
      'Exponential decay',
      'Capacitor discharge graphs',
      'Half-life of capacitor discharge',
      // 6.2 Electric fields
      'Electric field',
      'Electric field lines',
      'Uniform electric field',
      'Electric field strength',
      'E = V/d',
      'Force on a charge',
      'F = EQ',
      'Motion of charged particles in fields',
      'Radial electric field',
      'Coulomb\'s law',
      'Electric field of point charge',
      'Electric potential',
      'Electric potential energy',
      'Equipotentials',
      'Comparison of gravitational and electric fields',
      // 6.3 Electromagnetism
      'Magnetic fields',
      'Magnetic field patterns',
      'Magnetic flux density',
      'Force on current-carrying wire',
      'F = BIL',
      'Fleming\'s left hand rule',
      'Force on moving charge',
      'F = BQv',
      'Charged particles in magnetic fields',
      'Circular path in magnetic field',
      'Velocity selector',
      'Cyclotron',
      'Magnetic flux',
      'Magnetic flux linkage',
      'Faraday\'s law',
      'Lenz\'s law',
      'Electromagnetic induction',
      'Induced EMF',
      'EMF in moving conductor',
      'Generators',
      'Alternating current',
      'Transformers',
      'Transformer equation',
      'Transformer efficiency',
      'Eddy currents',
      // 6.4 Nuclear and particle physics
      'Rutherford scattering',
      'Nuclear model of atom',
      'Nucleon number',
      'Proton number',
      'Isotopes',
      'Strong nuclear force',
      'Weak nuclear force',
      'Radius of nucleus',
      'Nuclear density',
      'Radioactive decay',
      'Alpha decay',
      'Beta-minus decay',
      'Beta-plus decay',
      'Gamma emission',
      'Nuclear decay equations',
      'Activity',
      'Decay constant',
      'Half-life',
      'Exponential decay of activity',
      'Radioactive dating',
      'Mass-energy equivalence',
      'E = mc²',
      'Binding energy',
      'Binding energy per nucleon',
      'Binding energy curve',
      'Nuclear fission',
      'Nuclear fusion',
      'Nuclear reactors',
      'Fundamental particles',
      'Standard Model',
      'Quarks',
      'Leptons',
      'Hadrons',
      'Baryons',
      'Mesons',
      'Antiparticles',
      'Particle interactions',
      'Conservation laws in particle physics',
      'Feynman diagrams',
      'Exchange particles',
      'Higgs boson',
      // 6.5 Medical imaging
      'X-rays',
      'X-ray production',
      'X-ray tube',
      'X-ray spectrum',
      'X-ray attenuation',
      'Attenuation coefficient',
      'Half-value thickness',
      'Contrast media',
      'CT scanning',
      'Image intensifiers',
      'Ultrasound',
      'Piezoelectric effect',
      'Ultrasound transducers',
      'Acoustic impedance',
      'Reflection coefficient',
      'A-scan',
      'B-scan',
      'Doppler ultrasound',
      'PET scanning',
      'Positron emission',
      'Annihilation',
      'Tracer techniques',
      'MRI scanning',
      'Nuclear magnetic resonance',
      'Comparison of imaging techniques',
    ],
  },
];

export function getOCRALevelPhysicsTopicById(id: string): Topic | undefined {
  return ocrALevelPhysicsTopics.find(topic => topic.id === id);
}
