// Edexcel GCSE Combined Science (1SC0) Topics
// Based on the official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/combined-science-2016.html
//
// Combined Science is worth 2 GCSEs and covers Biology, Chemistry, and Physics
// 6 papers total: Biology Paper 1 & 2, Chemistry Paper 1 & 2, Physics Paper 1 & 2
// Each paper: 1 hour 10 minutes, 60 marks, 16.7% of qualification
//
// (H) = Higher tier only

import { Topic } from '@/types';

export const edexcelCombinedScienceTopics: Topic[] = [
  // ============================================================================
  // BIOLOGY PAPER 1 TOPICS (B1-B5)
  // ============================================================================
  {
    id: 'edexcel-combined-biology-key-concepts',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Key Concepts in Biology',
    description: 'Cells, microscopy, enzymes, and transport',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // Topic 1: Key Concepts in Biology
      'Eukaryotic cell structure',
      'Plant and animal cells',
      'Prokaryotic cells',
      'Bacterial cell structure',
      'Specialised cells',
      'Light microscopy',
      'Electron microscopy',
      'Magnification calculations',
      'Enzymes as biological catalysts',
      'Lock and key model',
      'Effect of temperature on enzymes',
      'Effect of pH on enzymes',
      'Enzyme denaturation',
      'Diffusion',
      'Factors affecting diffusion',
      'Osmosis',
      'Osmosis in plant and animal cells',
      'Active transport',
      'Mitosis',
      'Stages of the cell cycle',
      'Cell differentiation',
      'Stem cells',
      'Stem cell uses',
    ],
  },
  {
    id: 'edexcel-combined-biology-cells-control',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Cells and Control',
    description: 'Cell division, growth, and the nervous system',
    icon: '🧬',
    color: 'bg-blue-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // Topic 2: Cells and Control
      'Mitosis for growth and repair',
      'The cell cycle',
      'Percentile growth charts',
      'Growth in plants and animals',
      'Cancer as uncontrolled cell division',
      'Structure of the nervous system',
      'Sensory, relay and motor neurones',
      'Synapses',
      'Reflex actions',
      'The reflex arc',
      'Reaction time practical',
    ],
  },
  {
    id: 'edexcel-combined-biology-genetics',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Genetics',
    description: 'DNA, inheritance, and genetic modification',
    icon: '🧬',
    color: 'bg-green-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // Topic 3: Genetics
      'Sexual and asexual reproduction',
      'Meiosis',
      'Gametes',
      'DNA structure',
      'Gene expression',
      'Chromosomes and genes',
      'Protein synthesis',
      'Mutations',
      'Inheritance of characteristics',
      'Dominant and recessive alleles',
      'Homozygous and heterozygous',
      'Genotype and phenotype',
      'Genetic diagrams',
      'Punnett squares',
      'Probability and genetics',
      'Sex determination',
      'XX and XY chromosomes',
      'Inherited disorders',
      'Polydactyly',
      'Cystic fibrosis',
    ],
  },
  {
    id: 'edexcel-combined-biology-natural-selection',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Natural Selection and Genetic Modification',
    description: 'Evolution, classification, and genetic engineering',
    icon: '🦎',
    color: 'bg-amber-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // Topic 4: Natural Selection and Genetic Modification
      'Darwin\'s theory of evolution',
      'Natural selection',
      'Evidence for evolution',
      'Fossil record',
      'Antibiotic resistance',
      'Classification',
      'Linnaean system',
      'Three domains',
      'Selective breeding',
      'Uses of selective breeding',
      'Problems with selective breeding',
      'Genetic engineering',
      'Process of genetic modification',
      'GM crops',
      'GM insulin',
      'Benefits and risks of GM',
    ],
  },
  {
    id: 'edexcel-combined-biology-health',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Health, Disease and the Development of Medicines',
    description: 'Pathogens, immunity, and drug development',
    icon: '🦠',
    color: 'bg-red-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // Topic 5: Health, Disease and the Development of Medicines
      'Health and disease',
      'Communicable diseases',
      'Non-communicable diseases',
      'Types of pathogens',
      'Bacteria',
      'Viruses',
      'Fungi',
      'Protists',
      'Spreading of pathogens',
      'Viral diseases (HIV, tobacco mosaic virus)',
      'Bacterial diseases (Salmonella, gonorrhoea)',
      'Fungal diseases (rose black spot)',
      'Protist diseases (malaria)',
      'Physical barriers to infection',
      'Chemical barriers to infection',
      'The immune response',
      'White blood cells',
      'Phagocytosis',
      'Antibodies',
      'Antitoxins',
      'Vaccination',
      'How vaccines work',
      'Herd immunity',
      'Antibiotics',
      'Antibiotic resistance',
      'Pain killers',
      'Drug development',
      'Pre-clinical and clinical trials',
    ],
  },

  // ============================================================================
  // BIOLOGY PAPER 2 TOPICS (B6-B9)
  // ============================================================================
  {
    id: 'edexcel-combined-biology-plant-structures',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Plant Structures and Their Functions',
    description: 'Photosynthesis, transport in plants, and plant hormones',
    icon: '🌱',
    color: 'bg-emerald-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // Topic 6: Plant Structures and Their Functions
      'Photosynthesis equation',
      'Photosynthesis as endothermic',
      'Factors affecting photosynthesis',
      'Light intensity',
      'Carbon dioxide concentration',
      'Temperature',
      'Limiting factors',
      'Leaf structure',
      'Adaptations for photosynthesis',
      'Investigating photosynthesis rate',
      'Xylem and phloem',
      'Transpiration',
      'Factors affecting transpiration',
      'Transpiration stream',
      'Translocation',
    ],
  },
  {
    id: 'edexcel-combined-biology-animal-coordination',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Animal Coordination, Control and Homeostasis',
    description: 'Hormones, reproduction, and maintaining stable conditions',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // Topic 7: Animal Coordination, Control and Homeostasis
      'Homeostasis',
      'Importance of homeostasis',
      'The endocrine system',
      'Glands and hormones',
      'Adrenaline',
      'Thyroxine',
      'Comparing nervous and hormonal responses',
      'Blood glucose control',
      'Insulin and glucagon',
      'Diabetes Type 1',
      'Diabetes Type 2',
      'The menstrual cycle',
      'Hormones in menstrual cycle',
      'FSH, oestrogen, LH, progesterone',
      'Contraception',
      'Hormonal contraception',
      'Non-hormonal contraception',
      'Fertility treatments',
      'IVF',
      'Negative feedback',
    ],
  },
  {
    id: 'edexcel-combined-biology-exchange-transport',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Exchange and Transport in Animals',
    description: 'Digestive system, circulatory system, and gas exchange',
    icon: '🫀',
    color: 'bg-red-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // Topic 8: Exchange and Transport in Animals
      'Levels of organisation',
      'Digestive system structure',
      'Digestive enzymes',
      'Carbohydrases',
      'Proteases',
      'Lipases',
      'Bile',
      'Food tests',
      'The heart',
      'Heart structure',
      'Heart function',
      'Blood vessels',
      'Arteries, veins, capillaries',
      'Blood components',
      'Red blood cells',
      'White blood cells',
      'Platelets',
      'Plasma',
      'Coronary heart disease',
      'Treatments for heart disease',
    ],
  },
  {
    id: 'edexcel-combined-biology-ecosystems',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Ecosystems and Material Cycles',
    description: 'Ecology, biodiversity, and nutrient cycles',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // Topic 9: Ecosystems and Material Cycles
      'Communities and ecosystems',
      'Abiotic factors',
      'Biotic factors',
      'Adaptations',
      'Food chains',
      'Food webs',
      'Pyramids of biomass',
      'Energy transfer',
      'Efficiency of energy transfer',
      'Sampling organisms',
      'Quadrats',
      'Transects',
      'Human effects on ecosystems',
      'Biodiversity',
      'Pollution',
      'Global warming',
      'Deforestation',
      'Decomposition',
      'Carbon cycle',
      'Water cycle',
    ],
  },

  // ============================================================================
  // CHEMISTRY PAPER 1 TOPICS (C1-C5)
  // ============================================================================
  {
    id: 'edexcel-combined-chemistry-key-concepts',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Key Concepts in Chemistry',
    description: 'Atomic structure, the periodic table, and bonding',
    icon: '⚛️',
    color: 'bg-blue-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // Topic 1: Key Concepts in Chemistry
      'Structure of an atom',
      'Protons, neutrons, electrons',
      'Mass number and atomic number',
      'Electronic configurations',
      'Isotopes',
      'Relative atomic mass',
      'Development of the periodic table',
      'Mendeleev\'s periodic table',
      'Modern periodic table',
      'Groups and periods',
      'Metals and non-metals',
      'Ionic bonding',
      'Forming ions',
      'Ionic compounds',
      'Covalent bonding',
      'Simple molecules',
      'Giant covalent structures',
      'Metallic bonding',
      'Properties of ionic compounds',
      'Properties of covalent compounds',
      'Properties of metals',
      'Alloys',
      'States of matter',
      'State changes',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-states-matter',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'States of Matter and Mixtures',
    description: 'Separating mixtures and water treatment',
    icon: '💧',
    color: 'bg-cyan-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // Topic 2: States of Matter and Mixtures
      'Particle model',
      'States of matter',
      'Melting, boiling, freezing, condensing',
      'Pure substances',
      'Impure substances',
      'Mixtures',
      'Separation techniques',
      'Filtration',
      'Crystallisation',
      'Distillation',
      'Fractional distillation',
      'Chromatography',
      'Calculating Rf values',
      'Drinking water',
      'Potable water',
      'Desalination',
      'Water treatment',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-chemical-changes',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Changes',
    description: 'Acids, bases, electrolysis, and reactions of metals',
    icon: '🧪',
    color: 'bg-orange-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // Topic 3: Chemical Changes
      'Acids and bases',
      'pH scale',
      'Indicators',
      'Neutralisation',
      'Reactions of acids with metals',
      'Reactions of acids with metal oxides',
      'Reactions of acids with metal hydroxides',
      'Reactions of acids with carbonates',
      'Making salts',
      'Soluble salts',
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Products at electrodes',
      'Electrolysis of molten compounds',
      'Electrolysis of aqueous solutions',
      'Half equations (H)',
      'Oxidation as loss of electrons',
      'Reduction as gain of electrons',
      'OILRIG',
      'Reactivity series',
      'Extraction of metals',
      'Displacement reactions',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-extracting-metals',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Extracting Metals and Equilibria',
    description: 'Metal extraction and reversible reactions',
    icon: '⛏️',
    color: 'bg-gray-600',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // Topic 4: Extracting Metals and Equilibria
      'Metals and reactivity',
      'Extraction of metals',
      'Reduction using carbon',
      'Electrolysis extraction',
      'Extraction of aluminium',
      'Properties of aluminium',
      'Recycling metals',
      'Life cycle assessment',
      'Oxidation and reduction',
      'Reversible reactions',
      'Dynamic equilibrium (H)',
      'Changing equilibrium position (H)',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-groups',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Separate Sciences Specific Topics',
    description: 'Groups in the periodic table',
    icon: '📊',
    color: 'bg-purple-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // Topic 5: Groups in Periodic Table
      'Group 1 - Alkali metals',
      'Properties of alkali metals',
      'Reactions with water',
      'Trends in Group 1',
      'Group 7 - Halogens',
      'Properties of halogens',
      'Reactions of halogens',
      'Displacement reactions',
      'Trends in Group 7',
      'Group 0 - Noble gases',
      'Properties of noble gases',
      'Uses of noble gases',
    ],
  },

  // ============================================================================
  // CHEMISTRY PAPER 2 TOPICS (C6-C9)
  // ============================================================================
  {
    id: 'edexcel-combined-chemistry-rates',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Rates of Reaction and Energy Changes',
    description: 'Reaction rates, catalysts, and energy transfers',
    icon: '⏱️',
    color: 'bg-yellow-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // Topic 6: Rates of Reaction and Energy Changes
      'Rate of reaction',
      'Measuring rate of reaction',
      'Factors affecting rate',
      'Concentration and rate',
      'Surface area and rate',
      'Temperature and rate',
      'Catalysts',
      'Collision theory',
      'Activation energy',
      'Exothermic reactions',
      'Endothermic reactions',
      'Reaction profiles',
      'Bond energies (H)',
      'Calculating energy changes (H)',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-fuels',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Fuels and Earth Science',
    description: 'Hydrocarbons, combustion, and the atmosphere',
    icon: '🛢️',
    color: 'bg-gray-700',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // Topic 7: Fuels and Earth Science
      'Crude oil',
      'Hydrocarbons',
      'Alkanes',
      'Properties of alkanes',
      'Fractional distillation',
      'Fractions of crude oil',
      'Complete combustion',
      'Incomplete combustion',
      'Carbon monoxide',
      'Particulates',
      'Sulfur dioxide',
      'Acid rain',
      'Nitrogen oxides',
      'Cracking',
      'Alkenes',
      'Testing for alkenes',
      'Addition polymers',
      'Condensation polymers',
      'Earth\'s atmosphere',
      'Evolution of atmosphere',
      'Greenhouse gases',
      'Climate change',
      'Carbon footprint',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-quantitative',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Calculations',
    description: 'Moles, concentrations, and yields',
    icon: '⚖️',
    color: 'bg-green-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // Topic 8: Quantitative Chemistry
      'Relative formula mass',
      'Conservation of mass',
      'Balancing equations',
      'The mole',
      'Avogadro\'s number',
      'Calculating moles',
      'Reacting masses',
      'Limiting reactants',
      'Percentage yield',
      'Atom economy',
      'Concentration in g/dm\u00B3',
      'Concentration in mol/dm\u00B3 (H)',
      'Titrations (H)',
    ],
  },
  {
    id: 'edexcel-combined-chemistry-analysis',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Analysis',
    description: 'Testing for ions and gases',
    icon: '🔬',
    color: 'bg-teal-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // Topic 9: Chemical Analysis
      'Purity',
      'Formulations',
      'Flame tests',
      'Flame test colours',
      'Testing for metal ions',
      'Sodium hydroxide tests',
      'Testing for carbonates',
      'Testing for halides',
      'Testing for sulfates',
      'Test for hydrogen',
      'Test for oxygen',
      'Test for carbon dioxide',
      'Test for chlorine',
    ],
  },

  // ============================================================================
  // PHYSICS PAPER 1 TOPICS (P1-P5)
  // ============================================================================
  {
    id: 'edexcel-combined-physics-key-concepts',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Key Concepts of Physics',
    description: 'Units, scalars and vectors',
    icon: '📏',
    color: 'bg-blue-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // Topic 1: Key Concepts of Physics
      'SI units',
      'Scalar quantities',
      'Vector quantities',
      'Distance and displacement',
      'Speed and velocity',
      'Contact forces',
      'Non-contact forces',
      'Gravity',
      'Weight equation (W = mg)',
      'Resultant forces',
      'Free body diagrams',
      'Work done (W = Fs)',
      'Work done and energy transfer',
    ],
  },
  {
    id: 'edexcel-combined-physics-motion',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Motion and Forces',
    description: 'Describing motion, Newton\'s laws, and momentum',
    icon: '🏎️',
    color: 'bg-red-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // Topic 2: Motion and Forces
      'Describing motion',
      'Distance-time graphs',
      'Gradient as speed',
      'Velocity-time graphs',
      'Gradient as acceleration',
      'Area as displacement',
      'Acceleration',
      'Acceleration equation',
      'Newton\'s First Law',
      'Newton\'s Second Law (F = ma)',
      'Newton\'s Third Law',
      'Stopping distance',
      'Thinking distance',
      'Braking distance',
      'Factors affecting stopping distance',
      'Momentum (H)',
      'Conservation of momentum (H)',
      'Safety features (H)',
    ],
  },
  {
    id: 'edexcel-combined-physics-conservation',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Conservation of Energy',
    description: 'Energy stores, transfers, and efficiency',
    icon: '⚡',
    color: 'bg-yellow-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // Topic 3: Conservation of Energy
      'Energy stores',
      'Energy transfers',
      'Conservation of energy',
      'Kinetic energy (KE = \u00BDmv\u00B2)',
      'Gravitational potential energy (GPE = mgh)',
      'Elastic potential energy',
      'Power (P = E/t)',
      'Power (P = W/t)',
      'Efficiency',
      'Wasted energy',
      'Reducing energy wastage',
    ],
  },
  {
    id: 'edexcel-combined-physics-waves',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Waves',
    description: 'Wave properties and electromagnetic radiation',
    icon: '🌊',
    color: 'bg-cyan-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // Topic 4: Waves
      'Transverse waves',
      'Longitudinal waves',
      'Wave properties',
      'Amplitude',
      'Wavelength',
      'Frequency',
      'Wave speed equation (v = f\u03BB)',
      'Period',
      'Measuring wave speed',
      'Reflection',
      'Refraction',
      'Sound waves',
      'Human hearing range',
      'Electromagnetic spectrum',
      'EM wave properties',
      'Uses of EM waves',
      'Hazards of EM waves',
    ],
  },
  {
    id: 'edexcel-combined-physics-light-em',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Light and the Electromagnetic Spectrum',
    description: 'Light behaviour and applications of EM waves',
    icon: '💡',
    color: 'bg-amber-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // Topic 5: Light and the EM Spectrum
      'Reflection of light',
      'Law of reflection',
      'Refraction of light',
      'Radio waves uses',
      'Microwaves uses',
      'Infrared uses',
      'Visible light uses',
      'Ultraviolet hazards',
      'X-ray uses and hazards',
      'Gamma ray uses and hazards',
      'Comparing EM waves',
    ],
  },

  // ============================================================================
  // PHYSICS PAPER 2 TOPICS (P6-P9)
  // ============================================================================
  {
    id: 'edexcel-combined-physics-radioactivity',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Radioactivity',
    description: 'Atomic structure, radiation, and nuclear reactions',
    icon: '⚛️',
    color: 'bg-green-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 6: Radioactivity
      'Atomic structure',
      'Development of atomic model',
      'Plum pudding model',
      'Rutherford scattering',
      'Bohr model',
      'Isotopes',
      'Radioactive decay',
      'Alpha radiation',
      'Beta radiation',
      'Gamma radiation',
      'Penetrating power',
      'Ionising ability',
      'Nuclear equations',
      'Half-life',
      'Background radiation',
      'Uses of radiation',
      'Hazards of radiation',
      'Nuclear fission',
      'Nuclear fusion',
    ],
  },
  {
    id: 'edexcel-combined-physics-energy-resources',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Energy - Forces Doing Work',
    description: 'Energy resources and forces',
    icon: '🔋',
    color: 'bg-emerald-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 7: Energy - Forces Doing Work
      'Renewable energy resources',
      'Non-renewable energy resources',
      'Solar power',
      'Wind power',
      'Hydroelectric power',
      'Tidal power',
      'Wave power',
      'Geothermal energy',
      'Biomass',
      'Fossil fuels',
      'Nuclear power',
      'Advantages and disadvantages',
      'Environmental impact',
      'Hooke\'s law (F = ke)',
      'Spring constant',
      'Elastic potential energy',
      'Force-extension graphs',
    ],
  },
  {
    id: 'edexcel-combined-physics-forces-fields',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Forces and their Effects',
    description: 'Pressure, moments, and equilibrium',
    icon: '🏋️',
    color: 'bg-indigo-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 8: Forces and their Effects
      'Pressure in fluids',
      'Pressure equation (p = F/A)',
      'Atmospheric pressure',
      'Terminal velocity',
      'Forces on falling objects',
    ],
  },
  {
    id: 'edexcel-combined-physics-electricity-circuits',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Electricity and Circuits',
    description: 'Current, voltage, resistance, and circuits',
    icon: '🔌',
    color: 'bg-blue-600',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 9: Electricity and Circuits
      'Electric current',
      'Charge (Q = It)',
      'Potential difference',
      'Resistance',
      'Ohm\'s law (V = IR)',
      'I-V characteristics',
      'Resistors',
      'Filament lamps',
      'Diodes',
      'LDRs',
      'Thermistors',
      'Series circuits',
      'Parallel circuits',
      'Power (P = IV)',
      'Power (P = I\u00B2R)',
      'Energy transferred (E = Pt)',
      'Energy transferred (E = QV)',
      'AC and DC',
      'Mains electricity',
      'Three-core cable',
      'Fuses and circuit breakers',
      'National Grid',
      'Transformers (H)',
    ],
  },
  {
    id: 'edexcel-combined-physics-magnetism',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Magnetism and the Motor Effect',
    description: 'Magnets, electromagnets, and motors',
    icon: '🧲',
    color: 'bg-purple-600',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 10: Magnetism and the Motor Effect
      'Magnets and magnetic poles',
      'Magnetic fields',
      'Magnetic field lines',
      'Earth\'s magnetic field',
      'Induced magnetism',
      'Permanent magnets',
      'Electromagnets',
      'Solenoids',
      'Motor effect',
      'Fleming\'s left-hand rule',
      'Force on a wire (F = BIL) (H)',
      'Electric motors',
      'Split-ring commutator',
      'Electromagnetic induction (H)',
      'Generators (H)',
    ],
  },
  {
    id: 'edexcel-combined-physics-particle-model',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Particle Model',
    description: 'Density, states of matter, and internal energy',
    icon: '🔬',
    color: 'bg-violet-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // Topic 11: Particle Model
      'Density',
      'Density equation (\u03C1 = m/V)',
      'Measuring density',
      'Particle arrangement in states',
      'Particle motion in states',
      'Changes of state',
      'Internal energy',
      'Specific heat capacity',
      'Calculating energy (E = mc\u0394\u03B8)',
      'Specific latent heat',
      'Latent heat of fusion',
      'Latent heat of vaporisation',
      'Calculating energy (E = mL)',
      'Pressure in gases (H)',
      'Pressure and volume (H)',
    ],
  },
];

export function getEdexcelCombinedScienceTopicById(id: string): Topic | undefined {
  return edexcelCombinedScienceTopics.find((topic) => topic.id === id);
}

export function countEdexcelCombinedScienceSubtopics(): number {
  return edexcelCombinedScienceTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
