// OCR A-Level English Literature (H472) Topics
// Based on official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/english-literature-h072-h472-from-2015/

import { Topic } from '@/types';

export const ocrALevelEnglishLiteratureTopics: Topic[] = [
  // Component 01: Drama and Poetry Pre-1900
  {
    id: 'ocr-alevel-eng-lit-measure-measure',
    name: 'Measure for Measure',
    description: 'Shakespeare\'s dark comedy exploring justice, mercy, and sexual morality',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Justice and mercy',
      'Sexual morality',
      'Power and authority',
      'Appearance vs reality',
      'Religion and law',
      'Gender and sexuality',
      'The Duke\'s manipulation',
      'Angelo\'s hypocrisy',
      'Isabella\'s virtue',
      'Claudio\'s sentence',
      'Vienna\'s corruption',
      'The bed trick',
      'Problem play genre',
      'Comic resolution',
      'Jacobean context',
      'Critical interpretations',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-duchess-malfi',
    name: 'The Duchess of Malfi',
    description: 'Webster\'s Jacobean tragedy of female defiance and aristocratic corruption',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Female agency',
      'Aristocratic corruption',
      'Death and decay',
      'Madness and revenge',
      'Love and defiance',
      'Family and honour',
      'The Duchess\'s courage',
      'Ferdinand\'s obsession',
      'Bosola\'s conflict',
      'The Cardinal\'s evil',
      'Antonio\'s love',
      'Imprisonment scenes',
      'Revenge tragedy',
      'Memento mori',
      'Jacobean court',
      'Gender politics',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-doctor-faustus',
    name: 'Doctor Faustus',
    description: 'Marlowe\'s morality play exploring ambition, damnation, and Renaissance learning',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Ambition and damnation',
      'Knowledge and power',
      'Good and evil',
      'Free will and fate',
      'Renaissance humanism',
      'Religious doubt',
      'Faustus\'s bargain',
      'Mephistopheles',
      'Good and Bad Angels',
      'Helen of Troy',
      'The final hour',
      'Comic scenes',
      'Morality play form',
      'A and B texts',
      'Reformation context',
      'Tragic or damned?',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-chaucer-pardoner',
    name: 'Chaucer: The Pardoner\'s Prologue and Tale',
    description: 'Chaucer\'s satirical tale exposing religious corruption and moral hypocrisy',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Religious hypocrisy',
      'Avarice and sin',
      'Death and mortality',
      'Rhetoric and persuasion',
      'Self-revelation',
      'Irony and satire',
      'The Pardoner\'s confession',
      'The tale\'s moral',
      'The three rioters',
      'The Old Man',
      'Relics and pardons',
      'Medieval Church',
      'Exemplum form',
      'Narrator reliability',
      'Middle English features',
      'Critical approaches',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-romantic-poetry',
    name: 'Romantic Poetry',
    description: 'Selected Romantic poets exploring nature, imagination, and the self',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Nature and the sublime',
      'Imagination and creativity',
      'The self and identity',
      'Revolution and freedom',
      'Mortality and permanence',
      'The supernatural',
      'Wordsworth\'s nature',
      'Coleridge\'s imagination',
      'Blake\'s visions',
      'Shelley\'s idealism',
      'Keats\'s sensuality',
      'Byron\'s rebellion',
      'Lyrical Ballads',
      'Romantic forms',
      'Political context',
      'Critical debates',
    ],
  },
  // Component 02: Comparative and Contextual Study
  {
    id: 'ocr-alevel-eng-lit-gothic-lit',
    name: 'The Gothic',
    description: 'Gothic literature from its origins to contemporary manifestations',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Fear and horror',
      'The supernatural',
      'Transgression and taboo',
      'The double and doppelgänger',
      'Female Gothic',
      'Psychological terror',
      'Gothic settings',
      'Gothic villains',
      'Damsels and heroines',
      'Frankenstein',
      'Dracula',
      'The Castle of Otranto',
      'Genre conventions',
      'Historical context',
      'Gothic revival',
      'Contemporary Gothic',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-dystopia',
    name: 'Dystopia',
    description: 'Dystopian literature exploring totalitarianism and social critique',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Totalitarian control',
      'Individual vs society',
      'Language and thought',
      'Technology and surveillance',
      'Human nature',
      'Warning and prophecy',
      '1984 - Orwell',
      'Brave New World - Huxley',
      'The Handmaid\'s Tale - Atwood',
      'Never Let Me Go - Ishiguro',
      'Utopia vs dystopia',
      'Political contexts',
      'Genre conventions',
      'Contemporary relevance',
      'Satirical elements',
      'Critical perspectives',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-women-writing',
    name: 'Women in Literature',
    description: 'Female experience and representation across literary periods',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Female voice and agency',
      'Marriage and society',
      'Education and opportunity',
      'Sexuality and desire',
      'Motherhood and family',
      'Work and independence',
      'Jane Eyre',
      'The Yellow Wallpaper',
      'A Room of One\'s Own',
      'The Bell Jar',
      'Wide Sargasso Sea',
      'Historical context',
      'Feminist criticism',
      'Female Gothic',
      'Domestic fiction',
      'Contemporary voices',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-american-lit',
    name: 'American Literature 1880-1940',
    description: 'American literary development from realism through modernism',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'The American Dream',
      'Identity and self',
      'Race and slavery',
      'Class and wealth',
      'Gender and society',
      'Modernity and change',
      'The Great Gatsby',
      'The Grapes of Wrath',
      'Their Eyes Were Watching God',
      'Death of a Salesman',
      'American realism',
      'The Jazz Age',
      'The Depression',
      'Modernist experiment',
      'Regional voices',
      'Critical approaches',
    ],
  },
  // Component 03: Literature Post-1900 (NEA)
  {
    id: 'ocr-alevel-eng-lit-post-1900',
    name: 'Literature Post-1900',
    description: 'Twentieth and twenty-first century literature for independent study',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Modernism',
      'Postmodernism',
      'Post-colonial literature',
      'Contemporary fiction',
      'Drama since 1900',
      'Poetry since 1900',
      'Narrative technique',
      'Form and experiment',
      'Context and meaning',
      'Critical approaches',
      'Choosing texts',
      'Research methods',
      'Close reading',
      'Creative response option',
      'Essay structure',
      'Academic writing',
    ],
  },
  {
    id: 'ocr-alevel-eng-lit-nea-ocr',
    name: 'NEA: Close Reading or Re-creative Writing',
    description: 'Independent study through close reading analysis or creative response',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Close reading task',
      'Re-creative writing task',
      'Text selection',
      'Commentary writing',
      'Critical analysis',
      'Creative transformation',
      'AO1: Response',
      'AO2: Methods',
      'AO3: Context',
      'AO4: Connections',
      'Word limits',
      'Research integration',
      'Draft development',
      'Teacher guidance',
      'Moderation process',
      'Academic integrity',
    ],
  },
];

export function getOCRALevelEnglishLiteratureTopicById(id: string): Topic | undefined {
  return ocrALevelEnglishLiteratureTopics.find((topic) => topic.id === id);
}
