// AQA A-Level Business (7132) Topics
// Based on the official AQA specification
// Reference: https://www.aqa.org.uk/subjects/business/a-level/business-7132/specification
// Paper 1: Business 1 (33.3%) - Topics 3.1-3.6
// Paper 2: Business 2 (33.3%) - Topics 3.7-3.10
// Paper 3: Business 3 (33.3%) - Synoptic, all topics

import { Topic } from '@/types';

export const aqaALevelBusinessTopics: Topic[] = [
  // ============================================================================
  // SECTION 3.1: WHAT IS BUSINESS?
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-what-is-business',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'What is Business?',
    description: 'Understanding business purpose, forms, objectives, and stakeholders',
    icon: '🏢',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.1.1 Understanding the nature and purpose of business
      'Purpose of business activity',
      'Mission statements',
      'Corporate objectives',
      'Aims vs objectives',
      'Profit motive',
      'Non-profit objectives',
      'Social enterprises',
      'Adding value',
      'Creating value for customers',
      'Primary sector',
      'Secondary sector',
      'Tertiary sector',
      'Quaternary sector',
      'Business activity and wealth creation',
      // 3.1.2 Understanding different business forms
      'Sole traders',
      'Advantages of sole traders',
      'Disadvantages of sole traders',
      'Partnerships',
      'Partnership agreements',
      'Limited liability partnerships (LLP)',
      'Private limited companies (Ltd)',
      'Public limited companies (PLC)',
      'Share capital',
      'Shareholders',
      'Dividends',
      'Limited liability',
      'Unlimited liability',
      'Incorporation',
      'Articles of Association',
      'Franchise businesses',
      'Franchisors and franchisees',
      'Social enterprises',
      'Cooperatives',
      'Mutual organisations',
      'Not-for-profit organisations',
      'Charities',
      // 3.1.3 Understanding business objectives
      'Corporate objectives',
      'Functional objectives',
      'Hierarchy of objectives',
      'SMART objectives',
      'Profit maximisation',
      'Revenue maximisation',
      'Sales maximisation',
      'Market share objectives',
      'Cost minimisation',
      'Survival objectives',
      'Growth objectives',
      'Corporate social responsibility (CSR)',
      'Ethical objectives',
      'Environmental objectives',
      'Triple bottom line',
      // 3.1.4 Stakeholders
      'Internal stakeholders',
      'External stakeholders',
      'Shareholders as stakeholders',
      'Employees as stakeholders',
      'Customers as stakeholders',
      'Suppliers as stakeholders',
      'Local community as stakeholders',
      'Government as stakeholders',
      'Pressure groups',
      'Stakeholder conflict',
      'Stakeholder mapping',
      'Mendelow\'s stakeholder matrix',
      'Balancing stakeholder interests',
    ],
  },

  // ============================================================================
  // SECTION 3.2: MANAGERS, LEADERSHIP AND DECISION MAKING
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-managers-leadership',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managers, Leadership and Decision Making',
    description: 'Management styles, leadership theories, and decision-making processes',
    icon: '👔',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.2.1 Understanding management and leadership
      'Managers vs leaders',
      'Functions of management',
      'Planning function',
      'Organising function',
      'Directing function',
      'Controlling function',
      'Coordinating function',
      'Management roles (Mintzberg)',
      'Interpersonal roles',
      'Informational roles',
      'Decisional roles',
      // Leadership styles
      'Autocratic leadership',
      'Democratic leadership',
      'Paternalistic leadership',
      'Laissez-faire leadership',
      'Authoritarian leadership',
      'Situational leadership',
      'Transformational leadership',
      'Transactional leadership',
      'Factors affecting leadership style',
      'Blake Mouton grid',
      'Tannenbaum Schmidt continuum',
      // Effectiveness
      'Effective leadership characteristics',
      'Emotional intelligence in leadership',
      'Adapting leadership style',
      // 3.2.2 Understanding management decision making
      'Decision making process',
      'Scientific decision making',
      'Intuitive decision making',
      'Strategic decisions',
      'Tactical decisions',
      'Operational decisions',
      'Data-driven decisions',
      'Risk vs uncertainty',
      'Opportunity cost in decisions',
      // Decision making tools
      'Decision trees',
      'Expected values',
      'Net gains',
      'Probability in decisions',
      'Limitations of decision trees',
      // Influences on decision making
      'Mission and objectives influence',
      'Ethics in decision making',
      'External environment influence',
      'Resource constraints',
      'Stakeholder influence on decisions',
      // 3.2.3 Understanding the role and importance of stakeholders
      'Stakeholder influence on decisions',
      'Stakeholder communication',
      'Managing stakeholder expectations',
      'Stakeholder engagement strategies',
    ],
  },

  // ============================================================================
  // SECTION 3.3: DECISION MAKING TO IMPROVE MARKETING PERFORMANCE
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-marketing',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Marketing Management',
    description: 'Marketing objectives, market research, segmentation, and marketing mix',
    icon: '📊',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.3.1 Setting marketing objectives
      'Marketing objectives',
      'Sales volume objectives',
      'Sales value objectives',
      'Market share objectives',
      'Market size',
      'Market growth',
      'Brand loyalty objectives',
      'Brand awareness',
      'Internal influences on marketing objectives',
      'External influences on marketing objectives',
      // 3.3.2 Understanding markets and customers
      'Mass markets',
      'Niche markets',
      'Market segmentation',
      'Demographic segmentation',
      'Geographic segmentation',
      'Psychographic segmentation',
      'Behavioural segmentation',
      'Income segmentation',
      'Benefits of segmentation',
      'Target markets',
      'Market positioning',
      'Market mapping',
      'Competitive positioning',
      'Unique selling proposition (USP)',
      // 3.3.3 Market research
      'Primary research',
      'Secondary research',
      'Quantitative research',
      'Qualitative research',
      'Surveys and questionnaires',
      'Focus groups',
      'Interviews',
      'Observation',
      'Test marketing',
      'Sampling methods',
      'Random sampling',
      'Stratified sampling',
      'Quota sampling',
      'Market research data interpretation',
      'Correlation analysis',
      'Confidence intervals',
      'Extrapolation',
      'Limitations of market research',
      // Technology and market research
      'Big data in marketing',
      'Social media analytics',
      'Customer databases',
      // 3.3.4 Making marketing decisions: segmentation, targeting, positioning
      'STP process',
      'Targeting strategies',
      'Undifferentiated marketing',
      'Differentiated marketing',
      'Concentrated marketing',
      'Positioning strategies',
      'Repositioning',
      'Perceptual mapping',
      // 3.3.5 Making marketing decisions: using the marketing mix
      // Product
      'Product decisions',
      'Product design',
      'Product features and benefits',
      'Product differentiation',
      'Product portfolio',
      'Boston Matrix',
      'Stars products',
      'Cash cows',
      'Question marks',
      'Dogs products',
      'Product life cycle',
      'Introduction stage',
      'Growth stage',
      'Maturity stage',
      'Decline stage',
      'Extension strategies',
      'New product development',
      'Branding',
      'Brand building',
      'Brand extension',
      'Own-label brands',
      // Price
      'Pricing decisions',
      'Cost-plus pricing',
      'Price skimming',
      'Penetration pricing',
      'Competitive pricing',
      'Psychological pricing',
      'Dynamic pricing',
      'Price elasticity of demand',
      'Calculating PED',
      'Interpreting PED',
      'PED and revenue',
      'Income elasticity of demand',
      'Calculating YED',
      'Interpreting YED',
      // Promotion
      'Promotion decisions',
      'Above-the-line promotion',
      'Below-the-line promotion',
      'Advertising',
      'Sales promotion',
      'Public relations (PR)',
      'Sponsorship',
      'Direct marketing',
      'Digital marketing',
      'Social media marketing',
      'Viral marketing',
      'Promotional mix',
      'Integrated marketing communications',
      'Branding and promotion',
      // Place (Distribution)
      'Place decisions',
      'Distribution channels',
      'Direct distribution',
      'Indirect distribution',
      'Retailers',
      'Wholesalers',
      'Agents',
      'Multi-channel distribution',
      'E-commerce',
      'M-commerce',
      'Physical distribution',
      // 3.3.6 Using digital marketing and e-commerce
      'Digital marketing strategies',
      'Search engine optimisation (SEO)',
      'Pay-per-click advertising (PPC)',
      'Content marketing',
      'Email marketing',
      'Influencer marketing',
      'E-commerce benefits',
      'E-commerce challenges',
      'Online vs offline marketing',
    ],
  },

  // ============================================================================
  // SECTION 3.4: DECISION MAKING TO IMPROVE OPERATIONAL PERFORMANCE
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-operations',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Operational Management',
    description: 'Operations objectives, efficiency, quality, and supply chain management',
    icon: '⚙️',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.4.1 Setting operational objectives
      'Operations objectives',
      'Cost objectives',
      'Unit costs',
      'Quality objectives',
      'Speed and flexibility objectives',
      'Dependability objectives',
      'Environmental objectives in operations',
      'Added value through operations',
      'Internal influences on operations objectives',
      'External influences on operations objectives',
      // 3.4.2 Analysing operational performance
      'Labour productivity',
      'Calculating labour productivity',
      'Improving labour productivity',
      'Capital productivity',
      'Unit costs calculation',
      'Capacity',
      'Capacity utilisation',
      'Calculating capacity utilisation',
      'Under-utilisation',
      'Over-utilisation',
      'Improving capacity utilisation',
      'Outsourcing',
      'Subcontracting',
      // 3.4.3 Making operational decisions to improve efficiency
      'Efficiency vs effectiveness',
      'Lean production',
      'Just-in-time (JIT)',
      'Advantages of JIT',
      'Disadvantages of JIT',
      'Kaizen (continuous improvement)',
      'Total Quality Management (TQM)',
      'Cell production',
      'Time-based management',
      'Simultaneous engineering',
      'Critical path analysis',
      'Network diagrams',
      'Earliest start times (EST)',
      'Latest finish times (LFT)',
      'Float time',
      'Critical path',
      'Benefits of CPA',
      'Limitations of CPA',
      // 3.4.4 Making operational decisions to improve quality
      'Quality management',
      'Quality control',
      'Quality assurance',
      'Quality standards',
      'ISO 9001',
      'Quality circles',
      'Zero defects',
      'Benchmarking',
      'Cost of quality',
      'Cost of poor quality',
      'Customer satisfaction and quality',
      // 3.4.5 Making operational decisions to improve flexibility and speed
      'Operational flexibility',
      'Volume flexibility',
      'Product flexibility',
      'Delivery flexibility',
      'Mix flexibility',
      'Flexible workforce',
      'Multi-skilling',
      'Flexible working hours',
      'Speed of response',
      'Lead times',
      'Reducing lead times',
      // 3.4.6 Inventory management
      'Inventory management',
      'Buffer stocks',
      'Lead time',
      'Re-order level',
      'Re-order quantity',
      'Economic order quantity',
      'Just-in-time inventory',
      'Waste minimisation',
      // 3.4.7 Supply chain management
      'Supply chain',
      'Supplier relationships',
      'Supplier selection',
      'Supplier appraisal',
      'Vertical integration',
      'Backward vertical integration',
      'Forward vertical integration',
      'Outsourcing decisions',
      'Offshoring',
      'Reshoring',
      'Procurement',
      'Logistics',
      'Supply chain efficiency',
      'Supply chain risks',
    ],
  },

  // ============================================================================
  // SECTION 3.5: DECISION MAKING TO IMPROVE FINANCIAL PERFORMANCE
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-finance',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Financial Management',
    description: 'Financial objectives, budgets, cash flow, profitability, and financial strategies',
    icon: '💰',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.5.1 Setting financial objectives
      'Financial objectives',
      'Revenue objectives',
      'Costs objectives',
      'Profit objectives',
      'Cash flow objectives',
      'Return on investment objectives',
      'Capital structure objectives',
      'Internal influences on financial objectives',
      'External influences on financial objectives',
      // 3.5.2 Analysing financial performance
      // Budgets
      'Budgets',
      'Types of budgets',
      'Income budgets',
      'Expenditure budgets',
      'Profit budgets',
      'Setting budgets',
      'Historical budgeting',
      'Zero-based budgeting',
      'Variance analysis',
      'Favourable variances',
      'Adverse variances',
      'Causes of variances',
      'Responding to variances',
      'Benefits of budgeting',
      'Limitations of budgeting',
      // Cash flow
      'Cash flow',
      'Cash flow vs profit',
      'Cash flow forecasts',
      'Cash inflows',
      'Cash outflows',
      'Net cash flow',
      'Opening balance',
      'Closing balance',
      'Cash flow problems',
      'Causes of cash flow problems',
      'Improving cash flow',
      // Break-even
      'Break-even analysis',
      'Fixed costs',
      'Variable costs',
      'Semi-variable costs',
      'Total costs',
      'Total revenue',
      'Contribution',
      'Contribution per unit',
      'Break-even point',
      'Calculating break-even',
      'Break-even charts',
      'Margin of safety',
      'Target profit output',
      'Benefits of break-even analysis',
      'Limitations of break-even analysis',
      // Profitability ratios
      'Profit',
      'Gross profit',
      'Operating profit',
      'Net profit',
      'Profit margins',
      'Gross profit margin',
      'Operating profit margin',
      'Net profit margin',
      'Profit for the year',
      'Return on capital employed (ROCE)',
      'Calculating ROCE',
      'Interpreting ROCE',
      // 3.5.3 Sources of finance
      'Internal sources of finance',
      'Retained profit',
      'Sale of assets',
      'Working capital management',
      'External sources of finance',
      'Share capital',
      'Loan capital',
      'Bank loans',
      'Bank overdrafts',
      'Mortgages',
      'Debentures',
      'Venture capital',
      'Business angels',
      'Crowdfunding',
      'Trade credit',
      'Hire purchase',
      'Leasing',
      'Government grants',
      'Short-term vs long-term finance',
      'Factors affecting choice of finance',
      // 3.5.4 Improving profitability and financial performance
      'Improving profitability',
      'Increasing revenue',
      'Reducing costs',
      'Cost cutting strategies',
      'Financial efficiency',
      'Working capital management',
      'Receivables management',
      'Payables management',
      'Inventory management',
      // Investment appraisal
      'Investment appraisal',
      'Payback period',
      'Calculating payback',
      'Average rate of return (ARR)',
      'Calculating ARR',
      'Net present value (NPV)',
      'Calculating NPV',
      'Discount factors',
      'Time value of money',
      'Comparing investment appraisal methods',
      'Qualitative factors in investment decisions',
    ],
  },

  // ============================================================================
  // SECTION 3.6: DECISION MAKING TO IMPROVE HUMAN RESOURCE PERFORMANCE
  // Assessed in Paper 1 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-human-resources',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Human Resource Management',
    description: 'HR objectives, workforce planning, motivation, and employer-employee relations',
    icon: '👥',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 3.6.1 Setting HR objectives
      'HR objectives',
      'Employee engagement objectives',
      'Talent development objectives',
      'Training objectives',
      'Diversity objectives',
      'Alignment of values objectives',
      'Labour cost objectives',
      'Labour productivity objectives',
      'Internal influences on HR objectives',
      'External influences on HR objectives',
      // 3.6.2 Analysing HR performance
      'Labour productivity',
      'Labour turnover',
      'Calculating labour turnover',
      'Causes of labour turnover',
      'Costs of labour turnover',
      'Reducing labour turnover',
      'Retention rates',
      'Absenteeism',
      'Calculating absenteeism',
      'Causes of absenteeism',
      'Costs of absenteeism',
      'Labour costs per unit',
      // 3.6.3 Making HR decisions: improving organisational design
      'Organisational design',
      'Organisational structure',
      'Hierarchy',
      'Span of control',
      'Chain of command',
      'Levels of hierarchy',
      'Tall structures',
      'Flat structures',
      'Centralisation',
      'Decentralisation',
      'Advantages of centralisation',
      'Advantages of decentralisation',
      'Delegation',
      'Empowerment',
      'Matrix structures',
      'Functional structures',
      'Product-based structures',
      'Regional structures',
      'Flexible organisations',
      'Delayering',
      'Organisational culture',
      'Types of organisational culture',
      'Changing organisational culture',
      // 3.6.4 Making HR decisions: improving motivation and engagement
      // Motivation theory
      'Motivation',
      'Taylor\'s Scientific Management',
      'Time and motion studies',
      'Piece rate pay',
      'Mayo\'s Human Relations',
      'Hawthorne studies',
      'Maslow\'s Hierarchy of Needs',
      'Physiological needs',
      'Safety needs',
      'Social needs',
      'Esteem needs',
      'Self-actualisation',
      'Herzberg\'s Two Factor Theory',
      'Motivators',
      'Hygiene factors',
      'Job enrichment',
      'Job enlargement',
      'Job rotation',
      // Financial motivation methods
      'Financial motivation',
      'Wages',
      'Salaries',
      'Piece rate',
      'Commission',
      'Performance-related pay',
      'Profit sharing',
      'Share ownership schemes',
      'Fringe benefits',
      'Bonuses',
      // Non-financial motivation
      'Non-financial motivation',
      'Job design',
      'Job enrichment',
      'Job rotation',
      'Job enlargement',
      'Empowerment',
      'Team working',
      'Flexible working',
      'Recognition and praise',
      'Career development',
      // 3.6.5 Making HR decisions: improving employer-employee relations
      'Employer-employee relations',
      'Trade unions',
      'Functions of trade unions',
      'Collective bargaining',
      'Works councils',
      'Employee representation',
      'Industrial action',
      'Strikes',
      'Work to rule',
      'Overtime bans',
      'Go slow',
      'ACAS',
      'Arbitration',
      'Conciliation',
      'Mediation',
      'Individual bargaining',
      'Employee involvement',
      'Employee consultation',
      // 3.6.6 Making HR decisions: workforce planning
      'Workforce planning',
      'Labour demand',
      'Labour supply',
      'Recruitment',
      'Internal recruitment',
      'External recruitment',
      'Job descriptions',
      'Person specifications',
      'Selection methods',
      'Interviews',
      'Assessment centres',
      'Psychometric testing',
      'Training',
      'Induction training',
      'On-the-job training',
      'Off-the-job training',
      'Apprenticeships',
      'Development',
      'Appraisals',
      'Performance management',
      'Redundancy',
      'Dismissal',
      'Employment law',
    ],
  },

  // ============================================================================
  // SECTION 3.7: ANALYSING THE STRATEGIC POSITION OF A BUSINESS
  // Assessed in Paper 2 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-strategic-position',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Analysing Strategic Position',
    description: 'Strategic analysis, SWOT, PESTLE, and competitive environment',
    icon: '🔍',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.7.1 Mission, corporate objectives and strategy
      'Mission',
      'Mission statements',
      'Purpose of mission statements',
      'Corporate objectives',
      'Strategic objectives',
      'Strategy',
      'Corporate strategy',
      'Functional strategy',
      'Strategy and tactics',
      'Long-term vs short-term objectives',
      // 3.7.2 Analysing internal position: financial ratio analysis
      'Ratio analysis',
      'Profitability ratios',
      'Gross profit margin',
      'Operating profit margin',
      'Net profit margin',
      'Return on capital employed',
      'Liquidity ratios',
      'Current ratio',
      'Acid test ratio',
      'Gearing ratio',
      'Debt to equity ratio',
      'Interest cover',
      'Efficiency ratios',
      'Receivables days',
      'Payables days',
      'Inventory turnover',
      'Limitations of ratio analysis',
      'Interpreting ratios',
      'Inter-firm comparison',
      'Trend analysis',
      // 3.7.3 Analysing internal position: human resources
      'HR data analysis',
      'Labour productivity trends',
      'Labour turnover analysis',
      'Absenteeism analysis',
      'Staff costs analysis',
      'Skills audit',
      'Workforce planning data',
      // 3.7.4 Analysing internal position: overall performance
      'Core competencies',
      'Distinctive capabilities',
      'Competitive advantage sources',
      'Value chain analysis',
      'Primary activities',
      'Support activities',
      'Kaplan and Norton Balanced Scorecard',
      'Financial perspective',
      'Customer perspective',
      'Internal business perspective',
      'Learning and growth perspective',
      'Benchmarking performance',
      'Performance indicators',
      'Key Performance Indicators (KPIs)',
      // 3.7.5 Analysing external environment: political and legal
      'PESTLE analysis',
      'Political factors',
      'Government policy impact',
      'Taxation impact',
      'Government spending impact',
      'Political stability',
      'Legal factors',
      'Employment law impact',
      'Consumer protection law',
      'Health and safety law',
      'Competition law',
      'Environmental law',
      'Data protection',
      'GDPR',
      // Economic factors
      'Economic factors',
      'Economic growth',
      'GDP impact on business',
      'Business cycle',
      'Boom',
      'Recession',
      'Recovery',
      'Slump',
      'Interest rates',
      'Impact of interest rate changes',
      'Inflation',
      'Impact of inflation on business',
      'Exchange rates',
      'Impact of exchange rate changes',
      'Unemployment',
      'Consumer confidence',
      'Business confidence',
      // Social factors
      'Social factors',
      'Demographic changes',
      'Ageing population',
      'Migration',
      'Urbanisation',
      'Changing consumer lifestyles',
      'Consumer attitudes',
      'Environmental awareness',
      'Ethical consumerism',
      'Health consciousness',
      // Technological factors
      'Technological factors',
      'Disruptive technology',
      'Automation',
      'Artificial intelligence impact',
      'E-commerce growth',
      'Digital transformation',
      'Research and development',
      'Innovation impact',
      // Environmental factors
      'Environmental factors',
      'Climate change impact',
      'Sustainability',
      'Carbon footprint',
      'Environmental regulations',
      'Green business practices',
      'Waste management',
      'Resource depletion',
      // Competitive environment
      'Competitive environment',
      'Porter\'s Five Forces',
      'Threat of new entrants',
      'Barriers to entry',
      'Bargaining power of suppliers',
      'Bargaining power of buyers',
      'Threat of substitutes',
      'Competitive rivalry',
      'Industry attractiveness',
      'Competitor analysis',
      // 3.7.6 Strategic positioning
      'SWOT analysis',
      'Strengths',
      'Weaknesses',
      'Opportunities',
      'Threats',
      'Using SWOT strategically',
      'Converting weaknesses to strengths',
      'Exploiting opportunities',
      'Mitigating threats',
    ],
  },

  // ============================================================================
  // SECTION 3.8: CHOOSING STRATEGIC DIRECTION
  // Assessed in Paper 2 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-strategic-direction',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Choosing Strategic Direction',
    description: 'Strategic options, growth strategies, and competitive positioning',
    icon: '🧭',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.8.1 Choosing which markets to compete in
      'Market selection',
      'Ansoff\'s Matrix',
      'Market penetration',
      'Market development',
      'Product development',
      'Diversification',
      'Related diversification',
      'Unrelated diversification',
      'Risk and Ansoff\'s Matrix',
      // 3.8.2 Choosing how to compete
      'Porter\'s Generic Strategies',
      'Cost leadership',
      'Achieving cost leadership',
      'Differentiation strategy',
      'Achieving differentiation',
      'Focus strategy',
      'Cost focus',
      'Differentiation focus',
      'Stuck in the middle',
      'Competitive advantage',
      'Sustainable competitive advantage',
      // Strategic positioning
      'Strategic positioning',
      'Market leader strategy',
      'Market challenger strategy',
      'Market follower strategy',
      'Market nicher strategy',
      'First mover advantage',
      'Fast follower strategy',
      // Innovation strategy
      'Innovation as strategy',
      'Product innovation',
      'Process innovation',
      'Disruptive innovation',
      'Blue ocean strategy',
      'Red ocean markets',
      // International markets
      'Internationalisation',
      'Reasons for internationalisation',
      'Risks of internationalisation',
      'Market entry strategies',
      'Exporting',
      'Licensing',
      'Franchising internationally',
      'Joint ventures',
      'Foreign direct investment (FDI)',
      'Wholly owned subsidiaries',
      'Global vs multi-domestic strategy',
      'Globalisation impact',
    ],
  },

  // ============================================================================
  // SECTION 3.9: STRATEGIC METHODS: HOW TO PURSUE STRATEGIES
  // Assessed in Paper 2 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-strategic-methods',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Strategic Methods',
    description: 'Growth methods, mergers, acquisitions, and retrenchment strategies',
    icon: '🚀',
    color: 'bg-red-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.9.1 Assessing a change in scale
      'Business growth',
      'Organic growth',
      'Advantages of organic growth',
      'Disadvantages of organic growth',
      'Inorganic growth',
      'Mergers',
      'Acquisitions (takeovers)',
      'Hostile takeovers',
      'Friendly takeovers',
      'Advantages of mergers and acquisitions',
      'Disadvantages of mergers and acquisitions',
      'Integration types',
      'Horizontal integration',
      'Vertical integration',
      'Forward vertical integration',
      'Backward vertical integration',
      'Conglomerate integration',
      'Synergy',
      'Economies of scale from growth',
      'Diseconomies of scale',
      // Retrenchment
      'Retrenchment',
      'Reasons for retrenchment',
      'Divestment',
      'Demergers',
      'Management buyouts (MBOs)',
      'Asset stripping',
      'Downsizing',
      'Delayering',
      // 3.9.2 Assessing innovation
      'Innovation',
      'Product innovation',
      'Process innovation',
      'Incremental innovation',
      'Radical innovation',
      'Research and development (R&D)',
      'R&D investment decisions',
      'Innovation and competitiveness',
      'First mover advantage',
      'Patents',
      'Intellectual property',
      'Protecting innovation',
      'Innovation culture',
      'Intrapreneurship',
      // 3.9.3 Assessing internationalisation
      'Reasons for trading internationally',
      'Offshoring',
      'Reshoring',
      'Global sourcing',
      'International marketing',
      'Adapting vs standardising products',
      'Glocal strategies',
      'Barriers to international trade',
      'Tariffs',
      'Quotas',
      'Non-tariff barriers',
      'Exchange rate management',
      'Cultural differences',
      'Managing international operations',
      // 3.9.4 Digital technology and business strategy
      'Digital transformation',
      'E-commerce strategies',
      'Big data analytics',
      'Data-driven decision making',
      'Artificial intelligence in business',
      'Automation strategies',
      'Internet of Things (IoT)',
      'Cybersecurity',
      'Digital marketing strategies',
      'Platform business models',
      'Disruptive digital business models',
    ],
  },

  // ============================================================================
  // SECTION 3.10: MANAGING STRATEGIC CHANGE
  // Assessed in Paper 2 and Paper 3
  // ============================================================================
  {
    id: 'aqa-alevel-bus-managing-change',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managing Strategic Change',
    description: 'Change management, organisational culture, and strategic implementation',
    icon: '🔄',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.10.1 Managing change
      'Strategic change',
      'Causes of change',
      'Internal causes of change',
      'External causes of change',
      'Types of change',
      'Incremental change',
      'Disruptive change',
      'Transformational change',
      // Change management models
      'Lewin\'s Force Field Analysis',
      'Driving forces',
      'Restraining forces',
      'Using Force Field Analysis',
      'Kotter\'s 8 Steps of Change',
      'Creating urgency',
      'Building coalitions',
      'Communicating vision',
      'Empowering action',
      'Creating short-term wins',
      'Consolidating gains',
      'Anchoring change',
      // 3.10.2 Managing organisational culture
      'Organisational culture',
      'Handy\'s cultural types',
      'Power culture',
      'Role culture',
      'Task culture',
      'Person culture',
      'Importance of organisational culture',
      'Culture and performance',
      'Reasons for changing culture',
      'Difficulties in changing culture',
      'Strategies for changing culture',
      // 3.10.3 Managing strategic implementation
      'Strategic implementation',
      'Strategy and structure alignment',
      'Leadership and change',
      'Change leadership styles',
      'Communication during change',
      'Overcoming resistance to change',
      'Employee involvement in change',
      'Training for change',
      'Resource allocation',
      'Network analysis for change',
      // Problems with change
      'Barriers to change',
      'Resistance to change',
      'Sources of resistance',
      'Managing resistance',
      'Change and motivation',
      'Change fatigue',
      'Pace of change',
      // 3.10.4 Problems with strategy and why strategies fail
      'Strategy failure',
      'Reasons for strategy failure',
      'Poor implementation',
      'Lack of resources',
      'External environment changes',
      'Internal resistance',
      'Competitor response',
      'Strategic drift',
      'Avoiding strategic drift',
      'Contingency planning',
      'Scenario planning',
      'Strategic flexibility',
      // Corporate social responsibility
      'Corporate social responsibility (CSR)',
      'Carroll\'s CSR pyramid',
      'Economic responsibilities',
      'Legal responsibilities',
      'Ethical responsibilities',
      'Philanthropic responsibilities',
      'Stakeholder approach to CSR',
      'Business ethics',
      'Ethical decision making',
      'Environmental sustainability',
      'Triple bottom line',
      'Social enterprise strategy',
    ],
  },
];

// Helper function to get topic by ID
export function getAQAALevelBusinessTopicById(id: string): Topic | undefined {
  return aqaALevelBusinessTopics.find(topic => topic.id === id);
}
