// Edexcel (Pearson) A-Level Business (9BS0) Topics
// Based on the official Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/business-2015.html
// Paper 1: Marketing, People and Global Businesses (35%) - Themes 1 & 4
// Paper 2: Business Activities, Decisions and Strategy (35%) - Themes 2 & 3
// Paper 3: Investigating Business in a Competitive Environment (30%) - All Themes (Synoptic)

import { Topic } from '@/types';

export const edexcelALevelBusinessTopics: Topic[] = [
  // ============================================================================
  // THEME 1: MARKETING AND PEOPLE
  // Assessed in Paper 1 and Paper 3
  // ============================================================================

  // 1.1 Meeting customer needs
  {
    id: 'edexcel-alevel-bus-meeting-customer-needs',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Meeting Customer Needs',
    description: 'Understanding markets, customer needs, and market research',
    icon: '🎯',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 1.1.1 The market
      'Mass markets',
      'Characteristics of mass markets',
      'Niche markets',
      'Characteristics of niche markets',
      'Mass vs niche market advantages',
      'Mass vs niche market disadvantages',
      'Market size',
      'Measuring market size by value',
      'Measuring market size by volume',
      'Market share',
      'Calculating market share',
      'Dynamic markets',
      'How markets change',
      'Online retailing impact',
      'Innovation and markets',
      'Adapting to market change',
      'Competition and market structure',
      'Risk and uncertainty in markets',
      // 1.1.2 Market research
      'Purpose of market research',
      'Primary research',
      'Surveys',
      'Questionnaires',
      'Interviews',
      'Focus groups',
      'Observation',
      'Test marketing',
      'Secondary research',
      'Internal secondary data',
      'External secondary data',
      'Qualitative research',
      'Quantitative research',
      'Market research data limitations',
      'Sampling',
      'Random sampling',
      'Stratified sampling',
      'Quota sampling',
      'Sample size',
      'Sampling bias',
      // 1.1.3 Market positioning
      'Market positioning',
      'Market mapping',
      'Creating market maps',
      'Using market maps',
      'Gaps in the market',
      'Competitive advantage through positioning',
      'Repositioning products',
    ],
  },

  // 1.2 The market
  {
    id: 'edexcel-alevel-bus-market-analysis',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Market Analysis',
    description: 'Demand, supply, price elasticity, and market conditions',
    icon: '📈',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 1.2.1 Demand
      'Demand',
      'Factors affecting demand',
      'Price and demand relationship',
      'Income and demand',
      'Substitutes and demand',
      'Complements and demand',
      'Fashion and tastes',
      'Demographics and demand',
      'Seasonality',
      // 1.2.2 Supply
      'Supply',
      'Factors affecting supply',
      'Costs of production',
      'Technology and supply',
      'Number of competitors',
      'Commodity prices',
      // 1.2.3 Markets
      'Markets and equilibrium',
      'Price mechanism',
      'Supply and demand interaction',
      'Market clearing price',
      'Surplus and shortage',
      // 1.2.4 Price elasticity of demand
      'Price elasticity of demand (PED)',
      'Calculating PED',
      'Interpreting PED values',
      'Elastic demand',
      'Inelastic demand',
      'Unit elastic demand',
      'Perfectly elastic demand',
      'Perfectly inelastic demand',
      'Factors affecting PED',
      'Necessity vs luxury',
      'Availability of substitutes',
      'Proportion of income',
      'Time period',
      'PED and total revenue',
      'Using PED in pricing decisions',
      // 1.2.5 Income elasticity of demand
      'Income elasticity of demand (YED)',
      'Calculating YED',
      'Interpreting YED values',
      'Normal goods',
      'Inferior goods',
      'Luxury goods',
      'Necessities',
      'Using YED in business planning',
    ],
  },

  // 1.3 Marketing mix and strategy
  {
    id: 'edexcel-alevel-bus-marketing-mix',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Marketing Mix and Strategy',
    description: 'Product, price, promotion, place, and people decisions',
    icon: '🎨',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 1.3.1 Product/service design
      'Product design',
      'Design mix',
      'Function in design',
      'Aesthetics in design',
      'Cost in design',
      'Design and competitiveness',
      'Social trends and design',
      'Environmental concerns in design',
      'Resource depletion',
      'Ethical sourcing',
      // 1.3.2 Branding and promotion
      'Branding',
      'Types of branding',
      'Manufacturer brands',
      'Own-label brands',
      'Benefits of strong branding',
      'Brand building',
      'Brand loyalty',
      'Promotion strategies',
      'Promotional mix',
      'Advertising',
      'Sales promotion',
      'Public relations',
      'Sponsorship',
      'Direct marketing',
      'Social media marketing',
      'Viral marketing',
      'Guerrilla marketing',
      'Changes in promotion spending',
      'Technology and promotion',
      // 1.3.3 Pricing strategies
      'Pricing strategies',
      'Price skimming',
      'Penetration pricing',
      'Competitive pricing',
      'Cost-plus pricing',
      'Predatory pricing',
      'Psychological pricing',
      'Dynamic pricing',
      'Loss leader pricing',
      'Factors affecting pricing decisions',
      'Pricing and product life cycle',
      'Pricing and PED',
      // 1.3.4 Distribution
      'Distribution channels',
      'Direct to consumer',
      'Retailers',
      'Wholesalers',
      'Agents and brokers',
      'Multi-channel distribution',
      'E-commerce distribution',
      'M-commerce',
      'Physical distribution',
      'Choosing distribution channels',
      // 1.3.5 Marketing strategy
      'Marketing strategy',
      'Product portfolio analysis',
      'Boston Matrix',
      'Stars',
      'Cash cows',
      'Question marks',
      'Dogs',
      'Product life cycle',
      'Introduction stage',
      'Growth stage',
      'Maturity stage',
      'Decline stage',
      'Extension strategies',
      'Marketing mix balance',
      'Integrated marketing',
    ],
  },

  // 1.4 Managing people
  {
    id: 'edexcel-alevel-bus-managing-people',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managing People',
    description: 'Workforce planning, motivation, and leadership',
    icon: '👥',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 1.4.1 Approaches to staffing
      'Flexible workforce',
      'Multi-skilling',
      'Part-time employment',
      'Temporary employment',
      'Flexible hours',
      'Home working',
      'Remote working',
      'Outsourcing',
      'Dismissal',
      'Redundancy',
      'Employer-employee relationships',
      // 1.4.2 Recruitment, selection and training
      'Recruitment process',
      'Internal recruitment',
      'External recruitment',
      'Job descriptions',
      'Person specifications',
      'Selection process',
      'Application forms',
      'CVs',
      'Interviews',
      'Assessment centres',
      'Psychometric testing',
      'Training',
      'Induction training',
      'On-the-job training',
      'Off-the-job training',
      'Benefits of training',
      'Costs of training',
      // 1.4.3 Organisational design
      'Organisational structures',
      'Hierarchy',
      'Span of control',
      'Chain of command',
      'Levels of hierarchy',
      'Tall structures',
      'Flat structures',
      'Centralisation',
      'Decentralisation',
      'Delegation',
      'Authority and responsibility',
      'Matrix structures',
      'Functional structures',
      // 1.4.4 Motivation in theory
      'Motivation theories',
      'Taylor\'s Scientific Management',
      'Piece rate',
      'Time and motion',
      'Mayo\'s Human Relations',
      'Hawthorne Effect',
      'Maslow\'s Hierarchy of Needs',
      'Physiological needs',
      'Safety needs',
      'Social needs',
      'Esteem needs',
      'Self-actualisation',
      'Herzberg\'s Two Factor Theory',
      'Motivators',
      'Hygiene factors',
      // 1.4.5 Motivation in practice
      'Financial incentives',
      'Piecework',
      'Commission',
      'Bonus schemes',
      'Profit sharing',
      'Performance-related pay',
      'Share ownership',
      'Non-financial motivation',
      'Delegation',
      'Consultation',
      'Empowerment',
      'Team working',
      'Flexible working',
      'Job enrichment',
      'Job enlargement',
      'Job rotation',
      // 1.4.6 Leadership
      'Leadership',
      'Leadership vs management',
      'Leadership styles',
      'Autocratic leadership',
      'Democratic leadership',
      'Paternalistic leadership',
      'Laissez-faire leadership',
      'Situational leadership',
      'Factors affecting leadership style',
    ],
  },

  // 1.5 Entrepreneurs and leaders
  {
    id: 'edexcel-alevel-bus-entrepreneurs',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Entrepreneurs and Leaders',
    description: 'Role of entrepreneurs, intrapreneurs, and business leadership',
    icon: '💡',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 1.5.1 Role of an entrepreneur
      'Entrepreneurship',
      'Role of entrepreneurs',
      'Creating and setting up a business',
      'Running and expanding a business',
      'Entrepreneurial motives',
      'Profit motive',
      'Independence',
      'Personal satisfaction',
      'Making a difference',
      'Barriers to entrepreneurship',
      'Entrepreneur characteristics',
      'Risk-taking',
      'Creativity',
      'Determination',
      'Vision',
      // 1.5.2 Entrepreneurial motives and characteristics
      'Business objectives',
      'Financial objectives',
      'Survival',
      'Profit maximisation',
      'Revenue maximisation',
      'Non-financial objectives',
      'Social objectives',
      'Market share',
      'Customer satisfaction',
      'Employee welfare',
      // 1.5.3 Business objectives
      'Measuring success',
      'Profit as success measure',
      'Market share as success measure',
      'Customer satisfaction measures',
      'Social impact measurement',
      // 1.5.4 Forms of business
      'Sole traders',
      'Partnerships',
      'Private limited companies (Ltd)',
      'Public limited companies (PLC)',
      'Not-for-profit organisations',
      'Social enterprises',
      'Unlimited liability',
      'Limited liability',
      'Sources of finance for start-ups',
      // 1.5.5 Business choices
      'Opportunity cost',
      'Trade-offs',
      'Stakeholder impact of decisions',
    ],
  },

  // ============================================================================
  // THEME 2: MANAGING BUSINESS ACTIVITIES
  // Assessed in Paper 2 and Paper 3
  // ============================================================================

  // 2.1 Raising finance
  {
    id: 'edexcel-alevel-bus-raising-finance',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Raising Finance',
    description: 'Sources of finance and financial planning',
    icon: '💳',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 2.1.1 Internal finance
      'Internal sources of finance',
      'Retained profit',
      'Sale of assets',
      'Reducing working capital',
      // 2.1.2 External finance
      'External sources of finance',
      'Family and friends',
      'Banks',
      'Bank loans',
      'Bank overdrafts',
      'Peer-to-peer funding',
      'Crowdfunding',
      'Business angels',
      'Venture capital',
      'Share capital',
      'Floating on stock exchange',
      'Trade credit',
      'Leasing',
      'Hire purchase',
      'Grants',
      // 2.1.3 Liability
      'Limited liability',
      'Unlimited liability',
      'Implications of liability',
      // 2.1.4 Planning
      'Business planning',
      'Business plans',
      'Components of business plan',
      'Purpose of business plans',
      'Cash flow forecasting',
      'Sales forecasting',
      'Difficulties of forecasting',
    ],
  },

  // 2.2 Financial planning
  {
    id: 'edexcel-alevel-bus-financial-planning',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Financial Planning',
    description: 'Sales forecasting, budgeting, and break-even analysis',
    icon: '📋',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 2.2.1 Sales forecasting
      'Sales forecasting',
      'Methods of sales forecasting',
      'Time series analysis',
      'Moving averages',
      'Extrapolation',
      'Market research for forecasting',
      'Factors affecting sales forecasts',
      'Consumer trends',
      'Economic variables',
      'Actions of competitors',
      'Difficulties of forecasting',
      // 2.2.2 Sales, revenue and costs
      'Sales volume',
      'Sales revenue',
      'Calculating revenue',
      'Fixed costs',
      'Variable costs',
      'Total costs',
      'Average costs',
      'Cost classification',
      'Direct costs',
      'Indirect costs',
      // 2.2.3 Break-even
      'Break-even analysis',
      'Break-even point',
      'Calculating break-even',
      'Break-even formula',
      'Contribution',
      'Contribution per unit',
      'Break-even charts',
      'Margin of safety',
      'Target output',
      'Benefits of break-even',
      'Limitations of break-even',
      // 2.2.4 Budgets
      'Budgets',
      'Purpose of budgets',
      'Types of budgets',
      'Revenue budgets',
      'Cost budgets',
      'Profit budgets',
      'Setting budgets',
      'Historical budgeting',
      'Zero-based budgeting',
      'Variance analysis',
      'Favourable variance',
      'Adverse variance',
      'Responding to variances',
      'Difficulties of budgeting',
    ],
  },

  // 2.3 Managing finance
  {
    id: 'edexcel-alevel-bus-managing-finance',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managing Finance',
    description: 'Profit, liquidity, and business failure',
    icon: '💰',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 2.3.1 Profit
      'Profit',
      'Gross profit',
      'Calculating gross profit',
      'Operating profit',
      'Calculating operating profit',
      'Net profit',
      'Profit margins',
      'Gross profit margin',
      'Operating profit margin',
      'Net profit margin',
      'Profit vs cash',
      'Profit vs revenue',
      'Improving profitability',
      'Increasing revenue',
      'Reducing costs',
      // 2.3.2 Liquidity
      'Liquidity',
      'Cash flow',
      'Cash vs profit',
      'Working capital',
      'Current assets',
      'Current liabilities',
      'Working capital cycle',
      'Cash flow forecasts',
      'Cash inflows',
      'Cash outflows',
      'Net cash flow',
      'Opening balance',
      'Closing balance',
      'Cash flow problems',
      'Causes of cash flow problems',
      'Improving cash flow',
      'Speeding up receivables',
      'Delaying payables',
      'Managing inventory',
      'Short-term borrowing',
      // 2.3.3 Business failure
      'Business failure',
      'Causes of business failure',
      'Internal causes of failure',
      'External causes of failure',
      'Cash flow and failure',
      'Inadequate finance',
      'Poor financial management',
      'Over-expansion',
      'External shocks',
    ],
  },

  // 2.4 Resource management
  {
    id: 'edexcel-alevel-bus-resource-management',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Resource Management',
    description: 'Production, efficiency, and quality management',
    icon: '⚙️',
    color: 'bg-red-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 2.4.1 Production, productivity and efficiency
      'Production',
      'Job production',
      'Batch production',
      'Flow production',
      'Cell production',
      'Choosing production method',
      'Productivity',
      'Labour productivity',
      'Calculating labour productivity',
      'Capital productivity',
      'Improving productivity',
      'Efficiency',
      'Capacity',
      'Capacity utilisation',
      'Calculating capacity utilisation',
      'Under-utilisation',
      'Full capacity',
      'Improving capacity utilisation',
      // 2.4.2 Lean production
      'Lean production',
      'Just-in-time (JIT)',
      'JIT benefits',
      'JIT drawbacks',
      'Kanban',
      'Kaizen',
      'Continuous improvement',
      'Waste reduction',
      'Time-based management',
      'Lean production and competitiveness',
      // 2.4.3 Quality management
      'Quality',
      'Quality control',
      'Quality assurance',
      'Total Quality Management (TQM)',
      'Quality circles',
      'Zero defects',
      'Quality standards',
      'ISO standards',
      'Cost of quality',
      'Cost of poor quality',
      'Quality and competitiveness',
      // 2.4.4 Inventory management
      'Stock/inventory',
      'Stock control',
      'Buffer stocks',
      'Lead time',
      'Re-order level',
      'Re-order quantity',
      'Stock control charts',
      'Just-in-time stock',
      'Economic order quantity',
      'Costs of holding stock',
      'Costs of stockouts',
    ],
  },

  // 2.5 External influences
  {
    id: 'edexcel-alevel-bus-external-influences',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'External Influences',
    description: 'Economic, legal, and competitive factors',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 2.5.1 Economic influences
      'Economic environment',
      'Inflation',
      'Effects of inflation on business',
      'Interest rates',
      'Effects of interest rate changes',
      'Exchange rates',
      'Effects of exchange rate changes',
      'Strong pound impact',
      'Weak pound impact',
      'Taxation',
      'Corporation tax',
      'VAT',
      'Income tax effects',
      'Government spending',
      'Economic growth',
      'GDP and business',
      'Recession',
      'Recovery',
      'Business cycle',
      'Unemployment',
      // 2.5.2 Legislation
      'Consumer protection',
      'Consumer Rights Act',
      'Sale of Goods Act',
      'Consumer Contracts Regulations',
      'Employment law',
      'Minimum wage',
      'Working Time Regulations',
      'Equality Act',
      'Health and safety',
      'Environmental legislation',
      'Data protection',
      'GDPR',
      // 2.5.3 The competitive environment
      'Competition',
      'Direct competition',
      'Indirect competition',
      'Market structures',
      'Perfect competition',
      'Monopolistic competition',
      'Oligopoly',
      'Monopoly',
      'Barriers to entry',
      'Competitive advantage',
      'Price competition',
      'Non-price competition',
      'Responding to competition',
    ],
  },

  // ============================================================================
  // THEME 3: BUSINESS DECISIONS AND STRATEGY
  // Assessed in Paper 2 and Paper 3
  // ============================================================================

  // 3.1 Business objectives and strategy
  {
    id: 'edexcel-alevel-bus-objectives-strategy',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Business Objectives and Strategy',
    description: 'Corporate objectives, strategy, and stakeholders',
    icon: '🎯',
    color: 'bg-violet-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.1.1 Corporate objectives
      'Corporate objectives',
      'Types of corporate objectives',
      'Profit objectives',
      'Growth objectives',
      'Survival objectives',
      'Cash flow objectives',
      'Social and ethical objectives',
      'Hierarchy of objectives',
      'SMART objectives',
      'Internal influences on objectives',
      'External influences on objectives',
      // 3.1.2 Strategy
      'Business strategy',
      'Mission statements',
      'Corporate aims',
      'Strategic objectives',
      'Functional objectives',
      'Strategy vs tactics',
      'Strategic decision making',
      // 3.1.3 Ansoff's Matrix
      'Ansoff\'s Matrix',
      'Market penetration',
      'Market development',
      'Product development',
      'Diversification',
      'Related diversification',
      'Unrelated diversification',
      'Risk and Ansoff\'s Matrix',
      // 3.1.4 Porter's Generic Strategies
      'Porter\'s Generic Strategies',
      'Cost leadership',
      'Differentiation',
      'Focus strategy',
      'Cost focus',
      'Differentiation focus',
      'Stuck in the middle',
      // 3.1.5 SWOT analysis
      'SWOT analysis',
      'Strengths',
      'Weaknesses',
      'Opportunities',
      'Threats',
      'Using SWOT analysis',
      // 3.1.6 Impact of external influences
      'PESTLE analysis',
      'Political factors',
      'Economic factors',
      'Social factors',
      'Technological factors',
      'Legal factors',
      'Environmental factors',
    ],
  },

  // 3.2 Business growth
  {
    id: 'edexcel-alevel-bus-business-growth',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Business Growth',
    description: 'Organic and inorganic growth strategies',
    icon: '📈',
    color: 'bg-lime-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.2.1 Growth
      'Business growth',
      'Reasons for growth',
      'Economies of scale',
      'Internal economies',
      'Technical economies',
      'Purchasing economies',
      'Managerial economies',
      'Financial economies',
      'Marketing economies',
      'Risk-bearing economies',
      'External economies',
      'Diseconomies of scale',
      'Optimum size',
      // 3.2.2 Organic growth
      'Organic growth',
      'Methods of organic growth',
      'Advantages of organic growth',
      'Disadvantages of organic growth',
      // 3.2.3 Inorganic growth
      'Inorganic growth',
      'Mergers',
      'Acquisitions',
      'Takeovers',
      'Horizontal integration',
      'Vertical integration',
      'Forward integration',
      'Backward integration',
      'Conglomerate integration',
      'Advantages of inorganic growth',
      'Disadvantages of inorganic growth',
      'Synergy',
      // 3.2.4 Reasons for staying small
      'Small businesses',
      'Reasons for staying small',
      'Niche markets',
      'Flexibility',
      'Personal service',
      'Owner preferences',
    ],
  },

  // 3.3 Decision-making techniques
  {
    id: 'edexcel-alevel-bus-decision-making',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Decision-Making Techniques',
    description: 'Quantitative tools for business decisions',
    icon: '🧮',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.3.1 Quantitative sales forecasting
      'Quantitative forecasting',
      'Time series analysis',
      'Identifying trends',
      'Moving averages',
      'Calculating moving averages',
      'Extrapolation',
      'Using extrapolation',
      'Limitations of extrapolation',
      'Seasonal variations',
      'Cyclical variations',
      'Random variations',
      'Correlation',
      'Positive correlation',
      'Negative correlation',
      'No correlation',
      'Confidence levels',
      // 3.3.2 Investment appraisal
      'Investment appraisal',
      'Payback period',
      'Calculating payback',
      'Advantages of payback',
      'Disadvantages of payback',
      'Average rate of return (ARR)',
      'Calculating ARR',
      'Interpreting ARR',
      'Advantages of ARR',
      'Disadvantages of ARR',
      'Net present value (NPV)',
      'Calculating NPV',
      'Discount factors',
      'Time value of money',
      'Interpreting NPV',
      'Advantages of NPV',
      'Disadvantages of NPV',
      'Comparing investment appraisal methods',
      'Non-financial factors in investment',
      // 3.3.3 Decision trees
      'Decision trees',
      'Drawing decision trees',
      'Probability',
      'Expected values',
      'Calculating expected value',
      'Net gains',
      'Decision nodes',
      'Chance nodes',
      'Using decision trees',
      'Benefits of decision trees',
      'Limitations of decision trees',
      // 3.3.4 Critical path analysis
      'Critical path analysis',
      'Network diagrams',
      'Activities',
      'Dependencies',
      'Earliest start time (EST)',
      'Latest finish time (LFT)',
      'Critical path',
      'Float time',
      'Free float',
      'Total float',
      'Benefits of CPA',
      'Limitations of CPA',
    ],
  },

  // 3.4 Influences on business decisions
  {
    id: 'edexcel-alevel-bus-influences-decisions',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Influences on Business Decisions',
    description: 'Corporate culture, stakeholders, and ethics',
    icon: '⚖️',
    color: 'bg-amber-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.4.1 Corporate influences
      'Corporate culture',
      'Types of culture',
      'Power culture',
      'Role culture',
      'Task culture',
      'Person culture',
      'Strong vs weak culture',
      'Culture and performance',
      'Changing culture',
      'Corporate governance',
      'Board of directors',
      'Shareholders',
      'Accountability',
      // 3.4.2 Shareholder vs stakeholder concept
      'Shareholders',
      'Shareholder value',
      'Stakeholders',
      'Stakeholder groups',
      'Stakeholder conflict',
      'Balancing interests',
      'Shareholder vs stakeholder approach',
      // 3.4.3 Business ethics
      'Business ethics',
      'Ethical behaviour',
      'Ethical decision making',
      'Trade-offs in ethics',
      'Pay and conditions',
      'Environmental considerations',
      'Sourcing decisions',
      'Ethical marketing',
      // 3.4.4 Corporate Social Responsibility
      'Corporate Social Responsibility (CSR)',
      'CSR activities',
      'Environmental responsibility',
      'Social responsibility',
      'Economic responsibility',
      'Benefits of CSR',
      'Costs of CSR',
      'CSR vs profit',
    ],
  },

  // 3.5 Assessing competitiveness
  {
    id: 'edexcel-alevel-bus-competitiveness',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Assessing Competitiveness',
    description: 'Financial analysis and competitive position',
    icon: '🏆',
    color: 'bg-rose-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.5.1 Financial statements
      'Financial statements',
      'Statement of comprehensive income',
      'Revenue',
      'Cost of sales',
      'Gross profit',
      'Operating expenses',
      'Operating profit',
      'Interest',
      'Tax',
      'Profit for year',
      'Statement of financial position',
      'Non-current assets',
      'Current assets',
      'Receivables',
      'Cash',
      'Inventory',
      'Current liabilities',
      'Payables',
      'Non-current liabilities',
      'Share capital',
      'Retained earnings',
      'Total equity',
      // 3.5.2 Financial ratios
      'Ratio analysis',
      'Profitability ratios',
      'Gross profit margin',
      'Operating profit margin',
      'Return on capital employed',
      'Liquidity ratios',
      'Current ratio',
      'Acid test ratio',
      'Gearing ratio',
      'Efficiency ratios',
      'Payables days',
      'Receivables days',
      'Inventory turnover',
      'Interpreting ratios',
      'Limitations of ratios',
      // 3.5.3 Human resources data
      'HR data',
      'Labour productivity',
      'Labour turnover',
      'Labour costs',
      'Absenteeism',
      'Using HR data',
    ],
  },

  // 3.6 Managing change
  {
    id: 'edexcel-alevel-bus-managing-change',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Managing Change',
    description: 'Causes of change and change management',
    icon: '🔄',
    color: 'bg-fuchsia-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      // 3.6.1 Causes and effects of change
      'Business change',
      'Internal causes of change',
      'External causes of change',
      'Effects of change',
      'Change and uncertainty',
      'Planned change',
      'Emergent change',
      // 3.6.2 Key factors in change
      'Organisational culture and change',
      'Resistance to change',
      'Overcoming resistance',
      'Communication during change',
      'Leadership during change',
      'Size of organisation',
      'Time and speed of change',
      'Flexibility and change',
      'Managing information',
      // 3.6.3 Scenario planning
      'Scenario planning',
      'Purpose of scenarios',
      'Creating scenarios',
      'Best case',
      'Worst case',
      'Most likely case',
      'Using scenarios',
      'Benefits of scenario planning',
      'Limitations of scenarios',
    ],
  },

  // ============================================================================
  // THEME 4: GLOBAL BUSINESS
  // Assessed in Paper 1 and Paper 3
  // ============================================================================

  // 4.1 Globalisation
  {
    id: 'edexcel-alevel-bus-globalisation',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Globalisation',
    description: 'Global markets and international trade',
    icon: '🌐',
    color: 'bg-sky-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 4.1.1 Growing economies
      'Globalisation',
      'Causes of globalisation',
      'Benefits of globalisation',
      'Drawbacks of globalisation',
      'Emerging economies',
      'BRIC economies',
      'Characteristics of emerging markets',
      'Opportunities in emerging markets',
      'Threats from emerging markets',
      // 4.1.2 International trade and business growth
      'International trade',
      'Exports',
      'Imports',
      'Balance of trade',
      'Free trade',
      'Protectionism',
      'Tariffs',
      'Quotas',
      'Non-tariff barriers',
      'Trade agreements',
      'Trading blocs',
      'EU single market',
      'WTO',
      // 4.1.3 Factors contributing to increased globalisation
      'Technology and globalisation',
      'Internet',
      'Communication technology',
      'Transport improvements',
      'Containerisation',
      'Trade liberalisation',
      'Political change',
      'Deregulation',
    ],
  },

  // 4.2 Global markets and business expansion
  {
    id: 'edexcel-alevel-bus-global-expansion',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Global Markets and Business Expansion',
    description: 'International marketing and market entry strategies',
    icon: '🚀',
    color: 'bg-purple-600',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 4.2.1 Conditions that prompt trade
      'Push factors',
      'Pull factors',
      'Saturated domestic markets',
      'New market opportunities',
      'Economies of scale globally',
      'Risk spreading',
      // 4.2.2 Assessment of country
      'Assessing countries',
      'Market attractiveness',
      'Infrastructure',
      'Income levels',
      'Political stability',
      'Legal framework',
      'Cultural factors',
      'Ease of doing business',
      'Exchange rate stability',
      // 4.2.3 Global competitiveness
      'Global competitiveness',
      'Cost competitiveness',
      'Quality competitiveness',
      'Innovation',
      'Marketing globally',
      'Global supply chains',
      // 4.2.4 Methods of expansion
      'Market entry strategies',
      'Exporting',
      'Licensing',
      'Franchising internationally',
      'Joint ventures',
      'Wholly owned subsidiaries',
      'Foreign direct investment',
      'Mergers and acquisitions internationally',
      'Strategic alliances',
      'Offshoring',
      'Outsourcing internationally',
    ],
  },

  // 4.3 Global marketing
  {
    id: 'edexcel-alevel-bus-global-marketing',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Global Marketing',
    description: 'Global branding and marketing strategies',
    icon: '📣',
    color: 'bg-red-600',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 4.3.1 Global marketing strategy
      'Global marketing',
      'Standardisation vs adaptation',
      'Global standardisation',
      'Local adaptation',
      'Glocal strategy',
      'Benefits of standardisation',
      'Benefits of adaptation',
      // 4.3.2 Global branding
      'Global brands',
      'Building global brands',
      'Brand recognition worldwide',
      'Global brand value',
      'Cultural considerations',
      'Adapting brands locally',
      // 4.3.3 Global niche markets
      'Global niche markets',
      'Identifying global niches',
      'Serving global niches',
      'Cultural differences',
      'Language barriers',
      'Marketing across cultures',
    ],
  },

  // 4.4 Global industries and companies (multinational corporations)
  {
    id: 'edexcel-alevel-bus-mncs',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'business',
    name: 'Multinational Corporations',
    description: 'Impact and influence of MNCs',
    icon: '🏭',
    color: 'bg-slate-600',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      // 4.4.1 Impact of MNCs
      'Multinational corporations (MNCs)',
      'Characteristics of MNCs',
      'Reasons for becoming MNC',
      'Benefits to host country',
      'Employment creation',
      'Tax revenue',
      'Technology transfer',
      'Infrastructure development',
      'Drawbacks to host country',
      'Exploitation concerns',
      'Profit repatriation',
      'Environmental damage',
      'Cultural impact',
      // 4.4.2 Ethics and MNCs
      'Ethical issues in MNCs',
      'Pay and conditions globally',
      'Child labour',
      'Working conditions',
      'Environmental responsibility',
      'Tax avoidance',
      'Transfer pricing',
      'Bribery and corruption',
      // 4.4.3 Controlling MNCs
      'Regulation of MNCs',
      'National regulations',
      'International agreements',
      'Pressure groups',
      'Consumer pressure',
      'Corporate Social Responsibility globally',
    ],
  },
];

// Helper function to get topic by ID
export function getEdexcelALevelBusinessTopicById(id: string): Topic | undefined {
  return edexcelALevelBusinessTopics.find(topic => topic.id === id);
}
