// AQA GCSE Psychology Topics (8182)
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/psychology/gcse/psychology-8182

import { Topic } from '@/types';

export const aqaGCSEPsychologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: COGNITION AND BEHAVIOUR (50%)
  // ============================================================================
  {
    id: 'aqa-gcse-psych-memory',
    name: 'Memory',
    description: 'How memories are encoded, stored and retrieved, and why we forget',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Processes of memory
      'Encoding in memory',
      'Storage in memory',
      'Retrieval from memory',
      // Structure of memory
      'The multi-store model of memory',
      'Sensory register: duration and capacity',
      'Short-term memory: duration and capacity',
      'Long-term memory: duration and capacity',
      'Coding in STM (acoustic)',
      'Coding in LTM (semantic)',
      'Strengths of multi-store model',
      'Weaknesses of multi-store model',
      // Episodic and semantic memory
      'Episodic memory definition',
      'Characteristics of episodic memory',
      'Semantic memory definition',
      'Characteristics of semantic memory',
      'Differences between episodic and semantic',
      // Primacy and recency effects
      "Murdock's serial position curve study",
      'Primacy effect',
      'Recency effect',
      'Evidence for STM and LTM',
      // Forgetting
      'Retroactive interference',
      'Proactive interference',
      'Effects of similarity on interference',
      // Eyewitness testimony
      'Factors affecting eyewitness testimony',
      "Bartlett's War of the Ghosts study",
      'Reconstructive memory',
      'Role of schemas in memory',
      'Effect of leading questions',
    ],
  },
  {
    id: 'aqa-gcse-psych-perception',
    name: 'Perception',
    description: 'How we interpret sensory information and factors affecting perception',
    icon: '👁️',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Sensation and perception
      'Difference between sensation and perception',
      'Visual perception',
      'Visual illusions',
      // Depth cues
      'Monocular depth cues',
      'Height in plane',
      'Relative size',
      'Occlusion',
      'Linear perspective',
      'Binocular depth cues',
      'Retinal disparity',
      'Convergence',
      // Visual constancies
      'Size constancy',
      'Shape constancy',
      'Colour constancy',
      // Visual illusions
      'Ambiguous figures',
      'Necker cube',
      'Rubin vase',
      'Distortion illusions',
      'Ponzo illusion',
      'Müller-Lyer illusion',
      'Fictional illusions',
      'Kanizsa triangle',
      // Theories of illusions
      'Gregory: perception as hypothesis',
      'Misapplied depth cues',
      'Gibson: direct perception',
      // Factors affecting perception
      'Perceptual set',
      'Definition of perceptual set',
      'Bruner and Minturn study',
      'Effect of motivation on perception',
      'Gilchrist and Nesberg study',
      'Effect of expectation on perception',
      'Effect of emotion on perception',
      'Effect of culture on perception',
    ],
  },
  {
    id: 'aqa-gcse-psych-development',
    name: 'Development',
    description: 'Early brain development, learning, and the nature-nurture debate',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Early brain development
      'Early brain development',
      'Nature vs nurture in brain development',
      'Role of genetics in brain development',
      'Role of environment in brain development',
      // Piaget's theory
      "Piaget's stages of development",
      'Sensorimotor stage (0-2 years)',
      'Pre-operational stage (2-7 years)',
      'Concrete operational stage (7-11 years)',
      'Formal operational stage (11+ years)',
      'Object permanence',
      'Conservation tasks',
      'Egocentrism',
      'Three mountains task',
      "Evaluation of Piaget's theory",
      // Dweck's mindset theory
      "Dweck's mindset theory of learning",
      'Fixed mindset',
      'Growth mindset',
      'Effect of mindset on learning',
      'Effect of praise on mindset',
      'Person praise vs process praise',
      "Evaluation of Dweck's theory",
      // Willingham's learning theory
      "Willingham's learning theory",
      'Knowledge is prerequisite for skill',
      'Memory is residue of thought',
      'Practice makes permanent',
      'Importance of factual knowledge',
      'Limitations of learning styles',
      'Application to education',
      "Evaluation of Willingham's theory",
      // Learning styles
      'Learning styles debate',
      'Visual learners',
      'Auditory learners',
      'Kinaesthetic learners',
      'Problems with learning styles',
    ],
  },
  {
    id: 'aqa-gcse-psych-research-methods-paper1',
    name: 'Research Methods',
    description: 'Methods of psychological research, including experiments and sampling',
    icon: '📊',
    color: 'bg-yellow-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Formulating hypotheses
      'Formulating hypotheses',
      'Alternative hypothesis',
      'Null hypothesis',
      'Directional hypothesis',
      'Non-directional hypothesis',
      // Variables
      'Independent variable',
      'Dependent variable',
      'Extraneous variables',
      'Operationalisation of variables',
      // Experimental designs
      'Independent groups design',
      'Repeated measures design',
      'Strengths and weaknesses of designs',
      'Order effects',
      'Counterbalancing',
      'Participant variables',
      // Sampling
      'Target population',
      'Sample',
      'Generalisability',
      'Random sampling',
      'Opportunity sampling',
      'Systematic sampling',
      'Stratified sampling',
      'Strengths and weaknesses of sampling',
      // Types of research
      'Laboratory experiments',
      'Field experiments',
      'Natural experiments',
      'Questionnaires',
      'Interviews',
      'Structured interviews',
      'Unstructured interviews',
      'Observations',
      'Covert and overt observations',
      'Participant and non-participant',
      'Case studies',
      // Issues in research
      'Demand characteristics',
      'Investigator effects',
      'Ethics in research',
      'Informed consent',
      'Deception',
      'Protection from harm',
      'Right to withdraw',
      'Confidentiality',
    ],
  },

  // ============================================================================
  // PAPER 2: SOCIAL CONTEXT AND BEHAVIOUR (50%)
  // ============================================================================
  {
    id: 'aqa-gcse-psych-social-influence',
    name: 'Social Influence',
    description: 'Conformity, obedience, and prosocial behaviour',
    icon: '👥',
    color: 'bg-indigo-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Conformity
      'Definition of conformity',
      "Asch's study of conformity",
      'Procedure of Asch study',
      'Findings of Asch study',
      'Factors affecting conformity',
      'Group size',
      'Anonymity',
      'Task difficulty',
      'Evaluation of Asch study',
      // Obedience
      'Definition of obedience',
      "Milgram's study of obedience",
      'Procedure of Milgram study',
      'Findings: 65% obedience',
      'Factors affecting obedience',
      'Proximity',
      'Location',
      'Uniform',
      'Evaluation of Milgram study',
      'Ethical issues in Milgram',
      // Explanations of obedience
      'Agentic state',
      'Autonomous state',
      'Legitimacy of authority',
      // Deindividuation
      'Definition of deindividuation',
      'Anonymity and deindividuation',
      'Deindividuation and aggression',
      // Bystander behaviour
      'Diffusion of responsibility',
      'Bystander effect',
      "Piliavin's subway study",
      'Procedure of subway study',
      'Findings on helping',
      'Type of victim',
      'Cost-reward model',
      'Evaluation of Piliavin',
      // Prosocial behaviour
      'Factors affecting prosocial behaviour',
      'Presence of others',
      'Characteristics of bystander',
      'Cost of helping',
    ],
  },
  {
    id: 'aqa-gcse-psych-language-thought',
    name: 'Language, Thought and Communication',
    description: 'Relationship between language and thought, and human vs animal communication',
    icon: '💬',
    color: 'bg-green-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Piaget's theory
      "Piaget's view: language depends on thought",
      'Language as tool for thought',
      'Egocentric speech',
      "Evaluation of Piaget's view",
      // Sapir-Whorf hypothesis
      'Sapir-Whorf hypothesis',
      'Linguistic relativity',
      'Strong version: linguistic determinism',
      'Weak version: linguistic relativity',
      'Evidence for Sapir-Whorf',
      'Evidence against Sapir-Whorf',
      // Human and animal communication
      'Properties of human communication',
      'Properties of animal communication',
      'Differences between human and animal',
      // Von Frisch study
      "Von Frisch's bee study",
      'Waggle dance',
      'Distance and direction signals',
      'Round dance vs waggle dance',
      'Evaluation of Von Frisch',
      // Non-verbal communication
      'Eye contact',
      'Functions of eye contact',
      'Cultural differences in eye contact',
      'Body language',
      'Open and closed posture',
      'Postural echo',
      'Personal space',
      'Factors affecting personal space',
      'Facial expressions',
      'Universal facial expressions',
      'Touch',
      'Paralinguistics',
      'Tone of voice',
      'Emphasis',
      'Volume and pace',
    ],
  },
  {
    id: 'aqa-gcse-psych-brain-neuropsychology',
    name: 'Brain and Neuropsychology',
    description: 'Structure and function of the brain and nervous system',
    icon: '🔬',
    color: 'bg-red-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Structure of nervous system
      'The nervous system',
      'Central nervous system (CNS)',
      'Brain structure',
      'Spinal cord function',
      'Peripheral nervous system (PNS)',
      // Brain structure
      'Frontal lobe',
      'Functions of frontal lobe',
      'Temporal lobe',
      'Functions of temporal lobe',
      'Parietal lobe',
      'Functions of parietal lobe',
      'Occipital lobe',
      'Functions of occipital lobe',
      'Cerebellum',
      'Functions of cerebellum',
      // Neurons
      'Structure of neurons',
      'Sensory neurons',
      'Relay neurons',
      'Motor neurons',
      'Synaptic transmission',
      'Role of neurotransmitters',
      // Hebb's theory
      "Hebb's theory of learning",
      'Neurons that fire together wire together',
      'Neural pathways',
      'Strengthening of synapses',
      'Application to learning',
      // Brain scanning
      'Methods of studying the brain',
      'CT scans',
      'PET scans',
      'fMRI scans',
      'Strengths of brain scanning',
      'Weaknesses of brain scanning',
      // Tulving's study
      "Tulving's gold memory study",
      'Episodic vs semantic memory',
      'Brain regions involved',
      'Use of PET scanning',
      'Evaluation of Tulving study',
    ],
  },
  {
    id: 'aqa-gcse-psych-psychological-problems',
    name: 'Psychological Problems',
    description: 'Mental health, depression, addiction, and their treatments',
    icon: '🩺',
    color: 'bg-orange-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Mental health
      'Definition of mental health',
      'Mental health continuum',
      'Effects of mental health problems',
      'Individual effects',
      'Social effects',
      'Economic effects',
      'Stigma around mental health',
      'Challenges of modern living',
      'Increased stress',
      'Social isolation',
      // Depression
      'Characteristics of depression',
      'Cognitive characteristics',
      'Emotional characteristics',
      'Behavioural characteristics',
      'Biological explanation',
      'Role of neurotransmitters',
      'Serotonin hypothesis',
      'Genetic factors',
      'Psychological explanation',
      'Cognitive approach',
      'Negative thinking patterns',
      "Beck's negative cognitive triad",
      // Treatment of depression
      'Drug therapy',
      'Antidepressants',
      'SSRIs',
      'How antidepressants work',
      'Strengths of drug therapy',
      'Weaknesses of drug therapy',
      'Cognitive Behavioural Therapy (CBT)',
      'How CBT works',
      'Challenging negative thoughts',
      'Strengths of CBT',
      'Weaknesses of CBT',
      // Addiction
      'Definition of addiction',
      'Physical dependence',
      'Psychological dependence',
      'Tolerance',
      'Withdrawal',
      'Characteristics of addiction',
      // Causes of addiction
      'Biological explanation',
      'Genetics and addiction',
      'Brain chemistry',
      'Dopamine reward system',
      'Psychological explanation',
      'Classical conditioning',
      'Operant conditioning',
      'Social learning',
      'Peer pressure',
      // Treatment of addiction
      'Drug therapy for addiction',
      'How it works',
      'Evaluation of drug therapy',
      'Cognitive Behavioural Therapy',
      'Functional analysis',
      'Skills training',
      'Evaluation of CBT for addiction',
      'Aversion therapy',
      'How aversion therapy works',
      'Evaluation of aversion therapy',
    ],
  },
];

export function getAQAGCSEPsychologyTopicById(id: string): Topic | undefined {
  return aqaGCSEPsychologyTopics.find((topic) => topic.id === id);
}
