// Edexcel A-Level Biology A (9BI0) Topics
// Based on the official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/biology-a-2015.html

import { Topic } from '@/types';

export const edexcelALevelBiologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1 TOPICS (1-4) - The Natural Environment and Species Survival
  // ============================================================================
  {
    id: 'lifestyle-health',
    examBoard: 'edexcel',
    name: 'Lifestyle, Health and Risk',
    description: 'Cardiovascular system, diet, and heart disease',
    icon: '❤️',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Topic 1
      'Water and its properties',
      'Hydrogen bonding',
      'Structure of carbohydrates',
      'Monosaccharides',
      'Disaccharides',
      'Polysaccharides',
      'Glycosidic bonds',
      'Testing for carbohydrates',
      'Structure of lipids',
      'Triglycerides',
      'Phospholipids',
      'Saturated and unsaturated fatty acids',
      'Roles of lipids',
      'Cardiovascular system structure',
      'Blood vessel structure',
      'Arteries',
      'Veins',
      'Capillaries',
      'Cardiac cycle',
      'Heart structure',
      'Blood pressure',
      'Atherosclerosis',
      'Risk factors for cardiovascular disease',
      'Diet and CVD',
      'Energy budgets',
      'BMI',
      'Correlation and causation',
      'Core Practical 1: Vitamin C in food',
    ],
  },
  {
    id: 'genes-health',
    examBoard: 'edexcel',
    name: 'Genes and Health',
    description: 'DNA, protein synthesis, cell membranes, and genetic diseases',
    icon: '🧬',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Topic 2
      'Gas exchange system structure',
      'Lung structure',
      'Alveoli',
      'Pulmonary ventilation',
      'Cystic fibrosis',
      'Gene mutations',
      'Cell membrane structure',
      'Fluid mosaic model',
      'Phospholipid bilayer',
      'Membrane proteins',
      'Passive transport',
      'Diffusion',
      'Facilitated diffusion',
      'Osmosis',
      'Water potential',
      'Active transport',
      'DNA structure',
      'Nucleotides',
      'Base pairing',
      'DNA replication',
      'Semi-conservative replication',
      'Genes and polypeptides',
      'Genetic code',
      'Transcription',
      'mRNA',
      'Translation',
      'tRNA',
      'Ribosomes',
      'Protein structure',
      'Primary structure',
      'Secondary structure',
      'Tertiary structure',
      'Quaternary structure',
      'Enzymes',
      'Enzyme specificity',
      'Induced fit model',
      'Factors affecting enzyme activity',
      'Enzyme inhibition',
      'Gene therapy',
      'CFTR protein',
      'Core Practical 2: Cell membrane permeability',
    ],
  },
  {
    id: 'voice-genome',
    examBoard: 'edexcel',
    name: 'Voice of the Genome',
    description: 'Cell division, development, and stem cells',
    icon: '📢',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Topic 3
      'Prokaryotic cell structure',
      'Eukaryotic cell structure',
      'Ultrastructure of organelles',
      'Nucleus',
      'Mitochondria',
      'Chloroplasts',
      'Rough endoplasmic reticulum',
      'Smooth endoplasmic reticulum',
      'Golgi apparatus',
      'Ribosomes',
      'Lysosomes',
      'Centrioles',
      'Magnification calculations',
      'Resolution',
      'Electron microscopy',
      'Cell cycle',
      'Interphase',
      'Mitosis',
      'Cytokinesis',
      'Meiosis',
      'Stages of meiosis',
      'Genetic variation from meiosis',
      'Chromosome structure',
      'Homologous chromosomes',
      'Gametogenesis',
      'Fertilisation',
      'Development',
      'Cell differentiation',
      'Gene expression',
      'Totipotency',
      'Pluripotency',
      'Stem cells',
      'Therapeutic use of stem cells',
      'Ethical issues',
      'Core Practical 3: Mitosis in root tip',
    ],
  },
  {
    id: 'biodiversity',
    examBoard: 'edexcel',
    name: 'Biodiversity and Natural Resources',
    description: 'Classification, biodiversity, plant structure, and sustainability',
    icon: '🌿',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Topic 4
      'Classification systems',
      'Binomial naming',
      'Hierarchy of taxa',
      'Three-domain system',
      'Five-kingdom system',
      'Phylogenetics',
      'Molecular phylogeny',
      'Biodiversity',
      'Species richness',
      'Genetic diversity',
      'Simpson\'s Index',
      'Sampling techniques',
      'Random sampling',
      'Systematic sampling',
      'Plant cell structure',
      'Plant tissues',
      'Xylem',
      'Phloem',
      'Sclerenchyma',
      'Cellulose structure',
      'Starch structure',
      'Drug testing',
      'Clinical trials',
      'Plant-derived drugs',
      'Sustainability',
      'Conservation',
      'Maintaining biodiversity',
      'Core Practical 4: Staining plant tissue',
    ],
  },

  // ============================================================================
  // PAPER 2 TOPICS (5-6) - Energy, Exercise and Coordination
  // ============================================================================
  {
    id: 'energy-exercise',
    examBoard: 'edexcel',
    name: 'On the Wild Side',
    description: 'Ecosystems, photosynthesis, climate change, and evolution',
    icon: '🌳',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Topic 5
      'Ecosystems',
      'Biotic factors',
      'Abiotic factors',
      'Food chains and webs',
      'Trophic levels',
      'Producers',
      'Consumers',
      'Decomposers',
      'Energy transfer',
      'Gross primary productivity',
      'Net primary productivity',
      'Photosynthesis overview',
      'Chloroplast structure',
      'Light-dependent reactions',
      'Photosystems I and II',
      'Electron transport chain',
      'Chemiosmosis',
      'Photophosphorylation',
      'Light-independent reactions',
      'Calvin cycle',
      'Carbon fixation',
      'RuBisCO',
      'Limiting factors',
      'Carbon cycle',
      'Climate change',
      'Evidence for climate change',
      'Effects of climate change',
      'Natural selection',
      'Darwin and Wallace',
      'Evidence for evolution',
      'Speciation',
      'Reproductive isolation',
      'Core Practical 9: Photosynthesis pigments',
      'Core Practical 10: Respiration rates',
    ],
  },
  {
    id: 'infection-immunity',
    examBoard: 'edexcel',
    name: 'Infection, Immunity and Forensics',
    description: 'Pathogens, immune system, forensic biology, and decomposition',
    icon: '🦠',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Topic 6
      'Forensic biology',
      'DNA profiling',
      'Gel electrophoresis',
      'PCR',
      'Decomposition',
      'Factors affecting decay',
      'Time of death estimation',
      'Microorganisms',
      'Bacteria structure',
      'Virus structure',
      'Pathogens and disease',
      'Transmission of disease',
      'Plant defences',
      'Physical defences',
      'Chemical defences',
      'Animal defences',
      'Non-specific immunity',
      'Physical barriers',
      'Inflammation',
      'Phagocytosis',
      'Specific immunity',
      'Lymphocytes',
      'T cells',
      'B cells',
      'Antibodies',
      'Antigen-antibody interaction',
      'Primary immune response',
      'Secondary immune response',
      'Vaccination',
      'Herd immunity',
      'Antibiotics',
      'Antibiotic resistance',
      'Hospital-acquired infections',
      'Core Practical 11: Bacterial growth',
    ],
  },

  // ============================================================================
  // PAPER 3 TOPICS (7-8) - General and Practical Applications in Biology
  // ============================================================================
  {
    id: 'run-for-life',
    examBoard: 'edexcel',
    name: 'Run for Your Life',
    description: 'Respiration, muscles, exercise physiology, and homeostasis',
    icon: '🏃',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Topic 7
      'Cellular respiration overview',
      'Glycolysis',
      'Link reaction',
      'Krebs cycle',
      'Oxidative phosphorylation',
      'Electron transport chain',
      'ATP synthase',
      'ATP yield',
      'Anaerobic respiration',
      'Lactate fermentation',
      'Alcoholic fermentation',
      'Respiratory substrates',
      'Respiratory quotient',
      'Muscle structure',
      'Sarcomere structure',
      'Sliding filament theory',
      'Role of ATP',
      'Role of calcium ions',
      'Tropomyosin and troponin',
      'Fast twitch fibres',
      'Slow twitch fibres',
      'Cardiac muscle',
      'Cardiac cycle',
      'ECG',
      'Heart rate control',
      'SAN and AVN',
      'Exercise physiology',
      'VO2 max',
      'Oxygen debt',
      'Homeostasis',
      'Negative feedback',
      'Thermoregulation',
      'Core Practical 12: Muscle contraction',
    ],
  },
  {
    id: 'grey-matter',
    examBoard: 'edexcel',
    name: 'Grey Matter',
    description: 'Nervous system, brain, vision, and coordination',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Topic 8
      'Nervous system overview',
      'Central nervous system',
      'Peripheral nervous system',
      'Neurone structure',
      'Sensory neurones',
      'Motor neurones',
      'Relay neurones',
      'Resting potential',
      'Action potential',
      'Depolarisation',
      'Repolarisation',
      'Refractory period',
      'Factors affecting conduction',
      'Myelination',
      'Saltatory conduction',
      'Synapse structure',
      'Synaptic transmission',
      'Neurotransmitters',
      'Acetylcholine',
      'Dopamine',
      'Effects of drugs on synapses',
      'Brain structure',
      'Cerebrum',
      'Cerebellum',
      'Medulla oblongata',
      'Hypothalamus',
      'Brain imaging',
      'fMRI',
      'CT scans',
      'Vision',
      'Eye structure',
      'Retina',
      'Rods and cones',
      'Visual processing',
      'Critical windows in development',
      'Habituation',
      'Core Practical 13: Brain structure',
      'Core Practical 14: Habituation investigation',
      // Hormonal coordination
      'Endocrine system',
      'Hormones',
      'Second messengers',
      'Control of blood glucose',
      'Insulin and glucagon',
      'Diabetes',
      'Osmoregulation',
      'Kidney structure',
      'Nephron',
      'Ultrafiltration',
      'Selective reabsorption',
      'Loop of Henle',
      'ADH',
      'Gene expression control',
      'Transcription factors',
      'Genome',
      'Proteome',
      'Core Practical 15: Plant hormones',
      'Core Practical 16: Animal responses',
    ],
  },
];

export function getEdexcelALevelBiologyTopicById(id: string): Topic | undefined {
  return edexcelALevelBiologyTopics.find((topic) => topic.id === id);
}

export function getEdexcelALevelBiologyTopicsByPaper(paper: 1 | 2 | 3): Topic[] {
  const paperName = `Paper ${paper}`;
  return edexcelALevelBiologyTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countEdexcelALevelBiologySubtopics(): number {
  return edexcelALevelBiologyTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
