// Edexcel A-Level History (9HI0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/history-2015.html

import { Topic } from '@/types';

export const edexcelALevelHistoryTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: BREADTH STUDY WITH INTERPRETATIONS
  // Most popular options
  // ============================================================================
  {
    id: 'russia-1917-91',
    name: 'Paper 1E: Russia 1917-1991: From Lenin to Yeltsin',
    description: 'Soviet history from Revolution to collapse',
    icon: '🇷🇺',
    color: 'bg-red-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Communist government
      'Establishing Communist rule',
      'October Revolution aftermath',
      'Civil War',
      'War Communism',
      'Red Terror',
      'NEP',
      'Death of Lenin',
      'Power struggle',
      'Stalin\'s victory',
      // Stalinist state
      'Stalinist economy',
      'Five Year Plans',
      'Collectivisation',
      'Terror and purges',
      'Show trials',
      'Gulag',
      'Cult of personality',
      'Social impact',
      // WWII and after
      'Great Patriotic War',
      'Post-war Stalinism',
      'Death of Stalin',
      // Khrushchev
      'De-Stalinisation',
      'Secret Speech',
      'Reforms',
      'Virgin Lands',
      'Foreign policy',
      'Fall of Khrushchev',
      // Brezhnev era
      'Brezhnev Doctrine',
      'Stagnation',
      'Dissent',
      'Afghanistan',
      // Gorbachev
      'Glasnost',
      'Perestroika',
      'Democratisation',
      'Nationalities problem',
      'End of Cold War',
      // Collapse
      'August Coup',
      'Yeltsin',
      'End of USSR',
      // Interpretations
      'Historical debates',
      'Totalitarian model',
      'Revisionism',
    ],
  },
  {
    id: 'usa-1917-96',
    name: 'Paper 1F: In Search of the American Dream 1917-96',
    description: 'America from WWI to Clinton',
    icon: '🇺🇸',
    color: 'bg-blue-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1920s America
      'WWI impact',
      'Republican governments',
      'Economic boom',
      'Mass production',
      'Consumer society',
      'Social tensions',
      'Red Scare',
      'Immigration restriction',
      'Prohibition',
      'Cultural change',
      // Depression and New Deal
      'Wall Street Crash',
      'Great Depression',
      'Hoover\'s response',
      'FDR election',
      'First New Deal',
      'Second New Deal',
      'Opposition',
      'Impact assessment',
      // WWII
      'Road to war',
      'Pearl Harbor',
      'War economy',
      'Social change',
      'Atomic bomb',
      // Post-war America
      'Cold War domestic',
      'McCarthyism',
      'Affluent society',
      'Suburban growth',
      'Conformity',
      // Civil Rights
      'Segregation',
      'Brown v Board',
      'Montgomery',
      'Sit-ins',
      'Freedom Rides',
      'Birmingham',
      'March on Washington',
      'Civil Rights Act',
      'Voting Rights Act',
      'Black Power',
      // Later period
      'Great Society',
      'Vietnam',
      'Nixon',
      'Watergate',
      'Reagan era',
      'Culture wars',
      'Clinton',
      // Interpretations
      'New Deal historiography',
      'Civil Rights debates',
    ],
  },
  {
    id: 'germany-1918-89',
    name: 'Paper 1G: Germany and West Germany 1918-1989',
    description: 'Germany from Weimar to reunification',
    icon: '🇩🇪',
    color: 'bg-gray-800',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Weimar Republic
      'Revolution 1918-19',
      'Weimar Constitution',
      'Early challenges',
      'Versailles impact',
      'Political violence',
      'Hyperinflation',
      'Stresemann era',
      'Golden years',
      'Culture',
      'Depression impact',
      // Nazi rise
      'Nazi Party',
      'Hitler',
      'Growth of support',
      'Political crisis',
      'Hitler Chancellor',
      // Nazi Germany
      'Consolidation',
      'Enabling Act',
      'Gleichschaltung',
      'Night of Long Knives',
      'Fuhrer state',
      'Terror apparatus',
      'Economic policy',
      'Social policy',
      'Women and youth',
      'Racial policy',
      'Persecution',
      'Holocaust',
      'Opposition',
      // Divided Germany
      'Occupation',
      'Cold War division',
      'Federal Republic founding',
      'Adenauer',
      'Economic miracle',
      'Political stability',
      'Ostpolitik',
      'Terrorism',
      // Reunification
      'Fall of Wall',
      'Reunification process',
      // Interpretations
      'Sonderweg',
      'Nazi historiography',
    ],
  },
  {
    id: 'britain-1918-97',
    name: 'Paper 1H: Britain Transformed 1918-97',
    description: 'Britain from WWI aftermath to Blair',
    icon: '🇬🇧',
    color: 'bg-blue-800',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Inter-war
      'Post-WWI Britain',
      'Coalition collapse',
      'First Labour government',
      'General Strike',
      'Depression',
      'National Government',
      'Appeasement',
      // WWII
      'Churchill',
      'Home Front',
      'Beveridge',
      'Plans for peace',
      // Attlee
      'Labour victory 1945',
      'Welfare State',
      'NHS',
      'Nationalisation',
      'Austerity',
      // Conservative years
      '1951 election',
      'Churchill again',
      'Eden and Suez',
      'Macmillan',
      'Affluence',
      'Social change',
      'Profumo',
      'Home',
      // Wilson/Heath
      'Wilson 1964-70',
      'Devaluation',
      'Social reforms',
      'Heath',
      'Industrial relations',
      'EEC entry',
      // Crisis and Thatcher
      'Wilson/Callaghan',
      'IMF crisis',
      'Winter of Discontent',
      'Thatcherism',
      'Economic policy',
      'Union reform',
      'Privatisation',
      'Poll Tax',
      // Major to Blair
      'Major',
      'New Labour',
      'Blair',
      'Constitutional reform',
      // Interpretations
      'Welfare state debates',
      'Thatcherism legacy',
    ],
  },
  // ============================================================================
  // PAPER 2: DEPTH STUDIES
  // Most popular options
  // ============================================================================
  {
    id: 'france-revolution',
    name: 'Paper 2C.1: France in Revolution 1774-99',
    description: 'The French Revolution from causes to Napoleon',
    icon: '🇫🇷',
    color: 'bg-blue-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Ancien Regime
      'France under Louis XVI',
      'Social structure',
      'Financial crisis',
      'Enlightenment ideas',
      'American Revolution impact',
      // Revolution begins
      'Estates-General',
      'National Assembly',
      'Tennis Court Oath',
      'Storming of Bastille',
      'Great Fear',
      'August Decrees',
      'Declaration of Rights',
      'March on Versailles',
      // Constitutional monarchy
      'Civil Constitution Clergy',
      'Flight to Varennes',
      '1791 Constitution',
      'Political clubs',
      'Jacobins',
      'Girondins',
      // Republic
      'War with Austria',
      'Fall of monarchy',
      'September Massacres',
      'Convention',
      'Execution of Louis XVI',
      // Terror
      'Revolutionary War',
      'Vendee',
      'Committee of Public Safety',
      'Robespierre',
      'Terror',
      'Dechristianisation',
      'Thermidor',
      // Directory
      'Directory government',
      'Political instability',
      'Rise of Napoleon',
      'Coup of Brumaire',
      // Primary sources
      'Revolutionary documents',
      'Speeches',
      'Images',
    ],
  },
  {
    id: 'russia-revolution',
    name: 'Paper 2C.2: Russia in Revolution 1894-1924',
    description: 'Russia from Nicholas II to death of Lenin',
    icon: '☭',
    color: 'bg-red-800',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Tsarist Russia
      'Nicholas II',
      'Autocracy',
      'Russian society',
      'Opposition groups',
      'Marxism in Russia',
      'Bolsheviks and Mensheviks',
      // 1905 Revolution
      'Russo-Japanese War',
      'Bloody Sunday',
      '1905 Revolution',
      'October Manifesto',
      'Moscow uprising',
      'Dumas',
      'Stolypin',
      // WWI
      'Russia enters war',
      'Military failures',
      'Economic crisis',
      'Political crisis',
      'Rasputin',
      // February Revolution
      'Bread riots',
      'Army mutiny',
      'Abdication',
      'Provisional Government',
      'Soviet Order No 1',
      'Dual power',
      // Road to October
      'Lenin\'s return',
      'April Theses',
      'July Days',
      'Kornilov Affair',
      'Bolshevik preparations',
      // October Revolution
      'Seizure of power',
      'Second Congress Soviets',
      'First decrees',
      // Civil War
      'Constituent Assembly',
      'Brest-Litovsk',
      'Civil War',
      'War Communism',
      'Terror',
      // Lenin\'s legacy
      'NEP',
      'Party structure',
      'Death of Lenin',
      // Primary sources
      'Party documents',
      'Memoirs',
      'Statistical evidence',
    ],
  },
  {
    id: 'maos-china',
    name: 'Paper 2E.1: Mao\'s China 1949-76',
    description: 'China under Mao Zedong',
    icon: '🇨🇳',
    color: 'bg-red-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Establishing PRC
      'Communist victory',
      'PRC established',
      'Consolidation',
      'Mass campaigns',
      'Land reform',
      'Korean War',
      // Socialist transformation
      'First Five Year Plan',
      'Collectivisation',
      'Hundred Flowers',
      'Anti-Rightist Campaign',
      // Great Leap Forward
      'Great Leap origins',
      'Communes',
      'Backyard steel',
      'Famine',
      'Death toll',
      'Mao\'s retreat',
      // Cultural Revolution
      'Mao\'s comeback',
      'Red Guards',
      'Cultural Revolution',
      'Chaos and violence',
      'Lin Biao',
      'Restoration of order',
      'Gang of Four',
      'Death of Mao',
      // Themes
      'Cult of personality',
      'Foreign policy',
      'Impact on Chinese society',
      // Primary sources
      'Party documents',
      'Propaganda',
      'Personal accounts',
    ],
  },
  {
    id: 'south-africa',
    name: 'Paper 2F.2: South Africa 1948-94: Apartheid to Rainbow Nation',
    description: 'South Africa from apartheid to democracy',
    icon: '🇿🇦',
    color: 'bg-green-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Apartheid established
      '1948 election',
      'National Party',
      'Apartheid legislation',
      'Pass laws',
      'Group Areas Act',
      'Bantu Education',
      // Resistance
      'ANC',
      'Defiance Campaign',
      'Freedom Charter',
      'PAC',
      'Sharpeville',
      'Banning of ANC/PAC',
      'Armed struggle',
      'Mandela',
      'Rivonia Trial',
      // Apartheid entrenchment
      'Verwoerd',
      'Bantustans',
      'Economic apartheid',
      'International pressure',
      // Resistance grows
      'Black Consciousness',
      'Steve Biko',
      'Soweto Uprising 1976',
      'Township unrest',
      'UDF',
      // Collapse of apartheid
      'Botha reforms',
      'State of Emergency',
      'Sanctions',
      'De Klerk',
      'Unbanning ANC',
      'Release of Mandela',
      'CODESA',
      // Transition
      'Violence and negotiations',
      '1994 election',
      'TRC',
      'Rainbow Nation',
      // Primary sources
      'Government documents',
      'ANC sources',
      'Personal testimonies',
    ],
  },
  // ============================================================================
  // PAPER 3: THEMES IN BREADTH WITH ASPECTS IN DEPTH
  // Most popular options
  // ============================================================================
  {
    id: 'civil-rights-usa',
    name: 'Paper 3 Option 39: Civil Rights in the USA 1865-1992',
    description: 'African American experience from slavery to modern era',
    icon: '✊',
    color: 'bg-purple-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Reconstruction
      'Emancipation',
      'Reconstruction plans',
      '13th Amendment',
      '14th Amendment',
      '15th Amendment',
      'Freedmen\'s Bureau',
      'Black Codes',
      'Radical Reconstruction',
      'End of Reconstruction',
      // Jim Crow
      'Segregation',
      'Plessy v Ferguson',
      'Disfranchisement',
      'Lynch law',
      'KKK',
      // Early 20th century
      'Booker T Washington',
      'WEB Du Bois',
      'NAACP',
      'Great Migration',
      'Harlem Renaissance',
      'Marcus Garvey',
      // Depression and WWII
      'New Deal impact',
      'A Philip Randolph',
      'WWII and Double V',
      'Desegregation of military',
      // Civil Rights Movement
      'Brown v Board',
      'Emmett Till',
      'Montgomery Bus Boycott',
      'Little Rock',
      'Sit-ins',
      'Freedom Rides',
      'Albany Movement',
      'Birmingham',
      'March on Washington',
      'Civil Rights Act 1964',
      'Selma',
      'Voting Rights Act',
      // Later developments
      'Black Power',
      'Malcolm X',
      'Black Panthers',
      'Urban riots',
      'King assassination',
      'Affirmative Action',
      'Bakke case',
      'Reagan era',
      'LA riots 1992',
      // Aspects in depth
      'Detailed case studies',
      'Key turning points',
    ],
  },
  {
    id: 'making-russia',
    name: 'Paper 3 Option 38: The Making of Modern Russia 1855-1991',
    description: 'Russia from Alexander II to end of USSR',
    icon: '🏛️',
    color: 'bg-red-900',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Reform and reaction
      'Alexander II reforms',
      'Emancipation',
      'Judicial reforms',
      'Military reforms',
      'Opposition',
      'Alexander III reaction',
      'Russification',
      'Witte\'s industrialisation',
      // Nicholas II
      '1905 Revolution',
      'October Manifesto',
      'Stolypin',
      'WWI impact',
      // Revolutions
      'February Revolution',
      'October Revolution',
      'Civil War',
      // Soviet state
      'Lenin\'s rule',
      'NEP',
      'Stalin\'s rise',
      'Industrialisation',
      'Collectivisation',
      'Terror',
      'WWII',
      // Post-Stalin
      'Khrushchev',
      'De-Stalinisation',
      'Brezhnev',
      'Stagnation',
      'Gorbachev',
      'Collapse of USSR',
      // Themes
      'Role of individuals',
      'Continuity and change',
      'Government and people',
      // Aspects in depth
      'Key turning points',
      'Detailed case studies',
    ],
  },
  {
    id: 'warfare',
    name: 'Paper 3 Option 37: Changing Nature of Warfare 1859-1991',
    description: 'Evolution of warfare from Crimea to Gulf War',
    icon: '⚔️',
    color: 'bg-gray-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Paper 3',
    subtopics: [
      // 19th century warfare
      'Industrial warfare',
      'American Civil War',
      'Prussian wars',
      'Colonial warfare',
      // World War One
      'Causes',
      'Trench warfare',
      'Technology',
      'Attrition',
      'Total war',
      // Inter-war
      'Air power theories',
      'Mechanisation',
      'Spanish Civil War',
      // World War Two
      'Blitzkrieg',
      'Air power',
      'Strategic bombing',
      'Naval warfare',
      'Pacific War',
      'Atomic bomb',
      'Total war',
      // Cold War warfare
      'Nuclear weapons',
      'MAD',
      'Limited wars',
      'Korea',
      'Vietnam',
      'Proxy wars',
      'Gulf War',
      // Themes
      'Technology and tactics',
      'Home fronts',
      'Impact on society',
      // Aspects in depth
      'Key battles',
      'Turning points',
    ],
  },
  // ============================================================================
  // COURSEWORK
  // ============================================================================
  {
    id: 'coursework',
    name: 'Coursework: Independent Investigation',
    description: 'Historical investigation 3000-4000 words',
    icon: '📝',
    color: 'bg-indigo-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Coursework',
    subtopics: [
      // Investigation skills
      'Choosing a question',
      'Question formulation',
      'Scope requirements',
      'Time period requirements',
      'Primary sources',
      'Secondary interpretations',
      // Structure
      'Introduction',
      'Developing argument',
      'Use of evidence',
      'Analysis of sources',
      'Evaluation of interpretations',
      'Conclusion',
      // Assessment
      'AO1 criteria',
      'AO2 criteria',
      'AO3 criteria',
      'Word limit',
      'Referencing',
      'Bibliography',
    ],
  },
];

export function getEdexcelALevelHistoryTopicById(id: string): Topic | undefined {
  return edexcelALevelHistoryTopics.find((topic) => topic.id === id);
}
