// AQA GCSE English Literature (8702) Topics
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/english/gcse/english-literature-8702

import { Topic } from '@/types';

export const aqaGCSEEnglishLiteratureTopics: Topic[] = [
  // Paper 1: Shakespeare and the 19th-century novel
  {
    id: 'aqa-gcse-eng-lit-macbeth',
    name: 'Macbeth',
    description: 'Shakespeare\'s tragedy exploring ambition, guilt, and the supernatural through Macbeth\'s rise and fall',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Ambition and its consequences',
      'The supernatural and witchcraft',
      'Guilt and conscience',
      'Masculinity and gender roles',
      'Kingship and tyranny',
      'Appearance vs reality',
      'Violence and cruelty',
      'The natural order and chaos',
      'Lady Macbeth\'s character arc',
      'Macbeth as a tragic hero',
      'The witches\' influence',
      'Banquo and loyalty',
      'Macduff and revenge',
      'Light and darkness imagery',
      'Blood imagery',
      'Sleep and sleeplessness',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-romeo-juliet',
    name: 'Romeo and Juliet',
    description: 'Shakespeare\'s tragedy of star-crossed lovers caught between feuding families',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love and passion',
      'Fate and destiny',
      'Family conflict and loyalty',
      'Youth vs age',
      'Violence and revenge',
      'Light and dark imagery',
      'Death and mortality',
      'Marriage and duty',
      'Impulsiveness and haste',
      'Romeo\'s character development',
      'Juliet\'s growth and agency',
      'The Nurse\'s role',
      'Friar Lawrence as advisor',
      'Mercutio and Tybalt',
      'The Prologue and dramatic irony',
      'Public vs private worlds',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-merchant-venice',
    name: 'The Merchant of Venice',
    description: 'Shakespeare\'s complex comedy exploring justice, mercy, and prejudice in Venice',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Justice and mercy',
      'Prejudice and discrimination',
      'Friendship and loyalty',
      'Love and marriage',
      'Wealth and materialism',
      'Appearance vs reality',
      'Shylock as villain and victim',
      'Portia\'s intelligence and agency',
      'Antonio\'s melancholy',
      'The bond and its consequences',
      'The casket test',
      'Religious conflict',
      'Gender and disguise',
      'Venice vs Belmont',
      'The trial scene',
      'Comedy and tragedy elements',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-much-ado',
    name: 'Much Ado About Nothing',
    description: 'Shakespeare\'s witty comedy exploring love, deception, and honour in Messina',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love and relationships',
      'Deception and manipulation',
      'Honour and reputation',
      'Gender roles and expectations',
      'Wit and wordplay',
      'Appearance vs reality',
      'Beatrice and Benedick\'s relationship',
      'Hero and Claudio\'s relationship',
      'Don John\'s villainy',
      'Male friendship and loyalty',
      'The gulling scenes',
      'The masked ball',
      'The church scene',
      'Comedy and dramatic conventions',
      'Marriage and social expectations',
      'Redemption and forgiveness',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-tempest',
    name: 'The Tempest',
    description: 'Shakespeare\'s late romance exploring power, colonialism, and forgiveness',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Power and control',
      'Colonialism and exploitation',
      'Forgiveness and reconciliation',
      'Magic and the supernatural',
      'Freedom and imprisonment',
      'Nature vs nurture',
      'Prospero\'s journey',
      'Caliban as victim and villain',
      'Ariel and servitude',
      'Miranda\'s innocence',
      'The masque and spectacle',
      'Revenge and justice',
      'Civilization vs savagery',
      'Father-daughter relationships',
      'The island setting',
      'Art and illusion',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-julius-caesar',
    name: 'Julius Caesar',
    description: 'Shakespeare\'s political tragedy exploring ambition, honour, and betrayal in Rome',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Ambition and power',
      'Honour and duty',
      'Betrayal and loyalty',
      'Fate vs free will',
      'Public vs private selves',
      'Rhetoric and persuasion',
      'Brutus as tragic hero',
      'Caesar\'s character',
      'Cassius and manipulation',
      'Mark Antony\'s transformation',
      'The assassination scene',
      'The funeral speeches',
      'Omens and superstition',
      'Friendship and politics',
      'Violence and civil war',
      'Legacy and memory',
    ],
  },
  // 19th Century Novels
  {
    id: 'aqa-gcse-eng-lit-christmas-carol',
    name: 'A Christmas Carol',
    description: 'Dickens\' novella exploring redemption, social responsibility, and the Christmas spirit',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Redemption and transformation',
      'Social responsibility and poverty',
      'The Christmas spirit',
      'Greed and materialism',
      'Family and community',
      'Memory and regret',
      'Scrooge\'s character arc',
      'The Ghost of Christmas Past',
      'The Ghost of Christmas Present',
      'The Ghost of Christmas Yet to Come',
      'Bob Cratchit and family',
      'Tiny Tim and innocence',
      'Victorian attitudes to poverty',
      'Isolation vs connection',
      'Time and mortality',
      'Light and dark imagery',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-jekyll-hyde',
    name: 'The Strange Case of Dr Jekyll and Mr Hyde',
    description: 'Stevenson\'s novella exploring duality, repression, and Victorian morality',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Duality of human nature',
      'Good vs evil',
      'Victorian repression',
      'Science and ethics',
      'Secrecy and concealment',
      'Reputation and respectability',
      'Jekyll\'s experiment',
      'Hyde as evil incarnate',
      'Utterson as narrator',
      'The door and setting',
      'Gothic elements',
      'Violence and brutality',
      'Addiction and loss of control',
      'Male friendship and society',
      'The final confession',
      'Fog and darkness imagery',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-great-expectations',
    name: 'Great Expectations',
    description: 'Dickens\' bildungsroman exploring class, ambition, and identity in Victorian England',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Social class and ambition',
      'Identity and self-discovery',
      'Crime and punishment',
      'Guilt and redemption',
      'Love and rejection',
      'Wealth and corruption',
      'Pip\'s development',
      'Miss Havisham\'s influence',
      'Estella and emotional coldness',
      'Magwitch as benefactor',
      'Joe and true gentility',
      'Satis House symbolism',
      'The marshes setting',
      'Victorian justice system',
      'Childhood and innocence',
      'Expectations vs reality',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-jane-eyre',
    name: 'Jane Eyre',
    description: 'Brontë\'s novel exploring independence, morality, and love through Jane\'s journey',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Independence and self-respect',
      'Love and morality',
      'Social class and position',
      'Religion and spirituality',
      'Gender roles and equality',
      'Passion vs reason',
      'Jane\'s character development',
      'Rochester as Byronic hero',
      'Bertha Mason and the attic',
      'Childhood suffering',
      'Thornfield Hall',
      'The red room',
      'St John Rivers',
      'Marriage and equality',
      'Gothic elements',
      'Fire and ice imagery',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-frankenstein',
    name: 'Frankenstein',
    description: 'Shelley\'s Gothic novel exploring creation, responsibility, and the dangers of ambition',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Creation and responsibility',
      'Ambition and obsession',
      'Isolation and loneliness',
      'Nature vs nurture',
      'Monstrosity and humanity',
      'Science and ethics',
      'Victor Frankenstein\'s hubris',
      'The creature\'s development',
      'The creature\'s eloquence',
      'Rejection and revenge',
      'The De Lacey family',
      'Frame narrative structure',
      'Walton as double',
      'Female characters',
      'Prometheus myth',
      'Arctic and Alpine settings',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-pride-prejudice',
    name: 'Pride and Prejudice',
    description: 'Austen\'s novel exploring marriage, class, and personal growth in Regency England',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Pride and prejudice themes',
      'Marriage and social status',
      'Love and relationships',
      'Class and money',
      'Gender and society',
      'First impressions',
      'Elizabeth Bennet\'s wit',
      'Darcy\'s transformation',
      'Jane and Bingley',
      'Wickham\'s deception',
      'Lady Catherine de Bourgh',
      'Mr and Mrs Bennet',
      'Pemberley visit',
      'Irony and satire',
      'The entail',
      'Reputation and scandal',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-sign-four',
    name: 'The Sign of Four',
    description: 'Doyle\'s detective novel featuring Sherlock Holmes investigating a complex case',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Detection and deduction',
      'Empire and colonialism',
      'Justice and revenge',
      'Wealth and greed',
      'Friendship and partnership',
      'Science and reason',
      'Holmes\'s methods',
      'Watson as narrator',
      'Mary Morstan',
      'The Agra treasure',
      'Jonathan Small\'s revenge',
      'Victorian London setting',
      'The chase sequence',
      'Holmes\'s drug use',
      'Exotic and Gothic elements',
      'Class and respectability',
    ],
  },
  // Paper 2: Modern Texts and Poetry
  {
    id: 'aqa-gcse-eng-lit-inspector-calls',
    name: 'An Inspector Calls',
    description: 'Priestley\'s play exploring social responsibility, class, and generational conflict',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Social responsibility',
      'Class and inequality',
      'Generational conflict',
      'Guilt and confession',
      'Capitalism vs socialism',
      'Gender and society',
      'The Inspector\'s role',
      'Mr Birling\'s capitalist views',
      'Mrs Birling\'s hypocrisy',
      'Sheila\'s transformation',
      'Eric\'s guilt',
      'Gerald\'s affair',
      'Eva Smith/Daisy Renton',
      'The twist ending',
      'Time and structure',
      '1912 vs 1945 context',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-blood-brothers',
    name: 'Blood Brothers',
    description: 'Russell\'s musical exploring class, fate, and nature vs nurture through twin brothers',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Nature vs nurture',
      'Class and inequality',
      'Superstition and fate',
      'Friendship and loyalty',
      'Identity and belonging',
      'Motherhood and sacrifice',
      'Mickey\'s journey',
      'Edward\'s privilege',
      'Mrs Johnstone\'s sacrifice',
      'Mrs Lyons\' desperation',
      'The blood bond',
      'Linda and relationships',
      'The narrator\'s role',
      'Songs and their meanings',
      'Liverpool setting',
      'Tragedy and inevitability',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-poetry-anthology',
    name: 'Poetry Anthology: Power and Conflict',
    description: 'AQA poetry anthology exploring themes of power and conflict across 15 poems',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Ozymandias - power and legacy',
      'London - social injustice',
      'Extract from The Prelude - nature\'s power',
      'My Last Duchess - control and jealousy',
      'Charge of the Light Brigade - military conflict',
      'Exposure - war\'s brutal reality',
      'Storm on the Island - nature\'s threat',
      'Bayonet Charge - fear in battle',
      'Remains - psychological trauma',
      'Poppies - grief and loss',
      'War Photographer - memory and detachment',
      'Tissue - fragility and power',
      'The Emigrée - memory and identity',
      'Checking Out Me History - identity and resistance',
      'Kamikaze - duty vs family',
      'Comparing poems effectively',
    ],
  },
  {
    id: 'aqa-gcse-eng-lit-unseen-poetry',
    name: 'Unseen Poetry',
    description: 'Skills for analysing and comparing unseen poems in the exam',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'First reading strategies',
      'Identifying themes and ideas',
      'Analysing language techniques',
      'Analysing structure',
      'Analysing form',
      'Using subject terminology',
      'Writing about imagery',
      'Exploring tone and mood',
      'Understanding voice and speaker',
      'Comparing two poems',
      'Identifying similarities',
      'Identifying differences',
      'Linking ideas coherently',
      'Using quotations effectively',
      'Time management',
      'Planning responses',
    ],
  },
];

export function getAQAGCSEEnglishLiteratureTopicById(id: string): Topic | undefined {
  return aqaGCSEEnglishLiteratureTopics.find((topic) => topic.id === id);
}
