// AQA GCSE History (8145) Topics
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/history/gcse/history-8145

import { Topic } from '@/types';

export const aqaGCSEHistoryTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: UNDERSTANDING THE MODERN WORLD
  // Section A: Period Studies
  // ============================================================================
  {
    id: 'aqa-gcse-hist-america-expansion',
    name: 'America 1840-1895: Expansion and Consolidation',
    description: 'The development of America through expansion and civil war',
    icon: '🇺🇸',
    color: 'bg-blue-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section A',
    subtopics: [
      // Expansion
      'Manifest Destiny',
      'The Oregon Trail',
      'The California Gold Rush 1849',
      'Reasons for westward migration',
      'The Mormon migration',
      'Joseph Smith and Brigham Young',
      // Native Americans
      'Plains Indians way of life',
      'Impact of expansion on Native Americans',
      'Indian Removal Act 1830',
      'Trail of Tears',
      'Reservations policy',
      'Battle of Little Bighorn 1876',
      'Wounded Knee 1890',
      // Civil War
      'Causes of the Civil War',
      'Slavery and abolition',
      'Lincoln and the Union',
      'Key battles of the Civil War',
      'Emancipation Proclamation 1863',
      'Reconstruction',
      // Post-war America
      'Transcontinental Railroad',
      'Cattle industry',
      'Homesteaders',
      'Range wars',
      'Law and order in the West',
    ],
  },
  {
    id: 'aqa-gcse-hist-germany-democracy-dictatorship',
    name: 'Germany 1890-1945: Democracy and Dictatorship',
    description: 'Germany from Kaiser Wilhelm II to the fall of Nazi Germany',
    icon: '🇩🇪',
    color: 'bg-gray-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section A',
    subtopics: [
      // Kaiser Wilhelm II
      'Germany under Kaiser Wilhelm II',
      'German society 1890-1914',
      'Industrial growth',
      'Military expansion',
      'Colonial ambitions',
      // Impact of WWI
      'Impact of World War One on Germany',
      'Stresses of war',
      'Economic problems',
      'Political unrest',
      'German Revolution 1918',
      'Abdication of the Kaiser',
      // Weimar Republic
      'Weimar Constitution',
      'Strengths and weaknesses of Weimar',
      'Political threats',
      'Spartacist Rising 1919',
      'Kapp Putsch 1920',
      'French occupation of the Ruhr 1923',
      'Hyperinflation 1923',
      // Stresemann era
      'Gustav Stresemann',
      'Economic recovery',
      'Dawes Plan 1924',
      'Young Plan 1929',
      'Locarno Treaties 1925',
      'League of Nations membership 1926',
      'Cultural changes in Weimar Germany',
      // Nazi rise
      'Nazi Party origins',
      'Hitler and the Munich Putsch 1923',
      'Nazi ideology',
      'Impact of the Great Depression',
      'Growth of Nazi support 1929-1932',
      'Political instability 1930-1933',
      'Hitler becomes Chancellor January 1933',
      // Nazi consolidation
      'Reichstag Fire February 1933',
      'Enabling Act March 1933',
      'Night of the Long Knives 1934',
      'Death of Hindenburg 1934',
      'Creation of Fuhrer state',
      // Nazi control
      'SS and Gestapo',
      'Propaganda and censorship',
      'Goebbels and the Ministry of Propaganda',
      'Nazi control of education',
      'Hitler Youth',
      'Nazi policies towards the Church',
      // Life in Nazi Germany
      'Nazi economic policies',
      'Rearmament',
      'Autarky',
      'Workers and the DAF',
      'Women in Nazi Germany',
      'Persecution of minorities',
      'Nuremberg Laws 1935',
      'Kristallnacht 1938',
      'The Holocaust',
      // Opposition
      'Opposition to the Nazis',
      'Youth opposition',
      'Church opposition',
      'July Bomb Plot 1944',
    ],
  },
  {
    id: 'aqa-gcse-hist-russia-tsardom-communism',
    name: 'Russia 1894-1945: Tsardom and Communism',
    description: 'Russia from the last Tsar to Stalin',
    icon: '🇷🇺',
    color: 'bg-red-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section A',
    subtopics: [
      // Tsarist Russia
      'Russia under Nicholas II',
      'Autocracy and the Tsar',
      'Russian society 1894',
      'The Orthodox Church',
      'Opposition groups',
      'Social Revolutionaries',
      'Social Democrats',
      'Bolsheviks and Mensheviks',
      // 1905 Revolution
      'Causes of the 1905 Revolution',
      'Bloody Sunday',
      'Events of 1905',
      'October Manifesto',
      'The Dumas',
      'Stolypin reforms',
      // Impact of WWI
      'Russia in World War One',
      'Military defeats',
      'Economic problems',
      'Rasputin',
      // February Revolution
      'February Revolution 1917',
      'Fall of the Tsar',
      'Provisional Government',
      'Soviets and dual power',
      // October Revolution
      'Lenin and the Bolsheviks',
      'April Theses',
      'July Days',
      'Kornilov Affair',
      'October Revolution 1917',
      // Civil War
      'Treaty of Brest-Litovsk',
      'Civil War 1918-1921',
      'Whites vs Reds',
      'War Communism',
      'Red Terror',
      // NEP era
      'New Economic Policy',
      'Kronstadt Rising',
      'Death of Lenin 1924',
      'Power struggle 1924-1929',
      // Stalin
      'Stalin vs Trotsky',
      'Rise of Stalin',
      'Five Year Plans',
      'Collectivisation',
      'Dekulakisation',
      'Ukrainian Famine',
      'Purges and show trials',
      'Cult of personality',
      'Life under Stalin',
    ],
  },
  {
    id: 'aqa-gcse-hist-america-opportunity-inequality',
    name: 'America 1920-1973: Opportunity and Inequality',
    description: 'American society from the Roaring Twenties to Vietnam',
    icon: '🗽',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section A',
    subtopics: [
      // 1920s prosperity
      'American economy in the 1920s',
      'Mass production',
      'Consumer boom',
      'Hire purchase',
      'Stock market speculation',
      // 1920s society
      'Republican government policies',
      'Immigration restrictions',
      'Red Scare',
      'Prohibition',
      'Organised crime',
      'Jazz Age',
      'Changing role of women',
      'Flappers',
      // Intolerance
      'Racism in 1920s America',
      'Jim Crow laws',
      'Ku Klux Klan',
      'Sacco and Vanzetti',
      // Great Depression
      'Wall Street Crash 1929',
      'Causes of the Depression',
      'Impact of the Depression',
      'Hoovervilles',
      'Hoover\'s response',
      // New Deal
      'Election of FDR 1932',
      'First New Deal',
      'Alphabet agencies',
      'Second New Deal',
      'Opposition to the New Deal',
      'Impact of the New Deal',
      // WWII impact
      'Impact of World War Two',
      'Economic recovery',
      'Women in wartime',
      'African Americans in wartime',
      // Post-war prosperity
      'Post-war economic boom',
      'Suburban growth',
      'Consumer society',
      'McCarthyism and the Red Scare',
      // Civil Rights
      'Segregation in the South',
      'Brown v Board of Education 1954',
      'Montgomery Bus Boycott 1955-56',
      'Little Rock 1957',
      'Sit-ins and Freedom Rides',
      'Martin Luther King Jr',
      'March on Washington 1963',
      'Civil Rights Act 1964',
      'Voting Rights Act 1965',
      'Black Power movement',
      'Malcolm X',
      // Other inequalities
      'Women\'s movement',
      'Native American activism',
      'Vietnam War and protest',
    ],
  },
  // ============================================================================
  // PAPER 1: UNDERSTANDING THE MODERN WORLD
  // Section B: Wider World Depth Studies (Conflict and Tension)
  // ============================================================================
  {
    id: 'aqa-gcse-hist-conflict-ww1',
    name: 'Conflict and Tension: The First World War 1894-1918',
    description: 'Causes, events and conclusion of World War One',
    icon: '⚔️',
    color: 'bg-red-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section B',
    subtopics: [
      // Causes of WWI
      'Alliance system',
      'Triple Alliance',
      'Triple Entente',
      'Arms race',
      'Naval rivalry',
      'Colonial rivalries',
      'Nationalism',
      'Balkans crises',
      'Assassination of Franz Ferdinand',
      'July Crisis 1914',
      'Schlieffen Plan',
      // The war
      'Western Front',
      'Trench warfare',
      'Key battles',
      'Battle of the Somme',
      'Battle of Verdun',
      'Battle of Passchendaele',
      'Technology and warfare',
      'Tanks',
      'Gas',
      'Aircraft',
      // War on other fronts
      'Eastern Front',
      'Gallipoli',
      'War at sea',
      'U-boats and unrestricted warfare',
      // End of war
      'Entry of USA 1917',
      'German Spring Offensive 1918',
      'Allied counter-offensive',
      'Armistice November 1918',
      // Peace settlement
      'Paris Peace Conference',
      'Treaty of Versailles',
      'Terms of Versailles',
      'War guilt clause',
      'Reparations',
      'Territorial changes',
      'German reactions',
    ],
  },
  {
    id: 'aqa-gcse-hist-conflict-interwar',
    name: 'Conflict and Tension: The Inter-War Years 1918-1939',
    description: 'International relations between the world wars',
    icon: '🕊️',
    color: 'bg-amber-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section B',
    subtopics: [
      // Peace treaties
      'Treaty of Versailles',
      'Terms and impact',
      'German reactions',
      'Treaty of Saint-Germain',
      'Treaty of Trianon',
      'Treaty of Neuilly',
      'Treaty of Sevres/Lausanne',
      // League of Nations
      'Creation of the League',
      'Aims and structure',
      'Membership issues',
      'League successes in 1920s',
      'League weaknesses',
      // 1920s international relations
      'Ruhr Crisis 1923',
      'Dawes Plan 1924',
      'Locarno Treaties 1925',
      'Kellogg-Briand Pact 1928',
      'Young Plan 1929',
      // 1930s failures
      'Impact of the Depression',
      'Manchurian Crisis 1931-33',
      'League response to Manchuria',
      'Abyssinian Crisis 1935-36',
      'League response to Abyssinia',
      'Failure of collective security',
      // Rise of dictators
      'Hitler\'s foreign policy aims',
      'Rearmament',
      'Rhineland remilitarisation 1936',
      'Rome-Berlin Axis',
      'Anti-Comintern Pact',
      // Appeasement
      'Anschluss 1938',
      'Sudetenland Crisis',
      'Munich Agreement 1938',
      'Appeasement debate',
      'End of Czechoslovakia 1939',
      'Nazi-Soviet Pact',
      'Invasion of Poland',
      'Outbreak of World War Two',
    ],
  },
  {
    id: 'aqa-gcse-hist-conflict-cold-war',
    name: 'Conflict and Tension: East and West 1945-1972',
    description: 'The Cold War from 1945 to detente',
    icon: '❄️',
    color: 'bg-cyan-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section B',
    subtopics: [
      // Origins
      'Wartime conferences',
      'Yalta Conference',
      'Potsdam Conference',
      'Ideological differences',
      'Capitalism vs Communism',
      'Soviet expansion in Eastern Europe',
      'Iron Curtain speech',
      'Truman Doctrine',
      'Marshall Plan',
      'Cominform and Comecon',
      // Berlin
      'Division of Germany',
      'Berlin Blockade 1948-49',
      'Berlin Airlift',
      'Formation of NATO',
      'Formation of Warsaw Pact',
      // Hungary and Berlin
      'Khrushchev and de-Stalinisation',
      'Hungarian Uprising 1956',
      'Soviet response to Hungary',
      'Berlin Crisis 1958-61',
      'Berlin Wall 1961',
      // Cuba
      'Cuban Revolution',
      'Bay of Pigs 1961',
      'Cuban Missile Crisis 1962',
      'Thirteen days',
      'Significance of Cuba',
      // Czechoslovakia
      'Prague Spring 1968',
      'Dubcek reforms',
      'Soviet invasion',
      'Brezhnev Doctrine',
      // Detente
      'Reasons for detente',
      'SALT 1',
      'Helsinki Accords',
    ],
  },
  {
    id: 'aqa-gcse-hist-conflict-asia',
    name: 'Conflict and Tension in Asia 1950-1975',
    description: 'Korean and Vietnam Wars',
    icon: '🌏',
    color: 'bg-green-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1 Section B',
    subtopics: [
      // Korean War
      'Division of Korea',
      'Causes of Korean War',
      'North Korean invasion',
      'UN involvement',
      'Inchon landing',
      'Chinese intervention',
      'Stalemate and armistice',
      'Consequences of Korean War',
      // Vietnam background
      'French Indochina',
      'Ho Chi Minh',
      'Vietminh',
      'Dien Bien Phu 1954',
      'Geneva Conference',
      'Division of Vietnam',
      // US involvement
      'Domino theory',
      'Eisenhower and advisors',
      'Kennedy and increased involvement',
      'Gulf of Tonkin 1964',
      'Johnson and escalation',
      // The Vietnam War
      'US tactics',
      'Search and destroy',
      'Agent Orange',
      'Napalm',
      'Operation Rolling Thunder',
      'Vietcong tactics',
      'Guerrilla warfare',
      'Ho Chi Minh Trail',
      // Turning points
      'Tet Offensive 1968',
      'My Lai massacre',
      'Media coverage',
      'Anti-war movement',
      // End of war
      'Nixon and Vietnamisation',
      'Cambodia and Laos',
      'Paris Peace Accords 1973',
      'Fall of Saigon 1975',
      'Impact of Vietnam War',
    ],
  },
  // ============================================================================
  // PAPER 2: SHAPING THE NATION
  // Section A: Thematic Studies
  // ============================================================================
  {
    id: 'aqa-gcse-hist-health-people',
    name: 'Britain: Health and the People c1000-present',
    description: 'Development of medicine and public health in Britain',
    icon: '🏥',
    color: 'bg-pink-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section A',
    subtopics: [
      // Medieval medicine
      'Medieval ideas about disease',
      'Four Humours',
      'Miasma theory',
      'Role of the Church',
      'Hospitals in medieval times',
      'Islamic medicine',
      'Surgery in medieval times',
      // Medieval public health
      'Towns and public health',
      'The Black Death',
      'Responses to the Black Death',
      // Renaissance medicine
      'Renaissance and medical knowledge',
      'Vesalius and anatomy',
      'Pare and surgery',
      'Harvey and circulation',
      'Continuity and change',
      // 18th-19th century
      'Jenner and vaccination',
      'Germ theory',
      'Pasteur',
      'Koch',
      'Opposition to germ theory',
      // Surgery improvements
      'Pain - anaesthetics',
      'Simpson and chloroform',
      'Infection - antiseptics',
      'Lister and carbolic acid',
      'Blood loss - transfusions',
      // Public health 19th century
      'Industrial Revolution impact',
      'Cholera epidemics',
      'Chadwick Report 1842',
      'Public Health Acts 1848 and 1875',
      'John Snow and cholera',
      // 20th century
      'Magic bullets',
      'Penicillin',
      'Fleming, Florey and Chain',
      'NHS creation 1948',
      'Modern treatments',
      'DNA and genetics',
      'Lifestyle diseases',
      // Modern public health
      'Government campaigns',
      'Vaccination programmes',
      'Health inequalities today',
    ],
  },
  {
    id: 'aqa-gcse-hist-power-people',
    name: 'Britain: Power and the People c1170-present',
    description: 'Struggles for power and rights throughout British history',
    icon: '👑',
    color: 'bg-purple-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section A',
    subtopics: [
      // Medieval challenges
      'Magna Carta 1215',
      'Simon de Montfort',
      'Peasants\' Revolt 1381',
      // Tudor and Stuart
      'Pilgrimage of Grace 1536',
      'English Civil War',
      'Execution of Charles I',
      'The Glorious Revolution 1688',
      // Industrial period
      'American Revolution influence',
      'French Revolution influence',
      'Peterloo Massacre 1819',
      'Great Reform Act 1832',
      'Chartism',
      'Anti-Slavery movement',
      // Workers\' rights
      'Tolpuddle Martyrs',
      'Trade unions',
      'General Strike 1926',
      // Votes for women
      'Suffragists',
      'Suffragettes',
      'WSPU',
      'Cat and Mouse Act',
      'Emily Davison',
      'Women\'s suffrage achieved',
      // 20th century
      'Workers\' rights in 20th century',
      'Welfare state',
      'Anti-apartheid movement',
      'Miners\' Strike 1984-85',
      'Poll Tax protests',
    ],
  },
  {
    id: 'aqa-gcse-hist-migration-empires',
    name: 'Britain: Migration, Empires and the People c790-present',
    description: 'Migration to and from Britain and the British Empire',
    icon: '🌍',
    color: 'bg-teal-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section A',
    subtopics: [
      // Early migration
      'Viking invasions',
      'Norman Conquest',
      'Medieval migration',
      'Jewish communities',
      // Empire beginnings
      'Early colonisation',
      'Slave trade',
      'East India Company',
      // Growth of Empire
      'British in India',
      'Scramble for Africa',
      'Settlement colonies',
      'Impact of Empire',
      // Migration 19th century
      'Irish migration',
      'Jewish migration',
      'Emigration from Britain',
      // 20th century
      'Windrush generation',
      'Commonwealth immigration',
      'Immigration controls',
      'Multiculturalism',
      // Decolonisation
      'Indian independence',
      'African independence',
      'End of Empire',
      'Legacy of Empire',
    ],
  },
  // ============================================================================
  // PAPER 2: SHAPING THE NATION
  // Section B: British Depth Studies
  // ============================================================================
  {
    id: 'aqa-gcse-hist-norman-england',
    name: 'Norman England c1066-c1100',
    description: 'The Norman Conquest and its impact on England',
    icon: '🏰',
    color: 'bg-stone-600',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section B',
    subtopics: [
      // Conquest
      'Anglo-Saxon England',
      'Edward the Confessor',
      'Succession crisis 1066',
      'Claimants to the throne',
      'Harald Hardrada',
      'Harold Godwinson',
      'William of Normandy',
      'Battle of Stamford Bridge',
      'Battle of Hastings',
      'William\'s victory',
      // Establishing control
      'Submission of the English',
      'Coronation',
      'Rewarding supporters',
      'Maintaining control',
      'Castles',
      'Motte and bailey castles',
      'Stone castles',
      // Resistance
      'English resistance',
      'Rebellions 1067-1068',
      'Harrying of the North 1069-70',
      'Hereward the Wake',
      'Revolt of the Earls 1075',
      // Norman England
      'Feudal system',
      'Land ownership',
      'Domesday Book',
      'Forest laws',
      'Norman Church',
      'Lanfranc',
      'Changes to the Church',
      // Society
      'Norman nobility',
      'Towns and villages',
      'Peasant life',
      'Impact on English culture',
      // Historic Environment
      'Specific site study',
      'Site significance',
      'Site features',
    ],
  },
  {
    id: 'aqa-gcse-hist-elizabethan-england',
    name: 'Elizabethan England c1568-1603',
    description: 'England under Elizabeth I',
    icon: '👑',
    color: 'bg-amber-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section B',
    subtopics: [
      // Elizabeth\'s court
      'Elizabeth I',
      'Court and government',
      'Privy Council',
      'Parliament',
      'Local government',
      // Religious settlement
      'Religious divisions',
      'Religious Settlement 1559',
      'Church of England',
      'Catholic threats',
      'Puritan challenges',
      // Mary Queen of Scots
      'Mary Queen of Scots',
      'Arrival in England 1568',
      'Catholic plots',
      'Northern Rebellion 1569',
      'Ridolfi Plot 1571',
      'Throckmorton Plot 1583',
      'Babington Plot 1586',
      'Execution of Mary 1587',
      // Elizabeth and Spain
      'Relations with Spain',
      'Drake and privateering',
      'Spanish Armada 1588',
      'Reasons for English victory',
      // Elizabethan society
      'Social hierarchy',
      'Gentry and nobility',
      'The poor',
      'Poor Laws',
      'Poverty and vagabondage',
      // Elizabethan culture
      'Education',
      'Theatre',
      'Shakespeare',
      'Exploration',
      'Drake and Raleigh',
      // Historic Environment
      'Specific site study',
      'Site significance',
    ],
  },
  {
    id: 'aqa-gcse-hist-restoration-england',
    name: 'Restoration England 1660-1685',
    description: 'England under Charles II',
    icon: '🎭',
    color: 'bg-indigo-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section B',
    subtopics: [
      // Restoration
      'End of Interregnum',
      'Return of Charles II',
      'Restoration Settlement',
      'Church settlement',
      'Clarendon Code',
      // Government
      'Charles II\'s court',
      'Parliament',
      'Cavalier Parliament',
      'Political parties',
      'Whigs and Tories',
      // Religion
      'Religious tensions',
      'Catholics and Dissenters',
      'Popish Plot 1678',
      'Exclusion Crisis',
      // Society
      'Restoration society',
      'Role of women',
      'Theatre and culture',
      'Coffee houses',
      'Science and Royal Society',
      // Events
      'Great Plague 1665',
      'Responses to plague',
      'Great Fire of London 1666',
      'Rebuilding London',
      // Foreign policy
      'Anglo-Dutch Wars',
      'Treaty of Dover 1670',
      // Historic Environment
      'Specific site study',
    ],
  },
];

export function getAQAGCSEHistoryTopicById(id: string): Topic | undefined {
  return aqaGCSEHistoryTopics.find((topic) => topic.id === id);
}
