// AQA GCSE Combined Science: Trilogy (8464) Topics
// Based on the official AQA specification
// Reference: https://www.aqa.org.uk/subjects/science/gcse/combined-science-trilogy-8464
//
// Combined Science is worth 2 GCSEs and covers Biology, Chemistry, and Physics
// 6 papers total: Biology Paper 1 & 2, Chemistry Paper 1 & 2, Physics Paper 1 & 2
// Each paper: 1 hour 15 minutes, 70 marks, 16.7% of qualification
//
// Key differences from Triple Science (separate GCSEs):
// - No Space Physics topic
// - Some Higher Tier (H) content is the same
// - Content marked (T) in Triple Science is NOT in Combined Science
//
// (H) = Higher tier only

import { Topic } from '@/types';

export const aqaCombinedScienceTopics: Topic[] = [
  // ============================================================================
  // BIOLOGY PAPER 1 TOPICS (B1-B4)
  // ============================================================================
  {
    id: 'combined-biology-cell-biology',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Cell Biology',
    description: 'Cell structure, transport, division, and stem cells',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // 4.1.1 Cell structure
      'Eukaryotic and prokaryotic cells',
      'Animal cell structure',
      'Plant cell structure',
      'Bacterial cell structure',
      'Cell organelles and their functions',
      'Nucleus, cytoplasm, cell membrane',
      'Mitochondria and ribosomes',
      'Chloroplasts and vacuoles',
      'Cell wall in plants',
      'Plasmids in bacteria',
      // 4.1.2 Cell division
      'Chromosomes and DNA',
      'The cell cycle',
      'Mitosis',
      'Stages of mitosis',
      'Stem cells',
      'Embryonic stem cells',
      'Adult stem cells',
      'Therapeutic use of stem cells',
      'Meristems in plants',
      // 4.1.3 Transport in cells
      'Diffusion',
      'Factors affecting diffusion',
      'Osmosis',
      'Osmosis in plants and animals',
      'Active transport',
      'Active transport in root hair cells',
      'Active transport in the gut',
      // Microscopy (Required Practical 1)
      'Using a light microscope',
      'Magnification calculations',
      'Scale bars',
      'Resolution and magnification',
      'Electron microscopes',
      'Preparing microscope slides',
    ],
  },
  {
    id: 'combined-biology-organisation',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Organisation',
    description: 'Cells, tissues, organs, and organ systems in plants and animals',
    icon: '🫀',
    color: 'bg-red-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // 4.2.1 Principles of organisation
      'Cells, tissues, organs, organ systems',
      'Levels of organisation',
      // 4.2.2 Animal tissues, organs and organ systems
      'The digestive system',
      'Digestive enzymes',
      'Carbohydrases (amylase)',
      'Proteases (pepsin, trypsin)',
      'Lipases',
      'Bile and emulsification',
      'Factors affecting enzyme action',
      'Effect of pH on enzymes',
      'Effect of temperature on enzymes',
      'Lock and key model',
      'Food tests (Required Practical)',
      // The heart and blood vessels
      'The heart structure',
      'Heart chambers and valves',
      'Coronary arteries',
      'The cardiac cycle',
      'Blood vessels',
      'Arteries, veins, capillaries',
      'Blood composition',
      'Red blood cells',
      'White blood cells',
      'Platelets and plasma',
      // Cardiovascular disease
      'Coronary heart disease',
      'Stents',
      'Statins',
      'Heart valves replacement',
      'Artificial hearts',
      'Heart transplants',
      // Health issues
      'Health and disease',
      'Risk factors for disease',
      'Cancer',
      'Tumours (benign and malignant)',
      // 4.2.3 Plant tissues, organs and systems
      'Plant tissues',
      'Epidermal tissue',
      'Palisade mesophyll',
      'Spongy mesophyll',
      'Xylem and phloem',
      'Meristem tissue',
      'Plant organ system',
      'Transpiration',
      'Translocation',
      'Guard cells and stomata',
    ],
  },
  {
    id: 'combined-biology-infection-response',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Infection and Response',
    description: 'Pathogens, the immune system, and disease prevention',
    icon: '🦠',
    color: 'bg-green-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // 4.3.1 Communicable diseases
      'Pathogens',
      'Types of pathogen',
      'Bacteria',
      'Viruses',
      'Protists',
      'Fungi',
      'How pathogens spread',
      // Viral diseases
      'Measles',
      'HIV/AIDS',
      'Tobacco mosaic virus (TMV)',
      // Bacterial diseases
      'Salmonella',
      'Gonorrhoea',
      // Fungal diseases
      'Rose black spot',
      // Protist diseases
      'Malaria',
      // Human defence systems
      'Physical barriers',
      'Skin',
      'Nose hairs and mucus',
      'Trachea and bronchi cilia',
      'Stomach acid',
      // Immune system
      'White blood cells',
      'Phagocytosis',
      'Antibody production',
      'Antitoxin production',
      // 4.3.2 Vaccination
      'How vaccines work',
      'Herd immunity',
      'Vaccine development',
      // 4.3.3 Antibiotics and painkillers
      'Antibiotics',
      'Antibiotic resistance',
      'MRSA',
      'Painkillers',
      'Developing new drugs',
      'Clinical trials',
      'Placebo effect',
      'Double-blind trials',
      // 4.3.4 Discovery and development of drugs
      'Drug discovery',
      'Digitalis from foxgloves',
      'Aspirin from willow',
      'Penicillin discovery',
    ],
  },
  {
    id: 'combined-biology-bioenergetics',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Bioenergetics',
    description: 'Photosynthesis and respiration',
    icon: '🌱',
    color: 'bg-emerald-500',
    paperRestriction: 'Biology Paper 1',
    subtopics: [
      // 4.4.1 Photosynthesis
      'Photosynthesis equation',
      'Photosynthesis as endothermic',
      'Where photosynthesis occurs',
      'Role of chlorophyll',
      'Uses of glucose',
      'Glucose for respiration',
      'Glucose for cellulose',
      'Glucose for starch storage',
      'Glucose for lipids',
      'Glucose for proteins',
      // Rate of photosynthesis
      'Factors affecting photosynthesis rate',
      'Light intensity',
      'Carbon dioxide concentration',
      'Temperature',
      'Limiting factors',
      'Inverse square law (light intensity)',
      'Greenhouses and optimum conditions',
      // Required Practical
      'Investigating photosynthesis rate',
      'Effect of light intensity on photosynthesis',
      // 4.4.2 Respiration
      'Aerobic respiration equation',
      'Aerobic respiration in mitochondria',
      'Anaerobic respiration',
      'Anaerobic respiration in muscles',
      'Lactic acid',
      'Anaerobic respiration in yeast',
      'Fermentation',
      'Oxygen debt',
      'EPOC (excess post-exercise oxygen consumption)',
      // Metabolism
      'Metabolism definition',
      'Examples of metabolic reactions',
      'Response to exercise',
      'Heart rate during exercise',
      'Breathing rate during exercise',
    ],
  },

  // ============================================================================
  // BIOLOGY PAPER 2 TOPICS (B5-B7)
  // ============================================================================
  {
    id: 'combined-biology-homeostasis',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Homeostasis and Response',
    description: 'Nervous system, hormones, and maintaining stable internal conditions',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // 4.5.1 Homeostasis
      'Homeostasis definition',
      'Importance of homeostasis',
      'Control systems',
      'Receptors, coordination centres, effectors',
      'Negative feedback',
      // 4.5.2 The human nervous system
      'Structure of the nervous system',
      'Central nervous system (CNS)',
      'Peripheral nervous system',
      'Neurones',
      'Sensory neurones',
      'Relay neurones',
      'Motor neurones',
      'Synapses',
      'Reflex actions',
      'Reflex arc',
      // Required Practical
      'Investigating reaction time',
      // 4.5.3 Hormonal coordination
      'The endocrine system',
      'Glands and hormones',
      'Pituitary gland (master gland)',
      'Thyroid gland',
      'Pancreas',
      'Adrenal glands',
      'Ovaries and testes',
      // Blood glucose control
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Diabetes Type 1',
      'Diabetes Type 2',
      'Treating diabetes',
      // 4.5.4 Hormones in human reproduction
      'Puberty',
      'Hormones in the menstrual cycle',
      'Oestrogen',
      'Progesterone',
      'FSH (follicle stimulating hormone)',
      'LH (luteinising hormone)',
      // Contraception
      'Hormonal contraception',
      'Non-hormonal contraception',
      'Barrier methods',
      'Fertility treatments',
      'IVF',
      'FSH and LH in fertility',
      // Negative feedback in hormones (HT)
      'Negative feedback in menstrual cycle (H)',
      'Adrenaline (H)',
      'Thyroxine (H)',
    ],
  },
  {
    id: 'combined-biology-inheritance',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Inheritance, Variation and Evolution',
    description: 'Genetics, evolution, and classification',
    icon: '🧬',
    color: 'bg-blue-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // 4.6.1 Reproduction
      'Sexual reproduction',
      'Asexual reproduction',
      'Advantages and disadvantages of each',
      'Meiosis',
      'Gametes and fertilisation',
      'Genetic variation from meiosis',
      // DNA and the genome
      'DNA structure',
      'Double helix',
      'Genes and chromosomes',
      'The human genome',
      'Genome project significance',
      // Genetic inheritance
      'Alleles',
      'Dominant and recessive alleles',
      'Homozygous and heterozygous',
      'Genotype and phenotype',
      'Punnett squares',
      'Genetic crosses',
      'Monohybrid crosses',
      'Inherited disorders',
      'Polydactyly',
      'Cystic fibrosis',
      // Sex determination
      'Sex chromosomes',
      'XX and XY',
      'Inheritance of sex',
      // 4.6.2 Variation and evolution
      'Genetic variation',
      'Environmental variation',
      'Continuous and discontinuous variation',
      'Mutations',
      'Evolution by natural selection',
      'Darwin\'s theory',
      'Wallace\'s contribution',
      'Evidence for evolution',
      'Fossils',
      'Antibiotic resistant bacteria',
      // Selective breeding
      'Selective breeding process',
      'Uses of selective breeding',
      'Problems with selective breeding',
      // Genetic engineering
      'Genetic modification',
      'GM crops',
      'Insulin production',
      'Benefits and risks of GM',
      // 4.6.3 Classification
      'Linnaean classification',
      'Kingdoms',
      'Three-domain system',
      'Archaea, Bacteria, Eukaryota',
      'Evolutionary trees',
      'Binomial naming system',
    ],
  },
  {
    id: 'combined-biology-ecology',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Ecology',
    description: 'Ecosystems, interdependence, and human impact on the environment',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Biology Paper 2',
    subtopics: [
      // 4.7.1 Adaptations, interdependence and competition
      'Communities',
      'Ecosystems',
      'Abiotic factors',
      'Biotic factors',
      'Adaptations',
      'Structural adaptations',
      'Behavioural adaptations',
      'Functional adaptations',
      'Extremophiles',
      'Competition',
      'Interdependence',
      'Food chains and food webs',
      // 4.7.2 Organisation of an ecosystem
      'Feeding relationships',
      'Producers',
      'Consumers',
      'Primary, secondary, tertiary consumers',
      'Predator-prey relationships',
      'Pyramids of biomass',
      // Required Practical
      'Sampling techniques',
      'Quadrats',
      'Transects',
      'Estimating population size',
      // Transfer of biomass
      'Energy transfer',
      'Efficiency of transfer',
      'Biomass for materials and fuels',
      // Decomposition
      'Decay',
      'Decomposers',
      'Factors affecting decomposition',
      'Composting',
      'Biogas generators',
      // 4.7.3 Biodiversity and the effect of human interaction
      'Biodiversity',
      'Importance of biodiversity',
      'Waste management',
      'Pollution',
      'Land use',
      'Deforestation',
      'Peat destruction',
      'Global warming',
      'Greenhouse gases',
      'Climate change effects',
      'Maintaining biodiversity',
      'Breeding programmes',
      'Seed banks',
      'Habitat protection',
      // 4.7.4 Trophic levels
      'Trophic levels and pyramids (H)',
      'Pyramids of biomass (H)',
      'Energy transfer calculations (H)',
      // Food security
      'Food security',
      'Factors affecting food security',
      'Sustainable fisheries',
      'Role of biotechnology',
      // Carbon cycle
      'The carbon cycle',
      'Photosynthesis in carbon cycle',
      'Respiration in carbon cycle',
      'Decomposition in carbon cycle',
      'Combustion in carbon cycle',
      // Water cycle
      'The water cycle',
      'Evaporation and condensation',
      'Precipitation',
      'Transpiration',
    ],
  },

  // ============================================================================
  // CHEMISTRY PAPER 1 TOPICS (C1-C5)
  // ============================================================================
  {
    id: 'combined-chemistry-atomic-structure',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Atomic Structure and the Periodic Table',
    description: 'Atoms, elements, compounds, mixtures, and the development of the periodic table',
    icon: '⚛️',
    color: 'bg-blue-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // 5.1.1 A simple model of the atom
      'Atoms, elements and compounds',
      'Structure of an atom',
      'Protons, neutrons and electrons',
      'Atomic number and mass number',
      'Electronic structure',
      'Electron shells',
      'Electron configuration notation',
      'Isotopes',
      'Relative atomic mass',
      'Calculating relative atomic mass from isotopes',
      // 5.1.2 The periodic table
      'Development of the periodic table',
      'Mendeleev\'s periodic table',
      'The modern periodic table',
      'Periods and groups',
      'Metals and non-metals',
      'Electronic structure and the periodic table',
      // Group 0: Noble gases
      'Group 0 - The noble gases',
      'Properties of noble gases',
      'Unreactivity of noble gases',
      'Uses of noble gases',
      'Boiling points of noble gases',
      // Group 1: Alkali metals
      'Group 1 - The alkali metals',
      'Properties of alkali metals',
      'Reactions with water',
      'Reactions with oxygen',
      'Reactions with chlorine',
      'Trends in Group 1 reactivity',
      // Group 7: Halogens
      'Group 7 - The halogens',
      'Properties of halogens',
      'Physical states of halogens',
      'Colours of halogens',
      'Reactions with metals',
      'Halide ion tests',
      'Displacement reactions of halogens',
      'Trends in Group 7 reactivity',
    ],
  },
  {
    id: 'combined-chemistry-bonding',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Bonding, Structure and Properties of Matter',
    description: 'Chemical bonds, types of structure, and properties of materials',
    icon: '🔗',
    color: 'bg-purple-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // 5.2.1 Chemical bonds
      'Chemical bonds',
      'Ionic bonding',
      'Formation of ions',
      'Dot and cross diagrams for ionic compounds',
      'Ionic compounds',
      'Covalent bonding',
      'Single covalent bonds',
      'Double covalent bonds',
      'Dot and cross diagrams for covalent molecules',
      'Metallic bonding',
      'Structure of metals',
      'Delocalised electrons',
      // 5.2.2 Properties of substances
      'Properties of ionic compounds',
      'Giant ionic lattices',
      'Melting and boiling points of ionic compounds',
      'Electrical conductivity of ionic compounds',
      'Properties of small molecules',
      'Weak intermolecular forces',
      'Strong covalent bonds within molecules',
      'Melting and boiling points of covalent molecules',
      'Polymers',
      'Properties of polymers',
      'Giant covalent structures',
      'Diamond structure and properties',
      'Graphite structure and properties',
      'Silicon dioxide structure',
      'Graphene',
      'Properties of graphene',
      'Fullerenes',
      'Buckminsterfullerene (C60)',
      'Carbon nanotubes',
      'Properties of metals',
      'Malleability and ductility',
      'Electrical and thermal conductivity of metals',
      'Alloys',
      'Properties of alloys',
      // 5.2.3 Structure and bonding of carbon
      'Allotropes of carbon',
      'Comparing diamond and graphite',
      'Uses of carbon allotropes',
    ],
  },
  {
    id: 'combined-chemistry-quantitative',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Quantitative Chemistry',
    description: 'Conservation of mass, moles, concentrations, and yield calculations',
    icon: '⚖️',
    color: 'bg-green-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // 5.3.1 Conservation of mass
      'Conservation of mass',
      'Balancing chemical equations',
      'Relative formula mass (Mr)',
      'Calculating relative formula mass',
      // 5.3.2 Amount of substance
      'The mole',
      'Avogadro constant',
      'Calculating moles from mass',
      'Calculating mass from moles',
      'Moles and balanced equations',
      'Reacting mass calculations',
      'Limiting reactants',
      'Excess reactants',
      // 5.3.3 Concentrations of solutions
      'Concentration in g/dm\u00B3',
      'Calculating concentration',
      'Calculating mass from concentration',
      'Calculating volume from concentration',
      'Concentration in mol/dm\u00B3 (H)',
      'Converting between concentration units (H)',
      // 5.3.4 Percentage yield and atom economy
      'Percentage yield',
      'Calculating percentage yield',
      'Reasons for less than 100% yield',
      'Atom economy',
      'Calculating atom economy',
      'Importance of atom economy',
      'Choosing reaction pathways',
    ],
  },
  {
    id: 'combined-chemistry-chemical-changes',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Changes',
    description: 'Reactivity, extraction of metals, reactions of acids, and electrolysis',
    icon: '🧪',
    color: 'bg-orange-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // 5.4.1 Reactivity of metals
      'Metal oxides and the reactivity series',
      'The reactivity series',
      'Reactions of metals with water',
      'Reactions of metals with acids',
      'Displacement reactions',
      'Oxidation and reduction (redox)',
      'Oxidation as gain of oxygen',
      'Reduction as loss of oxygen',
      'Oxidation as loss of electrons (H)',
      'Reduction as gain of electrons (H)',
      // 5.4.2 Extraction of metals
      'Extraction of metals and reduction',
      'Extraction using carbon',
      'Extraction of unreactive metals',
      'Extraction of aluminium by electrolysis',
      'Recycling metals',
      // 5.4.3 Reactions of acids
      'Acids and alkalis',
      'The pH scale',
      'Indicators',
      'Neutralisation reactions',
      'Reactions of acids with metals',
      'Reactions of acids with metal oxides',
      'Reactions of acids with metal hydroxides',
      'Reactions of acids with metal carbonates',
      'Making soluble salts',
      'Crystallisation',
      'Strong and weak acids (H)',
      'Hydrogen ion concentration (H)',
      'pH of strong and weak acids (H)',
      // 5.4.4 Electrolysis
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Anode and cathode',
      'Products at electrodes',
      'Electrolysis of molten compounds',
      'Electrolysis of aqueous solutions',
      'Electrolysis of aqueous sodium chloride',
      'Products at electrodes in aqueous solutions (H)',
      'Half equations (H)',
      'Extraction of aluminium by electrolysis',
      'Electrolysis of copper sulfate solution',
      'Purification of copper',
    ],
  },
  {
    id: 'combined-chemistry-energy',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Energy Changes',
    description: 'Exothermic and endothermic reactions, reaction profiles, and bond energies',
    icon: '🔥',
    color: 'bg-red-500',
    paperRestriction: 'Chemistry Paper 1',
    subtopics: [
      // 5.5.1 Exothermic and endothermic reactions
      'Energy transfer in reactions',
      'Exothermic reactions',
      'Examples of exothermic reactions',
      'Endothermic reactions',
      'Examples of endothermic reactions',
      'Measuring temperature changes',
      'Reaction profiles for exothermic reactions',
      'Reaction profiles for endothermic reactions',
      'Activation energy',
      'Effect of catalysts on reaction profiles',
      // 5.5.2 Bond energy calculations (HT)
      'Bond energies (H)',
      'Energy to break bonds (H)',
      'Energy released when bonds form (H)',
      'Calculating energy change from bond energies (H)',
      'Explaining exothermic reactions using bond energies (H)',
      'Explaining endothermic reactions using bond energies (H)',
    ],
  },

  // ============================================================================
  // CHEMISTRY PAPER 2 TOPICS (C6-C10)
  // ============================================================================
  {
    id: 'combined-chemistry-rates',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'The Rate and Extent of Chemical Change',
    description: 'Rates of reaction, factors affecting rate, and reversible reactions',
    icon: '⏱️',
    color: 'bg-yellow-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // 5.6.1 Rate of reaction
      'Rate of reaction',
      'Measuring rate of reaction',
      'Mean rate of reaction',
      'Calculating rate from graphs',
      'Factors affecting rate of reaction',
      'Effect of concentration on rate',
      'Effect of pressure on rate (gases)',
      'Effect of surface area on rate',
      'Effect of temperature on rate',
      'Effect of catalysts on rate',
      // 5.6.2 Collision theory
      'Collision theory',
      'Activation energy and collisions',
      'Explaining concentration effect',
      'Explaining surface area effect',
      'Explaining temperature effect',
      'Explaining catalyst effect',
      // 5.6.3 Catalysts
      'Catalysts',
      'How catalysts work',
      'Catalysts in industry',
      'Enzymes as biological catalysts',
      // 5.6.4 Reversible reactions
      'Reversible reactions',
      'Dynamic equilibrium (H)',
      'Closed systems (H)',
      'Le Chatelier\'s principle (H)',
      'Effect of temperature on equilibrium (H)',
      'Effect of pressure on equilibrium (H)',
      'Effect of concentration on equilibrium (H)',
    ],
  },
  {
    id: 'combined-chemistry-organic',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Organic Chemistry',
    description: 'Crude oil, hydrocarbons, alkanes, alkenes, and reactions of organic compounds',
    icon: '🛢️',
    color: 'bg-gray-700',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // 5.7.1 Carbon compounds as fuels and feedstock
      'Crude oil',
      'Hydrocarbons',
      'Fractional distillation of crude oil',
      'Fractions from crude oil',
      'Properties of hydrocarbon fractions',
      'Uses of hydrocarbon fractions',
      'Alkanes',
      'General formula of alkanes',
      'Displayed formulae of alkanes',
      'Structural formulae of alkanes',
      'Combustion of hydrocarbons',
      'Complete combustion',
      'Incomplete combustion',
      'Carbon monoxide',
      'Particulates (soot)',
      'Cracking',
      'Thermal cracking',
      'Catalytic cracking',
      'Products of cracking',
      // 5.7.2 Reactions of alkenes and alcohols
      'Alkenes',
      'General formula of alkenes',
      'The C=C double bond',
      'Displayed formulae of alkenes',
      'Structural formulae of alkenes',
      'Addition reactions of alkenes',
      'Addition polymerisation',
      'Polymers from alkenes',
      'Poly(ethene)',
      'Poly(propene)',
    ],
  },
  {
    id: 'combined-chemistry-analysis',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Analysis',
    description: 'Purity, formulations, chromatography, and identification of ions',
    icon: '🔬',
    color: 'bg-teal-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // 5.8.1 Purity, formulations and chromatography
      'Pure substances',
      'Melting point of pure substances',
      'Mixtures',
      'Formulations',
      'Examples of formulations',
      'Chromatography',
      'Paper chromatography',
      'Rf values',
      'Calculating Rf values',
      'Identifying substances using chromatography',
      // 5.8.2 Identification of common gases
      'Test for hydrogen',
      'Test for oxygen',
      'Test for carbon dioxide',
      'Test for chlorine',
      // 5.8.3 Identification of ions
      'Flame tests',
      'Flame test colours',
      'Identifying metal ions using flame tests',
      'Metal hydroxide precipitates',
      'Testing for carbonate ions',
      'Testing for halide ions',
      'Testing for sulfate ions',
    ],
  },
  {
    id: 'combined-chemistry-atmosphere',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemistry of the Atmosphere',
    description: 'Composition and evolution of the atmosphere, climate change, and pollutants',
    icon: '🌍',
    color: 'bg-cyan-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // 5.9.1 The composition and evolution of Earth's atmosphere
      'Composition of the atmosphere',
      'Proportions of gases in the atmosphere',
      'Evolution of the atmosphere',
      'Early atmosphere',
      'Volcanic activity and gases',
      'Formation of oceans',
      'Development of life',
      'Photosynthesis and oxygen',
      'Formation of fossil fuels',
      'Formation of sedimentary rocks',
      // 5.9.2 Carbon dioxide and methane as greenhouse gases
      'Greenhouse gases',
      'Carbon dioxide as a greenhouse gas',
      'Methane as a greenhouse gas',
      'Water vapour as a greenhouse gas',
      'The greenhouse effect',
      'Global warming',
      'Climate change',
      'Evidence for climate change',
      'Effects of climate change',
      'Reducing carbon dioxide emissions',
      'Carbon capture and storage',
      'Carbon footprint',
      // 5.9.3 Atmospheric pollutants
      'Atmospheric pollutants from fuels',
      'Carbon monoxide',
      'Sulfur dioxide',
      'Nitrogen oxides',
      'Particulates',
      'Acid rain',
      'Effects of acid rain',
      'Global dimming',
    ],
  },
  {
    id: 'combined-chemistry-resources',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Using Resources',
    description: 'Earth\'s resources, water treatment, life cycle assessments, and recycling',
    icon: '♻️',
    color: 'bg-emerald-500',
    paperRestriction: 'Chemistry Paper 2',
    subtopics: [
      // 5.10.1 Using Earth's resources
      'Natural resources',
      'Sustainable development',
      'Finite and renewable resources',
      'Agriculture and food production',
      // 5.10.2 Potable water
      'Potable water',
      'Drinking water',
      'Water treatment',
      'Sedimentation',
      'Filtration',
      'Chlorination',
      'Sterilisation',
      'Desalination',
      'Distillation',
      'Reverse osmosis',
      'Sewage treatment',
      'Aerobic and anaerobic digestion',
      // 5.10.3 Life cycle assessment
      'Life cycle assessment (LCA)',
      'Extracting raw materials',
      'Manufacturing and packaging',
      'Use and disposal',
      'Comparing LCAs',
      'Limitations of LCAs',
      'Reducing use of resources',
      'Reusing materials',
      'Recycling materials',
      // 5.10.4 Ways of reducing the use of resources
      'Recycling metals',
      'Recycling glass',
      'Recycling plastics',
      'Biodegradable materials',
      'Compostable materials',
    ],
  },

  // ============================================================================
  // PHYSICS PAPER 1 TOPICS (P1-P4)
  // ============================================================================
  {
    id: 'combined-physics-energy',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Energy',
    description: 'Energy stores, transfers, conservation, efficiency and national energy resources',
    icon: '⚡',
    color: 'bg-yellow-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // 6.1.1 Energy changes in a system
      'Energy stores (kinetic, thermal, chemical, elastic, gravitational, nuclear, magnetic, electrostatic)',
      'Energy transfers between stores',
      'Work done as energy transfer',
      'Closed systems and energy conservation',
      // Changes in energy
      'Kinetic energy calculations (KE = \u00BDmv\u00B2)',
      'Elastic potential energy calculations (EPE = \u00BDke\u00B2)',
      'Gravitational potential energy calculations (GPE = mgh)',
      'Changes in energy between stores',
      // Energy changes in systems
      'Specific heat capacity',
      'Calculating energy change for temperature change (E = mc\u0394\u03B8)',
      'Required Practical: Investigating specific heat capacity',
      'Power as rate of energy transfer (P = E/t)',
      'Power calculations (P = W/t)',
      // 6.1.2 Conservation and dissipation of energy
      'Energy dissipation',
      'Energy transfer by heating',
      'Reducing unwanted energy transfers',
      'Thermal conductivity of materials',
      // Efficiency
      'Calculating efficiency',
      'Efficiency as a decimal or percentage',
      'Increasing efficiency of energy transfers',
      'Wasted energy and dissipation',
      // 6.1.3 National and global energy resources
      'Main energy resources',
      'Renewable energy resources (solar, wind, hydroelectric, tidal, wave, geothermal, biomass)',
      'Non-renewable energy resources (fossil fuels, nuclear)',
      'Advantages and disadvantages of energy resources',
      'Environmental impacts of energy generation',
      'Energy resource reliability and cost',
      'Social and economic considerations',
      'Trends in energy resource use',
      'Comparing power output of different resources',
    ],
  },
  {
    id: 'combined-physics-electricity',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Electricity',
    description: 'Current, circuits, resistance, domestic electricity and power',
    icon: '🔌',
    color: 'bg-blue-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // 6.2.1 Current, potential difference and resistance
      'Circuit symbols (cell, battery, switch, resistor, variable resistor, lamp, fuse, voltmeter, ammeter, diode, LED, thermistor, LDR)',
      'Drawing and interpreting circuit diagrams',
      'Electric current as flow of charge',
      'Charge calculation (Q = It)',
      'Electrons as charge carriers in metals',
      'Current in circuits (same everywhere in series)',
      'Potential difference (voltage)',
      'Resistance and its effect on current',
      'Ohm\'s law (V = IR)',
      'Calculating resistance',
      'Required Practical: Investigating resistance',
      'Factors affecting resistance (length, cross-sectional area, material)',
      // Resistors
      'Ohmic conductors (constant resistance)',
      'Non-ohmic conductors (changing resistance)',
      'Required Practical: I-V characteristics',
      'I-V graph for resistor (straight line through origin)',
      'I-V graph for filament lamp (curved)',
      'I-V graph for diode (one direction only)',
      'Thermistors (resistance decreases as temperature increases)',
      'Light-dependent resistors (resistance decreases as light intensity increases)',
      'Applications of thermistors and LDRs',
      // 6.2.2 Series and parallel circuits
      'Series circuit rules',
      'Current the same throughout series circuit',
      'Total potential difference shared between components',
      'Adding resistances in series (Rtotal = R1 + R2)',
      'Parallel circuit rules',
      'Potential difference same across parallel branches',
      'Current splits at junctions',
      'Total current is sum of currents through branches',
      'Total resistance less than smallest individual resistor (H)',
      'Calculating resistance in parallel (1/Rt = 1/R1 + 1/R2) (H)',
      // 6.2.3 Domestic uses and safety
      'Direct current (dc) and alternating current (ac)',
      'UK mains supply (230V, 50Hz)',
      'Frequency and potential difference of ac',
      'Three-wire cable (live, neutral, earth)',
      'Live wire (brown) carries alternating potential',
      'Neutral wire (blue) completes circuit',
      'Earth wire (green/yellow) safety wire',
      'Why the live wire is dangerous',
      'Fuses and circuit breakers',
      'Earth wire and fuse protection',
      // 6.2.4 Energy transfers
      'Electrical power (P = IV)',
      'Power in terms of resistance (P = I\u00B2R)',
      'Power in terms of resistance (P = V\u00B2/R)',
      'Energy transfer in appliances',
      'Calculating energy transferred (E = Pt)',
      'Calculating energy transferred (E = QV)',
      'Work done by electrical transfer (E = IVt)',
      // The National Grid
      'Structure of the National Grid',
      'Step-up transformers',
      'Step-down transformers',
      'Why high voltage transmission is efficient',
      'Reducing power loss in transmission (P = I\u00B2R)',
    ],
  },
  {
    id: 'combined-physics-particle-model',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Particle Model of Matter',
    description: 'States of matter, changes of state, internal energy and pressure',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // 6.3.1 Changes of state and the particle model
      'Density definition (mass per unit volume)',
      'Density equation (\u03C1 = m/V)',
      'Density of solids, liquids and gases',
      'Required Practical: Measuring density',
      'Measuring density of regular solids',
      'Measuring density of irregular solids (displacement)',
      'Measuring density of liquids',
      // Changes of state
      'Three states of matter (solid, liquid, gas)',
      'Particle arrangement in solids, liquids, gases',
      'Particle motion in solids, liquids, gases',
      'Melting and freezing',
      'Boiling and condensing',
      'Sublimation',
      'Physical changes vs chemical changes',
      'Conservation of mass during state changes',
      // 6.3.2 Internal energy and energy transfers
      'Internal energy definition',
      'Kinetic energy of particles',
      'Potential energy of particles',
      'How heating changes internal energy',
      'Temperature and kinetic energy',
      // Temperature changes in a system
      'Specific heat capacity definition',
      'Factors affecting energy needed for temperature change',
      'Calculating energy for temperature change (E = mc\u0394\u03B8)',
      // Changes of state
      'Specific latent heat definition',
      'Latent heat of fusion',
      'Latent heat of vaporisation',
      'Calculating energy for state change (E = mL)',
      'Why latent heat involves no temperature change',
      'Heating and cooling curves',
      // 6.3.3 Particle model and pressure
      'Random motion of gas particles',
      'Gas pressure from particle collisions',
      'Temperature and particle speed',
      // Pressure in gases (H)
      'Relationship between pressure, volume and temperature (H)',
      'Pressure-volume relationship at constant temperature (pV = constant) (H)',
      'Work done on gas increases temperature (H)',
      'Explaining pressure changes using particle model (H)',
    ],
  },
  {
    id: 'combined-physics-atomic-structure',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Atomic Structure',
    description: 'Atoms, isotopes, radioactive decay, nuclear radiation and nuclear energy',
    icon: '⚛️',
    color: 'bg-green-500',
    paperRestriction: 'Physics Paper 1',
    subtopics: [
      // 6.4.1 Atoms and isotopes
      'Atomic structure (protons, neutrons, electrons)',
      'Size of atoms and nuclei',
      'Atomic radius (about 10\u207B\u00B9\u2070 m)',
      'Nuclear radius (about 10\u207B\u00B9\u2075 m)',
      'Relative masses and charges of subatomic particles',
      // Mass number, atomic number and isotopes
      'Mass number (nucleon number)',
      'Atomic number (proton number)',
      'Calculating neutron number',
      'Isotopes definition',
      'Isotope notation',
      // Development of the model of the atom
      'History of atomic models',
      'Dalton\'s solid sphere model',
      'Thomson\'s plum pudding model',
      'Rutherford\'s nuclear model (alpha scattering)',
      'Bohr\'s model (electron shells)',
      'How experimental evidence led to model changes',
      // 6.4.2 Atoms and nuclear radiation
      'Radioactive decay as a random process',
      'Activity and count rate',
      'Alpha decay (\u03B1) - helium nuclei',
      'Beta decay (\u03B2) - electrons from nucleus',
      'Gamma radiation (\u03B3) - electromagnetic waves',
      'Neutron emission',
      'Nuclear equations for decay',
      'Changes to mass number and atomic number in decay',
      // Nuclear equations
      'Writing balanced nuclear equations',
      'Alpha decay equations',
      'Beta decay equations',
      'Conservation of mass number',
      'Conservation of atomic number',
      // Half-lives
      'Half-life definition',
      'Calculating half-life from data',
      'Using half-life to determine remaining activity',
      'Half-life and radioactive dating',
      'Decay curves and graphs',
      // Radioactive contamination
      'Contamination vs irradiation',
      'Hazards of radioactive contamination',
      'Hazards of irradiation',
      'Comparing risks of contamination and irradiation',
      // 6.4.3 Hazards and uses of radioactive emissions
      'Sources of background radiation',
      'Natural sources (rocks, cosmic rays, radon, food)',
      'Man-made sources (medical, nuclear industry, fallout)',
      'Factors affecting background radiation',
      // Uses of nuclear radiation
      'Medical tracers (diagnostic imaging)',
      'Radiotherapy (cancer treatment)',
      'Sterilisation of medical equipment',
      // 6.4.4 Nuclear fission and nuclear fusion
      'Nuclear fission definition',
      'Induced fission with neutrons',
      'Chain reactions',
      'Controlling chain reactions (moderators, control rods)',
      'Nuclear reactor operation',
      'Energy release from fission',
      'Nuclear fusion definition',
      'Fusion in stars',
      'Conditions needed for fusion',
      'Energy release from fusion',
      'Why fusion is difficult to achieve on Earth',
      'Comparing fission and fusion',
    ],
  },

  // ============================================================================
  // PHYSICS PAPER 2 TOPICS (P5-P7) - NO SPACE PHYSICS IN COMBINED SCIENCE
  // ============================================================================
  {
    id: 'combined-physics-forces',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Forces',
    description: 'Forces, motion, Newton\'s laws, and momentum',
    icon: '🏋️',
    color: 'bg-red-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // 6.5.1 Forces and their interactions
      'Scalar quantities (magnitude only)',
      'Vector quantities (magnitude and direction)',
      'Examples of scalars (speed, distance, mass, temperature, time)',
      'Examples of vectors (velocity, displacement, force, acceleration, momentum)',
      'Representing vectors as arrows',
      // Contact and non-contact forces
      'Contact forces (friction, air resistance, tension, normal contact force)',
      'Non-contact forces (gravitational, electrostatic, magnetic)',
      // Gravity
      'Weight as a force (gravitational force)',
      'Weight equation (W = mg)',
      'Mass vs weight',
      'Gravitational field strength (g)',
      'Centre of mass',
      // Resultant forces
      'Resultant force definition',
      'Adding forces in same direction',
      'Adding forces in opposite directions',
      'Free body diagrams',
      'Balanced and unbalanced forces',
      'Scale drawings for resultant forces (H)',
      'Resolving forces into components (H)',
      // 6.5.2 Work done and energy transfer
      'Work done definition',
      'Work done equation (W = Fs)',
      'Work done against friction',
      'Work done and energy transfer',
      'Joules as units of work and energy',
      // 6.5.3 Forces and elasticity
      'Elastic deformation',
      'Plastic deformation',
      'Extension and force relationship',
      'Hooke\'s law (F = ke)',
      'Spring constant',
      'Limit of proportionality',
      'Required Practical: Force and extension',
      'Force-extension graphs',
      'Linear and non-linear regions',
      'Elastic potential energy stored',
      'Calculating elastic potential energy (E = \u00BDke\u00B2)',
      // 6.5.4 Forces and motion
      'Distance and displacement',
      'Speed and velocity',
      'Average speed calculation',
      'Distance-time graphs',
      'Gradient of distance-time graph as speed',
      'Velocity-time graphs',
      'Gradient of velocity-time graph as acceleration',
      'Area under velocity-time graph as displacement',
      'Interpreting motion graphs',
      'Acceleration definition',
      'Acceleration equation (a = \u0394v/t)',
      // Newton's Laws
      'Newton\'s First Law',
      'Inertia and mass',
      'Newton\'s Second Law',
      'Force-mass-acceleration (F = ma)',
      'Required Practical: Investigating acceleration',
      'Newton\'s Third Law',
      'Action-reaction pairs',
      'Applying Newton\'s laws to calculations',
      // Forces and braking
      'Stopping distance',
      'Thinking distance',
      'Braking distance',
      'Factors affecting thinking distance (speed, tiredness, drugs, distractions)',
      'Factors affecting braking distance (speed, road conditions, tyre conditions, brake conditions)',
      'Kinetic energy and braking',
      'Dangers of high speed (KE proportional to v\u00B2)',
      'Braking force and deceleration',
      'Friction and energy dissipation in brakes',
      // Uniform acceleration equations (H)
      'Uniform acceleration equations (suvat) (H)',
      'v\u00B2 = u\u00B2 + 2as (H)',
      's = ut + \u00BDat\u00B2 (H)',
      'Applying equations of motion (H)',
      // Momentum (H)
      'Momentum definition (H)',
      'Momentum equation (p = mv) (H)',
      'Conservation of momentum (H)',
      'Momentum in collisions (H)',
      // Terminal velocity
      'Terminal velocity definition',
      'Forces on falling objects',
      'Air resistance and speed',
      'Reaching terminal velocity',
      'Terminal velocity examples (skydiving)',
      'Parachutes and terminal velocity',
    ],
  },
  {
    id: 'combined-physics-waves',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Waves',
    description: 'Wave properties, electromagnetic spectrum, and sound',
    icon: '🌊',
    color: 'bg-cyan-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // 6.6.1 Waves in air, fluids and solids
      'Wave definition (energy transfer)',
      'Transverse waves',
      'Longitudinal waves',
      'Examples of transverse waves (light, water waves, S-waves)',
      'Examples of longitudinal waves (sound, ultrasound, P-waves)',
      'Compressions and rarefactions',
      // Properties of waves
      'Amplitude',
      'Wavelength',
      'Frequency',
      'Period',
      'Wave equation (v = f\u03BB)',
      'Wave speed calculations',
      'Period-frequency relationship (T = 1/f)',
      'Required Practical: Measuring wave speed',
      'Ripple tank investigations',
      'Measuring speed of sound',
      // Reflection and absorption
      'Reflection of waves',
      'Law of reflection',
      'Absorption of waves',
      'Transmission of waves',
      // Sound waves
      'Sound as longitudinal waves',
      'Human hearing range (20 Hz to 20 kHz)',
      'Ultrasound (above 20 kHz)',
      'Infrasound (below 20 Hz)',
      'Sound wave detection (microphone, ear)',
      // 6.6.2 Electromagnetic waves
      'Electromagnetic spectrum',
      'EM waves as transverse waves',
      'Speed of EM waves in vacuum (3 \u00D7 10\u2078 m/s)',
      'Radio waves',
      'Microwaves',
      'Infrared radiation',
      'Visible light',
      'Ultraviolet radiation',
      'X-rays',
      'Gamma rays',
      'Relative wavelengths and frequencies',
      // Properties of EM waves
      'Common properties of all EM waves',
      'Differences between EM waves',
      'Refraction of EM waves',
      'Absorption and transmission',
      'Reflection of EM waves',
      // Uses and applications
      'Radio waves (TV, radio, communications)',
      'Microwaves (cooking, satellite communication, mobile phones)',
      'Infrared (heating, thermal imaging, remote controls)',
      'Visible light (vision, photography, illumination)',
      'Ultraviolet (fluorescent lamps, detecting counterfeit notes)',
      'X-rays (medical imaging, airport security)',
      'Gamma rays (sterilisation, cancer treatment)',
      // Hazards
      'Ionising vs non-ionising radiation',
      'UV radiation hazards (skin cancer, eye damage)',
      'X-ray hazards (cell damage, cancer)',
      'Gamma ray hazards (cell damage, cancer)',
      'Microwave hazards (internal heating of body tissue)',
      'Safety precautions',
    ],
  },
  {
    id: 'combined-physics-magnetism',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Magnetism and Electromagnetism',
    description: 'Magnets, magnetic fields, electromagnets, and motors',
    icon: '🧲',
    color: 'bg-indigo-500',
    paperRestriction: 'Physics Paper 2',
    subtopics: [
      // 6.7.1 Permanent and induced magnetism
      'Magnetic poles (north and south)',
      'Like poles repel, unlike poles attract',
      'Magnetic materials (iron, steel, cobalt, nickel)',
      'Permanent magnets',
      'Induced magnetism',
      // Magnetic fields
      'Magnetic field definition',
      'Magnetic field lines',
      'Direction of magnetic field',
      'Field strength and line spacing',
      'Plotting magnetic fields (compass method)',
      'Earth\'s magnetic field',
      // 6.7.2 The motor effect
      'Magnetic field around a current-carrying wire',
      'Right-hand grip rule',
      'Magnetic field of a solenoid',
      'Electromagnets',
      'Increasing electromagnet strength',
      'Uses of electromagnets',
      // Fleming's left-hand rule
      'Motor effect',
      'Force on a current-carrying wire in a magnetic field',
      'Fleming\'s left-hand rule',
      'Factors affecting force (current, field strength, length)',
      'Force equation (F = BIL) (H)',
      // Electric motors
      'DC motor construction',
      'Split-ring commutator',
      'How DC motors work',
      'Increasing motor speed',
      'Increasing motor force',
      // 6.7.3 Induced potential and transformers (H)
      'Electromagnetic induction (H)',
      'Factors affecting induced potential (H)',
      'Generator effect (H)',
      'Inducing potential in a wire (H)',
      'Inducing potential in a coil (H)',
      'AC generators (alternators) (H)',
      // Transformers (H)
      'Transformer construction (H)',
      'How transformers work (H)',
      'Step-up transformers (H)',
      'Step-down transformers (H)',
      'Transformer equation (Vp/Vs = Np/Ns) (H)',
      'Transformer power equation (VpIp = VsIs) (H)',
      'National Grid and transformers (H)',
    ],
  },
];

export function getAQACombinedScienceTopicById(id: string): Topic | undefined {
  return aqaCombinedScienceTopics.find((topic) => topic.id === id);
}

export function getAQACombinedScienceTopicsByPaper(science: 'biology' | 'chemistry' | 'physics', paper: 1 | 2): Topic[] {
  const paperName = `${science.charAt(0).toUpperCase() + science.slice(1)} Paper ${paper}`;
  return aqaCombinedScienceTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countAQACombinedScienceSubtopics(): number {
  return aqaCombinedScienceTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
