// AQA GCSE Business (8132) Topics
// Based on the official AQA specification
// Reference: https://www.aqa.org.uk/subjects/business/gcse/business-8132/specification
// Paper 1: Influences of operations and HRM on business activity (50%)
// Paper 2: Influences of marketing and finance on business activity (50%)

import { Topic } from '@/types';

export const aqaGCSEBusinessTopics: Topic[] = [
  // ============================================================================
  // SECTION 3.1: BUSINESS IN THE REAL WORLD
  // Assessed in Paper 1 and Paper 2
  // ============================================================================
  {
    id: 'aqa-gcse-bus-real-world',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Business in the Real World',
    description: 'Purpose of business, ownership, objectives, and stakeholders',
    icon: '🏢',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1, Paper 2',
    subtopics: [
      // 3.1.1 The purpose and nature of businesses
      'Purpose of business activity',
      'Goods and services',
      'Needs and wants',
      'Factors of production',
      'Land',
      'Labour',
      'Capital',
      'Enterprise',
      'Adding value',
      'Methods of adding value',
      'Sectors of business',
      'Primary sector',
      'Secondary sector',
      'Tertiary sector',
      'Enterprise',
      'Entrepreneurs',
      'Characteristics of entrepreneurs',
      'Risk and reward',
      'Role of business enterprise',
      // 3.1.2 Business ownership
      'Sole traders',
      'Advantages of sole traders',
      'Disadvantages of sole traders',
      'Partnerships',
      'Advantages of partnerships',
      'Disadvantages of partnerships',
      'Partnership agreements',
      'Limited liability',
      'Unlimited liability',
      'Private limited companies (Ltd)',
      'Advantages of Ltd',
      'Disadvantages of Ltd',
      'Public limited companies (PLC)',
      'Advantages of PLC',
      'Disadvantages of PLC',
      'Shares and shareholders',
      'Dividends',
      'Not-for-profit organisations',
      'Social enterprises',
      // 3.1.3 Setting business aims and objectives
      'Business aims',
      'Business objectives',
      'Financial objectives',
      'Survival',
      'Profit',
      'Sales',
      'Market share',
      'Non-financial objectives',
      'Social objectives',
      'Customer satisfaction',
      'Employee welfare',
      'Why objectives differ',
      'Size of business',
      'Stage of development',
      'Competitive environment',
      // 3.1.4 Stakeholders
      'Stakeholders',
      'Internal stakeholders',
      'External stakeholders',
      'Owners/shareholders',
      'Employees',
      'Customers',
      'Suppliers',
      'Local community',
      'Pressure groups',
      'Government',
      'Stakeholder objectives',
      'Stakeholder conflict',
      // 3.1.5 Business location
      'Business location',
      'Factors affecting location',
      'Proximity to market',
      'Proximity to materials',
      'Proximity to labour',
      'Transport links',
      'Costs of premises',
      'Technology and location',
      'E-commerce impact on location',
      // 3.1.6 Business planning
      'Business planning',
      'Business plans',
      'Purpose of business plans',
      'Components of business plan',
      'Executive summary',
      'Business description',
      'Market analysis',
      'Financial projections',
    ],
  },

  // ============================================================================
  // SECTION 3.2: INFLUENCES ON BUSINESS
  // Assessed in Paper 1 and Paper 2
  // ============================================================================
  {
    id: 'aqa-gcse-bus-influences',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Influences on Business',
    description: 'Technology, ethical, environmental, economic, and legal influences',
    icon: '🌍',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1, Paper 2',
    subtopics: [
      // 3.2.1 Technology
      'Technology in business',
      'E-commerce',
      'Benefits of e-commerce',
      'Drawbacks of e-commerce',
      'Digital communication',
      'Social media',
      'Payment systems',
      'Technology and costs',
      'Automation',
      'Technology and productivity',
      'Technology and marketing',
      'Technology and customer service',
      // 3.2.2 Ethical and environmental considerations
      'Business ethics',
      'Ethical issues',
      'Fair trade',
      'Working conditions',
      'Environmental issues',
      'Sustainability',
      'Carbon footprint',
      'Recycling',
      'Pollution',
      'Waste management',
      'Renewable resources',
      'Trade-offs',
      'Profit vs ethics',
      'Short-term vs long-term',
      // 3.2.3 The economic climate
      'Economic climate',
      'Interest rates',
      'Effects of interest rate changes',
      'Exchange rates',
      'Effects of exchange rate changes',
      'Inflation',
      'Effects of inflation',
      'Unemployment',
      'Effects of unemployment',
      'Economic growth',
      'Effects of economic growth',
      'Recession',
      'Effects of recession',
      'Consumer confidence',
      'Government taxation',
      'Government spending',
      // 3.2.4 Globalisation
      'Globalisation',
      'International trade',
      'Imports',
      'Exports',
      'Benefits of globalisation',
      'Drawbacks of globalisation',
      'Impact on UK businesses',
      'Competition from abroad',
      'Opportunities abroad',
      // 3.2.5 Legislation
      'Consumer protection',
      'Consumer Rights Act',
      'Sale of Goods Act',
      'Employment law',
      'Minimum wage',
      'Working hours',
      'Discrimination law',
      'Health and safety',
      'Impact of legislation',
      'Costs of compliance',
      // 3.2.6 Competitive environment
      'Competition',
      'Competitors',
      'Competitive advantage',
      'Price competition',
      'Non-price competition',
      'Market conditions',
      'Responding to competition',
    ],
  },

  // ============================================================================
  // SECTION 3.3: BUSINESS OPERATIONS
  // Assessed in Paper 1
  // ============================================================================
  {
    id: 'aqa-gcse-bus-operations',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Business Operations',
    description: 'Production, quality, and supply chain management',
    icon: '⚙️',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.3.1 Production processes
      'Production',
      'Production processes',
      'Job production',
      'Advantages of job production',
      'Disadvantages of job production',
      'Batch production',
      'Advantages of batch production',
      'Disadvantages of batch production',
      'Flow production',
      'Advantages of flow production',
      'Disadvantages of flow production',
      'Choosing production method',
      // 3.3.2 The role of procurement
      'Procurement',
      'Choosing suppliers',
      'Price',
      'Quality',
      'Reliability',
      'Flexibility',
      'Managing stock',
      'Stock control',
      'Just-in-time (JIT)',
      'Just-in-case',
      'Buffer stocks',
      'Lead time',
      'Costs of holding stock',
      'Costs of running out of stock',
      // 3.3.3 The concept of quality
      'Quality',
      'Quality of design',
      'Quality of conformance',
      'Quality control',
      'Quality assurance',
      'Benefits of quality',
      'Costs of quality',
      'Costs of poor quality',
      // 3.3.4 Customer service
      'Customer service',
      'Importance of customer service',
      'Elements of customer service',
      'Product knowledge',
      'Speed of service',
      'Customer engagement',
      'After-sales service',
      'Customer feedback',
      'Customer loyalty',
    ],
  },

  // ============================================================================
  // SECTION 3.4: HUMAN RESOURCES
  // Assessed in Paper 1
  // ============================================================================
  {
    id: 'aqa-gcse-bus-human-resources',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Human Resources',
    description: 'Recruitment, training, motivation, and organisational structure',
    icon: '👥',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.4.1 Organisational structures
      'Organisational structure',
      'Hierarchy',
      'Chain of command',
      'Span of control',
      'Levels of hierarchy',
      'Tall structures',
      'Flat structures',
      'Advantages of tall structures',
      'Advantages of flat structures',
      'Centralisation',
      'Decentralisation',
      'Advantages of centralisation',
      'Advantages of decentralisation',
      // 3.4.2 Recruitment and selection
      'Recruitment',
      'Identifying vacancies',
      'Job descriptions',
      'Person specifications',
      'Internal recruitment',
      'External recruitment',
      'Advantages of internal recruitment',
      'Advantages of external recruitment',
      'Selection',
      'Application forms',
      'CVs',
      'Interviews',
      'References',
      // 3.4.3 Motivation and retention
      'Motivation',
      'Benefits of motivated staff',
      'Financial motivation',
      'Remuneration',
      'Wages',
      'Salaries',
      'Commission',
      'Bonus',
      'Profit sharing',
      'Non-financial motivation',
      'Job rotation',
      'Job enrichment',
      'Autonomy',
      'Fringe benefits',
      'Training',
      'On-the-job training',
      'Off-the-job training',
      'Benefits of training',
      'Costs of training',
      // 3.4.4 Training
      'Induction training',
      'Purpose of training',
      'Appraisals',
      'Performance management',
    ],
  },

  // ============================================================================
  // SECTION 3.5: MARKETING
  // Assessed in Paper 2
  // ============================================================================
  {
    id: 'aqa-gcse-bus-marketing',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Marketing',
    description: 'Market research, segmentation, and marketing mix',
    icon: '📊',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.5.1 Identifying and understanding customers
      'Marketing',
      'Purpose of marketing',
      'Market',
      'Market segmentation',
      'Demographic segmentation',
      'Geographic segmentation',
      'Income segmentation',
      'Benefits of segmentation',
      'Target market',
      // 3.5.2 Market research
      'Market research',
      'Purpose of market research',
      'Primary research',
      'Surveys',
      'Questionnaires',
      'Focus groups',
      'Observation',
      'Secondary research',
      'Internet research',
      'Market reports',
      'Government statistics',
      'Qualitative data',
      'Quantitative data',
      'Limitations of market research',
      // 3.5.3 The marketing mix: product
      'Marketing mix',
      '4Ps',
      'Product',
      'Product design',
      'Product differentiation',
      'USP (Unique Selling Point)',
      'Brand',
      'Brand image',
      'Brand loyalty',
      'Product life cycle',
      'Introduction stage',
      'Growth stage',
      'Maturity stage',
      'Decline stage',
      'Extension strategies',
      'Product portfolio',
      'Boston Matrix',
      'Stars',
      'Cash cows',
      'Question marks',
      'Dogs',
      // 3.5.4 The marketing mix: price
      'Price',
      'Pricing strategies',
      'Cost-plus pricing',
      'Competitive pricing',
      'Penetration pricing',
      'Price skimming',
      'Psychological pricing',
      'Factors affecting price',
      'Costs',
      'Competition',
      'Target market',
      'Product life cycle stage',
      // 3.5.5 The marketing mix: promotion
      'Promotion',
      'Aims of promotion',
      'Informing',
      'Persuading',
      'Reminding',
      'Advertising',
      'Types of advertising',
      'Sales promotion',
      'Discounts',
      'BOGOF',
      'Competitions',
      'Sponsorship',
      'Public relations',
      'Social media marketing',
      'Viral marketing',
      // 3.5.6 The marketing mix: place
      'Place',
      'Distribution channels',
      'Direct selling',
      'Retailers',
      'Wholesalers',
      'E-commerce',
      'Multi-channel distribution',
      'Factors affecting distribution',
    ],
  },

  // ============================================================================
  // SECTION 3.6: FINANCE
  // Assessed in Paper 2
  // ============================================================================
  {
    id: 'aqa-gcse-bus-finance',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'business',
    name: 'Finance',
    description: 'Sources of finance, cash flow, and financial performance',
    icon: '💰',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.6.1 Sources of finance
      'Finance',
      'Why businesses need finance',
      'Start-up costs',
      'Running costs',
      'Expansion costs',
      'Internal sources of finance',
      'Retained profit',
      'Sale of assets',
      'External sources of finance',
      'Family and friends',
      'Bank loans',
      'Overdrafts',
      'Trade credit',
      'Crowdfunding',
      'Peer-to-peer lending',
      'Share capital',
      'Venture capital',
      'Choosing sources of finance',
      // 3.6.2 Revenue, costs and profit
      'Revenue',
      'Calculating revenue',
      'Total revenue',
      'Costs',
      'Fixed costs',
      'Variable costs',
      'Total costs',
      'Calculating total costs',
      'Profit',
      'Gross profit',
      'Net profit',
      'Calculating profit',
      'Profit margin',
      'Interest',
      // 3.6.3 Break-even
      'Break-even',
      'Break-even point',
      'Calculating break-even',
      'Break-even formula',
      'Contribution',
      'Contribution per unit',
      'Break-even charts',
      'Margin of safety',
      'Benefits of break-even analysis',
      'Limitations of break-even analysis',
      // 3.6.4 Cash and cash flow
      'Cash',
      'Importance of cash',
      'Cash vs profit',
      'Cash flow',
      'Cash inflows',
      'Cash outflows',
      'Net cash flow',
      'Cash flow forecasts',
      'Opening balance',
      'Closing balance',
      'Cash flow problems',
      'Causes of cash flow problems',
      'Solutions to cash flow problems',
      // 3.6.5 Financial terms and calculations
      'Gross profit margin',
      'Calculating gross profit margin',
      'Net profit margin',
      'Calculating net profit margin',
      'Average rate of return',
      'Calculating ARR',
      'Interpreting financial data',
    ],
  },
];

// Helper function to get topic by ID
export function getAQAGCSEBusinessTopicById(id: string): Topic | undefined {
  return aqaGCSEBusinessTopics.find(topic => topic.id === id);
}
