// OCR Gateway GCSE Biology A (J247) Topics
// Based on the official OCR Gateway Science specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/gateway-science-suite-biology-a-j247-from-2016/

import { Topic } from '@/types';

export const ocrBiologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1 & 3 TOPICS (B1-B3, B7)
  // ============================================================================
  {
    id: 'ocr-gcse-biology-cell-level-systems',
    examBoard: 'ocr',
    name: 'Cell Level Systems',
    description: 'Cell structure, transport, division, and stem cells',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1/3',
    subtopics: [
      // B1.1 Cell structures
      'Eukaryotic cells',
      'Prokaryotic cells',
      'Animal cell structure',
      'Plant cell structure',
      'Bacterial cell structure',
      'Nucleus',
      'Cytoplasm',
      'Cell membrane',
      'Mitochondria',
      'Ribosomes',
      'Chloroplasts',
      'Permanent vacuole',
      'Cell wall',
      'Plasmids',
      'PAG: Microscopy',
      // B1.2 What happens in cells
      'Enzymes',
      'Lock and key model',
      'Active site',
      'Enzyme specificity',
      'Factors affecting enzymes',
      'Temperature and enzymes',
      'pH and enzymes',
      'Denaturation',
      'PAG: Enzyme investigation',
      // B1.3 Respiration
      'Aerobic respiration',
      'Aerobic respiration equation',
      'Anaerobic respiration',
      'Anaerobic respiration in muscles',
      'Lactic acid',
      'Fermentation in yeast',
      'Oxygen debt',
      // B1.4 Photosynthesis
      'Photosynthesis equation',
      'Chlorophyll',
      'Adaptations of leaves',
      'Factors affecting photosynthesis',
      'Light intensity',
      'Carbon dioxide concentration',
      'Temperature',
      'Limiting factors',
      'Uses of glucose',
      'PAG: Photosynthesis investigation',
    ],
  },
  {
    id: 'ocr-gcse-biology-scaling-up',
    examBoard: 'ocr',
    name: 'Scaling Up',
    description: 'Cell division, growth, and stem cells',
    icon: '📈',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1/3',
    subtopics: [
      // B2.1 Cell division
      'The cell cycle',
      'Mitosis',
      'Stages of mitosis',
      'Chromosomes',
      'DNA replication',
      'Growth',
      'Percentile charts',
      'Meiosis',
      'Gametes',
      'Genetic variation',
      'Cancer',
      // B2.2 Growth
      'Cell differentiation',
      'Specialised cells',
      'Tissues',
      'Organs',
      'Organ systems',
      // B2.3 Stem cells
      'Stem cells',
      'Embryonic stem cells',
      'Adult stem cells',
      'Uses of stem cells',
      'Meristems',
      'Plant cloning',
      'Ethical issues',
    ],
  },
  {
    id: 'ocr-gcse-biology-organism-level',
    examBoard: 'ocr',
    name: 'Organism Level Systems',
    description: 'Nervous system, hormones, and homeostasis',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1/3',
    subtopics: [
      // B3.1 Nervous system
      'Coordinating body responses',
      'Central nervous system',
      'Peripheral nervous system',
      'Receptors',
      'Effectors',
      'Neurones',
      'Sensory neurones',
      'Relay neurones',
      'Motor neurones',
      'Synapses',
      'Neurotransmitters',
      'Reflex arc',
      'Reflex actions',
      'PAG: Reaction time',
      // B3.2 The eye
      'Structure of the eye',
      'Cornea',
      'Iris',
      'Pupil',
      'Lens',
      'Retina',
      'Optic nerve',
      'Accommodation',
      'Vision defects',
      'Myopia and hyperopia',
      // B3.3 Hormones
      'Endocrine system',
      'Hormones vs nervous system',
      'Glands',
      'Pituitary gland',
      'Thyroid gland',
      'Pancreas',
      'Adrenal glands',
      'Reproductive organs',
      // B3.3 Homeostasis
      'Definition of homeostasis',
      'Control systems',
      'Negative feedback',
      'Temperature regulation',
      'Thermoregulation',
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Diabetes Type 1',
      'Diabetes Type 2',
      // B3.3 Water balance
      'Kidneys',
      'Structure of kidney',
      'Nephron',
      'Filtration',
      'Reabsorption',
      'ADH',
      'Urine',
      'Kidney failure',
      'Dialysis',
      'Kidney transplant',
      // B3.4 Hormones and reproduction
      'Puberty',
      'Menstrual cycle',
      'FSH',
      'LH',
      'Oestrogen',
      'Progesterone',
      'Contraception',
      'Hormonal contraception',
      'IVF',
      'Fertility treatments',
    ],
  },

  // ============================================================================
  // PAPER 2 & 4 TOPICS (B4-B6, B7)
  // ============================================================================
  {
    id: 'ocr-gcse-biology-community',
    examBoard: 'ocr',
    name: 'Community Level Systems',
    description: 'Ecosystems, biodiversity, and human impact',
    icon: '🌍',
    color: 'bg-green-500',
    paperRestriction: 'Paper 2/4',
    subtopics: [
      // B4.1 Ecosystems
      'Ecosystems',
      'Communities',
      'Populations',
      'Habitats',
      'Interdependence',
      'Abiotic factors',
      'Biotic factors',
      'Competition',
      'Adaptations',
      'PAG: Sampling techniques',
      // B4.1 Food chains and webs
      'Producers',
      'Consumers',
      'Primary consumers',
      'Secondary consumers',
      'Tertiary consumers',
      'Decomposers',
      'Food chains',
      'Food webs',
      'Trophic levels',
      // B4.1 Energy transfer
      'Energy flow',
      'Pyramids of biomass',
      'Energy transfer efficiency',
      'Energy losses',
      // B4.2 Carbon cycle
      'Carbon cycle',
      'Photosynthesis in carbon cycle',
      'Respiration in carbon cycle',
      'Decomposition',
      'Combustion',
      // B4.2 Water cycle
      'Water cycle',
      'Evaporation',
      'Transpiration',
      'Condensation',
      'Precipitation',
      // B4.2 Nitrogen cycle
      'Nitrogen cycle',
      'Nitrogen-fixing bacteria',
      'Nitrifying bacteria',
      'Denitrifying bacteria',
      'Decomposers',
      // B4.3 Biodiversity
      'Biodiversity',
      'Importance of biodiversity',
      'Human impact',
      'Pollution',
      'Deforestation',
      'Global warming',
      'Greenhouse gases',
      'Conservation',
      'Gene banks',
      'Seed banks',
      'Captive breeding',
    ],
  },
  {
    id: 'ocr-gcse-biology-genes-inheritance',
    examBoard: 'ocr',
    name: 'Genes, Inheritance and Selection',
    description: 'DNA, genetics, evolution, and classification',
    icon: '🧬',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2/4',
    subtopics: [
      // B5.1 Inheritance
      'DNA structure',
      'Double helix',
      'Nucleotides',
      'Base pairs',
      'Genes',
      'Chromosomes',
      'Genome',
      'Human genome project',
      // B5.1 Genetic inheritance
      'Alleles',
      'Dominant alleles',
      'Recessive alleles',
      'Homozygous',
      'Heterozygous',
      'Genotype',
      'Phenotype',
      'Genetic crosses',
      'Punnett squares',
      'Monohybrid inheritance',
      'Family pedigrees',
      // B5.1 Genetic disorders
      'Inherited disorders',
      'Polydactyly',
      'Cystic fibrosis',
      'Sickle cell disease',
      // B5.1 Sex inheritance
      'Sex chromosomes',
      'XX and XY',
      'Sex-linked disorders',
      // B5.2 Natural selection
      'Variation',
      'Genetic variation',
      'Environmental variation',
      'Mutations',
      'Natural selection',
      'Darwin\'s theory',
      'Survival of the fittest',
      'Evolution',
      'Evidence for evolution',
      'Fossils',
      'Antibiotic resistance',
      // B5.2 Selective breeding
      'Selective breeding',
      'Uses of selective breeding',
      'Problems with selective breeding',
      'Inbreeding',
      // B5.2 Genetic engineering
      'Genetic modification',
      'Genetic engineering process',
      'Restriction enzymes',
      'Vectors',
      'GM crops',
      'GM bacteria',
      'Benefits of GM',
      'Risks of GM',
      // B5.3 Classification
      'Classification',
      'Linnaean system',
      'Kingdoms',
      'Taxonomic groups',
      'Binomial naming',
      'Three-domain system',
      'Archaea',
      'Bacteria',
      'Eukaryota',
      'Evolutionary trees',
    ],
  },
  {
    id: 'ocr-gcse-biology-global-challenges',
    examBoard: 'ocr',
    name: 'Global Challenges',
    description: 'Health, disease, food production, and sustainability',
    icon: '🌐',
    color: 'bg-red-500',
    paperRestriction: 'Paper 2/4',
    subtopics: [
      // B6.1 Monitoring health
      'Health definition',
      'Disease',
      'Lifestyle factors',
      'Risk factors',
      'Cardiovascular disease',
      'BMI',
      'Blood pressure',
      'Heart rate',
      // B6.1 Non-communicable diseases
      'Non-communicable diseases',
      'Cancer',
      'Tumours',
      'Carcinogens',
      'Heart disease',
      'Obesity',
      'Liver disease',
      // B6.2 Communicable diseases
      'Pathogens',
      'Bacteria',
      'Viruses',
      'Fungi',
      'Protists',
      'How diseases spread',
      // B6.2 Viral diseases
      'HIV/AIDS',
      'Influenza',
      'TMV (plants)',
      // B6.2 Bacterial diseases
      'Tuberculosis',
      'Salmonella',
      'Chlamydia',
      // B6.2 Other pathogens
      'Malaria (protist)',
      'Athlete\'s foot (fungus)',
      'Chalara ash dieback (fungus)',
      // B6.2 Human defences
      'Physical barriers',
      'Skin',
      'Mucus',
      'Cilia',
      'Stomach acid',
      'Immune system',
      'White blood cells',
      'Phagocytes',
      'Lymphocytes',
      'Antibodies',
      'Memory cells',
      // B6.2 Vaccination
      'Vaccines',
      'How vaccines work',
      'Herd immunity',
      // B6.2 Antibiotics
      'Antibiotics',
      'Antibiotic resistance',
      'Antiseptics',
      'PAG: Antibiotics investigation',
      // B6.2 Drug development
      'Drug testing',
      'Clinical trials',
      'Placebo',
      'Double-blind trials',
      // B6.3 Plant diseases
      'Plant defences',
      'Physical defences',
      'Chemical defences',
      // B6.3 Food production
      'Food security',
      'Farming methods',
      'Selective breeding in agriculture',
      'GM crops in food production',
      'Fertilisers',
      'Pesticides',
      'Biological control',
      'Hydroponics',
      'Sustainable food production',
    ],
  },

  // ============================================================================
  // TOPIC B7 - PRACTICAL SKILLS (Both Papers)
  // ============================================================================
  {
    id: 'ocr-gcse-biology-practical-skills',
    examBoard: 'ocr',
    name: 'Practical Skills',
    description: 'Scientific methodology, data analysis, and practical techniques',
    icon: '🧪',
    color: 'bg-amber-500',
    paperRestriction: 'Both',
    subtopics: [
      // B7 Practical skills
      'Planning investigations',
      'Variables',
      'Independent variable',
      'Dependent variable',
      'Control variables',
      'Hypotheses',
      'Predictions',
      'Fair tests',
      'Repeats',
      'Accuracy',
      'Precision',
      'Resolution',
      'Reproducibility',
      // Data handling
      'Recording data',
      'Tables',
      'Graphs',
      'Bar charts',
      'Line graphs',
      'Scatter graphs',
      'Calculating means',
      'Identifying anomalies',
      // Analysis and evaluation
      'Drawing conclusions',
      'Evaluating methods',
      'Identifying limitations',
      'Suggesting improvements',
      // Mathematical skills
      'Calculating percentages',
      'Magnification calculations',
      'Surface area to volume ratio',
      'Rate calculations',
      'Standard form',
      'Significant figures',
    ],
  },
];

export function getOCRBiologyTopicById(id: string): Topic | undefined {
  return ocrBiologyTopics.find((topic) => topic.id === id);
}

export function getOCRBiologyTopicsByPaper(paper: '1/3' | '2/4' | 'Both'): Topic[] {
  if (paper === 'Both') {
    return ocrBiologyTopics.filter((topic) => topic.paperRestriction === 'Both');
  }
  return ocrBiologyTopics.filter((topic) => topic.paperRestriction === `Paper ${paper}`);
}

export function countOCRBiologySubtopics(): number {
  return ocrBiologyTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
