// OCR A-Level Psychology Topics (H567)
// Based on official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/psychology-h167-h567-from-2015/

import { Topic } from '@/types';

export const ocrALevelPsychologyTopics: Topic[] = [
  // ============================================================================
  // COMPONENT 1: RESEARCH METHODS (30%)
  // ============================================================================
  {
    id: 'ocr-alevel-psych-research-methods',
    name: 'Research Methods',
    description: 'Research methodology, experimental design, data analysis, and scientific processes',
    icon: '📊',
    color: 'bg-indigo-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 1',
    subtopics: [
      // Research methods and techniques
      'Experiment as research method',
      'Laboratory experiments',
      'Field experiments',
      'Natural experiments',
      'Quasi-experiments',
      'Strengths of experiments',
      'Weaknesses of experiments',
      'Observation as research method',
      'Naturalistic observation',
      'Controlled observation',
      'Participant observation',
      'Non-participant observation',
      'Covert observation',
      'Overt observation',
      'Strengths of observations',
      'Weaknesses of observations',
      'Self-report as research method',
      'Questionnaires',
      'Structured interviews',
      'Unstructured interviews',
      'Semi-structured interviews',
      'Strengths of self-reports',
      'Weaknesses of self-reports',
      'Correlation as research method',
      'Positive correlation',
      'Negative correlation',
      'Zero correlation',
      'Correlation vs causation',
      'Strengths of correlations',
      'Weaknesses of correlations',
      // Planning and conducting research
      'Aims in research',
      'Hypotheses',
      'Directional hypotheses',
      'Non-directional hypotheses',
      'Null hypothesis',
      'Populations and samples',
      'Target population',
      'Generalisability',
      'Sampling techniques',
      'Random sampling',
      'Self-selected sampling',
      'Opportunity sampling',
      'Stratified sampling',
      'Snowball sampling',
      'Experimental designs',
      'Independent measures design',
      'Repeated measures design',
      'Matched pairs design',
      'Strengths and weaknesses of each design',
      'Variables',
      'Independent variable',
      'Dependent variable',
      'Extraneous variables',
      'Confounding variables',
      'Participant variables',
      'Situational variables',
      'Operationalisation of variables',
      'Designing observations',
      'Behavioural categories',
      'Time sampling',
      'Event sampling',
      'Inter-observer reliability',
      'Designing self-reports',
      'Open questions',
      'Closed questions',
      'Rating scales',
      'Likert scales',
      'Leading questions',
      // Data recording, analysis and presentation
      'Types of data',
      'Quantitative data',
      'Qualitative data',
      'Primary data',
      'Secondary data',
      'Descriptive statistics',
      'Measures of central tendency',
      'Mean calculation and use',
      'Median calculation and use',
      'Mode calculation and use',
      'Measures of dispersion',
      'Range calculation',
      'Standard deviation calculation',
      'Interpretation of standard deviation',
      'Data presentation',
      'Tables',
      'Bar charts',
      'Histograms',
      'Frequency polygons',
      'Scattergrams',
      'Normal distribution',
      'Characteristics of normal distribution',
      'Skewed distributions',
      'Positive skew',
      'Negative skew',
      // Inferential statistics
      'Inferential testing',
      'Probability',
      'Significance levels',
      'Type I errors',
      'Type II errors',
      'Choosing statistical tests',
      'Chi-squared test',
      'When to use chi-squared',
      'Calculation of chi-squared',
      'Mann-Whitney U test',
      'When to use Mann-Whitney',
      'Wilcoxon signed-ranks test',
      'When to use Wilcoxon',
      "Spearman's rho",
      'When to use Spearman',
      'Critical values',
      'One-tailed vs two-tailed tests',
      // Issues in research
      'Reliability',
      'Test-retest reliability',
      'Inter-rater reliability',
      'Split-half reliability',
      'Ways to improve reliability',
      'Validity',
      'Internal validity',
      'External validity',
      'Ecological validity',
      'Population validity',
      'Temporal validity',
      'Face validity',
      'Concurrent validity',
      'Predictive validity',
      'Construct validity',
      'Ways to improve validity',
      'Ethical issues',
      'BPS ethical guidelines',
      'Informed consent',
      'Deception',
      'Right to withdraw',
      'Protection from harm',
      'Confidentiality',
      'Privacy',
      'Debriefing',
      'Dealing with ethical issues',
      'Socially sensitive research',
      'Issues in socially sensitive research',
      'Implications of research',
      // Scientific processes
      'Features of science',
      'Objectivity',
      'Empiricism',
      'Replicability',
      'Falsifiability',
      'Theory construction',
      'Hypothesis testing',
      'Paradigms and paradigm shifts',
      'Peer review process',
    ],
  },

  // ============================================================================
  // COMPONENT 2: PSYCHOLOGICAL THEMES THROUGH CORE STUDIES (35%)
  // ============================================================================
  {
    id: 'ocr-alevel-psych-social-area',
    name: 'Social Psychology Area',
    description: 'Core studies in social psychology including obedience, conformity, and bystander behaviour',
    icon: '👥',
    color: 'bg-blue-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 2',
    subtopics: [
      // Core study 1: Milgram (1963)
      "Milgram's (1963) obedience study",
      'Background and aims of Milgram',
      'Procedure: learner, teacher, experimenter',
      'The shock generator',
      'Verbal prods used',
      'Findings: 65% obedience rate',
      'Signs of stress in participants',
      'Conclusions about obedience',
      'Ethical issues in Milgram study',
      'Methodological issues',
      'Ecological validity of Milgram',
      'Applications of Milgram',
      // Core study 2: Bocchiaro et al. (2012)
      'Bocchiaro et al. (2012) disobedience study',
      'Background: extending Milgram',
      'Aims of the study',
      'Procedure: unethical experiment scenario',
      'Whistle-blowing condition',
      'Findings: rates of obedience, disobedience, whistle-blowing',
      'Predicted vs actual behaviour',
      'Individual differences: personality measures',
      'Conclusions about disobedience',
      'Methodological evaluation',
      'Ethical considerations',
      // Key theme: Responses to people in authority
      'Responses to authority',
      'Factors affecting obedience',
      'Factors affecting disobedience',
      'Agency theory',
      'Legitimacy of authority',
      'Proximity',
      'Social support for disobedience',
      // Additional social studies
      'Piliavin et al. (1969) subway study',
      'Background and aims',
      'Procedure: victim conditions',
      'Findings on helping behaviour',
      'Diffusion of responsibility',
      'Cost-reward model',
      'Evaluation of Piliavin',
      // Conformity and social influence
      'Types of conformity',
      'Normative social influence',
      'Informational social influence',
      'Internalisation',
      'Compliance',
      'Identification',
      'Minority influence',
      'Consistency',
      'Flexibility',
      // Areas, perspectives and debates
      'Individual vs situational explanations',
      'Usefulness of research',
      'Ethical issues in social psychology',
    ],
  },
  {
    id: 'ocr-alevel-psych-cognitive-area',
    name: 'Cognitive Psychology Area',
    description: 'Core studies in cognitive psychology including memory, attention, and cognitive processes',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 2',
    subtopics: [
      // Core study 1: Loftus and Palmer (1974)
      'Loftus and Palmer (1974) eyewitness testimony',
      'Background on reconstructive memory',
      'Aims: effect of leading questions',
      'Experiment 1 procedure',
      'Use of verbs: smashed, collided, bumped, hit, contacted',
      'Experiment 1 findings',
      'Experiment 2 procedure',
      'Broken glass question',
      'Experiment 2 findings',
      'Conclusions about memory distortion',
      'Response-bias vs memory alteration',
      'Applications to legal system',
      'Methodological evaluation',
      // Core study 2: Grant et al. (1998)
      'Grant et al. (1998) context-dependent memory',
      'Background: encoding specificity',
      'Aims of the study',
      'Independent groups design',
      'Conditions: silent study/test, noisy study/test',
      'Findings on context-dependent memory',
      'Short-answer vs multiple choice tests',
      'Conclusions and applications',
      'Evaluation of Grant et al.',
      // Key theme: Memory
      'Reconstructive memory theory',
      'Schema theory',
      'Encoding, storage, retrieval',
      'Context effects on memory',
      'State-dependent memory',
      'Mood-congruent memory',
      'Forgetting theories',
      'Interference theory',
      'Retrieval failure',
      // Additional cognitive studies
      'Moray (1959) selective attention',
      'Dichotic listening task',
      'Cocktail party effect',
      'Filter model of attention',
      'Simons and Chabris (1999)',
      'Inattentional blindness',
      'Gorilla study',
      // Cognitive processes
      'Attention theories',
      'Memory models',
      'Multi-store model',
      'Working memory model',
      // Areas, perspectives and debates
      'Laboratory vs field research',
      'Ecological validity in cognitive research',
      'Applications of cognitive psychology',
      'Reductionism in cognitive psychology',
    ],
  },
  {
    id: 'ocr-alevel-psych-developmental-area',
    name: 'Developmental Psychology Area',
    description: 'Core studies in developmental psychology including cognitive and social development',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 2',
    subtopics: [
      // Core study 1: Bandura et al. (1961)
      'Bandura et al. (1961) Bobo doll study',
      'Background: social learning theory',
      'Aims of the study',
      'Sample: Stanford nursery children',
      'Procedure: aggressive model conditions',
      'Non-aggressive model condition',
      'Control condition',
      'Male vs female models',
      'The mild aggression arousal',
      'Observational measures',
      'Findings: imitative aggression',
      'Gender differences in aggression',
      'Same-sex vs opposite-sex model effects',
      'Non-imitative aggression findings',
      'Conclusions about observational learning',
      'Methodological evaluation',
      'Ethical issues with children',
      // Core study 2: Chaney et al. (2004)
      'Chaney et al. (2004) Funhaler study',
      'Background: childhood asthma',
      'Aims: improving adherence',
      'Sample: Australian children',
      'The Funhaler device',
      'Procedure: breath-mediated spinner',
      'Self-report questionnaires',
      'Findings on adherence',
      'Parent attitudes',
      'Conclusions on health behaviour',
      'Applications and implications',
      'Evaluation of Chaney et al.',
      // Key theme: External influences on behaviour
      'Observational learning',
      'Vicarious reinforcement',
      'Mediational processes',
      'Role models',
      'Media influences on development',
      'Parental influence',
      'Environmental influences',
      // Additional developmental studies
      "Piaget's conservation tasks",
      'Stages of cognitive development',
      "Vygotsky's ZPD",
      'Scaffolding',
      // Attachment
      "Bowlby's attachment theory",
      'Strange Situation (Ainsworth)',
      'Attachment types',
      'Effects of early experience',
      // Areas, perspectives and debates
      'Nature-nurture in development',
      'Longitudinal vs cross-sectional research',
      'Ethics of research with children',
      'Applications to education',
      'Applications to parenting',
    ],
  },
  {
    id: 'ocr-alevel-psych-biological-area',
    name: 'Biological Psychology Area',
    description: 'Core studies in biological psychology including brain structure, genetics, and physiology',
    icon: '🔬',
    color: 'bg-green-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 2',
    subtopics: [
      // Core study 1: Sperry (1968)
      'Sperry (1968) split-brain research',
      'Background: corpus callosum',
      'Aims: hemispheric specialisation',
      'Sample: split-brain patients',
      'Commissurotomy procedure',
      'Testing apparatus',
      'Visual field testing procedure',
      'Left visual field / right hemisphere',
      'Right visual field / left hemisphere',
      'Findings: language lateralisation',
      'Left hemisphere language dominance',
      'Right hemisphere spatial abilities',
      'Conclusions on lateralisation',
      'Applications of research',
      'Methodological evaluation',
      'Generalisability issues',
      // Core study 2: Casey et al. (2011)
      'Casey et al. (2011) delayed gratification',
      'Background: Mischel marshmallow test',
      'Aims: brain mechanisms of self-control',
      'Longitudinal design',
      'Sample: original participants tracked',
      'Go/No-Go task',
      'fMRI scanning procedure',
      'Findings: high vs low delayers',
      'Prefrontal cortex activity',
      'Ventral striatum findings',
      'Conclusions on impulse control',
      'Biological basis of self-control',
      'Evaluation of Casey et al.',
      // Key theme: Regions of the brain
      'Brain structure and function',
      'Localisation of function',
      'Prefrontal cortex',
      'Corpus callosum',
      'Hemispheric lateralisation',
      'Language centres',
      "Broca's area",
      "Wernicke's area",
      'Brain plasticity',
      // Additional biological studies
      'Brain scanning techniques',
      'fMRI scanning',
      'PET scanning',
      'EEG',
      'CAT/CT scans',
      // Nervous system
      'Structure of nervous system',
      'Neurons and synaptic transmission',
      'Neurotransmitters',
      // Genetics
      'Genetic influences on behaviour',
      'Twin studies',
      'Adoption studies',
      // Areas, perspectives and debates
      'Biological reductionism',
      'Nature-nurture debate',
      'Free will vs determinism',
      'Ethics of brain research',
    ],
  },
  {
    id: 'ocr-alevel-psych-individual-differences',
    name: 'Individual Differences Area',
    description: 'Core studies in individual differences including psychopathology and personality',
    icon: '🎭',
    color: 'bg-yellow-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 2',
    subtopics: [
      // Core study 1: Freud (1909)
      'Freud (1909) Little Hans case study',
      'Background: psychoanalytic theory',
      'Aims of the case study',
      "Hans's phobia development",
      'The giraffe dream',
      'The plumber fantasy',
      "Freud's interpretation",
      'Oedipus complex application',
      'Castration anxiety',
      'Resolution of phobia',
      'Conclusions on psychosexual development',
      'Methodological evaluation',
      'Scientific status of psychoanalysis',
      'Alternative explanations',
      // Core study 2: Baron-Cohen et al. (1997)
      'Baron-Cohen et al. (1997) autism eyes study',
      'Background: theory of mind',
      'Mindblindness hypothesis',
      'Aims of the study',
      'Sample: adults with autism/Asperger',
      'Control groups: normal and Tourette',
      'Eyes Task procedure',
      'Basic and complex emotions',
      'Gender recognition control task',
      'Findings on emotion recognition',
      'Conclusions on theory of mind',
      'Applications to autism',
      'Evaluation of Baron-Cohen et al.',
      // Key theme: Understanding disorders
      'Defining abnormality',
      'Statistical infrequency',
      'Deviation from social norms',
      'Failure to function adequately',
      'Deviation from ideal mental health',
      'Classification systems',
      'DSM and ICD',
      // Autism spectrum
      'Characteristics of autism',
      'Social communication difficulties',
      'Restricted interests',
      'Theory of mind deficit',
      'Biological explanations',
      'Psychological explanations',
      // Psychoanalytic theory
      'Structure of personality',
      'Id, ego, superego',
      'Defence mechanisms',
      'Psychosexual stages',
      'Role of unconscious',
      // Areas, perspectives and debates
      'Individual vs situational factors',
      'Idiographic vs nomothetic approaches',
      'Ethics of labelling',
      'Cultural issues in diagnosis',
      'Usefulness of case studies',
    ],
  },

  // ============================================================================
  // COMPONENT 3: APPLIED PSYCHOLOGY (35%)
  // ============================================================================
  {
    id: 'ocr-alevel-psych-mental-health',
    name: 'Mental Health',
    description: 'Historical context of mental health, specific disorders, and treatments',
    icon: '🩺',
    color: 'bg-red-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 3',
    subtopics: [
      // Historical context
      'Historical views of mental illness',
      'Supernatural explanations',
      'Early biological approaches',
      'Moral treatment',
      'Rise of asylums',
      'Deinstitutionalisation',
      'Community care',
      // Definitions of abnormality
      'Statistical definition',
      'Social norms definition',
      'Failure to function adequately',
      'Deviation from ideal mental health',
      'Cultural considerations',
      'Evaluation of definitions',
      // Medical model
      'Medical model of mental illness',
      'Assumptions of medical model',
      'Biological explanations',
      'Genetics',
      'Neurochemistry',
      'Brain structure',
      'Diagnosis and classification',
      'DSM-5',
      'ICD-11',
      'Reliability of diagnosis',
      'Validity of diagnosis',
      'Drug treatments',
      'Antidepressants',
      'Antipsychotics',
      'Anxiolytics',
      'Mood stabilisers',
      'Evaluation of medical model',
      // Alternatives to medical model
      'Behavioural approach',
      'Classical conditioning explanations',
      'Operant conditioning explanations',
      'Behavioural treatments',
      'Systematic desensitisation',
      'Flooding',
      'Token economies',
      'Cognitive approach',
      'Faulty thinking patterns',
      'Cognitive distortions',
      'Cognitive behavioural therapy',
      'Humanistic approach',
      'Person-centred therapy',
      "Rogers's core conditions",
      'Empathy, congruence, unconditional positive regard',
      'Psychodynamic approach',
      'Role of unconscious',
      'Psychoanalysis',
      'Dream analysis',
      'Free association',
      // Specific disorders
      'Anxiety disorders',
      'Phobias',
      'Types of phobias',
      'Biological explanations of phobias',
      'Behavioural explanations of phobias',
      'Treatments for phobias',
      'Obsessive-compulsive disorder',
      'Characteristics of OCD',
      'Biological explanations of OCD',
      'Psychological explanations',
      'Treatments for OCD',
      'Depression',
      'Characteristics of depression',
      'Biological explanations',
      'Cognitive explanations',
      'Negative cognitive triad',
      'Treatments for depression',
      'Schizophrenia',
      'Positive and negative symptoms',
      'Biological explanations',
      'Dopamine hypothesis',
      'Psychological explanations',
      'Treatments for schizophrenia',
      // Issues and debates
      'Nature-nurture in mental health',
      'Reductionism in mental health',
      'Ethics of diagnosis and treatment',
      'Socially sensitive research',
      'Individual differences',
    ],
  },
  {
    id: 'ocr-alevel-psych-criminal',
    name: 'Criminal Psychology',
    description: 'Explanations of criminal behaviour, collection of evidence, and psychology of testimony',
    icon: '🔍',
    color: 'bg-gray-600',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 3 Option',
    subtopics: [
      // What makes a criminal?
      'Definition of crime',
      'Measuring crime',
      'Official statistics',
      'Self-report studies',
      'Victim surveys',
      // Biological explanations
      'Biological explanations of crime',
      'Genetic factors',
      "Lombroso's atavistic form",
      'Twin and adoption studies',
      'XYY syndrome',
      'Brain dysfunction',
      'Prefrontal cortex damage',
      'Amygdala dysfunction',
      "Raine's research on brain abnormalities",
      'Biochemistry and crime',
      'Testosterone',
      'Serotonin',
      'Evaluation of biological explanations',
      // Social explanations
      'Social explanations of crime',
      "Sutherland's differential association",
      'Social learning theory',
      'Modelling and imitation',
      'Labelling theory',
      'Self-fulfilling prophecy',
      'Poverty and crime',
      'Social deprivation',
      'Evaluation of social explanations',
      // Psychological explanations
      'Psychological explanations',
      'Cognitive explanations',
      'Moral reasoning development',
      'Cognitive distortions',
      'Hostile attribution bias',
      "Eysenck's criminal personality",
      'Extraversion, neuroticism, psychoticism',
      'Conditioning and crime',
      'Psychodynamic explanations',
      'Maternal deprivation',
      'Evaluation of psychological explanations',
      // Collection of evidence
      'Collection of evidence',
      'Interviewing suspects',
      'PEACE model',
      'Reid technique',
      'False confessions',
      'DNA evidence',
      'Forensic psychology',
      // Psychology of testimony
      'Psychology of testimony',
      'Eyewitness testimony',
      'Factors affecting accuracy',
      'Weapon focus',
      'Anxiety effects',
      'Leading questions',
      'Post-event information',
      'Cognitive interview',
      'Child witnesses',
      'Detecting lies',
      'Verbal and non-verbal cues',
      'Polygraph testing',
      // Trial processes
      'Jury decision making',
      'Characteristics of defendant',
      'Expert witnesses',
      'Pre-trial publicity',
      // Punishing crime
      'Aims of punishment',
      'Deterrence',
      'Incapacitation',
      'Retribution',
      'Rehabilitation',
      'Effectiveness of punishment',
      'Recidivism',
      // Treatment programmes
      'Treatment of offenders',
      'Cognitive skills programmes',
      'Anger management',
      'Token economies',
      'Restorative justice',
      'Evaluation of treatments',
    ],
  },
  {
    id: 'ocr-alevel-psych-sport-exercise',
    name: 'Sports and Exercise Psychology',
    description: 'Psychological factors in sport performance, motivation, and exercise',
    icon: '⚽',
    color: 'bg-emerald-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 3 Option',
    subtopics: [
      // Individual factors
      'Personality and sport',
      "Eysenck's personality theory",
      'Narrow band approaches',
      'Interactionist approach',
      'Type A and Type B personality',
      'Personality assessment',
      'Motivation in sport',
      'Intrinsic motivation',
      'Extrinsic motivation',
      'Self-determination theory',
      'Achievement motivation',
      'Need for achievement',
      'Fear of failure',
      'Attribution theory',
      'Locus of causality',
      'Stability',
      'Controllability',
      'Self-efficacy',
      "Bandura's theory",
      'Sources of self-efficacy',
      // Anxiety and arousal
      'Arousal in sport',
      'Drive theory',
      'Inverted-U hypothesis',
      'Catastrophe theory',
      'Individual zones of optimal functioning',
      'Anxiety in sport',
      'State and trait anxiety',
      'Cognitive anxiety',
      'Somatic anxiety',
      'Anxiety management techniques',
      // Aggression in sport
      'Aggression in sport',
      'Hostile aggression',
      'Instrumental aggression',
      'Assertion',
      'Biological explanations',
      'Instinct theory',
      'Frustration-aggression hypothesis',
      'Social learning theory',
      'Management of aggression',
      // Social factors
      'Group processes in sport',
      'Team cohesion',
      'Social loafing',
      "Ringelmann's research",
      'Audience effects',
      'Social facilitation',
      'Evaluation apprehension',
      'Home advantage',
      'Leadership in sport',
      'Leadership styles',
      'Effective leadership',
      // Exercise and health
      'Psychological benefits of exercise',
      'Stress reduction',
      'Anxiety reduction',
      'Effects on depression',
      'Self-esteem',
      'Adherence to exercise',
      'Barriers to exercise',
      'Transtheoretical model',
      'Exercise addiction',
      // Performance enhancement
      'Mental preparation',
      'Goal setting',
      'SMART goals',
      'Imagery and visualisation',
      'Mental rehearsal',
      'Self-talk',
      'Relaxation techniques',
      'Progressive muscular relaxation',
      'Concentration and attention',
      'Pre-performance routines',
      // Issues and debates
      'Nature-nurture in sport',
      'Use of psychological research',
      'Ethics of performance enhancement',
      'Individual differences',
    ],
  },
  {
    id: 'ocr-alevel-psych-environmental',
    name: 'Environmental Psychology',
    description: 'Effects of environment on behaviour, personal space, and environmental cognition',
    icon: '🌍',
    color: 'bg-teal-500',
    examBoard: 'ocr',
    qualification: 'a-level',
    subject: 'psychology',
    paperRestriction: 'Component 3 Option',
    subtopics: [
      // Stressors in the environment
      'Environmental stressors',
      'Noise',
      'Effects of noise on behaviour',
      'Noise and task performance',
      'Noise and social behaviour',
      'Density and crowding',
      'Crowding vs density distinction',
      'Effects of crowding',
      'Urban overload',
      'Temperature effects',
      'Heat and aggression',
      'Pollution effects',
      'Air quality and behaviour',
      // Personal space
      'Personal space',
      "Hall's proxemic zones",
      'Intimate distance',
      'Personal distance',
      'Social distance',
      'Public distance',
      'Cultural differences in personal space',
      'Gender differences',
      'Invasion of personal space',
      'Reactions to invasion',
      // Territory
      'Territory and territoriality',
      'Types of territory',
      'Primary territory',
      'Secondary territory',
      'Public territory',
      'Territorial markers',
      'Personalisation',
      'Defensible space',
      "Newman's theory",
      // Architecture and behaviour
      'Architecture and behaviour',
      'Residential environments',
      'Workplace design',
      'Open-plan offices',
      'Hospital design',
      'Prison design',
      'School design',
      // Environmental cognition
      'Cognitive maps',
      "Tolman's research",
      'Spatial cognition',
      "Lynch's city image elements",
      'Paths, edges, districts, nodes, landmarks',
      'Wayfinding',
      'You-are-here maps',
      // Changing behaviour
      'Pro-environmental behaviour',
      'Recycling behaviour',
      'Energy conservation',
      'Persuasion techniques',
      'Social norms approach',
      'Prompts and feedback',
      'Environmental education',
      'Theory of planned behaviour',
      // Issues and debates
      'Individual vs situational factors',
      'Practical applications',
      'Research methods in environmental psychology',
      'Ethics of environmental manipulation',
    ],
  },
];

export function getOCRALevelPsychologyTopicById(id: string): Topic | undefined {
  return ocrALevelPsychologyTopics.find((topic) => topic.id === id);
}
