// Edexcel A-Level Physics (9PH0) Topics
// Complete specification coverage
// Paper 1: Topics 1-3, 6-8 (Advanced Physics I)
// Paper 2: Topics 1, 4-5, 9-13 (Advanced Physics II)
// Paper 3: All topics + Practical skills (General and Practical Principles)

import { Topic } from '@/types';

export const edexcelALevelPhysicsTopics: Topic[] = [
  // ==========================================
  // PAPER 1 TOPICS (Advanced Physics I)
  // ==========================================

  // Topic 1: Working as a Physicist
  {
    id: 'working',
    name: 'Working as a Physicist',
    description: 'Scientific methodology, units, estimation and practical skills',
    icon: '🔬',
    color: 'bg-gray-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Papers 1, 2 & 3',
    subtopics: [
      // 1. Scientific methodology
      'SI base units and derived units',
      'SI prefixes from femto to tera',
      'Checking homogeneity of equations',
      'Dimensional analysis',
      'Estimating physical quantities',
      'Orders of magnitude',
      // 2. Experimental skills
      'Planning experiments',
      'Identifying variables',
      'Control of variables',
      'Accurate measurement techniques',
      'Recording data in tables',
      'Significant figures',
      // 3. Errors and uncertainties
      'Random and systematic errors',
      'Accuracy and precision',
      'Absolute and percentage uncertainty',
      'Combining uncertainties',
      'Uncertainties in graphs',
      'Error bars and best fit lines',
      // 4. Data analysis
      'Processing experimental data',
      'Calculating gradients',
      'Interpreting intercepts',
      'Linearising relationships',
      'Using log graphs',
    ],
  },

  // Topic 2: Mechanics
  {
    id: 'mechanics',
    name: 'Mechanics',
    description: 'Motion, forces, momentum, work, energy and power',
    icon: '⚙️',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 2a. Rectilinear motion
      'Distance and displacement',
      'Speed and velocity',
      'Acceleration as rate of change of velocity',
      'Displacement-time graphs',
      'Velocity-time graphs',
      'Gradient and area under motion graphs',
      'SUVAT equations of motion',
      'v = u + at',
      's = ut + ½at²',
      's = ½(u + v)t',
      'v² = u² + 2as',
      's = vt - ½at²',
      'Free fall motion',
      'Acceleration due to gravity g = 9.81 m/s²',
      'Core practical: Measuring g by free fall',
      // 2b. Projectile motion
      'Independence of horizontal and vertical motion',
      'Horizontal component: constant velocity',
      'Vertical component: constant acceleration',
      'Resolving initial velocity',
      'Time of flight calculations',
      'Maximum height calculations',
      'Range calculations',
      'Trajectory analysis',
      'Core practical: Projectile motion investigation',
      // 2c. Forces
      'Newton\'s first law of motion',
      'Newton\'s second law: F = ma',
      'Newton\'s third law: action-reaction pairs',
      'Free body force diagrams',
      'Weight and gravitational field strength',
      'Normal contact force',
      'Friction forces',
      'Tension in strings',
      'Resolving forces into components',
      'Forces in equilibrium',
      'Moments and torque',
      'Moment = force × perpendicular distance',
      'Principle of moments',
      'Centre of mass and centre of gravity',
      'Conditions for equilibrium',
      'Couples and torque',
      // 2d. Momentum
      'Momentum = mass × velocity',
      'Conservation of linear momentum',
      'Elastic and inelastic collisions',
      'Perfectly inelastic collisions',
      'Explosions and recoil',
      'Newton\'s second law as F = Δp/Δt',
      'Impulse = FΔt = Δp',
      'Force-time graphs',
      'Area under F-t graph as impulse',
      // 2e. Work, energy and power
      'Work done = force × displacement',
      'Work done at an angle: W = Fs cos θ',
      'Kinetic energy: Ek = ½mv²',
      'Gravitational potential energy: Ep = mgh',
      'Conservation of mechanical energy',
      'Energy transfers and dissipation',
      'Power = work done / time',
      'Power = force × velocity',
      'Efficiency calculations',
    ],
  },

  // Topic 3: Electric Circuits
  {
    id: 'circuits',
    name: 'Electric Circuits',
    description: 'Current, voltage, resistance, EMF and circuit analysis',
    icon: '⚡',
    color: 'bg-yellow-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3a. Charge and current
      'Electric charge and the coulomb',
      'Current as rate of flow of charge: I = ΔQ/Δt',
      'Conventional current vs electron flow',
      'Charge carriers in conductors',
      'Number density of charge carriers',
      'Drift velocity equation: I = nAvq',
      // 3b. Potential difference and resistance
      'Potential difference (voltage)',
      'Work done per unit charge',
      'Resistance: R = V/I',
      'Ohm\'s law and ohmic conductors',
      'Resistivity: ρ = RA/L',
      'Effect of temperature on resistance',
      'Effect of temperature on metals',
      'Effect of temperature on semiconductors',
      'Core practical: Resistivity of a wire',
      // 3c. I-V characteristics
      'I-V graphs for resistors',
      'I-V graphs for filament lamps',
      'I-V graphs for diodes',
      'I-V graphs for thermistors',
      'I-V graphs for LDRs',
      'Core practical: I-V characteristics',
      // 3d. Circuit rules
      'Series circuits',
      'Parallel circuits',
      'Kirchhoff\'s first law (current)',
      'Kirchhoff\'s second law (voltage)',
      'Total resistance in series',
      'Total resistance in parallel',
      'Combined series-parallel circuits',
      // 3e. Power and energy
      'Power in circuits: P = IV',
      'P = I²R and P = V²/R',
      'Energy transfer: E = VIt',
      'E = I²Rt and E = V²t/R',
      'Kilowatt-hour calculations',
      // 3f. EMF and internal resistance
      'Electromotive force (EMF)',
      'EMF vs terminal potential difference',
      'Internal resistance',
      'ε = I(R + r)',
      'ε = V + Ir (lost volts)',
      'Core practical: EMF and internal resistance',
      // 3g. Potential dividers
      'Potential divider principle',
      'Vout = Vin × R₂/(R₁ + R₂)',
      'Sensor circuits with thermistors',
      'Sensor circuits with LDRs',
      'Potentiometer applications',
    ],
  },

  // Topic 6: Further Mechanics
  {
    id: 'further-mechanics',
    name: 'Further Mechanics',
    description: 'Circular motion and momentum in two dimensions',
    icon: '🔄',
    color: 'bg-indigo-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 6a. Circular motion
      'Angular displacement in radians',
      'Converting between degrees and radians',
      'Angular velocity: ω = θ/t = 2πf',
      'Period and frequency: T = 1/f',
      'Linear speed: v = rω',
      'Centripetal acceleration: a = v²/r = ω²r',
      'Centripetal force: F = mv²/r = mω²r',
      'Objects in horizontal circles',
      'Objects in vertical circles',
      'Conical pendulum',
      'Banked tracks',
      'Core practical: Circular motion investigation',
      // 6b. Momentum in 2D
      'Vector nature of momentum',
      'Conservation in two dimensions',
      '2D collision analysis',
      'Resolving momentum into components',
      'Oblique collisions',
    ],
  },

  // Topic 7: Electric and Magnetic Fields
  {
    id: 'em-fields',
    name: 'Electric and Magnetic Fields',
    description: 'Electric fields, capacitance, magnetic fields and electromagnetic induction',
    icon: '🧲',
    color: 'bg-green-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 7a. Electric fields
      'Electric field concept',
      'Electric field lines',
      'Field patterns around charges',
      'Uniform field between parallel plates',
      'Electric field strength: E = F/Q',
      'E = V/d for uniform field',
      'Coulomb\'s law: F = kQ₁Q₂/r²',
      'Permittivity of free space ε₀',
      'k = 1/(4πε₀)',
      'E = kQ/r² for point charge',
      'Electric potential: V = kQ/r',
      'Potential difference and work done',
      'Equipotential surfaces',
      'Motion of charges in uniform fields',
      // 7b. Capacitance
      'Capacitor structure and function',
      'Capacitance: C = Q/V',
      'Parallel plate capacitor: C = ε₀A/d',
      'Effect of dielectrics',
      'Relative permittivity εᵣ',
      'C = ε₀εᵣA/d',
      'Energy stored: E = ½QV = ½CV²',
      'Capacitors in series',
      'Capacitors in parallel',
      'Charging capacitors through resistors',
      'Discharging capacitors',
      'Time constant: τ = RC',
      'Exponential charge/discharge equations',
      'Q = Q₀e^(-t/RC)',
      'I = I₀e^(-t/RC)',
      'V = V₀e^(-t/RC)',
      'Core practical: Capacitor discharge',
      // 7c. Magnetic fields
      'Magnetic flux density B',
      'Magnetic field patterns',
      'Field around straight wire',
      'Field around solenoid',
      'Force on current-carrying wire: F = BIL',
      'F = BIL sin θ',
      'Force on moving charge: F = BQv',
      'Fleming\'s left-hand rule',
      'Motion of charges in magnetic fields',
      'Circular paths of charged particles',
      'r = mv/(BQ)',
      'Velocity selector',
      'Mass spectrometer principle',
      // 7d. Electromagnetic induction
      'Magnetic flux: Φ = BA',
      'Flux linkage: NΦ = BAN',
      'Faraday\'s law: ε = -N(dΦ/dt)',
      'Lenz\'s law',
      'EMF from flux changes',
      'Generator and alternator principles',
      'Core practical: Investigating EMI',
      // 7e. Alternating currents
      'AC waveforms',
      'Peak and RMS values',
      'Irms = I₀/√2',
      'Vrms = V₀/√2',
      'Power in AC circuits',
      'Transformers',
      'Ns/Np = Vs/Vp = Ip/Is',
      'Transformer efficiency',
      'Power transmission',
    ],
  },

  // Topic 8: Nuclear and Particle Physics
  {
    id: 'nuclear-particle',
    name: 'Nuclear and Particle Physics',
    description: 'Particle physics, nuclear structure and fundamental interactions',
    icon: '⚛️',
    color: 'bg-purple-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 8a. Atomic structure
      'Atomic model evolution',
      'Rutherford scattering',
      'Nuclear model of the atom',
      'Protons, neutrons and electrons',
      'Nucleon number A and proton number Z',
      'Isotopes',
      'Specific charge',
      // 8b. Particle physics
      'Fundamental particles',
      'Quarks: up, down, strange, charm, bottom, top',
      'Quark charges',
      'Antiquarks',
      'Hadrons and leptons',
      'Baryons (3 quarks)',
      'Mesons (quark-antiquark)',
      'Quark composition of protons and neutrons',
      'Quark composition of pions and kaons',
      'Leptons: electron, muon, tau, neutrinos',
      'Lepton number conservation',
      'Baryon number conservation',
      'Strangeness conservation',
      // 8c. Fundamental interactions
      'Four fundamental forces',
      'Strong nuclear force',
      'Weak nuclear force',
      'Electromagnetic force',
      'Gravitational force',
      'Exchange particles',
      'Photons (electromagnetic)',
      'W and Z bosons (weak)',
      'Gluons (strong)',
      'Feynman diagrams',
      'Beta decay Feynman diagrams',
      // 8d. Particle accelerators
      'Linear accelerators (linacs)',
      'Cyclotrons',
      'Synchrotrons',
      'Particle collisions and discoveries',
      'CERN and the LHC',
      // 8e. Antimatter
      'Antiparticles',
      'Pair production',
      'Annihilation',
      'Threshold energy for pair production',
      'E = mc² applications',
    ],
  },

  // ==========================================
  // PAPER 2 TOPICS (Advanced Physics II)
  // ==========================================

  // Topic 4: Materials
  {
    id: 'materials',
    name: 'Materials',
    description: 'Properties of materials, stress, strain and the Young modulus',
    icon: '🔩',
    color: 'bg-slate-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 4a. Fluid flow
      'Density: ρ = m/V',
      'Upthrust and Archimedes\' principle',
      'Viscosity and viscous drag',
      'Stokes\' law: F = 6πηrv',
      'Terminal velocity in fluids',
      'Core practical: Terminal velocity in fluids',
      // 4b. Solid materials
      'Hooke\'s law: F = kx',
      'Spring constant k',
      'Force-extension graphs',
      'Elastic limit',
      'Elastic and plastic deformation',
      'Springs in series and parallel',
      // 4c. Stress and strain
      'Tensile stress: σ = F/A',
      'Tensile strain: ε = ΔL/L',
      'Young modulus: E = σ/ε',
      'Stress-strain graphs',
      'Ultimate tensile stress',
      'Breaking stress',
      'Core practical: Young modulus',
      // 4d. Energy in materials
      'Elastic strain energy',
      'E = ½FΔL = ½kx²',
      'Area under force-extension graph',
      'Loading and unloading curves',
      'Hysteresis',
      'Energy dissipation',
    ],
  },

  // Topic 5: Waves and Particle Nature of Light
  {
    id: 'waves',
    name: 'Waves and Particle Nature of Light',
    description: 'Wave properties, superposition, diffraction and quantum phenomena',
    icon: '🌊',
    color: 'bg-cyan-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 5a. Wave properties
      'Transverse and longitudinal waves',
      'Displacement, amplitude, wavelength',
      'Period, frequency and wave speed',
      'v = fλ',
      'Phase and phase difference',
      'Polarisation',
      'Polarisation as evidence of transverse waves',
      'Polaroid filters',
      'Malus\'s law',
      'Applications of polarisation',
      // 5b. Wave behaviour
      'Reflection',
      'Refraction',
      'Refractive index: n = c/v',
      'Snell\'s law: n₁ sin θ₁ = n₂ sin θ₂',
      'Total internal reflection',
      'Critical angle',
      'Optical fibres',
      'Core practical: Refractive index',
      // 5c. Superposition
      'Principle of superposition',
      'Constructive and destructive interference',
      'Path difference',
      'Coherent sources',
      'Two-source interference',
      'Young\'s double slit experiment',
      'Fringe spacing: w = λD/s',
      'Core practical: Young\'s double slit',
      // 5d. Stationary waves
      'Formation of stationary waves',
      'Nodes and antinodes',
      'Harmonics on strings',
      'First harmonic: f = (1/2L)√(T/μ)',
      'Stationary waves in pipes',
      'Open and closed pipes',
      'Core practical: Stationary waves',
      // 5e. Diffraction
      'Single slit diffraction',
      'Diffraction grating: d sin θ = nλ',
      'Orders of diffraction',
      'Grating spectra',
      'Core practical: Diffraction grating',
      // 5f. Particle nature of light
      'Photon model of light',
      'Photon energy: E = hf = hc/λ',
      'Planck constant',
      'Electronvolt (eV)',
      'Photoelectric effect',
      'Work function φ',
      'Photoelectric equation: hf = φ + Ek(max)',
      'Threshold frequency',
      'Stopping potential',
      'Wave-particle duality',
      'de Broglie wavelength: λ = h/p = h/mv',
      'Electron diffraction',
      // 5g. Energy levels
      'Discrete energy levels in atoms',
      'Ground state and excited states',
      'Photon emission and absorption',
      'Line spectra',
      'Energy level diagrams',
      'Ionisation energy',
      'Excitation energy',
      'Fluorescence',
    ],
  },

  // Topic 9: Thermodynamics
  {
    id: 'thermodynamics',
    name: 'Thermodynamics',
    description: 'Heat transfer, ideal gases and kinetic theory',
    icon: '🌡️',
    color: 'bg-red-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 9a. Heat transfer
      'Internal energy',
      'Temperature and thermal equilibrium',
      'Absolute zero',
      'Kelvin scale',
      'Specific heat capacity: E = mcΔθ',
      'Specific latent heat: E = mL',
      'Latent heat of fusion',
      'Latent heat of vaporisation',
      'Continuous flow methods',
      'Core practical: Specific heat capacity',
      // 9b. Ideal gases
      'Gas laws',
      'Boyle\'s law: pV = constant',
      'Charles\'s law: V/T = constant',
      'Pressure law: p/T = constant',
      'Ideal gas equation: pV = nRT',
      'pV = NkT',
      'Molar gas constant R',
      'Boltzmann constant k',
      'Avogadro constant NA',
      'Molar mass and molecular mass',
      'Core practical: Gas laws',
      // 9c. Kinetic theory
      'Assumptions of kinetic theory',
      'Brownian motion',
      'Derivation of pressure equation',
      'pV = ⅓Nm<c²>',
      'Root mean square speed',
      'Mean kinetic energy: ½m<c²> = 3/2 kT',
      'Internal energy of ideal gas',
      'Maxwell-Boltzmann distribution',
    ],
  },

  // Topic 10: Space
  {
    id: 'space',
    name: 'Space',
    description: 'Astrophysics, stellar evolution and cosmology',
    icon: '🔭',
    color: 'bg-purple-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 10a. Stellar quantities
      'Astronomical unit (AU)',
      'Light year',
      'Parsec',
      'Stellar parallax',
      'Luminosity',
      'Intensity and inverse square law',
      'Apparent magnitude',
      'Absolute magnitude',
      'Magnitude equation: m - M = 5 log(d/10)',
      // 10b. Stellar spectra
      'Black body radiation',
      'Wien\'s displacement law: λmax T = constant',
      'Stefan-Boltzmann law: L = 4πr²σT⁴',
      'Stellar absorption spectra',
      'Spectral classes: O B A F G K M',
      'Temperature and spectral class',
      // 10c. Hertzsprung-Russell diagram
      'HR diagram structure',
      'Main sequence',
      'Giants and supergiants',
      'White dwarfs',
      'Stellar radius from HR diagram',
      // 10d. Stellar evolution
      'Star formation from nebulae',
      'Main sequence lifetime',
      'Red giant phase',
      'Planetary nebulae',
      'White dwarf formation',
      'Supernova explosions',
      'Neutron stars',
      'Black holes',
      'Chandrasekhar limit',
      // 10e. Cosmology
      'Doppler effect for light',
      'Red shift: z = Δλ/λ',
      'z = v/c for v << c',
      'Hubble\'s law: v = H₀d',
      'Hubble constant',
      'Age of universe from H₀',
      'Big Bang theory',
      'Cosmic microwave background radiation',
      'Evidence for expanding universe',
    ],
  },

  // Topic 11: Nuclear Radiation
  {
    id: 'nuclear-rad',
    name: 'Nuclear Radiation',
    description: 'Radioactivity, decay, binding energy and nuclear reactions',
    icon: '☢️',
    color: 'bg-orange-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 11a. Radioactive decay
      'Random nature of decay',
      'Background radiation',
      'Alpha particles',
      'Beta-minus particles',
      'Beta-plus particles',
      'Gamma rays',
      'Properties of radiations',
      'Ionising ability',
      'Penetrating power',
      'Deflection in fields',
      'Nuclear equations',
      'Alpha decay equations',
      'Beta decay equations',
      // 11b. Half-life
      'Activity: A = λN',
      'Decay constant λ',
      'Half-life: t½ = ln2/λ',
      'Exponential decay: N = N₀e^(-λt)',
      'A = A₀e^(-λt)',
      'Decay graphs',
      'Determining half-life from graphs',
      'Carbon dating',
      'Core practical: Half-life simulation',
      // 11c. Nuclear binding energy
      'Mass defect',
      'Binding energy: E = mc²',
      'Atomic mass unit (u)',
      'Binding energy per nucleon',
      'Binding energy curve',
      'Stability and binding energy',
      // 11d. Nuclear reactions
      'Nuclear fission',
      'Fission products',
      'Chain reactions',
      'Critical mass',
      'Nuclear reactors',
      'Control rods and moderators',
      'Nuclear fusion',
      'Fusion in stars',
      'Fusion reactor challenges',
      // 11e. Nuclear safety
      'Radiation exposure',
      'Dose and dose equivalent',
      'Shielding',
      'Nuclear waste management',
    ],
  },

  // Topic 12: Gravitational Fields
  {
    id: 'gravity',
    name: 'Gravitational Fields',
    description: 'Gravitational fields, potential and orbital motion',
    icon: '🌍',
    color: 'bg-blue-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 12a. Gravitational field concept
      'Gravitational field as force field',
      'Field lines around point masses',
      'Radial fields',
      'Uniform fields near Earth\'s surface',
      // 12b. Newton\'s law of gravitation
      'F = GMm/r²',
      'Gravitational constant G',
      'Point masses and spherical bodies',
      // 12c. Gravitational field strength
      'g = F/m',
      'g = GM/r² for point mass',
      'Variation of g with distance',
      'g at Earth\'s surface',
      // 12d. Gravitational potential
      'V = -GM/r',
      'Potential as energy per unit mass',
      'Negative potential values',
      'Equipotential surfaces',
      'Potential gradient: g = -dV/dr',
      'Gravitational potential energy: Ep = -GMm/r',
      // 12e. Orbital motion
      'Orbital speed: v = √(GM/r)',
      'Orbital period',
      'Kepler\'s third law: T² ∝ r³',
      'Geostationary orbits',
      'Low Earth orbits',
      'Satellite energy',
      'Total energy of satellites',
      // 12f. Escape velocity
      'Escape velocity derivation',
      'v = √(2GM/r)',
    ],
  },

  // Topic 13: Oscillations
  {
    id: 'oscillations',
    name: 'Oscillations',
    description: 'Simple harmonic motion, damping and resonance',
    icon: '〰️',
    color: 'bg-teal-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 13a. Simple harmonic motion
      'Conditions for SHM',
      'Defining equation: a = -ω²x',
      'Angular frequency: ω = 2πf',
      'Displacement: x = A cos(ωt)',
      'Velocity: v = -Aω sin(ωt)',
      'v = ±ω√(A² - x²)',
      'Maximum velocity: vmax = ωA',
      'Acceleration: a = -Aω² cos(ωt)',
      'Maximum acceleration: amax = ω²A',
      'Phase relationships',
      'Graphs of x, v, a against time',
      // 13b. SHM systems
      'Mass-spring system: T = 2π√(m/k)',
      'Simple pendulum: T = 2π√(L/g)',
      'Core practical: Mass-spring oscillations',
      'Core practical: Simple pendulum',
      // 13c. Energy in SHM
      'Kinetic energy in SHM',
      'Potential energy in SHM',
      'Total energy: E = ½kA² = ½mω²A²',
      'Energy-time graphs',
      'Energy-displacement graphs',
      'Energy interchange',
      // 13d. Damping
      'Free oscillations',
      'Natural frequency',
      'Damped oscillations',
      'Light damping',
      'Heavy damping',
      'Critical damping',
      'Amplitude decay in damped systems',
      // 13e. Forced oscillations and resonance
      'Forced vibrations',
      'Driving frequency',
      'Resonance',
      'Resonance at f = f₀',
      'Amplitude-frequency graphs',
      'Effect of damping on resonance',
      'Sharpness of resonance',
      'Examples of resonance',
      'Useful and harmful resonance',
    ],
  },
];

// Helper functions
export function getEdexcelALevelPhysicsTopicById(id: string): Topic | undefined {
  return edexcelALevelPhysicsTopics.find(topic => topic.id === id);
}

export function getEdexcelALevelPhysicsTopicsByPaper(paper: 1 | 2 | 3): Topic[] {
  return edexcelALevelPhysicsTopics.filter(topic =>
    topic.paperRestriction?.includes(`Paper ${paper}`)
  );
}

export function countEdexcelALevelPhysicsSubtopics(): number {
  return edexcelALevelPhysicsTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
