// AQA A-Level Biology (7402) Topics
// Based on the official AQA specification
// Reference: https://www.aqa.org.uk/subjects/biology/a-level/biology-7402/specification

import { Topic } from '@/types';

export const aqaALevelBiologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1 TOPICS (1-4)
  // ============================================================================
  {
    id: 'aqa-alevel-biology-biological-molecules',
    examBoard: 'aqa',
    name: 'Biological Molecules',
    description: 'Carbohydrates, lipids, proteins, nucleic acids, enzymes, and water',
    icon: '🧪',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.1.1 Monomers and polymers
      'Monomers and polymers',
      'Condensation and hydrolysis reactions',
      // 3.1.2 Carbohydrates
      'Monosaccharides',
      'Glucose isomers',
      'Disaccharides',
      'Glycosidic bonds',
      'Polysaccharides',
      'Starch structure and function',
      'Glycogen structure and function',
      'Cellulose structure and function',
      // 3.1.3 Lipids
      'Triglycerides',
      'Ester bonds',
      'Saturated and unsaturated fatty acids',
      'Phospholipids',
      'Functions of lipids',
      // 3.1.4 Proteins
      'Amino acids',
      'Peptide bonds',
      'Primary structure',
      'Secondary structure',
      'Tertiary structure',
      'Quaternary structure',
      'Globular proteins',
      'Fibrous proteins',
      'Collagen structure',
      'Haemoglobin structure',
      // 3.1.5 Nucleic acids
      'DNA structure',
      'RNA structure',
      'Nucleotides',
      'Phosphodiester bonds',
      'Purines and pyrimidines',
      'Complementary base pairing',
      'DNA replication',
      'Semi-conservative replication',
      'ATP structure and function',
      // 3.1.6 Enzymes
      'Lock and key model',
      'Induced fit model',
      'Enzyme specificity',
      'Factors affecting enzyme activity',
      'Vmax and Km',
      'Competitive inhibitors',
      'Non-competitive inhibitors',
      'Required Practical 1: Effect of enzyme concentration',
      // 3.1.7 Water
      'Properties of water',
      'Hydrogen bonding',
      'Cohesion and surface tension',
      'Specific heat capacity',
      'Solvent properties',
      // 3.1.8 Inorganic ions
      'Role of inorganic ions',
      'Iron ions',
      'Hydrogen ions',
      'Phosphate ions',
    ],
  },
  {
    id: 'aqa-alevel-biology-cells',
    examBoard: 'aqa',
    name: 'Cells',
    description: 'Cell structure, transport mechanisms, and cell recognition',
    icon: '🔬',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.2.1 Cell structure
      'Eukaryotic cell structure',
      'Prokaryotic cell structure',
      'Ultrastructure of organelles',
      'Nucleus',
      'Mitochondria',
      'Chloroplasts',
      'Golgi apparatus',
      'Endoplasmic reticulum',
      'Ribosomes',
      'Lysosomes',
      'Centrioles',
      'Required Practical 2: Microscopy',
      // 3.2.2 All cells arise from other cells
      'Cell cycle',
      'Mitosis',
      'Interphase',
      'Prophase',
      'Metaphase',
      'Anaphase',
      'Telophase',
      'Binary fission',
      'Viruses',
      // 3.2.3 Transport across cell membranes
      'Fluid mosaic model',
      'Phospholipid bilayer',
      'Membrane proteins',
      'Cholesterol',
      'Glycoproteins',
      'Diffusion',
      'Facilitated diffusion',
      'Osmosis',
      'Water potential',
      'Active transport',
      'Co-transport',
      'Endocytosis',
      'Exocytosis',
      'Required Practical 3: Osmosis',
      // 3.2.4 Cell recognition and the immune system
      'Antigens',
      'Pathogens and disease',
      'Phagocytosis',
      'T lymphocytes',
      'B lymphocytes',
      'Plasma cells',
      'Antibody structure',
      'Primary immune response',
      'Secondary immune response',
      'Vaccination',
      'Active and passive immunity',
      'HIV and AIDS',
      'Monoclonal antibodies',
    ],
  },
  {
    id: 'aqa-alevel-biology-organisms-exchange',
    examBoard: 'aqa',
    name: 'Organisms Exchange Substances',
    description: 'Gas exchange, digestion, and mass transport in plants and animals',
    icon: '🫁',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.3.1 Surface area to volume ratio
      'Surface area to volume ratio',
      'Importance of exchange surfaces',
      'Features of exchange surfaces',
      // 3.3.2 Gas exchange
      'Gas exchange in insects',
      'Spiracles and tracheae',
      'Gas exchange in fish',
      'Counter-current flow',
      'Gas exchange in dicotyledonous plants',
      'Stomata and guard cells',
      'Xerophytes',
      'Mammalian gas exchange',
      'Alveoli structure',
      'Ventilation',
      'Required Practical 4: Dissection of gas exchange system',
      // 3.3.3 Digestion and absorption
      'Structure of digestive system',
      'Physical digestion',
      'Chemical digestion',
      'Carbohydrate digestion',
      'Protein digestion',
      'Lipid digestion',
      'Absorption in ileum',
      'Role of villi',
      'Required Practical 5: Dissection of alimentary canal',
      // 3.3.4 Mass transport
      // Mass transport in animals
      'Need for transport systems',
      'Single and double circulatory systems',
      'Structure of heart',
      'Cardiac cycle',
      'Cardiac output',
      'Blood vessels',
      'Arteries',
      'Arterioles',
      'Capillaries',
      'Veins',
      'Tissue fluid formation',
      'Lymph',
      'Haemoglobin',
      'Oxygen dissociation curve',
      'Bohr effect',
      'Carbon dioxide transport',
      // Mass transport in plants
      'Xylem structure',
      'Cohesion-tension theory',
      'Transpiration',
      'Factors affecting transpiration',
      'Required Practical 6: Dissection of plant transport tissues',
      'Phloem structure',
      'Translocation',
      'Mass flow hypothesis',
    ],
  },
  {
    id: 'aqa-alevel-biology-genetic-information',
    examBoard: 'aqa',
    name: 'Genetic Information, Variation and Relationships',
    description: 'DNA, genes, protein synthesis, genetic variation, and classification',
    icon: '🧬',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.4.1 DNA, genes and chromosomes
      'Genes and genomes',
      'Chromosomes',
      'Alleles',
      'Introns and exons',
      'Gene structure',
      // 3.4.2 DNA and protein synthesis
      'Genetic code',
      'Codons',
      'Degenerate code',
      'Transcription',
      'mRNA processing',
      'Translation',
      'tRNA structure',
      'Ribosome structure',
      // 3.4.3 Genetic diversity
      'Meiosis',
      'Independent assortment',
      'Crossing over',
      'Random fertilisation',
      'Mutations',
      'Gene mutations',
      'Chromosome mutations',
      // 3.4.4 Genetic diversity and adaptation
      'Natural selection',
      'Types of selection',
      'Directional selection',
      'Stabilising selection',
      'Adaptations',
      // 3.4.5 Species and taxonomy
      'Species definition',
      'Classification systems',
      'Phylogenetic classification',
      'Binomial naming',
      'Three-domain system',
      // 3.4.6 Biodiversity within a community
      'Species richness',
      'Index of diversity',
      'Sampling techniques',
      'Required Practical 7: DNA electrophoresis',
    ],
  },

  // ============================================================================
  // PAPER 2 TOPICS (5-8)
  // ============================================================================
  {
    id: 'aqa-alevel-biology-energy-transfers',
    examBoard: 'aqa',
    name: 'Energy Transfers in and between Organisms',
    description: 'Photosynthesis, respiration, energy and ecosystems',
    icon: '⚡',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.5.1 Photosynthesis
      'Photosynthesis overview',
      'Light-dependent reactions',
      'Photosystems',
      'Photophosphorylation',
      'Cyclic photophosphorylation',
      'Non-cyclic photophosphorylation',
      'Chemiosmosis in chloroplasts',
      'Light-independent reactions',
      'Calvin cycle',
      'Carbon fixation',
      'Rubisco',
      'Limiting factors',
      'Required Practical 8: Chromatography of photosynthetic pigments',
      // 3.5.2 Respiration
      'Glycolysis',
      'Link reaction',
      'Krebs cycle',
      'Oxidative phosphorylation',
      'Electron transport chain',
      'Chemiosmosis in mitochondria',
      'ATP yield',
      'Anaerobic respiration',
      'Respiratory substrates',
      'Respiratory quotient',
      'Required Practical 9: Respiration using respirometer',
      // 3.5.3 Energy and ecosystems
      'Food chains and webs',
      'Producers and consumers',
      'Trophic levels',
      'Gross primary productivity',
      'Net primary productivity',
      'Energy transfer efficiency',
      'Net production',
      'Farming practices and productivity',
    ],
  },
  {
    id: 'aqa-alevel-biology-organisms-respond',
    examBoard: 'aqa',
    name: 'Organisms Respond to Changes',
    description: 'Nervous and hormonal coordination, muscle contraction, and homeostasis',
    icon: '🧠',
    color: 'bg-red-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.6.1 Stimuli and responses
      'Nervous communication',
      'Hormonal communication',
      'Tropisms in plants',
      'Taxes and kineses',
      'Reflexes',
      // 3.6.2 Nervous coordination and muscles
      // Receptors
      'Receptors',
      'Pacinian corpuscle',
      'Retina structure',
      'Rods and cones',
      // Neurones
      'Neurone structure',
      'Sensory neurones',
      'Motor neurones',
      'Relay neurones',
      'Resting potential',
      'Action potential',
      'Refractory period',
      'Saltatory conduction',
      'Myelination',
      'Factors affecting conduction speed',
      // Synapses
      'Synapse structure',
      'Synaptic transmission',
      'Neurotransmitters',
      'Acetylcholine',
      'Summation',
      'Effects of drugs on synapses',
      // Muscles
      'Muscle structure',
      'Sarcomere structure',
      'Sliding filament theory',
      'Role of ATP in contraction',
      'Role of calcium ions',
      'Fast and slow twitch fibres',
      'Required Practical 10: Dissection of muscle and nerve tissue',
      // 3.6.3 Homeostasis
      // Control mechanisms
      'Homeostasis definition',
      'Negative feedback',
      'Positive feedback',
      // Control of blood glucose
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Second messengers',
      'Diabetes mellitus',
      'Type 1 and Type 2 diabetes',
      // Control of blood water potential
      'ADH',
      'Osmoregulation',
      'Kidney structure',
      'Nephron',
      'Ultrafiltration',
      'Selective reabsorption',
      'Loop of Henle',
      'Counter-current multiplier',
      'Required Practical 11: Animal response investigation',
      // 3.6.4 Plant responses
      'Plant hormones',
      'Auxins',
      'Gibberellins',
      'Ethene',
      'Abscisic acid',
      'Phototropism mechanism',
      'Commercial uses of plant hormones',
      'Required Practical 12: Plant response investigation',
    ],
  },
  {
    id: 'aqa-alevel-biology-genetics-populations',
    examBoard: 'aqa',
    name: 'Genetics, Populations, Evolution and Ecosystems',
    description: 'Inheritance, population genetics, evolution, and ecosystems',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.7.1 Inheritance
      'Mendel\'s laws',
      'Monohybrid inheritance',
      'Dihybrid inheritance',
      'Codominance',
      'Multiple alleles',
      'Sex linkage',
      'Autosomal linkage',
      'Epistasis',
      'Chi-squared test',
      // 3.7.2 Populations
      'Gene pool',
      'Allele frequency',
      'Hardy-Weinberg principle',
      'Hardy-Weinberg equation',
      // 3.7.3 Evolution
      'Types of variation',
      'Natural selection',
      'Speciation',
      'Allopatric speciation',
      'Sympatric speciation',
      'Genetic drift',
      'Founder effect',
      'Bottleneck effect',
      // 3.7.4 Populations in ecosystems
      'Ecosystems',
      'Biotic factors',
      'Abiotic factors',
      'Population dynamics',
      'Predator-prey relationships',
      'Competition',
      'Interspecific competition',
      'Intraspecific competition',
      'Succession',
      'Primary succession',
      'Secondary succession',
      'Climax community',
      'Conservation',
      'Nitrogen cycle',
      'Phosphorus cycle',
    ],
  },
  {
    id: 'aqa-alevel-biology-gene-expression',
    examBoard: 'aqa',
    name: 'The Control of Gene Expression',
    description: 'Gene regulation, recombinant DNA technology, and gene therapy',
    icon: '🔧',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.8.1 Alteration of the sequence of bases in DNA
      'Mutations',
      'Point mutations',
      'Deletion mutations',
      'Effects of mutations',
      'Mutagenic agents',
      // 3.8.2 Gene expression
      'Totipotency',
      'Stem cells',
      'Cell specialisation',
      'Regulation of transcription',
      'Transcription factors',
      'Oestrogen and gene expression',
      'Epigenetics',
      'DNA methylation',
      'Histone modification',
      // 3.8.3 Using genome projects
      'Sequencing genomes',
      'Comparing genomes',
      'Proteomics',
      'Synthetic biology',
      // 3.8.4 Recombinant DNA technology
      'Restriction enzymes',
      'Ligases',
      'Vectors',
      'Plasmids',
      'Transformation',
      'Gene probes',
      'Gel electrophoresis',
      'PCR',
      'Genetic fingerprinting',
      'Locating genes',
      // 3.8.5 Gene therapy
      'Treating genetic disorders',
      'Somatic cell therapy',
      'Germ line therapy',
      'Viral vectors',
      'Ethical considerations',
    ],
  },
];

export function getAQAALevelBiologyTopicById(id: string): Topic | undefined {
  return aqaALevelBiologyTopics.find((topic) => topic.id === id);
}

export function getAQAALevelBiologyTopicsByPaper(paper: 1 | 2): Topic[] {
  const paperName = `Paper ${paper}`;
  return aqaALevelBiologyTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countAQAALevelBiologySubtopics(): number {
  return aqaALevelBiologyTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
