// Edexcel GCSE Chemistry (1CH0) Topics
// Complete specification coverage
// Paper 1: Topics 1-5 (Key concepts to Separate chemistry 1)
// Paper 2: Topics 6-9 (Groups to Separate chemistry 2)

import { Topic } from '@/types';

export const edexcelChemistryTopics: Topic[] = [
  // ==========================================
  // PAPER 1 TOPICS
  // ==========================================

  // Topic 1: Key Concepts in Chemistry
  {
    id: 'edexcel-gcse-chemistry-key-concepts',
    name: 'Key Concepts in Chemistry',
    description: 'Atomic structure, periodic table, ionic and covalent bonding, equations and calculations',
    icon: '⚛️',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 1a Atomic structure
      'Atoms, elements, compounds and mixtures',
      'Structure of an atom',
      'Protons, neutrons and electrons',
      'Atomic number and mass number',
      'Electron configuration',
      'Electron shells and energy levels',
      'Isotopes',
      'Relative atomic mass',
      'Calculating relative atomic mass',
      // 1b The periodic table
      'The modern periodic table',
      'Mendeleev and the periodic table',
      'Periods and groups',
      'Metals and non-metals',
      'Electronic structure and position in periodic table',
      // 1c Ionic bonding
      'Formation of ions',
      'Positive and negative ions',
      'Ionic bonding',
      'Dot and cross diagrams for ionic compounds',
      'Properties of ionic compounds',
      'Giant ionic lattices',
      'Melting and boiling points of ionic compounds',
      'Electrical conductivity of ionic compounds',
      // 1d Covalent bonding
      'Covalent bonds',
      'Sharing electrons',
      'Single and double covalent bonds',
      'Dot and cross diagrams for covalent molecules',
      'Properties of simple molecular compounds',
      'Weak intermolecular forces',
      'Giant covalent structures',
      'Diamond',
      'Graphite',
      'Silicon dioxide',
      'Fullerenes and graphene',
      // 1e Types of substance
      'Metallic bonding',
      'Properties of metals',
      'Alloys',
      'Polymers',
      // 1f Calculations involving masses
      'Relative formula mass (Mr)',
      'Conservation of mass',
      'Balancing chemical equations',
      'Calculating masses in reactions',
      'The mole',
      'Avogadro constant',
      'Moles and mass calculations',
      'Concentration of solutions',
      'Calculating concentration in g/dm³',
      'Calculating concentration in mol/dm³ (HT)',
      'Percentage yield',
      'Atom economy',
    ],
  },

  // Topic 2: States of Matter and Mixtures
  {
    id: 'edexcel-gcse-chemistry-states-mixtures',
    name: 'States of Matter and Mixtures',
    description: 'States of matter, separation techniques, and methods of purification',
    icon: '💧',
    color: 'bg-cyan-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 2a States of matter
      'Solids, liquids and gases',
      'Particle model',
      'Properties of solids, liquids and gases',
      'Changes of state',
      'Melting and freezing',
      'Boiling and condensing',
      'Sublimation',
      'State symbols in equations',
      'Limitations of the particle model',
      // 2b Methods of separating and purifying substances
      'Pure substances and mixtures',
      'Melting point of pure substances',
      'Boiling point of pure substances',
      'Filtration',
      'Evaporation',
      'Crystallisation',
      'Simple distillation',
      'Fractional distillation',
      'Separating immiscible liquids',
      'Chromatography',
      'Paper chromatography',
      'Rf values',
      'Calculating Rf values',
      'Identifying substances using chromatography',
      // 2c Solubility
      'Solubility',
      'Saturated solutions',
      'Solubility curves',
      'Effect of temperature on solubility',
    ],
  },

  // Topic 3: Chemical Changes
  {
    id: 'edexcel-gcse-chemistry-chemical-changes',
    name: 'Chemical Changes',
    description: 'Acids, bases, neutralisation, electrolysis, and obtaining metals',
    icon: '🧪',
    color: 'bg-orange-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 3a Acids, alkalis and neutralisation
      'Acids and bases',
      'The pH scale',
      'pH and hydrogen ion concentration (HT)',
      'Indicators',
      'Universal indicator',
      'Neutralisation reactions',
      'Acids and metal oxides',
      'Acids and metal hydroxides',
      'Acids and metal carbonates',
      'Acids and metals',
      'Making salts',
      'Soluble and insoluble salts',
      'Crystallisation',
      'Strong and weak acids (HT)',
      'Concentration vs strength (HT)',
      // 3b Reactivity series and displacement
      'Reactivity series',
      'Reactions of metals with water',
      'Reactions of metals with dilute acids',
      'Displacement reactions',
      'Metal displacement from solutions',
      // 3c Oxidation and reduction
      'Oxidation as gain of oxygen',
      'Reduction as loss of oxygen',
      'Redox reactions',
      'Oxidation as loss of electrons (HT)',
      'Reduction as gain of electrons (HT)',
      'Ionic half equations (HT)',
      // 3d Electrolysis
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Anode and cathode',
      'Electrolysis of molten compounds',
      'Electrolysis of aqueous solutions',
      'Products at electrodes',
      'Electrolysis of sodium chloride solution',
      'Industrial uses of electrolysis',
      'Half equations at electrodes (HT)',
      'Extraction of aluminium',
      'Purification of copper',
    ],
  },

  // Topic 4: Extracting Metals and Equilibria
  {
    id: 'edexcel-gcse-chemistry-metals-equilibria',
    name: 'Extracting Metals and Equilibria',
    description: 'Extraction of metals, life cycle assessments, and reversible reactions',
    icon: '⚙️',
    color: 'bg-gray-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4a Obtaining and using metals
      'Metal ores',
      'Extraction and the reactivity series',
      'Reduction with carbon',
      'Extraction of iron in the blast furnace',
      'Extraction of aluminium by electrolysis',
      'Biological methods of extraction',
      'Phytomining',
      'Bioleaching',
      'Recycling metals',
      'Life cycle assessment (LCA)',
      'Stages of a life cycle assessment',
      'Comparing life cycle assessments',
      // 4b Reversible reactions and equilibria
      'Reversible reactions',
      'The ⇌ symbol',
      'Energy changes in reversible reactions',
      'Dynamic equilibrium (HT)',
      'Closed systems (HT)',
      'Effect of temperature on equilibrium (HT)',
      'Effect of pressure on equilibrium (HT)',
      'Effect of concentration on equilibrium (HT)',
    ],
  },

  // Topic 5: Separate Chemistry 1 (Triple Science)
  {
    id: 'edexcel-gcse-chemistry-separate1',
    name: 'Separate Chemistry 1',
    description: 'Transition metals, alloys, quantitative analysis, and dynamic equilibria',
    icon: '🔬',
    color: 'bg-purple-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 5a Transition metals, alloys and corrosion
      'Transition metals',
      'Properties of transition metals',
      'Transition metal compounds',
      'Coloured compounds',
      'Catalytic properties',
      'Alloys',
      'Properties of alloys',
      'Uses of alloys',
      'Corrosion',
      'Rusting of iron',
      'Preventing rusting',
      'Sacrificial protection',
      'Galvanising',
      // 5b Quantitative analysis
      'Titrations',
      'Titration method',
      'Titration calculations',
      'Calculating concentration from titration (HT)',
      'Molar volume of gases',
      'Volume of gases at RTP',
      'Calculating volumes of gases (HT)',
      // 5c Dynamic equilibria (HT)
      'Position of equilibrium (HT)',
      'Le Chatelier\'s principle (HT)',
      'Optimising conditions (HT)',
      'Haber process conditions (HT)',
      'Contact process conditions (HT)',
    ],
  },

  // ==========================================
  // PAPER 2 TOPICS
  // ==========================================

  // Topic 6: Groups in the Periodic Table
  {
    id: 'edexcel-gcse-chemistry-groups',
    name: 'Groups in the Periodic Table',
    description: 'Group 1, Group 7, Group 0, and tests for ions and gases',
    icon: '📊',
    color: 'bg-indigo-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 6a Group 1 - The alkali metals
      'Group 1 - The alkali metals',
      'Properties of alkali metals',
      'Reactions with water',
      'Reactions with oxygen',
      'Reactions with chlorine',
      'Trends in reactivity down Group 1',
      'Explaining reactivity trends',
      // 6b Group 7 - The halogens
      'Group 7 - The halogens',
      'Properties of halogens',
      'Physical states of halogens',
      'Colours of halogens',
      'Trends in physical properties',
      'Reactions with metals',
      'Reactions with non-metals',
      'Displacement reactions',
      'Trends in reactivity down Group 7',
      'Explaining reactivity trends',
      'Halide ion tests',
      // 6c Group 0 - The noble gases
      'Group 0 - The noble gases',
      'Properties of noble gases',
      'Unreactivity of noble gases',
      'Electronic configuration of noble gases',
      'Uses of noble gases',
      'Trends in boiling points',
      // 6d Tests for ions and gases
      'Flame tests',
      'Flame test colours',
      'Testing for metal ions using sodium hydroxide',
      'Metal hydroxide precipitates',
      'Testing for carbonates',
      'Testing for halide ions',
      'Testing for sulfate ions',
      'Test for hydrogen',
      'Test for oxygen',
      'Test for carbon dioxide',
      'Test for chlorine',
    ],
  },

  // Topic 7: Rates of Reaction and Energy Changes
  {
    id: 'edexcel-gcse-chemistry-rates-energy',
    name: 'Rates of Reaction and Energy Changes',
    description: 'Rates of reaction, catalysts, exothermic and endothermic reactions',
    icon: '⏱️',
    color: 'bg-yellow-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 7a Rates of reaction
      'Rate of reaction',
      'Measuring rate of reaction',
      'Calculating rate of reaction',
      'Rate from graphs',
      'Mean rate of reaction',
      'Factors affecting rate',
      'Effect of concentration',
      'Effect of surface area',
      'Effect of temperature',
      'Effect of pressure (gases)',
      'Effect of catalysts',
      // 7b Collision theory
      'Collision theory',
      'Activation energy',
      'Frequency of collisions',
      'Successful collisions',
      'Explaining concentration effect',
      'Explaining surface area effect',
      'Explaining temperature effect',
      'Explaining catalyst effect',
      // 7c Catalysts and enzymes
      'Catalysts',
      'How catalysts work',
      'Catalysts in industry',
      'Enzymes',
      'Enzymes as biological catalysts',
      'Properties of enzymes',
      // 7d Exothermic and endothermic reactions
      'Energy transfer in reactions',
      'Exothermic reactions',
      'Examples of exothermic reactions',
      'Endothermic reactions',
      'Examples of endothermic reactions',
      'Measuring temperature changes',
      'Reaction profiles',
      'Activation energy on profiles',
      'Effect of catalysts on reaction profiles',
      // 7e Bond energies (HT)
      'Bond energies (HT)',
      'Breaking bonds - endothermic (HT)',
      'Making bonds - exothermic (HT)',
      'Calculating energy change (HT)',
      'Using bond energies (HT)',
    ],
  },

  // Topic 8: Fuels and Earth Science
  {
    id: 'edexcel-gcse-chemistry-fuels-earth',
    name: 'Fuels and Earth Science',
    description: 'Hydrocarbons, crude oil, combustion, the atmosphere, and climate',
    icon: '🌍',
    color: 'bg-green-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 8a Hydrocarbons
      'Hydrocarbons',
      'Crude oil',
      'Finite resources',
      'Alkanes',
      'General formula of alkanes',
      'Names and formulae of alkanes',
      'Displayed formulae',
      'Structural formulae',
      'Properties of hydrocarbons',
      'Boiling points of alkanes',
      'Viscosity of alkanes',
      'Flammability of alkanes',
      // 8b Fractional distillation
      'Fractional distillation',
      'Fractionating column',
      'Fractions from crude oil',
      'Uses of fractions',
      'Refinery gases',
      'Petrol',
      'Kerosene',
      'Diesel',
      'Fuel oil',
      'Bitumen',
      // 8c Combustion
      'Complete combustion',
      'Incomplete combustion',
      'Products of combustion',
      'Carbon dioxide',
      'Water',
      'Carbon monoxide',
      'Soot (carbon particulates)',
      'Sulfur dioxide',
      'Nitrogen oxides',
      'Acid rain',
      'Global dimming',
      // 8d Earth and atmospheric science
      'Evolution of the atmosphere',
      'Early atmosphere',
      'Volcanic activity',
      'Development of the atmosphere',
      'Photosynthesis and oxygen',
      'Formation of fossil fuels',
      'Composition of the atmosphere today',
      'Greenhouse gases',
      'The greenhouse effect',
      'Global warming',
      'Climate change',
      'Evidence for climate change',
      'Reducing carbon emissions',
      'Carbon footprint',
    ],
  },

  // Topic 9: Separate Chemistry 2 (Triple Science)
  {
    id: 'edexcel-gcse-chemistry-separate2',
    name: 'Separate Chemistry 2',
    description: 'Hydrocarbons reactions, alcohols, carboxylic acids, polymers, and nanoparticles',
    icon: '🛢️',
    color: 'bg-red-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 9a Alkenes and reactions of alkenes
      'Alkenes',
      'General formula of alkenes',
      'The C=C double bond',
      'Names and formulae of alkenes',
      'Displayed formulae of alkenes',
      'Test for alkenes (bromine water)',
      'Addition reactions',
      'Hydrogenation',
      'Hydration',
      'Halogenation',
      // 9b Alcohols, carboxylic acids and esters
      'Alcohols',
      'Functional group of alcohols (-OH)',
      'Names and formulae of alcohols',
      'Properties of alcohols',
      'Reactions of alcohols',
      'Combustion of alcohols',
      'Oxidation of alcohols',
      'Carboxylic acids',
      'Functional group (-COOH)',
      'Names and formulae of carboxylic acids',
      'Properties of carboxylic acids',
      'Reactions of carboxylic acids',
      'Weak acids',
      'Esters',
      'Formation of esters',
      'Naming esters',
      'Uses of esters',
      // 9c Addition polymerisation
      'Polymers',
      'Addition polymerisation',
      'Monomers',
      'Poly(ethene)',
      'Poly(propene)',
      'Poly(chloroethene) (PVC)',
      'PTFE',
      'Drawing polymer structures',
      'Identifying monomers from polymers',
      // 9d Condensation polymerisation
      'Condensation polymerisation',
      'Polyesters',
      'Polyamides (nylon)',
      'Amino acids',
      'Proteins',
      'DNA structure',
      // 9e Nanoparticles
      'Nanoparticles',
      'Size of nanoparticles',
      'Surface area to volume ratio',
      'Properties of nanoparticles',
      'Uses of nanoparticles',
      'Nanoparticles in sunscreens',
      'Nanoparticles in electronics',
      'Nanoparticles in medicine',
      'Risks of nanoparticles',
    ],
  },
];

export function getEdexcelChemistryTopicById(id: string): Topic | undefined {
  return edexcelChemistryTopics.find(topic => topic.id === id);
}
