// Edexcel GCSE Geography A (1GA0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/geography-a-2016.html

import { Topic } from '@/types';

export const edexcelGCSEGeographyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: THE PHYSICAL ENVIRONMENT
  // ============================================================================
  {
    id: 'hazardous-earth',
    name: 'The Changing Climate and Hazardous Earth',
    description: 'Past climate, climate change and tectonic hazards',
    icon: '🌋',
    color: 'bg-red-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Past climate
      'Evidence for past climate change',
      'Ice cores',
      'Tree rings',
      'Historical records',
      'Natural causes of climate change',
      'Orbital changes (Milankovitch)',
      'Solar output variation',
      'Volcanic activity',
      // Present climate change
      'Enhanced greenhouse effect',
      'Human causes of climate change',
      'Fossil fuel burning',
      'Deforestation',
      'Agriculture',
      // Climate change impacts
      'Global temperature rise',
      'Sea level rise',
      'Extreme weather',
      'Ecosystem changes',
      'Impacts on people',
      // Responses to climate change
      'Mitigation strategies',
      'Adaptation strategies',
      'International agreements',
      'Individual actions',
      // Global atmospheric circulation
      'Pressure belts',
      'Hadley cells',
      'Trade winds',
      'Westerlies',
      // Natural hazards
      'Definition of natural hazard',
      'Hazard risk factors',
      'Vulnerability',
      // Plate tectonics
      'Structure of Earth',
      'Tectonic plates',
      'Plate boundaries',
      'Constructive/divergent margins',
      'Destructive/convergent margins',
      'Conservative/transform margins',
      'Distribution of earthquakes/volcanoes',
      // Earthquakes
      'Causes of earthquakes',
      'Focus and epicentre',
      'Seismic waves',
      'Measuring earthquakes',
      'Richter and Mercalli scales',
      // Earthquake impacts
      'Primary effects',
      'Secondary effects',
      'Tsunamis',
      'Earthquake responses',
      'Contrasting earthquake examples',
      // Volcanoes
      'Causes of volcanic eruptions',
      'Types of volcano',
      'Volcanic hazards',
      'Volcanic impacts',
      'Volcanic responses',
      // Managing tectonic hazards
      'Prediction',
      'Protection',
      'Planning',
      'Tectonic hazard case study',
    ],
  },
  {
    id: 'coastal-landscapes',
    name: 'Coastal Landscapes and Processes',
    description: 'Coastal processes, landforms and management',
    icon: '🌊',
    color: 'bg-cyan-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Coastal system
      'The coast as a system',
      'Inputs, processes, outputs',
      // Waves
      'Wave formation',
      'Wave characteristics',
      'Fetch',
      'Constructive waves',
      'Destructive waves',
      'Swash and backwash',
      // Weathering
      'Mechanical weathering',
      'Freeze-thaw',
      'Salt crystallisation',
      'Chemical weathering',
      'Biological weathering',
      // Mass movement
      'Rock falls',
      'Landslides',
      'Slumping',
      'Soil creep',
      // Coastal erosion
      'Hydraulic action',
      'Abrasion',
      'Attrition',
      'Corrosion',
      'Rates of erosion',
      // Erosional landforms
      'Cliffs',
      'Wave-cut platforms',
      'Headlands and bays',
      'Caves',
      'Arches',
      'Stacks',
      'Stumps',
      // Transport processes
      'Longshore drift',
      'Traction',
      'Saltation',
      'Suspension',
      'Solution',
      // Depositional landforms
      'Beaches',
      'Spits',
      'Bars',
      'Tombolos',
      'Sand dunes',
      // Human activity at coasts
      'Coastal development',
      'Coastal settlements',
      'Tourism',
      'Industry',
      // Coastal management
      'Reasons for management',
      'Hard engineering',
      'Sea walls',
      'Groynes',
      'Rock armour',
      'Gabions',
      'Soft engineering',
      'Beach nourishment',
      'Dune regeneration',
      'Managed retreat',
      'Coastal management case study',
    ],
  },
  {
    id: 'river-landscapes',
    name: 'River Landscapes and Processes',
    description: 'River processes, landforms and flooding',
    icon: '🏞️',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // River system
      'The river as a system',
      'Drainage basin',
      'Watershed',
      'Source and mouth',
      'Tributary and confluence',
      // Water cycle
      'Water cycle processes',
      'Interception',
      'Infiltration',
      'Surface runoff',
      'Throughflow',
      'Groundwater flow',
      // River erosion
      'Hydraulic action',
      'Abrasion',
      'Attrition',
      'Solution',
      // River transport
      'Traction',
      'Saltation',
      'Suspension',
      'Solution',
      // River deposition
      'Why rivers deposit',
      'When rivers deposit',
      // Long and cross profiles
      'Upper course',
      'Middle course',
      'Lower course',
      'Changes downstream',
      // Upper course landforms
      'V-shaped valleys',
      'Interlocking spurs',
      'Waterfalls',
      'Gorges',
      'Rapids',
      // Middle/lower course landforms
      'Meanders',
      'Ox-bow lakes',
      'Floodplains',
      'Levees',
      'Deltas',
      'Estuaries',
      // Flooding
      'Causes of flooding',
      'Physical factors',
      'Human factors',
      'Hydrographs',
      'Rising and falling limbs',
      'Lag time',
      'Peak discharge',
      // Flood impacts
      'Social impacts',
      'Economic impacts',
      'Environmental impacts',
      // Flood management
      'Hard engineering',
      'Dams and reservoirs',
      'Channel straightening',
      'Embankments',
      'Flood walls',
      'Soft engineering',
      'Flood warnings',
      'Preparation',
      'Floodplain zoning',
      'Afforestation',
      'River flooding case study',
    ],
  },
  {
    id: 'glaciated-landscapes',
    name: 'Glaciated Upland Landscapes',
    description: 'Glacial processes and landforms in the UK',
    icon: '❄️',
    color: 'bg-blue-200',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Ice ages
      'Past glaciation in UK',
      'Extent of ice cover',
      'Evidence of glaciation',
      // Glacier formation
      'How glaciers form',
      'Accumulation',
      'Compaction',
      'Glacial ice',
      // Glacier movement
      'Gravity and movement',
      'Rotational movement',
      'Basal sliding',
      // Glacial erosion
      'Plucking',
      'Abrasion',
      'Freeze-thaw weathering',
      // Erosional landforms
      'Corries/cirques',
      'Aretes',
      'Pyramidal peaks',
      'U-shaped valleys',
      'Hanging valleys',
      'Truncated spurs',
      'Ribbon lakes',
      'Roches moutonnees',
      // Glacial deposition
      'Till/boulder clay',
      'Moraines',
      'Lateral moraines',
      'Medial moraines',
      'Terminal moraines',
      'Ground moraine',
      'Drumlins',
      'Erratics',
      // Human activity
      'Tourism in glaciated areas',
      'Lake District',
      'Scottish Highlands',
      'Farming in glaciated areas',
      'Quarrying',
      // Managing glaciated landscapes
      'Conflicts in National Parks',
      'Sustainable management',
      'Conservation',
    ],
  },
  // ============================================================================
  // PAPER 2: THE HUMAN ENVIRONMENT
  // ============================================================================
  {
    id: 'changing-cities',
    name: 'Changing Cities',
    description: 'Urbanisation and urban change',
    icon: '🏙️',
    color: 'bg-gray-600',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Urbanisation
      'Global urbanisation trends',
      'Causes of urbanisation',
      'Push factors',
      'Pull factors',
      'Natural increase',
      'Megacities',
      // UK urbanisation
      'UK urban areas',
      'Counter-urbanisation',
      'Suburbanisation',
      'Re-urbanisation',
      // Urban land use
      'CBD',
      'Inner city',
      'Suburbs',
      'Rural-urban fringe',
      'Land use patterns',
      // Major UK city case study
      'UK city example',
      'Location and growth',
      'Migration impacts',
      'Economic change',
      // Urban opportunities
      'Employment',
      'Services',
      'Culture and leisure',
      'Housing',
      // Urban challenges
      'Urban deprivation',
      'Inequality',
      'Environmental issues',
      'Traffic and transport',
      // Urban sustainability
      'Sustainable urban development',
      'Green transport',
      'Brownfield development',
      'Urban greening',
      'Waste management',
      // NEE city case study
      'NEE city example (e.g. Mumbai)',
      'Location and importance',
      'Growth of city',
      'Opportunities',
      'Challenges',
      'Squatter settlements',
      'Improving quality of life',
    ],
  },
  {
    id: 'global-development',
    name: 'Global Development',
    description: 'Development patterns and reducing the gap',
    icon: '🌍',
    color: 'bg-yellow-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Measuring development
      'What is development?',
      'Economic indicators',
      'GDP/GNI',
      'Social indicators',
      'Life expectancy',
      'Literacy rate',
      'Infant mortality',
      'Composite indicators',
      'HDI',
      // Global development patterns
      'Global inequality',
      'Development gap',
      'North-South divide',
      // Causes of inequality
      'Physical factors',
      'Location and climate',
      'Natural resources',
      'Economic factors',
      'Trade',
      'Debt',
      'Historical factors',
      'Colonialism',
      'Political factors',
      'Governance',
      'Conflict',
      // Development theories
      'Rostow model',
      'Dependency theory',
      // Changing patterns
      'NICs/NEEs',
      'Emerging economies',
      // Reducing development gap
      'Aid',
      'Types of aid',
      'Bilateral and multilateral',
      'NGO aid',
      'Trade',
      'Fair trade',
      'Trade agreements',
      'Investment',
      'FDI',
      'TNCs',
      'Technology',
      'Intermediate technology',
      'Debt relief',
      'Microfinance',
      // Sustainable development
      'Sustainability goals',
      'UN SDGs',
      // Development case study
      'Country case study',
      'Development strategies',
    ],
  },
  {
    id: 'resource-management',
    name: 'Resource Management and Energy',
    description: 'Global resource challenges and energy security',
    icon: '⚡',
    color: 'bg-orange-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Resource overview
      'Types of resources',
      'Renewable resources',
      'Non-renewable resources',
      'Resource distribution',
      // Resource consumption
      'Global consumption patterns',
      'Factors affecting consumption',
      'Population growth',
      'Economic development',
      'Technology',
      // Resource challenges
      'Resource depletion',
      'Resource conflicts',
      // Energy resources
      'Types of energy',
      'Fossil fuels',
      'Coal',
      'Oil',
      'Natural gas',
      // Non-renewable energy
      'Formation of fossil fuels',
      'Distribution of fossil fuels',
      'Extraction methods',
      'Environmental impacts',
      // Renewable energy
      'Solar energy',
      'Wind energy',
      'Hydroelectric power',
      'Tidal energy',
      'Wave energy',
      'Geothermal energy',
      'Biomass',
      // Nuclear energy
      'How nuclear works',
      'Advantages and disadvantages',
      // Energy supply and demand
      'Global energy demand',
      'Energy mix',
      'Energy security',
      'Energy insecurity',
      // Managing energy
      'Reducing demand',
      'Energy efficiency',
      'Alternative energy',
      'Energy conservation',
      // UK energy
      'UK energy mix',
      'Changes in UK energy',
      'Future energy strategies',
    ],
  },
  // ============================================================================
  // PAPER 3: GEOGRAPHICAL INVESTIGATIONS
  // ============================================================================
  {
    id: 'fieldwork-skills',
    name: 'Fieldwork and UK Challenges',
    description: 'Geographical investigations and skills',
    icon: '📊',
    color: 'bg-purple-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'geography',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Fieldwork enquiry
      'Geographical questions',
      'Hypotheses',
      'Planning investigations',
      // Data collection
      'Primary data',
      'Secondary data',
      'Sampling methods',
      'Random sampling',
      'Systematic sampling',
      'Stratified sampling',
      // Fieldwork methods
      'Questionnaires',
      'Interviews',
      'Environmental quality surveys',
      'Field sketches',
      'Photography',
      'Measurement techniques',
      // Physical fieldwork
      'River fieldwork',
      'Coastal fieldwork',
      'Measuring techniques',
      // Human fieldwork
      'Urban fieldwork',
      'Land use surveys',
      'Traffic counts',
      // Data presentation
      'Maps',
      'Graphs',
      'Charts',
      'Photographs',
      'GIS',
      // Data analysis
      'Describing data',
      'Explaining data',
      'Identifying patterns',
      'Identifying anomalies',
      // Conclusions and evaluation
      'Drawing conclusions',
      'Evaluating enquiry',
      'Reliability',
      'Accuracy',
      'Improvements',
      // UK challenges
      'UK geographical issues',
      'Decision-making',
      'Evaluating options',
      'Resource analysis',
      // Geographical skills
      'Map skills',
      'OS maps',
      'Grid references',
      'Scale and distance',
      'Relief and contours',
      'Graphical skills',
      'Statistical skills',
      'Mean, median, mode',
      'Percentages',
    ],
  },
];

export function getEdexcelGCSEGeographyTopicById(id: string): Topic | undefined {
  return edexcelGCSEGeographyTopics.find((topic) => topic.id === id);
}
