// OCR Gateway GCSE Physics A (J249) Topics
// Complete specification coverage for examinations from 2024 onwards
// Paper 1: Topics P1-P4 (50% of GCSE)
// Paper 2: Topics P5-P8 (50% of GCSE)
// Higher Tier content marked with (HT)

import { Topic } from '@/types';

export const ocrPhysicsTopics: Topic[] = [
  // =====================
  // PAPER 1 - Topics P1-P4
  // =====================

  // P1: Matter
  {
    id: 'ocr-physics-p1-matter',
    name: 'P1: Matter',
    description: 'The particle model, changes of state, and pressure',
    icon: '🔬',
    color: 'bg-purple-500',
    subtopics: [
      // P1.1 The Particle Model
      'Development of atomic models (Thomson, Rutherford, Bohr)',
      'Nuclear composition: protons, neutrons, electrons',
      'Atomic size and order of magnitude (~1×10⁻¹⁰ m)',
      'Density: definition and calculations',
      'Density = mass / volume',
      'Comparing densities of solids, liquids and gases',
      'Measuring density of regular and irregular objects',
      'Particle arrangement in solids, liquids and gases',
      'Particle motion and energy in different states',
      // P1.2 Changes of State
      'Conservation of mass during state changes',
      'Physical vs chemical changes',
      'Energy transfer during heating',
      'Heating curves and state changes',
      'Specific heat capacity: E = mcΔθ',
      'Calculating energy for temperature changes',
      'Specific latent heat: E = mL',
      'Latent heat of fusion and vaporisation',
      'Why temperature stays constant during state changes',
      'Required practical: specific heat capacity measurement',
      // P1.3 Pressure
      'Gas pressure and molecular motion',
      'Temperature and pressure relationship in gases',
      'Constant volume: pressure ∝ temperature',
      'Boyle\'s law: pV = constant',
      'Compressing gases and work done (HT)',
      'Atmospheric pressure',
      'Atmospheric pressure variation with altitude',
      'Liquid pressure and depth: p = hρg (HT)',
      'Upthrust and floating/sinking (HT)',
      'Hydraulic systems and pressure transmission',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 1',
  },

  // P2: Forces
  {
    id: 'ocr-physics-p2-forces',
    name: 'P2: Forces',
    description: 'Motion, Newton\'s laws, and forces in action',
    icon: '🚀',
    color: 'bg-blue-500',
    subtopics: [
      // P2.1 Motion
      'Distance and displacement',
      'Speed and velocity',
      'Scalar and vector quantities',
      'Speed = distance / time',
      'Typical speeds: walking, running, cycling, cars',
      'Distance-time graphs',
      'Calculating speed from d-t graphs (gradient)',
      'Velocity-time graphs',
      'Calculating acceleration from v-t graphs (gradient)',
      'Calculating distance from v-t graphs (area under curve) (HT)',
      'Uniform motion and non-uniform motion',
      'Average speed calculations',
      'Acceleration = Δv / t',
      'Equations of motion: v² = u² + 2as',
      'Required practical: investigating motion',
      // P2.2 Newton's Laws
      'Contact and non-contact forces',
      'Gravitational, electrostatic and magnetic forces',
      'Free body force diagrams',
      'Resultant forces',
      'Resolving forces into components (HT)',
      'Newton\'s First Law: balanced forces',
      'Objects at rest and constant velocity',
      'Newton\'s Second Law: F = ma',
      'Calculating acceleration, force and mass',
      'Inertial mass and resistance to change (HT)',
      'Newton\'s Third Law: action-reaction pairs',
      'Identifying third law pairs',
      'Terminal velocity and drag forces (HT)',
      'Factors affecting drag',
      'Circular motion and changing velocity (HT)',
      'Centripetal force (HT)',
      'Momentum = mass × velocity (HT)',
      'Conservation of momentum (HT)',
      'Elastic and inelastic collisions (HT)',
      'Calculating momentum in collisions (HT)',
      // P2.3 Forces in Action
      'Deformation: stretching, compressing, bending',
      'Elastic and plastic deformation',
      'Hooke\'s Law: F = kx',
      'Spring constant calculations',
      'Limit of proportionality',
      'Energy stored in springs: E = ½kx²',
      'Required practical: force-extension investigation',
      'Gravitational field strength',
      'Weight = mg',
      'Weight on different planets',
      'Free fall and g = 9.8 m/s²',
      'Moments and turning effects',
      'Moment = force × distance',
      'Principle of moments',
      'Levers as force multipliers',
      'Gears: changing force and speed',
      'Pressure in fluids: p = F/A',
      'Hydraulic systems and force multiplication',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 1',
  },

  // P3: Electricity
  {
    id: 'ocr-physics-p3-electricity',
    name: 'P3: Electricity',
    description: 'Static electricity and simple circuits',
    icon: '⚡',
    color: 'bg-yellow-500',
    subtopics: [
      // P3.1 Static and Charge
      'Positive and negative charges',
      'Like charges repel, unlike attract',
      'Static electricity from friction',
      'Electron transfer and charging',
      'Insulators and conductors',
      'Electrostatic phenomena examples',
      'Electric fields around charges',
      'Electric field direction and strength',
      'Earthing and discharging',
      'Dangers of static electricity',
      'Uses of static: precipitators, spraying',
      'Current as flow of charge',
      'Charge, current and time: Q = It',
      'Conventional current direction',
      // P3.2 Simple Circuits
      'Circuit symbols and diagrams',
      'Series and parallel circuits',
      'Current in series circuits',
      'Current in parallel circuits',
      'Potential difference in series',
      'Potential difference in parallel',
      'Resistance in circuits',
      'Ohm\'s Law: V = IR',
      'Resistance of fixed resistors',
      'Variable resistors and rheostats',
      'I-V characteristics: resistors',
      'I-V characteristics: filament lamps',
      'I-V characteristics: diodes',
      'Required practical: I-V characteristics',
      'LDRs and light intensity',
      'Thermistors and temperature',
      'Total resistance in series circuits',
      'Total resistance in parallel circuits (HT)',
      'Power in circuits: P = IV',
      'Power equations: P = I²R and P = V²/R',
      'Energy transfer: E = Pt',
      'Energy and charge: E = QV',
      'AC and DC',
      'UK mains: 230V, 50Hz',
      'Three-wire cables: live, neutral, earth',
      'Fuses and circuit breakers',
      'Earthing for safety',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 1',
  },

  // P4: Magnetism and Magnetic Fields
  {
    id: 'ocr-physics-p4-magnetism',
    name: 'P4: Magnetism and Magnetic Fields',
    description: 'Magnets, magnetic fields and uses of magnetism',
    icon: '🧲',
    color: 'bg-red-500',
    subtopics: [
      // P4.1 Magnets and Magnetic Fields
      'Magnetic poles: north and south',
      'Like poles repel, unlike attract',
      'Magnetic vs non-magnetic materials',
      'Permanent and induced magnets',
      'Magnetic field lines and direction',
      'Field patterns around bar magnets',
      'Field strength variation with distance',
      'Earth\'s magnetic field',
      'Compass and Earth\'s core',
      'Magnetic field of current-carrying wire',
      'Right-hand grip rule',
      'Field around a straight conductor',
      'Field strength: current and distance factors',
      'Solenoid magnetic field',
      'Increasing solenoid field strength',
      'Electromagnets and applications',
      // P4.2 Uses of Magnetism (mostly HT)
      'Force on a current-carrying conductor (HT)',
      'Fleming\'s left-hand rule (HT)',
      'Motor effect: F = BIL (HT)',
      'DC motor construction and operation (HT)',
      'Motor components: split-ring commutator (HT)',
      'Electromagnetic induction (HT)',
      'Factors affecting induced EMF (HT)',
      'Alternators and AC generation (HT)',
      'Dynamos and DC generation (HT)',
      'Transformers: structure and function (HT)',
      'Transformer equation: Vp/Vs = Np/Ns (HT)',
      'Step-up and step-down transformers (HT)',
      'Transformer efficiency (HT)',
      'Microphones: pressure to current (HT)',
      'Loudspeakers: current to sound (HT)',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 1',
  },

  // =====================
  // PAPER 2 - Topics P5-P8
  // =====================

  // P5: Waves in Matter
  {
    id: 'ocr-physics-p5-waves',
    name: 'P5: Waves in Matter',
    description: 'Wave behaviour, the electromagnetic spectrum and wave interactions',
    icon: '🌊',
    color: 'bg-cyan-500',
    subtopics: [
      // P5.1 Wave Behaviour
      'Waves transfer energy without matter',
      'Amplitude, wavelength and frequency',
      'Wave period and frequency relationship',
      'Wave speed equation: v = fλ',
      'Transverse waves: oscillation perpendicular to travel',
      'Longitudinal waves: oscillation parallel to travel',
      'Examples of transverse waves',
      'Examples of longitudinal waves',
      'Sound as a longitudinal wave',
      'Sound wave compressions and rarefactions',
      'Required practical: measuring wave speed',
      'Reflection of waves',
      'Transmission and absorption',
      'Echoes and sound reflection',
      'Ultrasound and applications',
      'Sound to vibration conversion (HT)',
      'Vibration to sound conversion (HT)',
      // P5.2 The Electromagnetic Spectrum
      'EM waves as transverse waves',
      'EM waves travel at speed of light',
      'Speed of light: 3×10⁸ m/s',
      'EM spectrum: radio to gamma',
      'Frequency and wavelength across spectrum',
      'Radio waves: communication uses',
      'Microwaves: cooking and satellites',
      'Infrared: heating and thermal imaging',
      'Visible light: vision and photography',
      'Ultraviolet: fluorescence and security',
      'X-rays: medical imaging',
      'Gamma rays: medical treatment',
      'Hazards of UV, X-rays and gamma',
      'Protection from harmful radiation',
      'Detection using different EM waves (HT)',
      'Exploring structures with EM waves (HT)',
      // P5.3 Wave Interactions
      'Reflection at boundaries',
      'Law of reflection',
      'Refraction at boundaries',
      'Refraction direction changes',
      'Lenses: convex (converging)',
      'Lenses: concave (diverging)',
      'Ray diagrams through lenses',
      'Colour and absorption/reflection',
      'White light and colour mixing',
      'Filters and coloured objects',
      'Refraction and wave speed changes (HT)',
      'Required practical: light investigation',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 2',
  },

  // P6: Radioactivity
  {
    id: 'ocr-physics-p6-radioactivity',
    name: 'P6: Radioactivity',
    description: 'Radioactive emissions, uses and hazards',
    icon: '☢️',
    color: 'bg-orange-500',
    subtopics: [
      // P6.1 Radioactive Emissions
      'Nuclear composition: protons and neutrons',
      'Atomic number and mass number',
      'Isotopes: same element, different mass',
      'Radioactive decay: random process',
      'Alpha particles: 2 protons, 2 neutrons',
      'Alpha decay and nuclear equations',
      'Beta particles: high-speed electrons',
      'Beta decay and nuclear equations',
      'Gamma rays: electromagnetic radiation',
      'Neutron radiation',
      'Penetration: alpha, beta, gamma',
      'Ionisation: alpha, beta, gamma',
      'Stopping radiation: paper, aluminium, lead',
      'Background radiation sources',
      'Detecting radiation: Geiger-Müller tube',
      'Half-life: definition and concept',
      'Half-life calculations',
      'Decay graphs and half-life',
      'Activity and half-life relationship',
      'Net decline after multiple half-lives (HT)',
      'Required practical: half-life simulation',
      // P6.2 Uses and Hazards
      'Contamination vs irradiation',
      'Hazards of contamination',
      'Hazards of irradiation',
      'Half-life and hazard level',
      'Safe handling of radioactive sources',
      'Medical uses: tracers',
      'Medical uses: radiotherapy',
      'Industrial uses: thickness monitoring',
      'Smoke detectors and ionisation',
      'Nuclear fission: splitting heavy nuclei',
      'Chain reactions',
      'Nuclear reactors and energy',
      'Nuclear fusion: joining light nuclei',
      'Mass-energy equivalence (E = mc²)',
      'Fusion in stars',
      'Challenges of controlled fusion',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 2',
  },

  // P7: Energy
  {
    id: 'ocr-physics-p7-energy',
    name: 'P7: Energy',
    description: 'Work done, power and efficiency',
    icon: '🔋',
    color: 'bg-green-500',
    subtopics: [
      // P7.1 Work Done
      'Energy stores: kinetic, gravitational, elastic, thermal',
      'Energy stores: chemical, magnetic, electrostatic, nuclear',
      'Energy transfers: mechanically, electrically, by heating, by radiation',
      'Conservation of energy in closed systems',
      'Work done and energy transfer',
      'Work done = force × distance: W = Fd',
      'Work against friction and heating',
      'Kinetic energy: Ek = ½mv²',
      'Calculating kinetic energy',
      'Gravitational potential energy: Ep = mgh',
      'Calculating GPE changes',
      'Energy transfer between Ek and Ep',
      'Elastic potential energy: Ee = ½kx²',
      'Energy dissipation to surroundings',
      // P7.2 Power and Efficiency
      'Power as rate of energy transfer',
      'Power = energy / time: P = E/t',
      'Power = work done / time: P = W/t',
      'Power = force × velocity: P = Fv',
      'Watt as unit of power',
      'Comparing power of appliances',
      'Efficiency definition and calculation',
      'Efficiency = useful output / total input',
      'Efficiency as percentage or decimal',
      'Wasted energy in systems',
      'Reducing wasted energy',
      'Lubrication and friction reduction',
      'Thermal insulation: reducing heat loss',
      'Required practical: thermal insulation',
      'Thermal conductivity and materials',
      'U-values and building insulation',
      'Domestic energy use and costs',
      'Kilowatt-hours (kWh)',
      'Calculating energy costs',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 2',
  },

  // P8: Global Challenges
  {
    id: 'ocr-physics-p8-global',
    name: 'P8: Global Challenges',
    description: 'Physics on the move, powering Earth and beyond Earth',
    icon: '🌍',
    color: 'bg-indigo-500',
    subtopics: [
      // P8.1 Physics on the Move
      'Typical speeds for everyday activities',
      'Walking: ~1.5 m/s, Running: ~3 m/s',
      'Cycling: ~6 m/s, Cars: ~13-30 m/s',
      'Sound in air: ~330 m/s',
      'Estimating accelerations',
      'Reaction time: definition and factors',
      'Typical reaction times: 0.2-0.9 s',
      'Measuring reaction time',
      'Thinking distance',
      'Braking distance',
      'Stopping distance = thinking + braking',
      'Factors affecting thinking distance',
      'Factors affecting braking distance',
      'Speed and braking distance relationship',
      'Estimating forces in collisions (HT)',
      'Vehicle safety features',
      'Crumple zones and energy absorption',
      'Seat belts and airbags',
      // P8.2 Powering Earth
      'Energy resources: renewable vs non-renewable',
      'Fossil fuels: coal, oil, natural gas',
      'Nuclear fuel',
      'Renewable: solar, wind, water, geothermal',
      'Biofuels and biomass',
      'Comparing energy resources',
      'Environmental impacts',
      'Reliability and supply issues',
      'The National Grid',
      'Power stations to consumers',
      'Step-up transformers and transmission',
      'Reducing power losses in cables',
      'Step-down transformers for distribution',
      'UK mains supply: 230V, 50Hz',
      'AC vs DC supply',
      'Live, neutral and earth wires',
      'Colour coding of wires',
      // P8.3 Beyond Earth
      'The Solar System composition',
      'Planets, dwarf planets, moons',
      'Asteroids, comets, meteors',
      'The Sun as our star',
      'Light years and astronomical distances',
      'Natural and artificial satellites',
      'Satellite orbits: circular and elliptical',
      'Geostationary orbits',
      'Polar orbits',
      'Orbital radius and speed (HT)',
      'Gravity and orbital motion (HT)',
      'Red-shift: evidence for expansion',
      'Doppler effect and galaxy motion',
      'Big Bang theory',
      'Cosmic microwave background radiation',
      'Life cycle of stars',
      'Main sequence stars',
      'Red giants and supergiants',
      'White dwarfs, neutron stars, black holes',
      'Fusion in stars: hydrogen to helium',
      'Heavy element formation in supernovae',
      'Black body radiation (HT)',
      'Temperature and peak wavelength (HT)',
      'Seismic waves: P and S waves (HT)',
      'Earth structure from seismic data (HT)',
    ],
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'physics',
    paperRestriction: 'Paper 2',
  },
];

// Helper function to get a topic by ID
export function getOCRPhysicsTopicById(id: string): Topic | undefined {
  return ocrPhysicsTopics.find(topic => topic.id === id);
}

// Helper function to get topics by paper
export function getOCRPhysicsTopicsByPaper(paper: 1 | 2): Topic[] {
  return ocrPhysicsTopics.filter(topic => topic.paperRestriction === `Paper ${paper}`);
}

// Helper function to count all subtopics
export function countOCRPhysicsSubtopics(): number {
  return ocrPhysicsTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
