// OCR GCSE Chemistry Gateway (J248) Topics
// Complete specification coverage
// Paper 1: Topics C1-C3 (Particles to Chemical reactions)
// Paper 2: Topics C4-C6 (Predicting reactions to Global challenges)

import { Topic } from '@/types';

export const ocrChemistryTopics: Topic[] = [
  // ==========================================
  // PAPER 1 TOPICS
  // ==========================================

  // Topic C1: Particles
  {
    id: 'particles',
    name: 'Particles',
    description: 'Atomic structure, the periodic table, and bonding',
    icon: '⚛️',
    color: 'bg-blue-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C1.1 The particle model
      'The particle model',
      'Solids, liquids and gases',
      'Arrangement of particles',
      'Movement of particles',
      'Energy of particles',
      'Changes of state',
      'Melting and freezing',
      'Boiling and condensing',
      'Sublimation',
      'Heating and cooling curves',
      'State symbols',
      'Limitations of the particle model',
      // C1.2 Atomic structure
      'Atoms and elements',
      'Structure of an atom',
      'Protons, neutrons and electrons',
      'Atomic number',
      'Mass number',
      'Calculating numbers of subatomic particles',
      'Electron configuration',
      'Electron shells',
      'Drawing electron configurations',
      'Isotopes',
      'Relative atomic mass',
      'Calculating relative atomic mass',
      // C1.3 The periodic table
      'Development of the periodic table',
      'Mendeleev\'s periodic table',
      'The modern periodic table',
      'Periods and groups',
      'Metals and non-metals',
      'Electronic structure and position',
      'Predicting properties from position',
      // C1.4 Bonding
      'Ionic bonding',
      'Formation of ions',
      'Electron transfer',
      'Dot and cross diagrams for ionic compounds',
      'Properties of ionic compounds',
      'Giant ionic lattices',
      'Covalent bonding',
      'Sharing electrons',
      'Single covalent bonds',
      'Double covalent bonds',
      'Dot and cross diagrams for molecules',
      'Properties of simple molecules',
      'Weak intermolecular forces',
      'Giant covalent structures',
      'Diamond',
      'Graphite',
      'Silicon dioxide',
      'Comparing diamond and graphite',
      'Metallic bonding',
      'Structure of metals',
      'Delocalised electrons',
      'Properties of metals',
      'Alloys',
      'Polymers',
      'Fullerenes',
      'Graphene',
      'Carbon nanotubes',
    ],
  },

  // Topic C2: Elements, Compounds and Mixtures
  {
    id: 'elements-compounds',
    name: 'Elements, Compounds and Mixtures',
    description: 'Purity, separation techniques, and groups of the periodic table',
    icon: '🧪',
    color: 'bg-purple-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C2.1 Purity and separating mixtures
      'Pure substances',
      'Melting point of pure substances',
      'Boiling point of pure substances',
      'Mixtures',
      'Formulations',
      'Examples of formulations',
      'Filtration',
      'Evaporation',
      'Crystallisation',
      'Simple distillation',
      'Fractional distillation',
      'Paper chromatography',
      'Rf values',
      'Calculating Rf values',
      'Interpreting chromatograms',
      // C2.2 Bonding and properties
      'Relating structure to properties',
      'Ionic compound properties',
      'Simple molecular properties',
      'Giant covalent properties',
      'Metallic properties',
      'Nanoparticles',
      'Size of nanoparticles',
      'Surface area to volume ratio',
      'Properties of nanoparticles',
      'Uses of nanoparticles',
      'Risks of nanoparticles',
      // C2.3 Group 1 - Alkali metals
      'Group 1 - The alkali metals',
      'Properties of alkali metals',
      'Reactions with water',
      'Reactions with oxygen',
      'Reactions with chlorine',
      'Trends in Group 1',
      'Explaining reactivity trends',
      // C2.4 Group 7 - Halogens
      'Group 7 - The halogens',
      'Physical properties of halogens',
      'Colours and states of halogens',
      'Reactions of halogens',
      'Halide compounds',
      'Displacement reactions',
      'Trends in Group 7',
      'Explaining reactivity trends',
      // C2.5 Group 0 - Noble gases
      'Group 0 - The noble gases',
      'Properties of noble gases',
      'Electronic configuration',
      'Unreactivity of noble gases',
      'Uses of noble gases',
      'Trends in boiling points',
      // C2.6 Transition metals
      'Transition metals',
      'Position in periodic table',
      'Properties of transition metals',
      'Coloured compounds',
      'Catalytic properties',
      'Uses of transition metals',
    ],
  },

  // Topic C3: Chemical Reactions
  {
    id: 'reactions',
    name: 'Chemical Reactions',
    description: 'Equations, acids and bases, electrolysis, and energy changes',
    icon: '⚗️',
    color: 'bg-green-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C3.1 Equations and calculations
      'Word equations',
      'Balanced symbol equations',
      'Conservation of mass',
      'Relative formula mass (Mr)',
      'Calculating relative formula mass',
      'The mole',
      'Avogadro constant',
      'Moles calculations',
      'Mass from moles',
      'Moles from mass',
      'Reacting mass calculations',
      'Limiting reactants',
      'Concentration of solutions',
      'Concentration in g/dm³',
      'Concentration in mol/dm³ (HT)',
      'Volume of gases',
      'Molar volume at RTP (HT)',
      'Percentage yield',
      'Calculating percentage yield',
      'Atom economy',
      'Calculating atom economy',
      // C3.2 Acids and bases
      'Acids and alkalis',
      'The pH scale',
      'Indicators',
      'Universal indicator',
      'Neutralisation',
      'Reactions of acids with metals',
      'Reactions of acids with metal oxides',
      'Reactions of acids with metal hydroxides',
      'Reactions of acids with metal carbonates',
      'Making salts',
      'Soluble salts',
      'Insoluble salts',
      'Strong acids (HT)',
      'Weak acids (HT)',
      'Hydrogen ion concentration (HT)',
      // C3.3 Electrolysis
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Anode and cathode',
      'Electrolysis of molten compounds',
      'Products at electrodes',
      'Electrolysis of aqueous solutions',
      'Electrolysis of sodium chloride solution',
      'Half equations (HT)',
      'Extraction of aluminium',
      'Purification of copper',
      // C3.4 Energy changes
      'Exothermic reactions',
      'Endothermic reactions',
      'Examples of exothermic reactions',
      'Examples of endothermic reactions',
      'Temperature changes',
      'Practical: measuring temperature changes',
      'Reaction profiles',
      'Activation energy',
      'Catalysts and activation energy',
      'Bond energies (HT)',
      'Breaking bonds (HT)',
      'Making bonds (HT)',
      'Calculating energy changes (HT)',
    ],
  },

  // ==========================================
  // PAPER 2 TOPICS
  // ==========================================

  // Topic C4: Predicting and Identifying Reactions and Products
  {
    id: 'predicting',
    name: 'Predicting and Identifying Reactions and Products',
    description: 'Reactivity series, extracting metals, and chemical tests',
    icon: '🔍',
    color: 'bg-orange-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C4.1 Reactivity and oxidation-reduction
      'Reactivity series',
      'Reactions of metals with water',
      'Reactions of metals with acids',
      'Displacement reactions',
      'Oxidation',
      'Reduction',
      'Redox reactions',
      'Oxidation as loss of electrons (HT)',
      'Reduction as gain of electrons (HT)',
      'Ionic half equations (HT)',
      // C4.2 Extracting metals
      'Metal ores',
      'Extraction and reactivity',
      'Reduction with carbon',
      'Extraction of iron',
      'Extraction of aluminium',
      'Biological extraction',
      'Phytomining',
      'Bioleaching',
      'Recycling metals',
      // C4.3 Identifying ions
      'Flame tests',
      'Flame test colours',
      'Lithium - red',
      'Sodium - yellow',
      'Potassium - lilac',
      'Calcium - orange-red',
      'Copper - green',
      'Testing with sodium hydroxide',
      'Metal hydroxide precipitates',
      'Copper(II) - blue precipitate',
      'Iron(II) - green precipitate',
      'Iron(III) - brown precipitate',
      'Testing for carbonates',
      'Testing for halides',
      'Silver nitrate test',
      'Testing for sulfates',
      'Barium chloride test',
      'Test for hydrogen',
      'Test for oxygen',
      'Test for carbon dioxide',
      'Test for chlorine',
      'Instrumental methods (HT)',
    ],
  },

  // Topic C5: Monitoring and Controlling Chemical Reactions
  {
    id: 'monitoring',
    name: 'Monitoring and Controlling Chemical Reactions',
    description: 'Rates of reaction, equilibria, and industrial processes',
    icon: '⏱️',
    color: 'bg-yellow-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C5.1 Rate of reaction
      'Rate of reaction',
      'Measuring rate of reaction',
      'Calculating rate',
      'Rate from graphs',
      'Factors affecting rate',
      'Effect of concentration',
      'Effect of temperature',
      'Effect of surface area',
      'Effect of catalysts',
      'Effect of pressure (gases)',
      // C5.2 Collision theory
      'Collision theory',
      'Successful collisions',
      'Activation energy',
      'Explaining concentration effect',
      'Explaining temperature effect',
      'Explaining surface area effect',
      'Explaining catalyst effect',
      // C5.3 Catalysts
      'Catalysts',
      'How catalysts work',
      'Catalysts and activation energy',
      'Enzymes',
      'Biological catalysts',
      'Properties of enzymes',
      'Industrial catalysts',
      // C5.4 Reversible reactions
      'Reversible reactions',
      'The ⇌ symbol',
      'Examples of reversible reactions',
      'Energy changes in reversible reactions',
      'Dynamic equilibrium (HT)',
      'Closed systems (HT)',
      'Le Chatelier\'s principle (HT)',
      'Effect of temperature on equilibrium (HT)',
      'Effect of pressure on equilibrium (HT)',
      'Effect of concentration on equilibrium (HT)',
      // C5.5 The Haber process
      'The Haber process',
      'Raw materials for Haber process',
      'Conditions for Haber process',
      'Compromise conditions',
      'Effect of temperature',
      'Effect of pressure',
      'Role of catalyst',
      'NPK fertilisers',
    ],
  },

  // Topic C6: Global Challenges
  {
    id: 'global',
    name: 'Global Challenges',
    description: 'Organic chemistry, atmosphere, resources, and sustainability',
    icon: '🌍',
    color: 'bg-teal-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // C6.1 Organic chemistry
      'Hydrocarbons',
      'Crude oil',
      'Finite resources',
      'Fractional distillation',
      'Fractions from crude oil',
      'Uses of fractions',
      'Alkanes',
      'General formula of alkanes',
      'Names and formulae of alkanes',
      'Displayed formulae',
      'Properties of hydrocarbons',
      'Boiling point trends',
      'Viscosity trends',
      'Flammability trends',
      'Complete combustion',
      'Incomplete combustion',
      'Carbon monoxide',
      'Particulates',
      'Cracking',
      'Thermal cracking',
      'Catalytic cracking',
      'Products of cracking',
      'Alkenes',
      'General formula of alkenes',
      'The C=C double bond',
      'Test for alkenes',
      'Addition reactions',
      'Addition polymerisation',
      'Poly(ethene)',
      'Poly(propene)',
      'Drawing polymers',
      'Alcohols',
      'Functional group of alcohols',
      'Properties of alcohols',
      'Uses of alcohols',
      'Carboxylic acids',
      'Functional group of carboxylic acids',
      'Properties of carboxylic acids',
      'Esters',
      'Formation of esters',
      'Uses of esters',
      // C6.2 Earth and atmospheric science
      'Evolution of the atmosphere',
      'Early atmosphere',
      'Volcanic activity',
      'Development of atmosphere',
      'Photosynthesis',
      'Formation of fossil fuels',
      'Formation of sedimentary rocks',
      'Composition today',
      'Greenhouse gases',
      'Carbon dioxide',
      'Methane',
      'Water vapour',
      'The greenhouse effect',
      'Global warming',
      'Climate change',
      'Evidence for climate change',
      'Effects of climate change',
      'Carbon footprint',
      'Reducing carbon emissions',
      // C6.3 Pollution
      'Atmospheric pollutants',
      'Sulfur dioxide',
      'Nitrogen oxides',
      'Particulates',
      'Carbon monoxide',
      'Acid rain',
      'Effects of acid rain',
      'Global dimming',
      // C6.4 Using resources
      'Natural resources',
      'Synthetic materials',
      'Sustainable development',
      'Finite resources',
      'Renewable resources',
      'Potable water',
      'Water treatment',
      'Sedimentation',
      'Filtration',
      'Chlorination',
      'Desalination',
      'Distillation',
      'Reverse osmosis',
      'Sewage treatment',
      'Life cycle assessment',
      'Stages of LCA',
      'Comparing LCAs',
      'Reduce, reuse, recycle',
      'Recycling metals',
      'Recycling polymers',
    ],
  },
];

export function getOCRChemistryTopicById(id: string): Topic | undefined {
  return ocrChemistryTopics.find(topic => topic.id === id);
}
