// Edexcel A-Level Geography (9GE0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-a-levels/geography-2016.html

import { Topic } from '@/types';

export const edexcelALevelGeographyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: PHYSICAL GEOGRAPHY
  // ============================================================================
  {
    id: 'edexcel-alevel-geog-tectonic',
    name: 'Tectonic Processes and Hazards',
    description: 'Plate tectonics, volcanic and seismic hazards',
    icon: '🌋',
    color: 'bg-red-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Plate tectonics theory
      'Earth structure',
      'Continental and oceanic crust',
      'Lithosphere and asthenosphere',
      'Plate tectonic theory development',
      'Evidence: continental fit',
      'Evidence: geological sequences',
      'Evidence: fossil records',
      'Evidence: paleomagnetism',
      'Sea floor spreading',
      'Convection currents',
      'Slab pull and ridge push',
      // Plate boundaries
      'Divergent/constructive boundaries',
      'Mid-ocean ridges',
      'Rift valleys',
      'Convergent/destructive boundaries',
      'Oceanic-continental collision',
      'Oceanic-oceanic collision',
      'Continental-continental collision',
      'Conservative/transform boundaries',
      'Hot spots and mantle plumes',
      // Volcanic hazards
      'Causes of volcanic eruptions',
      'Types of volcanic eruption',
      'Effusive vs explosive eruptions',
      'Volcanic landforms',
      'Shield volcanoes',
      'Stratovolcanoes',
      'Calderas',
      'Primary hazards: lava flows',
      'Primary hazards: pyroclastic flows',
      'Primary hazards: tephra/ash',
      'Secondary hazards: lahars',
      'Secondary hazards: tsunamis',
      'Volcanic gases',
      'Supervolcanoes',
      // Seismic hazards
      'Causes of earthquakes',
      'Shallow vs deep focus',
      'Seismic waves',
      'Earthquake measurement',
      'Primary hazards: ground shaking',
      'Secondary hazards: liquefaction',
      'Secondary hazards: landslides',
      'Secondary hazards: tsunamis',
      // Hazard profiles
      'Magnitude and intensity',
      'Speed of onset',
      'Duration',
      'Areal extent',
      'Spatial predictability',
      'Frequency',
      // Governance and management
      'Hazard perception',
      'Risk management strategies',
      'Prediction and forecasting',
      'Mitigation and adaptation',
      'Community preparedness',
      'Building design',
      'Land use planning',
      'Emergency response',
      // Case studies
      'Contrasting volcanic events',
      'Contrasting seismic events',
    ],
  },
  {
    id: 'edexcel-alevel-geog-coastal',
    name: 'Coastal Landscapes and Change',
    description: 'Coastal systems, processes and management',
    icon: '🌊',
    color: 'bg-cyan-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Coastal systems
      'Littoral zone',
      'Coastal system components',
      'Energy inputs',
      'Sediment sources',
      'Sediment budget',
      'Sediment cells',
      'Dynamic equilibrium',
      // Marine processes
      'Wave formation',
      'Wave characteristics',
      'Constructive waves',
      'Destructive waves',
      'Wave refraction',
      'Tides: spring and neap',
      'Tidal range',
      'Storm surges',
      'Currents: longshore drift',
      'Rip currents',
      // Weathering and erosion
      'Marine erosion: hydraulic action',
      'Marine erosion: abrasion',
      'Marine erosion: attrition',
      'Marine erosion: corrosion',
      'Sub-aerial processes',
      'Chemical weathering',
      'Mechanical weathering',
      'Biological weathering',
      'Mass movement',
      'Cliff retreat rates',
      // Erosional landforms
      'Cliffs',
      'Wave-cut platforms',
      'Caves, arches, stacks, stumps',
      'Headlands and bays',
      // Depositional landforms
      'Beaches',
      'Beach profiles',
      'Berms and cusps',
      'Spits',
      'Bars',
      'Tombolos',
      'Barrier islands',
      'Sand dunes',
      'Salt marshes',
      // Sea level change
      'Eustatic change',
      'Isostatic change',
      'Submergent coastlines',
      'Emergent coastlines',
      'Rias and fjords',
      'Raised beaches',
      // Coastal management
      'Hard engineering',
      'Sea walls',
      'Groynes',
      'Revetments',
      'Rock armour',
      'Soft engineering',
      'Beach nourishment',
      'Dune stabilisation',
      'Managed retreat',
      'Shoreline Management Plans',
      'ICZM',
      'Sustainability',
    ],
  },
  {
    id: 'edexcel-alevel-geog-glaciated',
    name: 'Glaciated Landscapes and Change',
    description: 'Glacial processes, landforms and environments',
    icon: '❄️',
    color: 'bg-blue-200',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1 (Option)',
    subtopics: [
      // Glacial systems
      'Glacial system concept',
      'Glacier mass balance',
      'Accumulation',
      'Ablation',
      'Equilibrium line',
      'Glacier advance and retreat',
      // Ice formation
      'Snow accumulation',
      'Firn formation',
      'Glacial ice',
      'Types of glacier',
      'Ice sheets',
      'Ice caps',
      'Valley glaciers',
      'Cirque glaciers',
      // Glacier movement
      'Internal deformation',
      'Basal sliding',
      'Rotational movement',
      'Warm-based glaciers',
      'Cold-based glaciers',
      'Glacier velocity',
      // Glacial erosion
      'Plucking/quarrying',
      'Abrasion',
      'Freeze-thaw weathering',
      'Erosion rates',
      // Erosional landforms
      'Corries/cirques',
      'Aretes',
      'Pyramidal peaks',
      'U-shaped valleys',
      'Hanging valleys',
      'Truncated spurs',
      'Ribbon lakes',
      'Roches moutonnees',
      'Striations',
      // Glacial deposition
      'Till/boulder clay',
      'Moraines',
      'Lateral moraines',
      'Medial moraines',
      'Terminal moraines',
      'Ground moraine',
      'Drumlins',
      'Erratics',
      // Fluvioglacial processes
      'Meltwater',
      'Fluvioglacial erosion',
      'Fluvioglacial deposition',
      'Eskers',
      'Kames',
      'Outwash plains',
      'Kettles',
      'Varves',
      // Periglacial environments
      'Permafrost',
      'Active layer',
      'Periglacial processes',
      'Ice wedges',
      'Patterned ground',
      'Pingos',
      'Solifluction',
      // Human interactions
      'Settlement in glaciated areas',
      'Tourism impacts',
      'Climate change effects',
      'Management strategies',
    ],
  },
  {
    id: 'edexcel-alevel-geog-water-cycle',
    name: 'The Water Cycle and Water Insecurity',
    description: 'Global water cycle and water security issues',
    icon: '💧',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Water cycle
      'Global water cycle',
      'Major water stores',
      'Oceans',
      'Ice and glaciers',
      'Groundwater',
      'Atmosphere',
      'Biosphere',
      // Processes and transfers
      'Evaporation',
      'Transpiration',
      'Evapotranspiration',
      'Condensation',
      'Precipitation',
      'Interception',
      'Infiltration',
      'Percolation',
      'Throughflow',
      'Groundwater flow',
      'Surface runoff',
      // Drainage basins
      'Drainage basin system',
      'Inputs and outputs',
      'Stores and transfers',
      'Water balance',
      'Storm hydrographs',
      'Factors affecting hydrographs',
      // Water and climate
      'Cryospheric changes',
      'Sea ice melting',
      'Glacier retreat',
      'Permafrost thaw',
      'Climate change impacts',
      'Feedback mechanisms',
      // Water insecurity
      'Water availability',
      'Physical water scarcity',
      'Economic water scarcity',
      'Water stress',
      'Water demand',
      'Agricultural demand',
      'Industrial demand',
      'Domestic demand',
      // Water conflicts
      'Transboundary water issues',
      'Water geopolitics',
      'Shared river basins',
      // Management strategies
      'Large-scale schemes',
      'Dams and reservoirs',
      'Water transfer',
      'Desalination',
      'Local schemes',
      'Rainwater harvesting',
      'Water conservation',
      'Sustainable water management',
    ],
  },
  {
    id: 'edexcel-alevel-geog-carbon-cycle',
    name: 'The Carbon Cycle and Energy Security',
    description: 'Global carbon cycle and energy security',
    icon: '🔋',
    color: 'bg-gray-700',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Carbon cycle
      'Global carbon cycle',
      'Carbon stores',
      'Atmosphere',
      'Oceans',
      'Terrestrial biosphere',
      'Lithosphere',
      // Carbon transfers
      'Photosynthesis',
      'Respiration',
      'Decomposition',
      'Combustion',
      'Weathering',
      'Ocean-atmosphere exchange',
      // Carbon and climate
      'Greenhouse effect',
      'Carbon dioxide levels',
      'Methane',
      'Carbon feedbacks',
      'Carbon sinks',
      'Rainforest carbon storage',
      'Ocean carbon storage',
      // Human impacts
      'Fossil fuel combustion',
      'Deforestation',
      'Land use change',
      'Carbon emissions',
      'Enhanced greenhouse effect',
      // Energy security
      'Energy mix',
      'Global energy consumption',
      'Energy demand factors',
      'Economic development',
      'Population growth',
      // Fossil fuels
      'Oil',
      'Natural gas',
      'Coal',
      'Unconventional fossil fuels',
      'Shale gas and fracking',
      'Tar sands',
      'Peak oil',
      // Renewable energy
      'Solar power',
      'Wind power',
      'Hydroelectric power',
      'Geothermal',
      'Tidal energy',
      'Biofuels',
      'Nuclear energy',
      // Energy geopolitics
      'OPEC',
      'Energy pathways',
      'Energy interdependence',
      'Energy conflicts',
      // Energy futures
      'Energy transition',
      'Decarbonisation',
      'Carbon capture',
      'Sustainable energy',
      'Net zero targets',
    ],
  },
  // ============================================================================
  // PAPER 2: HUMAN GEOGRAPHY
  // ============================================================================
  {
    id: 'edexcel-alevel-geog-globalisation',
    name: 'Globalisation',
    description: 'Causes, consequences and management of globalisation',
    icon: '🌍',
    color: 'bg-indigo-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Globalisation concept
      'Definition of globalisation',
      'Dimensions of globalisation',
      'KOF Globalisation Index',
      'History of globalisation',
      // Drivers of globalisation
      'Transport developments',
      'Containerisation',
      'Communication technology',
      'Internet and social media',
      'Financial deregulation',
      'Trade liberalisation',
      'Political factors',
      // Global organisations
      'World Trade Organisation',
      'International Monetary Fund',
      'World Bank',
      'Regional trading blocs',
      'EU, NAFTA, ASEAN',
      // TNCs
      'Characteristics of TNCs',
      'Global production networks',
      'Outsourcing and offshoring',
      'FDI patterns',
      'TNC decision-making',
      'TNC impacts',
      // Global shift
      'Deindustrialisation',
      'NICs and emerging economies',
      "China's economic growth",
      "India's economic growth",
      'Consequences of global shift',
      // Globalisation impacts
      'Economic impacts',
      'Social impacts',
      'Cultural impacts',
      'Environmental impacts',
      'Winners and losers',
      'Inequality',
      // Migration and globalisation
      'Global migration patterns',
      'Economic migration',
      'Elite migration',
      'Diaspora',
      'Remittances',
      // Tensions
      'Nationalism vs globalisation',
      'Protectionism',
      'Anti-globalisation movements',
      'Ethical consumption',
      'Fair trade',
    ],
  },
  {
    id: 'edexcel-alevel-geog-superpowers',
    name: 'Superpowers',
    description: 'Changing global power, geopolitics and influence',
    icon: '🏛️',
    color: 'bg-slate-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Superpower concept
      'Definition of superpower',
      'Types of power',
      'Hard power',
      'Soft power',
      'Smart power',
      // Characteristics of superpowers
      'Economic power',
      'GDP and trade',
      'Military power',
      'Political power',
      'Cultural influence',
      'Demographic power',
      // Historical superpowers
      'British Empire',
      'Colonial legacy',
      'Post-1945 order',
      'Cold War bipolarity',
      'USA dominance',
      'Soviet Union',
      // Contemporary patterns
      'Unipolar world',
      'Multipolar world',
      'USA superpower status',
      'US military presence',
      'US cultural influence',
      // Emerging powers
      'BRICS',
      'China rising',
      "China's Belt and Road",
      'India emerging',
      'Russia resurgence',
      // Geopolitical tensions
      'Spheres of influence',
      'Pivot regions',
      'Resource conflicts',
      'Territorial disputes',
      'South China Sea',
      'Arctic geopolitics',
      // International organisations
      'United Nations',
      'UN Security Council',
      'NATO',
      'G7/G20',
      'Effectiveness of institutions',
      // Future scenarios
      'Power shift to Asia',
      'US decline?',
      'New Cold War?',
      'Multipolar future',
    ],
  },
  {
    id: 'edexcel-alevel-geog-regenerating-places',
    name: 'Regenerating Places',
    description: 'Place meanings, economic change and regeneration',
    icon: '🏗️',
    color: 'bg-orange-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Place concepts
      'Place definition',
      'Place characteristics',
      'Place identity',
      'Sense of place',
      'Insider and outsider perspectives',
      // Place characteristics
      'Demographic characteristics',
      'Cultural characteristics',
      'Economic characteristics',
      'Social characteristics',
      'Built environment',
      // Economy and change
      'Economic sectors',
      'Deindustrialisation',
      'Post-industrial economy',
      'Service sector growth',
      'Creative industries',
      // Inequality
      'Spatial inequality',
      'Measures of deprivation',
      'Index of Multiple Deprivation',
      'Rural-urban inequality',
      'Regional inequality',
      'North-South divide',
      // Place perceptions
      'Lived experience',
      'Media representations',
      'Place images',
      'Place marketing',
      // Connections
      'Past and present connections',
      'Local to global connections',
      'Migration impacts',
      'Investment flows',
      // Regeneration
      'Why regenerate?',
      'Regeneration strategies',
      'Government policies',
      'Infrastructure investment',
      'Rebranding',
      'Reimaging',
      // Regeneration players
      'National government',
      'Local government',
      'Private sector',
      'Local communities',
      'NGOs',
      // Regeneration assessment
      'Measuring success',
      'Economic measures',
      'Social measures',
      'Environmental measures',
      'Urban regeneration case study',
      'Rural regeneration case study',
    ],
  },
  {
    id: 'edexcel-alevel-geog-diverse-places',
    name: 'Diverse Places',
    description: 'Population change, diversity and place character',
    icon: '🏘️',
    color: 'bg-teal-500',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 2 (Option)',
    subtopics: [
      // Population change
      'Population structure',
      'Natural change',
      'Migration',
      'Rural-urban migration',
      'International migration',
      // Diversity
      'Ethnic diversity',
      'Cultural diversity',
      'Religious diversity',
      'Age diversity',
      'Economic diversity',
      // Migration patterns
      'Historical migration',
      'Commonwealth migration',
      'EU migration',
      'Asylum seekers',
      'Refugees',
      // Impacts of migration
      'Economic impacts',
      'Social impacts',
      'Cultural impacts',
      'Demographic impacts',
      'Host community views',
      // Place character
      'Factors shaping character',
      'Natural factors',
      'Human factors',
      'Historical factors',
      'Globalisation effects',
      // Rural places
      'Rural characteristics',
      'Accessible rural',
      'Remote rural',
      'Rural decline',
      'Counter-urbanisation',
      // Urban places
      'Urban characteristics',
      'Inner city',
      'Suburbs',
      'Urban fringe',
      'Gentrification',
      // Segregation
      'Causes of segregation',
      'Types of segregation',
      'Consequences of segregation',
      'Social cohesion',
      // Conflict and engagement
      'Community tension',
      'Conflict resolution',
      'Community engagement',
      'Participation',
    ],
  },
  // ============================================================================
  // PAPER 3: SYNOPTIC INVESTIGATION
  // ============================================================================
  {
    id: 'edexcel-alevel-geog-synoptic',
    name: 'Synoptic Geography',
    description: 'Integrating knowledge across physical and human geography',
    icon: '🔗',
    color: 'bg-purple-600',
    examBoard: 'edexcel',
    qualification: 'a-level',
    subject: 'geography',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Synoptic themes
      'Players',
      'Stakeholders and decision-makers',
      'Government role',
      'Business role',
      'Community role',
      'NGO role',
      'Attitudes and actions',
      'Different perspectives',
      'Value systems',
      'Decision-making',
      'Futures and uncertainties',
      'Possible futures',
      'Probable futures',
      'Preferable futures',
      // Connections
      'Physical-human connections',
      'Scale interactions',
      'Local to global',
      'Past-present-future',
      'Cause and effect',
      // Analysis skills
      'Resource analysis',
      'Data interpretation',
      'Evaluating evidence',
      'Forming judgements',
      'Constructing arguments',
      // Geographical issues
      'Contemporary issues',
      'Contested spaces',
      'Sustainability challenges',
      'Development dilemmas',
      'Environmental management',
    ],
  },
];

export function getEdexcelALevelGeographyTopicById(id: string): Topic | undefined {
  return edexcelALevelGeographyTopics.find((topic) => topic.id === id);
}
