// Edexcel GCSE History (1HI0) Topics
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/history-2016.html

import { Topic } from '@/types';

export const edexcelGCSEHistoryTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: THEMATIC STUDY AND HISTORIC ENVIRONMENT
  // ============================================================================
  {
    id: 'crime-punishment',
    name: 'Crime and Punishment in Britain c1000-present',
    description: 'Changes in crime, punishment and law enforcement',
    icon: '⚖️',
    color: 'bg-gray-700',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Medieval c1000-c1500
      'Nature of crimes medieval',
      'Crimes against the person',
      'Crimes against property',
      'Crimes against authority',
      'Heresy and treason',
      'Law enforcement medieval',
      'Tithings and hue and cry',
      'Manor courts',
      'Royal courts',
      'Trial by ordeal',
      'Trial by jury',
      'Punishments medieval',
      'Fines and stocks',
      'Corporal punishment',
      'Capital punishment',
      // Early Modern c1500-c1700
      'New crimes 16th-17th century',
      'Vagabondage',
      'Witchcraft',
      'Heresy under Tudors',
      'Treason and religious change',
      'Law enforcement early modern',
      'JPs and parish constables',
      'Watchmen',
      'Punishments early modern',
      'Bloody Code beginnings',
      'Transportation',
      'Public executions',
      // Case studies
      'Gunpowder Plotters 1605',
      'Matthew Hopkins witch-hunts',
      // Industrial c1700-c1900
      'Changing crimes 18th-19th century',
      'Poaching',
      'Smuggling',
      'Highway robbery',
      'Crimes in industrial towns',
      'Law enforcement changes',
      'Bow Street Runners',
      'Metropolitan Police 1829',
      'Robert Peel',
      'Detective department',
      'Prison reform',
      'John Howard',
      'Elizabeth Fry',
      'Separate and silent systems',
      'End of public execution',
      'Transportation to Australia',
      // Modern c1900-present
      'New crimes 20th century',
      'Hate crimes',
      'Computer crime',
      'Terrorism',
      'Drug crimes',
      'Modern policing',
      'Technology in policing',
      'Community policing',
      'Modern punishments',
      'Abolition of death penalty',
      'Open and closed prisons',
      'Alternatives to prison',
      // Historic Environment
      'Whitechapel c1870-c1900',
      'Living conditions',
      'Immigration',
      'Policing Whitechapel',
      'Jack the Ripper',
      'H Division',
    ],
  },
  {
    id: 'medicine',
    name: 'Medicine in Britain c1250-present',
    description: 'Development of medicine and treatment',
    icon: '💊',
    color: 'bg-pink-600',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Medieval c1250-c1500
      'Ideas about disease medieval',
      'Four Humours',
      'Miasma',
      'God and religion',
      'Astrology',
      'Treatments medieval',
      'Bloodletting and purging',
      'Herbal remedies',
      'Prayer and pilgrimage',
      'Hospitals medieval',
      'Role of the Church',
      'Training of physicians',
      'Surgery medieval',
      'The Black Death',
      'Causes and responses',
      // Renaissance c1500-c1700
      'Continuity in ideas',
      'New approaches',
      'Vesalius anatomy',
      'Harvey circulation',
      'Pare surgery',
      'Thomas Sydenham',
      'Great Plague 1665',
      // 18th-19th century
      'Germ theory',
      'Pasteur',
      'Koch',
      'Jenner vaccination',
      'Opposition to vaccination',
      'Anaesthetics',
      'Chloroform',
      'Antiseptics',
      'Lister carbolic',
      'Aseptic surgery',
      'Florence Nightingale',
      'Nursing reforms',
      // 20th-21st century
      'Understanding genetics',
      'DNA',
      'Magic bullets',
      'Antibiotics',
      'Penicillin discovery',
      'Fleming Florey Chain',
      'Modern surgery',
      'Transplants',
      'Keyhole surgery',
      'Modern treatments',
      'Cancer treatment',
      'Government role',
      'NHS 1948',
      // Historic Environment
      'Western Front 1914-18',
      'Trench conditions',
      'Wounds and injuries',
      'Medical developments',
      'Blood transfusions',
      'Brain surgery',
      'Plastic surgery',
      'RAMC and FANY',
      'Casualty evacuation',
    ],
  },
  {
    id: 'warfare',
    name: 'Warfare and British Society c1250-present',
    description: 'Changes in warfare through British history',
    icon: '⚔️',
    color: 'bg-red-700',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Medieval c1250-c1500
      'Medieval warfare',
      'Feudal armies',
      'Knights and infantry',
      'Castles and sieges',
      'Longbow revolution',
      'Battles: Falkirk Crécy',
      // Early Modern c1500-c1700
      'Gunpowder revolution',
      'Muskets and pikes',
      'New Model Army',
      'English Civil War tactics',
      'Naval warfare',
      'Defeat of Armada',
      // 18th-19th century
      'Professional armies',
      'Redcoats',
      'Napoleonic warfare',
      'Battle of Waterloo',
      'Industrial revolution impact',
      'Crimean War',
      'Colonial warfare',
      // World War One
      'Trench warfare',
      'New technology WWI',
      'Machine guns',
      'Artillery',
      'Gas warfare',
      'Tanks',
      'Air warfare',
      'Naval warfare WWI',
      // World War Two
      'Blitzkrieg',
      'Air power WWII',
      'Battle of Britain',
      'Strategic bombing',
      'D-Day',
      'Atomic bomb',
      // Modern warfare
      'Cold War nuclear',
      'Limited wars',
      'Falklands War',
      'Gulf Wars',
      'War on Terror',
      'Technology today',
      // Historic Environment
      'London WWII 1939-45',
      'The Blitz',
      'Evacuation',
      'Air raid precautions',
      'Home Guard',
    ],
  },
  // ============================================================================
  // PAPER 2: PERIOD STUDY AND BRITISH DEPTH STUDY
  // Section A: Period Studies
  // ============================================================================
  {
    id: 'superpower-relations',
    name: 'Superpower Relations and the Cold War 1941-91',
    description: 'The Cold War from origins to collapse',
    icon: '❄️',
    color: 'bg-cyan-700',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section A',
    subtopics: [
      // Origins 1941-58
      'Grand Alliance',
      'Tehran Conference',
      'Yalta Conference',
      'Potsdam Conference',
      'Ideological differences',
      'Soviet expansion',
      'Iron Curtain',
      'Truman Doctrine',
      'Marshall Plan',
      'Cominform',
      'Comecon',
      'Berlin Blockade',
      'NATO formation',
      'Warsaw Pact',
      'Arms race',
      'Hungarian Uprising 1956',
      // Crisis 1958-70
      'Berlin Crisis',
      'Berlin Wall 1961',
      'Cuban Revolution',
      'Bay of Pigs',
      'Cuban Missile Crisis',
      'Consequences of Cuba',
      'Czechoslovakia 1968',
      'Prague Spring',
      'Brezhnev Doctrine',
      // End of Cold War 1970-91
      'Detente',
      'SALT 1',
      'Helsinki Accords',
      'SALT 2',
      'Afghanistan invasion',
      'Reagan and Star Wars',
      'Gorbachev reforms',
      'Glasnost perestroika',
      'Fall of Berlin Wall',
      'End of Warsaw Pact',
      'Collapse of USSR',
    ],
  },
  {
    id: 'american-west',
    name: 'The American West c1835-c1895',
    description: 'Settlement and conflict in the American West',
    icon: '🤠',
    color: 'bg-amber-600',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section A',
    subtopics: [
      // Plains Indians
      'Plains Indians way of life',
      'Beliefs and culture',
      'Buffalo importance',
      'Nomadic lifestyle',
      'Family and society',
      // Early settlement
      'Manifest Destiny',
      'Early migrants',
      'Mountain men',
      'Oregon Trail',
      'Donner Party',
      'Mormons',
      'Joseph Smith',
      'Brigham Young',
      'Salt Lake City',
      // Gold Rush
      'California Gold Rush',
      'Mining towns',
      'Law and order problems',
      'Vigilantes',
      // Cattle industry
      'Texas longhorns',
      'Cattle drives',
      'Cowboys',
      'Cow towns',
      'Abilene',
      'Open range',
      'Range wars',
      'End of open range',
      // Homesteaders
      'Homestead Act 1862',
      'Farming the Plains',
      'Problems and solutions',
      'Railroads',
      'Sod houses',
      'Women homesteaders',
      // Conflict
      'Indian wars',
      'Fort Laramie Treaties',
      'Reservations',
      'Sand Creek Massacre',
      'Little Bighorn',
      'Wounded Knee',
      // Law and order
      'Lawlessness',
      'Outlaws',
      'Lawmen',
      'Wyatt Earp',
      'Lincoln County War',
    ],
  },
  // ============================================================================
  // PAPER 2: Section B - British Depth Studies
  // ============================================================================
  {
    id: 'anglo-saxon-norman',
    name: 'Anglo-Saxon and Norman England c1060-88',
    description: 'England before and after the Norman Conquest',
    icon: '🏰',
    color: 'bg-stone-600',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section B',
    subtopics: [
      // Anglo-Saxon England
      'Anglo-Saxon society',
      'King and government',
      'Earls and thegns',
      'Peasants',
      'Towns and villages',
      'The Church',
      'Edward the Confessor',
      // Succession crisis
      'Death of Edward 1066',
      'Claimants',
      'Harold Godwinson',
      'William of Normandy',
      'Harald Hardrada',
      'Edgar Atheling',
      // Battles of 1066
      'Gate Fulford',
      'Stamford Bridge',
      'Harold\'s march south',
      'Battle of Hastings',
      'William\'s tactics',
      // Norman conquest
      'William\'s coronation',
      'Establishing control',
      'Marcher earldoms',
      'Castles',
      'Rebellions 1067-68',
      'Harrying of North',
      'Revolt of Earls 1075',
      // Norman England
      'Feudal system',
      'Landholding',
      'Domesday Book',
      'Norman Church',
      'Lanfranc',
      'William\'s government',
      'Forest laws',
      'Norman culture',
    ],
  },
  {
    id: 'early-elizabethan',
    name: 'Early Elizabethan England 1558-88',
    description: 'The first thirty years of Elizabeth I',
    icon: '👑',
    color: 'bg-amber-700',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 2 Section B',
    subtopics: [
      // Elizabeth\'s situation
      'Elizabeth\'s background',
      'Problems in 1558',
      'Government structure',
      'Court and Council',
      'Parliament',
      // Religious settlement
      'Religious divisions 1558',
      'Settlement of 1559',
      'Act of Supremacy',
      'Act of Uniformity',
      'Church of England',
      // Catholic challenge
      'Catholic threats',
      'Mary Queen of Scots',
      'Northern Rebellion 1569',
      'Papal Bull 1570',
      'Missionary priests',
      'Catholic plots',
      'Ridolfi Plot',
      'Throckmorton Plot',
      'Babington Plot',
      'Execution of Mary',
      // Puritan challenge
      'Puritan beliefs',
      'Vestment controversy',
      'Archbishop Grindal',
      'Prophesyings',
      'Whitgift',
      // Marriage question
      'Importance of marriage',
      'Suitors',
      'Reasons for not marrying',
      // Spanish relations
      'Causes of conflict',
      'Trade and privateering',
      'Drake',
      'Netherlands',
      'Spanish Armada 1588',
      'Defeat of Armada',
      // Society and culture
      'Education',
      'Poverty',
      'Theatre',
      'Exploration',
      'Raleigh and Virginia',
    ],
  },
  // ============================================================================
  // PAPER 3: MODERN DEPTH STUDY
  // ============================================================================
  {
    id: 'weimar-nazi',
    name: 'Weimar and Nazi Germany 1918-39',
    description: 'Germany from defeat to dictatorship',
    icon: '🇩🇪',
    color: 'bg-gray-800',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Weimar Republic
      'German Revolution 1918',
      'Abdication of Kaiser',
      'Weimar Constitution',
      'Proportional representation',
      'Article 48',
      // Early challenges
      'Treaty of Versailles',
      'German reactions',
      'Stab in back myth',
      'Spartacist Rising',
      'Kapp Putsch',
      'Political assassinations',
      'Ruhr invasion 1923',
      'Hyperinflation',
      // Recovery
      'Stresemann',
      'New currency',
      'Dawes Plan',
      'Young Plan',
      'Locarno Treaties',
      'League membership',
      'Cultural changes',
      // Nazi Party
      'Nazi origins',
      'Hitler',
      'Nazi ideology',
      '25 Points',
      'SA',
      'Munich Putsch 1923',
      'Lean years 1924-29',
      'Mein Kampf',
      'Party reorganisation',
      // Rise of Nazis
      'Wall Street Crash impact',
      'Unemployment',
      'Political instability',
      'Bruning',
      'Nazi appeal',
      'Propaganda',
      'Elections 1930-32',
      'Hitler Chancellor 1933',
      // Nazi consolidation
      'Reichstag Fire',
      'Enabling Act',
      'Trade unions banned',
      'Political parties banned',
      'Night of Long Knives',
      'Death of Hindenburg',
      'Fuhrer',
      // Nazi control
      'Police state',
      'SS',
      'Gestapo',
      'Concentration camps',
      'Propaganda ministry',
      'Goebbels',
      'Censorship',
      'Rallies',
      'Olympics 1936',
      // Life in Nazi Germany
      'Nazi economy',
      'Unemployment measures',
      'Rearmament',
      'Workers',
      'DAF',
      'KdF',
      'Women',
      'Young people',
      'Hitler Youth',
      'Education',
      // Persecution
      'Nazi racial policy',
      'Anti-Semitism',
      'Nuremberg Laws',
      'Kristallnacht',
      'Minorities',
      // Opposition
      'Church opposition',
      'Youth opposition',
      'Military opposition',
    ],
  },
  {
    id: 'usa-conflict',
    name: 'The USA 1954-75: Conflict at Home and Abroad',
    description: 'Civil Rights movement and Vietnam War',
    icon: '🇺🇸',
    color: 'bg-blue-700',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Paper 3',
    subtopics: [
      // Civil Rights
      'Segregation in 1950s',
      'Jim Crow laws',
      'Brown v Board 1954',
      'Little Rock 1957',
      'Montgomery Bus Boycott',
      'Rosa Parks',
      'Martin Luther King',
      'SCLC',
      'Sit-ins',
      'Freedom Rides',
      'Albany Movement',
      'Birmingham 1963',
      'March on Washington',
      'Civil Rights Act 1964',
      'Selma 1965',
      'Voting Rights Act',
      // Black Power
      'Malcolm X',
      'Nation of Islam',
      'Black Panthers',
      'Race riots',
      'King assassination',
      // Vietnam
      'French Indochina',
      'US involvement',
      'Domino theory',
      'Gulf of Tonkin',
      'Escalation',
      'US tactics',
      'Search and destroy',
      'Agent Orange',
      'Napalm',
      'Vietcong tactics',
      'Guerrilla warfare',
      'Ho Chi Minh Trail',
      'Tet Offensive',
      'My Lai',
      'Media coverage',
      'Anti-war movement',
      'Kent State',
      'Vietnamisation',
      'Paris Peace Accords',
      'Fall of Saigon',
      'Impact of Vietnam',
    ],
  },
];

export function getEdexcelGCSEHistoryTopicById(id: string): Topic | undefined {
  return edexcelGCSEHistoryTopics.find((topic) => topic.id === id);
}
