// OCR A-Level Computer Science (H446) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/computer-science-h046-h446-from-2015/
// Paper 1: Computer Systems (40%) - H446/01
// Paper 2: Algorithms and Programming (40%) - H446/02
// NEA: Programming Project (20%) - H446/03

import { Topic } from '@/types';

export const ocrALevelComputerScienceTopics: Topic[] = [
  // ============================================================================
  // COMPONENT 1: COMPUTER SYSTEMS
  // ============================================================================

  // 1.1 CHARACTERISTICS OF CONTEMPORARY PROCESSORS, INPUT, OUTPUT AND STORAGE
  {
    id: 'processors-io',
    examBoard: 'ocr',
    name: 'Processors, Input, Output and Storage',
    description: 'CPU architecture, memory types, and storage devices',
    icon: '🔧',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.1.1 Structure and function of processor
      'Arithmetic Logic Unit (ALU)',
      'Control Unit (CU)',
      'Registers',
      'Program Counter (PC)',
      'Accumulator (ACC)',
      'Memory Address Register (MAR)',
      'Memory Data Register (MDR)',
      'Current Instruction Register (CIR)',
      'Buses',
      'Data bus',
      'Address bus',
      'Control bus',
      'Fetch-Decode-Execute cycle',
      'Factors affecting CPU performance',
      'Clock speed',
      'Number of cores',
      'Cache size',
      'Word length',
      'Pipelining',
      'Von Neumann architecture',
      'Harvard architecture',
      'Contemporary processors',
      'CISC vs RISC',
      'Multi-core processors',
      'Parallel processing',
      'GPU processing',
      // 1.1.2 Types of processor
      'Co-processors',
      'Graphics processing unit',
      'SIMD',
      'MIMD',
      // 1.1.3 Input, output and storage
      'Input devices',
      'Output devices',
      'Barcode readers',
      'Digital cameras',
      'RFID',
      'Laser printers',
      'Inkjet printers',
      '3D printers',
      'Actuators',
      'Speakers',
      'Magnetic storage',
      'Optical storage',
      'Solid state storage',
      'RAM',
      'ROM',
      'Virtual storage',
    ],
  },

  // 1.2 SOFTWARE AND SOFTWARE DEVELOPMENT
  {
    id: 'software',
    examBoard: 'ocr',
    name: 'Software and Software Development',
    description: 'System software, programming languages, and development tools',
    icon: '⚙️',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.2.1 Systems software
      'Operating systems',
      'Memory management',
      'Paging',
      'Segmentation',
      'Virtual memory',
      'Interrupts',
      'Interrupt Service Routines (ISR)',
      'Interrupt priorities',
      'Scheduling algorithms',
      'Round robin',
      'First come first served',
      'Shortest job first',
      'Shortest remaining time',
      'Multi-level feedback queues',
      'Types of operating system',
      'Distributed OS',
      'Embedded OS',
      'Multi-tasking OS',
      'Multi-user OS',
      'Real-time OS',
      'BIOS',
      'Device drivers',
      'Virtual machines',
      'Host operating system',
      'Guest operating system',
      'Intermediate code',
      // 1.2.2 Applications generation
      'Nature of applications',
      'Utilities',
      'Open source software',
      'Closed source software',
      'Proprietary software',
      'Translators',
      'Assemblers',
      'Compilers',
      'Interpreters',
      'Stages of compilation',
      'Lexical analysis',
      'Syntax analysis',
      'Semantic analysis',
      'Code generation',
      'Code optimisation',
      'Linkers',
      'Loaders',
      'Libraries',
      // 1.2.3 Software development
      'Development methodologies',
      'Waterfall model',
      'Agile methodologies',
      'Extreme programming',
      'Spiral model',
      'Rapid Application Development',
      'Debugging',
      'IDE features',
      // 1.2.4 Programming languages
      'Programming paradigms',
      'Procedural languages',
      'Object-oriented languages',
      'Assembly language',
      'Modes of addressing memory',
      'Immediate addressing',
      'Direct addressing',
      'Indirect addressing',
      'Indexed addressing',
    ],
  },

  // 1.3 EXCHANGING DATA
  {
    id: 'exchanging-data',
    examBoard: 'ocr',
    name: 'Exchanging Data',
    description: 'Compression, encryption, databases, networks, and web technologies',
    icon: '🔄',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.3.1 Compression, encryption, hashing
      'Lossy compression',
      'Lossless compression',
      'Run-length encoding',
      'Dictionary coding',
      'Symmetric encryption',
      'Asymmetric encryption',
      'Public key',
      'Private key',
      'Uses of hashing',
      'Hash tables',
      'Hash collisions',
      // 1.3.2 Databases
      'Relational databases',
      'Flat file databases',
      'Tables',
      'Records',
      'Fields',
      'Primary key',
      'Secondary key',
      'Foreign key',
      'Entity-relationship modelling',
      'Entity-relationship diagrams',
      'One-to-one',
      'One-to-many',
      'Many-to-many',
      'Referential integrity',
      'Normalisation',
      'First normal form (1NF)',
      'Second normal form (2NF)',
      'Third normal form (3NF)',
      'SQL',
      'SELECT',
      'INSERT',
      'UPDATE',
      'DELETE',
      'CREATE TABLE',
      'DROP TABLE',
      'ALTER TABLE',
      'JOIN',
      'WHERE',
      'ORDER BY',
      'GROUP BY',
      'Transaction processing',
      'ACID',
      'Record locking',
      'Redundancy',
      // 1.3.3 Networks
      'Network characteristics',
      'Types of network',
      'LAN',
      'WAN',
      'Protocols',
      'Protocol stack',
      'TCP/IP model',
      'Application layer protocols',
      'HTTP',
      'HTTPS',
      'FTP',
      'POP3',
      'IMAP',
      'SMTP',
      'Transport layer',
      'TCP',
      'UDP',
      'Ports',
      'Network layer',
      'IP addressing',
      'Subnetting',
      'DNS',
      'Data link layer',
      'MAC addresses',
      'CSMA/CD',
      'Circuit switching',
      'Packet switching',
      'Network hardware',
      'Routers',
      'Switches',
      'Hubs',
      'Gateways',
      'Firewalls',
      'Network topologies',
      'Star',
      'Bus',
      'Physical vs logical topology',
      'Client-server model',
      'Peer-to-peer model',
      // 1.3.4 Web technologies
      'HTML',
      'CSS',
      'JavaScript',
      'Search engine indexing',
      'PageRank algorithm',
      'Client-side processing',
      'Server-side processing',
    ],
  },

  // 1.4 DATA TYPES, DATA STRUCTURES AND ALGORITHMS
  {
    id: 'data-structures',
    examBoard: 'ocr',
    name: 'Data Types, Data Structures and Algorithms',
    description: 'Data representation, data structures, and Boolean algebra',
    icon: '🗃️',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.4.1 Data types
      'Primitive data types',
      'Integer',
      'Real',
      'Boolean',
      'Character',
      'String',
      'Pointer',
      'User-defined data types',
      // 1.4.2 Data structures
      'Arrays',
      'Records',
      'Lists',
      'Tuples',
      'Linked lists',
      'Queues',
      'Stacks',
      'Trees',
      'Binary trees',
      'Binary search trees',
      'Hash tables',
      'Dictionaries',
      'Graphs',
      'Directed graphs',
      'Undirected graphs',
      'Weighted graphs',
      'Adjacency matrix',
      'Adjacency list',
      // 1.4.3 Boolean algebra
      'Boolean expressions',
      'De Morgan\'s laws',
      'Boolean identities',
      'Karnaugh maps',
      'Logic gate diagrams',
      'AND gate',
      'OR gate',
      'NOT gate',
      'XOR gate',
      'NAND gate',
      'NOR gate',
      'Adder circuits',
      'Half adder',
      'Full adder',
      'Flip-flops',
      'D-type flip-flop',
    ],
  },

  // 1.5 LEGAL, MORAL, CULTURAL AND ETHICAL ISSUES
  {
    id: 'ethics',
    examBoard: 'ocr',
    name: 'Legal, Moral, Cultural and Ethical Issues',
    description: 'Computing legislation and ethical considerations',
    icon: '⚖️',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.5.1 Computing related legislation
      'Data Protection Act 2018',
      'GDPR',
      'Computer Misuse Act 1990',
      'Copyright, Designs and Patents Act 1988',
      'Regulation of Investigatory Powers Act 2000',
      'Freedom of Information Act 2000',
      // 1.5.2 Moral and ethical issues
      'Ethical considerations',
      'Privacy',
      'Surveillance',
      'Data ownership',
      'Personal data',
      'Cookies',
      'Digital footprint',
      'Censorship',
      'AI ethics',
      'Environmental impact',
      'E-waste',
      'Energy consumption',
      'Impact on employment',
      'Automation',
      'Digital divide',
      'Accessibility',
      'Code of conduct',
      'Professional standards',
      'BCS Code of Conduct',
      'ACM Code of Ethics',
    ],
  },

  // ============================================================================
  // COMPONENT 2: ALGORITHMS AND PROGRAMMING
  // ============================================================================

  // 2.1 ELEMENTS OF COMPUTATIONAL THINKING
  {
    id: 'computational-thinking',
    examBoard: 'ocr',
    name: 'Elements of Computational Thinking',
    description: 'Problem solving, abstraction, and algorithm design',
    icon: '🧠',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.1.1 Thinking abstractly
      'Abstraction',
      'Representational abstraction',
      'Abstraction by generalisation',
      'Information hiding',
      'Procedural abstraction',
      'Functional abstraction',
      'Data abstraction',
      'Problem abstraction',
      'Decomposition',
      // 2.1.2 Thinking ahead
      'Identifying inputs and outputs',
      'Pre-conditions',
      'Caching',
      'Reusable components',
      // 2.1.3 Thinking procedurally
      'Problem decomposition',
      'Top-down design',
      'Identifying components',
      'Identifying subprocedures',
      'Flow charts',
      'Pseudo-code',
      // 2.1.4 Thinking logically
      'Identifying decision points',
      'Determining logical conditions',
      'Logical reasoning',
      // 2.1.5 Thinking concurrently
      'Concurrent processing',
      'Parallel processing',
      'Benefits of concurrent processing',
    ],
  },

  // 2.2 PROBLEM SOLVING AND PROGRAMMING
  {
    id: 'programming',
    examBoard: 'ocr',
    name: 'Problem Solving and Programming',
    description: 'Programming concepts, paradigms, and techniques',
    icon: '💻',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.2.1 Programming techniques
      'Variable declaration',
      'Constant declaration',
      'Assignment',
      'Iteration',
      'For loops',
      'While loops',
      'Repeat-until loops',
      'Selection',
      'If-then-else',
      'Case/switch',
      'Nested structures',
      'Subroutines',
      'Procedures',
      'Functions',
      'Parameters',
      'Passing by value',
      'Passing by reference',
      'Return values',
      'Local and global scope',
      'Recursion',
      'Recursive algorithms',
      'Base case',
      'Stack frames',
      'Use of IDE',
      'Debugging',
      'Breakpoints',
      // 2.2.2 Computational methods
      'Features of computational methods',
      'Problem recognition',
      'Problem decomposition',
      'Divide and conquer',
      'Pattern recognition',
      'Backtracking',
      'Data mining',
      'Heuristics',
      'Performance modelling',
      'Pipelining',
      'Visualisation',
      // Object-oriented programming
      'Object-oriented programming',
      'Classes',
      'Objects',
      'Methods',
      'Attributes',
      'Instantiation',
      'Encapsulation',
      'Inheritance',
      'Polymorphism',
      'Overriding',
      'Public and private',
      'Getters and setters',
      'Constructors',
      'Destructors',
      'Class diagrams',
      'Association',
      'Aggregation',
      'Composition',
    ],
  },

  // 2.3 ALGORITHMS
  {
    id: 'algorithms',
    examBoard: 'ocr',
    name: 'Algorithms',
    description: 'Analysis, searching, sorting, path finding, and optimisation',
    icon: '🔄',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.3.1 Analysis and design of algorithms
      'Algorithm design',
      'Big O notation',
      'Time complexity',
      'Space complexity',
      'O(1) - constant',
      'O(log n) - logarithmic',
      'O(n) - linear',
      'O(n log n) - linearithmic',
      'O(n²) - polynomial',
      'O(2^n) - exponential',
      'O(n!) - factorial',
      'Best case',
      'Average case',
      'Worst case',
      'Comparing algorithms',
      'Tractable problems',
      'Intractable problems',
      'Limits of computation',
      'Halting problem',
      'Computable and non-computable',
      // 2.3.2 Searching algorithms
      'Linear search',
      'Binary search',
      'Binary tree search',
      // 2.3.3 Sorting algorithms
      'Bubble sort',
      'Insertion sort',
      'Merge sort',
      'Quick sort',
      'Comparing sorting algorithms',
      // 2.3.4 Graph traversal
      'Breadth-first search',
      'Depth-first search',
      'Applications of graph traversal',
      // 2.3.5 Path-finding algorithms
      'Dijkstra\'s algorithm',
      'A* algorithm',
      'Shortest path',
      // 2.3.6 Optimisation algorithms
      'Optimisation problems',
      'Heuristic methods',
    ],
  },

  // ADDITIONAL TOPICS
  // Regular languages and finite state machines
  {
    id: 'theory-computation',
    examBoard: 'ocr',
    name: 'Theory of Computation',
    description: 'Finite state machines, regular expressions, and BNF',
    icon: '🧮',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Finite state machines
      'Finite state machines',
      'Mealy machines',
      'Moore machines',
      'State transition diagrams',
      'State transition tables',
      'Acceptors',
      'Recognisers',
      // Sets
      'Set theory',
      'Set notation',
      'Finite and infinite sets',
      'Countably infinite',
      'Subsets',
      'Union',
      'Intersection',
      'Difference',
      'Cartesian product',
      // Regular expressions
      'Regular expressions',
      'Pattern matching',
      'Metacharacters',
      'Regular languages',
      // BNF and syntax diagrams
      'Backus-Naur Form (BNF)',
      'Syntax diagrams',
      'Parsing',
      'Context-free grammars',
      'Parse trees',
      // Reverse Polish notation
      'Reverse Polish notation',
      'Infix to RPN',
      'Evaluating RPN',
      'Using stacks for RPN',
    ],
  },

  // Functional programming
  {
    id: 'functional',
    examBoard: 'ocr',
    name: 'Functional Programming',
    description: 'Functional programming paradigm and techniques',
    icon: 'λ',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Functional programming
      'Functional programming paradigm',
      'First-class functions',
      'Higher-order functions',
      'Pure functions',
      'Side effects',
      'Immutability',
      'Function application',
      'Function composition',
      'Partial application',
      'Currying',
      // List processing
      'Lists in functional programming',
      'Head and tail',
      'List operations',
      'Map',
      'Filter',
      'Reduce/fold',
      'Recursion with lists',
    ],
  },
];

export function getOCRALevelComputerScienceTopicById(id: string): Topic | undefined {
  return ocrALevelComputerScienceTopics.find((topic) => topic.id === id);
}

export function getOCRALevelComputerScienceTopicsByPaper(paper: 1 | 2): Topic[] {
  const paperName = `Paper ${paper}`;
  return ocrALevelComputerScienceTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countOCRALevelComputerScienceSubtopics(): number {
  return ocrALevelComputerScienceTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
