// OCR A-Level Biology A (H420) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/as-and-a-level/biology-a-h020-h420-from-2015/

import { Topic } from '@/types';

export const ocrALevelBiologyTopics: Topic[] = [
  // ============================================================================
  // MODULE 2: Foundations in Biology
  // ============================================================================
  {
    id: 'ocr-alevel-biology-foundations',
    examBoard: 'ocr',
    name: 'Foundations in Biology',
    description: 'Cell structure, biological molecules, enzymes, and membranes',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 2.1.1 Cell structure
      'Microscopy',
      'Magnification and resolution',
      'Eukaryotic cell structure',
      'Prokaryotic cell structure',
      'Ultrastructure of organelles',
      'Nucleus',
      'Mitochondria',
      'Chloroplasts',
      'Ribosomes',
      'Endoplasmic reticulum',
      'Golgi apparatus',
      'Lysosomes',
      'Centrioles',
      'Comparing plant, animal, and prokaryotic cells',
      'PAG 1: Microscopy',
      // 2.1.2 Biological molecules
      'Water properties',
      'Hydrogen bonding',
      'Carbohydrates',
      'Monosaccharides',
      'Disaccharides',
      'Polysaccharides',
      'Glycosidic bonds',
      'Starch',
      'Glycogen',
      'Cellulose',
      'Lipids',
      'Triglycerides',
      'Phospholipids',
      'Saturated and unsaturated fatty acids',
      'Proteins',
      'Amino acids',
      'Peptide bonds',
      'Protein structure levels',
      'Fibrous proteins',
      'Globular proteins',
      'Testing for biological molecules',
      'PAG 2: Biological molecules',
      // 2.1.3 Nucleic acids
      'DNA structure',
      'RNA structure',
      'Nucleotides',
      'Purines and pyrimidines',
      'Complementary base pairing',
      'DNA replication',
      'Semi-conservative replication',
      'ATP structure',
      'ATP as energy currency',
      // 2.1.4 Enzymes
      'Enzyme structure',
      'Active site',
      'Lock and key model',
      'Induced fit model',
      'Enzyme specificity',
      'Factors affecting enzyme activity',
      'Temperature',
      'pH',
      'Substrate concentration',
      'Enzyme concentration',
      'Competitive inhibition',
      'Non-competitive inhibition',
      'Cofactors and coenzymes',
      'PAG 3: Enzyme investigations',
      // 2.1.5 Biological membranes
      'Fluid mosaic model',
      'Phospholipid bilayer',
      'Membrane proteins',
      'Glycoproteins',
      'Cholesterol',
      'Passive transport',
      'Diffusion',
      'Facilitated diffusion',
      'Osmosis',
      'Water potential',
      'Active transport',
      'Endocytosis',
      'Exocytosis',
      'PAG 4: Membrane permeability',
      // 2.1.6 Cell division
      'Cell cycle',
      'Interphase',
      'Mitosis',
      'Cytokinesis',
      'Cell cycle regulation',
      'Cancer',
      'Meiosis',
      'Stages of meiosis',
      'Genetic variation from meiosis',
      'PAG 5: Cell division',
    ],
  },

  // ============================================================================
  // MODULE 3: Exchange and Transport
  // ============================================================================
  {
    id: 'ocr-alevel-biology-exchange-transport',
    examBoard: 'ocr',
    name: 'Exchange and Transport',
    description: 'Gas exchange, transport systems in plants and animals',
    icon: '🫁',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.1.1 Exchange surfaces
      'Surface area to volume ratio',
      'Exchange surface features',
      'Specialised exchange surfaces',
      // 3.1.2 Gas exchange in different organisms
      'Gas exchange in insects',
      'Spiracles',
      'Tracheae',
      'Gas exchange in fish',
      'Counter-current flow',
      'Gas exchange in amphibians',
      'Gas exchange in plants',
      'Stomata',
      'Guard cells',
      'Xerophytes',
      'Hydrophytes',
      'Gas exchange in mammals',
      'Lung structure',
      'Alveoli',
      'Ventilation',
      'PAG 6: Dissection',
      // 3.1.3 Transport in animals
      'Need for transport systems',
      'Single circulatory system',
      'Double circulatory system',
      'Heart structure',
      'Cardiac cycle',
      'Cardiac output',
      'Heart rate control',
      'Blood vessels',
      'Arteries',
      'Arterioles',
      'Capillaries',
      'Venules',
      'Veins',
      'Blood composition',
      'Plasma',
      'Red blood cells',
      'White blood cells',
      'Platelets',
      'Haemoglobin',
      'Oxygen transport',
      'Oxygen dissociation curve',
      'Bohr effect',
      'Foetal haemoglobin',
      'Carbon dioxide transport',
      'Tissue fluid formation',
      'Lymph',
      'PAG 7: Heart dissection',
      // 3.1.4 Transport in plants
      'Xylem structure',
      'Phloem structure',
      'Transpiration',
      'Cohesion-tension theory',
      'Root pressure',
      'Factors affecting transpiration',
      'Translocation',
      'Mass flow hypothesis',
      'Source and sink',
      'PAG 8: Plant transport',
    ],
  },

  // ============================================================================
  // MODULE 4: Biodiversity, Evolution and Disease
  // ============================================================================
  {
    id: 'ocr-alevel-biology-biodiversity',
    examBoard: 'ocr',
    name: 'Biodiversity, Evolution and Disease',
    description: 'Classification, biodiversity, evolution, and communicable diseases',
    icon: '🌍',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 4.1.1 Communicable diseases
      'Pathogens',
      'Bacteria',
      'Viruses',
      'Protoctista',
      'Fungi',
      'Transmission of disease',
      'Plant diseases',
      'Animal diseases',
      'Tuberculosis',
      'HIV/AIDS',
      'Malaria',
      'Cholera',
      'Plant defences',
      'Animal defences',
      'Primary defences',
      'Non-specific immunity',
      'Inflammation',
      'Phagocytosis',
      'Specific immunity',
      'T lymphocytes',
      'B lymphocytes',
      'Antibodies',
      'Clonal selection',
      'Primary immune response',
      'Secondary immune response',
      'Vaccination',
      'Herd immunity',
      'Antibiotics',
      'Antibiotic resistance',
      'PAG 9: Investigating microorganisms',
      // 4.2.1 Biodiversity
      'Biodiversity definition',
      'Species richness',
      'Species evenness',
      'Genetic diversity',
      'Ecosystem diversity',
      'Sampling techniques',
      'Random sampling',
      'Systematic sampling',
      'Simpson\'s Index',
      // 4.2.2 Classification and evolution
      'Classification',
      'Linnaean system',
      'Three-domain system',
      'Binomial naming',
      'Phylogeny',
      'Cladistics',
      'Evidence for evolution',
      'Fossil record',
      'Comparative anatomy',
      'Molecular evidence',
      'Natural selection',
      'Variation',
      'Types of selection',
      'Directional selection',
      'Stabilising selection',
      'Disruptive selection',
      'Genetic drift',
      'Speciation',
      'Allopatric speciation',
      'Sympatric speciation',
      // 4.2.3 Maintaining biodiversity
      'Threats to biodiversity',
      'Conservation methods',
      'In-situ conservation',
      'Ex-situ conservation',
      'Seed banks',
      'Captive breeding',
      'International agreements',
    ],
  },

  // ============================================================================
  // MODULE 5: Communication, Homeostasis and Energy
  // ============================================================================
  {
    id: 'ocr-alevel-biology-communication-homeostasis',
    examBoard: 'ocr',
    name: 'Communication and Homeostasis',
    description: 'Nervous system, hormones, and homeostasis',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 5.1.1 Communication and homeostasis
      'Need for communication',
      'Cell signalling',
      'Homeostasis definition',
      'Negative feedback',
      'Positive feedback',
      // 5.1.2 Nervous communication
      'Nervous system structure',
      'Sensory neurones',
      'Motor neurones',
      'Relay neurones',
      'Receptors',
      'Pacinian corpuscle',
      'Resting potential',
      'Action potential',
      'Depolarisation',
      'Repolarisation',
      'Refractory period',
      'Saltatory conduction',
      'Factors affecting conduction',
      'Synapses',
      'Synaptic transmission',
      'Neurotransmitters',
      'Acetylcholine',
      'Summation',
      'PAG 10: Nervous tissue dissection',
      // 5.1.3 Hormonal communication
      'Endocrine system',
      'Hormones',
      'Adrenal glands',
      'Adrenaline',
      'Pancreas',
      'Islets of Langerhans',
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Second messengers',
      'Diabetes mellitus',
      'Type 1 diabetes',
      'Type 2 diabetes',
      // 5.1.4 Excretion
      'Excretion definition',
      'Liver structure',
      'Liver functions',
      'Ornithine cycle',
      'Kidney structure',
      'Nephron',
      'Ultrafiltration',
      'Selective reabsorption',
      'Loop of Henle',
      'Counter-current multiplier',
      'Osmoregulation',
      'ADH',
      'Water potential control',
      'Kidney failure',
      'Dialysis',
      'Kidney transplant',
    ],
  },
  {
    id: 'ocr-alevel-biology-energy',
    examBoard: 'ocr',
    name: 'Energy for Biological Processes',
    description: 'Photosynthesis and respiration',
    icon: '⚡',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 5.2.1 Photosynthesis
      'Photosynthesis overview',
      'Chloroplast structure',
      'Photosynthetic pigments',
      'Light-dependent reactions',
      'Photosystems I and II',
      'Cyclic photophosphorylation',
      'Non-cyclic photophosphorylation',
      'Photolysis',
      'Chemiosmosis',
      'Light-independent reactions',
      'Calvin cycle',
      'Carbon fixation',
      'RuBisCO',
      'Regeneration of RuBP',
      'Limiting factors',
      'Compensation point',
      'PAG 11: Chromatography',
      // 5.2.2 Respiration
      'Respiration overview',
      'Glycolysis',
      'Link reaction',
      'Krebs cycle',
      'Oxidative phosphorylation',
      'Electron transport chain',
      'ATP synthase',
      'Chemiosmosis in mitochondria',
      'ATP yield',
      'Anaerobic respiration',
      'Lactate fermentation',
      'Alcoholic fermentation',
      'Respiratory substrates',
      'Respiratory quotient',
      'PAG 12: Respiration rates',
    ],
  },

  // ============================================================================
  // MODULE 6: Genetics, Evolution and Ecosystems
  // ============================================================================
  {
    id: 'ocr-alevel-biology-genetics',
    examBoard: 'ocr',
    name: 'Genetics and Evolution',
    description: 'Inheritance, genetic technologies, and evolution',
    icon: '🧬',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 6.1.1 Cellular control
      'Genes and protein synthesis',
      'Genetic code',
      'Transcription',
      'mRNA processing',
      'Translation',
      'Gene mutations',
      'Point mutations',
      'Chromosome mutations',
      'Gene regulation',
      'Lac operon',
      'Transcription factors',
      'Epigenetics',
      'Body plans',
      'Homeobox genes',
      'Apoptosis',
      // 6.1.2 Patterns of inheritance
      'Mendelian inheritance',
      'Monohybrid crosses',
      'Dihybrid crosses',
      'Codominance',
      'Multiple alleles',
      'Sex linkage',
      'Autosomal linkage',
      'Epistasis',
      'Chi-squared test',
      // 6.1.3 Manipulating genomes
      'DNA sequencing',
      'Polymerase chain reaction',
      'Gel electrophoresis',
      'Genetic fingerprinting',
      'Restriction enzymes',
      'Ligases',
      'Vectors',
      'Recombinant DNA',
      'Transformation',
      'Gene probes',
      'Genetic engineering',
      'Gene therapy',
      'Genetically modified organisms',
      'CRISPR',
      'Ethical considerations',
    ],
  },
  {
    id: 'ocr-alevel-biology-ecosystems',
    examBoard: 'ocr',
    name: 'Ecosystems',
    description: 'Populations, succession, and nutrient cycles',
    icon: '🌳',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 6.3.1 Ecosystems
      'Ecosystem structure',
      'Biotic factors',
      'Abiotic factors',
      'Populations',
      'Population growth',
      'Carrying capacity',
      'Limiting factors',
      'Predator-prey relationships',
      'Competition',
      'Interspecific competition',
      'Intraspecific competition',
      'Ecological niches',
      // 6.3.2 Energy and ecosystems
      'Energy flow',
      'Food chains',
      'Food webs',
      'Trophic levels',
      'Gross primary productivity',
      'Net primary productivity',
      'Energy transfer efficiency',
      'Pyramids of biomass',
      'Pyramids of energy',
      // 6.3.3 Nutrient cycles
      'Nitrogen cycle',
      'Nitrogen fixation',
      'Nitrification',
      'Denitrification',
      'Ammonification',
      'Carbon cycle',
      'Decomposition',
      'Phosphorus cycle',
      // 6.3.4 Succession
      'Primary succession',
      'Secondary succession',
      'Climax community',
      'Deflected succession',
      'Conservation',
      // 6.3.5 Human impacts
      'Agriculture',
      'Farming practices',
      'Sustainability',
      'Climate change',
      'Nitrogen fertilisers',
      'Eutrophication',
    ],
  },
  {
    id: 'ocr-alevel-biology-control-coordination',
    examBoard: 'ocr',
    name: 'Animal and Plant Responses',
    description: 'Muscles, animal behaviour, and plant responses',
    icon: '🌱',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 6.2.1 Animal responses
      'Musculoskeletal system',
      'Muscle structure',
      'Sarcomere',
      'Sliding filament theory',
      'Role of ATP',
      'Role of calcium ions',
      'Tropomyosin and troponin',
      'Fast twitch fibres',
      'Slow twitch fibres',
      'Neuromuscular junction',
      'Brain structure',
      'Cerebrum',
      'Cerebellum',
      'Medulla oblongata',
      'Hypothalamus',
      'Reflexes',
      'Fight or flight response',
      'Controlling heart rate',
      'PAG: Animal responses',
      // 6.2.2 Plant responses
      'Plant hormones',
      'Auxins',
      'Gibberellins',
      'Abscisic acid',
      'Ethene',
      'Cytokinins',
      'Tropisms',
      'Phototropism',
      'Gravitropism',
      'Hormone interactions',
      'Commercial uses of plant hormones',
      'PAG: Plant responses',
    ],
  },
];

export function getOCRALevelBiologyTopicById(id: string): Topic | undefined {
  return ocrALevelBiologyTopics.find((topic) => topic.id === id);
}

export function getOCRALevelBiologyTopicsByPaper(paper: 1 | 2): Topic[] {
  const paperName = `Paper ${paper}`;
  return ocrALevelBiologyTopics.filter((topic) => topic.paperRestriction === paperName);
}

export function countOCRALevelBiologySubtopics(): number {
  return ocrALevelBiologyTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
