// OCR GCSE History B (Schools History Project) (J411) Topics
// Based on official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/history-b-schools-history-project-j411-from-2016/

import { Topic } from '@/types';

export const ocrGCSEHistoryTopics: Topic[] = [
  // ============================================================================
  // COMPONENT GROUP 1: BRITISH HISTORY
  // Thematic Studies
  // ============================================================================
  {
    id: 'peoples-health',
    name: 'The People\'s Health c1250-present',
    description: 'Changes in health and medicine in Britain',
    icon: '🏥',
    color: 'bg-pink-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Thematic',
    subtopics: [
      // Medieval c1250-c1500
      'Medieval ideas about disease',
      'Four Humours theory',
      'Miasma theory',
      'Role of God',
      'Medieval treatments',
      'Herbal remedies',
      'Prayer and pilgrimage',
      'Bloodletting',
      'Medieval hospitals',
      'Role of the Church',
      'Public health medieval',
      'Towns and sanitation',
      'The Black Death',
      'Responses to plague',
      // Early Modern c1500-c1750
      'Continuity in ideas',
      'New Renaissance ideas',
      'Vesalius',
      'Harvey',
      'Pare',
      'Great Plague 1665',
      'Public health problems',
      // Industrial c1750-c1900
      'Industrial Revolution impact',
      'Urban growth problems',
      'Cholera epidemics',
      'Germ theory',
      'Pasteur',
      'Koch',
      'Jenner vaccination',
      'Public Health Acts',
      'Chadwick',
      'John Snow',
      'Surgery improvements',
      'Anaesthetics',
      'Antiseptics',
      'Lister',
      // Modern c1900-present
      'Magic bullets',
      'Antibiotics',
      'Penicillin',
      'Fleming Florey Chain',
      'NHS creation',
      'Modern medicine',
      'Government role today',
      'Lifestyle diseases',
    ],
  },
  {
    id: 'crime-punishment',
    name: 'Crime and Punishment c1250-present',
    description: 'Changes in crime, punishment and law enforcement',
    icon: '⚖️',
    color: 'bg-gray-700',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Thematic',
    subtopics: [
      // Medieval c1250-c1500
      'Crimes medieval',
      'Property crimes',
      'Violent crimes',
      'Crimes against authority',
      'Heresy',
      'Law enforcement medieval',
      'Tithings',
      'Hue and cry',
      'Manor courts',
      'Royal courts',
      'Trial by ordeal',
      'Punishments medieval',
      'Fines',
      'Corporal punishment',
      'Execution',
      // Early Modern c1500-c1750
      'New crimes',
      'Vagabondage',
      'Witchcraft',
      'Smuggling',
      'Poaching',
      'Highway robbery',
      'Enforcement changes',
      'JPs role',
      'Parish constables',
      'Punishments changes',
      'Bloody Code',
      'Transportation',
      // Industrial c1750-c1900
      'Industrial crime',
      'Policing revolution',
      'Bow Street Runners',
      'Metropolitan Police 1829',
      'Peel reforms',
      'Prison reform',
      'Howard',
      'Fry',
      'Pentonville',
      'End of public execution',
      // Modern c1900-present
      'Modern crimes',
      'Car crime',
      'Computer crime',
      'Terrorism',
      'Modern policing',
      'Technology',
      'Modern punishments',
      'Death penalty abolished',
      'Prison today',
      'Alternatives to prison',
    ],
  },
  {
    id: 'migrants-britain',
    name: 'Migrants to Britain c1250-present',
    description: 'Migration and its impact on British history',
    icon: '🌍',
    color: 'bg-teal-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Thematic',
    subtopics: [
      // Medieval
      'Medieval migration',
      'Jewish communities',
      'Italian merchants',
      'Flemish weavers',
      'Hanseatic League',
      // Early Modern
      'Religious refugees',
      'Huguenots',
      'Black Tudors',
      'Romani people',
      // Industrial
      'Irish migration',
      'Great Famine',
      'Jewish migration',
      'Pogroms',
      'Aliens Act 1905',
      // 20th century
      'Belgian refugees WWI',
      'Jewish refugees 1930s',
      'Kindertransport',
      'Windrush generation',
      'Commonwealth immigration',
      'Ugandan Asians',
      'EU migration',
      // Impact
      'Economic impact',
      'Cultural impact',
      'Responses to migration',
      'Integration',
      'Multiculturalism',
    ],
  },
  // ============================================================================
  // COMPONENT GROUP 1: BRITISH HISTORY
  // British Depth Studies
  // ============================================================================
  {
    id: 'norman-conquest',
    name: 'The Norman Conquest 1065-1087',
    description: 'England before and after 1066',
    icon: '🏰',
    color: 'bg-stone-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Depth',
    subtopics: [
      // Anglo-Saxon England
      'Anglo-Saxon government',
      'Edward the Confessor',
      'Earls and thegns',
      'The Church',
      'Villages and towns',
      // Succession crisis
      'Edward\'s death',
      'Claimants to throne',
      'Harold Godwinson',
      'William of Normandy',
      'Harald Hardrada',
      'Edgar Atheling',
      // 1066
      'Stamford Bridge',
      'Harold\'s march',
      'Battle of Hastings',
      'Norman tactics',
      'English defeat',
      // Conquest
      'William\'s coronation',
      'Establishing control',
      'Marcher earls',
      'Castles',
      'Motte and bailey',
      // Resistance
      'English rebellions',
      'Exeter 1068',
      'Northern rebellion',
      'Harrying of the North',
      'Hereward the Wake',
      'Revolt of Earls 1075',
      // Norman England
      'Feudal system',
      'Land ownership',
      'Domesday Book',
      'Norman Church',
      'Lanfranc',
      'William\'s government',
      'Forest laws',
    ],
  },
  {
    id: 'elizabethans',
    name: 'The Elizabethans 1580-1603',
    description: 'England in the later Elizabethan period',
    icon: '👑',
    color: 'bg-amber-700',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Depth',
    subtopics: [
      // Elizabeth and government
      'Elizabeth I',
      'Government structure',
      'Privy Council',
      'Parliament',
      'Court life',
      // Religion
      'Religious settlement',
      'Catholic threat',
      'Mary Queen of Scots',
      'Catholic plots',
      'Puritans',
      // War with Spain
      'Causes of conflict',
      'Drake privateering',
      'Netherlands',
      'Spanish Armada 1588',
      'Armada campaign',
      'English victory',
      // Society
      'Social hierarchy',
      'Gentry',
      'Yeomen',
      'The poor',
      'Poverty problem',
      'Poor Laws',
      'Vagabonds',
      // Culture
      'Education',
      'Theatre',
      'Shakespeare',
      'Globe Theatre',
      'Music and art',
      // Exploration
      'Voyages of discovery',
      'Drake circumnavigation',
      'Raleigh',
      'Virginia colony',
      'Trade expansion',
    ],
  },
  {
    id: 'britain-1900-1918',
    name: 'Britain in Peace and War 1900-1918',
    description: 'Britain from Edwardian era through WWI',
    icon: '🇬🇧',
    color: 'bg-blue-700',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 1 Depth',
    subtopics: [
      // Edwardian Britain
      'Britain in 1900',
      'Class system',
      'Poverty',
      'Booth and Rowntree',
      'Liberal reforms',
      'Old age pensions',
      'National Insurance',
      // Suffrage
      'Women\'s suffrage',
      'Suffragists',
      'NUWSS',
      'Suffragettes',
      'WSPU',
      'Pankhursts',
      'Militancy',
      'Cat and Mouse Act',
      'Emily Davison',
      // WWI impact
      'Outbreak of war',
      'Recruitment',
      'Pals battalions',
      'Conscription',
      'DORA',
      // Home Front
      'Women\'s war work',
      'Munitions',
      'Land Army',
      'Rationing',
      'Propaganda',
      'Air raids',
      // Trenches
      'Life in trenches',
      'Conditions',
      'Going over the top',
      'Shell shock',
      // End of war
      'Armistice',
      'Impact on Britain',
      'Women\'s vote 1918',
    ],
  },
  // ============================================================================
  // COMPONENT 2: HISTORY AROUND US
  // ============================================================================
  {
    id: 'around-us',
    name: 'History Around Us',
    description: 'Study of a local historic site',
    icon: '🏛️',
    color: 'bg-purple-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 2',
    subtopics: [
      // Site study skills
      'Physical features of site',
      'Layout and design',
      'Changes over time',
      'Evidence at the site',
      'Archaeological evidence',
      'Documentary evidence',
      // Historical context
      'Site in its time period',
      'People who used the site',
      'Purpose of the site',
      'Local and national significance',
      // Analysis
      'How site has changed',
      'Why site has changed',
      'Preservation',
      'Heritage management',
      // Evaluation
      'What site tells us',
      'Limitations of site evidence',
      'Comparing sources',
    ],
  },
  // ============================================================================
  // COMPONENT GROUP 3: WORLD HISTORY
  // Period Studies
  // ============================================================================
  {
    id: 'viking-expansion',
    name: 'Viking Expansion c750-c1050',
    description: 'Viking raids, settlement and legacy',
    icon: '⚔️',
    color: 'bg-slate-700',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 3 Period',
    subtopics: [
      // Viking society
      'Scandinavian origins',
      'Viking society',
      'Religion and beliefs',
      'Longships',
      'Navigation',
      // Raids
      'Reasons for raids',
      'Lindisfarne 793',
      'Raids on Britain',
      'Raids on Francia',
      'Great Heathen Army',
      // Settlement
      'Danelaw',
      'Viking York',
      'Alfred the Great',
      'Wessex resistance',
      // Wider expansion
      'Iceland',
      'Greenland',
      'Vinland',
      'Russia',
      'Byzantium',
      'Normandy',
      // Legacy
      'Cnut\'s empire',
      'End of Viking Age',
      'Cultural legacy',
      'Place names',
      'Language impact',
    ],
  },
  {
    id: 'making-america',
    name: 'The Making of America 1789-1900',
    description: 'Development of the United States',
    icon: '🇺🇸',
    color: 'bg-blue-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 3 Period',
    subtopics: [
      // Early Republic
      'Constitution',
      'Washington presidency',
      'Political parties',
      'Louisiana Purchase',
      // Westward expansion
      'Manifest Destiny',
      'Lewis and Clark',
      'Oregon Trail',
      'California Gold Rush',
      'Railroads',
      // Native Americans
      'Plains Indians',
      'Indian Removal',
      'Trail of Tears',
      'Reservations',
      'Indian Wars',
      'Little Bighorn',
      'Wounded Knee',
      // Slavery
      'Cotton economy',
      'Slave life',
      'Abolition movement',
      'Underground Railroad',
      'Compromise of 1850',
      // Civil War
      'Causes',
      'Secession',
      'Lincoln',
      'Key battles',
      'Emancipation',
      'Union victory',
      // Reconstruction
      'Reconstruction plans',
      'Freedmen\'s Bureau',
      '13th 14th 15th Amendments',
      'Jim Crow',
      'KKK',
      // Gilded Age
      'Industrial growth',
      'Immigration',
      'Urbanisation',
    ],
  },
  // ============================================================================
  // COMPONENT GROUP 3: WORLD HISTORY
  // World Depth Studies
  // ============================================================================
  {
    id: 'nazi-rule',
    name: 'Living under Nazi Rule 1933-1945',
    description: 'Life in Nazi Germany and occupied Europe',
    icon: '🇩🇪',
    color: 'bg-gray-800',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 3 Depth',
    subtopics: [
      // Nazi takeover
      'Hitler Chancellor',
      'Reichstag Fire',
      'Enabling Act',
      'Night of Long Knives',
      'Fuhrer state',
      // Control
      'SS and Gestapo',
      'Concentration camps',
      'Propaganda',
      'Goebbels',
      'Censorship',
      'Book burning',
      // Economy
      'Economic policies',
      'Public works',
      'Rearmament',
      'Four Year Plan',
      'Autarky',
      // Society
      'Workers',
      'DAF',
      'Strength through Joy',
      'Women\'s role',
      'Kinder Kuche Kirche',
      'Youth',
      'Hitler Youth',
      'Education',
      // Religion
      'Churches',
      'Concordat',
      'Protestant churches',
      'Church opposition',
      // Persecution
      'Anti-Semitism',
      'Nuremberg Laws',
      'Kristallnacht',
      'Ghettos',
      'Final Solution',
      'Holocaust',
      'Other victims',
      // War years
      'Home front WWII',
      'Total war',
      'Bombing',
      // Opposition
      'Youth opposition',
      'White Rose',
      'Military opposition',
      'July Plot 1944',
      // Occupied Europe
      'Nazi occupation',
      'Collaboration',
      'Resistance',
    ],
  },
  {
    id: 'first-crusade',
    name: 'The First Crusade c1070-1100',
    description: 'Origins, events and impact of the First Crusade',
    icon: '⚔️',
    color: 'bg-red-700',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 3 Depth',
    subtopics: [
      // Background
      'Christian-Muslim relations',
      'Byzantine Empire',
      'Seljuk Turks',
      'Holy Land significance',
      'Pilgrimage',
      // Causes
      'Alexius I appeal',
      'Pope Urban II',
      'Council of Clermont',
      'Motivations for crusading',
      'Religious motives',
      'Political motives',
      'Economic motives',
      // People\'s Crusade
      'Peter the Hermit',
      'Popular response',
      'March to Constantinople',
      'Destruction of People\'s Crusade',
      // Princes\' Crusade
      'Leaders',
      'Godfrey of Bouillon',
      'Raymond of Toulouse',
      'Bohemond',
      'Journey to Constantinople',
      'Siege of Nicaea',
      'Battle of Dorylaeum',
      'March through Anatolia',
      // Key events
      'Siege of Antioch',
      'Holy Lance',
      'March to Jerusalem',
      'Siege of Jerusalem',
      'Capture of Jerusalem 1099',
      // Aftermath
      'Crusader states',
      'Kingdom of Jerusalem',
      'Impact on East',
      'Impact on West',
      'Legacy of First Crusade',
    ],
  },
  {
    id: 'aztecs-spanish',
    name: 'Aztecs and the Spanish Conquest 1519-1535',
    description: 'The Aztec Empire and its conquest by Spain',
    icon: '🏛️',
    color: 'bg-amber-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'history',
    paperRestriction: 'Component 3 Depth',
    subtopics: [
      // Aztec civilisation
      'Aztec society',
      'Tenochtitlan',
      'Government',
      'Montezuma II',
      'Religion',
      'Human sacrifice',
      'Economy',
      'Tribute system',
      'Warfare',
      // Spanish arrival
      'Spanish in Caribbean',
      'Cortes expedition',
      'Landing in Mexico',
      'Totonac alliance',
      'March inland',
      'Tlaxcala',
      // Conquest
      'Meeting Montezuma',
      'Tenochtitlan first visit',
      'Montezuma captive',
      'Narvaez expedition',
      'La Noche Triste',
      'Siege of Tenochtitlan',
      'Fall of Aztec Empire',
      // Aftermath
      'Spanish rule',
      'Encomienda',
      'Impact on Aztecs',
      'Disease',
      'Population collapse',
      'Cultural destruction',
      'Legacy',
    ],
  },
];

export function getOCRGCSEHistoryTopicById(id: string): Topic | undefined {
  return ocrGCSEHistoryTopics.find((topic) => topic.id === id);
}
