// OCR GCSE Gateway Combined Science A (J250) Topics
// Based on the official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/gateway-science-suite-combined-science-a-j250-from-2016/
//
// Combined Science is worth 2 GCSEs and covers Biology, Chemistry, and Physics
// 6 papers total: Biology, Chemistry, Physics (each has Foundation and Higher tiers)
// Each paper: 1 hour 10 minutes, 60 marks, 16.7% of qualification
//
// (H) = Higher tier only

import { Topic } from '@/types';

export const ocrCombinedScienceTopics: Topic[] = [
  // ============================================================================
  // BIOLOGY TOPICS (B1-B6)
  // ============================================================================
  {
    id: 'ocr-combined-biology-cell-level-systems',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Cell Level Systems',
    description: 'Cell structure, transport across membranes, and cell division',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B1: Cell Level Systems
      'Structure of eukaryotic cells',
      'Plant cell structure',
      'Animal cell structure',
      'Prokaryotic cells',
      'Bacteria structure',
      'Sub-cellular structures',
      'Nucleus',
      'Mitochondria',
      'Ribosomes',
      'Chloroplasts',
      'Vacuole',
      'Cell wall',
      'Microscopy',
      'Calculating magnification',
      'Scale and size',
      'Resolution',
      'Electron microscopes',
      'DNA structure',
      'Genes and chromosomes',
      'Protein synthesis',
      'Enzymes',
      'Lock and key model',
      'Enzyme specificity',
      'Effect of temperature on enzymes',
      'Effect of pH on enzymes',
      'Diffusion',
      'Factors affecting diffusion',
      'Osmosis',
      'Osmosis investigations',
      'Active transport',
      'Mitosis',
      'Cell cycle',
      'Stem cells',
      'Uses of stem cells',
      'Embryonic stem cells',
      'Adult stem cells',
    ],
  },
  {
    id: 'ocr-combined-biology-scaling-up',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Scaling Up',
    description: 'Levels of organisation and organ systems',
    icon: '🫀',
    color: 'bg-red-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B2: Scaling Up
      'Levels of organisation',
      'Specialised cells',
      'Tissues',
      'Organs',
      'Organ systems',
      'Digestive system',
      'Digestive enzymes',
      'Carbohydrases',
      'Proteases',
      'Lipases',
      'Bile',
      'Food tests',
      'The circulatory system',
      'The heart',
      'Heart structure',
      'Blood vessels',
      'Arteries',
      'Veins',
      'Capillaries',
      'Blood',
      'Red blood cells',
      'White blood cells',
      'Platelets',
      'Plasma',
      'Coronary heart disease',
      'Cardiovascular disease treatments',
      'Stents',
      'Statins',
    ],
  },
  {
    id: 'ocr-combined-biology-organism-systems',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Organism Level Systems',
    description: 'Nervous system, hormones, and homeostasis',
    icon: '🧠',
    color: 'bg-pink-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B3: Organism Level Systems
      'Nervous system structure',
      'Central nervous system',
      'Peripheral nervous system',
      'Sensory neurones',
      'Relay neurones',
      'Motor neurones',
      'Synapses',
      'Reflex actions',
      'Reflex arc',
      'Reaction time',
      'The endocrine system',
      'Hormones',
      'Glands',
      'Comparing nervous and hormonal control',
      'Blood glucose regulation',
      'Insulin',
      'Glucagon',
      'Diabetes Type 1',
      'Diabetes Type 2',
      'Treating diabetes',
      'Homeostasis',
      'Negative feedback',
      'The menstrual cycle',
      'Reproductive hormones',
      'FSH',
      'LH',
      'Oestrogen',
      'Progesterone',
      'Contraception',
      'Fertility treatment',
      'IVF',
    ],
  },
  {
    id: 'ocr-combined-biology-community-systems',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Community Level Systems',
    description: 'Photosynthesis, respiration, and ecosystems',
    icon: '🌱',
    color: 'bg-emerald-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B4: Community Level Systems
      'Photosynthesis equation',
      'Photosynthesis as endothermic',
      'Leaf structure',
      'Adaptations for photosynthesis',
      'Factors affecting photosynthesis',
      'Light intensity',
      'Carbon dioxide concentration',
      'Temperature',
      'Limiting factors',
      'Investigating photosynthesis rate',
      'Aerobic respiration',
      'Respiration equation',
      'Anaerobic respiration',
      'Fermentation',
      'Oxygen debt',
      'Response to exercise',
      'Ecosystems',
      'Communities',
      'Abiotic factors',
      'Biotic factors',
      'Food chains',
      'Food webs',
      'Energy transfer',
      'Pyramids of biomass',
      'Efficiency of energy transfer',
      'Carbon cycle',
      'Water cycle',
      'Decomposition',
    ],
  },
  {
    id: 'ocr-combined-biology-interaction-environments',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Interaction Between Systems',
    description: 'Transport in plants and disease',
    icon: '🌿',
    color: 'bg-green-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B5: Interaction Between Systems
      'Plant tissues',
      'Xylem',
      'Phloem',
      'Transpiration',
      'Transpiration stream',
      'Factors affecting transpiration',
      'Guard cells',
      'Stomata',
      'Translocation',
      'Communicable diseases',
      'Pathogens',
      'Bacteria',
      'Viruses',
      'Fungi',
      'Protists',
      'Spreading diseases',
      'Viral diseases',
      'HIV',
      'TMV',
      'Bacterial diseases',
      'Salmonella',
      'Gonorrhoea',
      'Fungal diseases',
      'Rose black spot',
      'Protist diseases',
      'Malaria',
      'Non-specific defences',
      'Immune response',
      'Phagocytosis',
      'Antibodies',
      'Antitoxins',
      'Vaccination',
      'Antibiotics',
      'Antibiotic resistance',
    ],
  },
  {
    id: 'ocr-combined-biology-genes-inheritance',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Global Challenges - Genetics',
    description: 'Genetics, evolution, and biodiversity',
    icon: '🧬',
    color: 'bg-blue-500',
    paperRestriction: 'Biology Paper',
    subtopics: [
      // B6: Global Challenges
      'Sexual reproduction',
      'Asexual reproduction',
      'Meiosis',
      'Genetic variation',
      'Inherited characteristics',
      'Alleles',
      'Dominant and recessive',
      'Homozygous and heterozygous',
      'Genotype and phenotype',
      'Genetic diagrams',
      'Punnett squares',
      'Inherited disorders',
      'Polydactyly',
      'Cystic fibrosis',
      'Sex determination',
      'Evolution',
      'Natural selection',
      'Evidence for evolution',
      'Fossils',
      'Antibiotic resistance',
      'Classification',
      'Binomial system',
      'Three-domain system',
      'Selective breeding',
      'Genetic engineering',
      'GM organisms',
      'Biodiversity',
      'Human impact on biodiversity',
      'Conservation',
      'Sampling techniques',
      'Quadrats',
      'Transects',
    ],
  },

  // ============================================================================
  // CHEMISTRY TOPICS (C1-C6)
  // ============================================================================
  {
    id: 'ocr-combined-chemistry-particles',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Particles',
    description: 'Atomic structure and the periodic table',
    icon: '⚛️',
    color: 'bg-blue-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C1: Particles
      'Structure of an atom',
      'Subatomic particles',
      'Protons',
      'Neutrons',
      'Electrons',
      'Atomic number',
      'Mass number',
      'Electronic configuration',
      'Electron shells',
      'Isotopes',
      'Relative atomic mass',
      'Development of the periodic table',
      'Mendeleev',
      'Modern periodic table',
      'Groups and periods',
      'Electron configuration and groups',
      'Metals and non-metals',
      'Group 1 - Alkali metals',
      'Properties of alkali metals',
      'Reactions of alkali metals',
      'Trends in Group 1',
      'Group 7 - Halogens',
      'Properties of halogens',
      'Reactions of halogens',
      'Displacement reactions',
      'Trends in Group 7',
      'Group 0 - Noble gases',
      'Properties of noble gases',
    ],
  },
  {
    id: 'ocr-combined-chemistry-elements-compounds',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Elements, Compounds and Mixtures',
    description: 'Bonding, structure, and separating mixtures',
    icon: '🔗',
    color: 'bg-purple-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C2: Elements, Compounds and Mixtures
      'Elements',
      'Compounds',
      'Mixtures',
      'Ionic bonding',
      'Formation of ions',
      'Ionic compounds',
      'Giant ionic structures',
      'Properties of ionic compounds',
      'Covalent bonding',
      'Simple molecules',
      'Properties of simple molecules',
      'Giant covalent structures',
      'Diamond',
      'Graphite',
      'Silicon dioxide',
      'Graphene',
      'Fullerenes',
      'Carbon nanotubes',
      'Metallic bonding',
      'Properties of metals',
      'Alloys',
      'Separation techniques',
      'Filtration',
      'Crystallisation',
      'Distillation',
      'Fractional distillation',
      'Chromatography',
      'Rf values',
    ],
  },
  {
    id: 'ocr-combined-chemistry-chemical-reactions',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Chemical Reactions',
    description: 'Reactions of acids, oxidation and reduction',
    icon: '🧪',
    color: 'bg-orange-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C3: Chemical Reactions
      'Chemical equations',
      'Balancing equations',
      'Conservation of mass',
      'Acids and alkalis',
      'pH scale',
      'Indicators',
      'Neutralisation',
      'Reactions with metals',
      'Reactions with metal oxides',
      'Reactions with metal hydroxides',
      'Reactions with metal carbonates',
      'Making salts',
      'Strong and weak acids (H)',
      'Reactivity series',
      'Displacement reactions',
      'Extraction of metals',
      'Reduction with carbon',
      'Oxidation and reduction',
      'OILRIG',
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Anode and cathode',
      'Electrolysis of molten compounds',
      'Electrolysis of solutions',
      'Half equations (H)',
    ],
  },
  {
    id: 'ocr-combined-chemistry-predicting',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Predicting and Identifying Reactions',
    description: 'Rates of reaction and energy changes',
    icon: '⏱️',
    color: 'bg-yellow-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C4: Predicting and Identifying Reactions
      'Rate of reaction',
      'Measuring rate',
      'Factors affecting rate',
      'Temperature',
      'Concentration',
      'Surface area',
      'Catalysts',
      'Collision theory',
      'Activation energy',
      'Exothermic reactions',
      'Endothermic reactions',
      'Reaction profiles',
      'Bond energies (H)',
      'Calculating energy changes (H)',
      'Reversible reactions',
      'Dynamic equilibrium (H)',
      'Le Chatelier\'s principle (H)',
      'Identifying ions',
      'Flame tests',
      'Testing for carbonates',
      'Testing for halides',
      'Testing for sulfates',
      'Testing for gases',
    ],
  },
  {
    id: 'ocr-combined-chemistry-quantitative',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Monitoring and Controlling Reactions',
    description: 'Moles, concentrations, and yields',
    icon: '⚖️',
    color: 'bg-green-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C5: Monitoring and Controlling Reactions
      'Relative formula mass',
      'The mole',
      'Avogadro\'s number',
      'Mole calculations',
      'Reacting masses',
      'Limiting reactants',
      'Concentration',
      'Concentration in g/dm\u00B3',
      'Concentration in mol/dm\u00B3 (H)',
      'Percentage yield',
      'Atom economy',
      'Titrations (H)',
    ],
  },
  {
    id: 'ocr-combined-chemistry-global-challenges',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Global Challenges - Chemistry',
    description: 'Earth\'s resources, atmosphere, and organic chemistry',
    icon: '🌍',
    color: 'bg-teal-500',
    paperRestriction: 'Chemistry Paper',
    subtopics: [
      // C6: Global Challenges
      'Crude oil',
      'Hydrocarbons',
      'Alkanes',
      'Fractional distillation',
      'Combustion',
      'Complete combustion',
      'Incomplete combustion',
      'Carbon monoxide',
      'Particulates',
      'Cracking',
      'Alkenes',
      'Testing for alkenes',
      'Addition polymers',
      'Plastics',
      'Earth\'s atmosphere',
      'Evolution of atmosphere',
      'Greenhouse gases',
      'Carbon dioxide',
      'Methane',
      'Climate change',
      'Global warming',
      'Pollution',
      'Sulfur dioxide',
      'Acid rain',
      'Nitrogen oxides',
      'Natural resources',
      'Sustainable development',
      'Recycling',
      'Life cycle assessment',
      'Potable water',
      'Water treatment',
    ],
  },

  // ============================================================================
  // PHYSICS TOPICS (P1-P6)
  // ============================================================================
  {
    id: 'ocr-combined-physics-matter',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Matter',
    description: 'Particle model, density, and changes of state',
    icon: '🔬',
    color: 'bg-purple-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P1: Matter
      'The particle model',
      'States of matter',
      'Particle arrangement',
      'Particle motion',
      'Density',
      'Density equation (\u03C1 = m/V)',
      'Measuring density',
      'Changes of state',
      'Melting and freezing',
      'Boiling and condensing',
      'Internal energy',
      'Kinetic energy of particles',
      'Potential energy of particles',
      'Temperature',
      'Specific heat capacity',
      'Calculating energy (E = mc\u0394\u03B8)',
      'Specific latent heat',
      'Latent heat of fusion',
      'Latent heat of vaporisation',
      'Calculating latent heat (E = mL)',
      'Pressure in gases',
      'Gas pressure and volume (H)',
      'Gas pressure and temperature (H)',
    ],
  },
  {
    id: 'ocr-combined-physics-forces',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Forces',
    description: 'Motion, Newton\'s laws, and forces',
    icon: '🏋️',
    color: 'bg-red-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P2: Forces
      'Speed',
      'Distance and time',
      'Average speed',
      'Velocity',
      'Distance-time graphs',
      'Velocity-time graphs',
      'Acceleration',
      'Acceleration calculations',
      'Forces',
      'Contact forces',
      'Non-contact forces',
      'Gravity',
      'Weight (W = mg)',
      'Resultant forces',
      'Free body diagrams',
      'Newton\'s First Law',
      'Newton\'s Second Law (F = ma)',
      'Newton\'s Third Law',
      'Stopping distance',
      'Thinking distance',
      'Braking distance',
      'Work done (W = Fs)',
      'Hooke\'s Law (F = ke)',
      'Elastic potential energy',
      'Momentum (H)',
      'Conservation of momentum (H)',
      'Terminal velocity',
    ],
  },
  {
    id: 'ocr-combined-physics-electricity',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Electricity',
    description: 'Current, voltage, resistance, and circuits',
    icon: '🔌',
    color: 'bg-blue-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P3: Electricity
      'Electric current',
      'Charge (Q = It)',
      'Potential difference',
      'Resistance',
      'Ohm\'s Law (V = IR)',
      'Factors affecting resistance',
      'I-V characteristics',
      'Resistors',
      'Filament lamps',
      'Diodes',
      'LDRs',
      'Thermistors',
      'Series circuits',
      'Parallel circuits',
      'Electrical power (P = IV)',
      'Power (P = I\u00B2R)',
      'Energy transferred (E = Pt)',
      'Energy transferred (E = QV)',
      'AC and DC',
      'Mains electricity',
      'Three-core cable',
      'Fuses',
      'Circuit breakers',
      'National Grid',
      'Step-up transformers',
      'Step-down transformers',
      'Transformer equation (H)',
    ],
  },
  {
    id: 'ocr-combined-physics-magnetism',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Magnetism and Magnetic Fields',
    description: 'Magnets, electromagnets, and the motor effect',
    icon: '🧲',
    color: 'bg-indigo-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P4: Magnetism and Magnetic Fields
      'Poles of magnets',
      'Magnetic materials',
      'Permanent magnets',
      'Induced magnetism',
      'Magnetic fields',
      'Field lines',
      'Earth\'s magnetic field',
      'Electromagnets',
      'Solenoids',
      'Uses of electromagnets',
      'Motor effect',
      'Force on a current-carrying wire',
      'Fleming\'s left-hand rule',
      'Force calculation (F = BIL) (H)',
      'Electric motors',
      'Electromagnetic induction (H)',
      'Generators (H)',
    ],
  },
  {
    id: 'ocr-combined-physics-waves',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Waves in Matter',
    description: 'Wave properties, sound, and light',
    icon: '🌊',
    color: 'bg-cyan-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P5: Waves in Matter
      'Transverse waves',
      'Longitudinal waves',
      'Wave properties',
      'Amplitude',
      'Wavelength',
      'Frequency',
      'Period',
      'Wave speed (v = f\u03BB)',
      'Measuring wave speed',
      'Reflection',
      'Refraction',
      'Sound waves',
      'Human hearing range',
      'Ultrasound',
      'Electromagnetic spectrum',
      'Types of EM waves',
      'Properties of EM waves',
      'Uses of EM waves',
      'Hazards of EM waves',
      'Comparing EM waves',
    ],
  },
  {
    id: 'ocr-combined-physics-radioactivity',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Radioactivity',
    description: 'Nuclear structure, radiation, and nuclear reactions',
    icon: '⚛️',
    color: 'bg-green-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P6: Radioactivity
      'Atomic structure',
      'Development of atomic model',
      'Plum pudding model',
      'Rutherford scattering',
      'Bohr model',
      'Isotopes',
      'Nuclear notation',
      'Radioactive decay',
      'Alpha decay',
      'Beta decay',
      'Gamma radiation',
      'Neutron radiation',
      'Properties of radiation',
      'Penetrating power',
      'Ionising ability',
      'Nuclear equations',
      'Half-life',
      'Background radiation',
      'Uses of radiation',
      'Medical uses',
      'Industrial uses',
      'Hazards of radiation',
      'Nuclear fission',
      'Chain reactions',
      'Nuclear reactors',
      'Nuclear fusion',
      'Stars and fusion',
    ],
  },
  {
    id: 'ocr-combined-physics-energy',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'combined-science',
    name: 'Energy',
    description: 'Energy stores, transfers, and resources',
    icon: '⚡',
    color: 'bg-yellow-500',
    paperRestriction: 'Physics Paper',
    subtopics: [
      // P7: Energy
      'Energy stores',
      'Kinetic energy store',
      'Gravitational potential energy store',
      'Chemical energy store',
      'Elastic potential energy store',
      'Thermal energy store',
      'Nuclear energy store',
      'Energy transfers',
      'Conservation of energy',
      'Kinetic energy (KE = \u00BDmv\u00B2)',
      'Gravitational potential energy (GPE = mgh)',
      'Elastic potential energy (E = \u00BDke\u00B2)',
      'Power (P = E/t)',
      'Efficiency',
      'Wasted energy',
      'Reducing energy dissipation',
      'Energy resources',
      'Renewable resources',
      'Non-renewable resources',
      'Solar power',
      'Wind power',
      'Hydroelectric power',
      'Tidal power',
      'Geothermal energy',
      'Biomass',
      'Fossil fuels',
      'Nuclear power',
      'Environmental impact',
    ],
  },
];

export function getOCRCombinedScienceTopicById(id: string): Topic | undefined {
  return ocrCombinedScienceTopics.find((topic) => topic.id === id);
}

export function countOCRCombinedScienceSubtopics(): number {
  return ocrCombinedScienceTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
