// AQA GCSE Chemistry (8462) Topics
// Complete specification coverage
// Paper 1: Topics 1-5 (Atomic structure to Energy changes)
// Paper 2: Topics 6-10 (Rates to Using resources)

import { Topic } from '@/types';

export const aqaChemistryTopics: Topic[] = [
  // ==========================================
  // PAPER 1 TOPICS
  // ==========================================

  // Topic 1: Atomic Structure and the Periodic Table
  {
    id: 'aqa-gcse-chemistry-atomic-structure',
    name: 'Atomic Structure and the Periodic Table',
    description: 'Atoms, elements, compounds, mixtures, and the development of the periodic table',
    icon: '⚛️',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.1.1 A simple model of the atom
      'Atoms, elements and compounds',
      'Structure of an atom',
      'Protons, neutrons and electrons',
      'Atomic number and mass number',
      'Electronic structure',
      'Electron shells',
      'Electron configuration notation',
      'Isotopes',
      'Relative atomic mass',
      'Calculating relative atomic mass from isotopes',
      // 4.1.2 The periodic table
      'Development of the periodic table',
      'Mendeleev\'s periodic table',
      'The modern periodic table',
      'Periods and groups',
      'Metals and non-metals',
      'Electronic structure and the periodic table',
      // 4.1.3 Properties of transition metals (HT)
      'Transition metals',
      'Properties of transition metals',
      'Transition metal compounds',
      'Catalytic properties of transition metals',
      // Group 0: Noble gases
      'Group 0 - The noble gases',
      'Properties of noble gases',
      'Unreactivity of noble gases',
      'Uses of noble gases',
      'Boiling points of noble gases',
      // Group 1: Alkali metals
      'Group 1 - The alkali metals',
      'Properties of alkali metals',
      'Reactions with water',
      'Reactions with oxygen',
      'Reactions with chlorine',
      'Trends in Group 1 reactivity',
      // Group 7: Halogens
      'Group 7 - The halogens',
      'Properties of halogens',
      'Physical states of halogens',
      'Colours of halogens',
      'Reactions with metals',
      'Halide ion tests',
      'Displacement reactions of halogens',
      'Trends in Group 7 reactivity',
    ],
  },

  // Topic 2: Bonding, Structure and Properties of Matter
  {
    id: 'aqa-gcse-chemistry-bonding',
    name: 'Bonding, Structure and Properties of Matter',
    description: 'Chemical bonds, types of structure, and properties of materials',
    icon: '🔗',
    color: 'bg-purple-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.2.1 Chemical bonds
      'Chemical bonds',
      'Ionic bonding',
      'Formation of ions',
      'Dot and cross diagrams for ionic compounds',
      'Ionic compounds',
      'Covalent bonding',
      'Single covalent bonds',
      'Double covalent bonds',
      'Dot and cross diagrams for covalent molecules',
      'Metallic bonding',
      'Structure of metals',
      'Delocalised electrons',
      // 4.2.2 Properties of substances
      'Properties of ionic compounds',
      'Giant ionic lattices',
      'Melting and boiling points of ionic compounds',
      'Electrical conductivity of ionic compounds',
      'Properties of small molecules',
      'Weak intermolecular forces',
      'Strong covalent bonds within molecules',
      'Melting and boiling points of covalent molecules',
      'Polymers',
      'Properties of polymers',
      'Giant covalent structures',
      'Diamond structure and properties',
      'Graphite structure and properties',
      'Silicon dioxide structure',
      'Graphene',
      'Properties of graphene',
      'Fullerenes',
      'Buckminsterfullerene (C60)',
      'Carbon nanotubes',
      'Properties of metals',
      'Malleability and ductility',
      'Electrical and thermal conductivity of metals',
      'Alloys',
      'Properties of alloys',
      // 4.2.3 Structure and bonding of carbon
      'Allotropes of carbon',
      'Comparing diamond and graphite',
      'Uses of carbon allotropes',
      // 4.2.4 Bulk and surface properties (HT)
      'Bulk properties of matter',
      'Nanoparticles',
      'Surface area to volume ratio',
      'Properties of nanoparticles',
      'Uses of nanoparticles',
      'Risks of nanoparticles',
    ],
  },

  // Topic 3: Quantitative Chemistry
  {
    id: 'aqa-gcse-chemistry-quantitative',
    name: 'Quantitative Chemistry',
    description: 'Conservation of mass, moles, concentrations, and yield calculations',
    icon: '⚖️',
    color: 'bg-green-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.3.1 Conservation of mass
      'Conservation of mass',
      'Balancing chemical equations',
      'Relative formula mass (Mr)',
      'Calculating relative formula mass',
      // 4.3.2 Amount of substance
      'The mole',
      'Avogadro constant',
      'Calculating moles from mass',
      'Calculating mass from moles',
      'Moles and balanced equations',
      'Reacting mass calculations',
      'Limiting reactants',
      'Excess reactants',
      // 4.3.3 Concentrations of solutions
      'Concentration in g/dm³',
      'Calculating concentration',
      'Calculating mass from concentration',
      'Calculating volume from concentration',
      'Concentration in mol/dm³ (HT)',
      'Converting between concentration units (HT)',
      // 4.3.4 Use of amount of substance (HT)
      'Molar volume of gases (HT)',
      'Volume of gases at RTP (HT)',
      'Calculating volumes of gases (HT)',
      // 4.3.5 Percentage yield and atom economy
      'Percentage yield',
      'Calculating percentage yield',
      'Reasons for less than 100% yield',
      'Atom economy',
      'Calculating atom economy',
      'Importance of atom economy',
      'Choosing reaction pathways',
    ],
  },

  // Topic 4: Chemical Changes
  {
    id: 'aqa-gcse-chemistry-chemical-changes',
    name: 'Chemical Changes',
    description: 'Reactivity, extraction of metals, reactions of acids, and electrolysis',
    icon: '🧪',
    color: 'bg-orange-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.4.1 Reactivity of metals
      'Metal oxides and the reactivity series',
      'The reactivity series',
      'Reactions of metals with water',
      'Reactions of metals with acids',
      'Displacement reactions',
      'Oxidation and reduction (redox)',
      'Oxidation as gain of oxygen',
      'Reduction as loss of oxygen',
      'Oxidation as loss of electrons (HT)',
      'Reduction as gain of electrons (HT)',
      // 4.4.2 Extraction of metals
      'Extraction of metals and reduction',
      'Extraction using carbon',
      'Extraction of unreactive metals',
      'Extraction of aluminium by electrolysis',
      'Biological methods of extraction',
      'Phytoextraction',
      'Bioleaching',
      'Recycling metals',
      // 4.4.3 Reactions of acids
      'Acids and alkalis',
      'The pH scale',
      'Indicators',
      'Neutralisation reactions',
      'Reactions of acids with metals',
      'Reactions of acids with metal oxides',
      'Reactions of acids with metal hydroxides',
      'Reactions of acids with metal carbonates',
      'Making soluble salts',
      'Crystallisation',
      'Strong and weak acids (HT)',
      'Hydrogen ion concentration (HT)',
      'pH of strong and weak acids (HT)',
      // 4.4.4 Electrolysis
      'Electrolysis',
      'Electrolytes',
      'Electrodes',
      'Anode and cathode',
      'Products at electrodes',
      'Electrolysis of molten compounds',
      'Electrolysis of aqueous solutions',
      'Electrolysis of aqueous sodium chloride',
      'Products at electrodes in aqueous solutions (HT)',
      'Half equations (HT)',
      'Extraction of aluminium by electrolysis',
      'Electrolysis of copper sulfate solution',
      'Purification of copper',
    ],
  },

  // Topic 5: Energy Changes
  {
    id: 'aqa-gcse-chemistry-energy',
    name: 'Energy Changes',
    description: 'Exothermic and endothermic reactions, reaction profiles, and bond energies',
    icon: '🔥',
    color: 'bg-red-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.5.1 Exothermic and endothermic reactions
      'Energy transfer in reactions',
      'Exothermic reactions',
      'Examples of exothermic reactions',
      'Endothermic reactions',
      'Examples of endothermic reactions',
      'Measuring temperature changes',
      'Reaction profiles for exothermic reactions',
      'Reaction profiles for endothermic reactions',
      'Activation energy',
      'Effect of catalysts on reaction profiles',
      // 4.5.2 Bond energy calculations (HT)
      'Bond energies (HT)',
      'Energy to break bonds (HT)',
      'Energy released when bonds form (HT)',
      'Calculating energy change from bond energies (HT)',
      'Explaining exothermic reactions using bond energies (HT)',
      'Explaining endothermic reactions using bond energies (HT)',
      // 4.5.3 Chemical cells and fuel cells (HT)
      'Chemical cells (HT)',
      'Voltage of chemical cells (HT)',
      'Non-rechargeable cells (HT)',
      'Rechargeable cells (HT)',
      'Hydrogen fuel cells (HT)',
      'Advantages of fuel cells (HT)',
      'Disadvantages of fuel cells (HT)',
    ],
  },

  // ==========================================
  // PAPER 2 TOPICS
  // ==========================================

  // Topic 6: The Rate and Extent of Chemical Change
  {
    id: 'aqa-gcse-chemistry-rates',
    name: 'The Rate and Extent of Chemical Change',
    description: 'Rates of reaction, factors affecting rate, and reversible reactions',
    icon: '⏱️',
    color: 'bg-yellow-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.6.1 Rate of reaction
      'Rate of reaction',
      'Measuring rate of reaction',
      'Mean rate of reaction',
      'Calculating rate from graphs',
      'Factors affecting rate of reaction',
      'Effect of concentration on rate',
      'Effect of pressure on rate (gases)',
      'Effect of surface area on rate',
      'Effect of temperature on rate',
      'Effect of catalysts on rate',
      // 4.6.2 Collision theory
      'Collision theory',
      'Activation energy and collisions',
      'Explaining concentration effect',
      'Explaining surface area effect',
      'Explaining temperature effect',
      'Explaining catalyst effect',
      // 4.6.3 Catalysts
      'Catalysts',
      'How catalysts work',
      'Catalysts in industry',
      'Enzymes as biological catalysts',
      // 4.6.4 Reversible reactions (HT)
      'Reversible reactions',
      'Dynamic equilibrium (HT)',
      'Closed systems (HT)',
      'Le Chatelier\'s principle (HT)',
      'Effect of temperature on equilibrium (HT)',
      'Effect of pressure on equilibrium (HT)',
      'Effect of concentration on equilibrium (HT)',
      'Optimising industrial reactions (HT)',
    ],
  },

  // Topic 7: Organic Chemistry
  {
    id: 'aqa-gcse-chemistry-organic',
    name: 'Organic Chemistry',
    description: 'Crude oil, hydrocarbons, alkanes, alkenes, and reactions of organic compounds',
    icon: '🛢️',
    color: 'bg-gray-700',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.7.1 Carbon compounds as fuels and feedstock
      'Crude oil',
      'Hydrocarbons',
      'Fractional distillation of crude oil',
      'Fractions from crude oil',
      'Properties of hydrocarbon fractions',
      'Uses of hydrocarbon fractions',
      'Alkanes',
      'General formula of alkanes',
      'Displayed formulae of alkanes',
      'Structural formulae of alkanes',
      'Combustion of hydrocarbons',
      'Complete combustion',
      'Incomplete combustion',
      'Carbon monoxide',
      'Particulates (soot)',
      'Cracking',
      'Thermal cracking',
      'Catalytic cracking',
      'Products of cracking',
      // 4.7.2 Reactions of alkenes and alcohols
      'Alkenes',
      'General formula of alkenes',
      'The C=C double bond',
      'Displayed formulae of alkenes',
      'Structural formulae of alkenes',
      'Addition reactions of alkenes',
      'Addition polymerisation',
      'Polymers from alkenes',
      'Poly(ethene)',
      'Poly(propene)',
      'Alcohols',
      'Functional group of alcohols',
      'General formula of alcohols',
      'Properties of alcohols',
      'Combustion of alcohols',
      'Reactions of alcohols with sodium',
      'Oxidation of alcohols',
      'Uses of alcohols',
      'Carboxylic acids',
      'Functional group of carboxylic acids',
      'Properties of carboxylic acids',
      'Reactions of carboxylic acids',
      'Esters',
      'Formation of esters',
      'Uses of esters',
      // 4.7.3 Synthetic and naturally occurring polymers
      'Condensation polymerisation (HT)',
      'Amino acids and proteins (HT)',
      'DNA structure (HT)',
      'Naturally occurring polymers',
    ],
  },

  // Topic 8: Chemical Analysis
  {
    id: 'aqa-gcse-chemistry-analysis',
    name: 'Chemical Analysis',
    description: 'Purity, formulations, chromatography, and identification of ions',
    icon: '🔬',
    color: 'bg-teal-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.8.1 Purity, formulations and chromatography
      'Pure substances',
      'Melting point of pure substances',
      'Mixtures',
      'Formulations',
      'Examples of formulations',
      'Chromatography',
      'Paper chromatography',
      'Rf values',
      'Calculating Rf values',
      'Identifying substances using chromatography',
      // 4.8.2 Identification of common gases
      'Test for hydrogen',
      'Test for oxygen',
      'Test for carbon dioxide',
      'Test for chlorine',
      // 4.8.3 Identification of ions
      'Flame tests',
      'Flame test colours',
      'Identifying metal ions using flame tests',
      'Metal hydroxide precipitates',
      'Testing for carbonate ions',
      'Testing for halide ions',
      'Testing for sulfate ions',
      'Instrumental methods (HT)',
      'Advantages of instrumental methods (HT)',
      'Flame emission spectroscopy (HT)',
    ],
  },

  // Topic 9: Chemistry of the Atmosphere
  {
    id: 'aqa-gcse-chemistry-atmosphere',
    name: 'Chemistry of the Atmosphere',
    description: 'Composition and evolution of the atmosphere, climate change, and pollutants',
    icon: '🌍',
    color: 'bg-cyan-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.9.1 The composition and evolution of Earth's atmosphere
      'Composition of the atmosphere',
      'Proportions of gases in the atmosphere',
      'Evolution of the atmosphere',
      'Early atmosphere',
      'Volcanic activity and gases',
      'Formation of oceans',
      'Development of life',
      'Photosynthesis and oxygen',
      'Formation of fossil fuels',
      'Formation of sedimentary rocks',
      // 4.9.2 Carbon dioxide and methane as greenhouse gases
      'Greenhouse gases',
      'Carbon dioxide as a greenhouse gas',
      'Methane as a greenhouse gas',
      'Water vapour as a greenhouse gas',
      'The greenhouse effect',
      'Global warming',
      'Climate change',
      'Evidence for climate change',
      'Effects of climate change',
      'Reducing carbon dioxide emissions',
      'Carbon capture and storage',
      'Carbon footprint',
      // 4.9.3 Atmospheric pollutants
      'Atmospheric pollutants from fuels',
      'Carbon monoxide',
      'Sulfur dioxide',
      'Nitrogen oxides',
      'Particulates',
      'Acid rain',
      'Effects of acid rain',
      'Global dimming',
    ],
  },

  // Topic 10: Using Resources
  {
    id: 'aqa-gcse-chemistry-resources',
    name: 'Using Resources',
    description: 'Earth\'s resources, water treatment, life cycle assessments, and recycling',
    icon: '♻️',
    color: 'bg-emerald-500',
    examBoard: 'aqa',
    qualification: 'gcse',
    subject: 'chemistry',
    subtopics: [
      // 4.10.1 Using Earth's resources
      'Natural resources',
      'Sustainable development',
      'Finite and renewable resources',
      'Agriculture and food production',
      // 4.10.2 Potable water
      'Potable water',
      'Drinking water',
      'Water treatment',
      'Sedimentation',
      'Filtration',
      'Chlorination',
      'Sterilisation',
      'Desalination',
      'Distillation',
      'Reverse osmosis',
      'Sewage treatment',
      'Aerobic and anaerobic digestion',
      // 4.10.3 Alternative methods of extracting metals (HT)
      'Phytomining (HT)',
      'Bioleaching (HT)',
      // 4.10.4 Life cycle assessment
      'Life cycle assessment (LCA)',
      'Extracting raw materials',
      'Manufacturing and packaging',
      'Use and disposal',
      'Comparing LCAs',
      'Limitations of LCAs',
      'Reducing use of resources',
      'Reusing materials',
      'Recycling materials',
      // 4.10.5 Ways of reducing the use of resources
      'Recycling metals',
      'Recycling glass',
      'Recycling plastics',
      'Biodegradable materials',
      'Compostable materials',
      // 4.10.6 The Haber process and NPK fertilisers
      'The Haber process',
      'Conditions for the Haber process',
      'Reversible reaction in the Haber process',
      'Choosing conditions for the Haber process',
      'NPK fertilisers',
      'Production of fertilisers',
      'Ammonia in fertiliser production',
      'Phosphate rock in fertiliser production',
      'Potassium compounds in fertiliser production',
    ],
  },
];

export function getAQAChemistryTopicById(id: string): Topic | undefined {
  return aqaChemistryTopics.find(topic => topic.id === id);
}
