// NEW Simplified Edexcel A-Level Economics Topics
// Designed to match UI display names exactly and ensure proper topic lookup
import { Topic } from '@/types';

export const edexcelALevelEconomicsTopics: Topic[] = [
  // MICROECONOMICS TOPICS
  {
    id: 'nature-of-economics',
    examBoard: 'edexcel',
    name: 'Nature of Economics',
    description: 'Economics as a social science, positive and normative economics',
    icon: '📚',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Economics as a social science',
      'Positive statements',
      'Normative statements',
      'The role of value judgements',
      'Ceteris paribus',
      'Economic modelling',
      'Scarcity and opportunity cost',
    ],
  },
  
  {
    id: 'how-markets-work',
    examBoard: 'edexcel',
    name: 'How Markets Work',
    description: 'Demand, supply, price determination, and elasticities',
    icon: '📈',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Demand curves',
      'Supply curves', 
      'Market equilibrium',
      'Price elasticity of demand',
      'Price elasticity of supply',
      'Income elasticity of demand',
      'Cross elasticity of demand',
      'Consumer surplus',
      'Producer surplus',
    ],
  },

  {
    id: 'market-failure',
    examBoard: 'edexcel',
    name: 'Market Failure',
    description: 'Externalities, public goods, monopoly power, and information gaps',
    icon: '⚠️',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Externalities',
      'Public goods',
      'Merit goods',
      'Demerit goods',
      'Information gaps',
      'Monopoly power',
      'Government intervention',
      'Market failure evaluation',
    ],
  },

  // MACROECONOMICS TOPICS
  {
    id: 'measures-of-economic-performance',
    examBoard: 'edexcel', 
    name: 'Measures of Economic Performance',
    description: 'GDP, inflation, unemployment, and balance of payments',
    icon: '📊',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Gross domestic product (GDP)',
      'Real and nominal GDP',
      'GDP per capita',
      'Inflation measurement',
      'Consumer Price Index (CPI)',
      'Unemployment types',
      'Balance of payments',
      'Economic growth measurement',
    ],
  },

  {
    id: 'aggregate-demand',
    examBoard: 'edexcel',
    name: 'Aggregate Demand',
    description: 'Components of AD and factors affecting aggregate demand',
    icon: '📉',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Consumption (C)',
      'Investment (I)',
      'Government spending (G)',
      'Net exports (X-M)',
      'AD curve',
      'Factors affecting consumption',
      'Factors affecting investment',
      'Multiplier effect',
    ],
  },

  {
    id: 'aggregate-supply',
    examBoard: 'edexcel',
    name: 'Aggregate Supply', 
    description: 'Short-run and long-run aggregate supply',
    icon: '⬆️',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Short-run aggregate supply (SRAS)',
      'Long-run aggregate supply (LRAS)',
      'AS curve shifts',
      'Production costs',
      'Productivity',
      'Technology improvements',
      'Labour market changes',
      'Supply-side policies',
    ],
  },

  {
    id: 'national-income',
    examBoard: 'edexcel',
    name: 'National Income',
    description: 'Circular flow, injections and leakages, equilibrium',
    icon: '💹',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Circular flow of income',
      'Injections and leakages',
      'Marginal propensity to consume',
      'Marginal propensity to save',
      'National income equilibrium',
      'Output gaps',
      'Economic cycle',
      'Income distribution',
    ],
  },

  {
    id: 'economic-growth',
    examBoard: 'edexcel',
    name: 'Economic Growth',
    description: 'Causes and consequences of economic growth',
    icon: '🚀',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Actual vs potential growth',
      'Production possibility frontier',
      'Factors of production',
      'Productivity growth',
      'Innovation and technology',
      'Human capital',
      'Benefits of growth',
      'Costs of growth',
    ],
  },

  {
    id: 'macroeconomic-objectives-and-policies',
    examBoard: 'edexcel',
    name: 'Macroeconomic Objectives and Policies',
    description: 'Government objectives and policy tools',
    icon: '🎯',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Economic growth objectives',
      'Price stability',
      'Low unemployment',
      'Balance of payments equilibrium',
      'Fiscal policy',
      'Monetary policy',
      'Supply-side policies',
      'Policy conflicts and trade-offs',
    ],
  },

  // BUSINESS ECONOMICS TOPICS  
  {
    id: 'business-growth',
    examBoard: 'edexcel',
    name: 'Business Growth',
    description: 'Reasons for and types of business growth',
    icon: '📈',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Reasons for growth',
      'Organic growth',
      'Inorganic growth',
      'Horizontal integration',
      'Vertical integration',
      'Conglomerate mergers',
      'Public vs private sector',
      'Privatisation',
    ],
  },

  {
    id: 'business-objectives',
    examBoard: 'edexcel',
    name: 'Business Objectives',
    description: 'Profit maximisation and alternative objectives',
    icon: '🎯',
    color: 'bg-lime-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Profit maximisation',
      'Revenue maximisation',
      'Sales maximisation',
      'Satisficing',
      'Corporate social responsibility',
      'Principal-agent problem',
      'Divorce of ownership and control',
      'Stakeholder objectives',
    ],
  },

  {
    id: 'revenues-costs-and-profits',
    examBoard: 'edexcel',
    name: 'Revenues, Costs and Profits',
    description: 'Revenue, cost and profit analysis for firms',
    icon: '💰',
    color: 'bg-emerald-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Total revenue (TR)',
      'Average revenue (AR)',
      'Marginal revenue (MR)',
      'Fixed costs',
      'Variable costs',
      'Total costs (TC)',
      'Average costs (AC)',
      'Marginal costs (MC)',
      'Profit calculation',
      'Economies and diseconomies of scale',
    ],
  },

  {
    id: 'market-structures',
    examBoard: 'edexcel',
    name: 'Market Structures',
    description: 'Perfect competition, monopoly, monopolistic competition, oligopoly',
    icon: '🏢',
    color: 'bg-violet-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Perfect competition',
      'Monopolistic competition',
      'Oligopoly',
      'Monopoly',
      'Barriers to entry',
      'Price discrimination',
      'Game theory',
      'Contestable markets',
      'Market concentration',
    ],
  },

  // LABOUR AND INTERNATIONAL TOPICS
  {
    id: 'the-labour-market',
    examBoard: 'edexcel',
    name: 'The Labour Market',
    description: 'Labour demand, supply, and wage determination',
    icon: '👷',
    color: 'bg-slate-500',
    paperRestriction: 'Paper 1, Paper 3',
    subtopics: [
      'Demand for labour',
      'Supply of labour',
      'Wage determination',
      'Trade unions',
      'Monopsony',
      'Labour market imperfections',
      'Unemployment types',
      'Labour mobility',
    ],
  },

  {
    id: 'international-economics',
    examBoard: 'edexcel',
    name: 'International Economics',
    description: 'International trade, exchange rates, and globalisation',
    icon: '🌍',
    color: 'bg-blue-600',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Absolute advantage',
      'Comparative advantage',
      'Free trade benefits',
      'Protectionism',
      'Tariffs and quotas',
      'Exchange rates',
      'Balance of payments',
      'Globalisation',
      'Economic integration',
    ],
  },

  {
    id: 'poverty-and-inequality',
    examBoard: 'edexcel',
    name: 'Poverty and Inequality',
    description: 'Income distribution, poverty measurement, and policies',
    icon: '⚖️',
    color: 'bg-red-600',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Absolute poverty',
      'Relative poverty',
      'Income inequality',
      'Lorenz curve',
      'Gini coefficient',
      'Causes of inequality',
      'Government redistribution',
      'Welfare policies',
    ],
  },

  {
    id: 'emerging-and-developing-economies',
    examBoard: 'edexcel',
    name: 'Emerging and Developing Economies',
    description: 'Development indicators, growth strategies, and challenges',
    icon: '🌱',
    color: 'bg-green-600',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Human Development Index',
      'GDP per capita',
      'Development indicators',
      'Growth vs development',
      'Primary product dependency',
      'Foreign aid',
      'Foreign direct investment',
      'Debt issues',
    ],
  },

  {
    id: 'the-financial-sector',
    examBoard: 'edexcel',
    name: 'The Financial Sector',
    description: 'Financial markets, institutions, and regulation',
    icon: '🏦',
    color: 'bg-purple-600',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Role of financial markets',
      'Money and banking',
      'Central banks',
      'Commercial banks',
      'Market failure in finance',
      'Financial regulation',
      'Moral hazard',
      'Systemic risk',
    ],
  },

  {
    id: 'role-of-the-state-in-the-macroeconomy',
    examBoard: 'edexcel',
    name: 'Role of the State in the Macroeconomy',
    description: 'Government intervention, public finance, and macroeconomic policy',
    icon: '🏛️',
    color: 'bg-gray-600',
    paperRestriction: 'Paper 2, Paper 3',
    subtopics: [
      'Public expenditure',
      'Taxation',
      'Government borrowing',
      'Budget deficits and surpluses',
      'National debt',
      'Fiscal policy effectiveness',
      'Automatic stabilisers',
      'Crowding out',
    ],
  },
];

// Helper function to get a topic by ID
export function getEdexcelALevelEconomicsTopicById(id: string) {
  return edexcelALevelEconomicsTopics.find(topic => topic.id === id);
}

export default edexcelALevelEconomicsTopics;