// Edexcel GCSE Business (1BS0) Topics
// Based on the official Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/business-2017.html
// Paper 1: Investigating Small Business (50%) - Theme 1
// Paper 2: Building a Business (50%) - Theme 2

import { Topic } from '@/types';

export const edexcelGCSEBusinessTopics: Topic[] = [
  // ============================================================================
  // THEME 1: INVESTIGATING SMALL BUSINESS
  // Assessed in Paper 1
  // ============================================================================
  {
    id: 'enterprise-entrepreneurship',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Enterprise and Entrepreneurship',
    description: 'The dynamic nature of business, risk and reward, and the role of business enterprise',
    icon: '🚀',
    color: 'bg-blue-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.1.1 The dynamic nature of business
      'Dynamic nature of business',
      'Why new business ideas come about',
      'Changes in technology',
      'Changes in consumer wants',
      'Products and services',
      'How new business ideas come about',
      'Original ideas',
      'Adapting existing ideas',
      // 1.1.2 Risk and reward
      'Risk',
      'Business risk',
      'Financial risk',
      'Business failure',
      'Causes of business failure',
      'Reward',
      'Business success',
      'Profit',
      'Independence',
      'Business satisfaction',
      'Balancing risk and reward',
      // 1.1.3 The role of business enterprise
      'Enterprise',
      'Entrepreneurs',
      'Role of entrepreneurs',
      'Identifying opportunities',
      'Organising resources',
      'Making business decisions',
      'Purpose of business activity',
      'Producing goods',
      'Providing services',
      'Meeting customer needs',
      'Adding value',
      'Methods of adding value',
      'Convenience',
      'Branding',
      'Quality',
      'Design',
      'Unique selling point (USP)',
    ],
  },
  {
    id: 'spotting-opportunity',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Spotting a Business Opportunity',
    description: 'Customer needs, market research, and market segmentation',
    icon: '🔍',
    color: 'bg-green-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.2.1 Customer needs
      'Customer needs',
      'Understanding customer needs',
      'Price',
      'Quality',
      'Choice',
      'Convenience',
      'Market research',
      'Purpose of market research',
      'Identifying customer needs',
      'Identifying gaps in the market',
      'Reducing risk',
      'Informing business decisions',
      // 1.2.2 Market research
      'Primary research',
      'Methods of primary research',
      'Surveys',
      'Questionnaires',
      'Focus groups',
      'Observation',
      'Advantages of primary research',
      'Disadvantages of primary research',
      'Secondary research',
      'Methods of secondary research',
      'Internet research',
      'Market reports',
      'Government statistics',
      'Advantages of secondary research',
      'Disadvantages of secondary research',
      'Qualitative data',
      'Uses of qualitative data',
      'Quantitative data',
      'Uses of quantitative data',
      'Reliability of data',
      // 1.2.3 Market segmentation
      'Market segmentation',
      'Segmenting a market',
      'Location',
      'Demographics',
      'Age',
      'Gender',
      'Income',
      'Lifestyle',
      'Benefits of market segmentation',
      'Target market',
      'Market mapping',
      'Identifying market gaps',
      'Competitor positioning',
    ],
  },
  {
    id: 'putting-idea-into-practice',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Putting a Business Idea into Practice',
    description: 'Business aims and objectives, revenue, costs, profit, and cash flow',
    icon: '📋',
    color: 'bg-purple-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.3.1 Business aims and objectives
      'Business aims',
      'Business objectives',
      'Financial objectives',
      'Survival',
      'Profit',
      'Sales',
      'Market share',
      'Financial security',
      'Non-financial objectives',
      'Social objectives',
      'Personal satisfaction',
      'Challenge',
      'Independence',
      'Control',
      'Why objectives differ',
      'Nature of business',
      'Size of business',
      // 1.3.2 Business revenues, costs and profits
      'Revenue',
      'Calculating revenue',
      'Revenue formula',
      'Total revenue',
      'Fixed costs',
      'Examples of fixed costs',
      'Rent',
      'Salaries',
      'Insurance',
      'Variable costs',
      'Examples of variable costs',
      'Raw materials',
      'Stock',
      'Wages',
      'Total costs',
      'Calculating total costs',
      'Interest',
      'Interest on loans',
      'Profit',
      'Calculating profit',
      'Profit formula',
      'Gross profit',
      'Net profit',
      'Importance of profit',
      'Loss',
      'Break-even',
      'Break-even calculation',
      'Break-even formula',
      'Break-even point',
      'Contribution',
      'Contribution per unit',
      'Break-even charts',
      'Drawing break-even charts',
      'Interpreting break-even charts',
      'Margin of safety',
      'Uses of break-even',
      'Limitations of break-even',
      // 1.3.3 Cash and cash flow
      'Cash',
      'Importance of cash',
      'Cash vs profit',
      'Cash flow',
      'Cash inflows',
      'Sources of cash inflows',
      'Cash outflows',
      'Types of cash outflows',
      'Net cash flow',
      'Cash flow forecasts',
      'Structure of cash flow forecast',
      'Opening balance',
      'Closing balance',
      'Purpose of cash flow forecasts',
      'Cash flow problems',
      'Causes of cash flow problems',
      'Low sales',
      'High costs',
      'Poor credit control',
      'Solutions to cash flow problems',
      'Increasing cash inflows',
      'Reducing cash outflows',
      'Finding finance',
    ],
  },
  {
    id: 'making-business-effective',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Making the Business Effective',
    description: 'Business ownership, business location, and the marketing mix',
    icon: '⚙️',
    color: 'bg-orange-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.4.1 The options for start-up and small businesses
      'Business ownership',
      'Sole traders',
      'Characteristics of sole traders',
      'Advantages of sole traders',
      'Disadvantages of sole traders',
      'Partnerships',
      'Characteristics of partnerships',
      'Advantages of partnerships',
      'Disadvantages of partnerships',
      'Deed of partnership',
      'Limited liability',
      'Unlimited liability',
      'Private limited companies (Ltd)',
      'Characteristics of Ltd',
      'Advantages of Ltd',
      'Disadvantages of Ltd',
      'Shareholders',
      'Share capital',
      'Franchising',
      'Franchisor',
      'Franchisee',
      'Advantages of franchising',
      'Disadvantages of franchising',
      // 1.4.2 Business location
      'Business location',
      'Factors affecting location',
      'Proximity to market',
      'Proximity to materials',
      'Proximity to labour',
      'Proximity to competitors',
      'Costs',
      'E-commerce',
      'Impact of e-commerce',
      'Fixed vs flexible premises',
      // 1.4.3 The marketing mix
      'Marketing mix',
      '4Ps',
      'Product',
      'Product design',
      'Form',
      'Function',
      'Cost',
      'Aesthetics',
      'Price',
      'Pricing strategies',
      'Price skimming',
      'Price penetration',
      'Competitive pricing',
      'Cost-plus pricing',
      'Promotion',
      'Types of promotion',
      'Advertising',
      'Sponsorship',
      'Product trials',
      'Special offers',
      'Branding',
      'Brand image',
      'Importance of branding',
      'Place',
      'Distribution channels',
      'Retailers',
      'E-tailers',
      'Direct selling',
    ],
  },
  {
    id: 'external-influences',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Understanding External Influences',
    description: 'Stakeholders, technology, legislation, and the economy',
    icon: '🌐',
    color: 'bg-red-500',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 1.5.1 Business stakeholders
      'Stakeholders',
      'Types of stakeholders',
      'Owners',
      'Employees',
      'Customers',
      'Local community',
      'Suppliers',
      'Pressure groups',
      'Government',
      'Stakeholder needs',
      'Conflicting stakeholder needs',
      'Stakeholder impact',
      // 1.5.2 Technology and business
      'Technology',
      'Impact of technology',
      'E-commerce',
      'Social media',
      'Digital communication',
      'Payment systems',
      'Benefits of technology',
      'Drawbacks of technology',
      // 1.5.3 Legislation and business
      'Legislation',
      'Consumer law',
      'Consumer Rights Act',
      'Impact of consumer law',
      'Employment law',
      'Recruitment legislation',
      'Pay and working hours',
      'Health and safety',
      'Impact of employment law',
      // 1.5.4 The economy and business
      'The economy',
      'Economic climate',
      'Unemployment',
      'Effects of unemployment',
      'Consumer spending',
      'Effects of consumer spending changes',
      'Inflation',
      'Effects of inflation',
      'Interest rates',
      'Effects of interest rate changes',
      'Exchange rates',
      'Impact on importers',
      'Impact on exporters',
      'Government',
      'Taxation',
      'Income tax',
      'National Insurance',
      'VAT',
      'Corporation tax',
      'Impact of taxation',
    ],
  },

  // ============================================================================
  // THEME 2: BUILDING A BUSINESS
  // Assessed in Paper 2
  // ============================================================================
  {
    id: 'growing-business',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Growing the Business',
    description: 'Business growth, changes in business aims, globalisation, and ethics',
    icon: '📈',
    color: 'bg-teal-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.1.1 Business growth
      'Business growth',
      'Methods of growth',
      'Internal growth',
      'Organic growth',
      'Advantages of organic growth',
      'Disadvantages of organic growth',
      'External growth',
      'Mergers',
      'Takeovers',
      'Types of integration',
      'Horizontal integration',
      'Vertical integration',
      'Forward vertical integration',
      'Backward vertical integration',
      'Advantages of integration',
      'Disadvantages of integration',
      'Public limited companies (PLC)',
      'Advantages of PLC',
      'Disadvantages of PLC',
      'Stock exchange',
      'Flotation',
      'Sources of finance for growth',
      'Internal sources',
      'Retained profit',
      'Selling assets',
      'External sources',
      'Loans',
      'Share capital',
      'Venture capital',
      'Crowdfunding',
      // 2.1.2 Changes in business aims and objectives
      'Changing aims',
      'Focus on survival',
      'Focus on growth',
      'Focus on profit',
      'Focus on market share',
      'Responding to change',
      'Market conditions',
      'Technology changes',
      'Competitor actions',
      'Legislation changes',
      // 2.1.3 Business and globalisation
      'Globalisation',
      'What is globalisation',
      'International trade',
      'Imports',
      'Exports',
      'Barriers to international trade',
      'Tariffs',
      'Trading blocs',
      'Impact of globalisation',
      'Competition from abroad',
      'New markets',
      'Global sourcing',
      'Multinational corporations',
      // 2.1.4 Ethics, the environment and business
      'Business ethics',
      'Ethical considerations',
      'Fair treatment of workers',
      'Fair treatment of suppliers',
      'Honest marketing',
      'Environmental considerations',
      'Sustainability',
      'Carbon footprint',
      'Pollution',
      'Waste management',
      'Recycling',
      'Trade-offs',
      'Profit vs ethics',
      'Short-term vs long-term',
      'Pressure groups',
      'Impact of pressure groups',
    ],
  },
  {
    id: 'making-marketing-decisions',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Making Marketing Decisions',
    description: 'Product, price, promotion, and place decisions for growing businesses',
    icon: '📊',
    color: 'bg-pink-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.2.1 Product
      'Product',
      'Product life cycle',
      'Development stage',
      'Introduction stage',
      'Growth stage',
      'Maturity stage',
      'Decline stage',
      'Extension strategies',
      'Product modification',
      'New markets',
      'New uses',
      'Rebranding',
      'Product differentiation',
      'USP (Unique Selling Point)',
      'Product portfolio',
      'Boston Matrix',
      'Stars',
      'Cash cows',
      'Question marks',
      'Problem children',
      'Dogs',
      'Using Boston Matrix',
      // 2.2.2 Price
      'Price',
      'Pricing strategies',
      'Cost-plus pricing',
      'Competitive pricing',
      'Psychological pricing',
      'Penetration pricing',
      'Price skimming',
      'Factors affecting pricing',
      'Costs',
      'Competition',
      'Target market',
      'Nature of product',
      'Product life cycle stage',
      'Technology impact on pricing',
      'Price comparison websites',
      // 2.2.3 Promotion
      'Promotion',
      'Promotional mix',
      'Advertising',
      'Above the line promotion',
      'Below the line promotion',
      'Sales promotion',
      'Discounts',
      'BOGOF',
      'Competitions',
      'Loyalty schemes',
      'Sponsorship',
      'Public relations',
      'Product placement',
      'Social media marketing',
      'Viral marketing',
      'Targeted advertising',
      'Technology and promotion',
      'Digital marketing',
      // 2.2.4 Place
      'Place',
      'Distribution channels',
      'Choosing distribution channels',
      'Retailers',
      'Wholesalers',
      'Direct selling',
      'E-commerce',
      'M-commerce',
      'Multi-channel distribution',
      'Changing distribution',
      'Technology impact on distribution',
    ],
  },
  {
    id: 'making-operational-decisions',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Making Operational Decisions',
    description: 'Business operations, working with suppliers, managing quality, and the sales process',
    icon: '🏭',
    color: 'bg-indigo-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.3.1 Business operations
      'Operations',
      'Production processes',
      'Job production',
      'Advantages of job production',
      'Disadvantages of job production',
      'Batch production',
      'Advantages of batch production',
      'Disadvantages of batch production',
      'Flow production',
      'Advantages of flow production',
      'Disadvantages of flow production',
      'Choosing production method',
      'Factors affecting choice',
      'Nature of product',
      'Demand',
      'Resources',
      'Productivity',
      'Measuring productivity',
      'Improving productivity',
      'Technology and productivity',
      'Automation',
      // 2.3.2 Working with suppliers
      'Suppliers',
      'Role of suppliers',
      'Choosing suppliers',
      'Price',
      'Quality',
      'Reliability',
      'Flexibility',
      'Supplier relationships',
      'Procurement',
      'Stock management',
      'Managing stock',
      'Stock control',
      'Just-in-time (JIT)',
      'Advantages of JIT',
      'Disadvantages of JIT',
      'Just-in-case',
      'Advantages of holding stock',
      'Disadvantages of holding stock',
      'Bar gate stock graphs',
      'Lead time',
      'Buffer stock',
      'Reorder level',
      'Maximum stock level',
      // 2.3.3 Managing quality
      'Quality',
      'Importance of quality',
      'Customer expectations',
      'Reputation',
      'Quality control',
      'Inspecting finished products',
      'Advantages of quality control',
      'Disadvantages of quality control',
      'Quality assurance',
      'Building quality in',
      'Zero defects',
      'Advantages of quality assurance',
      'Total Quality Management (TQM)',
      'Continuous improvement',
      // 2.3.4 The sales process
      'Sales process',
      'Product knowledge',
      'Speed and efficiency',
      'Customer engagement',
      'Post-sales service',
      'Customer service',
      'Importance of customer service',
      'Customer loyalty',
      'Repeat business',
      'Customer feedback',
      'Responding to feedback',
    ],
  },
  {
    id: 'making-financial-decisions',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Making Financial Decisions',
    description: 'Business calculations, understanding business performance, and making financial decisions',
    icon: '💰',
    color: 'bg-yellow-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.4.1 Business calculations
      'Gross profit',
      'Calculating gross profit',
      'Gross profit formula',
      'Net profit',
      'Calculating net profit',
      'Net profit formula',
      'Gross profit margin',
      'Calculating gross profit margin',
      'Gross profit margin formula',
      'Net profit margin',
      'Calculating net profit margin',
      'Net profit margin formula',
      'Average rate of return (ARR)',
      'Calculating ARR',
      'ARR formula',
      'Interpreting ARR',
      // 2.4.2 Understanding business performance
      'Quantitative data',
      'Financial data',
      'Sales data',
      'Market research data',
      'Interpreting data',
      'Graphs and charts',
      'Limitations of data',
      'Qualitative data',
      'Customer feedback',
      'Employee opinions',
      'Using qualitative data',
      'Limitations of qualitative data',
      // 2.4.3 Making financial decisions
      'Financial decisions',
      'Sources of finance',
      'Short-term finance',
      'Overdraft',
      'Trade credit',
      'Long-term finance',
      'Loans',
      'Share capital',
      'Venture capital',
      'Retained profit',
      'Sale of assets',
      'Crowdfunding',
      'Choosing finance',
      'Purpose of finance',
      'Amount needed',
      'Cost of finance',
      'Risk involved',
    ],
  },
  {
    id: 'making-human-resource-decisions',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'business',
    name: 'Making Human Resource Decisions',
    description: 'Organisational structure, recruitment, training, and motivation',
    icon: '👥',
    color: 'bg-cyan-500',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 2.5.1 Organisational structures
      'Organisational structure',
      'Hierarchy',
      'Span of control',
      'Wide span of control',
      'Narrow span of control',
      'Chain of command',
      'Levels of hierarchy',
      'Tall structures',
      'Advantages of tall structures',
      'Disadvantages of tall structures',
      'Flat structures',
      'Advantages of flat structures',
      'Disadvantages of flat structures',
      'Centralisation',
      'Advantages of centralisation',
      'Disadvantages of centralisation',
      'Decentralisation',
      'Advantages of decentralisation',
      'Disadvantages of decentralisation',
      // 2.5.2 Effective recruitment
      'Recruitment',
      'Recruitment process',
      'Identifying vacancies',
      'Writing job descriptions',
      'Creating person specifications',
      'Internal recruitment',
      'Advantages of internal recruitment',
      'Disadvantages of internal recruitment',
      'External recruitment',
      'Advantages of external recruitment',
      'Disadvantages of external recruitment',
      'Recruitment methods',
      'Job adverts',
      'Recruitment agencies',
      'Headhunting',
      'Online recruitment',
      'Selection',
      'Application forms',
      'CVs',
      'Interviews',
      'References',
      'Tests and assessments',
      // 2.5.3 Effective training and development
      'Training',
      'Purpose of training',
      'Induction training',
      'On-the-job training',
      'Advantages of on-the-job training',
      'Disadvantages of on-the-job training',
      'Off-the-job training',
      'Advantages of off-the-job training',
      'Disadvantages of off-the-job training',
      'Benefits of training',
      'Employee skills',
      'Productivity',
      'Staff retention',
      'Costs of training',
      // 2.5.4 Motivation
      'Motivation',
      'Importance of motivation',
      'Productivity',
      'Quality',
      'Staff retention',
      'Financial motivation',
      'Remuneration',
      'Wages',
      'Time rate',
      'Piece rate',
      'Salaries',
      'Commission',
      'Bonus',
      'Profit sharing',
      'Performance-related pay',
      'Non-financial motivation',
      'Job rotation',
      'Job enrichment',
      'Autonomy',
      'Recognition',
      'Working environment',
      'Fringe benefits',
    ],
  },
];

// Helper function to get topic by ID
export function getEdexcelGCSEBusinessTopicById(id: string): Topic | undefined {
  return edexcelGCSEBusinessTopics.find(topic => topic.id === id);
}
