// Edexcel GCSE Psychology Topics (1PS0)
// Based on official Pearson Edexcel specification
// Reference: https://qualifications.pearson.com/en/qualifications/edexcel-gcses/psychology-2017.html

import { Topic } from '@/types';

export const edexcelGCSEPsychologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: COGNITION AND BEHAVIOUR (55%)
  // ============================================================================
  {
    id: 'development',
    name: 'Development',
    description: 'Brain development, nature vs nurture, and educational applications',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Early brain development
      'Early brain development',
      'Role of nature in brain development',
      'Role of nurture in brain development',
      'Brain plasticity',
      // Piaget's stages
      "Piaget's stage theory",
      'Key features of Piaget',
      'Sensorimotor stage (0-2)',
      'Object permanence',
      'Pre-operational stage (2-7)',
      'Egocentrism',
      'Conservation',
      'Class inclusion',
      'Concrete operational stage (7-11)',
      'Formal operational stage (11+)',
      'Abstract reasoning',
      // Evaluation of Piaget
      "Strengths of Piaget's theory",
      "Weaknesses of Piaget's theory",
      'Application to education',
      // Hughes and McGarrigle studies
      "Hughes's policeman doll study",
      "McGarrigle and Donaldson's naughty teddy",
      'Criticisms of Piaget',
      // Dweck's mindset theory
      "Dweck's mindset theory",
      'Fixed mindset characteristics',
      'Growth mindset characteristics',
      'Effect of praise on mindset',
      'Person praise vs process praise',
      'Application to education',
      "Evaluation of Dweck's theory",
      // Willingham's learning theory
      "Willingham's learning theory",
      'Memory is residue of thought',
      'Why factual knowledge is important',
      'How practice helps learning',
      'Application to teaching',
      "Evaluation of Willingham's theory",
    ],
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'How memory works, models of memory, and forgetting',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Information processing
      'Memory as information processing',
      'Encoding',
      'Storage',
      'Retrieval',
      // Multi-store model
      'Multi-store model of memory',
      'Sensory register',
      'Short-term memory',
      'Long-term memory',
      'Duration of each store',
      'Capacity of each store',
      'Coding in each store',
      'Transfer between stores',
      'Evaluation of multi-store model',
      // Key research
      "Peterson and Peterson's duration study",
      "Jacobs's digit span study",
      "Bahrick et al.'s yearbook study",
      "Baddeley's encoding study",
      // Murdock's serial position study
      "Murdock's (1962) serial position study",
      'Procedure',
      'Primacy effect findings',
      'Recency effect findings',
      'Conclusions about memory stores',
      'Evaluation of study',
      // Types of LTM
      'Episodic memory',
      'Semantic memory',
      'Procedural memory',
      // Forgetting
      'Theories of forgetting',
      'Interference theory',
      'Proactive interference',
      'Retroactive interference',
      'Retrieval failure',
      'Context-dependent forgetting',
      // Bartlett's study
      "Bartlett's War of the Ghosts study",
      'Procedure of the study',
      'Findings on memory distortion',
      'Role of schemas',
      'Reconstructive memory',
      'Evaluation of Bartlett',
    ],
  },
  {
    id: 'psychological-problems',
    name: 'Psychological Problems',
    description: 'Mental health issues, causes and treatments of depression and addiction',
    icon: '🩺',
    color: 'bg-red-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Mental health
      'Understanding of mental health',
      'Mental health continuum',
      'Prevalence of mental health problems',
      'Effects on individual',
      'Effects on family/friends',
      'Effects on society',
      // Effects of mental health problems
      'Stigma and discrimination',
      'Impact on employment',
      'Impact on relationships',
      'Impact on physical health',
      // Depression
      'Characteristics of depression',
      'DSM-5 criteria',
      'Cognitive symptoms',
      'Emotional symptoms',
      'Behavioural symptoms',
      'Physical symptoms',
      // Causes of depression
      'Genetic explanation',
      'Twin studies evidence',
      'Brain chemistry explanation',
      'Role of serotonin',
      'Role of noradrenaline',
      'Cognitive explanation',
      "Beck's negative cognitive triad",
      'Negative view of self',
      'Negative view of world',
      'Negative view of future',
      // Treatments for depression
      'Antidepressant medication',
      'SSRIs: how they work',
      'Effectiveness of medication',
      'Side effects',
      'Cognitive Behavioural Therapy (CBT)',
      'How CBT works',
      'Challenging negative thoughts',
      'Behavioural activation',
      'Effectiveness of CBT',
      // Addiction
      'Definition of addiction',
      'Physical dependence',
      'Psychological dependence',
      'Tolerance',
      'Withdrawal symptoms',
      // Causes of addiction
      'Genetic explanation',
      'Dopamine reward system',
      'Peer pressure',
      'Social learning',
      'Personality factors',
      // Treatments for addiction
      'Drug therapy',
      'Cognitive Behavioural Therapy',
      'Functional analysis',
      'Skills training',
      'Relapse prevention',
      'Aversion therapy',
      'Principles of aversion therapy',
      'Effectiveness of treatments',
    ],
  },
  {
    id: 'brain-neuropsychology',
    name: 'The Brain and Neuropsychology',
    description: 'Structure and function of the brain and how damage affects behaviour',
    icon: '🔬',
    color: 'bg-green-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Structure of nervous system
      'The nervous system',
      'Central nervous system',
      'Brain',
      'Spinal cord',
      'Peripheral nervous system',
      'Somatic nervous system',
      'Autonomic nervous system',
      // Brain structure
      'Structure of the brain',
      'Cerebral hemispheres',
      'Frontal lobe',
      'Motor area',
      "Broca's area",
      'Temporal lobe',
      "Wernicke's area",
      'Parietal lobe',
      'Occipital lobe',
      'Visual cortex',
      'Cerebellum',
      // Neurons
      'Neuron structure',
      'Cell body',
      'Dendrites',
      'Axon',
      'Myelin sheath',
      'Types of neurons',
      'Sensory neurons',
      'Motor neurons',
      'Relay neurons',
      // Synaptic transmission
      'Synaptic transmission',
      'Neurotransmitters',
      'Synaptic gap',
      'Receptors',
      // Brain damage
      'Effects of brain damage',
      'Phineas Gage case study',
      'The accident',
      'Changes in personality',
      'Damage to frontal lobe',
      'Conclusions about brain function',
      'Evaluation of case study',
      // Methods of studying brain
      'Brain scanning techniques',
      'CT scans',
      'PET scans',
      'fMRI scans',
      'Strengths of scanning',
      'Limitations of scanning',
    ],
  },
  {
    id: 'social-influence',
    name: 'Social Influence',
    description: 'How others affect our behaviour including conformity, obedience, and crowds',
    icon: '👥',
    color: 'bg-blue-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Conformity
      'Definition of conformity',
      'Types of conformity',
      'Informational social influence',
      'Normative social influence',
      // Asch's study
      "Asch's (1951) conformity study",
      'Aim of the study',
      'Procedure: line judgment task',
      'Role of confederates',
      'Findings: 75% conformed at least once',
      'Conclusions about conformity',
      'Factors affecting conformity',
      'Group size',
      'Unanimity',
      'Task difficulty',
      'Private vs public answers',
      "Evaluation of Asch's study",
      // Obedience
      'Definition of obedience',
      'Difference from conformity',
      // Milgram's study
      "Milgram's (1963) obedience study",
      'Aim of the study',
      'Procedure: electric shocks',
      'Role of learner and experimenter',
      'Verbal prods used',
      'Findings: 65% obeyed fully',
      'Explanations of findings',
      'Evaluation of Milgram',
      'Ethical issues',
      // Factors affecting obedience
      'Proximity variations',
      'Location variations',
      'Uniform variations',
      // Agency theory
      'Agency theory of obedience',
      'Agentic state',
      'Autonomous state',
      'Moral strain',
      'Evaluation of agency theory',
      // Bickman's study
      "Bickman's (1974) field study",
      'Procedure: uniform conditions',
      'Findings on obedience',
      'Conclusions about authority',
      // Crowd and collective behaviour
      'Crowd behaviour',
      'Deindividuation',
      'Anonymity',
      'Le Bon and crowds',
      'Prosocial crowds',
      'Antisocial crowds',
    ],
  },

  // ============================================================================
  // PAPER 2: SOCIAL AND COGNITIVE PSYCHOLOGY (45%)
  // Section B is optional topics
  // ============================================================================
  {
    id: 'research-methods',
    name: 'Research Methods',
    description: 'How psychologists conduct research and analyse data',
    icon: '📊',
    color: 'bg-yellow-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Hypotheses
      'Hypotheses in research',
      'Alternative hypothesis',
      'Null hypothesis',
      'Directional (one-tailed) hypothesis',
      'Non-directional (two-tailed) hypothesis',
      // Variables
      'Variables in research',
      'Independent variable (IV)',
      'Dependent variable (DV)',
      'Extraneous variables',
      'Control of variables',
      'Operationalisation',
      // Types of research
      'Laboratory experiments',
      'Strengths of lab experiments',
      'Weaknesses of lab experiments',
      'Field experiments',
      'Strengths of field experiments',
      'Weaknesses of field experiments',
      'Natural experiments',
      'Questionnaires',
      'Open vs closed questions',
      'Interviews',
      'Structured interviews',
      'Unstructured interviews',
      'Observations',
      'Naturalistic vs controlled',
      'Participant vs non-participant',
      'Covert vs overt',
      'Case studies',
      'Correlations',
      // Experimental design
      'Independent groups design',
      'Repeated measures design',
      'Matched pairs design',
      'Strengths and weaknesses of each',
      'Order effects',
      'Counterbalancing',
      // Sampling
      'Target population',
      'Sample',
      'Random sampling',
      'Opportunity sampling',
      'Stratified sampling',
      'Evaluation of sampling methods',
      // Data types
      'Quantitative data',
      'Qualitative data',
      'Primary data',
      'Secondary data',
      // Analysis
      'Measures of central tendency',
      'Mean, median, mode',
      'Measures of spread',
      'Range',
      'Graphs and charts',
      'Bar charts',
      'Histograms',
      'Scatter diagrams',
      // Evaluation
      'Reliability',
      'Validity',
      'Ecological validity',
      'Generalisability',
      // Ethics
      'Ethical guidelines',
      'Informed consent',
      'Deception',
      'Protection from harm',
      'Right to withdraw',
      'Confidentiality',
      'Privacy',
    ],
  },

  // OPTIONAL TOPICS (Choose 2 from Sections B-F)
  {
    id: 'criminal',
    name: 'Criminal Psychology',
    description: 'Why do people become criminals? Biological, social and psychological factors',
    icon: '🔍',
    color: 'bg-gray-600',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // What is crime?
      'Defining criminal behaviour',
      'Types of crime',
      'Measuring crime',
      // Biological explanations
      'Biological explanations of crime',
      'Genetic factors',
      'Twin studies',
      'Adoption studies',
      'Brain structure',
      'Limbic system',
      'Prefrontal cortex',
      // Raine et al. study
      "Raine et al.'s (1997) brain study",
      'Aim: brain differences in murderers',
      'Sample: NGRIs',
      'Procedure: PET scans',
      'Findings: prefrontal differences',
      'Limbic system differences',
      'Conclusions',
      'Evaluation of study',
      // Psychological explanations
      "Eysenck's criminal personality",
      'Extraversion',
      'Neuroticism',
      'Psychoticism',
      'Link to crime',
      'Cognitive explanations',
      'Moral reasoning',
      'Cognitive distortions',
      // Social explanations
      'Social learning theory',
      "Sutherland's differential association",
      'Labelling theory',
      'Poverty and crime',
      // Treating offenders
      'Aims of punishment',
      'Deterrence',
      'Incapacitation',
      'Rehabilitation',
      'Prison',
      'Community sentences',
      'Token economy programmes',
      'Anger management',
      'Restorative justice',
    ],
  },
  {
    id: 'self',
    name: 'The Self',
    description: 'What makes you who you are? Self-concept, personality and free will',
    icon: '🪞',
    color: 'bg-violet-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Self-concept
      'Self-concept definition',
      'Self-image',
      'Self-esteem',
      'Ideal self',
      'Development of self-concept',
      'Role of others',
      'Social comparison',
      // Humanistic theory
      'Humanistic approach',
      "Rogers's self theory",
      'Self-actualisation',
      'Conditions of worth',
      'Congruence',
      'Unconditional positive regard',
      "Maslow's hierarchy of needs",
      // Free will
      'Free will vs determinism',
      'Humanistic view of free will',
      'Personal agency',
      // Self-report measures
      'Van Dalen study on self-concept',
      // Personality
      'Trait theories',
      "Eysenck's personality types",
      'Extraversion-Introversion',
      'Neuroticism-Stability',
      'Psychoticism',
      'Big Five personality traits',
      'Openness',
      'Conscientiousness',
      'Extraversion',
      'Agreeableness',
      'Neuroticism',
      // Cattell's research
      "Cattell's 16PF",
      'Factor analysis',
      'Surface traits',
      'Source traits',
    ],
  },
  {
    id: 'perception',
    name: 'Perception',
    description: 'How do you interpret the world around you? Visual perception and illusions',
    icon: '👁️',
    color: 'bg-cyan-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Sensation vs perception
      'Sensation vs perception',
      'Visual perception',
      // Depth cues
      'Monocular depth cues',
      'Height in plane',
      'Relative size',
      'Occlusion',
      'Linear perspective',
      'Texture gradient',
      'Binocular depth cues',
      'Retinal disparity',
      'Convergence',
      // Visual constancies
      'Size constancy',
      'Shape constancy',
      // Visual illusions
      'Types of illusion',
      'Distortion illusions',
      'Ponzo illusion',
      'Müller-Lyer illusion',
      'Ambiguous figures',
      'Rubin vase',
      'Necker cube',
      'Fictional illusions',
      'Kanizsa triangle',
      // Theories of perception
      "Gibson's direct perception",
      'Bottom-up processing',
      'Role of environment',
      "Gregory's constructivist theory",
      'Top-down processing',
      'Role of schemas',
      'Perception as hypothesis',
      // Perceptual set
      'Factors affecting perception',
      'Motivation',
      'Expectation',
      'Culture',
      'Emotion',
      // Haber and Levin study
      'Research on visual perception',
      'Individual differences',
    ],
  },
  {
    id: 'sleep-dreaming',
    name: 'Sleep and Dreaming',
    description: 'Why do you need to sleep and dream? Sleep stages and theories of dreaming',
    icon: '😴',
    color: 'bg-indigo-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Sleep stages
      'Stages of sleep',
      'Stage 1 (light sleep)',
      'Stage 2',
      'Stage 3 (deep sleep)',
      'Stage 4 (deepest sleep)',
      'REM sleep',
      'Sleep cycle',
      'Characteristics of each stage',
      'Brain waves: alpha, beta, theta, delta',
      // Functions of sleep
      'Why we sleep',
      'Restoration theory',
      'Physical restoration',
      'Psychological restoration',
      'Memory consolidation',
      'Evolutionary theory',
      'Sleep deprivation',
      // Internal and external factors
      'Circadian rhythms',
      'Body clock',
      'Role of light',
      'Melatonin',
      // Sleep disorders
      'Insomnia',
      'Causes of insomnia',
      'Treatment of insomnia',
      'Narcolepsy',
      'Sleep apnoea',
      // Dreaming
      'Characteristics of dreams',
      'When we dream',
      'Content of dreams',
      // Theories of dreaming
      "Freud's theory of dreaming",
      'Manifest content',
      'Latent content',
      'Wish fulfilment',
      'Dream work',
      "Evaluation of Freud's theory",
      'Activation-synthesis theory',
      'Hobson and McCarley',
      'Random neural activity',
      'Brain interpretation',
      'Evaluation of activation-synthesis',
    ],
  },
  {
    id: 'language',
    name: 'Language, Thought and Communication',
    description: 'How do you communicate with others? Verbal and non-verbal communication',
    icon: '💬',
    color: 'bg-emerald-500',
    examBoard: 'edexcel',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2 Option',
    subtopics: [
      // Language and thought
      "Piaget's theory",
      'Thought develops first',
      'Language depends on thought',
      'Sapir-Whorf hypothesis',
      'Linguistic relativity',
      'Strong version',
      'Weak version',
      'Evidence for Sapir-Whorf',
      // Non-verbal communication
      'Functions of NVC',
      'Eye contact',
      'Functions of eye contact',
      'Cultural variations',
      'Body language',
      'Open posture',
      'Closed posture',
      'Postural echo',
      'Personal space',
      'Factors affecting personal space',
      'Facial expressions',
      'Ekman: universal expressions',
      'Touch',
      'Paralinguistics',
      'Tone',
      'Pitch',
      'Volume',
      // Animal communication
      'Human vs animal communication',
      'Properties of language',
      "Von Frisch's bee study",
      'Waggle dance',
      'Round dance',
      'Evaluation of study',
      // Yuki et al. study
      "Yuki et al.'s emoticon study",
      'Cross-cultural differences',
      'Eyes vs mouth focus',
    ],
  },
];

export function getEdexcelGCSEPsychologyTopicById(id: string): Topic | undefined {
  return edexcelGCSEPsychologyTopics.find((topic) => topic.id === id);
}
