// OCR GCSE Psychology Topics (J203)
// Based on official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/psychology-j203-from-2017/

import { Topic } from '@/types';

export const ocrGCSEPsychologyTopics: Topic[] = [
  // ============================================================================
  // PAPER 1: STUDIES AND APPLICATIONS IN PSYCHOLOGY 1 (50%)
  // Criminal Psychology, Development, Psychological Problems, Research Methods
  // ============================================================================
  {
    id: 'ocr-gcse-psych-criminal',
    name: 'Criminal Psychology',
    description: 'What makes a criminal? Biological, cognitive and social explanations',
    icon: '🔍',
    color: 'bg-gray-600',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // What makes a criminal?
      'Definition of crime',
      'Criminal behaviour',
      'Antisocial behaviour',
      // Biological explanations
      'Brain injury and crime',
      'Role of the amygdala',
      'Role of prefrontal cortex',
      'Genetic explanations',
      // Core study: Raine et al. (1997)
      "Raine et al.'s (1997) brain study",
      'Aim: brain abnormalities in murderers',
      'Background: NGRI pleas',
      'Sample: 41 murderers, 41 controls',
      'Procedure: PET scanning',
      'Glucose metabolic activity',
      'Findings: prefrontal cortex differences',
      'Limbic system findings',
      'Conclusions about brain and crime',
      'Evaluation of Raine study',
      'Strengths of PET scanning',
      'Limitations of sample',
      // Social learning theory
      'Social learning theory of crime',
      'Bandura: observational learning',
      'Role models',
      'Vicarious reinforcement',
      'Media influence on crime',
      // Cognitive explanations
      'Cognitive distortions',
      'Hostile attribution bias',
      'Minimisation',
      'Moral reasoning',
      "Kohlberg's stages",
      // Punishment and reform
      'Aims of punishment',
      'Retribution',
      'Deterrence',
      'Rehabilitation',
      'Effectiveness of punishment',
      'Token economy programmes',
      // Applications
      'Anger management',
      'Restorative justice',
    ],
  },
  {
    id: 'ocr-gcse-psych-development',
    name: 'Development',
    description: 'Early brain development, Piaget, and learning theories',
    icon: '👶',
    color: 'bg-pink-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Early brain development
      'Early brain development',
      'Nature vs nurture',
      'Critical periods',
      'Brain plasticity',
      // Piaget's theory
      "Piaget's theory of cognitive development",
      'Key concepts: schemas',
      'Assimilation',
      'Accommodation',
      'Stages of development',
      'Sensorimotor stage (0-2)',
      'Object permanence',
      'Pre-operational stage (2-7)',
      'Egocentrism',
      'Conservation',
      'Animism',
      'Concrete operational (7-11)',
      'Formal operational (11+)',
      // Core study: Piaget's conservation
      "Piaget's conservation study",
      'Background to conservation',
      'Procedure: liquid and number tasks',
      'Findings by age',
      'Conclusions about cognitive development',
      'Evaluation of conservation studies',
      // Criticisms of Piaget
      "Donaldson's criticisms",
      "McGarrigle and Donaldson's naughty teddy",
      'Hughes policeman doll study',
      // Dweck's mindset theory
      "Dweck's mindset theory",
      'Fixed mindset',
      'Growth mindset',
      'Mueller and Dweck study',
      'Effect of praise type',
      'Application to education',
      "Evaluation of Dweck's theory",
      // Willingham's learning theory
      "Willingham's learning theory",
      'Knowledge and skills',
      'Memory is residue of thought',
      'Practice makes permanent',
      'Critique of learning styles',
      'Application to teaching',
      "Evaluation of Willingham's theory",
    ],
  },
  {
    id: 'ocr-gcse-psych-psychological-problems',
    name: 'Psychological Problems',
    description: 'Mental health, depression, addiction, and their treatment',
    icon: '🩺',
    color: 'bg-red-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 1',
    subtopics: [
      // Mental health
      'Mental health awareness',
      'Prevalence of mental health problems',
      'Effects on individuals',
      'Effects on society',
      'Stigma',
      'Challenges of modern living',
      // Defining abnormality
      'Defining abnormality',
      'Statistical infrequency',
      'Deviation from social norms',
      'Failure to function adequately',
      // Depression
      'Characteristics of depression',
      'Cognitive symptoms',
      'Emotional symptoms',
      'Behavioural symptoms',
      'Biological explanation',
      'Brain chemistry: serotonin',
      'Genetic factors',
      'Cognitive explanation',
      "Beck's negative cognitive triad",
      'Negative view of self',
      'Negative view of world',
      'Negative view of future',
      // Treatments for depression
      'Drug therapy for depression',
      'Antidepressants: SSRIs',
      'How SSRIs work',
      'Effectiveness and limitations',
      'Cognitive Behavioural Therapy',
      'How CBT works',
      'Challenging negative thoughts',
      'Effectiveness of CBT',
      // Core study: Becket al.
      'Research on cognitive approach',
      // Addiction
      'Definition of addiction',
      'Physical dependence',
      'Psychological dependence',
      'Tolerance',
      'Withdrawal',
      'Types of addiction',
      // Causes of addiction
      'Biological explanation',
      'Genetic vulnerability',
      'Dopamine reward system',
      'Brain changes',
      'Psychological explanation',
      'Learning theory',
      'Classical conditioning',
      'Operant conditioning',
      'Social learning',
      // Treatment of addiction
      'Drug therapy',
      'Aversion therapy',
      'Principles and procedure',
      'Effectiveness',
      'Cognitive Behavioural Therapy',
      'Effectiveness of CBT for addiction',
    ],
  },

  // ============================================================================
  // PAPER 2: STUDIES AND APPLICATIONS IN PSYCHOLOGY 2 (50%)
  // Social Influence, Memory, Sleep and Dreaming, Research Methods
  // ============================================================================
  {
    id: 'ocr-gcse-psych-social-influence',
    name: 'Social Influence',
    description: 'How others influence behaviour: conformity, obedience, and crowds',
    icon: '👥',
    color: 'bg-blue-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Conformity
      'What is conformity?',
      'Types of conformity',
      'Compliance',
      'Internalisation',
      'Normative social influence',
      'Informational social influence',
      // Asch's study
      "Asch's (1951) line study",
      'Aim of the study',
      'Procedure: standard line task',
      'Role of confederates',
      'Critical trials',
      'Findings: 75% conformed at least once',
      '32% conformity rate overall',
      'Conclusions about conformity',
      'Factors affecting conformity',
      'Group size',
      'Unanimity',
      'Task difficulty',
      'Evaluation of Asch study',
      // Obedience
      'What is obedience?',
      'Difference from conformity',
      // Milgram's study
      "Milgram's (1963) obedience study",
      'Aim of the study',
      'Procedure: teacher-learner setup',
      'Shock generator',
      'Verbal prods',
      'Findings: 65% obeyed fully',
      'Signs of tension',
      'Conclusions about obedience',
      'Factors affecting obedience',
      'Proximity',
      'Location',
      'Uniform',
      'Evaluation of Milgram',
      'Ethical issues',
      // Core study: Bickman (1974)
      "Bickman's (1974) field study",
      'Aim: effect of uniform on obedience',
      'Procedure: three conditions',
      'Guard, milkman, civilian',
      'Tasks: pick up bag, coin, move from bus stop',
      'Findings on obedience rates',
      'Conclusions about legitimacy',
      'Evaluation of Bickman',
      // Explanations of obedience
      'Agency theory',
      'Agentic state',
      'Autonomous state',
      'Moral strain',
      // Collective behaviour
      'Crowd behaviour',
      'Deindividuation',
      'Social identity',
      'Prosocial vs antisocial crowds',
    ],
  },
  {
    id: 'ocr-gcse-psych-memory',
    name: 'Memory',
    description: 'How memory works, why we forget, and eyewitness testimony',
    icon: '🧠',
    color: 'bg-purple-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // How memory works
      'Processes of memory',
      'Encoding',
      'Storage',
      'Retrieval',
      // Structure of memory
      'Multi-store model',
      'Sensory register',
      'Short-term memory',
      'Coding in STM',
      'Capacity of STM',
      'Duration of STM',
      'Long-term memory',
      'Coding in LTM',
      'Capacity of LTM',
      'Duration of LTM',
      'Evaluation of multi-store model',
      // Key research
      'Research on STM duration',
      'Research on STM capacity',
      // Types of LTM
      'Episodic memory',
      'Characteristics of episodic',
      'Semantic memory',
      'Characteristics of semantic',
      'Procedural memory',
      // Forgetting
      'Why we forget',
      'Interference theory',
      'Proactive interference',
      'Retroactive interference',
      'Retrieval failure',
      'Context-dependent forgetting',
      'State-dependent forgetting',
      // Core study: Bartlett (1932)
      "Bartlett's War of the Ghosts study",
      'Aim: reconstructive nature of memory',
      'Procedure: repeated reproduction',
      'Serial reproduction',
      "The story: War of the Ghosts",
      'Findings: distortions',
      'Shortening',
      'Rationalisation',
      'Cultural changes',
      'Conclusions about schemas',
      'Reconstructive memory',
      'Confabulation',
      'Evaluation of Bartlett',
      // Eyewitness testimony
      'Factors affecting EWT',
      'Leading questions',
      'Post-event discussion',
      'Anxiety effects',
      'Cognitive interview',
    ],
  },
  {
    id: 'ocr-gcse-psych-sleep-dreaming',
    name: 'Sleep and Dreaming',
    description: 'Why we sleep, stages of sleep, and theories of dreaming',
    icon: '😴',
    color: 'bg-indigo-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Paper 2',
    subtopics: [
      // Why we sleep
      'Functions of sleep',
      'Physical restoration',
      'Growth hormone',
      'Immune function',
      'Psychological restoration',
      'Memory consolidation',
      'Evolutionary theory',
      'Energy conservation',
      // Stages of sleep
      'Sleep stages overview',
      'Non-REM sleep',
      'Stage 1: light sleep',
      'Alpha and theta waves',
      'Stage 2',
      'Sleep spindles',
      'Stage 3: deep sleep',
      'Stage 4: deepest sleep',
      'Delta waves',
      'REM sleep',
      'Rapid eye movement',
      'Brain activity in REM',
      'Muscle atonia',
      'Sleep cycle',
      '90-minute cycles',
      // Sleep disorders
      'Insomnia',
      'Primary insomnia',
      'Secondary insomnia',
      'Causes of insomnia',
      'Treatment of insomnia',
      // Dreaming
      'What are dreams?',
      'When we dream',
      'Dream content',
      // Core study: Freud
      "Freud's theory of dreaming",
      'Background to psychoanalysis',
      'Role of unconscious',
      'Wish fulfilment',
      'Manifest content',
      'Latent content',
      'Dream work',
      'Condensation',
      'Displacement',
      'Secondary elaboration',
      'Case of Little Hans',
      'Evaluation of Freud',
      'Lack of scientific support',
      // Alternative theory
      'Activation-synthesis theory',
      'Hobson and McCarley',
      'Random brain activity',
      'Brain interpretation',
      'Comparison with Freud',
      'Evaluation of theories',
    ],
  },
  {
    id: 'ocr-gcse-psych-research-methods',
    name: 'Research Methods',
    description: 'How psychologists conduct research and investigate behaviour',
    icon: '📊',
    color: 'bg-yellow-500',
    examBoard: 'ocr',
    qualification: 'gcse',
    subject: 'psychology',
    paperRestriction: 'Papers 1 and 2',
    subtopics: [
      // Research methods
      'Laboratory experiments',
      'Features of lab experiments',
      'Control and manipulation',
      'Strengths of lab experiments',
      'Weaknesses of lab experiments',
      'Field experiments',
      'Natural setting',
      'Strengths of field experiments',
      'Weaknesses of field experiments',
      'Natural experiments',
      'Naturally occurring IV',
      'Observations',
      'Naturalistic observation',
      'Controlled observation',
      'Participant observation',
      'Non-participant observation',
      'Covert vs overt',
      'Questionnaires',
      'Open questions',
      'Closed questions',
      'Interviews',
      'Structured interviews',
      'Unstructured interviews',
      'Case studies',
      // Hypotheses
      'Alternative hypothesis',
      'Null hypothesis',
      'Directional hypothesis',
      'Non-directional hypothesis',
      // Variables
      'Independent variable (IV)',
      'Dependent variable (DV)',
      'Extraneous variables',
      'Operationalisation',
      // Experimental design
      'Independent groups design',
      'Repeated measures design',
      'Matched pairs design',
      'Strengths and weaknesses',
      'Order effects',
      'Counterbalancing',
      // Sampling
      'Target population',
      'Sample',
      'Random sampling',
      'Opportunity sampling',
      'Self-selected sampling',
      'Stratified sampling',
      'Strengths of sampling methods',
      'Weaknesses of sampling methods',
      // Data
      'Types of data',
      'Quantitative data',
      'Qualitative data',
      'Primary data',
      'Secondary data',
      // Analysis
      'Measures of central tendency',
      'Mean',
      'Median',
      'Mode',
      'Measures of spread',
      'Range',
      'Data presentation',
      'Tables',
      'Bar charts',
      'Histograms',
      'Scatter diagrams',
      // Evaluation issues
      'Reliability',
      'Validity',
      'Internal validity',
      'External validity',
      'Ecological validity',
      'Generalisability',
      'Demand characteristics',
      'Social desirability',
      // Ethics
      'Ethical issues',
      'BPS guidelines',
      'Informed consent',
      'Deception',
      'Protection from harm',
      'Right to withdraw',
      'Confidentiality',
      'Privacy',
      'Debriefing',
    ],
  },
];

export function getOCRGCSEPsychologyTopicById(id: string): Topic | undefined {
  return ocrGCSEPsychologyTopics.find((topic) => topic.id === id);
}
