// OCR GCSE English Literature (J352) Topics
// Based on official OCR specification
// Reference: https://www.ocr.org.uk/qualifications/gcse/english-literature-j352-from-2015/

import { Topic } from '@/types';

export const ocrGCSEEnglishLiteratureTopics: Topic[] = [
  // Component 01: Exploring Modern and Literary Heritage Texts
  // Modern Prose or Drama
  {
    id: 'lit-inspector-calls',
    name: 'An Inspector Calls',
    description: 'Priestley\'s powerful drama examining social responsibility in Edwardian England',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Social responsibility',
      'Class divisions',
      'Generational conflict',
      'Morality and hypocrisy',
      'Socialism vs capitalism',
      'Women in society',
      'Inspector\'s function',
      'Arthur Birling\'s views',
      'Sybil\'s prejudice',
      'Sheila\'s awakening',
      'Eric\'s guilt',
      'Gerald\'s complicity',
      'Eva/Daisy\'s story',
      'The twist revelation',
      'Well-made play structure',
      'Time and dramatic tension',
    ],
  },
  {
    id: 'lit-animal-farm',
    name: 'Animal Farm',
    description: 'Orwell\'s satirical fable about power, corruption, and totalitarianism',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Power and its abuse',
      'Revolution betrayed',
      'Propaganda techniques',
      'Class and exploitation',
      'Idealism vs corruption',
      'Violence and terror',
      'Napoleon\'s dictatorship',
      'Snowball as scapegoat',
      'Boxer\'s tragic fate',
      'Squealer\'s rhetoric',
      'The commandments\' erosion',
      'The windmill symbol',
      'Historical parallels',
      'Satire and allegory',
      'Animal perspectives',
      'The final transformation',
    ],
  },
  {
    id: 'lit-never-let-go',
    name: 'Never Let Me Go',
    description: 'Ishiguro\'s dystopian novel exploring humanity, mortality, and what it means to be human',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Identity and humanity',
      'Mortality and purpose',
      'Memory and nostalgia',
      'Love and relationships',
      'Loss and acceptance',
      'Ethics and society',
      'Kathy as narrator',
      'Tommy\'s struggle',
      'Ruth\'s manipulation',
      'Hailsham\'s purpose',
      'The gallery mystery',
      'Donations and completing',
      'The deferral hope',
      'Madame\'s reaction',
      'Unreliable narration',
      'Science fiction elements',
    ],
  },
  // 19th Century Prose
  {
    id: 'lit-christmas-carol-ocr',
    name: 'A Christmas Carol',
    description: 'Dickens\' supernatural tale of transformation and social criticism',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Redemption and salvation',
      'Social injustice',
      'The Christmas spirit',
      'Avarice and generosity',
      'Family and belonging',
      'Time and mortality',
      'Scrooge\'s journey',
      'Marley\'s chains',
      'Spirit of Christmas Past',
      'Spirit of Christmas Present',
      'Spirit of Christmas Yet to Come',
      'The Cratchits',
      'Tiny Tim',
      'Victorian context',
      'Supernatural elements',
      'Narrative voice',
    ],
  },
  {
    id: 'lit-jekyll-hyde-ocr',
    name: 'The Strange Case of Dr Jekyll and Mr Hyde',
    description: 'Stevenson\'s Gothic mystery exploring Victorian double lives',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Duality of man',
      'Good and evil',
      'Victorian repression',
      'Science and morality',
      'Secrecy and society',
      'Reputation\'s importance',
      'Jekyll\'s experiment',
      'Hyde\'s nature',
      'Utterson\'s role',
      'The mysterious door',
      'London setting',
      'Murder and violence',
      'The transformation',
      'The confession',
      'Gothic conventions',
      'Detective story elements',
    ],
  },
  {
    id: 'lit-great-expectations-ocr',
    name: 'Great Expectations',
    description: 'Dickens\' classic bildungsroman about class, guilt, and self-discovery',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Social ambition',
      'True gentility',
      'Crime and justice',
      'Guilt and conscience',
      'Love and obsession',
      'Money and morality',
      'Pip\'s development',
      'Miss Havisham',
      'Estella\'s coldness',
      'Magwitch revealed',
      'Joe\'s goodness',
      'Satis House',
      'The marshes',
      'Victorian society',
      'Narrative perspective',
      'Irony and satire',
    ],
  },
  {
    id: 'lit-jane-eyre-ocr',
    name: 'Jane Eyre',
    description: 'Brontë\'s Gothic romance about a woman\'s search for independence and love',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Female independence',
      'Love and equality',
      'Class and position',
      'Religion and morality',
      'Passion and duty',
      'The supernatural',
      'Jane\'s spirit',
      'Rochester\'s mystery',
      'Bertha\'s significance',
      'Childhood trauma',
      'Thornfield Hall',
      'Lowood suffering',
      'Moor House',
      'Marriage as equality',
      'Gothic elements',
      'First-person voice',
    ],
  },
  {
    id: 'lit-pride-prejudice-ocr',
    name: 'Pride and Prejudice',
    description: 'Austen\'s comedy of manners examining marriage and social hierarchy',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Pride and prejudice',
      'Love vs practicality',
      'Class distinctions',
      'First impressions',
      'Women\'s position',
      'Irony and satire',
      'Elizabeth\'s journey',
      'Darcy\'s pride',
      'Jane and Bingley',
      'Wickham\'s true nature',
      'Lady Catherine',
      'Mr Collins',
      'Pemberley symbolism',
      'Letters\' importance',
      'Reputation and scandal',
      'Marriage market',
    ],
  },
  {
    id: 'lit-war-worlds',
    name: 'The War of the Worlds',
    description: 'Wells\' science fiction exploring invasion, imperialism, and human vulnerability',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Invasion and fear',
      'Imperialism reversed',
      'Science and reason',
      'Survival instincts',
      'Civilization collapse',
      'Faith and doubt',
      'The narrator\'s journey',
      'The Martians',
      'The heat ray',
      'Red weed symbolism',
      'The curate',
      'The artilleryman',
      'Bacteria and victory',
      'Victorian anxieties',
      'Scientific romance',
      'Narrative structure',
    ],
  },
  // Component 02: Exploring Poetry and Shakespeare
  {
    id: 'lit-shakespeare-macbeth',
    name: 'Macbeth (OCR)',
    description: 'Shakespeare\'s Scottish tragedy of ambition and its terrible consequences',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Vaulting ambition',
      'Guilt and madness',
      'Supernatural power',
      'Masculinity and violence',
      'Kingship and tyranny',
      'Deceptive appearances',
      'Macbeth\'s downfall',
      'Lady Macbeth\'s influence',
      'The weird sisters',
      'Banquo\'s ghost',
      'Duncan\'s murder',
      'Malcolm and Macduff',
      'Blood symbolism',
      'Night and darkness',
      'Sleepwalking scene',
      'Order restored',
    ],
  },
  {
    id: 'lit-shakespeare-romeo-juliet',
    name: 'Romeo and Juliet (OCR)',
    description: 'Shakespeare\'s immortal love tragedy set in feuding Verona',
    icon: '📖',
    color: 'bg-indigo-500',
    subtopics: [
      'Love versus hate',
      'Fate\'s cruelty',
      'Family loyalty',
      'Youth\'s passion',
      'Death\'s presence',
      'Light and darkness',
      'Romeo\'s romanticism',
      'Juliet\'s growth',
      'The Nurse\'s role',
      'Friar Lawrence',
      'Mercutio and Tybalt',
      'The balcony scene',
      'The death scene',
      'Prologue\'s prophecy',
      'Haste and impulse',
      'Reconciliation',
    ],
  },
  {
    id: 'lit-poetry-anthology-ocr',
    name: 'Poetry Anthology: Love and Relationships',
    description: 'OCR poetry anthology exploring love, loss, and human connections',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'Romantic love',
      'Parental love',
      'Unrequited love',
      'Lost love and grief',
      'Memory and time',
      'Identity and self',
      'Analysing language',
      'Analysing structure',
      'Analysing form',
      'Context and meaning',
      'Comparing poems',
      'Contrasting approaches',
      'Voice and perspective',
      'Imagery patterns',
      'Tone and mood',
      'Effective quotation',
    ],
  },
  {
    id: 'lit-unseen-poetry-ocr',
    name: 'Unseen Poetry (OCR)',
    description: 'Approaching unfamiliar poetry with confidence and analytical skill',
    icon: '📖',
    color: 'bg-indigo-500',
        subtopics: [
      'First impressions',
      'Theme identification',
      'Language features',
      'Structural devices',
      'Form and genre',
      'Tone recognition',
      'Speaker and voice',
      'Imagery types',
      'Sound effects',
      'Comparison skills',
      'Similarities finding',
      'Differences noting',
      'Terminology use',
      'Quotation selection',
      'Essay structure',
      'Exam technique',
    ],
  },
];

export function getOCRGCSEEnglishLiteratureTopicById(id: string): Topic | undefined {
  return ocrGCSEEnglishLiteratureTopics.find((topic) => topic.id === id);
}
