// AQA A-Level History (7042) Topics
// Based on official AQA specification
// Reference: https://www.aqa.org.uk/subjects/history/a-level/history-7042

import { Topic } from '@/types';

export const aqaALevelHistoryTopics: Topic[] = [
  // ============================================================================
  // COMPONENT 1: BREADTH STUDIES (WITH INTERPRETATIONS)
  // Most popular options
  // ============================================================================
  {
    id: 'aqa-alevel-hist-tudors',
    name: '1C The Tudors: England 1485-1603',
    description: 'England under the Tudor monarchs',
    icon: '👑',
    color: 'bg-amber-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // Henry VII
      'Henry VII consolidation',
      'Battle of Bosworth',
      'Establishing the dynasty',
      'Yorkist threats',
      'Lambert Simnel',
      'Perkin Warbeck',
      'Government under Henry VII',
      'Council and Parliament',
      'Financial policies',
      'Foreign policy',
      // Henry VIII
      'Henry VIII character',
      'Wolsey\'s rise and fall',
      'Reformation Parliament',
      'Break with Rome',
      'Royal Supremacy',
      'Dissolution of monasteries',
      'Cromwell\'s role',
      'Pilgrimage of Grace',
      'Henry\'s marriages',
      'Succession issues',
      // Edward VI
      'Minority government',
      'Somerset Protectorate',
      'Northumberland',
      'Religious changes',
      'Social and economic problems',
      'Kett\'s Rebellion',
      'Western Rebellion',
      // Mary I
      'Mary\'s accession',
      'Catholic restoration',
      'Spanish marriage',
      'Wyatt\'s Rebellion',
      'Protestant persecution',
      'Loss of Calais',
      // Elizabeth I
      'Elizabeth\'s early challenges',
      'Religious Settlement 1559',
      'Catholic threats',
      'Mary Queen of Scots',
      'Northern Rebellion',
      'Plots against Elizabeth',
      'Puritanism',
      'War with Spain',
      'Spanish Armada',
      'Government and Parliament',
      'Poverty and Poor Laws',
      'Essex Rebellion',
      'Elizabeth\'s legacy',
      // Historiography
      'Historical interpretations of Tudors',
      'Elton and Tudor revolution',
      'Revisionist views',
    ],
  },
  {
    id: 'aqa-alevel-hist-stuart-britain',
    name: '1D Stuart Britain and the Crisis of Monarchy 1603-1702',
    description: 'Britain from James I to William III',
    icon: '⚔️',
    color: 'bg-purple-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // James I
      'Union of Crowns',
      'James and Parliament',
      'Financial problems',
      'Great Contract',
      'Buckingham',
      'Religious policy',
      'Gunpowder Plot',
      'Foreign policy',
      'Thirty Years War',
      // Charles I
      'Charles\'s personality',
      'Buckingham continued',
      'Religious policy',
      'Arminianism',
      'Personal Rule 1629-40',
      'Ship Money',
      'Thorough',
      'Scottish Crisis',
      'Bishops\' Wars',
      'Long Parliament',
      'Root and Branch',
      'Grand Remonstrance',
      // Civil War
      'Outbreak of Civil War',
      'Sides and motivations',
      'Military campaigns',
      'Marston Moor',
      'Naseby',
      'New Model Army',
      'Political factions',
      'Army and Parliament',
      'Second Civil War',
      'Pride\'s Purge',
      'Trial and execution of Charles I',
      // Interregnum
      'Rump Parliament',
      'Commonwealth',
      'Barebone\'s Parliament',
      'Cromwellian Protectorate',
      'Major-Generals',
      'Religious toleration',
      'Ireland and Scotland',
      'Foreign policy',
      'Death of Cromwell',
      'Collapse of Protectorate',
      // Restoration
      'Restoration Settlement',
      'Charles II\'s government',
      'Clarendon Code',
      'Religious issues',
      'Financial settlement',
      'Foreign policy',
      'Anglo-Dutch Wars',
      'Secret Treaty of Dover',
      'Popish Plot',
      'Exclusion Crisis',
      'Whigs and Tories',
      // James II
      'James II\'s accession',
      'Religious policy',
      'Declaration of Indulgence',
      'Trial of Seven Bishops',
      'Glorious Revolution',
      'William and Mary',
      'Revolutionary Settlement',
      'Bill of Rights',
      // Historiography
      'Whig interpretation',
      'Revisionist debates',
      'Causes of Civil War historiography',
    ],
  },
  {
    id: 'aqa-alevel-hist-britain-transformation',
    name: '1G Challenge and Transformation: Britain c1851-1964',
    description: 'Political, social and economic change in modern Britain',
    icon: '🏭',
    color: 'bg-slate-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // Mid-Victorian Britain
      'Britain in 1851',
      'Great Exhibition',
      'Political system 1850s',
      'Gladstone and Disraeli',
      'Second Reform Act 1867',
      'Gladstone\'s First Ministry',
      'Disraeli\'s social reforms',
      // Late Victorian/Edwardian
      'Third Reform Act 1884',
      'Irish Home Rule',
      'Rise of Labour',
      'Salisbury\'s governments',
      'Liberal revival 1906',
      'Liberal social reforms',
      'Lloyd George budgets',
      'Constitutional crisis',
      'Parliament Act 1911',
      'Suffragettes',
      'Irish crisis 1912-14',
      // World War One
      'Impact of WWI',
      'Coalition government',
      'War economy',
      'Representation of People Act 1918',
      // Inter-war years
      'Post-war challenges',
      'Coalition and Conservative dominance',
      'First Labour government',
      'General Strike 1926',
      'Second Labour government',
      'National Government',
      'Unemployment',
      'Appeasement',
      // World War Two
      'Churchill\'s leadership',
      'Home Front WWII',
      'Beveridge Report',
      'Plans for reconstruction',
      // Post-war Britain
      'Attlee government',
      'Welfare State',
      'NHS',
      'Nationalisation',
      'Austerity',
      '1951 election',
      'Conservative governments 1951-64',
      'Consensus politics',
      'Affluence',
      'Macmillan',
      'Winds of Change',
      'Decline debates',
      // Historiography
      'Interpretations of welfare state',
      'Decline of Britain debates',
    ],
  },
  {
    id: 'aqa-alevel-hist-tsarist-communist-russia',
    name: '1H Tsarist and Communist Russia 1855-1964',
    description: 'Russia from Alexander II to Khrushchev',
    icon: '🇷🇺',
    color: 'bg-red-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // Alexander II
      'Russia in 1855',
      'Emancipation of serfs',
      'Judicial reforms',
      'Military reforms',
      'Zemstva',
      'Education reforms',
      'Opposition and repression',
      'Polish Revolt',
      'Assassination 1881',
      // Alexander III
      'Counter-reforms',
      'Repression',
      'Russification',
      'Economic development',
      'Witte\'s reforms',
      // Nicholas II
      'Nicholas II\'s character',
      '1905 Revolution',
      'Bloody Sunday',
      'October Manifesto',
      'Fundamental Laws',
      'Dumas',
      'Stolypin',
      'Economic progress',
      'Social tensions',
      // WWI and Revolution
      'Russia in WWI',
      'Military failures',
      'Rasputin',
      'February Revolution 1917',
      'Provisional Government',
      'Soviets',
      'Lenin\'s return',
      'October Revolution',
      // Lenin era
      'Consolidation of power',
      'Treaty of Brest-Litovsk',
      'Civil War',
      'War Communism',
      'Red Terror',
      'NEP',
      'Communist Party structure',
      'Death of Lenin',
      // Stalin
      'Power struggle',
      'Rise of Stalin',
      'Five Year Plans',
      'Collectivisation',
      'Dekulakisation',
      'Famine',
      'Terror and purges',
      'Show trials',
      'Gulag',
      'Cult of personality',
      'Great Patriotic War',
      'Post-war Stalinism',
      // Khrushchev
      'Death of Stalin',
      'Power struggle',
      'De-Stalinisation',
      'Secret Speech',
      'Reforms',
      'Foreign policy',
      'Fall of Khrushchev',
      // Historiography
      'Totalitarian model',
      'Revisionist views',
      'Intentionalist vs structuralist',
    ],
  },
  {
    id: 'aqa-alevel-hist-usa-superpower',
    name: '1K The Making of a Superpower: USA 1865-1975',
    description: 'America from Civil War to Vietnam',
    icon: '🇺🇸',
    color: 'bg-blue-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // Reconstruction
      'Post-Civil War America',
      'Reconstruction plans',
      'Radical Reconstruction',
      '13th 14th 15th Amendments',
      'Freedmen\'s Bureau',
      'Jim Crow laws',
      'KKK',
      // Gilded Age
      'Industrial growth',
      'Railroads',
      'Big business',
      'Trusts and monopolies',
      'Immigration',
      'Urbanisation',
      'Political corruption',
      'Populism',
      // Progressive Era
      'Roosevelt progressivism',
      'Trust-busting',
      'Conservation',
      'Wilson\'s New Freedom',
      // WWI and 1920s
      'Isolationism to intervention',
      'American role in WWI',
      'Treaty of Versailles rejection',
      'Return to normalcy',
      'Republican prosperity',
      'Consumer boom',
      'Social tensions',
      'Red Scare',
      'Immigration restriction',
      // Depression and New Deal
      'Wall Street Crash',
      'Hoover\'s response',
      'FDR and New Deal',
      'Alphabet agencies',
      'Second New Deal',
      'Opposition',
      'Impact and legacy',
      // WWII and Cold War
      'Isolationism to Pearl Harbor',
      'War economy',
      'Emergence as superpower',
      'Truman Doctrine',
      'Marshall Plan',
      'Containment',
      'Korean War',
      'McCarthyism',
      // Civil Rights
      'Segregation',
      'Brown v Board',
      'Montgomery',
      'King and SCLC',
      'Sit-ins and Freedom Rides',
      'Birmingham',
      'March on Washington',
      'Civil Rights Acts',
      'Black Power',
      // Vietnam era
      'Escalation',
      'Vietnam War',
      'Anti-war movement',
      'Nixon and Watergate',
      // Historiography
      'New Deal interpretations',
      'Civil Rights historiography',
    ],
  },
  {
    id: 'aqa-alevel-hist-germany-1871-1991',
    name: '1L The Quest for Political Stability: Germany 1871-1991',
    description: 'Germany from unification to reunification',
    icon: '🇩🇪',
    color: 'bg-gray-800',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 1 Breadth',
    subtopics: [
      // Imperial Germany
      'Unification legacy',
      'Constitution 1871',
      'Bismarck\'s domestic policy',
      'Kulturkampf',
      'Anti-socialist laws',
      'Social insurance',
      'Wilhelm II',
      'Weltpolitik',
      // Weimar Republic
      'Revolution 1918-19',
      'Weimar Constitution',
      'Early challenges',
      'Versailles impact',
      'Hyperinflation',
      'Stresemann era',
      'Golden twenties',
      'Depression impact',
      'Rise of Nazis',
      // Nazi Germany
      'Nazi ideology',
      'Consolidation of power',
      'Police state',
      'Economic policy',
      'Social policy',
      'Racial policy',
      'Foreign policy',
      'Road to war',
      'WWII',
      'Holocaust',
      // Divided Germany
      'Occupation zones',
      'Cold War division',
      'Federal Republic',
      'Adenauer era',
      'Economic miracle',
      'Ostpolitik',
      'GDR',
      'SED dictatorship',
      'Building socialism',
      'Berlin Wall',
      // Reunification
      'Fall of Berlin Wall',
      'Process of reunification',
      'Challenges of unity',
      // Historiography
      'Sonderweg debate',
      'Nazi Germany interpretations',
    ],
  },
  // ============================================================================
  // COMPONENT 2: DEPTH STUDIES
  // Most popular options
  // ============================================================================
  {
    id: 'aqa-alevel-hist-english-revolution',
    name: '2E The English Revolution 1625-1660',
    description: 'From Charles I to the Restoration',
    icon: '⚔️',
    color: 'bg-red-800',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 2 Depth',
    subtopics: [
      // Charles I early reign
      'Charles I\'s personality',
      'Buckingham',
      'Parliament 1625-29',
      'Forced Loan',
      'Petition of Right',
      'Personal Rule',
      'Religious policy',
      'Arminianism and Laud',
      'Ship Money',
      // Crisis
      'Scottish Crisis',
      'Bishops\' Wars',
      'Short Parliament',
      'Long Parliament',
      'Strafford\'s trial',
      'Ten Propositions',
      'Grand Remonstrance',
      'Five Members',
      // Civil War
      'Outbreak of war',
      'Royalist vs Parliamentarian',
      'Military campaigns',
      'Self-Denying Ordinance',
      'New Model Army',
      'Charles\'s defeat',
      // Search for settlement
      'Newcastle Propositions',
      'Army and Parliament conflict',
      'Putney Debates',
      'Second Civil War',
      'Pride\'s Purge',
      'Trial and execution',
      // Commonwealth
      'Rump Parliament',
      'Republic established',
      'Irish campaign',
      'Scottish campaign',
      'Dutch War',
      // Protectorate
      'Cromwell as Lord Protector',
      'Instrument of Government',
      'Parliaments',
      'Major-Generals',
      'Religious settlement',
      'Foreign policy',
      'Humble Petition',
      'Death of Cromwell',
      'Collapse',
      // Primary sources
      'Using contemporary sources',
      'Speeches and debates',
      'News and pamphlets',
    ],
  },
  {
    id: 'aqa-alevel-hist-cold-war',
    name: '2R The Cold War c1945-1991',
    description: 'Origins, development and end of the Cold War',
    icon: '❄️',
    color: 'bg-cyan-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 2 Depth',
    subtopics: [
      // Origins
      'Wartime alliance',
      'Yalta and Potsdam',
      'Ideological differences',
      'Soviet expansion',
      'Iron Curtain',
      'Truman Doctrine',
      'Marshall Plan',
      'Berlin Blockade',
      'NATO',
      // Early Cold War
      'Division of Germany',
      'Korean War',
      'NSC-68',
      'Arms race',
      'Hydrogen bomb',
      'Death of Stalin',
      'Khrushchev',
      'De-Stalinisation',
      'Hungary 1956',
      // Berlin and Cuba
      'Berlin Crisis 1958-61',
      'U-2 incident',
      'Berlin Wall',
      'Cuban Revolution',
      'Bay of Pigs',
      'Missile Crisis',
      'Significance of Cuba',
      // Detente
      'Reasons for detente',
      'SALT I',
      'Helsinki Accords',
      'Limits of detente',
      'Soviet perspective',
      // Second Cold War
      'Carter',
      'Afghanistan',
      'Reagan',
      'SDI',
      'Evil Empire',
      // End of Cold War
      'Gorbachev',
      'Glasnost and perestroika',
      'INF Treaty',
      'Eastern Europe 1989',
      'Fall of Berlin Wall',
      'End of USSR',
      // Primary sources
      'Diplomatic documents',
      'Speeches',
      'Intelligence sources',
    ],
  },
  {
    id: 'aqa-alevel-hist-making-modern-britain',
    name: '2S The Making of Modern Britain 1951-2007',
    description: 'Britain from Churchill to Blair',
    icon: '🇬🇧',
    color: 'bg-blue-800',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 2 Depth',
    subtopics: [
      // Conservative dominance 1951-64
      'Churchill\'s return',
      'Eden and Suez',
      'Macmillan',
      'Affluent society',
      'Never had it so good',
      'Winds of Change',
      'EEC application',
      'Profumo affair',
      'Douglas-Home',
      // Wilson and Heath
      'Wilson 1964-70',
      'Economic problems',
      'Devaluation',
      'In Place of Strife',
      'Heath government',
      'Industrial relations',
      'Three-day week',
      'EEC entry',
      // Callaghan and Thatcher
      'Wilson/Callaghan 1974-79',
      'IMF crisis',
      'Winter of Discontent',
      'Thatcher\'s rise',
      'Thatcherism',
      'Economic policy',
      'Trade union reform',
      'Miners\' Strike',
      'Privatisation',
      'Poll Tax',
      'Fall of Thatcher',
      // Major and Blair
      'Major government',
      'ERM crisis',
      'Sleaze',
      'New Labour',
      'Blair\'s domestic policy',
      'Devolution',
      'Constitutional reform',
      'Iraq War',
      // Themes
      'Immigration and race',
      'Windrush to multiculturalism',
      'Media and politics',
      'Social change',
      'Class and identity',
      // Primary sources
      'Political memoirs',
      'Parliamentary records',
      'Media sources',
    ],
  },
  {
    id: 'aqa-alevel-hist-russia-1917-1953',
    name: '2N Revolution and Dictatorship: Russia 1917-1953',
    description: 'Russia from Revolution to death of Stalin',
    icon: '☭',
    color: 'bg-red-900',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 2 Depth',
    subtopics: [
      // 1917 Revolutions
      'February Revolution',
      'Fall of Tsarism',
      'Provisional Government',
      'Dual power',
      'Soviets',
      'Lenin\'s return',
      'April Theses',
      'July Days',
      'Kornilov Affair',
      'October Revolution',
      // Civil War
      'Consolidation',
      'Constituent Assembly',
      'Brest-Litovsk',
      'Civil War outbreak',
      'Reds vs Whites',
      'War Communism',
      'Red Terror',
      'Reasons for Red victory',
      // Lenin\'s rule
      'Communist Party',
      'One-party state',
      'Kronstadt',
      'NEP',
      'Ban on factions',
      'National question',
      'Death of Lenin',
      // Stalin\'s rise
      'Power struggle',
      'Trotsky',
      'Left vs Right',
      'Stalin\'s victory',
      // Stalin\'s rule
      'End of NEP',
      'First Five Year Plan',
      'Industrialisation',
      'Collectivisation',
      'Dekulakisation',
      'Famine',
      'Second Five Year Plan',
      'Terror',
      'Show trials',
      'Great Terror',
      'Gulag',
      // WWII and after
      'Nazi-Soviet Pact',
      'Operation Barbarossa',
      'Great Patriotic War',
      'Victory',
      'Post-war Stalinism',
      'Cold War begins',
      'Death of Stalin',
      // Primary sources
      'Party documents',
      'Memoirs',
      'Statistics',
    ],
  },
  // ============================================================================
  // COMPONENT 3: HISTORICAL INVESTIGATION (NEA)
  // ============================================================================
  {
    id: 'aqa-alevel-hist-investigation',
    name: 'Historical Investigation (NEA)',
    description: 'Independent historical investigation 3500-4500 words',
    icon: '📝',
    color: 'bg-indigo-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'history',
    paperRestriction: 'Component 3 NEA',
    subtopics: [
      // Investigation skills
      'Choosing a question',
      'Question requirements',
      'Chronological requirements',
      'British or non-British',
      'Primary sources',
      'Secondary sources',
      'Historiography',
      // Structure
      'Introduction',
      'Analysis',
      'Argument development',
      'Use of evidence',
      'Evaluation of sources',
      'Historical interpretations',
      'Conclusion',
      // Assessment
      'AO1 requirements',
      'AO2 requirements',
      'AO3 requirements',
      'Word count',
      'Referencing',
      'Bibliography',
    ],
  },
];

export function getAQAALevelHistoryTopicById(id: string): Topic | undefined {
  return aqaALevelHistoryTopics.find((topic) => topic.id === id);
}
