// AQA A-Level Physics (7408) Topics
// Complete specification coverage
// Paper 1: Sections 1-5 + 6.1 (Further Mechanics)
// Paper 2: Sections 6.2, 7, 8 (Thermal Physics, Fields, Nuclear)
// Paper 3: Practical skills + Optional topic (Section 9-13)

import { Topic } from '@/types';

export const aqaALevelPhysicsTopics: Topic[] = [
  // ==========================================
  // PAPER 1 TOPICS (AS content + Further Mechanics)
  // ==========================================

  // Section 3.1: Measurements and Their Errors
  {
    id: 'alevel-physics-measurements',
    name: 'Measurements and Their Errors',
    description: 'SI units, uncertainty, errors and estimation',
    icon: '📏',
    color: 'bg-gray-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.1.1 Use of SI units
      'SI base units: kg, m, s, A, K, mol',
      'SI derived units and their base unit equivalents',
      'SI prefixes: pico to tera',
      'Converting between units',
      'Checking homogeneity of equations',
      // 3.1.2 Limitation of physical measurements
      'Random errors and systematic errors',
      'Precision, accuracy and resolution',
      'Repeatability and reproducibility',
      'Uncertainty in measurements',
      'Absolute uncertainty and percentage uncertainty',
      'Combining uncertainties: addition and subtraction',
      'Combining uncertainties: multiplication and division',
      'Combining uncertainties: powers and roots',
      'Error bars on graphs',
      'Determining uncertainty from graphs',
      'Maximum and minimum gradient methods',
      // 3.1.3 Estimation of physical quantities
      'Orders of magnitude',
      'Estimating physical quantities',
      'Fermi estimation problems',
    ],
  },

  // Section 3.2: Particles and Radiation
  {
    id: 'alevel-physics-particles',
    name: 'Particles and Radiation',
    description: 'Atomic structure, particle physics and quantum phenomena',
    icon: '⚛️',
    color: 'bg-purple-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.2.1.1 Constituents of the atom
      'Proton, neutron and electron',
      'Specific charge of particles',
      'Proton number Z and nucleon number A',
      'Isotopes and nuclide notation',
      // 3.2.1.2 Stable and unstable nuclei
      'The strong nuclear force',
      'Range of the strong force (~3 fm)',
      'Alpha decay and nuclear equations',
      'Beta-minus decay: neutron to proton',
      'Beta-plus decay: proton to neutron',
      'Neutrinos and antineutrinos in beta decay',
      // 3.2.1.3 Particles, antiparticles and photons
      'Antimatter and antiparticles',
      'Positron as antielectron',
      'Antiproton and antineutron',
      'Photons and electromagnetic radiation',
      'Photon energy: E = hf = hc/λ',
      'Electronvolt (eV) as energy unit',
      'Annihilation: particle-antiparticle',
      'Pair production from photons',
      'Threshold energy for pair production',
      // 3.2.1.4 Particle interactions
      'Fundamental forces: strong, weak, electromagnetic, gravitational',
      'Exchange particles for forces',
      'Virtual photons in electromagnetic interactions',
      'W bosons in weak interactions',
      'Gluons in strong interactions',
      'Gravitons (theoretical)',
      'Feynman diagrams for interactions',
      'Beta decay Feynman diagrams',
      'Electron capture',
      'Electron-proton collisions',
      // 3.2.1.5 Classification of particles
      'Hadrons: particles affected by strong force',
      'Baryons: protons, neutrons and their antiparticles',
      'Baryon number conservation',
      'Mesons: pion and kaon',
      'Pion as exchange particle',
      'Kaons and strangeness',
      'Leptons: electron, muon, tau and neutrinos',
      'Lepton number conservation',
      'Muon decay',
      // 3.2.1.6 Quarks and antiquarks
      'Quark model: up, down, strange',
      'Quark charges: +2/3e and -1/3e',
      'Quark composition of protons (uud)',
      'Quark composition of neutrons (udd)',
      'Quark composition of pions',
      'Quark composition of kaons',
      'Antiquarks and their properties',
      'Quark confinement',
      // 3.2.1.7 Application of conservation laws
      'Conservation of charge',
      'Conservation of baryon number',
      'Conservation of lepton number',
      'Conservation of strangeness (strong only)',
      'Strangeness change in weak interactions',
      'Analysing particle interactions',
      // 3.2.2.1 The photoelectric effect
      'Photoelectric emission',
      'Threshold frequency',
      'Work function φ',
      'Photoelectric equation: hf = φ + Ek(max)',
      'Stopping potential',
      'Wave-particle duality evidence',
      'Failure of wave theory to explain photoelectric effect',
      // 3.2.2.2 Collisions of electrons with atoms
      'Ionisation by electron collision',
      'Excitation by electron collision',
      'Ionisation energy',
      'Excitation energy',
      'Fluorescent tubes operation',
      // 3.2.2.3 Energy levels and photon emission
      'Discrete energy levels in atoms',
      'Ground state and excited states',
      'Photon emission from transitions',
      'Energy level diagrams',
      'Line spectra and energy levels',
      'Absorption spectra',
      // 3.2.2.4 Wave-particle duality
      'de Broglie wavelength: λ = h/p = h/mv',
      'Electron diffraction',
      'Wave nature of particles',
      'Particle nature of waves',
    ],
  },

  // Section 3.3: Waves
  {
    id: 'alevel-physics-waves',
    name: 'Waves',
    description: 'Progressive waves, stationary waves, refraction, diffraction and interference',
    icon: '🌊',
    color: 'bg-cyan-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.3.1.1 Progressive waves
      'Wave motion and energy transfer',
      'Transverse and longitudinal waves',
      'Displacement, amplitude, wavelength',
      'Period, frequency and phase',
      'Phase difference in radians and degrees',
      'Wave speed equation: v = fλ',
      // 3.3.1.2 Longitudinal and transverse waves
      'Oscillation direction relative to wave travel',
      'Compressions and rarefactions',
      'Polarisation of transverse waves',
      'Polaroid filters',
      'Malus\'s law (intensity variation)',
      'Applications of polarisation',
      'Polarisation by reflection',
      'Aerial alignment for transmission/reception',
      // 3.3.2.1 Stationary (standing) waves
      'Formation of stationary waves',
      'Nodes and antinodes',
      'Comparison with progressive waves',
      'Stationary waves on strings',
      'Harmonics and overtones',
      'Fundamental frequency',
      'First harmonic equation: f = 1/(2L) × √(T/μ)',
      'Stationary waves in pipes',
      'Open and closed pipes',
      'Required practical: stationary waves on a string',
      // 3.3.2.2 Interference
      'Path difference and phase difference',
      'Coherent sources',
      'Constructive and destructive interference',
      'Two-source interference',
      'Young\'s double slit experiment',
      'Fringe spacing equation: w = λD/s',
      'White light interference',
      'Required practical: Young\'s double slit',
      // 3.3.2.3 Diffraction
      'Diffraction at a single slit',
      'Width of central maximum',
      'Effect of slit width on diffraction pattern',
      'Diffraction grating equation: d sin θ = nλ',
      'Orders of diffraction',
      'Grating applications: spectrometry',
      'Angular separation of spectral lines',
      // 3.3.2.4 Refraction at a plane surface
      'Refractive index: n = c/v',
      'Snell\'s law: n₁ sin θ₁ = n₂ sin θ₂',
      'Total internal reflection',
      'Critical angle calculation',
      'Optical fibres: step-index',
      'Material and modal dispersion',
      'Pulse broadening in fibres',
      'Applications of optical fibres',
    ],
  },

  // Section 3.4: Mechanics and Materials
  {
    id: 'alevel-physics-mechanics',
    name: 'Mechanics and Materials',
    description: 'Forces, motion, momentum, energy and material properties',
    icon: '⚙️',
    color: 'bg-blue-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.4.1.1 Scalars and vectors
      'Definition of scalars and vectors',
      'Examples of each type',
      'Vector addition by scale drawing',
      'Vector addition by calculation',
      'Resolving vectors into components',
      'Resolving forces on inclined planes',
      // 3.4.1.2 Moments
      'Moment = force × perpendicular distance',
      'Couple and torque',
      'Principle of moments',
      'Centre of mass',
      'Conditions for equilibrium',
      // 3.4.1.3 Motion along a straight line
      'Displacement, velocity, acceleration',
      'Displacement-time graphs',
      'Velocity-time graphs',
      'Gradient and area under graphs',
      'SUVAT equations',
      'v = u + at',
      's = ut + ½at²',
      's = ½(u + v)t',
      'v² = u² + 2as',
      'Free fall and g = 9.81 m/s²',
      'Required practical: measuring g',
      // 3.4.1.4 Projectile motion
      'Independent horizontal and vertical motion',
      'Horizontal component constant',
      'Vertical component accelerated by g',
      'Time of flight calculations',
      'Range calculations',
      'Maximum height calculations',
      // 3.4.1.5 Newton\'s laws of motion
      'Newton\'s First Law',
      'Newton\'s Second Law: F = ma',
      'Newton\'s Third Law',
      'Free body diagrams',
      'Terminal velocity',
      'Air resistance and drag',
      // 3.4.1.6 Momentum
      'Momentum = mass × velocity',
      'Conservation of momentum',
      'Elastic collisions',
      'Inelastic collisions',
      'Explosions and separation',
      'Force as rate of change of momentum',
      'Impulse = FΔt = Δp',
      'Force-time graphs',
      // 3.4.1.7 Work, energy and power
      'Work done = force × displacement',
      'Work done at an angle: W = Fs cos θ',
      'Kinetic energy: Ek = ½mv²',
      'Gravitational potential energy: Ep = mgh',
      'Conservation of mechanical energy',
      'Power = work done / time',
      'Power = force × velocity',
      'Efficiency calculations',
      // 3.4.1.8 Conservation of energy
      'Conservation of energy principle',
      'Energy transfers in systems',
      'Energy dissipation',
      // 3.4.2.1 Bulk properties of solids
      'Density = mass / volume',
      'Hooke\'s law: F = kx',
      'Spring constant',
      'Elastic limit',
      'Elastic and plastic deformation',
      'Tensile stress: σ = F/A',
      'Tensile strain: ε = ΔL/L',
      'Breaking stress',
      'Ultimate tensile stress',
      'Required practical: Young modulus',
      // 3.4.2.2 The Young modulus
      'Young modulus: E = σ/ε = FL/AΔL',
      'Stress-strain graphs',
      'Elastic strain energy: E = ½FΔL = ½kx²',
      'Area under force-extension graph',
      'Loading and unloading curves',
      'Hysteresis and energy dissipation',
    ],
  },

  // Section 3.5: Electricity
  {
    id: 'alevel-physics-electricity',
    name: 'Electricity',
    description: 'Current, voltage, resistance, circuits and EMF',
    icon: '⚡',
    color: 'bg-yellow-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.5.1.1 Basics of electricity
      'Electric current as rate of charge flow',
      'I = ΔQ/Δt',
      'Charge carriers in conductors',
      'Conventional current vs electron flow',
      'Mean drift velocity: I = nAvq',
      'Number density of charge carriers',
      // 3.5.1.2 Current-voltage characteristics
      'Ohm\'s law: V = IR',
      'Ohmic and non-ohmic conductors',
      'I-V characteristics of resistors',
      'I-V characteristics of filament lamps',
      'I-V characteristics of diodes',
      'I-V characteristics of thermistors',
      'I-V characteristics of LDRs',
      'Required practical: I-V characteristics',
      // 3.5.1.3 Resistivity
      'Resistivity: ρ = RA/L',
      'Effect of temperature on resistivity',
      'Superconductivity',
      'Critical temperature',
      'Applications of superconductors',
      'Required practical: resistivity of a wire',
      // 3.5.1.4 Circuits
      'Series and parallel circuits',
      'Kirchhoff\'s first law (current)',
      'Kirchhoff\'s second law (voltage)',
      'Total resistance in series',
      'Total resistance in parallel',
      'Combined series-parallel circuits',
      'Power in circuits: P = IV = I²R = V²/R',
      'Energy: E = VIt = I²Rt',
      // 3.5.1.5 Potential divider
      'Potential divider equation',
      'Vout = Vin × R₂/(R₁ + R₂)',
      'Sensor circuits with LDR',
      'Sensor circuits with thermistor',
      'Applications of potential dividers',
      // 3.5.1.6 Electromotive force and internal resistance
      'EMF as energy per unit charge',
      'EMF vs terminal p.d.',
      'Internal resistance',
      'ε = I(R + r) = V + Ir',
      'Lost volts',
      'Required practical: EMF and internal resistance',
    ],
  },

  // Section 3.6.1: Further Mechanics (Periodic Motion)
  {
    id: 'alevel-physics-further-mechanics',
    name: 'Further Mechanics',
    description: 'Circular motion, simple harmonic motion and resonance',
    icon: '🔄',
    color: 'bg-indigo-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 1',
    subtopics: [
      // 3.6.1.1 Circular motion
      'Angular displacement in radians',
      'Angular velocity: ω = θ/t = 2πf',
      'Linear speed: v = ωr',
      'Centripetal acceleration: a = v²/r = ω²r',
      'Centripetal force: F = mv²/r = mω²r',
      'Objects in circular paths (horizontal)',
      'Objects in vertical circles',
      'Conical pendulum',
      'Banked tracks',
      // 3.6.1.2 Simple harmonic motion (SHM)
      'Conditions for SHM: a ∝ -x',
      'Defining equation: a = -ω²x',
      'Angular frequency: ω = 2πf',
      'Displacement equation: x = A cos(ωt)',
      'Velocity equation: v = -Aω sin(ωt)',
      'Velocity-displacement relation: v = ±ω√(A² - x²)',
      'Maximum velocity: vmax = ωA',
      'Maximum acceleration: amax = ω²A',
      'Phase relationships between x, v, a',
      'Graphs of SHM quantities',
      // 3.6.1.3 Simple harmonic systems
      'Mass-spring system period: T = 2π√(m/k)',
      'Simple pendulum period: T = 2π√(L/g)',
      'Energy in SHM',
      'Kinetic and potential energy exchange',
      'Total energy: E = ½kA² = ½mω²A²',
      'Energy-time graphs',
      'Energy-displacement graphs',
      'Required practical: mass-spring oscillations',
      'Required practical: simple pendulum',
      // 3.6.1.4 Forced vibrations and resonance
      'Free oscillations and natural frequency',
      'Damping: light, heavy, critical',
      'Effect of damping on amplitude',
      'Forced vibrations',
      'Driving frequency',
      'Resonance at f = f₀',
      'Amplitude-frequency graphs',
      'Effect of damping on resonance',
      'Sharpness of resonance peak',
      'Examples of resonance',
      'Barton\'s pendulums',
    ],
  },

  // ==========================================
  // PAPER 2 TOPICS (A-Level only content)
  // ==========================================

  // Section 3.6.2: Thermal Physics
  {
    id: 'alevel-physics-thermal',
    name: 'Thermal Physics',
    description: 'Heat transfer, ideal gases and kinetic theory',
    icon: '🌡️',
    color: 'bg-red-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.6.2.1 Thermal energy transfer
      'Internal energy',
      'Kinetic and potential energy of molecules',
      'Temperature and thermal equilibrium',
      'Absolute zero and the Kelvin scale',
      'Specific heat capacity: E = mcΔθ',
      'Specific latent heat: E = mL',
      'Latent heat of fusion and vaporisation',
      'Continuous flow heating method',
      'Heating curves and cooling curves',
      // 3.6.2.2 Ideal gases
      'Gas laws experiments',
      'Boyle\'s law: pV = constant (at constant T)',
      'Charles\'s law: V/T = constant (at constant p)',
      'Pressure law: p/T = constant (at constant V)',
      'Absolute temperature scale',
      'Ideal gas equation: pV = nRT',
      'Ideal gas equation: pV = NkT',
      'Molar gas constant R = 8.31 J mol⁻¹ K⁻¹',
      'Boltzmann constant k = 1.38 × 10⁻²³ J K⁻¹',
      'Molar mass and molecular mass',
      'Avogadro constant',
      'Required practical: gas laws',
      // 3.6.2.3 Molecular kinetic theory model
      'Brownian motion evidence for atoms',
      'Assumptions of kinetic theory',
      'Derivation of pressure equation',
      'pV = ⅓Nm<c²>',
      'Mean square speed <c²>',
      'Root mean square speed crms',
      'Kinetic energy of gas molecules',
      '½m<c²> = 3/2 kT',
      'Internal energy of ideal gas: U = 3/2 NkT',
    ],
  },

  // Section 3.7: Fields and Their Consequences
  {
    id: 'alevel-physics-fields',
    name: 'Fields and Their Consequences',
    description: 'Gravitational, electric and magnetic fields, capacitance and EM induction',
    icon: '🧲',
    color: 'bg-green-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.7.1 Fields
      'Concept of force fields',
      'Contact and non-contact forces',
      'Field lines and field patterns',
      // 3.7.2.1 Newton\'s law of gravitation
      'Newton\'s law: F = GMm/r²',
      'Gravitational constant G',
      'Point masses and spherical bodies',
      // 3.7.2.2 Gravitational field strength
      'g = F/m as field strength',
      'g = GM/r² for point mass',
      'Variation of g with distance',
      'Gravitational field inside a sphere',
      // 3.7.2.3 Gravitational potential
      'Gravitational potential V = -GM/r',
      'Potential as energy per unit mass',
      'Equipotential surfaces',
      'Potential gradient: g = -dV/dr',
      'Gravitational potential energy: E = -GMm/r',
      'Escape velocity derivation',
      // 3.7.2.4 Orbits of planets and satellites
      'Orbital motion and centripetal force',
      'Orbital speed: v = √(GM/r)',
      'Orbital period: T² ∝ r³',
      'Kepler\'s third law derivation',
      'Geostationary orbits',
      'Low polar orbits',
      'Satellite applications',
      'Energy of orbiting satellites',
      // 3.7.3.1 Coulomb\'s law
      'Coulomb\'s law: F = kQ₁Q₂/r²',
      'Permittivity of free space ε₀',
      'k = 1/(4πε₀)',
      'Comparison with gravitation',
      // 3.7.3.2 Electric field strength
      'E = F/Q as field strength',
      'E = kQ/r² for point charge',
      'Electric field between parallel plates',
      'E = V/d for uniform field',
      'Motion of charged particles in uniform fields',
      // 3.7.3.3 Electric potential
      'Electric potential V = kQ/r',
      'Potential at a point',
      'Work done moving charges',
      'Equipotential lines',
      'Potential gradient: E = -dV/dr',
      // 3.7.4.1 Capacitance
      'Definition: C = Q/V',
      'Energy stored: E = ½QV = ½CV² = ½Q²/C',
      'Capacitors in series and parallel',
      // 3.7.4.2 Parallel plate capacitor
      'C = ε₀A/d',
      'Effect of dielectrics',
      'Relative permittivity',
      'C = ε₀εᵣA/d',
      // 3.7.4.3 Capacitor charge and discharge
      'Charging through a resistor',
      'Time constant τ = RC',
      'Q = Q₀(1 - e^(-t/RC)) for charging',
      'Q = Q₀e^(-t/RC) for discharging',
      'Current during charge/discharge',
      'Required practical: capacitor discharge',
      // 3.7.5.1 Magnetic flux density
      'Magnetic field and flux density B',
      'Force on current-carrying wire: F = BIL',
      'F = BIL sin θ',
      'Tesla as unit',
      // 3.7.5.2 Moving charges in a magnetic field
      'Force on moving charge: F = BQv',
      'F = BQv sin θ',
      'Circular motion of charges',
      'Radius of circular path: r = mv/(BQ)',
      'Velocity selector',
      'Mass spectrometer',
      'Cyclotron',
      // 3.7.5.3 Magnetic flux and flux linkage
      'Magnetic flux: Φ = BA',
      'Flux linkage: NΦ = BAN',
      'Flux linkage changes',
      // 3.7.5.4 Electromagnetic induction
      'Faraday\'s law: ε = -NdΦ/dt',
      'Lenz\'s law and direction of induced EMF',
      'EMF from flux linkage changes',
      'Applications of electromagnetic induction',
      // 3.7.5.5 Alternating currents
      'AC generator principle',
      'Sinusoidal variation of EMF',
      'Peak and RMS values',
      'Irms = I₀/√2, Vrms = V₀/√2',
      'Transformers: Ns/Np = Vs/Vp',
      'Transformer efficiency',
      'Power transmission and the grid',
      'Required practical: investigating transformers',
    ],
  },

  // Section 3.8: Nuclear Physics
  {
    id: 'alevel-physics-nuclear',
    name: 'Nuclear Physics',
    description: 'Radioactivity, nuclear instability, mass-energy and fission',
    icon: '☢️',
    color: 'bg-orange-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 2',
    subtopics: [
      // 3.8.1.1 Rutherford scattering
      'Alpha particle scattering experiment',
      'Evidence for nuclear model',
      'Estimate of nuclear radius',
      // 3.8.1.2 α, β and γ radiation
      'Properties of alpha particles',
      'Properties of beta particles',
      'Properties of gamma rays',
      'Ionising ability comparison',
      'Penetrating power comparison',
      'Deflection in fields',
      // 3.8.1.3 Radioactive decay
      'Random nature of decay',
      'Activity A = λN',
      'Decay constant λ',
      'Half-life: t½ = ln2/λ',
      'Exponential decay: N = N₀e^(-λt)',
      'Activity decay: A = A₀e^(-λt)',
      'Decay graphs and half-life determination',
      'Carbon dating',
      'Required practical: absorption of radiation',
      // 3.8.1.4 Nuclear instability
      'N-Z diagram',
      'Stability line',
      'Alpha decay for heavy nuclei',
      'Beta-minus decay: neutron-rich',
      'Beta-plus decay: proton-rich',
      'Electron capture',
      'Gamma emission after decay',
      // 3.8.1.5 Nuclear radius
      'Nuclear radius: r = r₀A^(1/3)',
      'r₀ ≈ 1.2 fm',
      'Electron diffraction evidence',
      'Nuclear density calculation',
      'Uniform nuclear density',
      // 3.8.1.6 Mass and energy
      'Mass-energy equivalence: E = mc²',
      'Atomic mass unit u',
      'Mass defect',
      'Binding energy',
      'Binding energy per nucleon',
      'Binding energy curve',
      'Most stable nuclei (iron peak)',
      'Fission and fusion energetics',
      // 3.8.1.7 Induced fission
      'Fission process',
      'Fission products',
      'Chain reaction',
      'Critical mass',
      'Control rods in reactors',
      'Moderator function',
      'Nuclear reactor components',
      'Fuel enrichment',
      // 3.8.1.8 Safety aspects
      'Radiation exposure and dose',
      'Biological effects of radiation',
      'Shielding and containment',
      'Nuclear waste disposal',
      'Half-life and waste management',
    ],
  },

  // ==========================================
  // PAPER 3 OPTIONAL TOPICS (Choose one)
  // ==========================================

  // Section 3.9: Astrophysics (Optional)
  {
    id: 'alevel-physics-astrophysics',
    name: 'Astrophysics (Optional)',
    description: 'Telescopes, stellar classification and cosmology',
    icon: '🔭',
    color: 'bg-purple-700',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 3 (Optional)',
    subtopics: [
      // 3.9.1 Telescopes
      'Astronomical refracting telescope',
      'Chromatic aberration',
      'Astronomical reflecting telescope',
      'Cassegrain arrangement',
      'Parabolic mirrors',
      'Resolving power: θ ≈ λ/D',
      'Rayleigh criterion',
      'Collecting power',
      'Charge-coupled devices (CCDs)',
      'Quantum efficiency of CCDs',
      'Radio telescopes',
      'Single dish and arrays',
      'Infrared, UV and X-ray telescopes',
      'Atmospheric absorption',
      'Space-based telescopes',
      // 3.9.2 Classification of stars
      'Apparent magnitude m',
      'Absolute magnitude M',
      'Magnitude equation: m - M = 5 log(d/10)',
      'Luminosity and brightness',
      'Inverse square law for intensity',
      'Stefan-Boltzmann law: L = 4πr²σT⁴',
      'Wien\'s displacement law: λmax T = constant',
      'Stellar spectra',
      'Spectral classes: O B A F G K M',
      'Temperature and spectral class',
      'Hertzsprung-Russell diagram',
      'Main sequence stars',
      'Red giants and supergiants',
      'White dwarfs',
      'Stellar evolution',
      'Supernova',
      'Neutron stars',
      'Black holes and event horizon',
      'Schwarzschild radius',
      // 3.9.3 Cosmology
      'Doppler effect for light',
      'Red shift and blue shift',
      'z = Δλ/λ = v/c',
      'Hubble\'s law: v = H₀d',
      'Hubble constant',
      'Age of universe estimate',
      'Big Bang theory',
      'Cosmic microwave background radiation',
      'Quasars',
      'Exoplanet detection methods',
      'Transit method',
      'Radial velocity method',
    ],
  },

  // Section 3.10: Medical Physics (Optional)
  {
    id: 'alevel-physics-medical',
    name: 'Medical Physics (Optional)',
    description: 'Physics of the eye, ear, and medical imaging techniques',
    icon: '🏥',
    color: 'bg-pink-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 3 (Optional)',
    subtopics: [
      // 3.10.1 Physics of the eye
      'Structure of the eye',
      'Optical power and the lens equation',
      'Power of a lens: P = 1/f',
      'Accommodation',
      'Near and far points',
      'Myopia and hypermetropia',
      'Corrective lenses',
      // 3.10.2 Physics of the ear
      'Structure of the ear',
      'Sound intensity and decibel scale',
      'I = P/A',
      'Intensity level: IL = 10 log(I/I₀)',
      'Threshold of hearing',
      'Frequency response of the ear',
      // 3.10.3 Biological measurement
      'ECG: principle and interpretation',
      'Heart signals and timing',
      // 3.10.4 Non-ionising imaging
      'Ultrasound production',
      'Piezoelectric effect',
      'Acoustic impedance: Z = ρc',
      'Reflection at boundaries',
      'A-scan and B-scan ultrasound',
      'Doppler ultrasound for blood flow',
      'Optical fibres in endoscopy',
      // 3.10.5 X-ray imaging
      'X-ray production',
      'X-ray spectra',
      'Attenuation: I = I₀e^(-μx)',
      'Linear attenuation coefficient',
      'Half-value thickness',
      'Contrast media',
      'Image intensifiers',
      'CT scanning principle',
      // 3.10.6 Radionuclide imaging
      'Gamma camera',
      'Technetium-99m as a tracer',
      'Half-life requirements for tracers',
      'PET scanning',
      'Annihilation and gamma detection',
      // 3.10.7 MRI scanning
      'Nuclear magnetic resonance principle',
      'Precession and Larmor frequency',
      'Relaxation times T1 and T2',
      'Gradient fields for imaging',
      'Advantages of MRI',
    ],
  },

  // Section 3.11: Engineering Physics (Optional)
  {
    id: 'alevel-physics-engineering',
    name: 'Engineering Physics (Optional)',
    description: 'Rotational dynamics, thermodynamics and heat engines',
    icon: '🔧',
    color: 'bg-slate-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 3 (Optional)',
    subtopics: [
      // 3.11.1 Rotational dynamics
      'Moment of inertia I',
      'I = Σmr² for point masses',
      'Standard I values for shapes',
      'Rotational kinetic energy: E = ½Iω²',
      'Angular momentum: L = Iω',
      'Conservation of angular momentum',
      'Torque: τ = Iα',
      'Rotational equations of motion',
      'Coupled systems',
      // 3.11.2 Thermodynamics
      'First law: ΔU = Q - W',
      'Internal energy change',
      'Work done by/on a gas',
      'W = pΔV for isobaric processes',
      'W = area under p-V curve',
      'Isothermal processes',
      'Adiabatic processes',
      'p-V diagrams',
      // 3.11.3 Heat engines and pumps
      'Heat engine cycles',
      'Carnot cycle',
      'Efficiency: η = 1 - Tc/Th',
      'Real engine efficiency',
      'Heat pumps and refrigerators',
      'Coefficient of performance',
      'Second law of thermodynamics',
      'Entropy',
    ],
  },

  // Section 3.12: Turning Points in Physics (Optional)
  {
    id: 'alevel-physics-turning-points',
    name: 'Turning Points in Physics (Optional)',
    description: 'Historical development of key physics concepts',
    icon: '📜',
    color: 'bg-amber-600',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 3 (Optional)',
    subtopics: [
      // 3.12.1 The discovery of the electron
      'Cathode rays',
      'Thomson\'s e/m experiment',
      'Millikan\'s oil drop experiment',
      'Determination of electron charge',
      // 3.12.2 Wave-particle duality
      'Newton\'s corpuscular theory',
      'Huygens\' wave theory',
      'Young\'s double slit experiment',
      'Electromagnetic theory of light',
      'Photoelectric effect evidence',
      'Einstein\'s photon explanation',
      'de Broglie hypothesis',
      'Electron diffraction evidence',
      // 3.12.3 Special relativity
      'Michelson-Morley experiment',
      'Postulates of special relativity',
      'Time dilation: t = γt₀',
      'Length contraction: L = L₀/γ',
      'Lorentz factor γ',
      'Mass-energy equivalence',
      'Relativistic momentum',
      'Evidence for time dilation (muons)',
    ],
  },

  // Section 3.13: Electronics (Optional)
  {
    id: 'alevel-physics-electronics',
    name: 'Electronics (Optional)',
    description: 'Analogue and digital electronics, operational amplifiers',
    icon: '🔌',
    color: 'bg-teal-500',
    examBoard: 'aqa',
    qualification: 'a-level',
    subject: 'physics',
    paperRestriction: 'Paper 3 (Optional)',
    subtopics: [
      // 3.13.1 Discrete semiconductor devices
      'Diode characteristics',
      'LED and photodiode',
      'Transistor as a switch',
      'Field effect transistors',
      // 3.13.2 Analogue electronics
      'Operational amplifier characteristics',
      'Infinite input impedance',
      'Zero output impedance',
      'Infinite open-loop gain',
      'Inverting amplifier: Vout/Vin = -Rf/Rin',
      'Non-inverting amplifier: Vout/Vin = 1 + Rf/Rin',
      'Summing amplifier',
      'Comparator',
      // 3.13.3 Digital electronics
      'Binary logic',
      'Truth tables',
      'Logic gates: AND, OR, NOT, NAND, NOR',
      'Combination of gates',
      'Bistable (flip-flop)',
      'Astable and monostable',
      'Schmitt trigger',
      'Analogue to digital conversion',
      'Sampling and resolution',
    ],
  },
];

// Helper functions
export function getAQAALevelPhysicsTopicById(id: string): Topic | undefined {
  return aqaALevelPhysicsTopics.find(topic => topic.id === id);
}

export function getAQAALevelPhysicsTopicsByPaper(paper: 1 | 2 | 3): Topic[] {
  return aqaALevelPhysicsTopics.filter(topic =>
    topic.paperRestriction?.includes(`Paper ${paper}`)
  );
}

export function getAQAALevelPhysicsOptionalTopics(): Topic[] {
  return aqaALevelPhysicsTopics.filter(topic =>
    topic.paperRestriction?.includes('Optional')
  );
}

export function countAQAALevelPhysicsSubtopics(): number {
  return aqaALevelPhysicsTopics.reduce((total, topic) => total + topic.subtopics.length, 0);
}
