'use client';

import React, { useState, forwardRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import { Question, Difficulty, Subject, ExamBoard, QualificationLevel } from '@/types';
import { PrintableQuestion } from './PrintableQuestion';
import { useSubscription } from '@/contexts/SubscriptionContext';
import Link from 'next/link';

interface PrintNext10QuestionsProps {
  topicId: string;
  subtopic: string;
  difficulty: Difficulty;
  subject: Subject;
  examBoard: ExamBoard;
  qualification: QualificationLevel;
  onGenerateQuestions: (count: number) => Promise<Question[]>;
}

interface PrintableWorksheetProps {
  questions: Question[];
  title: string;
  subtitle: string;
}

const PrintableWorksheet = forwardRef<HTMLDivElement, PrintableWorksheetProps>(
  ({ questions, title, subtitle }, ref) => {
    return (
      <div ref={ref} style={{ 
        background: 'white', 
        padding: '2cm',
        fontFamily: 'Times New Roman, serif',
        fontSize: '12pt',
        lineHeight: '1.5',
        color: 'black'
      }}>
        {/* Worksheet Header */}
        <div style={{ 
          borderBottom: '3px solid #000', 
          paddingBottom: '15pt', 
          marginBottom: '20pt',
          textAlign: 'center'
        }}>
          <h1 style={{ fontSize: '18pt', margin: '0 0 8pt 0', fontWeight: 'bold' }}>
            {title}
          </h1>
          <h2 style={{ fontSize: '14pt', margin: '0', fontWeight: 'normal', color: '#666' }}>
            {subtitle}
          </h2>
        </div>

        {/* Instructions */}
        <div style={{ 
          marginBottom: '20pt', 
          padding: '10pt', 
          border: '1px solid #ccc',
          backgroundColor: '#f9f9f9'
        }}>
          <p style={{ margin: '0', fontSize: '11pt' }}>
            <strong>Instructions:</strong> Answer all questions in the spaces provided. 
            Show all working where appropriate.
          </p>
        </div>

        {/* Questions */}
        {questions.map((question, index) => (
          <div key={index} style={{ 
            marginBottom: '30pt',
            pageBreakInside: 'avoid'
          }}>
            {/* Question Header */}
            <div style={{ 
              display: 'flex', 
              justifyContent: 'space-between', 
              alignItems: 'center',
              marginBottom: '10pt',
              borderBottom: '1px solid #ddd',
              paddingBottom: '5pt'
            }}>
              <h3 style={{ fontSize: '14pt', margin: '0', fontWeight: 'bold' }}>
                {index + 1}.
              </h3>
              <span style={{ fontSize: '10pt', fontWeight: 'bold' }}>
                [{question.marks || 1} mark{(question.marks || 1) !== 1 ? 's' : ''}]
              </span>
            </div>

            {/* Question Content */}
            <div style={{ 
              fontSize: '11pt', 
              lineHeight: '1.6', 
              marginBottom: '15pt' 
            }}>
              <div dangerouslySetInnerHTML={{ __html: question.content }} />
            </div>

            {/* Answer Space */}
            <div style={{ 
              border: '1px solid #ccc',
              minHeight: '60pt',
              padding: '10pt',
              backgroundColor: '#fafafa',
              marginBottom: '10pt'
            }}>
              <div style={{ minHeight: '50pt' }}></div>
            </div>
          </div>
        ))}

        {/* Footer */}
        <div style={{ 
          marginTop: '30pt',
          paddingTop: '15pt',
          borderTop: '1px solid #ddd',
          textAlign: 'center',
          fontSize: '10pt',
          color: '#666'
        }}>
          <p style={{ margin: '0' }}>
            Generated by Past Papers - www.past-papers.co.uk
          </p>
        </div>
      </div>
    );
  }
);

PrintableWorksheet.displayName = 'PrintableWorksheet';

export function PrintNext10Questions({ 
  topicId, 
  subtopic, 
  difficulty, 
  subject, 
  examBoard, 
  qualification,
  onGenerateQuestions 
}: PrintNext10QuestionsProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [showWorksheet, setShowWorksheet] = useState(false);
  const { tier, hasFeature } = useSubscription();

  const printRef = React.useRef<HTMLDivElement>(null);

  // Check if user can print worksheets
  const canPrintWorksheets = hasFeature('print_worksheets');

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: `${subtopic} - Practice Questions`,
    onAfterPrint: () => {
      setShowWorksheet(false);
      setQuestions([]);
    },
  });

  const generateAndPrint = async (count: number = 10) => {
    setIsGenerating(true);
    try {
      const generatedQuestions = await onGenerateQuestions(count);
      setQuestions(generatedQuestions);
      setShowWorksheet(true);
      
      // Give React time to render
      setTimeout(() => {
        handlePrint();
      }, 200);
      
    } catch (error) {
      console.error('Failed to generate questions:', error);
      alert('Failed to generate questions. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Show upgrade prompt for free users
  if (!canPrintWorksheets) {
    return (
      <div className="p-4 bg-gradient-to-r from-purple-500/10 to-blue-500/10 border border-purple-500/20 rounded-lg">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="font-medium text-[var(--color-text-primary)] mb-1">
              🔒 Print Question Worksheets
            </h4>
            <p className="text-sm text-[var(--color-text-secondary)]">
              Generate and print 5-10 questions as professional worksheets with answer spaces
            </p>
          </div>
          <Link
            href="/pricing"
            className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-lg font-medium flex items-center gap-2 transition-colors text-sm"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
            </svg>
            Upgrade to {tier === 'free' ? 'Student Plus' : 'Exam Pro'}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="flex items-center gap-3">
        <button
          onClick={() => generateAndPrint(5)}
          disabled={isGenerating}
          className="px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-green-400 text-white rounded-lg font-medium flex items-center gap-2 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          {isGenerating ? 'Generating...' : 'Print 5 Questions'}
        </button>

        <button
          onClick={() => generateAndPrint(10)}
          disabled={isGenerating}
          className="px-4 py-2 bg-purple-600 hover:bg-purple-700 disabled:bg-purple-400 text-white rounded-lg font-medium flex items-center gap-2 transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          {isGenerating ? 'Generating...' : 'Print 10 Questions'}
        </button>
      </div>

      {/* Hidden worksheet for printing */}
      {showWorksheet && questions.length > 0 && (
        <div style={{ position: 'absolute', left: '-9999px', top: '-9999px' }}>
          <PrintableWorksheet
            ref={printRef}
            questions={questions}
            title={`${subtopic} Practice Questions`}
            subtitle={`${examBoard.toUpperCase()} ${qualification.toUpperCase()} ${subject} - ${difficulty} Level`}
          />
        </div>
      )}
    </>
  );
}