'use client';

import Link from 'next/link';
import { useAuth } from '@/contexts/AuthContext';

const features = [
  {
    icon: '🎯',
    title: 'Choose Your Topics',
    description: 'Select specific topics to focus on. Target your weak areas or revise everything - you decide what goes in your paper.',
  },
  {
    icon: '📊',
    title: 'Set Difficulty Mix',
    description: 'Adjust the balance of easy, medium, and hard questions. Build confidence or challenge yourself with exam-level difficulty.',
  },
  {
    icon: '✅',
    title: 'Instant Mark Schemes',
    description: 'Every paper comes with detailed mark schemes and worked solutions. Self-mark your answers and learn from mistakes.',
  },
  {
    icon: '📚',
    title: 'All Exam Boards',
    description: 'Full support for AQA, Edexcel, and OCR. Questions match your specific exam board style and format.',
  },
  {
    icon: '🔄',
    title: 'Unlimited Papers',
    description: 'Generate as many practice papers as you need. Never run out of revision material before your exams.',
  },
  {
    icon: '⚡',
    title: 'AI-Powered Quality',
    description: 'Questions generated by AI trained on real exam papers. Authentic style, accurate content, proper mark allocation.',
  },
];

const subjects = [
  { name: 'Maths', icon: '📐', href: '/gcse/maths/aqa/paper' },
  { name: 'Physics', icon: '⚡', href: '/gcse/physics/aqa/paper' },
  { name: 'Chemistry', icon: '🧪', href: '/gcse/chemistry/aqa/paper' },
  { name: 'Biology', icon: '🧬', href: '/gcse/biology/aqa/paper' },
  { name: 'Computer Science', icon: '💻', href: '/gcse/computer-science/aqa/paper' },
  { name: 'Economics', icon: '📈', href: '/a-level/economics/aqa/paper' },
];

const steps = [
  {
    step: 1,
    title: 'Choose Subject & Board',
    description: 'Select your subject, exam board, and qualification level (GCSE or A-Level).',
  },
  {
    step: 2,
    title: 'Pick Your Topics',
    description: 'Select which topics to include. Focus on areas you need to practice most.',
  },
  {
    step: 3,
    title: 'Configure Difficulty',
    description: 'Set the mix of easy, medium, and hard questions. Choose your total marks.',
  },
  {
    step: 4,
    title: 'Generate & Practice',
    description: 'Get your paper instantly. Answer questions, then self-mark with the mark scheme.',
  },
];

export default function PaperGeneratorContent() {
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-[#0a0a0a]">
      {/* Header */}
      <header className="border-b border-white/[0.06] bg-[#0a0a0a]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="text-xl font-semibold text-white">
              Past Papers
            </Link>
            <div className="flex items-center gap-4">
              {user ? (
                <>
                  <Link
                    href="/past-papers"
                    className="text-white/60 hover:text-white transition-colors"
                  >
                    Browse Papers
                  </Link>
                  <Link
                    href="/dashboard"
                    className="bg-white text-[#0a0a0a] px-4 py-2 rounded-lg font-medium hover:bg-white/90 transition-colors"
                  >
                    Dashboard
                  </Link>
                </>
              ) : (
                <>
                  <Link
                    href="/login"
                    className="text-white/60 hover:text-white transition-colors"
                  >
                    Sign in
                  </Link>
                  <Link
                    href="/signup"
                    className="bg-white text-[#0a0a0a] px-4 py-2 rounded-lg font-medium hover:bg-white/90 transition-colors"
                  >
                    Get Started
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </header>

      <main>
        {/* Hero Section */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <div className="text-center">
            <div className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/20 rounded-full px-4 py-2 mb-6">
              <span className="text-blue-400 text-sm font-medium">Student Plus Feature</span>
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white mb-6">
              Generate Custom
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400">
                Practice Papers
              </span>
            </h1>
            <p className="text-xl text-white/60 max-w-2xl mx-auto mb-8">
              Create unlimited GCSE and A-Level mock exams tailored to your needs.
              Choose topics, set difficulty, and get instant mark schemes.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href={user ? '/past-papers' : '/signup'}
                className="w-full sm:w-auto px-8 py-4 bg-blue-500 text-white rounded-xl font-medium hover:bg-blue-600 transition-colors text-center"
              >
                {user ? 'Create a Paper' : 'Get Started'}
              </Link>
              <Link
                href="/pricing"
                className="w-full sm:w-auto px-8 py-4 bg-white/[0.06] text-white rounded-xl font-medium hover:bg-white/[0.1] transition-colors text-center"
              >
                View Pricing
              </Link>
            </div>
            <p className="text-sm text-white/40 mt-4">
              3 papers per week with Student Plus
            </p>
          </div>
        </section>

        {/* Demo Preview */}
        <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
          <div className="bg-[#111] border border-white/[0.06] rounded-2xl p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-6">
              <div className="w-3 h-3 rounded-full bg-red-500/60" />
              <div className="w-3 h-3 rounded-full bg-yellow-500/60" />
              <div className="w-3 h-3 rounded-full bg-green-500/60" />
              <span className="ml-4 text-white/40 text-sm">Paper Builder</span>
            </div>

            <div className="grid sm:grid-cols-3 gap-4 mb-6">
              <div className="bg-white/[0.03] rounded-xl p-4 border border-white/[0.08]">
                <div className="text-white/40 text-sm mb-1">Subject</div>
                <div className="text-white font-medium">GCSE Maths</div>
              </div>
              <div className="bg-white/[0.03] rounded-xl p-4 border border-white/[0.08]">
                <div className="text-white/40 text-sm mb-1">Exam Board</div>
                <div className="text-white font-medium">AQA</div>
              </div>
              <div className="bg-white/[0.03] rounded-xl p-4 border border-white/[0.08]">
                <div className="text-white/40 text-sm mb-1">Total Marks</div>
                <div className="text-white font-medium">80 marks</div>
              </div>
            </div>

            <div className="mb-6">
              <div className="text-white/60 text-sm mb-3">Topics Selected</div>
              <div className="flex flex-wrap gap-2">
                {['Algebra', 'Geometry', 'Statistics', 'Number'].map(topic => (
                  <span key={topic} className="px-3 py-1.5 bg-blue-500/20 border border-blue-500/30 rounded-lg text-blue-400 text-sm">
                    {topic}
                  </span>
                ))}
              </div>
            </div>

            <div className="mb-6">
              <div className="text-white/60 text-sm mb-3">Difficulty Mix</div>
              <div className="flex h-3 rounded-full overflow-hidden">
                <div className="bg-green-500 w-[30%]" />
                <div className="bg-yellow-500 w-[50%]" />
                <div className="bg-red-500 w-[20%]" />
              </div>
              <div className="flex justify-between mt-2 text-xs text-white/40">
                <span>30% Easy</span>
                <span>50% Medium</span>
                <span>20% Hard</span>
              </div>
            </div>

            <button className="w-full py-4 bg-blue-500 text-white rounded-xl font-medium">
              Generate Paper
            </button>
          </div>
        </section>

        {/* Features Grid */}
        <section className="bg-[#111] border-y border-white/[0.06] py-16 sm:py-24">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-bold text-white mb-4">
                Everything You Need for Exam Success
              </h2>
              <p className="text-white/60 max-w-2xl mx-auto">
                Our paper generator gives you complete control over your revision material
              </p>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {features.map((feature, index) => (
                <div
                  key={index}
                  className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-6"
                >
                  <div className="text-3xl mb-4">{feature.icon}</div>
                  <h3 className="text-lg font-semibold text-white mb-2">{feature.title}</h3>
                  <p className="text-white/60 text-sm">{feature.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How It Works */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-white mb-4">How It Works</h2>
            <p className="text-white/60 max-w-2xl mx-auto">
              Create your first practice paper in under a minute
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((item) => (
              <div key={item.step} className="relative">
                <div className="text-6xl font-bold text-white/[0.05] absolute -top-4 left-0">
                  {item.step}
                </div>
                <div className="relative pt-8">
                  <h3 className="text-lg font-semibold text-white mb-2">{item.title}</h3>
                  <p className="text-white/60 text-sm">{item.description}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Popular Subjects */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 sm:pb-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-white mb-4">Popular Subjects</h2>
            <p className="text-white/60">Jump straight into creating a paper</p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {subjects.map((subject) => (
              <Link
                key={subject.name}
                href={subject.href}
                className="flex items-center gap-4 bg-[#111] border border-white/[0.06] rounded-xl p-5 hover:border-white/[0.12] transition-colors group"
              >
                <span className="text-3xl">{subject.icon}</span>
                <div>
                  <div className="text-white font-medium group-hover:text-blue-400 transition-colors">
                    {subject.name}
                  </div>
                  <div className="text-white/40 text-sm">Create paper</div>
                </div>
                <svg className="w-5 h-5 text-white/20 ml-auto group-hover:text-blue-400 transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </Link>
            ))}
          </div>

          <div className="text-center mt-8">
            <Link
              href="/past-papers"
              className="text-blue-400 hover:text-blue-300 transition-colors"
            >
              View all subjects and exam boards →
            </Link>
          </div>
        </section>

        {/* CTA Section */}
        <section className="bg-gradient-to-r from-blue-500/10 to-purple-500/10 border-y border-white/[0.06] py-16">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 className="text-3xl font-bold text-white mb-4">
              Ready to Start Practicing?
            </h2>
            <p className="text-white/60 mb-8 max-w-xl mx-auto">
              Join thousands of students using AI-generated practice papers to ace their exams.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link
                href={user ? '/past-papers' : '/signup'}
                className="w-full sm:w-auto px-8 py-4 bg-blue-500 text-white rounded-xl font-medium hover:bg-blue-600 transition-colors"
              >
                {user ? 'Create Your Paper' : 'Get Started Free'}
              </Link>
              <Link
                href="/pricing"
                className="w-full sm:w-auto px-8 py-4 bg-white/[0.06] text-white rounded-xl font-medium hover:bg-white/[0.1] transition-colors"
              >
                View Pricing
              </Link>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-white/[0.06] py-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-white/40 text-sm">
          <p>&copy; {new Date().getFullYear()} Past Papers. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
